### PR TITLE
Fulpstation Misc Sprites

### PR DESCRIPTION
**Pull request by GhostActual**
Ports some miscellaneous sprites from Fulpstation. Those are listed below.

-Plastic Flaps
-Crematorium
-Morgue
-Notice Board

I did this in less than five minutes.

### CODE REVIEW

**Comment by Very-Soft** [comment]
I love most of these, the only one I'm not crazy about is the plastic flaps, looks like it loses any kind of transparency, which I think is good for plastic flaps.

**Comment by GhostActual** [comment]
> I love most of these, the only one I'm not crazy about is the plastic flaps, looks like it loses any kind of transparency, which, transparency I think is good for plastic flaps.

Those actually do have some transparency - I found that the DMI comparer has issues with displaying alpha levels for whatever reason

**Comment by Arokha** [comment]
Why replace green light morgue with yellow light morgue when you have a green light morgue sprite too?

**Comment by GhostActual** [comment]
> Why replace green light morgue with yellow light morgue when you have a green light morgue sprite too?

Fixed

**Comment by KasparoVy** [comment]
RIP blinky green morgue light, that was actually useful and eyecatching

Sprites look great

**Comment by Arokha** [comment]
> RIP blinky green morgue light, that was actually useful and eyecatching
> 
> Sprites look great

Maybe a quick 2 frame animation can be done to add blinky?

**Comment by GhostActual** [comment]
> > RIP blinky green morgue light, that was actually useful and eyecatching
> > Sprites look great
> 
> Maybe a quick 2 frame animation can be done to add blinky?

*scream*

**Pull request merged**
