### PR TITLE
Adds Female tajara sprite back to the game.

### PR DESCRIPTION
**Pull request by Dhaeleena**
Adds Female tajaran sprite back to the game. Resolves Issue #629  Thank @DeepIndigo for the sprites.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
I feel like we should kick this back up to Polaris ASAP.

**Comment by Dhaeleena** [comment]
I have updated this. I added the Deform variant for the female body so the pack is now complete (Clone damage sprite)

**Comment by Arokha** [comment]
> I feel like we should kick this back up to Polaris ASAP.

They do not want it.

**Comment by SpadesNeil** [comment]
Kay.

**Pull request merged**
