### PR TITLE
The clime offices

### PR DESCRIPTION
**Pull request by SweetBlueSylveon**
-Expands Trash Maint
-Gives Clown an office in Trashmaint
-Gives Mime an office in Trashmaint
-Adds 2 new pets
-Adds a new language "Coulrian", which requires a clown whitelist to use.
-Adds a Clown and Mime storage closet
-Gives the Clown and Mime a roundstart spawn. This also allows people to see that those roles are in fact something you can play if you get whitelisted.
-Adds a secret area
I am not posting certain images due to not wanting to highlight certain bits on the github.
image
image
image

### CODE REVIEW

**Comment by Heroman3003** [comment]
Roundstart powertool in maint?

**Comment by SweetBlueSylveon** [comment]
I see the issue

> Roundstart powertool in maint?

Yeah that's probably a bit much. I'll take that our when I resolve the issues.

**Comment by Heroman3003** [comment]
Other than that... the thing that jumps into my eyes is that areas seem a bit wonky. Particularly tiny bit of area into mime office above the ladder, and the way the area switches mid-room in maint to the right of the Substation.

**Comment by SweetBlueSylveon** [comment]
> Other than that... the thing that jumps into my eyes is that areas seem a bit wonky. Particularly tiny bit of area into mime office above the ladder, and the way the area switches mid-room in maint to the right of the Substation.

You say that, but the one continuous path here wasn't changed. That's just how it is already. Both the clown and the mime have 2 doors and a wall entry point to their offices. Meaning that everyones' general ability to go through that area smoothly has not been affected, and the clowns and mimes who'll reside there have extra options.

**Comment by Heroman3003** [comment]
> 
> 
> > Other than that... the thing that jumps into my eyes is that areas seem a bit wonky. Particularly tiny bit of area into mime office above the ladder, and the way the area switches mid-room in maint to the right of the Substation.
> 
> You say that, but the one continuous path here wasn't changed. That's just how it is already. Both the clown and the mime have 2 doors and a wall entry point to their offices. Meaning that everyones' general ability to go through that area smoothly has not been affected, and the clowns and mimes who'll reside there have extra options.
> In addition, the idea is that the Clown/Mime union bargained for offices, so Nanotrasen spited them by putting them in an inconvenient and garbage filled place.

I don't mean the pathing. I mean the mechanical 'areas'. That determine the lines for the edges of rooms, for coverage of APCs, etc.

**Comment by SweetBlueSylveon** [comment]
Latest commit:
-Cleaned up the areas, removed the power drill, added a special function for the two pets.

**Pull request merged**
