### PR TITLE
[MIRROR] Bioprinters and Cloners now use Biomass reagent, maps in a Bioprinter

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/5355
--------------------
Adds a new reagent called `biomass`, which is made from protein, sugar, and phoron.
- The Cloner now uses liquid biomass for clones, rather than meat. The one on the map starts out full, with three bottles of biomass, but its capacity can be increased simply by replacing the beakers with larger ones. As always, Science is your friend if you want the really, really silly stuff.
- Bioprinters now use liquid biomass to print limbs. Like the Cloner, it starts with a full bottle of biomass, and its capacity can be increased by getting a bigger beaker.

Biomass, and by extension the Bioprinter, is deliberately far more costly in materials than the Prosthetics Fabricator, as part of the compromise that gets the Bioprinter  added to the map. The cloner is also more expensive now, but the presence of defibrillators means that cloning occurs far less often, and the noticeable change should be relatively minor.

Aro: Increased biomass return rate on reactions by 600% for the purpose of nomfs

### CODE REVIEW

**Comment by Arokha** [comment]
Resleeving UI needs to get the amount of biomass for display using a different proc now.

**Comment by TheDavestDave** [comment]
can chemistry make protien? Otherwise chemistry can't make their own biomass?

**Comment by Arokha** [comment]
Can just scrape it out of ye olde synthmeat I would imagine.

**Comment by Natje0** [comment]
Please no

**Comment by Arokha** [comment]
Discussed in medical, Temp was going to change another number to make it more reasonable after merge

**Pull request merged**
