### PR TITLE
Dragon sprite bugfix

### PR DESCRIPTION
**Pull request by Cameron653**
- Adds in reddragon-2 sprite to prevent sprite from bugging out when dragon eats 2 people

### CODE REVIEW

**Comment by JoanRisu** [comment]
This also fixes #1247.

**Comment by Cameron653** [comment]
Went ahead and made it so when this is merged it'll autoclose #1247

**Comment by JoanRisu** [comment]
Ooooh, how does that work.

**Comment by Cameron653** [comment]
Pretty much when you're initially committing a change, you write down "fixes #(issue number)" or "resolves #(issue number)"

You can click the little information bubble on #1247 and it'll explain it more in depth, but that's pretty much it.

**Comment by Arokha** [comment]
I split your issue fix into another branch on your repo, where you can make a PR if you want, but it's basically going to get reviewed by me to say it's a pointless change.

**Pull request merged**
