### PR TITLE
Gives Reasonable Species Brutal Predation

### PR DESCRIPTION
**Pull request by Cameron653**
- Gives Xenohybrids Brutal Predation, because they have sharp teeth and claws.
- Gives Teshari Brutal Predation, since they also have sharp teeth and claws.
- Gives Unathi Brutal Predation, ditto
-  Gives Tajaran Brutal Predation , ditto
- Gives Vox Brutal Predation, ditto.
- Gives Flatland Zorren Brutal Predation
- Gives Highland Zorren Brutal Predation
- Gives Vulpakins Brutal Predation

Forgot to give these species the verb when I was initially adding in Brutal Predation

### CODE REVIEW

**Comment by Dhaeleena** [comment]
how many species have this by this point?

**Comment by Cameron653** [comment]
Sergal, Akula, and custom species.

Hmm... Thinking about it, I should also give Tajaran it.

**Comment by Cameron653** [comment]
Alright. Checked all the species edited to make sure their verbs weren't accidentally overwritten.

**Comment by Cyantime** [comment]
Why not just give it to everyone at this point?

**Comment by SpadesNeil** [comment]
That's just it. I don't want everything to have it. D:

**Comment by SpadesNeil** [comment]
But, that is just me, hence the tag.

**Comment by LittleBigKid2000** [comment]
Why not give it to Vulpkanin? They have sharp teeth and claws, too.

**Comment by Cameron653** [comment]
Whoops, forgot about vulp.

Also, @SpadesNeil The verb is intended to be for scenes, not an actual mechanical feature to be used & whatnot. If someone does a HV scene as a species, like xenohybrid and then wants to actually mechanically take a limb/organ out without having to use a hatchet or whatever, this makes it easy.

There's so many restrictions on it that it makes it completely non-viable for abuse.

**Comment by SpadesNeil** [comment]
Eh good point.

**Comment by Cameron653** [comment]
Hmm. I'll need to give Promethean their own custom shred limb verb sometime where they actually turn the limb to goop instead of removing it, but that's for another time.

This PR is ready for merge.

**Comment by SpadesNeil** [comment]
Let's not give Prometheans any such thing please. Else it's literally just humans, Diona, and Skrell who don't have brutal predation, and that is silly.

**Comment by Cameron653** [comment]
Mm, very well.
~~PR is ready for merge aaahhh~~

**Pull request merged**
