### PR TITLE
Adds a coffee maker to the bar.

### PR DESCRIPTION
**Pull request by DigitalSquirrel95**
Adds a coffee machine to the bar.  Things that were where it is now were moved to the back room.

### CODE REVIEW

**Comment by Novacat** [comment]
I am not really sure how this will stop people from stealing the coffee dispenser? Though, I think a better solution might be to just add a coffee dispenser to the bar.

**Comment by DigitalSquirrel95** [comment]
These three cartridges are the main reasons people steal the coffee maker in the first place.  Adding them should prevent the issue entirely.

**Review by Novacat — CHANGES_REQUESTED** [review]
Rather than changing the dispenser itself, can you just map in another coffee dispenser to the bar, please?

**Comment by DigitalSquirrel95** [comment]
> 
> 
> Rather than changing the dispenser itself, can you just map in another coffee dispenser to the bar, please?

Uhhh gimme a bit to learn how to map and I'll see what I can do.

**Review by Novacat — APPROVED** [review]

**Pull request merged**
