### PR TITLE
[MIRROR] Kaleidoscope 2: The Retabbening

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/7697
--------------------
https://github.com/PolarisSS13/Polaris/pull/7608 but in a non-conflicting tab.

### CODE REVIEW

**Comment by KasparoVy** [comment]
:O really glad I saw this notification. Will have to change something I'm working on

**Comment by KasparoVy** [comment]
Oh shit, so wait-- does this mean all future sprite/asset additions should 100% be done upstream in non-vr files since they use it for "event purposes" and such?

Sounds like a workflow change, happy to accommodate.

**Comment by Novacat** [comment]
I am not really certain of what to think of this. I am fairly shocked that Polaris took the step to integrate such a huge part of Virgo into their codebase. I am going to have to go through the files one by one and see all of what was integrated, and what was left out, but it will likely result in a huge reduction in _vr files.

**Comment by KasparoVy** [comment]
Sounds good, thanks
Not sure where we draw the line now on what goes to Polaris and what doesn't but I'm sure they'll enjoy the new assets

**Comment by Verkister** [comment]
I'd recommend keeping most of our stuff in our own files in case of dmi edits and additions and vorestation specific features.

**Comment by Novacat** [comment]
Does not runtime, seems to load existing characters all right.

**Pull request merged**
