### PR TITLE
Disables stumbling into blast doors opening them.

### PR DESCRIPTION
**Pull request by Cyantime**
Also firelocks, basic mineral doors, etc.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
We really ought to send this to Polaris to fix.

**Comment by Cyantime** [comment]
This is unique to vorestation

**Comment by SpadesNeil** [comment]
Is it? Wait, then what do we use stumbling for? I'd swear that was a drunk feature in Polaris.

**Comment by SpadesNeil** [comment]
Nevermind I'm dumb

**Pull request merged**
