### PR TITLE
Aro shipself v3

### PR DESCRIPTION
**Pull request by Arokha**
- [x] Spare lights
- [x] Soft nameplate
- [x] Diagonal walls?
- [x] Autolok instead of elockers

### CODE REVIEW

**Comment by Novacat** [comment]
Beacon stuff should probably be kicked to polaris.

**Comment by KasparoVy** [comment]
Happy to see you working on this again! Shipself mad cool.

**Comment by KillianKirilenko** [comment]
Brace for innuendo.

**Comment by SigholtStarsong** [comment]
I can't wait to get inside.

**Comment by Arokha** [comment]
Polaris parts in https://github.com/PolarisSS13/Polaris/pull/8112

**Pull request merged**
