### PR TITLE
Adds more winter coats + moves existing winter coats to the same file

### PR DESCRIPTION
**Pull request by PastelPrinceDan**
It's pretty much constantly winter, and a lot of heads or misc roles don't have winter coats. This remedies that, and adds a bunch more civilian coats as well.

- Adds several winter coats, ported from Citadel - all available in loadout.
- Moves science and medical winter coats from loadout_suit_vr to loadout_suit
- Move the SaR winter coat files from southern cross map files to files where other coats are

Coats added:
- Heads: Head of Personnel, Head of security, Chief Engineer, Research Director, Chief Medical Officer, Quartmaster
- Science: roboticist
- Service: bartender, janitor
- Medical: alternative medical coat, virologist, paramedic, chemist
- Civilian: assistant formal, runed, brassy, cosmic

image

### CODE REVIEW

**Review by Novacat — CHANGES_REQUESTED** [review]
Since these are touching Polaris files they should probably be sent to Polaris, since Polaris has not gone downstream of Virgo (yet)

**Comment by dwinters99** [comment]
PastelPrinceDan has asked me to send this upstream for them, will edit this comment with the link when it is done.

**Review by Novacat — APPROVED** [review]

**Comment by Leshana** [comment]
Woah! Coats!

**Comment by Hatterhat** [comment]
good job champ i'm proud of you

**Pull request merged**
