### PR TITLE
adds food cubes.

### LINKED ISSUE #6063: [Oversight] Grubshake
#### Brief description of the bug
Grubshake chemical reaction is coded in but no reagent to go with in, resulting in disappeared reagents after the reaction occurs.

#### What you expected to happen
A drink to drink after mixing shockchem/200V and water together.

#### What actually happened
Poof! All gone!

#### Steps to reproduce
- (Step 1) Get grubs gibbed for their shockchem/200V
- (Step 2) Mix it with water
- (Step 3) Weep as it all goes away without making a drink to guzzle down.

#### Code Revision
Server revision: release - 
3f69d0b02ece9ef926a3496893049a02a86956b2 

#### Anything else you may wish to add:
`/datum/chemical_reaction/drinks/grubshake
	name = "Grub protein drink"
	id = "grubshake"
	result = "grubshake"
	required_reagents = list("shockchem" = 5, "water" = 25)
	result_amount = 30`
This is all there is right now. There's no reagent to go with it in https://github.com/VOREStation/VOREStation/blob/44ae320b95ada292de82c3adbe89b31b89d70ce7/code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks_vr.dm
Incidentally, this discovery came up on a downstream server where I checked and found this thing out. I could easily code this in but I'm a little unsure on what it should be worded as for the descriptions involved for the glass as well as the flavour text.

### LINKED ISSUE #6402: sharkchunk turns into untextured sharkmeat when cut.
#### Brief description of the bug
The item 'chunk of shark meat', or `/obj/item/weapon/reagent_containers/food/snacks/sliceable/sharkchunk`, spawns a 
 `/obj/item/weapon/reagent_containers/food/snacks/sharkmeat`, which is an untextured item called 'snack' in-game, even though it should probably spawn `/obj/item/weapon/reagent_containers/food/snacks/carpmeat/fish/sharkmeat`, which is a textured item called 'slice of sharkmeat.'
I think this is an issue with [https://github.com/VOREStation/VOREStation/pull/6360/commits/15c1c45b342cffb0ed386de90cb53ed32567e136](url) conflicting with the earlier code of the PR.

#### What you expected to happen
Using a sharp object on chunk of shark meat spawns some sharkmeat.

#### What actually happened
Using a sharp object on chunk of shark meat spawns an untextured version of sharkmeat, that for some reason seems to have more protein and nutrient than the textured sharkmeat. Maybe it's the default nutriment values for default snacks.

#### Steps to reproduce
- Use shark object on chunk of shark meat, obtained from butchering or gibbing measel sharks.

#### Code Revision
- 880fe39160f2257eadf18be08b7796cc5858f402
 
#### Anything else you may wish to add:
- I figure I might be able to work on this if ye need help, though I'd need to look into it more. Also this is me first issue I've made, lemme know if I've made any mistakes.

### PR DESCRIPTION
**Pull request by Ketrai**
Adds food cubes, details in #6389 

also fixed a bug with sharkmeat, and fixes grubshakes. resolves #6402 and resolves #6063

Someone else can map in the vending machine for MEDICAL*, I'm not risking the conflict potential. So it's removed in this pr.

Please for the love of god merge this before I have an aneurism.

### CODE REVIEW

**Comment by Ketrai** [comment]
I also made the cargo crate dispense a whole filled vending machine because someone complained they were too expensive. Now you effectively get 160 cubes, 320 if hacked for 75 points. As opposed to 80.

**Comment by TheFurryFeline** [comment]
As before, I suggest you edit your post to have the keyword `resolves #6063` so it automatically closes when this PR's merged.

**Comment by Ketrai** [comment]
@Novacat I mean, I chose virus food because both medical and the chef have access to it. Figured it'd be neat if people can ask the chef for a refill or custom shakes for expeditions should they want to. 

Medical has a fitness vendor, you can just take a milk carton from it and combine it with water. You get **30** virus food from just a little bit of milk and water. Which is enough to use **6** whole cubes.

**Comment by Ketrai** [comment]
Added a recipe for food cubes too. 20 enzyme, 15 nutriment & protein, 5 virus food. For a whole tray. Yes it's a lot of gain, but it's very labour intensive to make. Enzyme IS renewable, you can grow stingfruit. Or whatever it's called. They have 5 enzyme each.

**Pull request merged**
