### PR TITLE
Adds Suffocation Damage option to vore panel/bellies

### PR DESCRIPTION
**Pull request by Heroman3003**
Has higher damage cap of 12 to account for natural regeneration countering up to 5 damage per second. Suffocation-based damage only provides half as much nutrition as burn/brute.

Unlike other two, default damage value is 0.

### CODE REVIEW

**Comment by Wickedtemp** [comment]
I cannot put into words how much I **don't** want this.

If medical sees rising oxy on sensors, that tends to send off alarm bells. If their location's in the dorms then that's one thing, but if it's **anywhere else**, or if tracking is **off**, then I'm rushing to their location or trying my hardest to locate them because I'm thinking someone's got a ruptured lung somehow or left their internals on and ran out of air, and it's probably going to irritate people when I bust into their scene. It'll also irritate _me._

You pass out at 40 oxy. So you can't reply to a PDA or NIF message at that point so I can't verify if it's a scene or not. This is really going to fuck with medical players. This is going to lead to medical breaking into areas with the hardsuit and/or calling for emergency access into non-dorm areas if it isn't confirmed that its a scene. It's going to be fucking awkward and I really do not think this is a good idea. 

Also these values may be inaccurate because Heroman asked me for info regarding the natural 'heal rate' of oxy damage at like 1am last night, and I told them:

 ""think around 5 per tick? 's hard to really say because private servers never process that stuff correctly on my end, but you'll want to test this for yourself somehow before acting on this. a more accurate answer is "I can't really tell on a private server because its fucky" and "you'd be better off asking an admin to put 40 oxy on a printed sleeve and testing that way""

So unless this was tested after the fact, it would need further tweaking.

**Comment by TheFurryFeline** [comment]
> Edit:
> If damaging vore panel modes automatically disable suit sensors, then that'd actually fix all of the above issues, and also probably lead to improvements overall because endo-only Medical wouldn't have to watch vore snuff scenes on sensors and other newer Medical wouldn't be freaking out over other digestion damage. I say 'damaging modes' in particular because I wouldn't want healbelly to be affected - it...actually kind of relies on sensors being on because there's no other way to check to see if the patient's actually improving. The only other issues I see this potentially causing would be in cases of npc mob vore, but I think it'd be an overall net positive.
> Edit2: As far as resleeving concerns after the fact, if sensors are automatically set to Binary instead of straight Off, Medical would be able to see the 'deceased' for a split second before it disappears, letting them know a resleeving's coming up, if they're paying attention. But, 'Off' works as well because there's a transcore notif.

I support these ideas, however, it would have to be added to a followup PR. Being one who'd like this kind of thing for stuff like boob smothers and the like, I see the appeal of this, but agree with Mlempest about how it's gonna frak up Medical mains and how to interpret what's a scene in an OOC mindset and thus something to paw-wave off.

**Comment by Wickedtemp** [comment]
(I know, this isn't for this PR and its something to be done in its own PR, **preferably before this one is merged** buuuuut)
- Damaging belly disables/de-activates/sets-to-binary-or-off/hides/conceals-in-some-way, suit sensors
_Just damaging, because there's no issue with endo/absorb/etc and healbelly actually kinda relies on suit sensors, else you can't tell if they're healing or not_
And this would accomplish the following:
- Medical players who don't like digestion/death scenes no longer have to look at it all the time
- People who do like digestion/death scenes no longer have to deal with Medical PDA-ing them and shit
- Might cause issues with vore mobs and stuff but eh its an overall net positive
- Also means above PR's can just be accepted because medical's not going to see it and won't potentially freak out. Like, you could even throw in toxin damage too at that point.
-also on a side note this means it won't be a guessing game of "digestion set to 6 brute or being mauled by a mob/running into walls? Scene with 6 burn or are they on fire or overheating?" which is a question I kinda have to ask because FurryFeline's synth character was actually burning to death due to overheating in engineering's lobby and I only did a walk-by because it was close and I was expecting it to be a scene anyway and turns out they totes would've burned.

**Comment by TheFurryFeline** [comment]
>   -also on a side note this means it won't be a guessing game of "digestion set to 6 brute or being mauled by a mob/running into walls? Scene with 6 burn or are they on fire or overheating?" which is a question I kinda have to ask because FurryFeline's synth character was actually burning to death due to overheating in engineering's lobby and I only did a walk-by because it was close and I was expecting it to be a scene anyway and turns out they totes would've burned.

_coughs in totally not embarrassed_ Y-yeah, that was a bit embarrassing on my part, lmao. Was in my earlier days of playing borg/synth and forgot to just take off voidsuit after working in it, but thought I'd be fine charging while saving power with the suit cooler turned off. Big mistake and lessons learned.

**Comment by Torque4607** [comment]
Another medmain here (Echo-016). This is not a good idea. Suffocation damage always has been and always will be the key indicator of "This person needs help **NOW**." Making it so suffocation can also be during vore will make medical even more miserable when it comes to guessing if somebody's being vored or if it's an actual emergency. Oxyloss as a vore option _will lead to many, many times when medical breaks in and interrupts a scene._ This is simply a fact based on how we actually play the department. Oxyloss damage is the biggest red flag when it comes to initiating rescue efforts. I cannot argue against this enough. Forgive me if I'm being short-sighted here but I can't see any way in which anybody would need suffocation damage as part of their mechanical scene augmentations. And it is especially not worthwhile at the cost of medical's biggest tool for recognizing an emergency situation and saving someone from being sent to dchat.

Re: Tempest, that's not a viable solution due to instances such as "oh no this miner got vored by a simplemob and the digest has disabled their sensors so we can't find them."

**Comment by MrSign** [comment]
I'm uneasy on making this a proper mechanic since its rather niche! Unlike digestion, you don't really need oxy loss to roleplay out smothering or other things. As pointed out earlier, you pass out at a certain point of oxy-loss, meaning you can't reply nor see replies to your RP!

**Comment by YuskoTheCoyote** [comment]
I'm going to clear things up and say that I was the one who suggested the idea to Heroman. So if you have issues with that, refer them to Nodu on the Discord server. 

I got a feeling all of medical's concerns could be avoided if people involved in scenes were simply considerate and made sure to remove the outfit the the person being suffocated, or if the person simply disabled their sensors. We have an option in character setup that allows for sensors to be disabled upon spawning in. 

While I understand that this may be a niche addition, I believe that adding in extra options for the vore panel will help add flexibility for people to enjoy their scenes. 

As somebody who's not quite a medmain but still frequently plays medical, I don't share the concerns that the other medical players are stating. Suffocation damage is already easy to treat, and players can be revived no matter how much of it they suffered. That along with the fact that the defib timer is now 60 minutes, I cannot see a good reason why medical would be desperate enough to break into areas in an effort to find the suffocating person. I instead would recommend those people to do their best to find out what's going on first before blindly hurrying to where they believe the person would be.

**Comment by Wickedtemp** [comment]
...dude, this right here, 

> ...and made sure to remove the outfit the the person being suffocated, or if the person simply disabled their sensors.

... yeah that _would be nice_ but we all know that isn't how the server, playerbase, or humanity itself even works. This happens all the time. People forget, _all the time_. People _don't care in the first place, all the time._ The server's always been that way and most likely always will be. 

> "We have an option in character setup that allows for sensors to be disabled upon spawning in."
That's for being spawned in. Plenty of people want their sensors on during normal gameplay and forget to turn them off before/during a scene. 

> Suffocation damage is already easy to treat, and players can be revived no matter how much of it they suffered. That along with the fact that the defib timer is now 60 minutes, I cannot see a good reason why medical would be desperate enough to break into areas in an effort to find the suffocating person. I instead would recommend those people to do their best to find out what's going on first before blindly hurrying to where they believe the person would be.

I had this long post typed up, but I'm just gonna go with... uh... fuck that, no, lol. This is a HRP server and Medical is allowed to **and should treat** dying people with urgency. "oh just defib if they die its no biggie" is LRP as **fuck**.

**Comment by Torque4607** [comment]
While I do believe that expanding towards niches is usually nice, this is one occasion where it will do more harm than good. The first step to risk control is to eliminate or to not implement the risk in the first place. Saying "just take off clothes/turn off sensors" relies on humans. Humans _suck_ at doing things like that since it's so completely inconsequential that "meh" applies. 

And to concur with Tempest, this is allegedly an HRP server where I would _hope_ the paramedics tasked with saving me/my character do so in an expedient manner. Because virtually nobody wants to spend that 60 minute defib timer in dchat if he/she can help it. And since a lot of medical is already watching the funny panels of numbers occasionally change from 0/0/0/0 to something else, there tends to be a lot of chomping at the bit when the prospect of any kind of action (like a rescue) comes up. 

"I instead would recommend those people to do their best to find out what's going on first before blindly hurrying to where they believe the person would be." Let's talk a real life anecdote. If a person starts suddenly gasping for breath, EMS won't ask "okay, where is he suffocating at? How much does it suffocate for when he suffocates?" _They sprint to the scene of the fucking emergency._  

In summation, I believe the arguments for including this mechanic are not worth the strife that it can cause medical players when it comes time for us to do our jobs.

**Comment by Very-Soft** [comment]
So to say, I think this is fine, tbh. I think concerns about medics seeing it and getting fussy is no different than we already have. 

If you see someone taking damage on sensors but no one is yelling for help, it tends to get ignored unless they die and stay on the sensors. I think there will be an adjustment period where people get medical breaking into their scenes, but I don't think it will take long for people to extend how they handle brute and burn to mysteriously silent sudden oxy damage.

The only things I'm concerned about with this is that, if it goes in, I'd like to make sure that popped lungs are not a possibility from this, as that could turn a small tease into a serious medical situation.

On the mentioned topic of digest modes disabling sensors, I am extremely dubious about this, because eventually that's gonna have someone dying in a space carp or whatever, asking for help, but oops their sensors keep getting turned off because they're being digested. 

I do think though that preds having a belly addon mode that blocks or turns sensors off though as an option would be a good alternative to that.

**Comment by Wickedtemp** [comment]
Given that oxy damage causes brain damage, and brain damage causes you to suffocate, then it's possible. I'd have to actually check the rate of brain damage and at what threshold it actually starts.

I still think this is an incredibly dumb addition, I think it will cause a fair bit of headache if it pops up often.

Depending on how it looks on sensors, if it looks like its someone suffocating and they aren't in the dorms, I don't know what Nodu expects me to do. Obviously I'd PDA, but if I don't get a response, what then? I'm not going to break character and go full LRP and pretend Tempest is totally chill with "let them die and defib later". I also don't want to interrupt scenes, but that can just be handwaved without much consequence, so it's probably what I'm going to end up doing because I'd rather do that than ignore it and turns out someone died because they left internals on and AFK'd.

**Comment by lm40** [comment]
if you want to kill  sensors you can already use stripping modes to de-suit people even inside. i do think it will make things more annoying medically because oxygen loss is more likely to correlate with a significant non-vore injury. i also think it is kinda iffy to have as a mode cuz asphyxiated people lose consciousness pretty quickly so how actually scene-useful this is rather than extremely mild fluff is dubious, but i don't think it matters hugely either way.

**Comment by Novacat** [comment]
Due to the intensity of disagreement with this particular PR, it will likely be the next staff meeting when this gets discussed.

**Comment by Detective-Google** [comment]
> So to say, I think this is fine, tbh. I think concerns about medics seeing it and getting fussy is no different than we already have.
> 
> If you see someone taking damage on sensors but no one is yelling for help, it tends to get ignored unless they die and stay on the sensors. I think there will be an adjustment period where people get medical breaking into their scenes, but I don't think it will take long for people to extend how they handle brute and burn to mysteriously silent sudden oxy damage.
> 
> The only things I'm concerned about with this is that, if it goes in, I'd like to make sure that popped lungs are not a possibility from this, as that could turn a small tease into a serious medical situation.
> 
> On the mentioned topic of digest modes disabling sensors, I am extremely dubious about this, because eventually that's gonna have someone dying in a space carp or whatever, asking for help, but oops their sensors keep getting turned off because they're being digested.
> 
> I do think though that preds having a belly addon mode that blocks or turns sensors off as an option would be a good alternative to that, though perhaps is outside the scope of this PR.

The issue with this take is that puts the onus of taking the sensors off on the people participating in the scene, which if they did, this wouldn't be a problem brought up in the first place because medical wouldn't have to deal with it, but that's just not the server culture, and unless admins started PMing people saying that leaving your sensors on is a prefbreak, which never would (and probably shouldnt) happen, that isn't going to change, hell, especially given how often people will subtle(or not so subtle) brag about digesting X is indicative that it'd require a code or policy change to fix. the concerns brought up about endo med having to watch this stuff are completely valid and it'd be trivial to make a check to see if the digest-er has a client mind and then act if it does, solving the whole simplemob issue etc etc.

**Comment by Haery70** [comment]
As someone who doesn't do death/digestion I'm fine with this, it's no different than grabbing someone aggressively and strangling them in the dorms as an alternative to vore bellies not being able to do so. As for what Tempest suggested:

> - Damaging belly disables/de-activates/sets-to-binary-or-off/hides/conceals-in-some-way, suit sensors
> Just damaging, because there's no issue with endo/absorb/etc and healbelly actually kinda relies on suit sensors, else you can't tell if they're healing or not
> And this would accomplish the following:
> 
> - Medical players who don't like digestion/death scenes no longer have to look at it all the time
> 
> - People who do like digestion/death scenes no longer have to deal with Medical PDA-ing them and shit
> 
> - It's even more awkward when they use comms instead of PDA so this would be a double-plus
> 
> - Might cause issues with vore mobs and stuff but eh its an overall net positive
> 
> - Also means above PR's can just be accepted because medical's not going to see it and won't potentially freak out. Like, you could even throw in toxin damage too at that point.

Medical: "Remember to turn on your suit sensors!"
Crewmate: Listens to medical and turns on suit sensors.
Also Crewmate: Gets eaten and starts to digest.
Medical: "WTF? Why didn't you turn off your suit sensors before getting in a scene?"

I can't really fault the crew for having Medical watch as brute/burn damage slowly rises up on their sensors if Medical's putting up reminders for the crew to turn on their suit sensors, it's pretty ironic if you ask me.

**Comment by Wickedtemp** [comment]
""it's no different than grabbing someone aggressively and strangling them in the dorms as an alternative to vore bellies not being able to do so.""
- which would also cause Medical to treat it as more of an emergency situation if the person can't be contacted and if their sensors aren't set to tracking and they're in an obvious scene location like the dorms

""Medical: "Remember to turn on your suit sensors!"
Crewmate: Listens to medical and turns on suit sensors.
Also Crewmate: Gets eaten and starts to digest.
Medical: "WTF? Why didn't you turn off your suit sensors before getting in a scene?"

I can't really fault the crew for having Medical watch as brute/burn damage slowly rises up on their sensors if Medical's putting up reminders for the crew to turn on their suit sensors, it's pretty ironic if you ask me.""
- I mean I just say "Remlember suit sensors" literally for that reason, so people remember them when they're in a scene as well. It really isn't hard to turn them off as prey or pred, but people forget all the time, which is why I'm still suggesting an automatic disabling if digestion is toggled on.

**Comment by TheDavestDave** [comment]
12 is enough to cause brain damage. 3 is caused by face sitting already, it'd be a better cap.

a big reason for many medics burning out is they get sick of seeing vore damage and getting told off for trying to do their job.

or they seen normal damaged as non-vore damage and get off for not doing their job. 

new people who can't tell yet just get hated on what ever they do, the one tell with this update now gone

**Comment by Arokha** [comment]
I think some of the complaints in this are alleviated by https://github.com/VOREStation/VOREStation/pull/10221 since every comment against appears to be about sensors showing oxy damage.

VerySoft's concern about popped lungs isn't possible with this, as it deals oxy damage directly. Ruptured lungs come from handle_breath() and being unable to breathe.

I do think in terms of 'enjoyable roleplay', regardless of your kinks for oxyloss or whatever that represents, it seems like it'd pose a problem when you pass out and can't see replies anymore. Also in terms of how oxyloss is handled ingame, I think it might be a bit confusing for players. Oxyloss values up to 5 will do basically nothing, as humans heal 5 oxyloss per breath. Compared to brute and burn where humans heal small, fractional amounts, it will be a much 'faster' fight between causing oxy damage and healing it.

The 12 setting seems high, as it's more than 6, which is the max of the other digestion types, even taking into account the -5 each breath from the human. The max number would be 11 if you wanted to match the real max of the others.

**Comment by JoanRisu** [comment]
I also think #10221 addresses this. However, just to ensure we work out and understand the issues that may inevitably come up regarding this, we'll add it to our meeting pile.

**Comment by Wickedtemp** [comment]
Sensors being disabled in dorms is a step in the right direction, but won't really alleviate issues entirely. Since...it's dorms. Most people don't really scene in dorms, especially because this is going to be vore-related, which is most likely going to be happening in subtles all around the station.

**Comment by JoanRisu** [comment]
We have discussed this PR in a general meeting and generally agree that this is fine to pass pending final review by Aro. In regards to #10221, we will improve upon the idea and adjust it as needed to address concerns about it. We know what to keep an eye out for and we'll do our best to anticipate it.

**Comment by Heroman3003** [comment]
Conflicts SHOULD be fixed, but TGUI is a beast from the void so I am not too sure, but it should be good I guess? I updated then recompiled the files.

**Pull request merged**
