### PR TITLE
Reenables size changing.

### PR DESCRIPTION
**Pull request by Cameron653**
- Reenables size changing verb.
- Makes the size changing verb Promethean only.
- Makes the size changing verb available to pAIs due to lack of ways to change size.
- Allows non-humanoids to use the size changing verb.

People want it back for Prometheans and other things.

### CODE REVIEW

**Comment by Dhaeleena** [comment]
Yyeeess.
I want this because we are already changing and adding so many things to facilitate role-play and making features more role-play friendly...I cant think of a more role-play friendly tool than re-enabling this.

**Comment by kcin2001** [comment]
this can be very usefull and cool since for prommies they could technically intake more mass and grow from it by turning it to goop and borgs dont keep their size between rounds if my memory serves and some people may want to have a larger or smaller size of robot

**Comment by SilencedMP5A5** [comment]
i support this because:
big (and small) borgs are CUTE
and also prometheans should be able to mass change.
(and so people can reverse accidental/intentional sizeray shots they don't approve of)

**Comment by SpadesNeil** [comment]
Considering how flagrantly abused size changing was previously, I have really no desire to see it added back in.

Prometheans can have the ability if they want but they're _prometheans_.

**Comment by kcin2001** [comment]
I at least want to be able to spawn as bigger or smaller than 100% with a Borg

**Comment by Ketrai** [comment]
tbh, I'd be in favour, but all the roleplay aiding elements we have are still mostly IC, and something you have to achieve. There's also plenty of ways to change size. I do agrees borgos etc should be able to change easily without someone else to use a sizegun on em, however everyone else should just use the nifsoft or the size gun, it's not that hard.

**Comment by Kligor** [comment]
I personally think its a good idea for if you want to roleplay things you normally could. Sure you COULD do some things but if its abused just.... tell the player to knock it off? I feel like if someone's abusing size changing its for reasons that'd probably get them in more trouble than just abusing size. If Im wrong, tbh, please let me know what they can abuse with it? I really dont see much use to abusing it.

**Comment by Zeronis** [comment]
The only reason I can fathom for it being removed in the first place was because it was being abused, and then that's not the problem with the tool, that's a problem with the people abusing the tool.
Don't remove features, remove the fuckups fucking it up for everyone else. If the temptation is really so strong to break the rules and abuse features with blatant disregard then they either don't respect or don't care about the rules they're breaking and need to be dealt with.
I am in favor of bringing back this tool despite the massive amount of size changing equivalents that exist, due in part to the people/characters who could benefit from it that aren't covered by the existing alternatives, but I also won't shed any tears if it falls through.

**Comment by Renkindle** [comment]
I feel like it should only be available to prometheans/borgs. Prometheans because it makes sense species-wise and borgs because they can't eat the mushrooms or use a size gun on themselves or anything.

**Comment by DemgelZalvine** [comment]
Personally I don't want to see this back for everyone at all. I was glad when it was gone, as the people claiming magic and abusing the OOC use size-change button was really getting annoying. There are many means in station to change your size now, via NIF, Size gun, etc, that can set you however you'd like and not terribly hard to get. 

Arguably, enabling something like this for borgs wouldn't be so bad, maybe a size change module for them? Maybe promethians as it makes sense...but they already have a Ton of perks as is.

**Comment by Arokha** [comment]
I'm with Zalvine on this. Adding options for those that can't size-change because none of the existing methods work well with them or are mostly unavailable is a good idea, but I'm of the opinion that magical size-changing requires an SCA, like any other magical ability. I could see maybe an exception for prometheans since goo.

**Comment by kcin2001** [comment]
Yeah and its not a new concept that slimes can increase mass by eating since thats how xenobio smiles work essentially

**Comment by AliciaJewel** [comment]
I used the size change verb when I played my Promethean for a mass increase when she ate, so I might be a bit biased toward saying that they should at least be given to them.

**Comment by Cameron653** [comment]
Alright. General consensus from what I can see if Prometheans should have it. Going to change it.

**Comment by Cameron653** [comment]
Done. It's been made Promethean only. Tested it and the only species that has access to the proc is Prometheans.

**Comment by Cameron653** [comment]
_NOW_ it's done.
Only pAI's (Due to lack of ways to change size) and Prometheans (Due to them being slime) can use the size changing verb.

**Comment by kcin2001** [comment]
@Cameron6531 what about borgs?

**Comment by SpadesNeil** [comment]
We changed our mind with borgs. We don't need tiny borgs.

**Comment by kcin2001** [comment]
and pais are fine being even tinier?

**Comment by Cameron653** [comment]
Seeing as pAIs can't:
1. Open ID locked doors
2. Grab people
3. Hit people
4. Use machines
etc
I don't think it's really that much of an issue, while borgs could do all those things.

**Comment by kcin2001** [comment]
ok then, if there was a way to restrict the size change to certain limits easily i would suggest that

**Comment by SpadesNeil** [comment]
>Allows non-humanoids to use the size changing verb.

What?

**Comment by Cameron653** [comment]
There was a !ishuman check that prevented borgs, pai's, etc from using the verb. I removed said check.

**Comment by SpadesNeil** [comment]
I kinda don't want borgs able to change size freely.

**Comment by Cameron653** [comment]
They can't

**Comment by SpadesNeil** [comment]
oh ok

**Pull request merged**
