### PR TITLE
Adds Adranol

### PR DESCRIPTION
**Pull request by Arokha**
Adranol fixes jittery, eye_blurry, and confusion, and would be good as a post-resleeving drug. It'd also be the only drug that can actually fix jitteryness, since there is no way to undo that now.

### CODE REVIEW

**Comment by OrbisAnima** [comment]
are you sure you want to use milk for it? it makes it kinda of a pain to go to the bar and beg for it...

**Comment by Arokha** [comment]
There is already milk in fitness vending machines, which already exist in medical

**Comment by OrbisAnima** [comment]
oh!

**Comment by Wickedtemp** [comment]
Kitchen has milk, fitness vendors have milk, the bar has milk, there are plenty of sources of milk.

**Comment by Arokha** [comment]
> plenty of sources of milk.

c:<

**Comment by Wickedtemp** [comment]
I had nothing to do with this, I swear.

**Comment by Wickedtemp** [comment]
... What if an overdose of this made you drowsy?

**Pull request merged**
