### PR TITLE
Adds bridge protection turret to Talon

### PR DESCRIPTION
**Pull request by Cyantime**
The talon has a number of point defense turrets scattered around it, but is conspicuously missing any that would protect the most important and also vulnerable spot on it.
This sticks a turret there.

turret

### CODE REVIEW

**Comment by Cyantime** [comment]
Giving travis a boot

**Comment by Cyantime** [comment]
oh, did that not work

**Comment by Cyantime** [comment]
trav

Why is this running three times

**Comment by Leshana** [comment]
This PR is broken. I don't see a way to easily remove the extra two checks that will not run.   Please open as a new PR while github is not drunk.

**Pull request closed without merging**
