### PR TITLE
Makes the Create Object menu not freeze the client for an eternity

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
This PR is literally just copy pasting Aurora's optimizations of the underlying html that makes the Create Object menu work.

The Create Object menu will no longer freeze the client while it populates the object list. It will populate the list instantly and painlessly now.

It's black magic to me.

I have no idea how or why it works.

It just does.

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Polaris may want this thing, so you might want to port this there first.

**Comment by Michiyamenotehifunana** [comment]
Alright, I got it PR'd to Polaris. I'll leave this open until someone tells me to close it (or closes it themselves) tho.

**Comment by Very-Soft** [comment]
This issue is the main reason I never, ever use it!

So! While I think build mode will remain more generally useful, this will 100% make our lives easier in spawning in some stuff~ <3

**Comment by MrSign** [comment]
Please and thank you.

**Pull request closed without merging**
