### PR TITLE
Attempt at putting belter mining to Rascal Pass

### PR DESCRIPTION
**Pull request by Noobetski**
I did what i could and now i'm out of ideas, i opened it as draft in case someone manages to fix it

### CODE REVIEW

**Comment by Noobetski** [comment]
wait, wires?

**Comment by Noobetski** [comment]
Shuttle loses part of it's floor when moving, rogue zones work as intended

**Comment by Heroman3003** [comment]
Is this still being worked on?

**Comment by Heroman3003** [comment]
Due to no response for 3 months, I will be closing this. You're welcome to open the project up again if you're interested in continuin.

**Pull request closed without merging**
