### PR TITLE
Adds slimecore reactions and gives slimes a greater chemical pool to choose from.

### PR DESCRIPTION
**Pull request by Cameron653**
This is a new feature.

Proposed changes in this Pull Request:
-  Adds in chemistry reactions to simulate prior slime core reactions.
- Adds in an "Advanced mutation toxin" that turns the user into a Promethean
- Allows slimes to choose from an even greater  chemical pool than just a few medicines/poisons.

Notes:
Basically, this adds back what xenobiology2 removed, which was slime core reactions. The new reactions are weighted on how "big" they are 
**One slime core gives 5 slime jelly,** and different mutated slimes give different chemicals. For example, some can give mutationtoxin, but it mostly comes down to RNG, just like the old xenobiology. Once you get a good slime that creates phoron and mutationtoxin, you can basically start to mass produce reactions like you used to be able to do in old xenobiology when you got a specific slime (Ex: Dark purple slime.)
Reactions:
**Slime food spawn**: 10 phoron, 10 slime jelly, 10 nutriment
**Slime minerals**: 20 phoron, 40 slime jelly, 20 aluminum
**Slime flashlight**: 5 phoron 5 slimejelly 10 water
**Slime phoron** (10 phoron sheets): 20 phoron 20 uranium  20 slimejelly
**slime freeze**: 10 phoron 10 coolant 10 slimejelly
**slime frost oil**: 5 water 5 coolant 5 slimjelly 5 phoron
**slime fire**: 60 phoron 30 slimejelly 30 potassium
**Slime advmuttoxin** (turns user into Promethean): 15 phoron 15 slimjelly 15 mutationtoxin
**slime heal** (AOE heal effect.): 10 phoron 10 bicaridine 10 kelotane 10 inaprovaline 10 slimejelly
**slimejelly**: 20 phoron 50 sugar 50 lithium (Extremely high cost, will run the chem dispenser out quick, along with plasma. For the impatient xenobiologist.)
**Slime vore mobs**: 20 phoron 20 nutriment 20 sugar 20 mutationtoxin

REMOVED UNTIL WORKING FOR POLARIS CODE:
**Slime hostile mobs**: 20 phoron 20 mutationtoxin 20 docilitytoxin 20 slimejelly
**Slime passive mobs**: 20 phoron 20 silicon 20 docilitytoxin 20 slimejelly

**Gives slime's biochemistry a greater pool to choose from**

### CODE REVIEW

**Comment by Arokha** [comment]
I would make the list of vore mobs dynamic so this doesn't need to be updated for new mobs.

```js
//Produces a list of every vore mob, but includes the 'base' unfortunately which is then subtracted.
//Since 'mob/living/simple_animal/hostile/vore' probably is not a mob itself.
var/mob_path = /mob/living/simple_animal/hostile/vore
var/list/voremobs = typesof(mob_path) - mob_path

//Picks from our list
var/pickedmob = pick(voremobs)
```

You could make something fancy later if you wanted, by putting different paths in depending on what kinda slimes or whatever to spawn different sets of mobs.

**Comment by Cameron653** [comment]
Done.

**Comment by Cameron653** [comment]
EDIT: Added in a commit that gives slimes a greater chemical pool so they don't have only 15 chemicals (Most of which were either poisons or medications.) This makes it so the same few chemicals don't keep showing up, and adds some diversity.

**Comment by SpadesNeil** [comment]
Indeed, like the old slime core code for gold slimes, it's better to choose from a type, and just blacklist what you DON'T want to spawn.

**Comment by Cameron653** [comment]
That's currently in this PR (For the vore mobs)
The other gold slime core effects are going to most likely be in another PR, as I don't know which mobs are broken or not.

**Comment by Arokha** [comment]
`O.show_message(text("\red The solution begins to vibrate violently!")`

Color macros are verboten. Only reason Travis didn't complain is because someone on Polaris removed 10 so it's checking for 10 more than it needs to. Use `<span class='warning'></span>` for red text.

**Comment by Cameron653** [comment]
Alright, I believe I fixed all the areas with \red. Whatabout \blue?

**Comment by Cameron653** [comment]
Also fixed \blue while I was at it.

**Pull request merged**
