### PR TITLE
Removes Licking from context menu

### PR DESCRIPTION
**Pull request by SpadesNeil**
So you no longer right click on people and lick them instead of, say, pressing "give".

Also some grammar fixes for OOC escape.

### CODE REVIEW

**Comment by Draycu** [comment]
Gotta say, I really appreciate this change.  Would be nice to not accidentally lick people when in a hurry, that’s for sure!

For clarification, it’ll be possible to still lick through other means, right?

**Comment by KotetsuRedwood** [comment]
I'm not sure I like it. Makes it easier to slobber people up and let's be honest, that's _fun_

**Comment by SpadesNeil** [comment]
>For clarification, it’ll be possible to still lick through other means, right?

Yes. Use the IC menu.

**Comment by Leshana** [comment]
Booooooooo

**Comment by ArgobargSoup** [comment]
Oh darn.  There goes a perfect way of adding hilarity and awkwardness to a situation.  :P

**Pull request merged**
