### PR TITLE
Rebalances micro mechs, removes micro mech equipment, misc micro mech code cleaning

### PR DESCRIPTION
**Pull request by MisterGrimm**
**This PR comes in three parts. Each part will be explained in detail below.**

### Rebalancing micro mechs to allow them to use standard mech equipment
Micro mechs have existed in the code for almost five years, and it has become obvious over this time that the micro mech series leaves much to be desired. This part of the PR works to rebalance the micro mech, and create more incentive for micros to use micro mechs over being on foot. The rebalanced changes are : 

- Micro mechs can now use standard mech equipment, instead of micro mech equipment.
- Micro mechs have reduced slots now to balance the use of standard mech equipment.
- All micro mechs get one special slot by default, but no hull slots to prevent shenanigans. Polecat gets two weapon slots, but no utility slots due to the mech guns taking up most of the space. Weasel gets one weapon slot, but no utility slots due to being a scout/skirmisher. Gopher utility slots are unchanged at two, enough to do it's job but not much else.

### Removed micro mech equipment
Due to the balancing done above, the existence of micro mech equipment is no longer required. A large amount of micro mech equipment are copy pasted versions of normal mech equipment, or in a few anomalous cases have higher battery costs then the mech equipment it is based on. Removing micro mech equipment frees up a large amount of bloat found in the mech fabricators, and also prevents people from accidentally making micro mech equipment under the perception that it is not a micro equipment.

- Micro mech equipment removed, micro mechs use normal mech equipment now.
- No loss in equipment diversity due to standard mech equipment.

### Misc micro mech code cleaning
This part is just some pruning of redundant code.

- Micro module code removed, due to no longer needing it.
- Removed the mystery children in the code, known as /obj/mecha/micro/utility , and /obj/mecha/micro/sec . These children are not found anywhere in the code, and do not have any special procs that require them to be separate from each other.
- Removed moved_inside and go_out proc in micro/security.dm . Proc was already properly handled in micro.dm .
- Microshotgun has become a mech weapon, due to the interesting ability to cycle through ammo types.

### CODE REVIEW

**Comment by Heroman3003** [comment]
While I generally don't mind the idea of micro mechs being made more useful, there are several aspects to them that make them kinda insane when put together with 'normal' equipment.

General idea behind them is that they are supposed to be very cheap to produce and available earlier than ever. They were also designed long before materials fridge was a thing, meaning they took into account that they are supposed to be make-able with roundstart materials. They are fragile, but also, compared to normal mechs, mobile. And overall, are basically meant to not be a 'small mech' but just something on-par with roundstart-equipped sec/miner. I will take more thorough look at the changes, but I am very sceptical of any equipment capable of carrying people (sleeper or passenger cabin) being equippable on micro mechs, is the first and biggest balancing HMMMM that I have here.

**Comment by Enzo-Leon** [comment]
I like the idea of giving these some treatment to get rid of the mothball state they were basically in it'd feel. I do hope with this it gives some viable options for folks to use that can.

**Comment by TankTheBirb** [comment]
I have mixed feelings, I'm not sure this will really increase their usage as the role they were designed for is more of a roleplay one in the current server. Micros don't really need a mech to do dangerous work, and people are hesitant to ask for anything more significant than a few extra batteries from science.

However, while it isn't fixing any of the problems with micro mechs, it is probably making them less of a bit of jank. I think Scree should probably have some input since they made the things.

**Comment by Heroman3003** [comment]
Okay, I had some time to better gather my own thoughts. Basically, micro mechs being made 'useful' or in any way on par with real mechs kinda goes entirely against their original purpose of being like 70% roleplay tool for people who are perpetually micro - to be on par not with mechs, but with mechless people. Now, I do think that that purpose is kinda obsolete, but I also think trying to push micro mechs up to be more like normal mechs will either result them being only less unique, or them being excessively strong due to their advantages.

Rather, I think their niche should be focused less in 'practical usefulness' and more ease of procurement. Making them take way less construction steps, reducing or outright removing science level requirements, gutting material requirements, stuff like that might push them a lot more into a niche of ultra-easy procurement. But even that niche is hard to fill considering that mat fridge, well, exists.

**Comment by MisterGrimm** [comment]
> I have mixed feelings, I'm not sure this will really increase their usage as the role they were designed for is more of a roleplay one in the current server. Micros don't really need a mech to do dangerous work, and people are hesitant to ask for anything more significant than a few extra batteries from science.
> 
> However, while it isn't fixing any of the problems with micro mechs, it is probably making them less of a bit of jank. I think Scree should probably have some input since they made the things.

I agree with all of this. Honestly my first thought was to remove micro mechs in it's entirety, but I ultimately gave up on that idea. This PR is basically my compromise / trying to avoid a knee jerk reaction from myself, as the numerous disincentives the current micro mechs have don't warrent their continued existence. 

My ultimate opinion on the micro mech is that they need to either be rebalanced to try to give people a reason to use them, or completely removed since there are a ridiculous amount of better options compared to micro mechs.

> Okay, I had some time to better gather my own thoughts. Basically, micro mechs being made 'useful' or in any way on par with real mechs kinda goes entirely against their original purpose of being like 70% roleplay tool for people who are perpetually micro - to be on par not with mechs, but with mechless people. Now, I do think that that purpose is kinda obsolete, but I also think trying to push micro mechs up to be more like normal mechs will either result them being only less unique, or them being excessively strong due to their advantages.
> 
> Rather, I think their niche should be focused less in 'practical usefulness' and more ease of procurement. Making them take way less construction steps, reducing or outright removing science level requirements, gutting material requirements, stuff like that might push them a lot more into a niche of ultra-easy procurement. But even that niche is hard to fill considering that mat fridge, well, exists.

I agree that micro mechs should not be on-par with mechs, but rather on par with normal people. The problem is that in their current state they are already at the power of a mech, while just being as squishy as a person. If anything, this PR actually nerfs the micro mechs by reducing the amount of weapons they can have at once, while still giving them a array of options to choose from.

As was stated in the PR description, micro weapons are a literal copy paste of normal mech weapons, and also some personnel weapons. They have the same damage, the same fire rate, with only a few of them having different battery charge uses. The weapons also usually have the same build and tech costs to make them. Removing micro weapons and giving them mech weapons does not affect the balance at all, especially due to the fact that they are restricted to a single weapon instead of the original 3 the polecat had. The only thing I am minorly worried about is the utility slot items, which is why only the gopher has two utility slots.

**Comment by Screemonster** [comment]
Okay, so, about the equipment removal, there are a few differences between micromech equipment and regular mech equipment that may break things if you change them, and some of the comments make me wary that you're just ripping things out without looking into why they were done that way.

The energy weapons have energy costs and fire rates based on their handheld counterparts (at least, at the time they were added) rather than mech weapons but are functionally similar, they can probably go if they're redundant, they mainly existed for the purpose of saying "micromechs can _only_ fit these weapons" which was the entire reason for their existence, as normal weapons at the time had a `required_type` of `/obj/mecha/sec` which meant that they couldn't be mounted on 'obj/mecha/micro` - at the time, there were no such things as weapon/chassis/utility slots.

Likewise, the "mystery children" (/obj/mecha/micro/utility and /obj/mecha/micro/sec) exist specifically for the purpose of the `required_type` var on the modules, restricting weapons to the sec mechs and the utilities to the gopher as the mech code of the time didn't differentiate slot types.

There are some modules which _do_ differ from their normal mech counterparts:

The mounted ore box specifically allows a gopher to gather ore _without_ having an ore box in its internal compartment like a ripley, which is specifically because they don't have the ripley's insane internal cargo space (I'm not sure if I gave them any internal space at all when they were originally coded)

The drill, likewise, specifically looks for the mounted ore box instead of an internal one in mech storage.

The _ballistic_ weapons _do_ differ in stats. The flashbang launcher is nerfed to a single shot compared to a normal mech's 3-shot spread, and the shotgun is _entirely unique_. Seriously, the micromech shotgun has no equivalent among other mech weapons - it's even got utility above its handheld equivalent.  It's a select-fire shotgun that allows you to cycle the shot type on-demand between beanbags, slugs and buckshot without unloading and reloading it.
And unlike the scattershot (which fires a 4-shot spread of pistol bullets) it actually fires shot as ammo. Hell, it'd be pretty dank to promote it to "actual mech combat shotgun" rather than ripping it out.

As for the slots on the mechs themselves, the weasel _is_ intended to be a combat/exploration mech. As in, intended to take a weapon. As in, an actual-gun, not a jury-rigged one. The thing is _supposed_ to be a nimble little fast attack bastard that can perform blisteringly fast hit and run attacks if the terrain is good, it's the entire point of it. The polecat can _do_ it but while it's _quick_ it doesn't have the weasel's entirely-intentional ridiculous speedy bastard velocity.

**Comment by MisterGrimm** [comment]
> Okay, so, about the equipment removal, there are a few differences between micromech equipment and regular mech equipment that may break things if you change them, and some of the comments make me wary that you're just ripping things out without looking into why they were done that way.
> 
> The energy weapons have energy costs and fire rates based on their handheld counterparts (at least, at the time they were added) rather than mech weapons but are functionally similar, they can probably go if they're redundant, they mainly existed for the purpose of saying "micromechs can _only_ fit these weapons" which was the entire reason for their existence, as normal weapons at the time had a `required_type` of `/obj/mecha/sec` which meant that they couldn't be mounted on `obj/mecha/micro` - at the time, there were no such things as weapon/chassis/utility slots.
>
> Likewise, the "mystery children" (`/obj/mecha/micro/utility` and `/obj/mecha/micro/sec`) exist specifically for the purpose of the `required_type` var on the modules, restricting weapons to the sec mechs and the utilities to the gopher as the mech code of the time didn't differentiate slot types.

This is completely understandable in terms of required_type in the past, but it should be noted that this system no longer works with the current mech module refactor, and is deprecated at this moment. A example is that a sleeper mech equipment can be put in a gygax, odyss, and a ripley due to them having a utility slot. Even though the required_type says it can only be put in a medical mech, it ultimately does nothing to actually stop them from doing so with the current system.

> There are some modules which _do_ differ from their normal mech counterparts:
> 
> The mounted ore box specifically allows a gopher to gather ore _without_ having an ore box in its internal compartment like a ripley, which is specifically because they don't have the ripley's insane internal cargo space (I'm not sure if I gave them any internal space at all when they were originally coded)
> 
> The drill, likewise, specifically looks for the mounted ore box instead of an internal one in mech storage.

While this is a very interesting system, it feels more like this should be given to mechs by default, instead of only micro mechs. 

The current mech mining system works flawlessly with the Gopher, since all mechs have a default cargo capacity of 3. The gopher can use the clamp+drill, pick up a ore box, and go out and mine as a ripley / the old gopher could. And when it is done it can unload the ore box, with all of the contents inside that you have mined. This was tested before I made this PR, to make sure one of the gophers standard functions still applied.

> The _ballistic_ weapons _do_ differ in stats. The flashbang launcher is nerfed to a single shot compared to a normal mech's 3-shot spread, and the shotgun is _entirely unique_. Seriously, the micromech shotgun has no equivalent among other mech weapons - it's even got utility above its handheld equivalent. It's a select-fire shotgun that allows you to cycle the shot type on-demand between beanbags, slugs and buckshot without unloading and reloading it. And unlike the scattershot (which fires a 4-shot spread of pistol bullets) it actually fires shot as ammo. Hell, it'd be pretty dank to promote it to "actual mech combat shotgun" rather than ripping it out.

On the case of the flashbang launcher, the current mech flashbang launcher does not fire a three shot burst with spread. It only fires one flashbang a click, the same as the micro flashbang launcher. It should be noted that there is a special cluster flashbang launcher called the SOP-6, but it is a completely different mech equipment compared to the standard SGL-6 flashbang launcher.

Now the shotgun, I do have to agree with you completely there. The micro mech shotgun is very unique with cycle shot types, and I will be working on a commit here soon to replace the original mech shotgun with it, rather then remove it.

> As for the slots on the mechs themselves, the weasel _is_ intended to be a combat/exploration mech. As in, intended to take a weapon. As in, an actual-gun, not a jury-rigged one. The thing is _supposed_ to be a nimble little fast attack bastard that can perform blisteringly fast hit and run attacks if the terrain is good, it's the entire point of it. The polecat can _do_ it but while it's _quick_ it doesn't have the weasel's entirely-intentional ridiculous speedy bastard velocity.

That current slots for micros is just the current balancing on it. I can give the polecat 2 weapon slots and the weasel 1 weapon slot if you think that is a better idea. I just don't want to give the micro mechs too many slots, as they should not be a replacement of a standard combat mech.

**Comment by Heroman3003** [comment]
I will say, following all the discussions, I can't say I am ultimately convinced by this direction of rework to make them more like 'normal' mechs. Underuse of mechs is a thing that exists across all mech types on the server, not just micromechs, and micromechs are moreso a flavour option for a less-than-majority kind of character, so their underuse is understandable. Trying to make them 'viable' when they kinda already are is unideal. The way slots ended up arranged and stuff like 'jury rigged only for skirmisher mech' seems really counter intuitive and such.

My final general opinion is that this is trying to improve them in completely wrong design direction, although I don't disagree on there being room for improvement.

**Comment by Heroman3003** [comment]
I'll re-review it properly before end of next week. Apologies for repeatedly forgetting.

**Comment by Heroman3003** [comment]
Ultimately, the direction of the changes is not quite what micro mechs are wanted to be. You're free to try and aim them more in accessibility and ease of use direction, but making them more on par with regular mechs fails at either making them more usable or keeping them balanced at the same time.

**Pull request closed without merging**
