### PR TITLE
Tweak holoplant icons

### PR DESCRIPTION
**Pull request by Arokha**
Emagged now makes a saucy red dancing lady

### CODE REVIEW

**Comment by Very-Soft** [comment]
Can I smooch the red lady????

**Comment by Arokha** [comment]
> Can I smooch the red lady????

YA

**Comment by SplinterGP** [comment]
_ok thats great ~~hot~~_

**Review by Leshana — APPROVED** [review]

**Comment by Heroman3003** [comment]
I can't believe Vinny's desktop stripper is now in ss13...

**Pull request merged**
