### PR TITLE
[Map] Mining Ops Move

### PR DESCRIPTION
**Pull request by TheFurryFeline**
Moves Mining Ops to Space per Soft's Plan in #6122 (Removed imgur link. MapDiffBot's working again. :hype: 

Changelog Notes:

- Mining Ops Changes

- - Mining Ops design taken from Polaris's Southern Cross/Northern Star map.

- - Original Mining Ops moved to space near belt mining shuttle. Shuttle moved below control room and rotated southward facing, Space Belt Miner EVA adjusted slightly.

- - New Mining Ops area.

- - - Cameras added.

- - - Pipe outlet moved from Cargo Warehouse to new Mining Ops.

- - - New shuttle added for transport to and from Mining Outpost.

- Surface Warehouse changed for either storage of stuff found on the surface, etc. Has a back door leading out of it going towards the airlock. Delivery chute goes to new Mining Ops.

- - Signs added for conveyor's purpose.

- - Removed flaps push-through thing. Not needed now we have a delivery outlet for cargo to mail to.

- - Extra crates for storage purposes.

- Area of Mining EVA and what leads into it.

- - Mining EVA remains the same for a future Medbay move PR.

- - Washing machines moved, camera moved, scrubber moved, fire closet into fire wall locker.

- Add Transport to Mining Outpost.

- - Shuttle self explanatory addition. Walls all around it so you don't have to walk into a vacuum.

- - New hangar bay in Mining Outpost.

- - Add Secondary Mining Gear Storage with equipment and lockers.

- - Drills moved to above the airlock. Wires changed accordingly. No going under walls, please.

- - Move the whole outpost southwest a bit so it isn't too close to the mountain.

- Main Surface Cargo.

- - Area name changes for new Surface Cargo.

- - Add SortJunction for direct mailing to Surface Cargo Lobby to speed up supplying down there. Couple of tweaks in the room to make room for it. Adds safety guard railings and other decals for it. Warning Sign also added with custom description and name.

- - Fire/air alarm moved.

- - Changes pipeworks in Surface Cargonia to be more organised. Surface Cargo Office and Foyer disposals rerouted to main lines underneath Suface Cargo Office window.

- - Surface Cargo Office switch now connects to the  conveyor for surface deliveries. Even if it yeets out of the outlet. Should be fine if actual crates/closets are mailed compared to packages.

- Other changes.

- - Extra air supply/scrubber pipes removed from asteroid warehouse.

- - Trash Pit now on Master powergrid, old Mining Ops a construction zone.

- - Seems a vacant maint area was set for rocks between art supply and xenoflora maint. Fixed.

- - Leftover empty area of old Mining Ops pathed as a construction zone, TODO to repath other vacant sites for the same reason. Vermin events never spawn at the vacant areas because of the pathing.

### CODE REVIEW

**Comment by Leshana** [comment]
Hmm, such mining

**Comment by Heroman3003** [comment]
I personally just think that removing any mining trace from surface entirely and adding a separate small shuttle between cargo and mining outpost is much more sensible. Imagine getting all dressed in top level and then having to go down all the way to bottom level in the voidsuit. Or maybe just make entire mining on the outpost and a small shuttle there from a small mini-office in cargo? I just feel like this will create way too much tedious walking from all the way up in cargo to all the way down to the surface mining airlock.

**Comment by TheFurryFeline** [comment]
I'm just going by what the plans said was wanted for what goes where and mining ops being moved to asteroid side was there. However, that said, belt mining is difficult enough seeing that you have to float a lot and run the risk of having to abandon your ore box and float off shooting at mobs.

**Comment by TheFurryFeline** [comment]
AHHHH MISCLICKED

**Comment by piperherring** [comment]
as someone whose playtime is mostly in surface mining i dislike the idea of having to spawn at the asteroid to gear up + having to deal with elevator travel time from the exact opposite end of the station

**Comment by Heroman3003** [comment]
How would any of what I said affect belt mining again?

**Comment by TheFurryFeline** [comment]
Hmm, now that I think about it, Hero's idea can work. Rykka tried it for their version of Belt Mining. It would also complete the mining move to space that would pave the way for medical to have three decks. Which was a part I overlooked when following the instructions. Whoops.

 By that count, this isn't even 90% done. The shuttle addition going to mining outpost is easy enough and I can do it withina couple days and leave the EVA in for both the Medbay move and so miners don't have to wait on quick help if people need to rescue.

I'm gonna mark this as a draft for the time being

**Comment by TheFurryFeline** [comment]
So, yeah. Current issues as my latest commit says are a few runtimes happening while initialisations are happening. Console won't connect to the new shuttle. I'll work on it some more tomorrow. Just had a lot done just to get through conflicts that could have happened had I not renamed my files.

**Comment by TheFurryFeline** [comment]
Thanks to Aro for helping me figure out what the problem was with the runtimes and shuttle not connecting to the console. Ready for review for real now.

**Pull request merged**
