### PR TITLE
Skyrat extinguisher cabinet sprites

### PR DESCRIPTION
**Pull request by Arokha**
Destroys the mystery cabinet meta by showing you what's in the cabinet

Old vs New
dreammaker_K9oTYCNBxG
dreammaker_qethsouoSF

### CODE REVIEW

**Comment by Very-Soft** [comment]
me like

**Comment by Ketrai** [comment]
I like them but they look like they would take up almost as mich as the wall itself. Got an ingame shot?

**Comment by Arokha** [comment]
> I like them but they look like they would take up almost as mich as the wall itself. Got an ingame shot?

Sprites are only like 3 pixels taller

**Comment by Arokha** [comment]
dreamseeker_DH2QqClnak
dreamseeker_s7JkTi08fC

**Pull request merged**
