### PR TITLE
Adds a verb for rideable mobs to toggle rider control without a riding crop

### PR DESCRIPTION
**Pull request by Verkister**
-Mountable mobs/borgs/taurs can now let the rider in control without requiring a riding crop.
-And yes, riding crop has always been "the key" for rider control for these mechanics.
-Also tweaks the AO a little bit more because ouch my ocd.

### CODE REVIEW

**Comment by Wickedtemp** [comment]
Riding crop is broken and doesn't work, last I checked. Is this tested and working?

**Comment by Verkister** [comment]
Hmm well I know that the check for the crop is working and that this thing here is tested functional at enabling rider control by bypassing that check. Didn't really even think about testing it with the actual riding crop so i should probably check if there's like a pathing typo or something like that for the keytype

**Comment by Verkister** [comment]
Looks like the riding key checks are using their own specific is_holding_item_of_type spaghetti proc that looks kinda dodgy to me when it coud just do a get_equipped_item check

**Comment by Wickedtemp** [comment]
On a side note if this works and everything GOD ITLL BE SO AWESOME

**Comment by Novacat** [comment]
Is this ready for merge or are you planning on getting the riding crop check working?

**Comment by Verkister** [comment]
it's ready for now. The working crop check would be a polaris fix

**Comment by Wickedtemp** [comment]
..I know its closed now but given that virgo added the riding crops to start with, how is it a polaris fix if they dont even have riding crops

**Comment by Verkister** [comment]
Because it's using the keytype check for vehicle riding and it's that check where the fault is, not the crop itself.

**Pull request merged**
