### PR TITLE
Absorption Permission Stuff

### PR DESCRIPTION
**Pull request by TheFurryFeline**
Requested Vore Panel/Prefs thingy.

Edit 15/12/19 - Code change wasn't so hard there to get that to work. Nice.

Changelog Notes:

- If you have Unabsorbable displaying as disallowed permission, you're unable to be absorbed.

### CODE REVIEW

**Comment by Heroman3003** [comment]
This sounds really misleading considering it doesn't actually determine whether or not you can be aborbed (especially with var name such as 'absorbable'). Also, unlike healbelly, this pref wouldn't be something you need to have ability to emergently check, so I don't think it should be in mechanical prefs either.

**Comment by TheFurryFeline** [comment]
Marking as WIP pending code advice on preventing absorption mechanically.

**Comment by TheFurryFeline** [comment]
OP edited and removing WIP tag. Seems to prevent absorption on testing.

**Comment by TheFurryFeline** [comment]
Discussion on discord was brought up that this'll pave way to adding TF permissions/preventions but that's out of the scope of this PR.

**Comment by Screemonster** [comment]
I'd like it if it made it behave as drain mode instead of doing nothing, but doing nothing is also acceptable.

**Comment by TheFurryFeline** [comment]
> I'd like it if it made it behave as drain mode instead of doing nothing, but doing nothing is also acceptable.

From my test with a gaslamp, it definitely did drain me of nutrition but didn't absorb me until I re-enabled that to allow it to do it.

**Comment by TheFurryFeline** [comment]
Has this gotten any further discussions?

**Pull request merged**
