### PR TITLE
Cyborg transformation animation

### PR DESCRIPTION
**Pull request by Heroman3003**
Short transformation for module choice, icon choice and module reset from tg.
https://gfycat.com/SaneDeafeningIrishsetter

### CODE REVIEW

**Comment by Poojawa** [comment]
pff.

This is honestly better than what I cobbled together from Joan's code.

**Comment by Poojawa** [comment]
Also, yes I give you permission to port my scrubpup animation I made. the others are also in Citadel's mob/robots.dmi

**Comment by Heroman3003** [comment]
Okay, module reset seems a bit buggy atm, temoirarily no merging

**Comment by Poojawa** [comment]
TG calls 'ResetModule', which also allows for wire datums to work on the borg. very handy.

**Comment by Heroman3003** [comment]
tg has change of module itself as a part of transformation because they have the one-sprite-per-module thing. We have several sprites, and we have to play it for every sprite change, not just module change.

**Comment by Poojawa** [comment]
The service borg has multiple sprites for it's one module.

It's just having to manage all of these. :P 

Dogborgs are easier, relatively.

**Comment by Heroman3003** [comment]
They have the ability to choose a sprite, but not the "Do you like it or do you want to see other options?" window

**Comment by Arokha** [comment]
> if/when you get the ability to flick animations

We have this ability. Generate an image with `override = TRUE`, and pass it to flick_overlay

**Comment by Heroman3003** [comment]
Okay, closing for now until I find out what's wrong with and fix the animation on module reset.

**Pull request closed without merging**
