### PR TITLE
Space Traffic Update, Cleanup, & KHI Removal

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Since Selis hasn't responded to my request for an update on when #16574 will be ready, I'm posting this up now. I have not yet integrated the changes from that PR, but I could if desired (assuming I have clear enough instructions on what's being done and so on).

It makes some refactors to existing events for flavour and other adjustments, to somewhat-more-closely resemble actual ATC protocol. I have also added a bucketload of new generic ship names and made corporate groups draw from the core namelist in addition to their own namelists.

Also removes the ue-katish pirates, vox marauders, and widespread references to KHI, replacing the latter with references to various other extant companies.

Extensively tested, as always.

:cl:
tweak: adjusted a slew of traffic events and added an assload of new generic ship names, with most corps now using the generic names on top of their standard lists
rscdel: removed the ue-katish and vox marauders from events
tweak: removed widespread references to KHI, adjusting them to various appropriate companies
rscdel: purged the old busyspace module and replaced its contents entirely
/:cl:

### CODE REVIEW

**Comment by Heroman3003** [comment]
Wait, was KHI fully removed from lore now?

**Comment by Heroman3003** [comment]
KHI removal is not being sanctioned. If it needs a rewrite to bring its lore entry up to speed, that's what needs to be done, not it being removed entirely without proper lore consultations.

To review individual changes:

Universal core should either stay KHI or just be fully unknown. No morpheus involvement, they're brutalist kind of tech and cybernetics, not fine superadvanced nanite technomancy kind.

Poster change is kind of irrelevant either way, not needed, but also not really of importance if it does go through

Sleeving cure could probably use a brand new name entirely, rather than X Cure. It was named back in time when Kitsuhana was the source of resleeving as technology, now that resleeving has been reflavored to be more widespread and common, the medicine could have some more proper name.

Keep KHI references in air traffic

Do not remove them from cataloguers

Do not remove their uniform names

NIFs should stay as a KHI thing

Resleeving/medigun being made Vey-Med and combat guns being made Hephaestus is fine

The Sleevecard could be either Vey-Med or KHI

**Comment by Heroman3003** [comment]
I don't see why you want uniforms to not be named KHI in loadout or in description, but *shrug

Either way will send for staff to discuss as this reignited talks about actual intended state of KHI a bit.

**Comment by JoanRisu** [comment]
Just poking my head in here to ask the PR title be updated to include reference to the KHI stuff for documentation and to be clear from the jump what the PR is doing. I know you have it in the description already; with how much KHI stuff being combed through, it should be in the title.

**Comment by Heroman3003** [comment]
After discussion among the staff, and contacting the original creator of KHI, they requested that if we're not sticking with original lore, they'd rather it be removed anyway, so, uh. Sorry for confusion and extra work, but you can go back and scrub all references to them right back. The only changes from original requested is that NIF and technomancer core-related things shouldn't be Morpheus but Nanotrasen and KHI Nif should become just 'authentic NIF' (as path suggests)

**Pull request merged**
