### PR TITLE
Tweaks backpack/satchel sprites and readds straps.

### PR DESCRIPTION
**Pull request by Verkister**
The backpacks and satchels are no longer missing their straps and the satchels are no longer ridiculously bulky.

### CODE REVIEW

**Comment by Heroman3003** [comment]
Praise be! Onmob satchel sprites are saved.

Although Im not sure if this is icondiff bot freaking out again or not, there might be something wrong with the Honketron sprite's west-facing direction...

**Comment by Verkister** [comment]
yeah noticed there was a little misclick that had dragged the dir instead of just selecting it

**Comment by Ketrai** [comment]
These can still do with being a bit less bright.

**Comment by Arokha** [comment]
I actually kinda liked the lack of straps! I think they clutter the human sprite a little too much (mostly for the backpack ones).

**Comment by Verkister** [comment]
Feel free to add a strapless bag as an option for those who prefer minimalism over recognizability.

**Comment by Arokha** [comment]
Conflicts with https://github.com/VOREStation/VOREStation/pull/11002

**Comment by Verkister** [comment]
waiting for a merge so i can un-conflict this

**Comment by Arokha** [comment]
Done! The new equivalent to `icons/mob/back.dmi` is `icons/inventory/back/mob.dmi`

**Pull request closed without merging**
