### PR TITLE
Redesigns the armory

### PR DESCRIPTION
**Pull request by Arokha**
Ok ok fine, not a shuttle. *I* thought it was a neat idea, anyway!

Redoes the armory, and changes some of the orderable crates.

image

The armory comes in three parts now: green, blue, and red, to correspond to the alert levels. You also get a free bald naked ghost.

* Green armory is basically normal sec officer gear. The equipment lockers are in here now, attached to the breakroom. Makes more sense than changing clothes and stuff in the conference room. There are spare shelves by the lockers for Protectors and Hunters made in R&D.
* Blue is always accessible to Warden/HoS, but they will be harsly bapped if they start handing out blue stuff for no good reason on green. 
* Red armory is locked unless on code red, and has different equipment than before (somewhat less). We also get messages when you switch to red so no 'let's go to red to grab guns and then change it back'.

The crates that changed are:
* "Weapons crate", removed. 40 points for 8 guns?? What? The two egun crate cost 50. Makes no sense. Also only had normal security officer access! Just let anyone order the whole armory I guess.
* "Laser marksman" crate removed. No "double esniper" crate. This is like military hardware, it'd be a special request to NT to get.
* "Combat armor" crate removed, this is supposed to be ERT armor
* "Tactical armor" crate removed, THIS is supposed to be BETTER than ERT armor
* All crates with guns and heavy armor altered to at least Warden access (some had normal officer access before, but were shotguns 'n stuff)
 
If you wanna be guncargo or rogue sec people just get an emag or an emitter, gosh.

### CODE REVIEW

**Comment by Chargae** [comment]
Seems a more sensible solution than the shuttle to me, though to clarify, does Blue and Red alert open access to normal officers in that part of the armory too?

**Comment by Arokha** [comment]
> does Blue and Red alert open access to normal officers in that part of the armory too

No, like the current one, the Warden or HoS (or AI) needs to open it for them or hand out equipment. S'not free access just cus' it's on blue/red. They can get to both doors on any level though since that little hallway is considered green.

Hmm, in thinking about that, it'd be nice to have a button inside each that bolts the door so you can bolt them open, yes? I'll add that now.

**Comment by SpadesNeil** [comment]
This is a far superior design. The only change I would like made is that the Code Red armory should be accessible by a button and blast doors, similar to our current setup. Likewise, the blue armory's right side door should also be a blast door or shutter.

One, blast doors are far more difficult for a criminal to bypass. Two, if the doors _do_ need to be opened, then a toggleable open/close is superior for what its use will generally be. I don't think we have a problem with security people leaving the doors open.

**Comment by SpadesNeil** [comment]
Marking "needs discussion" just to be consistent since the last one needed it but I for one see no issues with this change. Let's ask Security though and see what they think.

**Comment by HzDonut** [comment]
While the redesign is nice, this all still seems pointless and I doubt it'd actually solve the problem that's trying to be solved here but I guess the only way we'd know is by trying.

Additionally:
You should probably add some kind of sensor in there that goes off if people enter when it's not code red, I bet people will just hack open the doors (if there's no shutters) to get around the whole code red thing because 'fuck central and their pointless additional security, i need my guns!'.

Why remove so much gear from being ordered when one of the big things with the revision was 'just go to cargo to order things if you really need it'? That's just removing one of the alternate avenues people were pointing out...

**Comment by saysage** [comment]
I'd say thing which was told by other person in security channel of discord - some guns from Red armory should be moved to blue, or there should be a way to open Red armory without code red, because there are situations when those weapons are needed, but there won't be any way to change code due to lack of command, or existing command staff having scenes. Probably would be a good idea to, maybe, add to the Blue armory single versions of specific guns from Red armory, like a single Ion pistol and single 4-ammo capacity shotgun, while Red security will have usual Ion rifle and 7-ammo capacity shotgun (why the hell ever warden has it lying in the locker? I'd say that he would have another 4-ammo one, while 7-shot should be in Red armory).

**Comment by SingoDingo** [comment]
I don't see an autolathe in the new armoury, was that intentional?

Even if not a hacked one, I just find them incredibly useful to have for printing out things like extra handcuffs or replacement lights for example, and it's saved me a lot of time since it's addition.

**Comment by Arokha** [comment]
> the blue armory's right side door should also be a blast door or shutter

You get the same effect of being able to keep it open with the buttons I just added without also requiring you open it whenever the warden wants to walk through it, since you can just bolt the doors open, otherwise the warden would either need to open/close each time or walk out of their office, all the way down the hallway through the breakroom and get into Green that way if they wanted to drop stuff off for example. Or are you worried about security? Could make the wires on the doors unique for added "fun".

> I don't see an autolathe in the new armoury, was that intentional?

Yes, you can work with R&D or cargo to get additional ammo. Less "security is an island"-ness. There's ammo for all the guns, and if you want MORE, you can have it made by one of the departments that makes things (okay, well Cargo doesn't 'make' things but they 'make' things appear).

>  like a single Ion pistol and single 4-ammo capacity shotgun
There already IS an ion pistol in blue. It's on the table there in the topright. A shotgun couldn't hurt I guess, there's ammo right inside the door there, nonlethal ammo (the lethal shotgun ammo is in red). I figured the warden could use it for their shotgun they start with.

> Why remove so much gear from being ordered
The things I removed didn't make sense. The reasoning is right next to them in the list above. Combat armor is literally better than ERT armor, it should not have been in the game. Tactical armor is better than DEATHSQUAD armor, and should not have been accessible. "Weapons" crate is absurd armory in a box practically for free, etc.

**Comment by SingoDingo** [comment]
As much as I appreciate the sentiment of making the departments rely on each other, science can often take up to 10-15 minutes to handle even basic requests due to how insular and self absorbed they can be, and most of the things sec would have to ask cargo to print them would require hacking their autolathe (and in turn leaving it to nothing but faith that they’ll set it back). Having it there made sense for the purposes security would use it for, and adding the extra step in between often did little more than completely bar access to essential supplies when other staff were incapable of getting to requests in time.

**Comment by Arokha** [comment]
Like I said, there's ammo for every weapon in the armory, in the armory. If you want a large surplus, get it made. There's no bar to using any of the weapons in the armory, especially considering there's four lethal energy weapons in there that can be recharged, and several spare batteries (not to mention that baton/taser/egun/carbine batteries are all the same battery). I really fail to see how this will become a critical situation unless you're like "I used both boxes of shotgun shells but the shotgun is my FAAAVORITE"

**Comment by Dankman** [comment]
OH GOD WHAT WILL WE DO THERE'S NOT GONNA BE ENOUGH GUNS TO FIT INSIDE ALL THESE PAWS

THINK OF THE PAWS ARO

THINK OF THE PAAAAAAAAAAAAAWS

but for real this is a pretty fucking awesome update, looking forward to seeing if this affects interdepartmental dynamics in a better way. I like providing things for people who ask for shit as science, provided it's a reasonable request and not just ''yo gimme like twelve boxes full of lethal shotgun ammo and a handy under the desk'' like nah bitch fuck that, shit prints out one shell at a time if i remember right, that's a shitload of labor, lol.

**Comment by SingoDingo** [comment]
It mostly comes down to not wanting to rely on busy (or often dead) scientists each and every time there’s a shortage of any type. Rechargeable laser weaponry is fine and dandy, but when someone is going around in albative armour and you only have a box or two of ammo between four people it really wears thin quickly.

**Comment by Arokha** [comment]
Made the red armory have 'vault' wires, so now it's more annoying to hack. Don't really wanna put blastdoors since I don't like the idea of "there's just no way to open these mechanically ingame other than the button". Seems hax. (It's easy to just cut through the walls anyway, as it was on the previous armory)

**Comment by Natje0** [comment]
"Each and every time there's a shortage of any type"
Why the heck would there be a shortage in the first place??
The rare times there's anything to shoot at, it usually dies from a handful of shots from *anything*.

**Comment by SingoDingo** [comment]
> The rare times there's anything to shoot at, it usually dies from a handful of shots from anything.

The rare times there’s anything to shoot at, there are a LOT of things to shoot at, from personal experience.

**Comment by Dankman** [comment]
doomsday preppers tier preparedness for the off chance that something might happen seems a bit powergamey imo. if you're always ready for everything, then there's never going to be any real challenge that can be offered beyond making things be insane, which is why there's probably usually a lot to shoot at, because it's known that people armed themselves to the teeth and it's the only way to stop any kind of event from instantly falling flat because urist mcbeard decided to cover himself in ten shotguns.

**Comment by SingoDingo** [comment]
I’ve been told multiple times that removing something from security will result in less events where it would be needed, and every time that turned out to be wrong. Excuse me if it comes across as a bit untrusting of the admin team, but I’ve very well seen that they’re not some kind of hivemind. If making events less threatening isn’t _actively enforced_ then I very much doubt one admin removing tools from the security’s arsenal will make a completely different admin lower the tone of their event in accordance to that unless they’re specifically told to.

Maybe events have become more passive over time and I’ve just missed the more recent ones, but I somehow doubt this will actually effect the potency of any combat situations here on out.

**Comment by Arokha** [comment]
Nobody has said removing anything from security will somehow make it less needed. I'm sure the two e-snipers that are in the armory now would be really useful in the event of mercenary attack.

But we don't want that. We want security to actually have a challenge, and we want to be able to give merc antags the ability to actually challenge security. As it is, unless we give the mercs pulse destroyers, why bother?

**Comment by SingoDingo** [comment]
> We want security to actually have a challenge, and we want to be able to give merc antags the ability to actually challenge security.

Then remove shotguns or shotgun slugs from the armoury entirely, considering how much damage they do even through armour. The only way mercs can challenge security is by getting laser resistant gear, considering just about every officer would have some sort of laser weapon by the time things reach code blue, and taking into account how little laser resist most all-purpose armours give. Considering a shotgun slug can 2-3 shot a heavily armoured target with a shield, someone with laser defences probably wouldn’t survive 1-2 hits at best.

**Comment by Arokha** [comment]
Ace reaaaally likes shotsguns. I already expressed my thoughts internally on energy weapons being 'the thing' since future and electricity is free whereas bullets are not, but sooome peeeople really like ballistics so I can't get rid of 'em. :p

**Comment by SingoDingo** [comment]
Replacing the slugs with buckshot and buffing laser defence on all-rounder armours would do the trick nicely. How easily available lasers are, and how all or nothing laser defences tend to be, would make them a total no brainer if security can’t make their own ammo.

**Comment by HzDonut** [comment]
> 'The things I removed didn't make sense.' The reasoning is right next to them in the list above. Combat armor is literally better than ERT armor, it should not have been in the game. Tactical armor is better than DEATHSQUAD armor, and should not have been accessible. "Weapons" crate is absurd armory in a box practically for free, etc.

I _see_ your reasoning for removing them, and I just suggested you simply nerf the armor and weapons crate instead of removing them completely.

**Comment by Screemonster** [comment]
Unfortunately cargo aren't very good at telling the doomsday preppers to fuck off.

Remember the "MILITARY WEAPONS, EMERGENCIES ONLY" crate back on boxstation? Yeah, science would bug cargo for one literally every round because apparently "weapons research numbers aren't maxed" qualifies as an emergency.

If there's going to be any kind of crazy shit like that available through cargo, cargo should _also_ have a security code lock and the price should be a lot higher than "40 points to replace armory".

**Comment by SpadesNeil** [comment]
I lament the removal of the autolathe but Aronai makes a good case for its removal.

**Comment by SpadesNeil** [comment]
>I see your reasoning for removing them, and I just suggested you or someone else nerfs the armor and weapons crate instead of removing them completely. Is there any reason why that wouldn't work?

Nerfing it defeats the point of it existing. It's currently a "balanced" middleground armor for all situations that specializes in none.

It also removes any incentive to use the specialized armor.

If we nerf it much more it will be worse than hardsuits. Then we have to nerf hardsuits. Then we have to nerf more stuff. Then we have to nerf more stuff after that.

_Or_ we could just remove the incentive to use jack-of-all-trades armor by taking it away.

**Comment by Arokha** [comment]
I'll point out you can order normal armor just fine. Also if we nerf it, that's nerfing deathsquad armor. That armor is LITERALLY the armor deathsquad is supposed to get if they aren't using a rig.

**Comment by saysage** [comment]
Why not to remain one single armory, but seriously rework it's contents? Make it be one-and-for-all-situations, five lockers with combat armor, two shotguns, two SMGs, one laser carbine (because it's actually a devastating weapon MUCH scarier than any laser canon, actual monstrosity with 400 to 600 total damage output, which makes me question why do people underestimate it, specifically, as it was told before, knowing how little armor has high protection against lasers), ion rifle. This armory should not need any specific Code to be opened, with either Warden, HoS or Director being able to open it, but there **for sure** should be some kind of mechanism to notify heads and other security about Tactical armory being used. Message to the main radiochannel would be a little over border, due to panic being inevitable if, let's say, combat is only possible to occure but if it will, will need not to tell on main channel that security already knows and is prepared, for any potential enemy near to intercomms to hear it. Or for people just not to panic before actual explanation from heads.
Plus, would also be balanced to place ion pistol, two e-guns along with some rubber and lethal handgun ammo in the "pre-armory", which would be a small room between Tactical armory and warden's office - lightest of lethal weapons for situations like slimes, rogue borgs and hostile mobs, which don't need to be armored like a tank and bear automatic weapon or laser rifle. Having something resticted to the Codes is not the best idea if it raises so much controversion, but for sure some kind of protection from just taking SMG for fun as a warden would be needed.

**Comment by saysage** [comment]
And, if something MORE POWERFULLER or in greater amounts would be needed, always can use Cargo. Which would actually be useful then.

**Comment by Arokha** [comment]
> and making it use specific, bulky power cells

I made a comment in the admin chat to that effect:
`kinda eh about too many batteries, maybe it shouldn't be the same batts for smaller guns as for heavy weapons? since your taser's battery is the same as the carbine's...`

> five lockers with combat armor, two shotguns, two SMGs, one laser carbine

This is too much, IMO. SMGs are silly, and combat armor is too good, which is why it's being removed from availability altogether with Tactical armor.

I'll point out that Green/Blue are not code locked, only Red, sorry if there was a misunderstanding about that. Blue is always accessible to warden/HoS/CD. Red with the ion rifle, lascarbines, and lethal shotgun stuff is not.

**Comment by saysage** [comment]
Well, not combat armor maybe, but something what would be good as uniformal, universal armor for any situation - i.e. not a highly specialised armor, with ablative/bullet-resistant being able to be, as well, ordered in case of expecting enemy will have only specific kind of weapons. Maybe Riot armor would be good for Blue, as it's useless against anything but melee. 
In my original thoughts it was, 5 lockers with armor because 4 for officers, 1 for warden/detective who might join, but 4 would be suiting good as well. 
SMGs are good because those are an often-seen weapons in hands of law enforcements, security and cops. Low-caliber, compact and fast-shooting, which makes it a much better weapon for swift operating than 10-shot monsterkiller in some situations. I might be as well wrong, but it feels like a good thing. Of course, all up for discussion.

**Comment by Arokha** [comment]
> uniformal, universal armor for any situation

This is why it's being removed. See Ace's quote.

**Comment by saysage** [comment]
Ehhh, I personally would prefer few universal armor suits over ton of different-typed, mostly because in case of need to have protection from specific damage, there won't be only 2 ablative/bulletproof vests for 4 officers, but that's just imo, in terms of balance and interest Ace might be right.

**Comment by Dhaeleena** [comment]
well sadly we cannot make everyone happy, I like this armory, I like it this way

**Comment by saysage** [comment]
> well sadly we cannot make everyone happy, I like this armory, I like it this way
True, that's why I don't complain, only suggesting stuff. Any armor is better than running at syndie in red pants only :^)

**Comment by Dankman** [comment]
security shouldn't be running at syndies anyway, that's what the ERT is for lmao.

**Comment by saysage** [comment]
If security has to call for ERT to shoot some pussies in red spacesuits, they are even worse pussies. You have laser carbines, having one allows you to make a mess outta syndie even if you have no armor, and armor makes you win even if you are worst robuster ever.

**Comment by Dankman** [comment]
security isn't supposed to be an army lol

**Comment by Screemonster** [comment]
This is a high-RP server, play literally any other server if you consider robustness to be the be-all and end-all of security play.

**Comment by Dankman** [comment]
bellybrig is the true security meta

**Comment by saysage** [comment]
Security is supposed to protect corporate resources and crew from both inside and outside threats, and if they are unable to fight back mercs raiding Tether - what's the use for them outside of telling people not to walk nude in public?

> This is a high-RP server, play literally any other server if you consider robustness to be the be-all and end-all of security play.

Didn't say that it isn't, but if it comes to fighting with syndies as a potential situation due to events, it's extremely hard to have really no chances against them with all the treasures of armory.

**Comment by Screemonster** [comment]
Maybe we'd like to have literally any event other than a full-on mercenary raid, because right now a full-on mercenary raid is the only thing that comes close to stretching sec's roundstart resoources.

**Comment by saysage** [comment]
Fair enough. That's, probably, one of the main reasons this discussion had began, nerfing armory to make it less OP. Which is actually very hard, as different people will always have different look on how many guns and of which type (energy/ballistic) should be present. Sometimes balancing things out is taking way more time than it should...

**Comment by SpadesNeil** [comment]
Even on servers with robust security and low RP, balance is actually even _more_ important. The armory we currently have is absurd even by _their_ standards.

**Comment by SpadesNeil** [comment]
Anyway I think most of us are in favor of these changes.

**Comment by saysage** [comment]
Would laser carbine be reworked as well later, or should it be made into other issue? It's really putting punch strong as hell, even more powerful than so out-of-place looking esniper.

**Comment by Arokha** [comment]
If the carbine is super OP it can be reworked, but not really part of an armory redesign.

**Comment by SpadesNeil** [comment]
Oiii, don't take away the detective's revolver if that's what you just did.

https://wiki.vore-station.net/Standard_Operating_Procedure#Detective

SoP specifically allows them to carry lethals for self defense only. It's also one of the worst guns in the game so just let them have it.

**Comment by Arokha** [comment]
I did, yeah. You may have missed the conversation in the admin chat where we decided to remove that from the SoP. Maybe I missed that line.

**Comment by Arokha** [comment]
Talk later in admun chat to try and make your points about det revolver, and we can do whatever about that in another PR (putting things on lockers on the map is silly anyway, probably better to just add them to the locker in code), but we decided to remove it from the SoP when it didn't match other parts of the SoP that weren't updated to say 'well also this ONE guy can carry lethals whenever' since some parts said 'no security at all on green can'.

Mostly my gripes are that nobody's offered me a reason I think is logical for detective to carry lethals:
a) "They can't be trusted with LTL because they might overstep their authority and misuse it to arrest people, and this forces them to consider their actions better"
b) "They might get attacked by someone they are investigating"
c) "Noir"

To which I say:
a') "You mention in your reason that you don't trust their judgement with weapons, why give lethals?"
b') "Security officers are far more likely to encounter physical violence, but even if a detective does get attacked, they should still be trying to detain them"
c') "Gaaaaaaaaaay"

Not to mention, overall, the goal of security is to arrest people, never to kill them. The only time sec should be killing people is when there are so many hostiles or they are so well armored that there's no hope but to keep up with the more powerful lethal weapons.

**Comment by Screemonster** [comment]
The detective locker spawns with a detective gun box that they use in hand and lets them choose from a revolver or a .45 automatic. This was added upstream after we manually added revolvers to the lockers, making our revolver-addition redundant.

**Pull request merged**
