### PR TITLE
Merge pull request #399 from VOREStation/master

### PR DESCRIPTION
**Pull request by Arokha**
New Release

### CODE REVIEW

**Comment by SpadesNeil** [comment]
:+1:

**Comment by SpadesNeil** [comment]
Wait why is this blank?

**Comment by Arokha** [comment]
OH didn't see your question. It's a dumb thing you need to do after merging master into release, that you then have to merge the single merge commit from release back into master otherwise next time you go to merge master into release it will tell you that master is 'behind' release because it's missing that one merge commit.

**Comment by SpadesNeil** [comment]
https://www.youtube.com/watch?v=KufiqCh3Qd4

**Pull request merged**
