### PR TITLE
Makes elevator permanently powered

### PR DESCRIPTION
**Pull request by Heroman3003**
This includes lights inside and the doors.

There have been multiple discussions, but always one of the biggest problems with Tether brought up is how power outages guarantee problems doing even basic task due to elevator stopping working, and only alternative being a way-too-restricted, unreliable and still sorta-power-reliant backup shuttle.

Putting as separate PR because decision may be controversial.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Do me a favor and make the elevator permanently fullbright as well.

The lighting is all fucked up. Just delete the lights and turn off dynamic lighting so it's always lit.

**Comment by Heroman3003** [comment]
Dynamic lighting is already off INSIDE elevator itself. Lights in there are not affecting anything

**Comment by SpadesNeil** [comment]
>Dynamic lighting is already off INSIDE elevator itself. Lights in there are not affecting anything

Why are the walls blacked out, then? You can't even see the button.

Also, marked this as requires discussion. The shuttle mechanics right now are bad. I am okay with this as an alternative until the shuttle is made less bad. The question is if everyone else is.

**Comment by Novacat** [comment]
Not really that controversial. Elevator problems have been the main downside of the Tether for a long time.

I think there is a mirror PR that fixes the lighting issues, however.

**Comment by Heroman3003** [comment]
Walls are dark because walls are not same area as inside of elevator. I will try disabling dynamic lighting on them too and see if this looks good on blackout.

**Comment by Novacat** [comment]
Also, possible suggestion: Adding a relay to the midpoint. One of the other things that annoyed me about the Tether was that any radio transmissions to and from the midpoint would be lost completely.

**Comment by TheFurryFeline** [comment]
@Novacat #4658 updates lighting, yeah.

**Comment by Heroman3003** [comment]
Alright, lighting fix seems cool and working.

**Comment by Very-Soft** [comment]
just to point out to make sure, this affects the doors, yes? The elevator itself normally works even when there is no power, the main issue tends to be that people crowbar open the doors at their destination, and then run away without closing them again, which makes it so the elevator can't move.

**Comment by Wickedtemp** [comment]
Yuh, includes the doors!

**Comment by Wickedtemp** [comment]
Lemme know if anybody comes up with a good reason to be opposed to this.

**Comment by Wickedtemp** [comment]
20 days and no reason not to merge. I feel like we can just add it in and get the problems fixed.

**Pull request merged**
