### PR TITLE
Atmta Port

### PR DESCRIPTION
**Pull request by NTestuya**
After several attempts, I seem to get it correct now. 

This idea wasn't well liked in Discord since people preferred RP, but it's a port and translation of ATMTA's "interaction.dm" file. It's similar to lifeweb's ERP sex system where you drag a mob onto another mob.

I didn't include it for all species, but the flags are easy to add in the interactions menu. Just to make it easy on everyone, changes are denoted by "ATMTA" comments.

### CODE REVIEW

**Comment by Eearslya** [comment]
```
code/modules/mob/living/carbon/human/interactions.dm:234:warning: ya: variable defined but not used
code/modules/mob/living/carbon/human/interactions.dm:614:warning: ya: variable defined but not used
code/modules/mob/living/carbon/human/human.dm:711:error: : missing expression
code/modules/mob/living/carbon/human/human.dm:747:error: : missing expression
code/modules/mob/living/carbon/human/human.dm:749:error: : missing expression
code/modules/mob/living/carbon/human/human.dm:755:error: : missing expression
code/modules/mob/living/carbon/human/human.dm:661:warning: ya: variable defined but not used
code/modules/mob/living/carbon/human/interactions.dm:151:warning: ya: variable defined but not used
```

```
../../VOREStation/VOREStation/code/modules/mob/living/carbon/human/interactions.dm
	<b> - Excess of 2 closing tag(s)
		Line 438
		Line 436
```

**Comment by Screemonster** [comment]
Cramming all this stuff into places like human.dm is gonna make future updates to the core game from Polaris a nightmare to maintain.

**Comment by SpadesNeil** [comment]
I'm under the impression that the community doesn't even want these. Even Citadel didn't want them.

**Comment by Cameron653** [comment]
Closing this since it's incorrectly ported to our code, would cause mass problems porting things from Polaris, and doesn't add much to the server.

**Pull request closed without merging**
