### PR TITLE
Removes /obj/item/weapon and /obj/item/device

### PR DESCRIPTION
**Pull request by TheCaramelion**
Most noticeable change would probably more items allowed to cleave, otherwise- This gets ride of things like /obj/item/weapon/paper

### CODE REVIEW

**Comment by TheCaramelion** [comment]
Haven't seen much game-breaking stuff, everything seems to be working

**Comment by TheCaramelion** [comment]
Oops I realized a big silly mistake :)

**Comment by Heroman3003** [comment]
Alright this will need one more deconflict, but im prioritizing this next time. Sorry again.

**Comment by Heroman3003** [comment]
Dream Checker is failing, gonna need to comb through the diffs and find where its finding issues.

**Comment by TheCaramelion** [comment]
> Dream Checker is failing, gonna need to comb through the diffs and find where its finding issues.

Oops, I forgot the icon for the tape/tape recorder

**Comment by Heroman3003** [comment]
Still has errors.

**Comment by Heroman3003** [comment]
code/_onclick/item_attack.dm, line 45, column 32:
error: an override of /obj/item/proc/resolve_attackby is missing keyword args
- code/game/objects/items/weapons/id cards/cards.dm:106:37: /obj/item/card/emag is missing "attack_modifier"
- code/game/objects/weapons.dm:40:6: called with "attack_modifier" here

[2024-09-28T04:20:41] Runtime in code/_helpers/unsorted.dm,1510: /obj/item/tape/random does not have a valid icon state

**Comment by Heroman3003** [comment]
It seems part of contradiction comes from the fact that there was an /obj/item/tape and /obj/item/weapon/tape and the two are entirely different objects. Look into that.

**Comment by TheCaramelion** [comment]
OKAY, that should have been all tapes. There was a /obj/item/device/tape and a /obj/item/weapon/tape

**Comment by TheCaramelion** [comment]
Seems like I forgot a map. I'll get on it soon.

**Pull request merged**
