### PR TITLE
Adds tentacle taur sprites

### PR DESCRIPTION
**Pull request by viv-eret**
Updates taurs_vr.dm
Updates sprite_accessories_vr.dmi

Preview picture pending.

((Please do excuse some of my sloppiness. Github is hard.))

### CODE REVIEW

**Comment by Cameron653** [comment]
Sprites: http://puu.sh/pBoHW/e41941d8c2.png

**Comment by SpadesNeil** [comment]
Now these look very nice.

**Comment by viv-eret** [comment]
It doesn't?

**Comment by viv-eret** [comment]
Lemme see when I get on my PC.

**Comment by viv-eret** [comment]
What was the issue with it? The other taur PR is closed.

**Comment by Cameron653** [comment]
This PR has the slime_s sprite in the taurs_vr.dmi file.

**Comment by viv-eret** [comment]
Oh. Lemme fix that. It'll be like 20 minutes.

**Comment by viv-eret** [comment]
Done.

**Pull request merged**
