### PR TITLE
Communicator + NIF Refactor

### PR DESCRIPTION
**Pull request by Arokha**
Refactors NIFs slightly:
* They now save your commlink name, so you can be named "FoxMaster 9000" each shift or whatever.
* Now work properly on species that don't have their brains in their head (and expect to be put into whatever organ that has the brain)

Refactors communicators slightly:
* Allows you to set the name without providing a mob (no mob-related features/vars were ever accessed so it was basically pointless)

### CODE REVIEW

**Comment by Dhaeleena** [comment]
Can you make this happen with PDA ringtone?

**Comment by Arokha** [comment]
Nope

**Comment by Little-119** [comment]
> Now work properly on species that don't have their brains in their head (and expect to be put into whatever organ that has the brain)

Does this mean prometheans don't need the bioadaptive NIFs?

**Comment by Arokha** [comment]
> Does this mean prometheans don't need the bioadaptive NIFs?

No, that's a gameplay thing, not a bug. It does mean you need to put them into their torso now though.

**Comment by Little-119** [comment]
Seems odd to me that you need to fax CC to get an admin to bluespace one in, in that case.

**Comment by Arokha** [comment]
Not super-related to this PR, tbh.

**Pull request merged**
