### PR TITLE
Makes Xander Bevin spawn in a random belly in the world

### PR DESCRIPTION
**Pull request by Heroman3003**
As is meant to be and always was

/s

### CODE REVIEW

**Comment by AegisOA** [comment]
**RUDE**

**Comment by AegisOA** [comment]
**EVEN RUDER**

**Comment by Heroman3003** [comment]
Requested changes implemented

**Comment by AegisOA** [comment]
**i swear to god**

**Comment by TheFurryFeline** [comment]
Get fucking bullied, nerd. @AegisOA <3

**Comment by AegisOA** [comment]
_**i'm being bullied super hard and i want to SCREAM**_

**Comment by KasparoVy** [comment]
Big red button it

**Comment by KasparoVy** [comment]
Into the river below

**Comment by Arokha** [comment]
> Big red button it

Red? Green.

**Pull request merged**
