### PR TITLE
[WIP] Yet another kitchen overhaul. V5.0

### PR DESCRIPTION
**Pull request by Ketrai**
Post updated with new design, seeing as no one liked the previous design.
P.S Please, please stop dropping huge ranty posts. Try and keep feedback/criticism more concise. Use bullet points with numbers. It's hard to read through, and an instant downer mood-wise. It's okay to be angry, just don't make me feel like I'm being attacked on a personal level. Please avoid responding with emoji's to the main post, as it will get updated. In case your initial opinion no longer reflects the changes.
P.P.S If someone has already stated something you agree with, please just mention the points you agree on rather than make a new post constantly relaying the same information as the person above. 

b l e p

OVERVIEW V5
image
Closeup V5
image
OLD
image

### CODE REVIEW

**Comment by Heroman3003** [comment]
IMO,  maybe connecting bar and kitchen by doors would be good, but making it all one giant table the way it is misses the ability for bartenders to be able to stand by their workplace (aka the dispensers) and still see their entire counter. And generally it just kind of looks dumb to have one oversized table span like 4 different rooms worth of counters, imo.

**Comment by Ketrai** [comment]
> IMO, maybe connecting bar and kitchen by doors would be good, but making it all one giant table the way it is misses the ability for bartenders to be able to stand by their workplace (aka the dispensers) and still see their entire counter. And generally it just kind of looks dumb to have one oversized table span like 4 different rooms worth of counters, imo.

The grand majority of counters, including those of the chef, are within the bartender's view. 14/20 seats. Either the bartender can move around a little for shy clients, or they can creep closer. The long counter is taken after big buffet restaurants, or all you can eat. You can't fit as much food on an ss13 counter as irl, so they have to be a bit longer to get similar effect. I decided to extend it towards hydro too, so the botanist feels less like they're locked up in their own bubble. Just making a huge buffet that stretches all of the northern counter, should be a ton of fun. At least towards the people interested. We've got quite a couple big buffet cooks.

**Comment by Ketrai** [comment]
image
Example of the counter. I don't think it looks that weird, other than the blots of empty space. If anything, a different kind of counter place intermittedly to make the whole look more sophisticated, could be a nice addition.

**Comment by dwinters99** [comment]
The entire point of the kitchen rework was to eliminate the problem of the kitchen being too big and unwieldy. This returns it to that state as well as reintroducing the issue of there being ways to have multiple screens worth of people in the bar. I also do severely hope that that vending machine placement is not permanent because *wew*. In fact, almost ALL of the problems the service rework fixed are being reintroduced here. I'm unsure who "a lot of people" are but they seem to have drastically different opinions compared to what was posed last time the kitchen required a rework. 
This also separates botany from xenobotany, which is very problematic. 
The freezer is two times larger for anomalous reasons, botany is now far less customizable without fixing the issue of making it easier to access. 
The bar is now way too big to the point that three entire groups of people can exist within it without seeing each other.  
The bar counter is also now gigantic to the **OUTRAGEOUS POINT THAT THE BARTENDER CANNOT SEE ALL OF THEIR PATRONS.** 

It doesn't seem as if the scale of the in-game viewport was considered if the massive fields of dead space though oddly enough, it also seems like table-space has been removed in favor of the worlds biggest and silliest counter and more dead space which is what most of the people working on the map are attempting to eliminate and is the single biggest issue with the current map. I desperately hope this is an extreme early version and that this isn't even close to a release candidate.

**Comment by SweetBlueSylveon** [comment]
Given I made the last rework of botany, xenobotany, the kitchen, and the bar, I feel I should comment on this. This rework removes so many fixes that I implemented to increase cooperation and accessibility. For starters, the bartender cannot see all of the patrons in the bar with this design. With my rework, I contacted 10+ players for every job I affected save xenobotany, for which I only contacted a few. However in your screenshots, you seem to have done nothing with xenobotany as of yet. The botany setup was co-designed with Callen, azura, Clara, Maddox, and several others. The only complaints I received about botany while designing and after pr'ing the former rework were solely from people who did not often play botany. Same goes for the bar. The only one I consistently had any negative feedback for was the kitchen, for which I got a resounding "It's better than before at least." I'm open to my designs being changed or replaced, but this is just a flat out not good design, right off the bat.  If this gets merged, I think that would be enough to keep me from those jobs and areas altogether.

**Comment by Enzo-Leon** [comment]
This leaves way too much to be desired and I agree with @dwinters99 100% on all their same points here that I would of covered.

**Comment by Ketrai** [comment]
@dwinters99 roiz, lindy come to mind immediately when talking about big buffets. Lindy specifically mentioned a desire for the old 9 tiles of counter space. As big as you all like to make a deal out of the visibility issue. You should know I measured out the distances carefully so the grand majority of spots can see the chef or bartender at the edges. If it's that big of a deal I can just shore up the bar by three spaces. As for the kitchen size it's about a single row bigger than the previous kitchen. I can easily scale that back,  but I wouldn't say it's unwieldy. At least with this kitchen design the chef won't have to crawl into any corners. Also, I've found myself lacking space at times when I start calling in cargo orders. It's nice to have a slight of free space.

@SweetBlueSylveon the biggest issue with botany was the lack of setup. There's a couple botanists who would just screw out three trays and grow them in the side room, because having to drag 12 trays through a door is quite a lot of work. I've not seen many custom designs. I did like the integration of botany with xenobotany, but I don't feel like it warrants putting the botanist in their own faraway corner. If customization is that much of a concern, can easily expand botany north  to have large swathes of empty space for them to play with. But the easy preset trays down below should definitely stay. The job of a chef is pretty involvent. A middle ground should be met between those who play dedicated botanist, and the chef that feels forced to grow crops quickly to fill orders or to get a broader range of recipes. The most consistent complaint I've seen is about the trays not being set. I can go through discord history to gather you a list of people if that makes you feel better.

@dwinters99 yeah the freezer is big. I wasn't sure how to fit it all there. Can just move some closets around to get it all fixed.

@SweetBlueSylveon I've no clue what game room you mean. The flashy blue room wasn't touched. I've taken care to replace features that were already there and others are still pending like the service belt. I literally just asked for feedback, clearly stated that this is a wip, and you're already yelling at me like I've murdered someone. 

@dwinters99 Regarding edit 3, I feel like you're missing a big part of the appeal of a large counter here. If you stack 1000 burgers on a tile, you won't be able to see every individual burger. It looks messy at that. Many cooks like to click the counter carefully to neatly line up their items. When you only have 7 counters, the amount of items you can neatly display is quite small. 

@dwinters99 edit 4 has me more confused than anything. We're making the asteroid smaller? With all the recent expansions to tether 3, kost notably the much larger public garden... this seems like a moot point. 

@dwinters99 regarding edit 2 : chickens don't have a map sprite. But they do exist there. The animal area felt rather cramped to me. This way it looks more like a petting zoo. Some folk like watching animals wander a large space. 

@dwinters99 regarding edit 1. I already said some stuff on this. But thanks for accusing me of not making any considerations, I literally made a visual aid in my spriting program. And then pulling in ds13 for some weird reason even though I'm not a mapper there. And if you've seen the map it's relatively compact save for a few exceptions. At this point maybe the limited view in big areas is a code issue as well. Warranting an 8 tile or 9 tiles radius when in a large room that's pre defined to zoom according to the area tag, with a toggle in preferences. Either way. That's not to say I'm not going to shrink the counter a bit either way. I also don't think it's wholly possible to guarantee a single screen of people to fit the entire bar without making it feel cramped at the same time. Especially to include a bit of botany, a nice circular counter, and the game table.

**Comment by Ketrai** [comment]
Goin to sleep soon. Here's a list of planned try-outs/changes and requests. 

- window access. Possibly south or east.
- 3 tiles less so every seat is represented. 
-  botany expansion. Maybe fill up part of the empty space that way.
- figure out a good spot for machines. 
- smaller freezer, should be automatic consequence of squishing the counter length. 
- some sort of xenobio connection. No promises though, if it requires bigger map changes than I'm comfy with it'll have to be a sacrifice for now.

**Comment by Very-Soft** [comment]
Not a fan of this change. It has some good things about it but it just looks crazy, and I very much do not like the merging of the bar and kitchen spaces. There is also SO MUCH 1 wide path space in the kitchen. If you need to move anything solid through there or there's ever more than 1 person in the kitchen, you're gonna be stepping on eachothers' toes constantly.

The tabels in front of the microwave seem kind of pointless too, being as you can't actually reach the table from where you use one of the microwaves. I think that space would be better empty, because it offers a way to get around someone who is working at that station. 

And I donno, I REALLY REALLY do not like the layout of the big long fuckhuge bar table. Like, I think the kitchen as it is isn't too bad, botany just needs to be less huge, and ought to have a table that's visible from the main hall. I THINK the kitchen could use the same, so you don't have to go into the bar to get a bite to eat. 

I appreciate the effort on this design, but the main things I don't like about it really outweigh the benefits imo. Would prefer something totally different to this design.

**Comment by Rykka-Stormheart** [comment]
@dwinters99 @SweetBlueSylveon and @Very-Soft have covered most/all of my points of concern, and I agree in that I feel that the rework reintroduces a lot of pre-existing problems in addition to leaving a lot of filler space, requiring the duplication of growing areas for xenobotany, poor ability to navigate the kitchen with more than one person, an inability to access the machines, and also: the cooks will have to run back and forth like a headless chicken between the microwaves and the main cooking machines.

Also, the large counter unfortunately just feels... awkward. I wouldn't necessarily mind if bar + kitchen had a co-joined counter and the like, but the way this has been done, it feels like without waiters and staff moving around, there's going to be a lot of running around, and it feels like a massive step backwards.

**Comment by Sinbest** [comment]
You somehow managed to make the bar feel both smaller and bigger at the same time, good work. Other than that, don't really like this change, having botany look right into the bar is a bit weird and there is **far** too much counterspace now, also what are we going to fill the extra space with?

**Comment by Ketrai** [comment]
This is the history post . As I update the main post with newer images.
V1
AFTER image
BEFORE image

**Comment by Very-Soft** [comment]
image
I actually don't hate this design for some things, like the bar having windows again, but you are making the bar fuckhuge again, with LOTS of places to hide from surrounding conversation, which is why the bar got redesigned in the first place. 

When there's one huge place for everyone to hang out and not have to worry about being inconvenienced by there being a lot of people there, then there is no reason for anyone to pay any attention to or even try to seek out alternatives if the present arrangement is not to their liking.

The present bar design could be a little less cramped to offer some more seats, but it achieves what it sets out to do well. It is the main hangout spot, but you can't really hide from the crowd there. If there's lots of people there, and it's too loud, you need to roam to seek an alternative, which helps every other roleplaying job, or people hanging at the desks to their jobs be discoverable. 

I very much do not want to return to everyone always being in the bar if they are not actively working, that hurts every other kind of general roleplay by making the bar the only place one can reliably find anyone. People should be encouraged to wander if the place they are at is at is not to their liking, but if you know that everyone who is not working is at the bar, why would you go anywhere else?

As such, the bar (or any social place) should not be so big or designed in such a way that many groups of people can exist secluded from one another. The cafe is a decent example of this design in decent practice. You can get KIND OF secluded in the cafe, but most of the seats are close enough together that if the place is busy, it's loud.

This design is MUCH too big, with FAR too many places to hide from other people.

**Comment by Rykka-Stormheart** [comment]
I like the newer iteration, as discussed in dev-general, I still feel the space between counter and machines should be two-tile rather than one-tile, but the author has stated they'd like to test and see if one-tile is workable.

I personally prefer chairs for the private booths, or some 2-tile tall couches, but the full couches wrapping around the entire tables looks a lil awkward.

Beyond that though I really like this. I especially like the additional seating where the old service corridor was - it gives an excuse for waiters/waitresses/servers to do their thing, which was sorely lacking in the current design. Now we can eat the waitresses and lament the lack of service staff. <3

**Comment by Ketrai** [comment]
@Very-Soft 

1. I'm personally not a fan of many hidey-holes either. Gives I mostly just hang around at the bar counter myself. But some folks have asked after more secluded spaces in the bar again. So you can take your roleplay in the bar to the next level, without having to go all the way to the dorms, or having to tune in to the conversation around the bar. The bar does feel a bit big because of them, and whilst I don't think entirely cutting out the private spaces is a good idea, I can reduce the number of spaces by removing the current private booths and building them at the window to the right instead.

2. I don't feel like purposefully cutting down on bar capacity is the right idea to force people to get out there and roleplay more. Events and jobs do a much better job at that. On lowpop it doesn't matter because the bar will always have too many seats. I don't visit many highpop shifts, so someone else will have to tell me how it goes there. I just feel like providing more random, coded events, should be prioritized.

**Comment by Ketrai** [comment]
> I do actually kind of like the kitchen design and placement though. That would make it pretty perfect for adding a small table in the hall so you could put food out there for people passing by. UWWU

Like this?
image

**Comment by Very-Soft** [comment]
> @Very-Soft
> 
> 1. I'm personally not a fan of many hidey-holes either. Gives I mostly just hang around at the bar counter myself. But some folks have asked after more secluded spaces in the bar again. So you can take your roleplay in the bar to the next level, without having to go all the way to the dorms, or having to tune in to the conversation around the bar. The bar does feel a bit big because of them, and whilst I don't think entirely cutting out the private spaces is a good idea, I can reduce the number of spaces by removing the current private booths and building them at the window to the right instead.
> 2. I don't feel like purposefully cutting down on bar capacity is the right idea to force people to get out there and roleplay more. Events and jobs do a much better job at that. On lowpop it doesn't matter because the bar will always have too many seats. I don't visit many highpop shifts, so someone else will have to tell me how it goes there. I just feel like providing more random, coded events, should be prioritized.

I am telling you, before the bar revamp, everyone always sat in the bar, there was never any reason for anyone to stick around their job place, because everyone knew that everyone else who was not actively working (and so, are likely unavailable) would be in the bar. 

If players are doing something weird and wacky somewhere else that might drive RP and interesting situations outside of event times, you need discoverability, and that comes from unoccupied people moving about to discover it. 

If everyone can congregate comfortably in the same space on even highpop shifts, like the old bar could allow, then that kind of thing is dead in the water. Such a person is generally left only to beg people over the radio to come see their wacky thing, and it's nearly never going to live up to the hype of having been spoiled first, where someone stumbling upon it is more likely to ask questions and potentially get involved.

I know I might sound like I am nitpicking here, but the design of social areas is kind of really important and influences in large part how people will engage with things. If something is the easiest most convenient way to do a thing, most people are going to just do that as opposed to taking the potentially more inconvenient path. In this case, even now, when you come into the station, you know that the most likely place to find people is going to be the bar. And that's usually true. But! The bar at present is small enough that, if there's too many people in there, it is somewhat inconvenient. People who would prefer it isn't so loud tend to wander, and the people who wander are the ones who will discover so and so's building project, or the chaplain's ritual sacrifice, or the lonely roboticist sitting at their desk.

If someone can go into the bar and sit in a quieter spot and wait for someone to come talk to them, the history of the bar has shown that, that's generally what will happen, and when everyone's doing that, then any roleplay that's not in the bar and/or vore, just doesn't happen.

I think the long bar and kitchen tables with many seats are good, a lot of people can fit in there. I think one or two booths close to the bar and kitchen would probably be fine. But, if I may use a kind of analogy the bar should be the place where you hang out between adventures, and potentially pick up the next one. When you get the call to adventure, you leave. It shouldn't just always be the whole adventure. 

I get that this is designed to be more like an actual real life bar/restraunt, and I recognize that it's cute and cool and a good design from that angle, but I am actually very confident that this design with so many private seats will damage non-bar roleplay opportunities outside of admin hosted events or emergencies.

What I am looking at right now I can basically guarantee will almost immediately become barstation 13. We already had that once, and we moved away from it.

**Comment by Very-Soft** [comment]
> > I do actually kind of like the kitchen design and placement though. That would make it pretty perfect for adding a small table in the hall so you could put food out there for people passing by. UWWU
> 
> Like this?
> image

YES JUST LIKE THAT!

**Comment by Rykka-Stormheart** [comment]
Hey @Very-Soft I do want to bring up - if the bar/kitchen have enough seating area for everyone to sit in front of it, and there's no overflow or forced seating away from it, there's little incentive to encourage stuff like waiters/waitresses to do their thing.

I'd love it if there was something to inspire/incentivize that.

**Comment by Ketrai** [comment]
@Very-Soft 
image
proposed alternative. Turns two booths into auxiliary storage that has very small quantities of ingredients to advertise cargo crates. As well as much lesser space at the windows, whilst still keeping a window.

**Comment by Rykka-Stormheart** [comment]
> @Very-Soft
> image
> proposed alternative. Turns two booths into auxiliary storage that has very small quantities of ingredients to advertise cargo crates. As well as much lesser space at the windows, whilst still keeping a window.

I really feel like those two empty storage rooms should also be private booths. Removing the secondary seating area behind bar was enough cut-down of smaller spaces, I'd really enjoy having 4 'private tables' rather than just the two, IMO.

**Comment by Ketrai** [comment]
4 is quite a lot tho. That's easily 8-20 people depending on how big the groups using the booths are. I'm willing to experiment with it though, can always tweak the number of booths after release.

**Comment by dwinters99** [comment]
> And then pulling in ds13 for some weird reason even though I'm not a mapper there.

I don't think I ever referred to.. ds13? I don't know what that is but I'm almost positive I didn't refer to it.

**Comment by Ketrai** [comment]
HISTORY : OLD POST - JUST HERE FOR POSTERITY. SEE MAIN POST FOR CURRENT PROGRESS.

Post updated with new design, seeing as no one liked the previous design.
P.S Please, please stop dropping huge ranty posts. Try and keep feedback/criticism more concise. Use bullet points with numbers. It's hard to read through, and an instant downer mood-wise. It's okay to be angry, just don't make me feel like I'm being attacked on a personal level. Please avoid responding with emoji's to the main post, as it will get updated. In case your initial opinion no longer reflects the changes.
P.P.S If someone has already stated something you agree with, please just mention the points you agree on rather than make a new post constantly relaying the same information as the person above. 

Information :
So this is the second iteration coming with a new design but with similar intentions. Main features include.
1. private booths. These have electrochromatic windows so you can hide yourself away for a private dinner. Allows people to scene more comfortably in the bar, especially when food play is involved. The design in the picture uses sofas, but here's an alternate design with chairs depending on what people prefer. 
image
2. Integrated hydro. Mostly so people can see the botanist again, and for the couple top spots to have a viewing window at the hard working planter. Hydro also has 16 trays set up for immediate use, and quick access to important machines such as the seed extractor. There's a lot of free space for those who want to set up hydro in a different fashion. Simply unwrench the trays and move them.
3. Open seating area. The main seating area is now close to both bartender and chef. So the chef doesn't have to feel isolated when most people simply flock to the bar. They can still easily partake in conversations across to the other side this way. 
4. Machine proximity. It's a little cramped, but machines have been plonked right up close to the counter so chefs can serve dishes and bartenders can do mixing whilst being able to see the other service members with ease, as well as all clients. I made sure to provide space behind the machines so it doesn't get cramped. One bartender can work on the right side, one on the left side.

OVERVIEW V2
image
Closeup V2
image
OLD
image

**Comment by Heroman3003** [comment]
Even with changes and cleanups, I still think the longer entrance hallway, the less amount of general walking space within the place and closely fit bar/kitchen counter staring each other down just doesn't look much better than the old bar. Whole rework still has strong feeling of only being designed for chef/bartender and not for people who will be visiting the place, as at least the current bar has more  room to move to if one end/corner happens to be too noisy without being driven out entirely. Also, while windows are cool, bar 'backroom' is now a side closet which completely sucks if bartender for one reason or another wants to leave without going through the bar itself.  Outside windows are 'cool' but not really that cool when they are coupled with rpetty meh design of staredown counters, and everything else feeling not like something 'small and not too spatious' but something huge that got cramped down as much as possible.

Overall, still can not see why this rework has to change the bar so radically anyway. The main issue originally brought up was lack of counterspace and excessive kitchen/botany size, both of which could be fixed with absolutely minimal changes to a very nice, kinda cozy and worn-in bar itself (and, depending one one's opinion, mild improvements in process), using instead all the excessive and generally uselss space of 'service block'.

**Comment by Ketrai** [comment]
> Even with changes and cleanups, I still think the longer entrance hallway, the less amount of general walking space within the place and closely fit bar/kitchen counter staring each other down just doesn't look much better than the old bar. Whole rework still has strong feeling of only being designed for chef/bartender and not for people who will be visiting the place, as at least the current bar has more room to move to if one end/corner happens to be too noisy without being driven out entirely. Also, while windows are cool, bar 'backroom' is now a side closet which completely sucks if bartender for one reason or another wants to leave without going through the bar itself. Outside windows are 'cool' but not really that cool when they are coupled with rpetty meh design of staredown counters, and everything else feeling not like something 'small and not too spatious' but something huge that got cramped down as much as possible.
> 
> Overall, still can not see why this rework has to change the bar so radically anyway. The main issue originally brought up was lack of counterspace and excessive kitchen/botany size, both of which could be fixed with absolutely minimal changes to a very nice, kinda cozy and worn-in bar itself (and, depending one one's opinion, mild improvements in process), using instead all the excessive and generally uselss space of 'service block'.

I'd appreciate a mention of the suggestions you've noted that I have taken into consideration, rather than all this downer talk. Just asking for a tiny bit of recognition here.

1. We've had bars before where the bartender can't sneak out silently. I also don't really see why this is anything more than a very minor concern. If they really want to, they can just sneak out through hydro. Or if it's really needed, just add a door the the back of the back room. The back room is pretty much just a place you're at the start of your shift, the end of your shift, or if you want to scene. It being more isolated here is actually a benefit for scenes.

2. You can't even see the other counter anymore because I moved the two apart like you asked. You're just staring at the bar's patrons now, so you can pick up half the conversation as chef no matter where they sit at the bar counter. This is nice for both the chef and the patrons. This way  they can also see whether the chef is active or not without having to move. The benefits outweigh the negatives imo.

3. "Huge but cramped down" feels like a very weird statement and is pretty opposite from the feeling ingame. There are a lot of counters and windows, you're almost never encroached on by walls. Any size bits that got cut were mostly to satisfy soft.

**Comment by Ketrai** [comment]
image
Have another alternative

**Comment by Kraseo** [comment]
don't fix what ain't broke

**Comment by TheToaster98** [comment]
> P.S Please, please stop dropping huge ranty posts. Try and keep feedback/criticism more concise.
Okay sure:

- The backroom is too far away from a bartender usual stop, in fact, it is not even a **back**room now!
- Too big. You still can't see the whole bar from the counter.
- I kinda like the kitchen! It feels compact, but the table between the middle and the counter is going to make you run around it, and that's inefficient.
- Also the orientation isn't good, though I like the little pick-up area outside the bar.
- The door is tiny, the entrance area in general feels like you are entering through a cramped backdoor.

**Comment by Ketrai** [comment]
> > P.S Please, please stop dropping huge ranty posts. Try and keep feedback/criticism more concise.
> 
> Okay sure:
> 
> * The backroom is too far away from a bartender usual stop, in fact, it is not even a **back**room now!

Did you check the main post for updates? Because the back room is very much a back room again.

> * Too big. You still can't see the whole bar from the counter.

This was actually requested. People do want to be able to sit in relative publicity without having to follow every conversation. Aka the two tables at the window. If soft wills it I can move the window to the left. 

> * I kinda like the kitchen! It feels compact, but the table between the middle and the counter is going to make you run around it, and that's inefficient.

You have to run around some tables either way. The one change I'm willing to make here is move the machines a tile to the left if they prove to be in the way in practice.

> * Also the orientation isn't good, though I like the little pick-up area outside the bar.

Same orientation as the current bar except I flipped the bar and the restaurant. Allows window access. Can you point out why this current orientation would be a bother for clients or staff? Unless you're once again not looking at the main post. For some reason.

> * The door is tiny, the entrance area in general feels like you are entering through a cramped backdoor.

Yeah I agree. Maybe a double door works better. It's kinda difficult with thw way the hallway is built currently.

**Comment by Ketrai** [comment]
For everyone saying it's still too big. Please note the current bar dimensions are 7wide primarily. And 12 long. The proposed bar is 10 tiles wide primarily, and 12 long. I'm willing to move the window to the left three times to get literally the same dimensions again. But it will feel a bit cramped and everyone will be able to see everyone again. Which are complaints with the current design from what I've gathered.

**Comment by ShudderEve** [comment]
The idea of some booths is super-grand. There's been a lot of times where people wanted to be in public, however still confined to their friends a bit. I think we could implement those in the existing bar, however:

- I know you want kitchen counters to be larger, because all your maps have pretty much at least doubled them, but I don't think this is very much needed, and the space could be used for something else,

- In actual architecture, we pay a lot of attention to logistics, foot traffic, and visibility. These have been applied to mapping as well. The reason why someone would go to the bar is for other people at the bar, it's a social gathering area. If you put people far and in-between, we'll create this loop of "no one is at the bar so I don't go to the bar" that sometimes occurs. If you check the previous map, you can see that moving into the doorway (or 1 tile further) pretty much gives you a full visual of who's sitting at the counter. This is a pretty good use of this technique. In your map, however, people have to go in, turn a corner, then a little more to do so.

- The bar backroom is not in the back of the bar, it's usually meant to be just there so that the bartender can store their shotgun there and grab it in a pinch, as well as supplies,

- Not a fan of the green table with stools being in the middle. That table is historically used to store maint loot, and for people to go AFK in,

- The entrance is 1-tile wide and surrounded by vendors, I think they need to be 2-wide at the least,

- Arcade machines being spaced out, and having stools looks a little strange to me. I think they could be along the right side of the area at least,

- You have a 3-tile wide walkway **farther** from the entrance, with the closer one being near the bar counter/green table. People will probably run into each other going through that 1-wide path, since it's closer.

- Kitchen is one of those rooms that NEEDS to be big. I've done cooking quite a bit, and I can tell you that making it smaller than it is right now is a net negative. It also needs a lot more tables than 4.

All in all, I'm not a huge fan of this design, but I think it could be improved upon. VerySoft once did a bar where there were some comfy sofas on the left side, with some booths down south which was received VERY well. Maybe we could try something like that?

**Comment by Ketrai** [comment]
@ShudderEve Soft is pretty adamant against booths or excessive secluded space in the bar. As for uh, the bar glancing thing? People are pretty guaranteed to go to the bar regardless. If people would only go in the bar if they glance presence, the bar wouldn't have any people ever, at all. If anything, I've been told by soft it's better if people go wander and find some other space to stay instead.

**Comment by Ketrai** [comment]
> * I know you want kitchen counters to be larger, because all your maps have pretty much at least doubled them, but I don't think this is very much needed, and the space could be used for something else,

The current counter is 7 spaces. With the very first kitchen we had both a 9 tile counter, and extra space to display dishes. This was very nice to display a large amount of food. I like, a couple other chefs like it. Not every chef prioritizes the same but I don't feel like two extra counters really hurts either.

> * The bar backroom is not in the back of the bar, it's usually meant to be just there so that the bartender can store their shotgun there and grab it in a pinch, as well as supplies,

It's a very short walk from the bar. I was thinking of fitting it down a ladder, but unfortunately the chapel's there. The shotgun is like, never ever used though? And if the bartender feels like they need the shotgun to maintain order, they might as well carry it on their person or keep it nearby.

> * Not a fan of the green table with stools being in the middle. That table is historically used to store maint loot, and for people to go AFK in,

I don't know what you mean by this. And everyone seems to have a different opinion on the damn thing, no matter who I talk to.

> * Arcade machines being spaced out, and having stools looks a little strange to me. I think they could be along the right side of the area at least,

Request from skree. I guess I can remove the stools tho.

> * You have a 3-tile wide walkway **farther** from the entrance, with the closer one being near the bar counter/green table. People will probably run into each other going through that 1-wide path, since it's closer.

... what? I'm not sure what you're trying to point at here. All walkways inside the bar are 2 tiles, the previous bar was 1 tile walkways and that worked fine.

> * Kitchen is one of those rooms that NEEDS to be big. I've done cooking quite a bit, and I can tell you that making it smaller than it is right now is a net negative. It also needs a lot more tables than 4.

I disagree. The current kitchen is a ton of walking, and you can always use the floor. It's actually a lot faster to drop stuff on the floor as you can use shortcuts and don't need to move your mouse far at all. I rarely use tables unless it's for something simple or to quickly get a large tray out of my hands. With a tiny bit of setup, you can use the tables for that already.
 
> All in all, I'm not a huge fan of this design, but I think it could be improved upon. VerySoft once did a bar where there were some comfy sofas on the left side, with some booths down south which was received VERY well. Maybe we could try something like that?

Soft dislikes booths now, so I unno?

> EDIT: I see the soda machine on a table in the kitchen. The soda machine is actually supposed to be on the counter, it's for the customers primarily.

I unno, this varies from kitchen to kitchen. In my eyes, the more customers need to interact with service staff to get what they want, the better.

**Comment by Ketrai** [comment]
image

**Comment by ShudderEve** [comment]
I think there was a disconnect, I'll also take the response on an item-by-item basis.

> As for uh, the bar glancing thing? People are pretty guaranteed to go to the bar regardless. If people would only go in the bar if they glance presence, the bar wouldn't have any people ever, at all. 

Not at all. If you go ahead and take a look at bars on any other map, including servers that aren't inherently HRP like Boxstation, you'll see that most of them obey the visibility mechanic to varying degrees. I think it is what makes or breaks a gathering area.

Though I didn't quite understand what you meant by:
>If anything, I've been told by soft it's better if people go wander and find some other space to stay instead.

Do you want the bar to be used less? I'm confused.

> It's a very short walk from the bar. I was thinking of fitting it down a ladder, but unfortunately the chapel's there. The shotgun is like, never ever used though? And if the bartender feels like they need the shotgun to maintain order, they might as well carry it on their person or keep it nearby.

The shotgun may rarely be used, but it's gotta be there. It's one of those things like having security on station. And I don't think saying 'just keep it on your person' is an extreme simplification of this. Not to mention, it's called bar backroom for a reason.


> I disagree. The current kitchen is a ton of walking, and you can always use the floor. It's actually a lot faster to drop stuff on the floor as you can use shortcuts and don't need to move your mouse far at all. I rarely use tables unless it's for something simple or to quickly get a large tray out of my hands. With a tiny bit of setup, you can use the tables for that already. It seems weird to be both complaining about too many, and too little tables. Just saying


 **Dropping food on the floor to prepare them** is not very HRP, wouldn't you think? Having more tables around to prepare food on them is preferred. And no, my feedback on tables is two exact opposites, I think you've misunderstood. The counter has too many tables for what it's worth, but inside the kitchen are too few. They serve completely **different** purposes. And I'm disappointed that you've taken my feedback as a complaint.

Moving on:
image

It takes a lot of maneuvering to get to the bar counter, unlike just heading towards the right in the current bar.  The last bit of arrow is what I mean by the 3-wide walkway.  I think it should be much simpler.

And a **very critical** issue with the design that I've just realized:
image

Small bit of background:
- Plants in Botany require different levels of light to grow. This is simulated by the actual light level of the surrounding area. 
- Most plants require 5-7 lumens to grow healthily and avoid taking constant damage. This is on par with the room lights on daytime lighting mode,
- Pretty much all botanists, due to this, **have to** disable night-lighting on their APCs to be able to mechanically do their job.
- The difference between these lighting modes are massive, and given that most bartenders switch the lighting mode of their bar to night mode for that cozy appearance, there's going to be a pretty huge conflict in the area of the counter.

Thinking again, I think the map could use some changes in its fundamental positioning of the three areas (Bar, Kitchen, Garden). But I appreciate the time you took to come up with it, and your responses. Hope this helps.

**Comment by Ketrai** [comment]
I've thrown a lot of designs out there. Personally still like 3 the most. I'm going to wait on a staff response to finish any particular design though. If anything I wish there was less reason to get all fussy over any particular design. If we don't have normal map rotation, maybe we can just rotate between versions of tether with different department setups?
image

**Comment by Ketrai** [comment]
Nyeeet?

**Comment by Arokha** [comment]
Entire kitchen changed since this PR, discuss in dev chat if you're still unsure which design you want among 3.

**Comment by Ketrai** [comment]
I was waiting for a staff response. At this point I'm pretty drained though. I don't see this making it in as anything other than a poi or if we had the code for alternative layouts.

**Pull request closed without merging**
