### PR TITLE
Fix Talon voidsuits being spriteless for Virgo-specific species

### LINKED ISSUE #8051: Talon engineering suit missing vulp sprites
### Brief description of the bug
Talon engineer suit is missing a vulp sprite. I'm unsure if it is missing others too.

#### Steps to reproduce
- Cycle a suit to vulp as a talon engineer.

#### Code Revision
- 1a20ff3ea5107e90a6c3ec3d97a9b9dc38e81f00

### PR DESCRIPTION
**Pull request by Little-119**
It seems someone forgot VOREStation edit marks in #7978 and thus the `sprite_sheets`s were removed in #8044. As a result, the Talon voidsuits have no sprites for Virgo species.
This adds the `sprite_sheets`s in in a _vr file, fixing that.

Also, I think I've removed everything (one suit cycler definition, some sprite sheets) that was made redundant by #8044. ...Oddly, it apparently didn't add Unathi variants for the obj sprites for the helmets.

Hopefully I haven't just accidentally broken these in a different way

Fixes #8051

### CODE REVIEW

**Comment by KillianKirilenko** [comment]
VR edit marks were unneeded as I specifically made the contents of that PR functionally standalone in the event that Polaris declined the upstream one.

The changes in `void_vr` are supposed to handle the sprite stuff automatically. If they're *not*, something is fucky.

> Hopefully I haven't just accidentally broken these in a different way

If you have to say this, compile and test on a local server. For the sake of your own time spent and/or wasted, if nothing else.

**Comment by Little-119** [comment]
@KillianKirilenko 
Well, something's fucky with those changes in void_vr then because the voidsuits didn't have sprites for non-Virgo species until I re-added the `sprite_sheets`

And I did compile and test on a local server as I was working, as I always do. [I'm just anxious about missing something](https://i.redd.it/rv7ax3lszpo21.png).

**Comment by KillianKirilenko** [comment]
Wait, so it was busted for all of them, or just vulp, or what?

Keep in mind I only did five sets of sprites; if you look at my original PR, you can see I pointed the akula and sergal refs to the unathi files with the custom/specific overrides. If you tried cycling it to either of those *after* aro's tweaks to the upstream merge then yeah they'd be invisible, but all the others should work.

I really should've just waited.

**Comment by SigholtStarsong** [comment]
@Killiankirilenko

I noticed the issue originally and tested all the sprites available to me in the suit cycler. Akula, Sergal, and Vulpkanin all failed to properly provide a sprite.

**Comment by Little-119** [comment]
>if you look at my original PR, you can see I pointed the akula and sergal refs to the unathi files with the custom/specific overrides
I copied the `sprite_sheets`s from that PR and edited them to point to the .dmi files that Polaris added

I didn't test to see which ones were broken beforehand, just took Sigholt's word that they were broken for Virgo-specific species. That's what this PR fixes.

**Comment by KillianKirilenko** [comment]
That tracks with expected behavior, then.

This is what I get for telling Aro it'd be fine to just wipe the entire sprite_sheet block. In my defense I *was* half-asleep when I said that.

**Pull request merged**
