### PR TITLE
Remove the lore blurb that pollutes the new player menu

### PR DESCRIPTION
**Pull request by ShadowLarkens**

### CODE REVIEW

**Comment by Heroman3003** [comment]
The only reason the lore blurb was even added is so that the giant window is not wasted space. If you're going to do that, then revert the fact that the window itself was made so needlessly huge in the first place as well.

**Comment by ShadowLarkens** [comment]
@Heroman3003 done

**Review by Novacat — DISMISSED** [review]
Will need to be marked with VS Edits for the time being.

**Comment by Wickedtemp** [comment]
I was kinda wondering why that was even there.

**Comment by DemicusMaximus** [comment]
Thanks. That huge window was incredibly annoying~

**Comment by DemicusMaximus** [comment]
Thank you. We needed this.

**Review by Arokha — APPROVED** [review]

**Review by Novacat — APPROVED** [review]
Code wise is fine! But waiting for other staff to review this in the staff meeting.

**Comment by JoanRisu** [comment]
I don't really think we need a meeting for this. From a design standpoint, the menu is meant to direct traffic, not tell us a story. Go ahead and merge this one.

**Pull request merged**
