### PR TITLE
Egg TF revamp, adds xeno egg sprite, bug fixes, reverts #382

### LINKED ISSUE #354: Floorlength Braid hairstyle is broken.
#### Brief description of the issue
Basically, the title of the issue.  It doesn't show up.
#### What you expected to happen
To see the hairstyle on my character.
#### What actually happened
Hair doesn't load, character is bald.
#### Steps to reproduce
1. Create character.
2. Choose the Floorlength braid in the hair options.
3. See a bald head instead in the character preview.
BONUS GAME:
4. Spawn in as character.
5. See that they're still bald.

#### Additional info:
 - **Server Revision**: release - 2016-06-09
eb05fc0682f692b13d69b9e8b6f277dec003c47d 
 - It's also still a thing in the latest V.O.R.E. code.
 - Looked in the code, someone over at Polaris seems to have done it on purpose?

`	braid
		name = "Floorlength Braid"
		icon_state = "bald" //Trust me, it's better this way.`

### PR DESCRIPTION
**Pull request by Cameron653**
- Fixes #354 for real this time.
- Adds a xenomorph egg sprite for xenohybrid characters. Sprited by Swat43
Open: http://puu.sh/pOmRR/8fb9cf00fc.png
Closed: (GIF) https://gyazo.com/896629e8e76d08f2faf3d6f2e0224b36
- Allows players to pick what egg sprite they want. An Unathi with custom race name  can use a Nevrean egg sprite.
- Reworked how the egg types work. It's now player specific, instead of species specific.
- Reverts #382 as it was causing more problems than anything. Need to look for another solution to #380 
- Allows all players to pick the xenochimera egg sprite.
- Renamed "Scree egg" to "Xenochimera egg"

~~- Fixes sprites not updating after tf. After egg TFing a human into a skrell, their sprite would still be a human one. This has been fixed.~~
This apparantly didn't fix it. Species TF won't update the actual mob sprite, but they'll mechanically be the species they were TF'd into.

Notes:
Swat43 asked me in adminhelp if we had layable eggs, and if so, if they could be given the file for them. They were given the .dmi and soon produced the xenomorph sprite seen above and gave it to me to add into the server. Due to not wanting to create an entirely new xenomorph race, I went ahead and revamped how the egg transformation works and made egg_type character specific, and not species specific. While testing, I found out that I missed a extremely severe bug in my #382 PR. If the predator was eaten and egg TF'd, the egg would appear on the floor. If the pred was not eaten and egg TF'd someone, the egg would teleport to somewhere random in the area. This was a major problem, so I reverted #382 in this PR to fix it. I also renamed the Scree egg to Xenochimera egg, and removed some lines of code that were unneeded.

### CODE REVIEW

**Comment by Cameron653** [comment]
I've worked on attempting to get the species icon to update after egg TF, and nothing appears to be working. Everything works mechanically, but the sprite doesn't update, although everything else (Tail, hair, etc) does as expected.

**Comment by SpadesNeil** [comment]
Conflicts.

**Comment by Cameron653** [comment]
Oh, let me fix that real fast. The human recoloring conflicted with this.

**Comment by Cameron653** [comment]
Alright, conflicts should be fixed now.

**Comment by Cameron653** [comment]
Alright, now it should be fixed for real this time.

**Comment by killer653** [comment]
Alright this should be ready for merge now.

**Pull request merged**
