### PR TITLE
Makes the CMO office comfy

### PR DESCRIPTION
**Pull request by Mewchild**
Makes the CMO office slightly larger, adds a couch, chair, and bookcase. Changes style of floor to be more welcoming and comforting to be in, less sterile and oppressive.

### CODE REVIEW

**Comment by Novacat** [comment]
If the CMO's office is going to be more exposed to space, than it could probably use whipple shields to deal with the space dust issue. Though truth be told all of medical could use whipple shields.

**Comment by SpadesNeil** [comment]
Conflict due to earlier PR that diddles with the map.

**Comment by Mewchild** [comment]
Screenshots not needed. MapDiffBot

**Comment by SpadesNeil** [comment]
oh pffft I'm sleepy and dumb

**Comment by Mewchild** [comment]
I love you anyway bb

**Pull request closed without merging**
