### PR TITLE
Beds prevent all falling damage

### PR DESCRIPTION
**Pull request by Arokha**
I have seen a movie before. I know how this works.

### CODE REVIEW

**Comment by SilencedMP5A5** [comment]
you can now slamdunk prisoners into their cells from above as security.
*excellent.*

**Comment by SpadesNeil** [comment]
This is silly but I like it.

**Comment by KotetsuRedwood** [comment]
POMF.

**Comment by SingoDingo** [comment]
Aw I was actually hoping this'd go through.

**Comment by Screemonster** [comment]
Clearly you need a conveniently placed donkey cart full of straw.

**Pull request closed without merging**
