### PR TITLE
[MIRROR] workspace improvements

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/8583
--------------------
closes #8554 -- conflicting outcomes

---

This improves repository health by:

- Adding a dependabot config to keep action versions and npm targets updated.
- Updating workflows to ubuntu-latest, instead of bionic.
- Correcting python files to not have mixed indentation and be 3.Xy.
- Adding a node script that can be used to identify files with bad UTF-8 contents.
  - This was necessary because python is a sad, weak thing. Destroy snek.
---

This improves the VSC, DMLS, and alternate editor experience by:

- Grouping dme, dmf, dmm, dm together as the `[dm]` language alias.
- Uniformly applying `\r\n` and tab indent rules to `[dm]`.
- Preferring `\n` line endings for all other file types.
- Explicitly using utf-8 encoding for all files.
- Enabling whitespace trimming for all files.
  - Except markdown, which does not trim final newlines for formatting reasons.
- Enforcing the local 4 space python indent.
- Enforcing the local 2 space yaml indent.
  - And cleaning up the inconsistently indented autochangelog workflow.
- Recommending language support, the language server, editorextensions, and gitlens.
- Adding a .editorextensions file with indent, trimming, etc as close as possible to VSC settings.
  - This permits the use of things like sublime and atom, if they are set up for it.
- Letting you preview DMI files in VSC (1).
- Building the type tree for (best effort) alternate source navigation (2).
- Skipping the task failed abort modal for suite builds that fail.
- Defaulting suite tick on create and auto update on.
---

(1):

(2):

Building the type tree also lets you discover path bugs with your eyes!

### CODE REVIEW

**Comment by Very-Soft** [comment]
me want to look into this more later

**Comment by Cameron653** [comment]
This has been sitting and has a lot of conflicts. Highly suggest to port this over later.

I won't close this because of it's importance, but this should be fixed ASAP.

**Comment by Heroman3003** [comment]
I don't really get this but it seems to be mostly for VSC nerds and if you say this is important, I'll leave this hanging.

**Comment by Heroman3003** [comment]
This is usalvagable by now, I imagine?

**Comment by Heroman3003** [comment]
I'll just say that if this is wanted, people are free to request a reopen on this, but until then, to the bin it goes.

**Pull request closed without merging**
