### PR TITLE
Makes Liquid Protean and Repair Nanites affect synths

### PR DESCRIPTION
**Pull request by Heroman3003**
Now they too can enjoy NIF repairs using chugging a glass of ~~spiders~~ nanites

### CODE REVIEW

**Comment by KasparoVy** [comment]
A brimming glass! Cheers.

**Comment by KillianKirilenko** [comment]
Be sure to test this one thoroughly if you haven't already; I tried to do something vaguely similar the other day (grinding nanopaste into a tricord-like reagent) but the code wasn't having any of it and I couldn't for the life of me figure out why.

**Comment by Heroman3003** [comment]
This just enables the variable for the NIF repair nanites and liquid protean reagents to function inside synths that was added recently. Nothing more.

**Comment by KillianKirilenko** [comment]
That doesn't mean it actually *works*, which is the important part of *testing*.

I took the liberty of testing it myself on my freshly-updated master (based on virgo's current master) and, as I suspected, it does nothing.

The problem is that reagents aren't transferred to the synth's blood, so `affect_blood` does nothing. I suspect the original FBP internals weren't tested thoroughly enough, or something else is breaking.

**Comment by Heroman3003** [comment]
Well, whenever it does get fixed, those reagents will work properly too. For now injections at least should work. Hopefully. And even if they don't not that big a loss. The intent of PR was mostly to throw virgo-unique reagents that should have that flag but don't under it. If flag is broken as a whole, thats entirely different issue.

**Comment by KillianKirilenko** [comment]
Injection won't work either as there's a blanket check on that, which is something else that needs fixing.

The whole FBP thing seems kinda janky and hacky taking a couple more looks at it, so there are probably more issues that need resolving down the line.

**Pull request merged**
