### PR TITLE
Adds *mlem and *awoo

### PR DESCRIPTION
**Pull request by Arokha**
YOU. MAKE. ME. ***SICK.***

That you somehow convinced me to do this.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
cmwaqc2

**Comment by JoanRisu** [comment]
SCA: Loud man with large clock telling people what time it is.

**Comment by Arokha** [comment]
DON'T STAHP. BELIEEEEEEEEVIN.

**Comment by Arokha** [comment]
Really though this adds the custom emotes framework so we can add our own emotes and not conflict with Polaris merges.

**Pull request merged**
