### PR TITLE
Adds realistic consequences of overindulging on plant-based products

### PR DESCRIPTION
**Pull request by drexample**
Soymilk now has overdose rate at 60 units causing it to turn you female.
To preserve the balance, a mutated version of soybean (boibean) has been added, with its signature reagent - boimilk.
Mixing soymilk, boymilk and sugar thickens them into a thoymilk shake with a predictable effect.

Do you guys also get a weird fucking idea at 3 AM when you're trying to go to sleep, stand upright and write it down to rain it upon unsuspecting people eventually?

### CODE REVIEW

**Comment by lbnesquik** [comment]
Merge it.

**Comment by Very-Soft** [comment]
No thank you, we already have an established way of achieving this, and I do not wish to see it expanded upon.

**Comment by drexample** [comment]
Alright, alright, I getcha. I'll come back with something better.

**Comment by Runa-Dacino** [comment]
I'd rather not reinforce this dumb meme.

**Pull request closed without merging**
