### PR TITLE
7/23/2021 Drink Revamp

### PR DESCRIPTION
**Pull request by GhostActual**
Polishes, adds, and changes some sprites for both cans and bottles alike that were a bit outdated. Also re-adds the Radical Renard vending machine with a more appeasing sprite that is also partially animated. Some organizational changes were also added to the code for better reference and a can_placeholder was added to the drinks.dmi file for any future canned drink additions.

Below are some examples of the sprites that were changed/added.

Placeholder Can:
125000489-829e8680-e01e-11eb-84b3-d100cd5c3857

Various Bottle Changes:
125000437-64388b00-e01e-11eb-9531-f8c5f86bfe17

Additions to the BODA machine:
125000443-67cc1200-e01e-11eb-9c9b-e0aeb41979a0

Additions to the Hot Drinks machine:
125000542-a19d1880-e01e-11eb-800d-747a689e9987

Sodas that were added/changed:
125000563-ac57ad80-e01e-11eb-8eda-e6dd764bac73

New Changeling Sting sprite animation:

New Carnoth (ntcahors) bottle:
125551603-68f6a628-b852-44a5-a2f1-26519a8931c9

Misc Stuff:
-Sodawater and Tonic cans were brought to 30 from 50 to match other cans.
-Adds in previously unused Soda Bottles found in `drinks.dmi`.
-Moves Grenadine next to Lemon and Lime juice bottles in the code.
-Addition of Grape Juice bottle for non-alcoholic characters that wish to be included.
-Addition of Turnip Juice reagent for those that wish to taste sadness.
-Adds Carnoth to Captains room
-Adds `Radical Renard Sodas` Machines to various spots around the station
-Small map changes that I spotted while looking for spots to place the new vendor
-Moves `vending_machine_vr` to the same file as `vending_machine`

### CODE REVIEW

**Review by Arokha — CHANGES_REQUESTED** [review]
/obj/item/weapon/reagent_containers/chem_disp_cartridge/wine still specifies that it dispenses "wine", and is used in the booze dispensers. "wine" no longer exists, so please fix.

**Comment by GhostActual** [comment]
Whoops, wrong PR

**Review by Arokha — CHANGES_REQUESTED** [review]
`icons/obj/closets/undies_wardrobe.dmi` is in this PR for some reason

**Comment by klaasjared** [comment]
> `icons/obj/closets/undies_wardrobe.dmi` is in this PR for some reason

Accidentally added it, forgot to remove it

**Comment by Arokha** [comment]
Your other PR was merged and created conflicts with this one.

**Pull request merged**
