### PR TITLE
Make laying people be under other people

### PR DESCRIPTION
**Pull request by Arokha**
Unsure what consequences this would have. PLEASE REVIEW. (It works fine ingame, but I can't test every object with every mob)

### CODE REVIEW

**Comment by Screemonster** [comment]
the only downside I can see for this would be for LAPSITTING.

**Comment by Arokha** [comment]
Generally lapsitting people are both standing. This only affects when sprites are 90deg rotated flat.

**Comment by Screemonster** [comment]
So basically only an issue when someone does the cat thing of flopping in someone's lap, lying belly-up and demanding pets :v
(which even I don't do all that often)

**Comment by Arokha** [comment]
Tru. But I think that is less common than every other time. Like just walking over someone who's laying, or using disarm-pin to pin someone, or just being on a bed over someone, etc.

**Comment by Very-Soft** [comment]
I'm honestly fine with how it presently is? All it takes is the person on bottom moving off the tile then back on to get on top. I don't really understand why you would want to make it so that people wouldn't have at least that minor control over it.

**Comment by Arokha** [comment]
That is not how it works.

**Comment by Very-Soft** [comment]
Ah as I said in discord, I'd not seen it actually behave this way on server. if that's how it do, then yeh, that should not be a thing. I'd prefer if it behaved like all the other things, where the person who last entered the tile is on top.

**Comment by Arokha** [comment]
If it breaks the universe you can yell at me.

**Comment by SpadesNeil** [comment]
I have **never** seen it behave like that. The fuck got changed to break this?

**Pull request merged**
