### PR TITLE
Updateu-san

### PR DESCRIPTION
**Pull request by Arokha**
***Sync Added***
Adds the box cutter knife and teapot
Advanced heal stacks now only heal 3 from 5
Synths have a special icon on medhuds (not AR overlays or omnihuds)
Laser Carbine renamed to the Laser Rifle, and now has a fire delay of 8 in lethal and 5 in suppressive.
Adds snowballs. Yay christmas fun!
Removes references to clothing being military from the loadout
Adds huge amounts of new drinks
Adds metamorphic drink glasses, basically just adding the old style glasses code without removing anything
ABS and sleepers reject non-human mobs
Makes galoshes shockproof
More types of sheets can be ground up in a grinder
Fixes a few research typos
Adds crawling to the game (drag self to adjacent turf to crawl)
Shotgun clips now only hold 2 from 4
Adjusts the amount of camera locations the AI can store from 10 to 30
Lowers the volume of mouse squeaks
Ballistic transportation pod
Alters the time it takes to applies cuffs
Adds bolas, which are fire-able legcuffs
Adds new spider types
Hacked borgs can no longer be locked down
Fixes a few vendor chat log things and uses unused sprites for vendors
Redoes Mosin sprites
Fixes how intents interact with drinks, allowing you to splash your drink on someone in harm intent
Adds exploration equipment including a hooded armour suit with a hood light (for miners?) and a survival bootknife
Adds the 'pagan', 'orthodox', and 'torah' chaplain bibles, and removes the 'creeper' chaplain bible
Adds a cap to breathloss, making it cause less oxyloss and only performing the *gasp emote every 10 ticks
Winter boots now no longer cover the legs, only the feet. Winter coats now cover the legs to compensate
Allows communicators to be made by RnD, shows ghosts communicator IMs
Mobs can't push objects that they can't pull
Adds an advanced roller bed, that takes up less bag space when folded, is developed by science, costs phoron.
Adds advanced health analyzer, that can give fracture, internal bleeding, and stomach reagent info. Is developed by science, costs diamonds.
Adds a bunch of loadout optimisations, and adds new loadout items, including: A stethoscope, a locket, plain goggles, prescription science goggles(?), science aviators (and prescription variant), a white cane, a colorable cap, a powdered wig, rabbit ears, a cheap lighter, a greatcoat, and a camera.
Contaminated items now respect gloves
Clotting crates now cost 100 cargo points from 40
Can no longer run around while in a roller chair
Adds Reach Variable to Weapons, currently only allowing spears to attack from 2 tiles (and over chairs/other people), making meatshield gladius greytide possible
Fixes and/or adds the chainsaw. Let the texas chainsaw massacre begin
Adds parachutes
Psychiatrists can now spawn with medical HUDs from the loadout

***VS Added***
Fixed pAI OOC notes
Xenochimera tweaks/fixes
Teshari can toggle passtable on and off
Renamed phoron dragon
Allows two misc fax machines to get replies
Fix and reenable organ rejection
Dogborg rest poses
Xenochimera pick iconbase
Clean up playerlist problems
Otie tweaks/fixes
Algae generator fixes
More status displays
Allows changing gender identity midround
Reduce solargrub frequency
Fixes cloning w/ wings

### CODE REVIEW

**Comment by SpadesNeil** [comment]
I didn't get to finish reviewing the sync PR. I hope someone else did.

**Comment by Arokha** [comment]
> I didn't get to finish reviewing the sync PR. I hope someone else did.

Leshana did yeah.

**Comment by SpadesNeil** [comment]
hokay

**Comment by SpadesNeil** [comment]
Tell Leshana good work because that's a lot of code to read through.

**Comment by Arokha** [comment]
Done, also yeah I think they spent like hours doing it.

**Pull request merged**
