### PR TITLE
Fixes belly spiral from being cut off.

### PR DESCRIPTION
**Pull request by Cameron653**
Looked like this pre-fix https://cdn.discordapp.com/attachments/1008937132259278969/1024508027182792794/unknown.png

I have absolutely _no_ idea how the markings code works, but it clearly is meant to be on the groin as well as the groin is cutting it off.

### CODE REVIEW

**Comment by Heroman3003** [comment]
Have you tested if it actually works? Iirc there need to be different sprites for different organ pieces. I dont remember if it applies to groin-chest, with those being never separate, but if it does, might also be sprite missing.

**Comment by Cameron653** [comment]
I'll go ahead and test it as well, since like I mentioned I had no idea it even had multiple sprites.

**Comment by Cameron653** [comment]
Hnnnnnngh fuck I hate sprite code I hate sprite code I hate sprite code I hate sprite code I hate sprite code

Going to fix

**Comment by Cameron653** [comment]
Alright fixed
https://i.imgur.com/WcGcX9z.png

**Review by Heroman3003 — APPROVED** [review]

**Pull request merged**
