### PR TITLE
Vocal announcements for events

### PR DESCRIPTION
**Pull request by Heroman3003**
Added vocal announcements for all events in current rotation.
Most examples can be seen here: https://soundcloud.com/heroman3003

### CODE REVIEW

**Comment by Arokha** [comment]
Can you rebase or something, or stop using PRs to update your fork? This'll be the last one I'll accept with the plethora of unrelated merge commits.

**Comment by SigholtStarsong** [comment]
How well do these match existing AI vox?

**Comment by Screemonster** [comment]
This sounds like it was just run through a text to speech generator and there wasn't much effort made to correct the weird mispronunciations that result. Especially every time it tries to say "EVA".

**Comment by Very-Soft** [comment]
I'd sort of prefer if an effort was made to correct the pronunciation of EVA. It should be E-V-A. Not Eva. And there are a couple of them that sound awkward when spoken "Unidentified lifesigns coming aboard station." I feel like would sound better as "Unidentified lifesigns coming aboard _the_ station."

Further, I'm not the most keen on how long they are. I get that these just run the literal text through a tts generator, and 9 seconds doesn't sound like a lot, but keep in mind, you're gonna get most of these every shift. Sometimes more than once.

I personally don't think all of them need a voice thing. But if they were to have them, it might be better to make a shorter version for them.

"Meteor detected, brace for impact."
"Attention: Unidentified lifesigns detected."
"A solar storm has been detected approaching the station. Please halt all EVA activities."
"The solar storm had passed the station. It is now safe to resume EVA activities."
"The solar storm has reached the station."
"Attention: Harmful fungi detected."
"Warning: Hazardous gas leak detected."
"Warning: Solar Grubs detected"
- Vendor, and debris ones are pretty short already.

Though, again. I don't think most of these need a voice announcement. I'm fine with solar grubs and gas leak getting one, because those are important not to miss. But who even cares about the fungi?

Further, unidentified lifesigns already has a voice line here afaik (I might be mistaken), so I'm not really sure why you'd want to replace it, unless you were planning to redo all the voice lines to be consistent with these new ones.

**Comment by Heroman3003** [comment]
closed, will open a new one after cleaning up my repository.

**Pull request closed without merging**
