### PR TITLE
Polaris Sync

### PR DESCRIPTION
**Pull request by Arokha**
Means what it says and says what it means!

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Looks pretty good.

**Comment by SpadesNeil** [comment]
Actually, please hold off on this until https://github.com/PolarisSS13/Polaris/pull/1923 is merged.

**Comment by Arokha** [comment]
Mmmmm. But bugfixes like, you know, bellies being available to multiple characters and stuff. S'kinda importantish. Few hours before shift ends anyway.

**Comment by SpadesNeil** [comment]
:U

**Comment by Arokha** [comment]
I can just do it again when that gets merged, anyway! :P I don't mind.

**Pull request merged**
