### PR TITLE
Xenobiology Station Gateway

### PR DESCRIPTION
**Pull request by dwinters99**
### Lava-borne small secret research station featuring medium difficulty combat and a special anomaly. 
---
**Features:**
- New mounted geiger counter
- Radiation anomaly, provides a set amount of rads without requiring input but cannot be disabled.
- Trash dump infested with xenos guarding a blast-door over-ride lock to enable further access to the facility
- Creature pens containing pacified mobs and lore notes associated with them
- Caves
- Short maze terminating in a small vault, requiring a switch be found in a seperate part of the level
---
st
---
### TODO
- [x] atmos + power
- [x] cages
- [x] caves + puzzle
- [x] notes
- [x] bridge
- [x] blackbox
- [x] rad anomaly cataloguer info
- [x] more detail, filth, etc. in rooms
- [x] idiot-proof gaslamp pen

### CODE REVIEW

**Comment by dwinters99** [comment]
after some playtesting, the following changes have been made:

one of the puzzle doors (the one that leads into science) is now more obvious as to it's purpose and opening method
i've started making another area (the "bridge" at the far north so going there isn't a waste of time
removed the deathsquad helmet (very sad day but must be done)
the corpses are no longer skeletons (again very sad)
lighting is better
extremely minor map edits to make it look less Shit.

**Review by Novacat — CHANGES_REQUESTED** [review]
Conflicts

**Comment by Arokha** [comment]
Any progress?

**Comment by dwinters99** [comment]
I've been particularly busy recently, I'm closing this until I have time to resolve the conflicts.

**Pull request closed without merging**
