### PR TITLE
Fixes ZAS issues on away maps

### PR DESCRIPTION
**Pull request by SpadesNeil**
It's probably one of my Z-levels but let's make a control test.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Ugh, are you kidding me? If this is what I think it is...

**Comment by ArgobargSoup** [comment]
Tried googlin' "active edges" in relation ta byond stuff and got nothin', so now I'm curious.  Have ya figured out what it was?

**Comment by SpadesNeil** [comment]
I know exactly what the problem is. It's an SS13 thing; not a Byond thing. Google won't help. It's a map issue.

**Comment by SpadesNeil** [comment]
Oh, that fixed it. Next map.

**Pull request merged**
