### PR TITLE
Modifies ERT dogborg disabler & minor bugfixes

### PR DESCRIPTION
**Pull request by Cameron653**
Gives the ERT dogborg's disabler 10 shots.

Having two shots was a bad idea, as it meant that the disabler was objectively worse than a normal taser, which has a lot more than just two shots.

~~- Gives disabler 10 shots~~

- Minor bugfix to get SilencedMP5A5/Serdykov Antoz's custom armor to work
- Minor bugfix to make wolftaur armor actually show up.

Made some edits and also made it DNM until adjustments are agreed on.

Changes made:

- Same amount of shots as a disabler

- Takes same amount of charge as a disabler (After some testing, it was found that having it at 1000 would sap a borg's battery way to quick

- Does 100 agony damage (One shot knock down)

### CODE REVIEW

**Comment by SpadesNeil** [comment]
I am pretty sure the disabler is more powerful.

**Comment by Cameron653** [comment]
Well, Polaris (to the best of my knowledge, didn't exactly see anything in the code for it) didn't have a disabler so I custom made one for a dogborg and pretty much made it a little stronger taser. I can bump up the halloss damage (And decrease the amount of shots) it does to make it 1 hit stun if you want

**Comment by Cameron653** [comment]
Made some edits and also made it DNM until adjustments are agreed on.

Changes made:

- Same amount of shots as a disabler
- Takes same amount of charge as a disabler (After some testing, it was found that having it at 1000 would sap a borg's battery way to quick
- Does 100 agony damage (One shot knock down)

**Comment by Cameron653** [comment]
Any input on this? Should the amount of shots be increased/decreased, damage it does be increased/decreased, etc etc, or is this ready to be merged?

**Comment by Cameron653** [comment]
DNM this accidentally combined two PRs into one by mistake

**Pull request merged**
