### PR TITLE
New Belts and Accessories (it's late, no joke title)

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

Adds in new, custom sprited icons for a vast number of things that were in desperate need of a face lift. The belts (all of them) now have a significantly better sprite that keeps the soul of the original sprites in mind. The vests and webbing you can find in maints now have their own polished sprites (Teshari onmob sprites included). Thigh drop bags also got the same treatment along with all the holsters whose sprites were originally ported from Aurora. Finally the pocket pouches got some love so their Eris born sprites no longer violently clash with the existing style.

This took a bit, it's late, I might have missed a couple things, but I did do a final pass before pushing to the PR so everything _should_ be in order.

## How This Contributes To The VOREStation Roleplay Experience

No more old sprites. This is the future. We get shiny new sprites.

## Proof of Testing

<details>
<summary>
Screenshots/Videos</summary>
 
New Belt Sprites
Screenshot 2023-06-16 235948

New Holster, Thigh Bag, and Webbing/Vests Sprites
Screenshot 2023-06-16 235743

New Pocket Pouches Sprites
Screenshot 2023-06-16 235706

</details>

## Changelog

:cl:
image: Adds in new custom Belt Sprites
image: Adds in new custom Webbing sprites
image: Adds in new custom Vest sprites
image: Adds in new custom Thigh Bag sprites
image: Adds in new custom Pocket Pouch sprites
del: Removed Baton Pouch
del: Removed Holster Pouch
add: Added in Injector Pouch
add: Added in Grenade Pouch
balance: Pouch of Holding is now slightly cheaper than the Bag of Holding
/:cl:

### CODE REVIEW

**Comment by TankTheBirb** [comment]
The sprites are fine, I actually like a lot of these. I do wish the pouches had more distinction as to the intended function of the pouch personally. But the big thing I'm not particularly fond of omitting the balance changes to pouches from the change log. For example, now you can have basically 3 engineering toolbelts between your pocket and two belts. You decreased the cost of the pouch of holding as well. The supplies pouch, a medium item, can now carry 4 stacks of sheets. You also deleted two pouches and added some new ones, the additions I'm fine with but in general if you're going to delete an option at least log it.

Pouches are meant to be enhanced pocket storage, something you could use if your belt or back was being taken up by something like a shield or RIG. I'm not sure your changes really reflect that.

**Comment by Youtubeboy139** [comment]
> The sprites are fine, I actually like a lot of these. I do wish the pouches had more distinction as to the intended function of the pouch personally. But the big thing I'm not particularly fond of omitting the balance changes to pouches from the change log. For example, now you can have basically 3 engineering toolbelts between your pocket and two belts. You decreased the cost of the pouch of holding as well. The supplies pouch, a medium item, can now carry 4 stacks of sheets. You also deleted two pouches and added some new ones, the additions I'm fine with but in general if you're going to delete an option at least log it.
> 
> Pouches are meant to be enhanced pocket storage, something you could use if your belt or back was being taken up by something like a shield or RIG. I'm not sure your changes really reflect that.

Only changes to the `engi_tool` pouch was the removal of the delay and the addition of a hard limit on items that the pouch can store which is four items - before and after below.

Before
Screenshot 2023-06-17 133844

After
Screenshot 2023-06-17 133142

The cost of the holding pouch was _more_ expensive than a standard bag of holding with the only benefit of holding half the amount of items as a standard backpack. Granted it was available in the tech tree earlier than the Bags of Holding but it was only by one level for each require tech which means that players are more likely to spend the resources on the Bag of Holding instead of the pouch.

Bag of Holding
Screenshot 2023-06-17 134727

Pouch of Holding
Screenshot 2023-06-17 134747

I can easily shrink the storage on the supply pouch to half of what it currently is. When I moved the sheets from the one pouch to the pouch it is currently in it never crossed my mind that this might be an issue. That was my bad. Another fix is to add an addition to the `/obj/item/weapon/storage/backpack` string that prevents the backpacks from holding pouches to prevent "storageception" which might be something worth adding regardless to prevent future issues.

As for the removals, when I did these pouches they were originally in their own separate PR that I created weeks ago that I merged here late last night and the fact I removed the `holster` and `baton holster` was simply forgotten. That's my bad, I was very tired, I'm sorry. 

I'll update the Changelog.

**Comment by Heroman3003** [comment]
I'd rather absolutely all balance changes (including stuff like removing holster/melee pouches, adjustments to what can be held, resource pricing, etc) be separated into their own PR rather than being packed together with sprite changes.

**Comment by Youtubeboy139** [comment]
> I'd rather absolutely all balance changes (including stuff like removing holster/melee pouches, adjustments to what can be held, resource pricing, etc) be separated into their own PR rather than being packed together with sprite changes.

https://github.com/VOREStation/VOREStation/pull/15040

**Pull request closed without merging**
