### PR TITLE
Removes Awoo speech

### PR DESCRIPTION
**Pull request by Mewchild**
Removes the Cursed Speech Autohiss/Awoo/Disability speech from traits, by community request.

### CODE REVIEW

**Comment by Ketrai** [comment]
Add them as admin verbs tbh. The ability to give a character a certain kind of speech that is.

**Comment by Shophaune** [comment]
A note for if Ket's suggestion is ever added: this cursed autohiss didn't even exclude the other autohisses properly, so you could have an awoo'ing Tajaran.

**Comment by TheFurryFeline** [comment]
> A note for if Ket's suggestion is ever added: this cursed autohiss didn't even exclude the other autohisses properly, so you could have an awoo'ing Tajaran.

Sadly, I think that one was intentional....

**Comment by TheDavestDave** [comment]
It will stop being so bad once it stops being the new hottness. I think it would also work better if we changed it to change just r. And replace that with a % chance to replace.

https://www.youtube.com/watch?v=ChTJHEdf6yM it's entirely possible to have a speach disorder and not sound retarded

**Comment by Haery70** [comment]
Where were you guys at when this pr was made?
https://github.com/VOREStation/VOREStation/pull/5475

**Comment by Novacat** [comment]
People tend to ignore github until a change happens that negatively affects their experience ingame.

**Comment by SpadesNeil** [comment]
https://www.youtube.com/watch?v=7mBqm8uO4Cg

**Comment by Haery70** [comment]
There's pros and cons to owo speak:

Pros:
It's funny.
It can annoy people for lulz.

Cons:
It makes you sound like a toddler.
It can annoy you overtime.

I'm more worried about the one con over the pros.

**Comment by Heroman3003** [comment]
I believe people ignored original PR because it was seen as 'joke' PR, and nobody expected it to be actually merged

**Comment by Wickedtemp** [comment]
...I wanted it ingame for a few weeks, not gonna lie, so I'm happy about all of this

**Comment by SpadesNeil** [comment]
>I believe people ignored original PR because it was seen as 'joke' PR, and nobody expected it to be actually merged

Which is exactly why I merged it.

CLeaRly IT's wHAt THE peOPle Want

**Comment by MrSign** [comment]
uwu

**Comment by MrSign** [comment]
On a serious note, whether or not this gets accepted. I don't mind. I haven't encountered any abuse of the awoo auto-hiss and more than likely it'll die off in a week or two.

**Comment by Screemonster** [comment]
is this even still a problem or just the usual "people use the absolute _hell_ out of a feature on day 1 to try it out, a kneejerk removal PR is made, and by the time it comes up for review everyone's forgotten it even existed" thing

**Pull request merged**
