### PR TITLE
Adds "Bridge Officer" alt-title of Command Sec

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
Also includes increase in job slots - roundstart max of 4, total max of 6. Yes, that seems high, and I don't mind reducing it based on feedback. <3

### CODE REVIEW

**Comment by Heroman3003** [comment]
I do still think that secretary slots as they are right now are fine. Fundamentally that title is no different from Secretary and there's no need to have as much people doing nothing in command as actual command.

**Comment by Rykka-Stormheart** [comment]
> I do still think that secretary slots as they are right now are fine. Fundamentally that title is no different from Secretary and there's no need to have as much people doing nothing in command as actual command.

Yeeee, like I said, I'm willing to reduce it - I thought I'd start with 6 total, 4 roundstart, and see what people thought! It's a simple vartweak to reduce the slots. <3

And, regarding the "do nothing as command" Bridge Officer should hopefully show that you intend to actually seriously either do paperwork, assist heads-of-staff, or the CD, and learn from them. Think of it like a stepping-stone role to full CD/etc. Obv, they don't have any authority (intentionally), but they can be tasked with things by diff Heads-of-Staff.

**Comment by SpadesNeil** [comment]
I am still not in support of this for the reasons outlined in https://github.com/VOREStation/VOREStation/pull/5740

I still see no purpose of this alt title, much less the need to add more job slots.

**Comment by Rykka-Stormheart** [comment]
> I am still not in support of this for the reasons outlined in #5740
> 
> I still see no purpose of this alt title, much less the need to add more job slots. The original job title already serves almost no purpose.

I can reduce the job slots, sure! <3

**Comment by HzDonut** [comment]
...I don't get why "i don't see the purpose of this" is a valid criticism for a fluff title. Alt-titles literally just exist for RP purposes and don't affect the game in any way, having more does nothing to the server. Also like Rykka said, this is supposed to be for people who actually want to learn about command instead of just doing paperwork and existing on the sidelines like a secretary. It's like the difference between a nurse and a MD. They're both the same job, except one is expected to do considerably less than the other.

**Comment by SpadesNeil** [comment]
>...I don't get why "i don't see the purpose of this" is a valid criticism for a fluff title. Alt-titles literally just exist for RP purposes and don't affect the game in any way, having more does nothing to the server. Also like Rykka said, this is supposed to be for people who actually want to learn about command instead of just doing paperwork and existing on the sidelines like a secretary. It's like the difference between a nurse and a MD. They're both the same job, except one is expected to do considerably less than the other.

Everything you just said is invalid because the new title implies an authority that the individual does not have.

"Command intern" would be a far better title for what you just described.

**Comment by Rykka-Stormheart** [comment]
> > ...I don't get why "i don't see the purpose of this" is a valid criticism for a fluff title. Alt-titles literally just exist for RP purposes and don't affect the game in any way, having more does nothing to the server. Also like Rykka said, this is supposed to be for people who actually want to learn about command instead of just doing paperwork and existing on the sidelines like a secretary. It's like the difference between a nurse and a MD. They're both the same job, except one is expected to do considerably less than the other.
> 
> Everything you just said is invalid because the new title implies an authority that the individual does not have.
> 
> "Command intern" would be a far better title for what you just described.

If people are implying authority with this title, laugh at them. If they're getting out of hand, contact their IC Supervisor, the CD/literally any Head of Staff, or just ahelp. It's not a role with any capability to command anyone else, and, frankly, "Bridge Officer" sounds better than "Command Intern", because a _good_ Bridge Officer will help Command accomplish their tasks, whereas an intern seems useless.

**Comment by Haery70** [comment]
I'm siding with Ace on this one, as I've stated back on the Github there's no need for an alt-title called 'Bridge Officer' for the Command Secretary. The role's already on thin ice and adding an alt-title like this one is going to lead to abuse of power just like Blueshield which is pretty much what a Bridge Officer actually is. Telling people to ignore them, report them to other Heads of Staff, or ahelping them will only escalate the situation more than it shouldn't since it drags things on further.
Personally, I'm more in favor of merging Command Secretary with Intern and splitting access levels between alt-titles within reasonable levels.

Besides, giving them an alt-title for the purpose of making them feel more useful seems more  counterproductive than it should, for it could only make them appear more useless than before. Not like Command ever calls on Command Secretaries or Interns anyway since they're already assumed to be useless, afk, or engaged in erotic/vore RP to be of any use.

**Comment by Heroman3003** [comment]
In the end, that is the primary and main purpose of secretaries. They are command interns, whose job is to assist command in general duties, paperwork, whatever. They aren't meant to sound like a serious position because they don't have duties, authority or any importance at all. Command Intern alt-title is a good idea, as it allows to highlight learning process without exasperating the issues the job already has. Its duties when it comes to practice are near-nonexistant and trying to draw some splitting line in those barely-there duties only makes the job seem even less relevant.

Also, the slot amount increase is still there, just by one slot instead. Highlighting this just in case.

**Comment by Heroman3003** [comment]
On the mechanical side of things, you really dont need to copy absolutely everything into _vr files, but only lines that will be edited and/or added as overrides. That just can create needless confusion.

**Comment by HzDonut** [comment]
I think y'all don't understand that an officer isn't locked to only being security, or at least Haery doesn't.

Also Blueshields are a LRP meme role to just be stick to the captain's hip and then murder people for funsies, they're completely irrelevant to this server.

**Comment by Rykka-Stormheart** [comment]
I still stand by my point that while it's not "needed", it's a fluff title. My first PR was denied because it was a separate entire job. That's fine.

An alt-title does nothing but be there to "look different". And, again, I'll reiterate this as many times as necessary, if a BO is being fucking stupid, or overstepping their bounds, chain-of-command their ass, or ahelp it. They're not fucking officers, they're Command Assistants who are specialized in assisting and working on the Bridge.

**Comment by Rykka-Stormheart** [comment]
> Also, the slot amount increase is still there, just by one slot instead. Highlighting this just in case.

Intentional.

**Comment by Haery70** [comment]
>HzDonut says: 
I think y'all don't understand that an officer isn't locked to only being security, or at least Haery doesn't.

Here's your dictionary quote for officer as a noun.

> a person holding a position of **command or authority** in the **armed services, in the merchant marine, or on a passenger ship**.

or

> a holder of a **public, civil, or ecclesiastical office**.

Nothing within the definition would describe the purpose of what people who support this want to ideally think that the Bridge Officer would fulfill in a **private corporate research facility in the Command Bridge**. When people see the word officer, their first thought isn't going to be, "Oh, yeah! We just do paperwork and fetch coffee for our bosses." People are going to instantly believe that it's a position of command/authority and treat it as so because of terms' common ties with military, police, and security detail. Trying to stomp out all meaning in the term to suit the ideals within the purpose of the alt-title via ahelps and IC would only make things worse. That's why I'm comparing it to Blueshield because the position of Bridge Officer would fit this nonexistent role as an alt-title over a Command Secretary.

Also, I like to add that saying that they're not officers despite the fact that their alt-title clearly states that they're an officer is pretty ironic and heavily confusing in a way.

**Comment by HzDonut** [comment]
I said they're not SECURITY. Learn to read :v

**Comment by Rykka-Stormheart** [comment]
> > HzDonut says:
> > I think y'all don't understand that an officer isn't locked to only being security, or at least Haery doesn't.
> 
> Here's your dictionary quote for officer as a noun.
> 
> > a person holding a position of **command or authority** in the **armed services, in the merchant marine, or on a passenger ship**.
> 
> or
> 
> > a holder of a **public, civil, or ecclesiastical office**.
> 
> Nothing within the definition would describe the purpose of what people who support this want to ideally think that the Bridge Officer would fulfill in a **private corporate research facility in the Command Bridge**. When people see the word officer, their first thought isn't going to be, "Oh, yeah! We just do paperwork and fetch coffee for our bosses." People are going to instantly believe that it's a position of command/authority and treat it as so because of terms' common ties with military, police, and security detail. Trying to stomp out all meaning in the term to suit the ideals within the purpose of the alt-title via ahelps and IC would only make things worse. That's why I'm comparing it to Blueshield because the position of Bridge Officer would fit this nonexistent role as an alt-title over a Command Secretary.
> 
> Also, I like to add that saying that they're not officers despite the fact that their alt-title clearly states that they're an officer is pretty ironic and heavily confusing in a way.

And to counterpoint your "they have authority" - Blueshield doesn't exist, first off, from my understanding - it existed 5 years ago, and was removed. So stop referencing it.
Second - They are "OFFICERS" of the "BRIDGE", not the station. They are not assigned any authority nor access beyond that of a CS. They're not Security, and if people don't believe it, that's their problem. If BO's overstep their bounds? Deal with it ICly or ahelp, you keep saying "it makes things worse". Explain to me HOW it makes things worse. It's called conflict resolution.

And? When's the last time you played Command Sec?

**Comment by Haery70** [comment]
I did read, and again, just as Ace has stated the term officer reeks of authority as I've been trying to say. It's not limited to just security, but is still enough to make people think that they have power over others. No amount of IC problem-solving and ahelps can save us from the amounts of abuse that could follow because it would simply be better for it to just not exist at all.

**Comment by Rykka-Stormheart** [comment]
> I did read, and again, just as Ace has stated the term officer reeks of authority as I've been trying to say. It's not limited to just security, but is still enough to make people think that they have power over others. No amount of IC problem-solving and ahelps can save us from the amounts of abuse that could follow because it would simply be better for it to just not exist at all.

I mean, if you think it'll be abused so heavily, get rid of Sec? Get rid of all the "abuse-able" things and hhhh.... you no longer have a game. It's called rules. We have them to prevent abuse. Instead of screaming "ABUSE", explain how? I've countered your point about "authority being abused" multiple times.

**Comment by Heroman3003** [comment]
Because unlike security, the alt-title adds nothing of value or novelty to the game as a whole. It has all exact same things as existing secretary. Except with much more abusable connotations due to the name. All the things you said you would expect the "Bridge Officer" to be, secretaries already are, so not even anything new in terms of duties or expectations.

**Comment by Rykka-Stormheart** [comment]
> Because unlike security, the alt-title adds nothing of value or novelty to the game as a whole. It has all exact same things as existing secretary. Except with much more abusable connotations due to the name. All the things you said you would expect the "Bridge Officer" to be, secretaries already are, so not even anything new in terms of duties or expectations.

Does everything have to add "value"? Adding Fennec pAI forms adds absolutely no "value" to the game, yet I did it.

**Comment by Haery70** [comment]
> And to counterpoint your "they have authority" - Blueshield doesn't exist, first off, from my understanding - it existed 5 years ago, and was removed. So stop referencing it.

I'll continue to reference Blueshield, regardless of whether or not they're still around because **that's exactly what a Bridge Officer would end up becoming in the first place**. You continue to spout rules, ahelps, and other things onto something that would be a constant headache for admins to deal with themselves, which is something that they should **not have to be dealing with in the first place**.

When people take a position in Command, they tend to assume that they can lord over everyone, including those that are not in their department when in reality they are limited to what authority they have other others. Heads of Staff have authority over those that are in their department. Command Secretaries? They'd be better off as an Intern Alt-Title. But, due to how most people that play the role take it as a belief that they already have some form of authority over others and it's happened numerous times to the point to where it [almost got removed.](https://github.com/VOREStation/VOREStation/pull/5251) There's really no need to explain abuse for a role that's already been abused if something that could potentially increase the rate of abuse gets added in.
 As I've stated in the past, you don't need to add an alt-title of such caliber to make them feel more useful, you need to give them something to do which is not inherently a problem with the secretaries, but a problem with the Heads of Staff itself because of their views towards them and Interns in general. The reason why we have Interns and Visitors was to replace the running gag of Assistants being lazy shits. But, since Visitors are just a copypaste of Interns, Interns will continue to remain largely ignored and overshadowed, unable to get out of the limbo that is Assistantmania.

Command Secretaries have that same problem because they are seen as Assistants, but with Bridge access. Adding a role with implications that it has more authority will only make things worse for them and continue to feed this vicious cycle, especially one that has the word 'officer' in its name.

Unlike vore and erp, if the playerbase that's already ingame or the admins have to repeatedly remind people not to abuse something repeatedly, then maybe it shouldn't have been there from the beginning and unlike security it leads to an increase in abuse. We've already removed Asshole as an alt-title for Clowns for obvious reasons, Bridge Officer would end up going down that same path.

**Comment by SpadesNeil** [comment]
Yeah, I concur, this is Blueshield all over again.

Regardless of what you say the role is for, I know how the role will end up being used. Furthermore, we don't need this to begin with.

After watching this argument play out, my decision is made. This will not be merged.

**Pull request closed without merging**
