### PR TITLE
[Map] Onions and Layers

### PR DESCRIPTION
**Pull request by TheFurryFeline**
Changelog Notes:

- Fixes layers for shutters and blast doors throughout the main station.

- Also adding in removal of mining's old substation per a discussion from last night. Yet ANOTHER oversight I did with it, good job, old me. Substation replaced with couple maint loot stuff and filled in with rock/wall.

- Making the door leading to old Mining EVA public access. Will restrict to Mining + Medical if needed.

- Missing firelock added for door to Atmos Processing pipes.

### CODE REVIEW

**Comment by Arokha** [comment]
I'm... confused about this layers fix for blast doors and stuff. Is this because they look weird in DM? They change their layer every time they open and close ingame. Whatever you set in DM is going to mean nothing once they're opened or closed once ingame.

**Comment by TheFurryFeline** [comment]
> I'm... confused about this layers fix for blast doors and stuff. Is this because they look weird in DM? They change their layer every time they open and close ingame. Whatever you set in DM is going to mean nothing once they're opened or closed once ingame.

Take a look at how the layering happens on current live. The blast doors at the bridge, atmos entrance, and other places, layer on **top** of the door after it opens. This makes it hard to close again without precise clicking, from purrsonal experience, and can be extremely annoying.

**Comment by Arokha** [comment]
I mean, it shouldn't fix that, because the blast doors set their layer every time they close/open. Anything you put in the map editor for layer will only last until it's used once.

Also blast doors aren't supposed to be close-able by clicking on them... they're controllable by remote...

**Comment by TheFurryFeline** [comment]
That's not why this is being done. I've made the closed layer reduced to the lowest so it doesn't show up in its open state when someone's passing through the doorways. And I've tested it. It keeps the settings, or at least the sprites don't revert to its present state of being layered over an open airlock.

**Pull request merged**
