### PR TITLE
Port Eris grenade sprites

### PR DESCRIPTION
**Pull request by Arokha**
I also sprited some that didn't exist in either codebase, like teargas, cleaner grenades, and made same-theme versions of banana grenades. I'll leave clusterbangs as they are for historic reasons.

EDIT: The top row looks like this now:
dreammaker_9k11lFpsFz

Top row is old, looks like above:
image

### CODE REVIEW

**Comment by dwinters99** [comment]
I really don't know how to feel about these. They all just look like the Left 4 Dead 2 boomer bile jars or a rip-off M84 grenade. Not to mention the NT grenades retain the religion aspect of Eris which doesn't really fit our lore or our art-style. Sometimes shiny isn't always better- in fact, I actually dislike a LOT of Eris sprites because of how much I like the codersprite "art-style" SS13 has.

**Comment by Arokha** [comment]
> I really don't know how to feel about these. They all just look like the Left 4 Dead 2 boomer bile jars or a rip-off M84 grenade. Not to mention the NT grenades retain the religion aspect of Eris which doesn't really fit our lore or our art-style. Sometimes shiny isn't always better- in fact, I actually dislike a LOT of Eris sprites because of how much I like the codersprite "art-style" SS13 has.

I guess we'll have to disagree about that... I like the professional game developer sprites more. And the religious ones aren't used for anything, I just imported the whole thing. They're there if a dev wants to make joke grenades or something for away missions or whatever. Ascian likes having extra sprites around to play with.

**Comment by Heroman3003** [comment]
They look okay, but I feel like 'default' grenade looks a bit too... Specific in coloration/design. The darkgrey from before was way more generic, which was good considering how much of anything default grenade looks.

**Comment by ShadeAware** [comment]
I think the chemical grenades could use a bit of a facelift. As of right now they feel too... bright, almost like they're made of foam. The old grey designs were atleast more general-purpose.

**Comment by Arokha** [comment]
Alrighty, I changed the chem grenades to be grey:
image

**Comment by Very-Soft** [comment]
I think this is fine. Some of them look quite a bit nicer than ours.

**Comment by Heroman3003** [comment]
Yeah, these generic ones are way better, imo.

**Comment by Screemonster** [comment]
Yeah, green grenades looked kinda meh but the grey is a lot better.

**Pull request merged**
