### PR TITLE
Adds a very lorg fen

### PR DESCRIPTION
**Pull request by Arokha**
She BIG. Sprite by @Ketrai!

For adminbuse/boss stuff, very powerful. If you're mob-edible she may sometimes just autonomf you during combat. If you're not mob edible, and <= 0.5 scale, she may do a stomp and crush you into nothing.

### CODE REVIEW

**Comment by Heroman3003** [comment]
The whole gibs into oblivion seems unnecesarily harsh and the fact that that one doesn't even check for existing prefs regarding step mechanics seems very rude.

**Comment by Arokha** [comment]
> The whole gibs into oblivion seems unnecesarily harsh and the fact that that one doesn't even check for existing prefs regarding step mechanics seems very rude.

It's for adminbuse, so 'harsh' isn't really relevant. The steps pref is something I totally forgot about though! I'll add that.

**Comment by Arokha** [comment]
S P E D M E R G

This isn't mapped in anywhere, and someone is wanting to work on it. So, given that it's a non-presence in gameplay, I'm just gonna do that so they can PR whatever changes they feel like instead of messing with 'they PR changes to my branch yadda'.

**Comment by Razgriz1032** [comment]
Whose OC is this

**Comment by Ketrai** [comment]
Mh, the gibbing doesn't really seem needed. If it's too powerful it's going to be hard for normal players to get an opportunity to play it :o

**Pull request merged**
