### PR TITLE
Re-enables the old vox sprites.

### PR DESCRIPTION
**Pull request by Verkister**
-Requested and majorly preferred shitBIRDS
-Noticed the old icons weren't even removed after all in the update, just renamed so gg ez

### CODE REVIEW

**Comment by AaronSherwood117** [comment]
Please yes.  Who thought three bright pink eyes and beak removal was a good idea?

**Comment by SpadesNeil** [comment]
Can we have a comparison of old vs new?

**Comment by Verkister** [comment]
kuva

**Comment by AaronSherwood117** [comment]
What is with all the pink and purple smears on them? Why are there single pixels on the shoulders? What is that thing on their chest supposed to be?  It just looks like some spriter went "Let's make them look like something from Halo" instead of, you know, Vox.  I just really want my old appearance back; such a dramatic overhaul with no warning sucks.

**Comment by DickFreedomJohnson** [comment]
return OG vox please they are supposed to be birds not whatever the fuck that beast is

**Comment by Rapidvalj** [comment]
Nooooo dont make them more generic. They're unique the way they are right now, and much better than literal space birds.

**Comment by AaronSherwood117** [comment]
@Rapidvalj They were also unique before, in no way were they 'more generic'.  Someone just mass-swapped pixels and haphazardly slapped on 'extra detail'.  In case you weren't paying attention, they're SUPPOSED to look fairly avian.
Seriously, the hell do you mean by 'make them more generic'?

@SpadesNeil Comments please?

**Comment by SpadesNeil** [comment]
I really like the new sprite so...  ¯\_(ツ)_/¯

**Comment by Verkister** [comment]
Imo the new look is a mess and will stay a mess until someone brings me the design the new sprites were based on. I for one am having hard time deciphering the pixels beyond "vaguely vox shaped amorphous uprooted swamp lump" from the sprites alone. Like there seem to be no consistent or recognizeable facial features apart from the 3 garishly pink eyes :v

**Comment by Verkister** [comment]
Hell what would even stop me from going extra again and just OC spriting a whole new and professionally done clear and consistent design based on the desirable parts of each style?

**Comment by Verkister** [comment]
So I'm about to do a next-gen professional combowombo, yeah?
Time to get parts-picking y'all. Taking in any and all feedback and suggestions.

**Comment by Cyantime** [comment]
The PR that added these sprites is https://github.com/Baystation12/Baystation12/pull/17620
They're based on artwork by the guy who originally created and added vox to ss13.

**Comment by Dhaeleena** [comment]
I dont play vox but that new sprite looks like a mess

**Comment by AaronSherwood117** [comment]
@Cyantime Looking at that, I see the issue. The guy re-sprited based totally on the Armalis appearance instead of normal Vox.
@Verkister If you'll be doing that, I vote for:
-Third eye removal
-Beak Re-Addition
-Fixing the pink/purple smudges on the face/chest
-Cleaning that weird dark V of pixels that makes it look like an exosuit or something
-Would it be possible to let the player choose a shade of green within a certain range? Say, between old color of light yellowish-green and new color of dark undergrowth green.
-Back to one tail

I really wouldn't mind the color shift if it didn't also make a few particularly annoying design choices.

**Comment by SpadesNeil** [comment]
Oh. So as usual, Bay ruins everything. :B

**Comment by SpadesNeil** [comment]
We'll do the fixes later.

**Comment by Zuhayr** [comment]
Just going to chip in, because it's hilarious: @AaronSherwood117 @DickFreedomJohnson I did both the original icon and the art you linked in this thread, including the one Prometh based his new icons on/. Vox were never meant to be birds, and the image description you claim represents an armalis just says 'the armalis have been busy' which was actually a typo for apex, but remains irrelevant either way.

Even if Prometh's icon is a bit muddy, it's still a vast improvement on the hyper-bland bird-person original icon.

No opinion or basis for commentary on what VORE is doing, but claiming misinformation on the part of _the person who made the species_ is misguided at best.

**Comment by Belsima** [comment]
zuhayr you are misinformed
vox are birds
please do not lie to us
you can not even comprehend the vox

**Comment by Zuhayr** [comment]
`*chirp`

**Pull request merged**
