### PR TITLE
Gazer Fluff.

### PR DESCRIPTION
**Pull request by LiquidFirefly**
Gazer fluff stuff.  Added Monoeye to public markings, because cyclops stuff.

### CODE REVIEW

**Comment by LiquidFirefly** [comment]
Changes have been made, we should be good now.

**Comment by Arokha** [comment]
Was there an app for the eyestalks? If you could link it here for posterity, I'd appreciate it.

**Comment by LiquidFirefly** [comment]
[This](http://forum.vore-station.net/viewtopic.php?f=45&t=892) is the only app that was submitted.  I'd posted an issue on here about it after a week of it sticking around.  Got approval pending after asking about the fluff.

**Comment by Arokha** [comment]
https://github.com/VOREStation/VOREStation/issues/1403

**Pull request merged**
