### PR TITLE
NOTHING TO SEE HERE MOVE ALONG

### PR DESCRIPTION
**Pull request by Dhaeleena**
Changes to legit non syndicate and totally not hidden and legal base, Adds med-bay for the law abiding members of society

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Please use the map merge tool correctly.

**Comment by Dhaeleena** [comment]
@SpadesNeil i was told the map merge tool doesn't work correctly atm

**Comment by SpadesNeil** [comment]
Who said that? Since when?

**Comment by Yoshax** [comment]
It should work. I changed the map merge to be directed at Tether. There shouldn't really be any difference,  I don't think. But I haven't really fully tested it. Looked fine on a small test though.

**Pull request merged**
