### PR TITLE
Skyrat emitter sprites

### PR DESCRIPTION
**Pull request by Arokha**
Old vs new

dreammaker_MBWUEDZYQv
dreammaker_CkNKMxFeXy

Also removes the Contain_F sprite from the file because the field generator PR moves it to it's file, so these either both need to be merged or one can be merged and the other edited.

### CODE REVIEW

**Comment by Very-Soft** [comment]
I like this but aren't our emitters not this one anymore? I thought we were using the barrel one with wheels and different states for securedness

**Comment by Arokha** [comment]
> I like this but aren't our emitters not this one anymore? I thought we were using the barrel one with wheels and different states for securedness

We are but I like these even more

**Comment by GhostActual** [comment]
> We are but I like these even more

I actually like the ones that are currently used and I was going to port them upstream if Polaris didn't have them. They make more sense being on wheels.

**Comment by Arokha** [comment]
Hm! Well, alright then.

**Pull request closed without merging**
