### PR TITLE
Eris multitool sprite

### PR DESCRIPTION
**Pull request by Arokha**
image

### CODE REVIEW

**Comment by dwinters99** [comment]
Please no. It doesn't fit. Please. These sprites just don't fit.

**Comment by Heroman3003** [comment]
I dont like the yellow color of it. Old sprite's yellow would look better on it.

**Comment by Very-Soft** [comment]
I do like the new sprite more than the old one. The old one is a classic, but the new one looks way more interesting and looks like a kind of evolution to the old design, with better material properties and shading going on to it. 

Me like.

**Comment by ShadeAware** [comment]
Very good, looks like something you'd actually use as a tool and not just an electrified banana.

**Comment by Screemonster** [comment]
This looks like an actual multimeter and not... whatever the old multitool is.

**Pull request merged**
