### PR TITLE
New folders/pen/clipboard sprites

### PR DESCRIPTION
**Pull request by Arokha**
image

From CEV-Eris (or maybe Bay?)

### CODE REVIEW

**Comment by Rykka-Stormheart** [comment]
I approve. Gewd. <3

**Comment by Cameron653** [comment]
The darker outline on the clipboard and the higher quality pens look nice, but those folders look _very_ good. 👍

**Comment by Heroman3003** [comment]
Colored folders just look much more pastel. Where did the deep colors go on folders, particularly red and blue?

Blue pen is now even less distinguishable from black one with how blue blends in.

Also its missing CE and HoS folders.

**Comment by Novacat** [comment]
CE and HOS folders would be nice, yah.

**Comment by Arokha** [comment]
> Also its missing CE and HoS folders.
> CE and HOS folders would be nice, yah.

They don't exist now though. You are welcome to sprite them.

**Comment by Arokha** [comment]
image

**Pull request merged**
