### PR TITLE
[AI BRANCH] Attempt to fix Active Edge

### PR DESCRIPTION
**Pull request by Novacat**
Probably should have a better fix long term, this is mostly to confirm something.

### CODE REVIEW

**Comment by Novacat** [comment]
Okay. Travis passed.

I poked Polaris about why this change happened, and the only response I got was that it was to stop vacuum tiles from forming when people drilled out stuff.

An alternative solution to this issue is to have a subtype of turf/space at the midpoint instead of the current indestructible walls.

**Comment by Heroman3003** [comment]
The problem with space at midpoint would be the fact that technically z-3 and z-4 are connected.

**Comment by Novacat** [comment]
It would be a subtype of space, that would be some kind of blocking tile. It would still pass the check, I think.

**Comment by Verkister** [comment]
The real solution polaris shouls have implemented in the first place would be actually utilizing the area/z-level defined base turf instead of hardcoding all holes to lead to space :v

**Pull request merged**
