### PR TITLE
Renames Engineer, new alt-titles for Stellar Delight

### PR DESCRIPTION
**Pull request by Heroman3003**
Too tired rn for any detailed or thorough description.

Renames Station Engineer to Engineer, globally
~~Makes Captain alt-title exclusive to Stellar Delight~~

Adds extra alt-titles exclusive to Stellar Delight:
HoP - First Mate
~~Atmostech - Refueling Technician~~
Atmostech - Fuel Technician
~~Warden - Gunner~~
Warden - Man-at-Arms
~~Security Officer - Ship Officer~~

### CODE REVIEW

**Comment by JoanRisu** [comment]
Should be good to go. Make sure Soft reviews this.

**Comment by Very-Soft** [comment]
Captain should not be exclusive to the SD. It's a general title, you don't stop being a captain when you step foot on the ground somewhere.

**Review by Very-Soft — CHANGES_REQUESTED** [review]
Pls leave captain alone

**Comment by SigholtStarsong** [comment]
Master-At-Arms is the generally accepted naval rating for personnel assigned security duties aboard US Navy/Royal Navy vessels, with a Chief Master-at-Arms (CMAA) being placed in command.

The Warden is a bit tricky to snag an alt-title for, but Corrections Specialist or Brig Steward are somewhat appropriate.

**Comment by Heroman3003** [comment]
> 
> 
> Master-At-Arms is the generally accepted naval rating for personnel assigned security duties aboard US Navy/Royal Navy vessels, with a Chief Master-at-Arms (CMAA) being placed in command.
> 
> The Warden is a bit tricky to snag an alt-title for, but Corrections Specialist or Brig Steward are somewhat appropriate.
> 
> If we're adding First Mate for HoP, would Executive Officer also be a good title? They're direct equivalents, both being second-in-command.

Iuono about first two, but in my original big alt-title PR I did propose Executive Officer as Site Manager alt-title, and IIRC it was turned down for sounding too much like something a Central character would have.

**Comment by KillianKirilenko** [comment]
> Very-Soft wrote:
>     [stuff about gunner]

Inclined to agree. If there were operated turrets on the ship, I'd expect alt-titled security officers to be manning them, not the warden. There is, after all, only the one warden.

The closest you're likely to get is if an ORB/OFD is added, and that's... not really a gun *per se*.

> Master-at-arms

Fun fact, you can actually *get* a master-at-arms brassard as a loadout accessory, and have been able to for a pretty long while.

**Comment by faaaay** [comment]
> Iuono about first two, but in my original big alt-title PR I did propose Executive Officer as Site Manager alt-title, and IIRC it was turned down for sounding too much like something a Central character would have.

Isn't Executive Officer usually a title given to the second in command, with Commanding Officer being the Captain of a vessel?

**Comment by SigholtStarsong** [comment]
> Isn't Executive Officer usually a title given to the second in command, with Commanding Officer being the Captain of a vessel?

Correct, at least in US Naval tradition.

**Comment by lm40** [comment]
first mate is fine, i would honestly prefer something like 'fuel technician' rather than 'refueling technician' personally
gunner & ship officer are iffy for the reasons that people have already brought up, if i didn't read this pr i would probably have assumed ship officer was an alt title for command  secretary or something lmao

**Comment by Very-Soft** [comment]
I do agree with Kenzie's suggestion of making it just be 'Fuel Technician', since that's a little more accurate to what you can actually do in atmos most of the time, and would reasonably cover the base of 'refueling' too.

**Comment by Heroman3003** [comment]
Did adjustments based on feedback. Renamed Refueling Tech to just Fuel Tech, renamed Gunner to Master-at-Arms, removed Ship Officer

**Pull request merged**
