### PR TITLE
Whitelist and Custom Items gitignore update

### PR DESCRIPTION
**Pull request by SpadesNeil**
I *really* don't care if players can see these on the server Github. Not
only will this make things easier to update, it'll also stop this stupid
bullshit idea that the server is full of snowflakes with gun permits.
Full transparency!

Yes I'm aware we could just use filezilla to do this but screw that.

### CODE REVIEW

**Comment by JoanRisu** [comment]
Gosh darn it Ace, and after Arokha taught me how to connect to serverbox. >:C

**Comment by SpadesNeil** [comment]
But this is easier and less messy. :(

**Comment by Arokha** [comment]
Before you update the server next, I would delete these files from the server, and let the update pull recreate them.

**Comment by SpadesNeil** [comment]
I'll do that, then.

**Comment by Cameron653** [comment]
Might be a late reply, but the whitelist is working, it's just that diona
haven't been whitelisted. I can make a pr later to whitelist them.

**Pull request merged**
