### PR TITLE
fixing some messed up medical hardsuit helmet sprites

### PR DESCRIPTION
**Pull request by kcin2001**

### CODE REVIEW

**Comment by SpadesNeil** [comment]
What was messed up about them? Also, this fix should go to Polaris.

**Comment by kcin2001** [comment]
i didnt think about pushing to polaris but on 2 of the med rig helmets the east and west sprites were flipped

**Comment by SpadesNeil** [comment]
What are the seromi again? Those aren't our thing, are they? Because if those sprites are fucked up, then Polaris needs this fix.

**Comment by Cyantime** [comment]
Seromi are what teshari are called in the code, it's their original name

**Comment by SpadesNeil** [comment]
Okay yea, don't fix this here. Fix this in Polaris.

**Pull request closed without merging**
