### PR TITLE
[FEEDBACK NEEDED]Traits tweaks.

### PR DESCRIPTION
**Pull request by lbnesquik**
- Make Conductive 1 increase damage to 75% and not 50%
- Make major conductive increase damage to 150% and not 100%
- Add numbing fangs as a standalone trait. (Nah it's not too many traits.)
Everything up for debate.

### CODE REVIEW

**Comment by CameronWoof** [comment]
This also increases the cost of Major Darksight from 2 to 3.

Can you explain your rationale for these changes?

**Comment by KasparoVy** [comment]
RIP darksight

**Comment by lbnesquik** [comment]
Very useful utility perk that helps in and out of combat.

**Comment by Mewchild** [comment]
You need to do testing with the conductive traits, as those may allow individuals to be one or two shot by tasers, and may make electrical shocks lethal as a baseline. I also disagree that darksight (major) is as useful as you think it is, given the adjustment time needed between light and dark areas, and the fact that any source of light, at all, renders it useless.

**Pull request closed without merging**
