### PR TITLE
Add a few new chair types

### PR DESCRIPTION
**Pull request by Arokha**
Some new chair types including various mounted chairs from Bay, some vibrant seats from Eris, and a few nests for Teshari to rest their butts in.

dreamseeker_2020-02-20_22-29-29
From CEV-Eris ^^^
image
From Baystation12 ^^^

### CODE REVIEW

**Comment by Very-Soft** [comment]
aeg

**Comment by Arokha** [comment]
AEG

**Comment by Ketrai** [comment]
I would desarurate the orange. They look a little neon. Otherwise they look great.

**Comment by Novacat** [comment]
Fix conflict tho, should be good after that.

**Comment by Arokha** [comment]
Added a bunch more chair styles from Bay like their dropship-style ship chairs and their normal mounted chairs

**Comment by Arokha** [comment]
Added a few more chair types from Bay, like one that Teshari can sit their raptor butts on.

**Pull request merged**
