### PR TITLE
[WIP, DNM] Adds Phoron Crystallizer!

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
Adds a Phoron Crystallizer - requires manual start, but once started, pulls phoron from outside atmos, converts it into sheets of phoron, requires coolant to not overheat.

I'm putting this down as a WIP because man am I fucking new and didn't realize how much I was underestimating this. I'll keep working on it, so if you want to laugh at my poor execution, you're welcome to :p

Inspired by #5145

### CODE REVIEW

**Comment by Screemonster** [comment]
oh boy oh boy it's a reverse-pacman

what happens if it overheats? Will it explode? Please tell me it explodes. Explosion to scale with the amount of sheets sitting in it when it reaches the temperature threshold?
Crazy-dangerous machines that punish you for your hubris if you tamper in god's domain are _peak_ SS13 and we need more of them, fuck this push towards bubblewrapping everything that I've seen some folks agitate for.

**Comment by Very-Soft** [comment]
If possible, I'd prefer something like this to have some form of possible collaboration between departments, but to be mainly a cargo job, since non miners typically have very little to do, and decent reason for wanting ever increasing amounts of phoron.

As I suggested in the original thing though, I think it would be great if something they needed for this could be ordered at an expense to make it not too profitable, or for the item to be craftable through chemistry. Since both science and medical have chemistry, it could allow for some reasonable cooperation.

Happy to see this worked on either way~

**Comment by Rykka-Stormheart** [comment]
> If possible, I'd prefer something like this to have some form of possible collaboration between departments, but to be mainly a cargo job, since non miners typically have very little to do, and decent reason for wanting ever increasing amounts of phoron.
> 
> As I suggested in the original thing though, I think it would be great if something they needed for this could be ordered at an expense to make it not too profitable, or for the item to be craftable through chemistry. Since both science and medical have chemistry, it could allow for some reasonable cooperation.
> 
> Happy to see this worked on either way~

Ye, the plan is for it to require coolant, if you run it w/out coolant, it catches fire/overheats... just like a pacman, sorta.

**Comment by Wickedtemp** [comment]
coolant, the reagent, can be made via chemistry.

**Comment by Rykka-Stormheart** [comment]
> coolant, the reagent, can be made via chemistry.

yis! It's where I got the idea from <3

**Comment by Rykka-Stormheart** [comment]
> Might want to change the filenames to include _vr, if it's going to only be for VOREStation.

Done

**Comment by chaoko99** [comment]
That's not how that works by the way. _vr are for override files. Don't worry about it, but.. That's just a thing for future reference.

**Comment by SpadesNeil** [comment]
It's fine in this context.

**Pull request closed without merging**
