### PR TITLE
Silicon OOC prefs fix TAKE 2

### LINKED ISSUE #2107: OOC notes broken on borgs and pAIs
#### Brief description of the issue
OOC notes link is unclickable for others as a borg. It however does open for the borg player themself, but does nothing for anyone else.
On pAIs they don't show up at all, but I'm not sure if it's restricted to the pre-download description to even begin with, but definitely is a feature that should exist.

#### What you expected to happen
OOC notes to be visible for other players.

#### What actually happened
OOC notes opened for the borg player, but showed absolutely nothing for anyone else.

#### Steps to reproduce
- (Step 1) Be a borg.
- (Step 2) Have OOC notes.
- (Step 3) Click the link and see it open up all fine.
- (Step 4) Have someone point out you have no OOC notes.
- (Step 5) Be the other player.
- (Step 6) Click on the borg's OOC notes.
- (Step 7) The computer says no.

#### Code Revision
- d127e06c0dcfb65be5a01c75ac6887c1ca3058c9
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

### PR DESCRIPTION
**Pull request by Funce**
Cheers for the ping @AeroWing

Fixes #2107 

If you would care for AI holograms, or pAI cards to also have OOC prefs, I could definitely add those nice and quick.

### CODE REVIEW

**Comment by chaoko99** [comment]
Holopads would be nice!

**Comment by Funce** [comment]
So AI holograms need proper testing from another's view point. Because you can't leave your hologram out whilst aghosting

**Comment by Cyantime** [comment]
To test as multiple people at once, disable the anti-guest proc at https://github.com/VOREStation/VOREStation/blob/master/code/_helpers/unsorted.dm#L270 by making it always return 0, then when you're connected as your normal ckey, log out of the byond pager and connect again through dream daemon to join as a guest.

**Comment by Funce** [comment]
An easier way was I just changed the config file to allow guests. Hologram OOC notes work just fine

**Pull request merged**
