### PR TITLE
[WIP, DNM] Add another Exploration Area - Space Hulk!

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
If any of you have seen 40k lore, you'll understand this, if not, I'll explain.
Space Hulks are a mishmash of ships combined in the warp (Redspace here). The idea is that the exploration team manages to find a dock somewhere aboard the Space Hulk, and goes to clear it in order to bring goodies back to the station.

Currently Finished Features:
- Add map to mapload list

WIP or Planned Features:
- Add Ambience to all areas
- Add new (custom) turrets for hangar/other areas
- Add 3 new hostile xenos/etc mobs
- Setup POI system to generate "rooms"
- Add new turfs for better appearance
- Add interactions with new hostile mobs (Xenobiology can harvest 'resin' from the xenos, etc)

I was originally intending to keep this "hidden", but I decided fuck it, it's not a bad idea to PR it so people can follow along - maybe someone will help out. <3

### CODE REVIEW

**Comment by lbnesquik** [comment]
Could we have pictures maybe? It sounds pretty interesting but hard to comment like this.

**Comment by Sebbe9123** [comment]
> Could we have pictures maybe? It sounds pretty interesting but hard to comment like this.

If you look in the map dif bot, you can see the map

**Comment by SpadesNeil** [comment]
Conflicts and still marked WIP for some reason.

**Comment by Rykka-Stormheart** [comment]
> Conflicts and still marked WIP for some reason.

It's currently halted development due to IRL stuff going on, and the fact that I can't get the POI system to work how I wanted. I wanted random gen hallways and rooms and such. But the POI system won't allow that/work properly.

**Comment by TheFurryFeline** [comment]
Conflicts resolved.

**Comment by SpadesNeil** [comment]
Is this ever going to not be WIP?

**Comment by Rykka-Stormheart** [comment]
> Is this ever going to not be WIP?

I'll see about updating it soon, but given I've not started on work as far as the turrets go, I'll close the PR and just work on it locally

**Pull request closed without merging**
