### PR TITLE
Engineering Mod-Computer Conversion.

### PR DESCRIPTION
**Pull request by Andromeda-K22**
This PR replaces a lot of the non specific computers (station alert consoles, power monitoring, RCON, etc) with Modular Computers. It seems like a good idea, specifically in conjunction with #8990 since modular computers *are* more flexible.

I should note that I'm not sure if 8990 touches the engineering programs, but regardless, they'll probably be eventually converted.

### CODE REVIEW

**Comment by Heroman3003** [comment]
Specific consoles > MCs

**Comment by Andromeda-K22** [comment]
I, too, enjoy running between tables to check two different computers.

**Comment by ShadowLarkens** [comment]
> I should note that I'm not sure if 8990 touches the engineering programs, but regardless, they'll probably be eventually converted.

That's because #8629 already converted all of them, #8990 completely removes NanoUI from modular computers :p

**Comment by Novacat** [comment]
One of the issues with going full MC would be that MCs require Telecom access to function. Perhaps an alternative solution would be to keep the dedicated consoles but add a single MC console where needed.

**Comment by Andromeda-K22** [comment]
In what situation would tcomms not be present on the main map? Ion storms?

I don't see the problem with this - five minutes of unavailability isn't really critical.

**Comment by Torque4607** [comment]
Speaking from experience with servers like Bastion, Bay, and Urist, modular computers are much more flexible and convenient to use versus the dedicated consoles.

**Comment by Novacat** [comment]
Ion storms, or shifts where the engine was not set up, tcomms usually goes out long before the rest of the station because of the insane power consumption. Compared to Bay, at least, TComms is a lot more finicky/temperamental on Virgo.

**Comment by Andromeda-K22** [comment]
That's because on all other servers, Tcomms runs on it's own fully charged
SMES by default. It does not here.

**Comment by Cyantime** [comment]
As it shouldn't, what's even the point of telecomms needing power if it just has with all the power it'll ever need at roundstart

**Comment by Andromeda-K22** [comment]
Here's the thing.

It doesn't. Tcomms is power hungry, but it will last long enough with the
engine off. It isn't going to stay online through a six hour round.

**Pull request closed without merging**
