### PR TITLE
Some taur contrast tweaks. (And dual color alraune)

### PR DESCRIPTION
**Pull request by Verkister**
-Adjusts some taur parts for a little more consistent brightness/contrast.
-These including naga, feline, lizard, and otie.
-Adds and implements the unwhitelisted dual-color alraune stuff.

kuva

### CODE REVIEW

**Comment by KasparoVy** [comment]
We got some before/after pics for this one?

**Comment by ArgobargSoup** [comment]
@KasparoVy For a rough preview of the base sprite changes, up in the Checks tab above this PR, there's a bot that generates icon difference comparisons... it's easier with this PR because unlike my eyes one, it's more than one or two pixels being moved.

That being said...
@Verkister On the one hand, THANK YOU SO MUCH, some of those taur bodies will look a lot better for colors.  No more grey snake tail when you want a white one...

On the other hand, concerning color matching... to make people's adjusting easier, did you match the taur body shading to the human species sprites they're usually used with?  Like, matching the snake tail to human or unathi body shading?

To go off on a related tangent, we had someone attempt ta do a sprite overhaul for colors and shading in the past, but they only did a part of it (just body sprites, no tails or anything), so colors were still a bit inconsistent.  And like with what KasparoVy said, people had to try and adjust their colors, and the mismatches caused some uproar.

So while I really, _really_, **_really_** like this adjustment, I feel that anything that does big color contrast/brightness tweaks should be part of one big all-in-one overhaul, that like, makes sure that all the colorable sprites use the same shades of grey, with white as the brightest.

...Markings too, with the way they're colored in a different fashion... black as the "brightest"...

**Comment by KasparoVy** [comment]
Awesome

**Comment by KasparoVy** [comment]
Oh wow, they are far brighter overall. Sweet.

**Comment by Verkister** [comment]
sure

**Pull request merged**
