### PR TITLE
Vox Phoron Tank Sprites Additions

### PR DESCRIPTION
**Pull request by HawkerTheGreat**
Fixes https://github.com/VOREStation/VOREStation/issues/1904

Sooo, since I already have everything put together, I just went ahead and dropped these in here for the push. This adds two sprites, _(There are no code or name changes at ALL.)_ plasma_fr and double_phoron_vox to make up for the missing states on the new paradise tank code listed in the issue and a missing belt sprite for double phoron tanks. _(No idea where they went to begin with.)_

I've gone ahead and compiled these, the tanks show as listed in further into the issue. I'll go ahead and pull the extra information and images from the issue now and hopefully this will be pushed. _(also in case we ever get rid of the paradise tank sprites, the state will revert back to phoron_vox which I have left there so we don't have to re-make this merge if we decide these tanks dont look good)_

### CODE REVIEW

**Comment by HawkerTheGreat** [comment]
> **The issue**
> 
> #1692 Was ported in and our tanks are named differently, but I've already gone ahead and changed everything - it just needs a sprite imported (or the old one changed) If someone wants, they can change the state name, but the icon and the back state all need to be renamed, so I just went ahead and made the icons that need to be imported. No code changes required, just a simple import of two sprites.
> 
> I also added a belt sprite for the phoron because it took me a single minute to throw it together, I'm testing it all right now before I attach them... so If all goes well, they'll come up in this issue post. (Unfortunately its going to take a while because I'm on dial up.)

**Comment by HawkerTheGreat** [comment]
> Blah, Blah... Bug fixed, I'm going to bed after I add these two files. I can't be bothered to upload it on a slow internet. Just wanted to fix this because every time it drives me absolute bonkers thankfully its a simple fix if anything.
> 
> [vox.zip](https://github.com/VOREStation/VOREStation/files/1173122/vox.zip)
> 
> image image
> image image

**Comment by HawkerTheGreat** [comment]
Aaand - I just went ahead and forwarded the important stuff. I know I ramble a ton on my issues and merges, but you'll just have to trust me that I didnt mess anything up on this simple fix if you don't like reading.

**Comment by HawkerTheGreat** [comment]
One more final thought on this... I just went and threw this together, but I just forgot... if this is merged without moving the states somewhere else, they'll be overwritten. Either that or I need to fix the paradise tank port update. 

It is safe however and I plan to see if I can't move them so they might not get overwritten.

**Comment by HawkerTheGreat** [comment]
Rather than using a tank that looks nothing like a phoron tank, I added the missing sprites to them and built everything into our codebase so we don't drop these files each update... I also made the last commit that broke these was correctly revised and am just finishing up. 

image

**Comment by HawkerTheGreat** [comment]
**Last Commit**
_Safe to Merge_

Okay! So after a bit of work, I just went ahead and added some missing sprites - just a couple of new tanks and the proper sprites to go with them. I've uploaded all the DMI's that I've changed. Everything is still in there as normal, anything I've replaced sprite wise (one single tank) is now labeled with 'old' and will remain inside of the DMI. I had to modify the code due to #1692 else we have conflicting Vox Tanks. Most of it is just re-directing states to the 'VR' DMI's and a single case of changing the description on a tank so it makes more sense.

In total, there is 3 new phoron tank icons (small, double small, large,) and 3 new phoron tank states to go with them in their respective slots (small, double small, large,) this not only fixes any future issues on the missing tanks, but also fixes #1692 's issue merge as a whole. 

**It has been compiled, tested, and ready to be merged.**

If you have any questions, - any at all... be sure to ask.

**Comment by HawkerTheGreat** [comment]
[vox.zip](https://github.com/VOREStation/VOREStation/files/1175985/vox.zip) Just gonna put this here for the stuff I added if anyone wants the files. (Just the additions.)

**Comment by Cameron653** [comment]
There's an issue - It touches icons/mob/back.dmi

**Comment by HawkerTheGreat** [comment]
I posted the first one and realized that wasn't going to work, the second upload of back and belt are to get rid of my edits (I may have moved the tank sprite around, however while I was fiddling with code.)

**Comment by Cameron653** [comment]
Yeah, just make sure you change it again so that back.dmi isn't being modified, because according to
https://github.com/VOREStation/VOREStation/pull/1908/files
it's being modified.

**Comment by HawkerTheGreat** [comment]
Ok, I went ahead and downloaded the original one and pushed it into my version of the merge, so nothing without a VR tag is being edited.

**Comment by Cameron653** [comment]
Alrighty, it looks good for merge, now.

**Pull request merged**
