### PR TITLE
The Personal Computer Unit

### PR DESCRIPTION
**Pull request by klaasjared**
Adds the new Personal Computer Unit (PCU) to the game to replace the static laptops in atmos, command, and medical. I always thought that the static laptops made no sense considering that there is already a portable laptop in the game - one that looks vastly different from the static one. So to replace the black brick that is the static laptop I dug through the code and found the 'personal' salvage computer in `salvageable.dmi` which I made rotateable. I hope this will be a more "makes sense" version of what is currently in the game. It's certainly better than a generic black box with a screen and buttons.

Pictures of the new computer are found below:

Test3

rotate_showcase

### CODE REVIEW

**Review by Novacat — COMMENTED** [review]
Why are the sprite files in computer_vr.dmi when it seems like the base computer object is still pulling from computer.dmi?

**Comment by klaasjared** [comment]
> Why are the sprite files in computer_vr.dmi when it seems like the base computer object is still pulling from computer.dmi?

I... I'mma be real with you, I'm not smart

**Comment by klaasjared** [comment]
> Why are the sprite files in computer_vr.dmi when it seems like the base computer object is still pulling from computer.dmi?

Because I am not a very smart person - fixed it thought

**Comment by Iroquois-Pliskin** [comment]
Aside from looking a little out of place in the art direction (if you can even say we have one) these seem pretty good.

**Comment by klaasjared** [comment]
> Aside from looking a little out of place in the art direction (if you can even say we have one) these seem pretty good.

I tried to make it match the art style as best I could - going as far as to rip a sprite from another .dmi and making it rotatable for the sake of looking decent - but I admit it's not perfect

**Review by Novacat — CHANGES_REQUESTED** [review]
Honestly? I would recommend just mirroring the Polaris PR down here, then re-opening the Polaris PR. That would make it much easier to deal with future code conflict, and, I would be happy to earlymerge it here.

**Pull request closed without merging**
