### PR TITLE
Port some power sprites from Bay

### PR DESCRIPTION
**Pull request by Arokha**
Mostly just more perspective changes, everything looks basically the same, except:
- Cable objects (like the pick-uppable ones, not the ones on the ground) have more than 4 pixels and you can click on them now, wows.
- TEGs have a beefier industrial looking sprite and have various animated overlays for the fans spinning and hot and cold and stuff.

dreamseeker_2020-04-12_17-36-21

Also stole the icon for Bay's potato reactor, but haven't implemented it anywhere yet.

### CODE REVIEW

**Comment by Cyantime** [comment]
These SMES sprites are a whole lot stubbier and just generally look wrong
the bay TEG also looks weird and unfitting imo

**Comment by Heroman3003** [comment]
I really don't like new grid checker sprite. Seems like yet another making of an object with shape into undiscernable rectangle.

**Comment by Arokha** [comment]
> Seems like yet another making of an object with shape into undiscernable rectangle.

Uhhhh. As if the grid checker had some sort of meaningful information conveyed by it's previous shape? It was a dev sprite recolor of the breakers.

**Comment by Cyantime** [comment]
This changes the breakers too into generic 3/4ths bricks. What's worse is that the new display and lights on them are on the top side, where no one would be able to see them.

**Comment by Arokha** [comment]
You have a point about the display being on the top! But I would not say that's "worse" than having no display or indicators at all besides the color of those 'coils' or whatever they are, like the previous ones did. The previous ones were a bit shit.

You (or anyone) is always welcome to rework them to have a display on the front to fix the issue you mentioned.

**Pull request merged**
