### PR TITLE
Ports Solarmoths!

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
Does what it says, upstream port of https://github.com/CHOMPStation2/CHOMPStation2/pull/191

Feel free to bonk me for the commenting. :p

Solarmoths are very deadly critters, and if a solargrub feasts on enough power, it'll mutate into a moth, which can either light the room on fire or freeze it.

### CODE REVIEW

**Comment by Heroman3003** [comment]
Solargrub but actually not announced by second announcement, turning the area into unlivable hellhole. Please no. Just no. If we want grubs to advance, make it more into being aggressive dangermob or even bigger bitch on how it affects powernet, don't have them fuck with atmos too. This is just awful.

Also it looks nothing like the grubs themselves OR the supposed solargrub broodmothers or whatever.

**Comment by Rykka-Stormheart** [comment]
> Solargrub but actually not announced by second announcement, turning the area into unlivable hellhole. Please no. Just no. If we want grubs to advance, make it more into being aggressive dangermob or even bigger bitch on how it affects powernet, don't have them fuck with atmos too. This is just awful.
> 
> Also it looks nothing like the grubs themselves OR the supposed solargrub broodmothers or whatever.

Could probably put out an alert over comms, something like "Warning: Temperature Spike!"

Regarding the sprite, I can't really say on that, I'm not the one who did the original sprite. I'd personally advocate for a different color entirely.

**Comment by Rykka-Stormheart** [comment]
Closing and reopening because Travis is big dumb.

**Comment by Screemonster** [comment]
While I like the idea of being able to construct a mob engine, I dunno.

**Comment by SpadesNeil** [comment]
While I like the idea of solar moths, this was not how I envisioned them functioning. Fires are very unpleasant to deal with.

I preferred the vision of solar moths where they try to get to space by bonking through windows.

**Comment by Screemonster** [comment]
having them specifically latch on to lights and bonk against them until they break before moving to the next nearest light sounds hilarious

then have them eat any unanchored light sources

or people carrying unanchored light sources

or in the case of prometheans, people that _are_ unanchored light sources

**Comment by Rykka-Stormheart** [comment]
> having them specifically latch on to lights and bonk against them until they break before moving to the next nearest light sounds hilarious
> 
> then have them eat any unanchored light sources
> 
> or people carrying unanchored light sources
> 
> or in the case of prometheans, people that _are_ unanchored light sources

...I didn't realize how much I wanted this until now.

**Comment by TheFurryFeline** [comment]
Here's a thought. Have them be a POI mob and only grow if there's someone nearby and attack with burning blitz. :eyes:

**Comment by SpadesNeil** [comment]
We do want solar moths, but this rendition of them is not desirable in our server. We want a fun nuisance, not something that destroys the station if it's ignored slightly too long.

Solar moths that we _do_ want are overdue. Scree reminded me of the way we do want them to function. The reason solar moths are overdue is that, if implemented properly, they change solar grub events in such a way that the solar grub problem eventually goes away on its own even if everyone ignores it. They just deal with blackouts for a bit, then power comes back.

**Comment by Heroman3003** [comment]
To note, the solargrubs from the very beginning have a way to 'end' them by just announcing the list of places where living solargrub remain but that was mechanically nonfunctional until recently.

**Comment by Ketrai** [comment]
All I'm hearing is that ya'll are down for moths, but want an already entirely functioning block of code to be completely rewritten for solar moths to become inert, light smashing dinguses. I instead suggest just changing the values around? Make it take like, an hour or mroe for grubs to grow into moths. And then lessen the effect of moths. So a moth outbreak can pnly happen rarely since solargrubs aren't ignored most of the time. Otherwise? Download the branch and rewrite the code yourself ._. Like seriously. People make festures and port them for fun, not to work overtime.

**Comment by SpadesNeil** [comment]
I sincerely don't think Engineering will like us if we make moths this destructive. The amount of work in this is appreciated but ultimately goes against what a lot of people seem to want in the server.

Correct me if I am wrong.

Effort alone does not get a PR merged. Sometimes you put a lot of work into something and get disappointed. It's just an unpleasant fact of open source work. I had a major gun overhaul rejected by Polaris once. Took me like nine hours to do it.

**Comment by SpadesNeil** [comment]
This should be closed with the reason "Unwanted."

We want moths. We don't want yet more things on fire.

**Comment by TheFurryFeline** [comment]
As I said earlier, this could either be a poi mob or admin spawn only

On Feb 11, 2020 18:55, "Spades" <notifications@github.com> wrote:

This should be closed with the reason "Unwanted."

We want moths. We don't want yet more things on fire.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/VOREStation/VOREStation/pull/6509?email_source=notifications&email_token=AJGMTY7TFAVZWVKSNIW4UPTRCM3IZA5CNFSM4KL6B3E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELOUCMY#issuecomment-584925491>,
or unsubscribe

**Comment by SpadesNeil** [comment]
Even as a POI spawn I don't see this as being fun.

**Comment by TheFurryFeline** [comment]
Just had the idea of having a poor Solarmoth locked behind an array of inflatables but ashed collections of bones and remains of people that tried to defeat the burning moth of death... Just as a POI idea. :eyes:

**Comment by SpadesNeil** [comment]
Considering the latest feedback about explorers, adding yet another violent POI sounds like a bad idea.

**Comment by TheFurryFeline** [comment]
Rip, then. That  idea's all I got to have them be a thing in a round that
isn't part of a random event of grub infestation

**Comment by SpadesNeil** [comment]
@Novacat Should we close or do you have more comments?

**Comment by Novacat** [comment]
tbh this would probably be fine as an adminspawn mob, but yeah with the way atmos works and interacts this would be absolute nightmare to deal with even with voidsuits.

**Comment by Very-Soft** [comment]
If I might make a suggestion: make a variant of solar grubs that can evolve,, and make those be admin spawn only or something. Having more destructive solar grubs for events sounds great. But not for normal station times.

**Comment by SpadesNeil** [comment]
I don't want to add it at all because it sets a precedent that this will get added eventually in its current state or that it will forever be trapped in admin spawn only limbo.

I don't want that false impression. I want solar moths that behave entirely differently from these griefy ones.

**Comment by Screemonster** [comment]
I want them to grow into things that eat people that are carrying light sources, rather than setting the station on fire

while a solarmoth engine using these guys sounds like an interesting project, on the majority of shifts having a random room heat up to a bazillion degrees and ambush the next poor sod to open the door doesn't sound fun

**Comment by SpadesNeil** [comment]
And yes, I know this could be an admin spawn mob.

I don't want it _at all_ if its only purpose is to set things on fire.

**Comment by TheFurryFeline** [comment]
> And yes, I know this could be an admin spawn mob.
> 
> I don't want it _at all_ if its only purpose is to set things on fire.

It doesn't set things on fire, just heats a room up.

**Comment by SpadesNeil** [comment]
> It doesn't set things on fire, just heats a room up.

I don't want that either.

**Pull request closed without merging**
