### PR TITLE
Adds in a modified Replicator Transformation Device

### PR DESCRIPTION
**Pull request by Cameron653**
DESCRIPTION UPDATED:

Creates a two heavily modified versions of the Replicator that xenoarcheology can find. This is a uncommon/rare item.
Notes:
- Prey must have spontaneous-tf turned on.
- Prey will be given TWO popups (Warning 1: https://i.imgur.com/HuCsCEx.png Warning 2: https://i.imgur.com/kVMBpBu.png) if they REALLY wish to be shoved into this item. This guarantees there can be no possibility of someone being prefbroken and then going "I didn't know."
- After being shoved in the replicator, the mob drops all their items (https://i.imgur.com/k8GL2kx.png)
- When the replicator is activated and turns the person into an item/mob, anything they have inside their stomachs is either ejected(with item replicator) or their stomachs are added to the mob and the prey is kept inside (with vore replicator)
- The item has a name tag that it is made of XYZ (if item) or that it is XYZ (if mob.) Description also notes that it is made of them (if item).
- When someone picks up a possessed object (Or someone TF'd into an item) it will give them a **very** clear notification that the item they just grabbed is a person and to act accordingly. (https://i.imgur.com/DlraBPQ.png)
- If someone if TF'd into an object, they are unable to use the /me command. They can only say & subtle. This removes the potential issue of someone accidentally stumbling onto someone's inanimate object TF scene and getting hit with a /me.
- There are two ways of reverting the TF. Either using OOC-escape or using the medical mouseray. (https://imgur.com/VrCtnza)

- The item's undigestable&eatable variables vary depending on the character that was TF'd into said object. Once again, this ensures no accidental prefbreaks occur.

This has been meticulously coded to ensure no possible prefbreaks can occur, as I was informed by a headmin that this PR is fine as long as prefbreaks can't occur. The inability of being able to /me and the warnings at every avenue accomplish this.

### First Type: Vore Replicator
This item allows you to shove people with aligning preferences into the machine.
- Person is shoved in and, 10-15 seconds later, comes out as a various simple_mob. Mobs are mostly passive mobs but there are a few hostile ones inside of there (ex: direwolf) to discourage spam.

### Second Type: Item Replicator
This item allows you to shove people with aligning preferences into the machine and turn them into various items.
- Person is shoved in and comes out as an item, simply put.

### CODE REVIEW

**Comment by lm40** [comment]
Proc is fine, I don't want the replicator tho since staff already agreed we don't want inanimate TF mechanics.

**Comment by Cameron653** [comment]
Oh, I didn't even know we had a ruling on that.

Should I just scrap it entirely & just leave the proc or just leave the file out of the .dme?

**Comment by Heroman3003** [comment]
I'd suggest maybe keeping it in code, but not accessible without admin intervention

**Comment by killer3905** [comment]
> Proc is fine, I don't want the replicator tho since staff already agreed we don't want inanimate TF mechanics.

Why tho

**Comment by Cameron653** [comment]
> I'd suggest maybe keeping it in code, but not accessible without admin intervention

Could very easily do that, given the only way of obtaining it would have been accessible is via xenoarcheology, which would have made it a uncommon/rare thing to find in the first place. 

If I re-enable the file in the .dme it'll make it adminspawn only by virtue of being unobtainable.

**Comment by lm40** [comment]
My personal opinion is to leave the file out entirely tho I don't pretend to be speaking with staff consensus or anything when I say that it's just my personal opinion.

**Comment by Cameron653** [comment]
After a bit more thinking, I do realize how it could be a problem with preferences, since if someone goes strolling around with XYZ talking boots, that will obviously cause problems with people that don't like that sort of thing. (At the moment, the current, on-server replicator can be used to make micros into items, albeit very finicky and only just names the item after them.)

So, I came up with a few solutions to make it vore oriented so the project isn't a complete waste of time.

## Solution 1: Make the replicator more vore-oriented by turning people into food items. 
Having gone back through admin chat though, I see this was noted as potentially a preferences nightmare (Chef somehow gets a hold of the xenoarch artifact and puts down a micro-person food on the table is the immediate thought that comes to mind.) So, this solution seems less-than-idea.
### This potential solution is more or less dead in the water due to the same reason that preferences could easily be stepped on.

## Solution 2: Make the replicator transform people/items put into it into various vore creatures.
This solution aligns more with the server's preferences. This would entirely mitigate the potential preferences nightmare that would be caused by turning people into clothes/food.
This would give the players which wish to be vore mobs the ability to do so outside of staff intervention, something which is requested relatively frequently. 
### This solution is the preferred method.

**Comment by Screemonster** [comment]
personally if it's a xenoarch thing I don't really care if people use it to turn each other into or trap people inside things

like, inanimate TF could be a problem for the theme if it's a thing that's happening all the time or shows up in trash piles but I don't really see how a xenoarch find doing something weird is a problem if it's just a weird device that shows up occasionally and needs someone to dig it out and identify it. I'd actually lean _against_ it being "a thing that admins spawn on request" because that'll just encourage people to ask for it all the time and result in it becoming _way_ more common than something that's, say, ultra-rare trashpile loot or xenoarch RNG spawn.

as long as there's _some means_ to get the person back out again 'cause that's the main thing that I can see causing problems.

the _main_ preference issue brought up when we were discussing clothing-tf things was the worry that you'd get into a scene with someone not knowing that their jumpsuit is another crewmember (and thereby unknowingly get dragged into a tf scene as a bystander when you're not into it) - in this case, the fact that it explicitly renames the item to be the name of the person in question rather than being sneaky about it helps. If they're not visible on the description then it's not _that_ wildly different to getting into a scene with a micro in your bag or whatever.

**Comment by Cameron653** [comment]
Going to keep working on this being a clothing related TF machine.
Making it so the machine checks the micro's prefs before they're shoved in.
Going to make it so the item respect prefs (digestable? eatable?)
Making it obvious to anybody that picks up the item that it is, in fact, _a person_ so no potential preference issues occur.

**Comment by Cameron653** [comment]
Changing this to a draft due to the complexity of this machine and how much more work is needed to be done on this. 
I'm already 11 hours into this project and it's looking like it's going to need even more to get all the various mechanics in the game to play nicely with each other to respect preferences and ensure there can be no complaints with the machine.

**Comment by Cameron653** [comment]
Update:
Re-enables the replicator.
Alerts people when they pick up an item that is is a possessed item. Impossible to ignore popup. Like, literally impossible to ignore, it shoves it in the middle of your screen screaming "WARNING"

Makes it so people TF'd into items can revert back to their normal, pre-TF form.

Makes OOC escape functional (An in-game obtainable escape is still needed to be coded in. That's next on the todo list.)

Gives FAIR WARNING to the person being shoved into the replicator that, hey, you're going to be turned into clothing/an item and possibly used as such. Gives them a second warning as well.

Makes the item's eatable&digestable variables adjust depending on the person's variables before TF'd.

Makes it so the 'voice mob' is properly deleted when digested.

Fixed a bug with the replicator allowing you to put grabs in it. (This will be edited to allow for stuffing people proper in it.)

Added framework for the vore simple mob replicator.

**Comment by Cameron653** [comment]
Clothing replicator is now 100% done after almost 30 hours of coding&testing.
Currently working on the simple_mob vore replicator version now.

**Comment by Cameron653** [comment]
As an aside: I tested everything involved (which is why I found so many bugs the original artifact had and had to correct them) and coded out any potential avenues for abuse that I could find.

As this was given the greenlight as long as it didn't have prefbreaking potential, I went ahead and dedicated stupid amounts of time into this, checking and double checking everything to make sure there was _no_ ambiguity when dealing with player controlled items.

With that being said, this is ready for merge. 
Just need a few eyes to look over it and make sure there's no glaring oversights I missed (Like almost making it so you could put vore blacklisted items into the replicator, something which you currently can do with the base one.)

**Comment by Heroman3003** [comment]
For compatibility issues, I recommend just updating from master, ignoring conflicts in tgui compiled file and re-compiling tgui

**Comment by Cameron653** [comment]
I hate tgui

**Comment by Cameron653** [comment]
what does it mean merge conflict
I literally synced with master and then recomplied the tgui

**Comment by Cameron653** [comment]
Going to do what redcat suggested and update, ignore the conflict, then make another pr recompiling the tgui.

**Pull request merged**
