### PR TITLE
Adds carafes and pitchers

### PR DESCRIPTION
**Pull request by Arokha**
Also adds them to the bartender vendor.

dreamseeker_2020-02-20_22-14-57

### CODE REVIEW

**Comment by Heroman3003** [comment]
Could also use those in autolathe too, maybe?

**Comment by TheFurryFeline** [comment]
`K$ awk -f tools/indentation.awk **/*.dm
code/game/machinery/vending.dm : 					/obj/item/weapon/reagent_containers/food/drinks/glass2/pitcher = 2, //VOREStation Add
code/game/machinery/vending.dm : 					/obj/item/weapon/reagent_containers/food/drinks/metaglass = 10,
The command "awk -f tools/indentation.awk **/*.dm" exited with 1.`
Forgot your commas at the end of each line, even if it's a comment there.

**Comment by Arokha** [comment]
> Forgot your commas at the end of each line, even if it's a comment there.

Someone should just fix that awk instead.

**Comment by Ketrai** [comment]
Looks nice.

**Pull request merged**
