### PR TITLE
Fixes syringes cutting apples

### LINKED ISSUE #1779: syringes slicing apples
#### Brief description of the issue
when you interact a syringe with an apple (either on draw or inject) it will 'slice the apple but when you interact with the slice it says "None of the apple slice left!" unless you inject a reagent inside, then you can bite it normally until the reagent is gone

#### What you expected to happen
to be able to inject something into the apple and not to create face apple slices

#### What actually happened
i got fake apple slices that are basically little containers

#### Steps to reproduce
- (Step 1) optain apple and syringe
- (Step 2) click syringe onto apple
- (Step 3) try to eat apples and then find them to dissapear into nothingness

#### Code Revision
256e1db4d6e43368e3e53cf3027e5ae395abdacd 

#### Anything else you may wish to add:
- i would suspect the same thing happens to any slicable fruit but i was trying it with apples

### PR DESCRIPTION
**Pull request by lbnesquik**
This makes syringes not sharp. I was able to take a blood sample from someone and put it within a beaker with those settings.
Fixes #1779

### CODE REVIEW

**Comment by lbnesquik** [comment]
https://github.com/VOREStation/VOREStation/issues/3828

**Comment by Mewchild** [comment]
Fixes https://github.com/VOREStation/VOREStation/issues/1779, not #3828

**Comment by lbnesquik** [comment]
Thanks for the correction.

**Comment by Mewchild** [comment]
Make sure you add "Fixes [ISSUE]" To your original post, so it closes the issue when this is merged

**Pull request closed without merging**
