### PR TITLE
7/22/2021 Food Revamp

### PR DESCRIPTION
**Pull request by GhostActual**
Polishes, adds, and changes some sprites for food and snacks alike that were a bit outdated and needed updating. Some organizational changes were also added to the code and sprite files for better reference and a top_bun and bottom_bun was added to the food.dmi file for any future burger additions.

Below are some examples of the sprites that were changed/added.

Onion Rings:
125751768-70b422c2-ba9c-4737-aa7b-c336475c8737

Cuban Carp:
125751784-e179b4b1-ef2f-4917-b59f-0b6fd5bf2e7b

Old Pizza, Crunchy Pizza, and Cheesy Bacon Flatbread:
125751809-e0684162-205a-46c3-b187-afdf7564f270

New Condiment Sprites:
126318827-b3082c87-be4d-4b8f-9633-c17aec38c6ac

New BBQ Chip design and Salt & Vinegar Chips:
125751918-3560841a-26b3-4761-959c-54675af06f16

Baked Beans Can:
125752800-3e7acc65-2c83-43a4-bfa4-248a7d5462b5

New Burritos:
showcase

New Spacer Cake Sprites (nothing major, just adds cake_out_of_package sprite):
126317129-46aff212-c4d9-41d4-a3d5-477abed32f60

New Packaged Vendor Food:
126397538-58d592fa-cf6b-4f0b-a4c4-cd3f4be033ab

Carnival Food Update (Corndog, Candy Apple, and Caramel Apple):
show3

New Cooked Crab Sprite:
show2

New Tacos:
show1

New Hotdogs:
126317152-ad7c0183-ce80-4d0a-a916-75412ff61b04

New Cooked Bacon:
125751836-e1c3de8d-3015-41c9-8b63-43f7731752fe

New Honey bread and Honeycomb:
Sprite-0001

New Grub Meat:
Sprite-0002

Misc Stuff:
-New Vinegar reagent added with condiment bottles
-New Mustard reagent added with condiment bottles
-Makes all plate/bowl sprites symmetrical for consistency
-Adds new `small_bowl` trash sprite for Wing Fang Chu (can be used for future soups in small bowls)
-Adds new `asian_bowl` trash sprite for Asian dishes in `food_vr.dm`
-Adds new `stew` sprite that is more symmetrical and straight
-Multiple sprite changes to make artstyle at least somewhat consistent
-Changes `ovenchips` and `microchips` into `ovenfries` and `microfries`
-Changes worm can sprites slightly to round them out and make them look similar to other cans

Final Note:
I have spent more than 12 hours consistently on this so there may be a few errors that slipped past, please feel free to make these errors known so I may fix them. Thank you in advance.

### CODE REVIEW

**Comment by Very-Soft** [comment]
I might have missed it somewhere, but it looks like you deleted the saltshaker sprite. Not sure if it got put elsewhere or if it's maybe using a different sprite now! But! Thought I should point it out.

image

**Comment by GhostActual** [comment]
> I might have missed it somewhere, but it looks like you deleted the saltshaker sprite. Not sure if it got put elsewhere or if it's maybe using a different sprite now! But! Thought I should point it out.
> 
> image

Aronai said that that specific sprite was never used so I removed it entirely. The existing saltshaker sprite is actually `saltshakersmall`

**Comment by Arokha** [comment]
Looks like you created+committed a blank file named `code/game/objects/random/computer_shims.dm`

**Comment by Arokha** [comment]
Looks like you committed a merge conflict as well:
image

**Comment by Ketrai** [comment]
I appreciate you taking to heart my request not to replace the lobster and sushi sprites. Sorry if I came off strong in dev-general. 

Otherwise this generally looks good. 

- notable sprites I believe are a major improvement.
- grub meat. Looks a lot shinier, I like it a lot.
- tacos. The previous one really didn't make much sense.
- cuban carp. The old one was very small and hard to read.

Otherwise I'm not a fan of the excessive usage of noise in some places, like crunchy pizza. For example, Hotdog also uses noise but it's way smoother and less noticeable there. Beans are an improvement but I advocate you use a brighter vertical hilight somewhere to make the cylindrical shape pop, like it has more depth. Chips could too. (I think the other chips sprites we have actually already used hilights and shading to achieve a more bag like depth.) But it doesn't stand out as much as the bean can.

**Comment by Ketrai** [comment]
Ah. Old chips also look flat. Look at MRE's then if you want to. They have that delicious baggy shape and nifty hilights.

**Comment by Arokha** [comment]
/obj/item/weapon/reagent_containers/food/snacks/burrito_hell does not have a valid icon state, icon=icons/obj/food.dmi, icon_state="hellfireburritoburrito"
/obj/item/weapon/reagent_containers/food/snacks/mouseburger does not have a valid icon state, icon=icons/obj/food_syn.dmi, icon_state="ratburger"
/obj/item/weapon/reagent_containers/food/snacks/breakfast_wrap does not have a valid icon state, icon=icons/obj/food_syn.dmi, icon_state="breakfastwrap"
/obj/item/weapon/reagent_containers/food/snacks/bearburger does not have a valid icon state, icon=icons/obj/food_syn.dmi, icon_state="bearburger"
/obj/item/weapon/reagent_containers/food/snacks/friedrice does not have a valid icon state, icon=icons/obj/food_syn.dmi, icon_state="friedrice"
/obj/item/weapon/reagent_containers/food/snacks/bibimbap does not have a valid icon state, icon=icons/obj/food_syn.dmi, icon_state="bibimbap"
/obj/item/weapon/reagent_containers/food/snacks/burger/bacon does not have a valid icon state, icon=icons/obj/food_syn.dmi, icon_state="baconburger"

**Comment by GhostActual** [comment]
After reviewing the code I have decided to convert this to a draft. I've discovered yet more sprites that require updates as well as code that is in need of organization.

**Comment by Ketrai** [comment]
I'm seeing three different actions here. Revamping sprites, adjusting centering. And adding large amounts of new food as well. I'd suggest you split this one into several prs, but given you're messing with icon files that's not that viable. Could you please document the changes and your reasoning?

**Review by Arokha — APPROVED** [review]

**Pull request merged**
