### PR TITLE
Moves Anomaly Lab to research outpost, replaces with Chemistry set

### LINKED ISSUE #4127: [SUGGESTION] Xenoarch safety adjustments
#### Brief description of the suggestion
Remove spawning of xenoarch spots on station levels

#### What is reason for it to change
Xenoarcheologists digging around station with no regard for safety can cause phoron flooding, depressurizations, radiation waves and generally artifacts affecting people. Not speaking how some people find picksets in maints and try to excavate using those.

#### How will things work after the change
Perhaps increase spawns of artifacts elsewhere, but no more in z1 through z7.

#### Brief description of the suggestion
Move anomalies and xenoarch to the outpost

#### What is reason for it to change
Artifacts sometimes have disasterous effects and are generally very dangerous. Them being worked with and contained away from the main station makes all the sense, and has less chance to directly affect people on the station, especially since anomalists and xenoarcheologists never bother with proper safety and leave them on without knowing for sure what they do, leave them uncontained, etc.

#### How will things work after the change
Expanded outpost with Anomaly Lab and Xenoarch Storage. Freed up space in station research can be used for general purpose lab.

### LINKED ISSUE #4413: The research outpost is not interesting.
#### Brief description of the issue
The research outpost lacks rooms to be interesting as a RP area. It's just a work area, which is fair and reasonable from nanotrasen standpoint but it's also really not a tempting place to go as a player. 
It's just a confusing mess of pipes, firelocks and burn chambers. It could be made more interesting if it held xenobio (and if xenobio was made fun too) along with some areas where you can 'rest' and 'take a break from exhausting dangerous work'.

### PR DESCRIPTION
**Pull request by Heroman3003**
What it says on the tin. More detailed list of changes:

- Anomaly lab moved to outpost.

- Stationside xenoarcheology storage now has twice as less excavation suits, but gets two sets of winter clothes

- Stationside xenoarch now gets oxygen canister, but one less field generator

- Added a small storage space outside outpost. Has a single anomaly container

- Additional xenoarch storage to the outpost, has second half of excavation suits, two field generators, two excavation lockers, two sets of digging supplies and two containments for anomalies

- Anomaly lab now has a longterm anomaly storage

- Anomaly lab now has two separate containment cells, one for scanning artifact and one for experimenting with activation. Experimentation cell is more secure.

- Anomaly lab gets a chemistry set for producing alternative coolants and reagents for artifact activation

- Increased outpost gas storage canister amoung by 1 per canister type (all moved from old anomaly lab) except nitrogen which gets 2 more

- Added a cyborg recharger to the outpost hallways

- Added 2 boxes of inflatables to outpost EVA

- Place where anomaly lab was before replaced with small chemistry lab. Has a single set of chemistry equipment and some grenade-making supplies

- Moved reagent analyzer for explorers from the xenoflora to research chemistry

- Xenoflora chem dispenser will now only dispense chemicals related to botany

- Added an important note to firing range, regarding testing explosives there

EDIT1: Screenshots due to mapdiffbot's failures:
https://prnt.sc/n76pos
https://prnt.sc/n76pjt

EDIT2: Fixes #4413 
Fixes #4127 (only part 2, but part 1 exists as a separate issue already)

EDIT3: On staff request, includes radiation shielding to maintenance and bluespace+radiation shielding to  dorms.

### CODE REVIEW

**Comment by Draycu** [comment]
Thank you so much for taking the time to map a good looking area for Xenoarch that's separate from the main station!  It was a long overdue change!

**Comment by TheFurryFeline** [comment]
I approve of this, really, since xenoarch is prone to being involved in accidents **and** Phoron fires that engineering has to deal with. 👍

**Comment by JoanRisu** [comment]
After an incident that happened earlier today, I would like this or at least the discussion of moving the anomaly lab to be considered. A radiation-wide anomaly killed 5 people, 3 of whom were scening.

**Comment by Novacat** [comment]
The only change I would like is for this PR to also add blue shielding and rad shielding to the eight main dorm/holodorm areas, and rad shielding to the maint dorms (but not blue shielding)

**Comment by Heroman3003** [comment]
That seems like something that should be done not in this PR, but just in general, regardless of whether lab is moved or not. I will look into it, but I do not see why that specific feature needs to be bundled with lab's move, considering its also much more essential.

**Comment by Heroman3003** [comment]
Alright. All maintenance and construction areas (And also that little maint storage research has and panic shelter) are not properly rad-shielded, while dorms, holo and non-holo, are both rad and blue shielded.

**Comment by Haery70** [comment]
At first, I was going to point something out regarding some of the changes. But, it seems that after careful reading and looking at the map files that the main issues was already addressed beforehand. The only concern that I have is the lack of proper gear to actually go out into a phoron-rich atmosphere to get to the outpost unless if the issues regarding wearing clothes that protect you from phoron have already been addressed beforehand.

With that being said, the only reason on why the lab would be close to the station is to start drama. But, as we all know, the drama induced by artifacts has led to some very unfavorable and salty results half the time. The isolation of the lab has worked in keeping dangerous artifacts off the station in the previous map, so I'm pretty sure that it'll work in this change.

**Comment by Heroman3003** [comment]
@Haery70 That is why only half of excavation suits have been moved to new outpost. Research still has xenoarch storage with two sets, and two sets that were moved were replaced with winter clothing sets.

**Pull request merged**
