### PR TITLE
Expands Science Workshop

### PR DESCRIPTION
**Pull request by Yoshax**
People complained it was too small.
Made this. People liked it:
Workshop

Workshop and Server Room swap places so the Workshop can be expanded. Has more space along with a locker, plant, disposals, charger and cell charger.

### CODE REVIEW

**Comment by Arokha** [comment]
You made sure the cooling and stuff works right in the server room right, cuz I'd hate for it to blow up like 20 minutes into the shift

**Comment by Yoshax** [comment]
I just copy-pasted it down. It's the exact same room, nothing changed.

**Comment by SpadesNeil** [comment]
_Should_ be okay.

**Comment by Arokha** [comment]
We will see if you have DOOMED US ALL.

**Pull request merged**
