### PR TITLE
Removes command secretary

### PR DESCRIPTION
**Pull request by Sebbe9123**
As title said, read something about command secretary basically just being free PTO, our station really has no mechanical nor roleplay reason for secretaries as we do not have anywhere near enough load to put anything on their plate.

### CODE REVIEW

**Comment by Heroman3003** [comment]
Same applies to jobs like librarian and chaplain and psychiatrist. Both are also jobs that have nothing to them but RP aspect and you can join, do absolutely nothing, never be asked to do anything, and come out on top. That doesn't mean all those jobs need to be removed. Secretary provides good RP opportunities and good potential for RP interaction and thats enough for it to exist.

**Comment by Sebbe9123** [comment]
> Same applies to jobs like librarian and chaplain and psychiatrist. Both are also jobs that have nothing to them but RP aspect and you can join, do absolutely nothing, never be asked to do anything, and come out on top. That doesn't mean all those jobs need to be removed. Secretary provides good RP opportunities and good potential for RP interaction and thats enough for it to exist.

Difference here is that those jobs you listed DO have things to them, they even have whole areas dedicated to them while command secretary doesn't.

**Comment by Screemonster** [comment]
lol wat

they actually have a job to do (run errands for the command staff) and tend to be _the_ people to send us faxes
while, yes, _theoretically_ assistants were supposed to be the subordinate-to-everyone errand-boy job, in practice they never did it and were never expected to.

**Comment by TheFurryFeline** [comment]
I vehemently am against this due to what Scree had said **AND** that people tend to take the slot to be able to RP with command access so they can scene without worry of having to need to do anything most of the time other than to do their job which rarely happens enough times to be a bother.

**Comment by Verkister** [comment]
Someone whose job is to send faxes for more staff sounds like one of the most important jobs on the station suffering from an absent/busy/useless crew.

**Comment by TheFurryFeline** [comment]
:V I know of some players who tend to play Command Secretary for mostly the
reasons I divulged. They'd also be very against this.

**Comment by Novacat** [comment]
I am personally against this, but I am going to leave it up for discussion for now.

**Comment by Wickedtemp** [comment]
From my experience, Command Secretaries, with the exception of like...maybe two of them, have always been kinda pointless. You don't really have a job. The Heads that care about paperwork tend to do it themselves and the ones that don't, don't care, and won't give a shit if you offer to handle it for them because they just don't care. Basically if you're wanting to play an actual Secretary, do HoP, because thats the only way you'll be able to really do anything.

It's just...a useless role. You can't really shadow anyone, it's difficult to get a handle on how Command functions with just access to comms and bridge, you aren't really ever needed for anything in actual gameplay despite theoretically being Commands Personal Assistant. Its a job for having scenes in the Heads Meeting Room and thats about it.

With that said, I don't think it should just be outright removed. Changed, potentially, to see if we can actually make something of it, but not removed. PTO isn't a big deal and I don't think anybody actually gives a shit, if you want PTO just join as a librarian and afk somewhere, nobody cares.

**Comment by Haery70** [comment]
I'm against the idea of outright removing this role, making it an Intern alt-title would be better than just removing it. The only issue that I see with Command Secretaries is that while their role generally involves filing faxes and doing paperwork for the Heads of Staff, they just feel like Visitors with access to the bridge most of the time since nobody asks them to do anything, which tends to make them lazy and not willing to do their job if their not already in a stomach which is common in RP-focused jobs and is something that we can't really do about it.

If you want these roles to be more than just a glorified Visitor you gotta give them something to do. Have them write a report, run your errands, fetch them your favorite beverage, have them bend down in front of you so that you can see their ass, and many, many more. And if they refuse to do their job? Try to lord over the crew? Well, you know how to deal with them in that case.

The point that I'm trying to make is that even with these flaws you're not going to remove the problems by simply removing the role outright. It's our responsibility to make sure that people are doing their jobs when asked (provided that they're not in a position that they can't get out of, that is.).

**Comment by MrSign** [comment]
I don't think this is a necessary removal to make. It allows people to customise how they play themselves as a secretary. Whether it be using it as an excuse to have 'private' rooms to scene in or to actually assist heads of staff in running the station.

**Comment by Heroman3003** [comment]
Being "Free PTO" job does not warrant removal, because there are other jobs counting as that. Lack of mechanics does not warrant removal, there are plenty of jobs with nothing but RP to them. No RP reason for them to be there? Thats a plain false. And if problem is that we're not too populated? Well, same thing applies, most 'useless' jobs could be curbed for that reason. But I do not see Polaris, who has MUCH lesser average population removing any jobs.

As a whole, this PR does nothing good, solves no problems and just screws over players who enjoyed the job, for casual RP and scenes both.

**Comment by Uwawa96** [comment]
Some input from a CS player here (Lise Evans) 
Just because the Majority of Command sec players do ussualy just use it to be a pretentious Off-duty worker , and most heads are unaware how to fully utelize their (hopefully) higely trained personal assistance does not make the job Useless

It is a RP job first ,and as such is realy open to whatever people can come up with 
Want to be a Sloppy prey,ish secretary who you use to Scene ? Go for it 
Be a Highely trained Secretary Send from NT space that just watches our Heads daily and internaly screams "what the fuck are those fools up to again?" , if thats how you want to role go for it 
Or even be the Personal Pet type , and spy on those lazy scientists for your beloved superiot , what people do with the job realy boils down to how they decide to RP it 

Now for what Command Secs can do Mechanicly , what they should do as a Bare Minumum and what they can do when fully utelized is a diffrent story , but you can trust me that having them around can only be helpfull to a shift , I had a good ammount of times where i assisted the crew with vital informations during all kind of emergencies , Hacker on the lose ?  Nobody expects the Command Nerd to check the Cameras , quick call to Head and Detective and BAMM Bridge time you go Greytide , 
Grub Invasion ? Man the Bridge and check Sensores and  Cameras to keep the crew on their toes !!!
I had countless times i accted as a medium between Crew and Crew or Crew and Head ...

Command Sec if fare from useless and can Even set Alert Levels or call a Emergency Shuttel when things go south and there is no Head on the station ... just because you never played the Job , do not interact with them or simply lack the Immagination to come up with fun and interesting gimicks to play a command secretary or the simple lack of knowlege of what a paper girl in command would do ,does not mean they are usless , fare from it even ... 

Its just a little role (with barrly any access) that some people Enjoy to play , if most people do not do a good job at it , so be it , but that does not make the role useless , plus its existance makes the workplace seem more realistic , do i have to remind you that this is a RP server ?
Watchign the Heads work without proper Paper Boiis would just feel very Unimersive to me ...

but hey this are just my 2cents 
Have a nice day

**Comment by Dhaeleena** [comment]
I agree with what scree said pretty much

**Comment by SpadesNeil** [comment]
I am one of the only people who dislikes command secretary, but the support for it existing is overwhelming, and what Scree said is true.

So no.

**Pull request closed without merging**
