### PR TITLE
Set a fake ID on shelter buttons to avoid messing with every door

### PR DESCRIPTION
**Pull request by Arokha**
Hopefully this is the issue.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
>This habit of using memes or pop culture references in code triggers me on a personal level and serves to do nothing but frustrate coders and admins who are trying to find something in the code but unfortunately aren't psychic and can't figure out what fucking path something exists under.

>I'm rejecting all future PRs that do this absurd thing with meme names.

>I used to have a coworker who would only name his variables in memes.

b87

no but seriously

**Comment by Arokha** [comment]
I can change it, but I think you missed what this is doing. It has to be something that's NEVER used. Whatever the string is,  it can't be used anywhere else.

**Comment by SpadesNeil** [comment]
Change it anyway.

**Comment by Arokha** [comment]
I did already, nerd

**Comment by Little-119** [comment]
...what happened in this PR?

**Pull request merged**
