### PR TITLE
Sharp melee fix

### PR DESCRIPTION
**Pull request by Cameron653**
- Fixes sharp melee trait
- Makes the monkey injector into /injector/fluff/monkey and the base into /injector/fluff

### CODE REVIEW

**Comment by Cameron653** [comment]
After travis passes this is ready to merge.

**Comment by Cameron653** [comment]
Err.. Wait, it apparantly wants to change something with the map even though I never touched the map file?

**Comment by SpadesNeil** [comment]
code/modules/mob/living/carbon/human/human.dm:1183:warning: species: unused label
code/modules/mob/living/carbon/human/human.dm:1183:warning: update_attack_types: unused label

**Comment by Cameron653** [comment]
WHOOPS. Forgot to put a () after it.
Fixed. It should compile w/o errors now.

**Comment by Cameron653** [comment]
Can we go ahead and merge this since it's a bugfix?

**Pull request merged**
