### PR TITLE
Verk's synthfluff stuff for possible easylazy approval.

### PR DESCRIPTION
**Pull request by Verkister**
Adds a new brand of synth limbs for Rahwoof.
Tested and working.

http://forum.vore-station.net/viewtopic.php?f=26&t=955
also related
http://forum.vore-station.net/viewtopic.php?f=26&t=957

### CODE REVIEW

**Comment by Arokha** [comment]
`icons/mob/human_face.dmi`

This .dmi cannot be changed. We don't change any stock DMI files. Please reset and recommit without this file. If you have questions about what files you CAN put things in, either ask here or refer to CONTRIBUTING.md

**Comment by Arokha** [comment]
Was this already approved elsewhere? Can you link whatever issue/thread discusses it? Even if it's not approved yet, handy to have here.

**Comment by Verkister** [comment]
Hasn't been approved yet. Just felt optimistic about it and decided to ease up the process a little bit.
http://forum.vore-station.net/viewtopic.php?f=26&t=955

**Comment by Verkister** [comment]
Oh yeah, just acquired a greentext as well. Same thread.

**Pull request merged**
