### PR TITLE
Adds a few more alt-titles to some jobs

### PR DESCRIPTION
**Pull request by Heroman3003**
More purely fluff alt-titles for the god of purely fluff alt-titles.

Command Secretary - Added Bridge Assistant
Quartermaster - Added Cargo Supervisor
Shaft Miner - Added Excavator
Chaplain - Added Priest, Nun, Monk
Atmospheric Technician - Added Atmospheric Engineer, Renamed Atmospherics Maintainer to Atmospheric Maintainer.
Pilot - Added Helmsman
Field Medic - Added Offsite Medic
Scientist - Added Researcher
Xenobotanist - Added Xenohydroponicist

### CODE REVIEW

**Comment by Wickedtemp** [comment]
add Chief Mlemical Officer pls

**Comment by Heroman3003** [comment]
> add Chief Mlemical Officer pls

Honestly, if someone were to go and had a fluff app for a personal alt-title for a job approved, I would add a system for whitelisted alt-titles.

**Comment by dwinters99** [comment]
My trepidation with the first PR was that some of the titles made little sense or were hard to tell what they actually were for. (see: surveyor). This trepidation still exists and still goes for this PR. Some of these, while descriptors of someone's job, don't actually feel like job titles. For example: Excavator is something (or someone) that excavates. But it's not a job title. An excavator is a piece of industrial machinery, not a person's title. This is true of anything ending in 'maintainer'. Maintainer is not a job (at least in my field of carpentry and residential engineering), but rather a modifier to a job. Such as an Equipment Maintainer Technician or Maintenance Technician. The only fields I can think of that have maintainer as a job of their own are computer science and the military, neither of which are present on our corporate gas-station. I have a few issues with the other PR as well but it's already been added, so it's not worth crying over spilled milk. 

All that being said, I do quite enjoy alternate job-titles, but some of them only make sense tangentially.

[/skub]

**Comment by Very-Soft** [comment]
Could we maybe have alt titles for pilot, relating to the different shuttles?

Like, Medical Pilot, Security Pilot, Expedition Pilot?

I wouldn't do one for the tourbus since it's more of a general shuttle! But, kind of give people the ability to show what they are interested in flying by their job.

**Comment by Heroman3003** [comment]
> 
> 
> Could we maybe have alt titles for pilot, relating to the different shuttles?
> 
> Like, Medical Pilot, Security Pilot, Expedition Pilot?
> 
> I wouldn't do one for the tourbus since it's more of a general shuttle! But, kind of give people the ability to show what they are interested in flying by their job.

I considered that, but I was worried about it going in direction opposite of what the pilot being moved to general civilian role intended. That and considering how way way less use Medical and Security shuttles have compared to exploration shuttle or even tourbus, that seems very disproportionate, since that kind of specialization is very direct and not really fluff.

**Comment by Very-Soft** [comment]
Those shuttles do get used very little, but I think the specialization would be cool. UWU

**Comment by BonniePandora** [comment]
If at all possible, an alt title of "Blast Miner" for the shaft miner role would be neat to see added to this list too, seeing as they have access to mining charges and can best utilise any explosive devices/mixes concocted by science.

**Pull request merged**
