### PR TITLE
Desc Change on Tracking Implant

### PR DESCRIPTION
**Pull request by Mewchild**
Changes the description on the tracking implant to better reflect what it does/what it's for

This is mainly to remove ambiguity from the loadout selection.

### CODE REVIEW

**Comment by Cyantime** [comment]
`//VOREStation Edit`, or send to Polaris

**Comment by Mewchild** [comment]
Completely forgot. My bad.

**Comment by Cameron653** [comment]
Yeah, this would be better sent to Polaris.

**Comment by Mewchild** [comment]
Will do, boss(es)

**Pull request closed without merging**
