### PR TITLE
TGUI Cargo

### PR DESCRIPTION
**Pull request by ShadowLarkens**
This converts the following UIs:
 - All non-overmap shuttle consoles (short jump, belter shuttle, etc)
 - Belter scanning console
 - Destination Tagger
 - GPSs have a real UI now
 - Mining Equipment Vendor
 - Mulebot
 - Notice Board
 - Ore Processing Console
 - Ore stacking console
 - Request Console (the things on the wall everywhere)
 - Supply Computer

# Screenshots
Asteroid Belt Scanner
Destination Tagger
GPS
Mining Equipment Vendor
MULEBot
Notice Board
Ore Processing Console
Request Console
Stacking Console
Supply Computer

All Shuttle Consoles
More shuttle consoles
Moreeeeeee

### CODE REVIEW

**Comment by ShadowLarkens** [comment]
dnm till I fix /obj/machinery/mineral/equipment_vendor/survey

**Comment by ShadowLarkens** [comment]
aight we groovin n--motherfuck

**Comment by ShadowLarkens** [comment]
*w e g r o o v i n n o w b i t c h*

**Comment by KasparoVy** [comment]
Fuck yeah! Hail Cargonia
Strike the earth!

**Pull request merged**
