### PR TITLE
Added some missing air alarms and firelocks around station

### PR DESCRIPTION
**Pull request by Heroman3003**
A leak happening here would be a disaster right now, wouldn't it?

### CODE REVIEW

**Comment by Screemonster** [comment]
it's on the space levels so a breach would be low pressure, which is far easier to deal with than most. Adding air alarms to sections that are lacking such is a good fix though.

**Comment by Heroman3003** [comment]
Tbh, those areas are pretty damn secure from breaches. The problem comes when a 'gas leak' random event pops up. And as a general thing, almost all airlocks should have shutters and almost all sealed areas should have air alarms.

**Comment by Screemonster** [comment]
the thing that makes leaks in maint a pain is the fact that maint has so many vertical shafts, so a gas leak can easily spread across multiple floors and in some cases bypass firelocks. Luckily gas leaks there are fairly rare.

**Comment by Heroman3003** [comment]
If anyone knows any other places where there should be air alarm/firelock but isn't, feel free to comment.

**Comment by Heroman3003** [comment]
Closed as of #4606 conflicting.

**Pull request closed without merging**
