### PR TITLE
Adds more fun say lines to wolfgirl, also removes old redundant code.

### PR DESCRIPTION
**Pull request by Sebbe9123**
see title.

### CODE REVIEW

**Comment by Sebbe9123** [comment]
My code > Travis

**Comment by Sebbe9123** [comment]
This PR passes Travis Verk, just merge it ffs.

**Comment by Jwguy** [comment]
Hey, what's the status on this? This has been bugged with a double Travis Build for quite some time.

I ask because I'm also lining up to make some changes to the same file.

**Comment by Sebbe9123** [comment]
> Hey, what's the status on this? This has been bugged with a double Travis Build for quite some time.
> 
> I ask because I'm also lining up to make some changes to the same file.

Waiting on merge, seems like all the maintainers are on break.

**Pull request merged**
