### PR TITLE
Switches smartfridges around in hydroponics

### PR DESCRIPTION
**Pull request by Huenererschrecker**
- Deletes the extra smartfridge in the hydroponics backroom that noone ever uses.
- Changes the smartfridge between hydroponics and the kitchen into a produce persistent one (previously used exclusively in the never used backroom fridge)
(I hope I did this right and haven't broken something)

### CODE REVIEW

**Comment by Arokha** [comment]
Update your copy of the repo before making map changes

**Comment by Huenererschrecker** [comment]
I have no idea what this means or how to do that. I just want to move a stupid fridge from point a to point b and I'm struggling at this for 2 days now

**Comment by Arokha** [comment]
Read the readme.md on the front page of the repo. Use a git client to clone your fork of the repo. Ask for help in #dev-general in the Discord if you have followup questions.

**Comment by GhostActual** [comment]
fixing this before bed

**Comment by Huenererschrecker** [comment]
Alright, the moment I got time to work on this again and it was fixed by someone else. Guess this is closed then.

**Pull request closed without merging**
