### PR TITLE
Added colorizable "tumby" vore overlays

### PR DESCRIPTION
**Pull request by Chlorotrifluoride**
added a grayscale 'a_tumby', 'another_tumby' and 'da_tumby' to screen_full_colorized_vore.dmi 
also gave 'a_tumby' and 'another_tumby' a vignette like with 'da_tumby' because it looks good.

### CODE REVIEW

**Comment by Heroman3003** [comment]
The author of all these overlays has made it expressly clear that they do not want to see them colorized because it ruins important parts of visual style (the white shines on various spots).

**Comment by Chlorotrifluoride** [comment]
I didn't know that. how about just adding the vignettes?

**Comment by Heroman3003** [comment]
Wdym by vignettes?

**Comment by Heroman3003** [comment]
Idk, I'd suggest actually asking original artist before doing changes to it. As for now I dont feel comfortable accepting it.

For the color selector, I'd say first implement a feature to make such colorability possible before changing existing ones.

**Comment by Chlorotrifluoride** [comment]
Do you know where can I find out who authored those images? I couldn't find anything in ATTRIBUTIONS.MD

**Comment by Heroman3003** [comment]
They're on our discord. Ask for Soft.

**Pull request closed without merging**
