### PR TITLE
More sprites for Silicons!

### PR DESCRIPTION
**Pull request by Very-Soft**
Adds
roombas

ZOOM-BA sprites for normal borgs

borgis

Borgi sprites for dogborgs (Sprite by Verki, I just did the color edits~)

a new sprite for pAIs

### CODE REVIEW

**Comment by KasparoVy** [comment]
Holy shit the borgi sprites are so cute.

**Comment by LSommers** [comment]
Is is possible to attach anti-personnel mines to the top of the roomba borgs?

**Comment by KasparoVy** [comment]
Or pilons/wet floor signs haha.

It'd be funny if you could stand on them - they are a flat platform

**Comment by Very-Soft** [comment]
That's take coding I don't know how to do! If one of you can manage it I'd say go for it!

**Comment by ArgobargSoup** [comment]
Hmm.  Don't dogborgs have riding code?  Or did they not get it?  It's been a while... but yah, you could possibly adapt that for the roomba borgs  \:P

**Comment by Very-Soft** [comment]
They do have it, but it would require making that work only for this particular borg skin thing. 

I don't really know or understand the code, I can just perform simple modifications. The roombas are just regular borgs, they aren't a new kind.

**Pull request merged**
