### PR TITLE
[MIRROR] Fixed showers not appearing to turn off [READY FOR MERGE]

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/8729
--------------------
cut overlay is for a specific overlay, not all overlays you silly me. (this was probably a typo)

Fixes #8601

### CODE REVIEW

**Comment by Cameron653** [comment]
This is just a minor verbage change at this point as we fixed waterclosets down here already.

**Review by Cameron653 — APPROVED** [review]
Just a minor verbage change in the description. Seems fine by me.

**Comment by Heroman3003** [comment]
We actually had intentionally changed verbage to that ourselves. There was also other change in the original Polaris PR which was a bugfix we had already.

**Comment by Cameron653** [comment]
Oh, I presumed the verbage was Polaris since it didn't have an edit comment on it. If that's the case I'll just close this.

**Pull request closed without merging**
