### PR TITLE
Adds 4 new crates for 4 new monkeycubes for the 4 primal species that lack them. 

### PR DESCRIPTION
**Pull request by Ketrai**
adds 4 extra monkey cubes for the special monkeys we have for akula, sergals, vulpakanin and nevreans

(since it's weird that we can't access them in game yet they exist in the code.)

### CODE REVIEW

**Comment by Ketrai** [comment]
don't merge this yet

**Comment by Ketrai** [comment]
Should be good now.

**Comment by Ketrai** [comment]
apparently they have no grab sprites or head sprites either
GRRRRRRRRRRRRRRRRRR, this won't do, i'll update those some other time -v-.

Also vassilan monkeys pls. also vox chickens anyone?

**Comment by SpadesNeil** [comment]
You're modifying core DM files. You don't need to do this, and it makes problems for us when we try to sync with Polaris.

Put your changes into files with _vr at the end. Example:

` code/datums/supplypacks/hydroponics.dm` becomes ` code/datums/supplypacks/hydroponics_vr.dm`

**Comment by Ketrai** [comment]
okay, i'll go do that right away.

**Pull request closed without merging**
