### PR TITLE
Phroronguarded Work Attire

### PR DESCRIPTION
**Pull request by VictorZisthus**
Phoronguarded some things that made sense.

### CODE REVIEW

**Comment by VictorZisthus** [comment]
I'll have to do another detailed runthrough and add more things to the list that would make sense. Lot's of work to be done here. Will be part of a fix to issue #9102

**Comment by KillianKirilenko** [comment]
These should probably either be marked as VR edits, put into _vr files, or pushed up to Polaris.

**Comment by KasparoVy** [comment]
Wicked.

**Comment by KillianKirilenko** [comment]
I don't see any changes to rigs here. *That said* that's a good point and something that actually needs fixing, but almost certainly ought to be pushed up to Polaris.

I believe the issue there is that rigs *have* `PHORONGUARD`, but they have it in their `item_flags` (where it doesn't work) and not their `flags` (where it ought to be).

**Comment by KillianKirilenko** [comment]
Okay I was slightly off (helmet/chest are okay because they inherit it from spacesuits, gauntlets had it mis-set, and boots had it mis-set because they inherited it from magboots which were also mis-set, gg), but I've made the necessary "oops, someone made a silly mistake" fixes for Polaris [here](https://github.com/PolarisSS13/Polaris/pull/7718).

As for the rest of *this* PR; eh. Phoron clearly isn't *super corrosive*, but I do think a lot of 'resilient' clothing would still offer a lot of little nooks and crannies for particulate phoron to embed itself into and later pose a threat to people, so I'd be wary of making too much stuff resistant to contamination.

Besides, clothing contamination is barely a risk to begin with unless you're really careless or reckless.

**Comment by KasparoVy** [comment]
Bless!

**Review by Novacat — CHANGES_REQUESTED** [review]
This touches some polaris files. Should either be sent to polaris or put into _vr files.

**Comment by Arokha** [comment]
Was created before current CI system. Kicking so current CI system runs against it.

**Comment by Novacat** [comment]
Closing due to inactivity.

**Pull request closed without merging**
