### PR TITLE
Expedition Balance Tweaks

### PR DESCRIPTION
**Pull request by Novacat**
- Removes hostile mobs from V4 Beach
- Adds Giant Snakes and Giant spiders in generic V4 Cave spawners
- Reduced respawn rates to cut down on incidences of 'deathclaw swarms'
- Giant Snakes and Deathclaws have reduced overall spawn rates, Giant Spiders and Frogs will generally be more common.
- Replaced Ion hivebots with Ion Spiders
- Fixes a bug with the holdout phaser getting the main phaser's fire modes
- Adds a single holdout phaser to the expedition phaser supply crate

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Why the nerf of the expedition phaser ammo?

**Comment by Novacat** [comment]
Expedition phasers currently, statistically, are equivalent to laser rifles (10 shots at 40 damage per shot) which is a bit too much for something that is pistol sized with a charging crank. The change puts them in line with eguns.

**Comment by SpadesNeil** [comment]
You can't remove and replace the batteries in expedition phasers. You have to _manually_ re-crank them, so if you run out of ammo in a fight, you're fucked.

Revert the change to the phasers.

**Comment by Novacat** [comment]
Done.

**Pull request merged**
