### PR TITLE
Time to cool off

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

Ports over the Suit Cooler sprite from Baystation and adds in a new Emergency Cooler Sprite as well.

## How This Contributes To The VOREStation Roleplay Experience

Replaces a legacy sprite with a cleaner, more refined sprite. Also gives players a visual on how charged their Suit Cooler is.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
 
New Suit Cooler Sprites
Screenshot 2023-06-02 012328

</details>

## Changelog

:cl:
image: Added in a new Suit Cooler sprite with included charge meter
image: Added in a new Emergency Cooler sprite
/:cl:

### CODE REVIEW

**Comment by KillianKirilenko** [comment]
Looks good. If possible, maybe have some indicator of whether it's active or not as well?

**Comment by Youtubeboy139** [comment]
> Looks good. If possible, maybe have some indicator of whether it's active or not as well?

Will work on later, brain hurty

**Comment by Youtubeboy139** [comment]
> Looks good. If possible, maybe have some indicator of whether it's active or not as well?

This actually already exists, looked closer at the code now that I'm not sleep deprived and I found that the battery indicator doesn't turn on unless you turn the device itself on.

**Comment by KillianKirilenko** [comment]
That works!

**Comment by Enzo-Leon** [comment]
Awesome

**Pull request merged**
