### PR TITLE
Ghosts stay in bellies

### PR DESCRIPTION
**Pull request by SatinIsle**
Ported a change to digestion from chomp:
Changed digestion death to place the characters ghost inside of the belly they died in. This allows them to be see the belly text still, be carried around and can even be moved between bellies (such as moved along with everything else to intestines, etc), or hear a final subtled message. Ghosts can leave the belly simply by moving in any direction. Tested and seems to work fine here.

Ports these PRs: https://github.com/CHOMPStation2/CHOMPStation2/pull/3074 https://github.com/CHOMPStation2/CHOMPStation2/pull/4772 https://github.com/CHOMPStation2/CHOMPStation2/pull/7132

Plus one addition of my own to prevent it playing the ingestion sound upon the ghost being placed in the belly.

Following the model of: https://github.com/TS-Rogue-Star/Rogue-Star/pull/213

Note: Currently has a bug where a ghosts view can get stuck in place if they are transferred between bellies.

### CODE REVIEW

**Comment by Heroman3003** [comment]
One thing I'd like personally to see modified about this PR but it may be up for discusssion, is ability for living players that arent the pred to 'see' ghosts that way. Such as in visual belly descriptions, transfer texts, interact texts etc.

**Comment by SatinIsle** [comment]
> One thing I'd like personally to see modified about this PR but it may be up for discusssion, is ability for living players that arent the pred to 'see' ghosts that way. Such as in visual belly descriptions, transfer texts, interact texts etc.

It MIGHT be possible already in the belly contents (where it shows all the other items in the same belly), but I'm not really sure how to test that on my own as I can't get other players in for testing atm.

**Comment by RandoGuy999** [comment]
> but I'm not really sure how to test that on my own as I can't get other players in for testing atm.
@SatinIsle (assuming your testing this on a local server) If you connect to the server while logged in, logout of byond without disconnecting to the server, and then attempt to connect to the server again (Specifically by pressing the yellow sign in daemon), you'll have a guest account connect to the server while still having your actual account connected to the server.
Note: You might have to edit the config so that you can actually have the guest join, since I think by default that is disabled.

**Comment by RandoGuy999** [comment]
> but I'm not really sure how to test that on my own as I can't get other players in for testing atm.
@SatinIsle (assuming your testing this on a local server) If you connect to the server while logged in, logout of byond without disconnecting to the server, and then attempt to connect to the server again (Specifically by pressing the yellow sign in daemon), you'll have a guest account connect to the server while still having your actual account connected to the server.
Note: You might have to edit the config so that you can actually have the guest join, since I think by default that is disabled.

**Comment by Heroman3003** [comment]
I'd say the only thing missing is excluding ghosts from belly examine (aka the one where you examine a pred and it tells you contents if they have it setup)

**Comment by SatinIsle** [comment]
> I'd say the only thing missing is excluding ghosts from belly examine (aka the one where you examine a pred and it tells you contents if they have it setup)

This is now fixed:
image

**Pull request merged**
