### PR TITLE
Fix promethean core revival flavor text and OOC notes

### LINKED ISSUE #5195: Info wiped when revived as promethean
#### Brief description of the issue
When being revived as a promethean, the following information is not restored to your character and therefore lost:
Custom species name
Flavour text
OOC Notes

#### Steps to reproduce
- Be a promethean
- Die
- Get revived from your core

#### Code Revision
8c6c1e51e3880cfacf434b15c2ef6ee2034430c6

### PR DESCRIPTION
**Pull request by Cyantime**
Prometheans revived from their core will now get their flavor text and OOC notes returned.

Closes #5195

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Fixes https://github.com/VOREStation/VOREStation/issues/5195

**Comment by Cyantime** [comment]
DNM, didn't know the other parts of that issue

**Comment by Cyantime** [comment]
Alright, carries over custom species name too, the issue there was actually off in DNA code of all things.

**Comment by KasparoVy** [comment]
Badass, great fix

**Comment by Novacat** [comment]
I cannot merge this, you will have to either make another commit or open another PR

**Comment by Cyantime** [comment]
Travis got pushed into submission.

**Comment by Novacat** [comment]
I am curious why some changes are marked with //VOREStation Edit and not others? Are the non-marked changes being sent up to Polaris?

**Comment by Cyantime** [comment]
The VOREStation Edits are vorestation-specific features, the OOC notes and custom species name. The general flavor text part has already been sent to polaris, yes.

**Pull request merged**
