### PR TITLE
Fixing Tal lore inaccuracies and languages.

### PR DESCRIPTION
**Pull request by MisterGrimm**
This has been something that has bugged me for **years** all the way back to the bay days of virgo, the general inaccuracies in the codex and languages for the Sergal and Nevrean, and the odd lack of the third sapient species, Agudners. While I do not have the spriting skills to create the third Eltus race Agudner, I do have the know how and knowledge to fix the already existing inaccuracies.

- Adds the real official language of Tal, named after the city it was made in : Gold Ring.
- Changes Sagaru and Birdsong to be "ancient animalistic" languages, which were used before the creation and propagation of the language Gold Ring. They can still be used as normal, but it is no longer considered the 'current modern' language Eltus races commonly use.
- Changed Sagaru syllables and the Sagaru speech verb to be accurate to the sounds Sergals commonly make when animalistically communicating.
- Changed the codex entries and the species descriptions of Sergals and Nevreans to be lore accurate, based on the current modern Vilous wiki. _Whoever came up with that 5000 year old Rain joke has bad class._
- Lowered Sergal max age to 60, as that is 90 in sergal years. Left min age untouched for obvious reasons.
- Minor change in organizations_vr.dm, from "Fort Rain on Tal" to "Gold Ring on Tal".

### CODE REVIEW

**Comment by Heroman3003** [comment]
Gonna relegate reviewing this to @BigBababooey

**Comment by TankTheBirb** [comment]
As a heads up, I’ve been (slowly) rewriting sergal lore for Virgo and I’ve already written a fair bit of nevrean lore. The main issue with Vilous’s existing lore in a vore station context is that the events of the Vilous canon happened hundreds of years in the past (based on their technology being a stylistic mix of 1700s to 1900s tech). So I’ve been interpreting a possible future for that. 

we also don’t have Agunders in the code nor lore as is and I’m not really sure I want to find a way to integrate them since they’re visually indistinct from humans in a 32x32 sprite.

However, I do like the idea of a common language. I’m not sure if I’d imply birdsong and sagaru are animalistic, just an older language set before the new, common one. Which in and of itself was probably competing with galactic common in the Vilous system at the time of Tal’s introduction to the stars.

**Comment by MisterGrimm** [comment]
> As a heads up, I’ve been (slowly) rewriting sergal lore for Virgo and I’ve already written a fair bit of nevrean lore. The main issue with Vilous’s existing lore in a vore station context is that the events of the Vilous canon happened hundreds of years in the past (based on their technology being a stylistic mix of 1700s to 1900s tech). So I’ve been interpreting a possible future for that.
> 
> we also don’t have Agunders in the code nor lore as is and I’m not really sure I want to find a way to integrate them since they’re visually indistinct from humans in a 32x32 sprite.
> 
> However, I do like the idea of a common language. I’m not sure if I’d imply birdsong and sagaru are animalistic, just an older language set before the new, common one. Which in and of itself was probably competing with galactic common in the Vilous system at the time of Tal’s introduction to the stars.

The events of the Vilous canon have no set timeframe based on earth. You could put the current Vilous year RC 100 as roughly when they met virgo, and you would require 0 editing on the Backstory section of the virgo wiki for sergals. You may have to edit the Nevrean backstory page a little, since it has a completely different story to the Sergal one, but otherwise it fits fine.

I understand why Agunders are not in the code, but they do still need to be mentioned lore-side, due to their VERY close ties to Sergals.

On the mention of Sagaru and Birdsong, let me just take something directly from the Vilous wiki describing the languages.

Vilous wiki : Cries : "Crying as communication is generally confined to Northern and Western sergals due to their more primitive culture. Eastern sergals may also sometimes use cries but their vocalizations are generally deeper and have rustic dialect like an animal. Southern sergals almost only use verbal language due to their cultural interaction with other races such as the agudners, therefore using cries to communicate is lost to the South."

Vilous wiki : Shigu, northern sergal society, Shigu Kingdom period RC28-RC40 : "Because of the absence of Text and Verbal Language within Northern Lands in the past, native Northern Citizens can't speak fluently and generally cannot read or write text. Even Rain and Leeric themselves were not able to use language during their earlier years. As for text, they could not write any until the end of their days."

Vilous wiki : Shigu, northern sergal society, fall of the Shigu Kingdom RC40-RC100 : "For a while after the World War, the Shigu lands developed a large city of their own, second only to Gold Ring, The "Shigu Dukedom" (Or Shigu Public). Due to the intrinsic Sergal nature of not holding grudges, anyone willing and able helped and cooperated with Northern sergals and as a result, their lands developed and globalized. Many Northerners have also gained the ability to use civilized spoken language and text since the foundation of the Shigu Dukedom."

**Comment by Runa-Dacino** [comment]
Hello!

We appreciate your wish to contribute. Unfortunately, we would strongly prefer if you had had worked with our lore staff rather than made the PR without their involvement.

It is important to note that VOREStation is a Distinct and Separate universe, where even if species names may match and certain themes may be retained - they are not the same species. Just changing our lore for sake of better match with other universes is not, in itself, a sufficient reasoning for doing so. Generally, when making lore changes our primary goal is to give players more hooks to relate their character to the world and most importantly, other players' characters. As such, we do welcome additions to expand what already exists or refine things for better integration.

If you still wish to pursue changes, it is advised you contact Tank and myself on the discord with your suggestions to discuss.

**Comment by Heroman3003** [comment]
If by end of next week, there's no further response or change, I'll probably close this.

**Pull request closed without merging**
