### PR TITLE
Engineering Overhaul

### PR DESCRIPTION
**Pull request by Jakksergal**
An entire redesign of Engineering.

Key features: 
- Engine is now as far away from the hallway as physically possible. Radiation exposure is impossible even with an overcharged SM
- A plethora of air pump ports and scrubber ports were added. Engineering no longer relies on cargo to fill up breaches.
- A new construction area was added where Engineering EVA was. It's multi-z with a balcony and a view!
- Engineering EVA is now recessed inside engineering as it should be. It's directly connected to the workshop for rapid response.
- Introduces a new maintenance area for scenes, RP, and antagery.

Notes: 
- A new map will need to be created for crew monitoring consoles, cameras, and directories. I wouldn't know how to do these so I'll leave the task to someone else.

(Almost) Full image: 
z1 - https://gyazo.com/7d5ac27a5885f191a29310d4dda0b265
z2 - https://gyazo.com/3c06bbe016e42e684c25d99f76dcae85

### CODE REVIEW

**Comment by Jakksergal** [comment]
Hooray! The fix might not be proper but if it isn't, it's no biggie.

**Comment by Yoshax** [comment]
Few points. 

First is the old-style air tank in the secondary atmos which is something I thought we weren't going to be using. 

Second is the SMES room for the engine room. It's in a really weird place compared to previously, and is really separate, it's quite odd, both functionally and aesthetically. 

Third is just the engine room overall. I don't feel like it's very good at all. Everything just looks like a bit of a mess compared to currently. It's also just rather ugly. It's very different to the current one and I don't feel like it's in a good way, I feel it's rather bad.

As a person who enjoys/ed playing engineering I'd hope that this won't go live with that engine room, everything else is kinda okayish.

**Comment by SpadesNeil** [comment]
That SMES and those pipes don't appear to have an asteroid screen.

**Comment by Jakksergal** [comment]
The air tank object was proven to just be, well.. _bad_. Even a whole array of them doesn't match the required output of filling air pumps and the distribution system. I intend to replace Atmos with tanks just like it. The initial reasoning behind not using the room-based air tanks was that there's an infinite supply of O2 on the planet, but it fills very slowly. 

I don't really got a rebuttal for the SMES, that's totally valid. I didn't have many options when it came to that portion. I tried to avoid the wonky solutions of overlapping powergrids as best I could. 

It looks like a total mess, yeah, but so do most atmos systems. Functionally, though, the key points that need to be interacted with to setup the engine are really convenient. There's no objects in your way like the old layout, but that's a bit of a strawgrab.

I'm not sure what you mean about the SMES requiring an asteroid screen? Can you elaborate?

**Comment by SpadesNeil** [comment]
The SMES and pipes have a metal grille surrounding it in space. Either that's not visible on screen or it isn't there.

**Comment by Jakksergal** [comment]
The pipes have a fairing. I'm adding a few more here and there now.

**Comment by Yoshax** [comment]
I just really don't think the tradeoff of being able to shoot the SM an unreasonable amount of times for that engine room is a good trade off, at all.

**Comment by Jakksergal** [comment]
Alright, I see you're really adamant about aesthetic changes that you only have to look at for a short period of time. I'm going to attempt to move things around and post any alternatives I can come up with.

**Comment by Jakksergal** [comment]
I couldn't think of any way to revert back to a more traditional design for the engine core without completely redoing half the department. Which I really don't want to do over aesthetic complaints. I do see a couple of options to rearrange the internals of the core to (possibly) be a bit better. 

Oh, and the SMES room is a total nightmare because of the need for power grids. I couldn't think of anywhere else to put it that wasn't pushing out into space.

**Comment by Yoshax** [comment]
I'm not "really adamant about aesthetic changes that you only have to look at for a short period of time." I'm 'adamant' about voicing my opinion about something being worse than it currently is for a poor reason, and one that basically invalidates what you just said yourself.

```
[1:27 AM] JakkSergal: Yeah. The radiation in the lobby and hallway was the main reason for the overhaul.
[1:29 AM] JakkSergal: It's fun seeing how powerful you can make the engine, though.
[1:30 AM] JakkSergal: Engineering is the "Break the game" department, anyway.
```

So... It kind of can't be both? Can't really " only have to look at for a short period of time." and "see how powerful you can make the engine."

**Comment by Jakksergal** [comment]
You got a point there. I'm gonna rescind all of that, though, because I've created a new layout that I hope everyone can agree is much better. A little more compact but a heck of a lot neater. If you don't like the aesthetics of it, then I've got nothing I can do for you. 

Changes from current:
- Reorganizes the whole engine room except for waste handling.
- Moves gas storage to connect with the atmos substation
- Moves the new main SMES room to where the former gas storage room was and gives it a door between it and the monitoring room for easy access.

Preview: https://gyazo.com/aeb8dbd420f5147a89c885b0497dd1c6

**Comment by Yoshax** [comment]
I just don't feel the 'goal' has been achieved. It's worse for expansion and tinkering than the current setup.

Your engine room appears to be missing an APC though. I'm not certain but the wire setup just doesn't really look right there. There should also probably be a way to get into the SMES room from the monitoring room, which there isn't. If you're trying to make it better you should maybe add more than one filter/vent in the room, it's rather large. One must also question why there's an air tank. You also appear to have changed the colour of some pipes, which is very questionable because they've been one way for sometime.

**Comment by Jakksergal** [comment]
Before I make any adjustments, what sort of engine modifications would you be expecting?

**Comment by Jakksergal** [comment]
The engine room has always had one vent and one scrubber. I don't agree with it but the only way to change that, with any layout, would be to cross pipes over everything or increase the room by one tile in every direction with a set of scrubber and distro pipes going around it.

I moved back the gas storage room to provide an extra tile that was intended for modifications, but I could potentially route a set of scrub/distro pipes from the gas storage room into the engine room, but that would take up room for the modifications.

The 'air tank' is an empty waste tank to help delay waste clogging. There's the conventional connector port beside it if anyone wanted to expand/interact with it. Though I may just remove that and leave it to the player if it gets in the way. The pipe colors were changed because it never made sense to represent the hot line with a cold color and a cold line with a neutral color. I can change it all back to the original colors if I get more voices on the matter.

The wiring's not neat, I'll give you that much, but it doesn't overlap power grids. Wires can cross and be independent since quite a while ago.

**Comment by Jakksergal** [comment]
Alright.. That's as final as this is going to get unless there's any more directly pressing issues. 

Full screenshots can be seen here if anyone wants to go pixel hunting:
https://gyazo.com/ff17b2dd14489529817d3ffb16fa7fde
https://gyazo.com/f6cc1329d17ef58db48c4778a389be9f
https://gyazo.com/f21327953925c6f503865b98c162f5c5

**Comment by Jakksergal** [comment]
I would like to know why before I do. Even if I were to fill that whole West wall with air tanks it wouldn't be able to fill the air pumps fast enough. 

Don't give me "We have infinite supply of air on the surface" because, while it's true, 1 mole a year doesn't cut it.

**Comment by Arokha** [comment]
I'd like Leshana to look at this, since they're more engineering-focused than me.

**Comment by Jakksergal** [comment]
I'm not against a second opinion, but it doesn't look like @Leshana checks their email. I don't know their contact information so if you could either message them or suggest someone else, I'd apreciate it. I don't want this to turn into a month-long PR.

**Comment by SpadesNeil** [comment]
Leshana lives with Aro. Aro's got this.

**Comment by Cameron653** [comment]
Any word on this? Been sitting here an awfully long time.

Additionally,
Conflicting files
maps/tether/tether-03-station.dmm
:v

**Comment by SpadesNeil** [comment]
The conflict is gonna be stuck here I think. There's not been a consensus either way on these changes from people who know what they are doing, save obviously for Jakk.

**Comment by Jakksergal** [comment]
I can fix the conflict very easily but I'd like to know if I even should. Yosh went silent on the issue and Aro's yet to provide any information on their review. I've tested everything myself and couldn't find an issue. No one's given me feedback on anything but the air tank, which was changed, and the engine, which I cooperated on to make better.

I've been waiting over a week for a review that's yet to take place. I asked Aro directly about the review on Discord and they gave no reply regarding it.

I would _like_ to cooperate and get this merged and revised but no one seems to be giving any indication that I _should_.

**Comment by Yoshax** [comment]
I said my piece and don't really want to spend more time harping on with repetition. I haven't really got anything new to say beyond what I already said.

**Comment by Jakksergal** [comment]
I wasn't trying to egg you on or anything. Just staying that things have been compromised and resolved.

**Comment by HawkerTheGreat** [comment]
I know my word doesn't mean as much as the devs, but I feel I'm just as much a part of engineering as I am atmospherics. From experience I can safely say the current design is flawed... We constantly have people walking by it and if I even enter engineering for any reason, I get shot up with radiation for even thinking of going anywhere near the main hallway because the core is waaay too close to the main area. This is an issue, I don't think his mapping is perfect, but I support it more than I support the current map.

**+1 To adding it.**

I hate to see this just sit here forever, too. Jakk obviously put a lot of work in making this.

**Comment by SpadesNeil** [comment]
Anyone who can speak from experience on engineering has a valid say.

**Comment by Dingosilver** [comment]
I only very occasionally play engineering, so I can't speak for the more complex repercussions it might have, but I'm with Hawker in that this really helps stop civilians from constantly getting irradiated by being even nearby engineering. That, and I _love_ the look of that new construction area.

**Comment by Jakksergal** [comment]
What the actual fuck, Git
What the actual fuck.

Let me google how to fix this shit..

**Comment by SpadesNeil** [comment]
screams_externally

**Comment by Jakksergal** [comment]
Might need 8 more DO NOT MERGE tags to get the point across.

**Comment by Jakksergal** [comment]
I'm unable to revert. I don't know how to fix this.

**Comment by Jakksergal** [comment]
At this point I'm all for completely closing the PR for another round. Conflicts are the worst.

**Comment by Cameron653** [comment]
Created a new tag, just for this PR and any PR in the future that breaks everything.

**Comment by Jakksergal** [comment]
My fork is cursed. I have touched nothing since my attempts last night at fixing that issue and yet there are completely new and inexplicable changes. Please just close the PR and let me do again.

Also, I recommend changing the new snazzy tag you made just for my failures to say "Panic in the Repo"

**Pull request closed without merging**
