### PR TITLE
Remove personal terminals, revert hydroponics

### PR DESCRIPTION
**Pull request by skraaak**
Removes several machines from the salvagable list and reverts the hydroponics machines to previous version.

As the original artist from Sojourn, which pushed sprites upstream to Eris, which then had sprites ported to Polaris, then downstreamed to Virgo, this PR resolves a permissions issue. Specifically, the hydro tray, seed extractor, salvageable personal terminals, and the salvageable computers are removed.

Since politely asking was not sufficient communication, I've made this PR to solve the issue without any further strife.

### CODE REVIEW

**Comment by Screemonster** [comment]
This makes changes to non-VR icon files and will conflict next time there's an upstream merge that changes DMIs.

**Comment by Arokha** [comment]
`resolves a permissions issue`

What permissions issue?

**Comment by Leshana** [comment]
`icons/obj/salvageable.dmi` is an upstream dmi file.  Modifications to that need to either be done in PR to https://github.com/PolarisSS13/Polaris or the dmi needs to be copied to `salvageable_vr.dmi` and changes made in there.  The salvageable.dmi file itself can't be changed here or it will mess up merges from upstream.

**Comment by drexample** [comment]
That's not how this license works, my dude.
You can ask them to be removed, but nobody has any legal (or otherwise) obligations to fulfill your request.

**Comment by skraaak** [comment]
> That's not how this license works, my dude.
> You can ask them to be removed, but nobody has any legal (or otherwise) obligations to fulfill your request.

A request was filed, but due to... incredibly poor communications, it was denied because an _Eris_ coder said to, while there being an issue of them actually coming up from Sojourn. Regardless, it was formally requested the removed sprites be removed from Vorestation, regardless of implimentation.

**Comment by Arokha** [comment]
Their source is irrelevant, really, as long as you licensed them AGPL3. You personally admit to having committed them to an AGPL3 codebase (any downstream of Eris is necessarily AGPL3), so I'd point you to the terms of the license that say that it is both irrevocable, and that applying additional restrictions is against the license:

[AGPL 3.0](https://www.gnu.org/licenses/agpl-3.0.en.html) §2p1
`All rights granted under this License are granted for the term of copyright on the Program, and are irrevocable provided the stated conditions are met.`

Additionally,
[AGPL 3.0](https://www.gnu.org/licenses/agpl-3.0.en.html) §10p3
`You may not impose any further restrictions on the exercise of the rights granted or affirmed under this License.`

If you're attempting to impose some additional restriction about us not being able to use it, I think you'll find that *you're* in violation of the license you put your works under, not us.

**Comment by drexample** [comment]
> 
> 
> > That's not how this license works, my dude.
> > You can ask them to be removed, but nobody has any legal (or otherwise) obligations to fulfill your request.
> 
> A request was filed, but due to... incredibly poor communications, it was denied because an _Eris_ coder said to, while there being an issue of them actually coming up from Sojourn. Regardless, it was formally requested the removed sprites be removed from Vorestation, regardless of implimentation.

Again, you can *ask* people to remove the sprites, but they don't have to. There is no permissions issue, because no one has to ask for permission, once you release something in open source project, anyone can use it according to the license. And no one can do anything about it.

**Comment by chaoko99** [comment]
The sprites aren't licensed AGPL. They're CC-BY-NA, They're sub-licensed.

**Comment by chaoko99** [comment]
There's still nothing wrong with just avoiding some stupid shitstorm by granting their request. Y'know. Being nice.

**Comment by Heroman3003** [comment]
There's no reason to be a legalese dick about the situation. Just because you can do something doesn't mean its a good thing to do. If someone is simply asking their work removed to not associate with our server (let's be honest, many people wouldn't want that), it should just be done.

**Comment by MistakeNot4892** [comment]
CC licenses are non-revocable.

**Comment by TheFurryFeline** [comment]
According to Travis, some items were not removed related to salvageables

**Comment by Novacat** [comment]
> There's still nothing wrong with just avoiding some stupid shitstorm by granting their request. Y'know. Being nice.

If they were serious about this, they would ask Polaris, especially since the core of the sprites being asked to remove are not even ours, but PR'd and added to Polaris with which we are a downstream of.

This PR inherently cannot abide by our coding standards. I am also not reverting hydroponics since, as said, someone here had replaced over half of the original sprite. Granting a reversion based on that would potentially open the door to the original designer of the SS13 hydroponics sprite being able to order codebases to remove even derivative sprites based on that design, including your very own! Considering that I highly doubt you would ever entertain a request like that.

I believe this PR has been entertained long enough. I would have closed this sooner but I have been rather sick the past week and avoiding all github related things.

**Pull request closed without merging**
