### PR TITLE
Oties and wilderness removed

### PR DESCRIPTION
**Pull request by SpadesNeil**
Both are glitchy and horrible and bad and they're causing more problems than the enjoyment of makes them worth. Ergo, they have been removed.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
and, shit, forgot to map cleanup on Tether, one minute

**Comment by SpadesNeil** [comment]
Fixed.

**Comment by SpadesNeil** [comment]
```The command "awk -f tools/indentation.awk **/*.dm" exited with 1.

0.02s$ md5sum -c - <<< "88490b460c26947f5ec1ab1bb9fa9f17 *html/changelogs/example.yml"

html/changelogs/example.yml: OK```

![confused](https://user-images.githubusercontent.com/6484985/29744807-890e79a6-8a7a-11e7-95ff-39349eaf26f0.png)

**Comment by Ketrai** [comment]
This is a good removal. The wilderness wasn't random as intended. (e.g for the longest time ever I had memorized it) and there really wasn't much fun to be had except hunting trips or opening a weapon crate hoping to get something cool like an energy sword from the crash site. also the server is way less laggy now.

**Comment by SilverTalismen** [comment]
Guess they are Otie here?

**Pull request merged**
