### PR TITLE
Port over RPD from YW/Chompstation.

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
Port of https://github.com/Yawn-Wider/YWPolarisVore/pull/443

Polarisport inc soon/whenever I get around to it.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
If this doesn't have its conflicts fixed by this Sunday, I suggest closing this with the tag "No response."

**Comment by Rykka-Stormheart** [comment]
> If this doesn't have its conflicts fixed by this Sunday, I suggest closing this with the tag "No response."

I'll get on it this week.

**Comment by TheFurryFeline** [comment]
Conflicts resolved.

**Comment by SpadesNeil** [comment]
Still missing //VOREStation Edits.

**Comment by TheFurryFeline** [comment]
Edit comments added, switched dmi icon over to the _vr.dmi, RPD to RPD_vr

**Comment by Novacat** [comment]
I still say with the extensive amount of vorestation edits this is going to require, it would be better off pushed to Polaris.

**Pull request closed without merging**
