### PR TITLE
Huge Map Tweaks w/antigrief

### PR DESCRIPTION
**Pull request by VictorZisthus**
S1:

Made the pillars outside R-wall. They support a portion of the station, it only makes sense that they would be ultra sturdy.

Added R-wall along atmos's eastern S1 wall to prevent busting in through holodeck dorms.

Added a box of Replacement lights to Surface med, overhauled the resleeve shower room to be public access, actually have a shower and not just a curtain with drains, and added some towels and bathrobes.

Fixed some issues with the Janicloset, making both doors say the same thing with the same color code, fixing the interier windoor under the shutters to be jani access only [previously public] and added a third bottle of space cleaner [one for each janitorial cart]

Added a light in the Maint tunnels so that the emergency evacuation from Surface Med to the Panic Shelter is fully [albeit dimly] lit

S3.

Secured the outer walls of Xenobio and the isolation hallway with R-wall to match the R-windows.

Patched a few r-wall holes in Surface sec [nothing major, just some corners needed reinforced to match the rest of the walls]

Adjusted the Tether automated backup shuttle to and from the station to be operable by the public. It's an emergency shuttle for goodness sake, having only exploration and Pilot's being able to operate it was a major safety hazard in the event the elevator was non-operational! [Modified all three control consoles to do this, S3, Shuttle, and A1]

Fixed lighting issues in the Panic Shelter.

Changed steel tile to wood tile in public study [look under the doooooors]

A1

Added R-walling along backup atmospherics to lessen the damage of canister explosions to Engineering's EVA and tool storage areas.

Added a way for engineering to lift Primary engineering lockdown from the outside [like they can do with atmos]

Added an Engine Room lockdown separate from Engineering lockdown to combat greifing. Greytide will now be required to gain access to Engine Room level clearance to lift blast doors, or set up emitters to bust them down.

A2

Added a way for engineering to lift Primary engineering lockdown from the outside [like they can do with atmos] 2, Electric boogaloo

Added R-walling to Secure Tech Storage.

A3

Added R-walling along the outside of Sec that was missing in some areas, as well as fully R-walling Forensics.

Mining:

Added a trashbin to combat litterbugs. Offset fire closet to adjust for bin placement.

Rewired exterior APC to go under the window instead of the wall

--------

Surface Med Overhaul

Added colormates to the re-sleeve rooms, adjusting some things to acomidate for the change.

Added a Blood-Onator to Surface med storage.

Added a disposal bin to surface med's lower hallway, offseting an air alarm to account for it.

Added a hand labeler to autopsy room on A2.

Added a syringe gun, MLEM, Rad suit, toolboxes, Defib to surface med storage to match Asteroid Medbay storage. Moved things around to accomidate.

Added Defibs and nanopaoste to Asteroid Surgery to match surface surgery. Removed a redundant set of surgery supplies from OP2.

Upgraded the EMT closet to an EMT bay at Surface Medical. Added "support" for the new closet at surface 1 in the form of a new wall just outside mining. Adjusted loading bay to compensate. [Has the hidden added benifit of preventing people from taking the mining inlet schute into the station without being damaged now that the tube is longer. NO FUN ALLOWED.]

New EMT bay has an EVA to quickly respond to any mining mishaps.

New EMT EVA has a small Maint network.

Moved some lights and items around in the surface medbay to make it less clutterd. Also added a sink.

Spun some wheelchairs around in Asteroid medbay storage so the backs are facing the wall.

Numerous updates to surface medbay once again to accomidate for the change in CMO office location.

Surface med is now part of the disposal loop.

Surface med can now be locked down.

### CODE REVIEW

**Comment by Heroman3003** [comment]
Tbh babyproofing literally all of science and the non-secure part of tech storage seems extremely excessive. I can see the chem lab and missing parts of xenobio. But also literally all of 'civilian' parts of science and all of internal walls as well? And even the completely decorative xenobio pillars? Both of these seem like excess babyproofing rather than grief protection.

Also dim lighting in both panic shelter and reading room always seemed more like intentional mood lighting rather than lighting with issues to me.

Also it's just me, but wasn't there any better aesthetically-wise places/offsets/positions to put lockdown lift button outside of engineering? In atmos it looks fine being on the table and without offsets, but when in the corner of the wall like that... Might just be me on this one. Same with Cental's button.

**Comment by VictorZisthus** [comment]
> 
> 
> Tbh babyproofing literally all of science and the non-secure part of tech storage seems extremely excessive. I can see the chem lab and missing parts of xenobio. But also literally all of 'civilian' parts of science and all of internal walls as well? And even the completely decorative xenobio pillars? Both of these seem like excess babyproofing rather than grief protection.
> 
> Also dim lighting in both panic shelter and reading room always seemed more like intentional mood lighting rather than lighting with issues to me.
> 
> Also it's just me, but wasn't there any better aesthetically-wise places/offsets/positions to put lockdown lift button outside of engineering? In atmos it looks fine being on the table and without offsets, but when in the corner of the wall like that... Might just be me on this one. Same with Cental's button.



> 
> 
> Tbh babyproofing literally all of science and the non-secure part of tech storage seems extremely excessive. I can see the chem lab and missing parts of xenobio. But also literally all of 'civilian' parts of science and all of internal walls as well? And even the completely decorative xenobio pillars? Both of these seem like excess babyproofing rather than grief protection.
> 
> Also dim lighting in both panic shelter and reading room always seemed more like intentional mood lighting rather than lighting with issues to me.
> 
> Also it's just me, but wasn't there any better aesthetically-wise places/offsets/positions to put lockdown lift button outside of engineering? In atmos it looks fine being on the table and without offsets, but when in the corner of the wall like that... Might just be me on this one. Same with Cental's button.

Removed the babyproofing!

**Comment by Heroman3003** [comment]
I do not think that JUST moving CMO office is good idea. Especially seeing what's been done with the old one. I think that if medical is to be moved fully to surface, it should be an "all or nothing" type of project, because trying to just slap in the specific parts to current layout of surface medical just looks messy, and I can't even see what the old CMO office s even meant to be.

**Comment by Wickedtemp** [comment]
Can we get screenshots of how SurfaceMedical will end up looking? And I'm not sure about moving the CMO office to Surface at the moment. Currently, it tends to be 50;50 on which Medbay is used primarily. Asteroid Medbay has two operating rooms and the morgue so it still maintains its usefulness.

**Comment by Heroman3003** [comment]
Asteroid medical also has remaining medical facilities, such as virology, properly sized breakroom, recovery ward, psych office, and generally more equipment.

**Comment by SpadesNeil** [comment]
If this doesn't have its conflicts fixed by this Sunday, I suggest closing this with the tag "No response."

**Comment by VictorZisthus** [comment]
> 
> 
> If this doesn't have its conflicts fixed by this Sunday, I suggest closing this with the tag "No response."

Oh jeez, I wasn't paying attention to Github. I'll fix the issues.

**Comment by VictorZisthus** [comment]
I have no idea how to fix the new merge issues... Gonna need some help with that.

**Comment by VictorZisthus** [comment]
Closing this request because I'm unable to solve the conflicts. I'll start from scratch on the new master branch when it is released.

**Pull request closed without merging**
