### PR TITLE
Fixes #371

### LINKED ISSUE #371: You get full way too fast
#### Brief description of the issue 
You get full too quickly and are unable to eat after one single food item.

#### What you expected to happen
Be able to eat a bunch of things

#### What actually happened
Eat one muffin and instantly be  fat and unable to eat

#### Steps to reproduce
Eat something
Be unable to eat more.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab. 
N/A didn't have time to check.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

Lines related: https://github.com/VOREStation/VOREStation/blob/54272da16785733c4036ab3738229491b85de5a3/code/modules/reagents/reagent_containers/food/snacks.dm#L59-L69

### PR DESCRIPTION
**Pull request by SpadesNeil**

### CODE REVIEW

**Comment by Cameron653** [comment]
This makes it so it only applies to people forcefeeding others, not if you're eating by yourself.

**Comment by SpadesNeil** [comment]
Whoops. Gimmie a minute.

**Comment by Cameron653** [comment]
Everything looks good, but it seems Travis isn't firing for some reason.

**Comment by SpadesNeil** [comment]
Merging because Cameron said it looks good. *shrug*

**Pull request merged**
