### PR TITLE
Exploration Gear Expansion DLC

### PR DESCRIPTION
**Pull request by klaasjared**
Adds long-awaited exploration department-based bags/backpacks as well as revamps the belts for both Explorer and Pathfinder. I also fixed the radio backpack on-mob sprite and did a little touching up like adding a dedicated handset sprite as opposed to the old signaler.

Below are the sprites that were added/changed.

pack_showcase

belt_showcase

radio_showcase

### CODE REVIEW

**Comment by lm40** [comment]
handset sprite looks amazing :disbelief:

**Comment by Ketrai** [comment]
image
image
Pointers for if you want to do in-depth shading.

**Comment by klaasjared** [comment]
Do not merge this yet, gonna modify the sprites

**Review by Novacat — CHANGES_REQUESTED** [review]
I would like to keep the old sprites (at least for the explorer backpack/satchel and the explorer belt) around because I probably will repurpose them for other things.

**Review by Novacat — CHANGES_REQUESTED** [review]
Still needs the onmob sprites restored. Also, rather than using (old), I would recommend using _old instead, to make it easier for varediting.

**Comment by Arokha** [comment]
Dang, these're pretty

**Comment by Arokha** [comment]
Missed explorer_belt (old) and explorer_belt (old) in last commit, should do what Ascian said and do 'em to _old and I'll dismiss his change request

**Comment by klaasjared** [comment]
closing really quick to reset the test - there's no Map Diffs so there shouldn't be an error

**Pull request closed without merging**
