### PR TITLE
removes all \icon

### PR DESCRIPTION
**Pull request by Kashargul**
Seemingly the \icon code is fully deprecated. It does nothing on old chat and causes a massive error log in Tg-Chat, inflating server log files into the GB area within merely a few rounds.

🆑Upstream
del: removes all \icon tags
/🆑

### CODE REVIEW

**Comment by Heroman3003** [comment]
Are you certain it does nothing on oldchat? IIRC it was added specifically because bicon didnt work for oldchat.

**Comment by Kashargul** [comment]
> Are you certain it does nothing on oldchat? IIRC it was added specifically because bicon didnt work for oldchat.

I didn't see any icons using oldchat, maybe that needs to be tested again. I only tested it for a short time and all icons in oldchat looked broken / didn't load during my tests.

**Comment by Kashargul** [comment]
Seems it's actually removing the images from oldchat. Going to test the icon2html proc later to see how that ends up.

**Comment by Kashargul** [comment]
I've not found a way for it to work with old chat and TG-Chat without erroring on TG-Chat or removing the icons on old chat.

**Comment by Kashargul** [comment]
Part of the 515 PR to rid of those.

**Pull request closed without merging**
