### PR TITLE
Adds a new M41A and M2922. Adds to weapons crate

### PR DESCRIPTION
**Pull request by Cameron653**
Adds a M41A, its sprite and M2922 and its sprite, along with adding them to a weapons crate. 
Also adds m41a ammo sprites. 
Adds both weapons to the automatic rifles weapon crate.
# All sprites provided by SilencedMP5A5

M41A full: https://i.gyazo.com/d5d7dbbd1e68326d4bbb3a8390ed22c8.png
M41A empty: https://i.gyazo.com/5fe1af79279bde390f3c389df9fba23b.png
M41A R hand: https://i.gyazo.com/25a77cc3e22c097be06d6a6f2acc393a.png
M41A L hand: https://i.gyazo.com/d4ed5df4e46b5b8f268a72d865355cec.png
M41A Back: https://i.gyazo.com/3e9e29f4a6761190ad7bd8dfc08c782f.png
M41A ammo: https://i.gyazo.com/bc21522d680f825199d331ea580bd0d7.png

M2922: https://i.gyazo.com/569ac6438275c5cb1e7d3660256b0f98.png
M2922 Empty: https://i.gyazo.com/fd35b3775f1d6fcf9689512e58f8573b.png
M2922 L Hand: https://i.gyazo.com/11dee5d7d3a6f162d16f17abbe33d4b1.png
M2922 R Hand: https://i.gyazo.com/f4f50cbd1c6b4631c17d8970a584f5cf.png
M2922 Back: https://i.gyazo.com/9b780abe9fb20c8e28cf41367d1d3592.png

### CODE REVIEW

**Comment by DarkWolfInsanity** [comment]
You can't unfortuantely use that sprite of the M41A because it is under copyright of Colonial Marines. I was talking with the owner myself with this the other day. All their icons are under a license that does not promote open use.

**Comment by Cameron653** [comment]
Actually, I am able to use their sprites as they're under GPL as shown here:

https://github.com/ColonialMarines-Mirror/ColonialMarines-bleedingedge/blob/master/LICENSE-GPL3.txt

(Mirror since CM falsely took down the original.)

This means I'm able to use their code as I wish and any sprites or other
parts of it, as section 5 subsection C. Says, and I quote:

 "You must license the entire work, as a whole, under this
License to anyone who comes into possession of a copy. This
License will therefore apply, along with any applicable section 7
additional terms, to the whole of the work, and all its parts,
regardless of how they are packaged."

This means that anyone that wishes to use the code may do so as they
please, no matter how they got the code.

Also, just because the owner says something doesn't mean it's true.

**Comment by SpadesNeil** [comment]
While Cameron is correct, I just think the sprites look like shit. I have a much better sprite for the pulse rifle laying around in the old code. Why not use that?

**Comment by Cameron653** [comment]
I could use different sprites for them if I'm given them. I made this PR since I wa s given the sprites and asked to have them added into the game.

**Comment by SpadesNeil** [comment]
Go dig them up from our old code. The sprites are infinitely less shitty.

https://github.com/SpadesNeil/VOREstation/

**Comment by Cameron653** [comment]
I'm looking at the gun.dmi file on the old code and all I can find is guns that are already in our current gun.dmi or gun_vr.dmi, and the pulse rifle in the old gun.dmi is the same as our current one.

Although, I did notice that we had an old m41a sprite in gun_vr.dmi 
https://gyazo.com/59b97d91cec049dfa7e75e7b713b2580

Should I use those sprites instead?

Also, what should I do with the M2922 code? I really don't see any sprites that aren't already used that can be used for it.

**Comment by SpadesNeil** [comment]
Redaction: I literally just read the license. The license literally says nothing about sharing. Closing this PR.

**Comment by apophis775** [comment]
Cameron is actually NOT correct.

I contacted the FSF (holders/maintainers of the GPL and AGPL license) and that repo stating that "GPL is GPL" is actually wrong.  According to them, hacking into a repository is the equivalent of what they consider "physical theft" and violates the GPL license, as well as "Trade Secret" law.  Because the GPL does not require distribution, when you are operating under "non-distributed" as they call is, because the FSF does not share the "common SS13 definitions" of Open/Closed source.  ( https://www.gnu.org/philosophy/open-source-misses-the-point.en.html)  .  
Anyway, I talked with the FSF and a copyright lawyer at length after the theft of our code and can provide references as necessary.  You can also contact the FSF yourself.  

If you want to ignore all that and claim "GPL is GPL", remember that you can not transfer code from GPL to AGPL (The licenses are not a sideways shift and are incompatible with each other, so a relicense is necessary) without express permission of the original developers, which we are expressly not giving permission for anything we have that may fall under GPL to be used into AGPL.  

If you want to talk about the licenses or how they function, feel free to contact me over Discord, Our Forums, or with a message here, I'm more than happy to discuss them.

**Comment by SpadesNeil** [comment]
Aye, I did speak to you about this shortly before I closed this PR. Either way, it's moot now. Still, good for education and future reference.

**Pull request closed without merging**
