### PR TITLE
Bugfixes and features

### LINKED ISSUE #354: Floorlength Braid hairstyle is broken.
#### Brief description of the issue
Basically, the title of the issue.  It doesn't show up.
#### What you expected to happen
To see the hairstyle on my character.
#### What actually happened
Hair doesn't load, character is bald.
#### Steps to reproduce
1. Create character.
2. Choose the Floorlength braid in the hair options.
3. See a bald head instead in the character preview.
BONUS GAME:
4. Spawn in as character.
5. See that they're still bald.

#### Additional info:
 - **Server Revision**: release - 2016-06-09
eb05fc0682f692b13d69b9e8b6f277dec003c47d 
 - It's also still a thing in the latest V.O.R.E. code.
 - Looked in the code, someone over at Polaris seems to have done it on purpose?

`	braid
		name = "Floorlength Braid"
		icon_state = "bald" //Trust me, it's better this way.`

### LINKED ISSUE #384: Akula eggs not working
Akula eggs have no sprite

Expected an egg to appear after egging someone

Egg "appreared" as an spriteless object

steps: "eat" someone as an akula, egg them.

### LINKED ISSUE #386: dogborg digestion doesn't seem to work correctly
#### Brief description of the issue
A dogborg ate a player. Roleplayed. Hit cleaning cycle. It didn't digest, instead just giving the digestion message over and over.

#### What you expected to happen
ding dong gurgle.

#### What actually happened
  [Player PM] Alex123890/(Alexander Nash)(?): i would also like to state that i have had this happen with Two diffrent borgs, one multuble times, it also causes a problum with the borgs power by repetedly giveing it the digestion power boost
  [Player PM] Alex123890/(Alexander Nash)(?): nevermined, anyways i Sould be set to digest but it seems to still not digest me or something, litteraly all i did was rp a bit and than thay hit the self clean, so im not shure what could have caused it

From my end, I saw
ADMIN LOG: Wyvernus/(KOBALT) has digested Alex123890/(Alexander Nash) as a dogborg. (JMP)

thirteen times in total. Saw some LOOC about them hitting crit some time before, not sure if they tried to turn it off and on again.

#### Steps to reproduce
Eat someone as dogborg.
Commence cleaning cycle.

#### Additional info:
Server revision: release - 2016-06-15
50aec7ce3f6e10a8cbdd4d96ecaf56a76ba4d2e8

### PR DESCRIPTION
**Pull request by Cameron653**
- Fixes #384  Akula eggs.
- Fixes #386  dogborg digestion.
- Fixes absorption being super slow.
- Adds custom monkeys back
- Custom monkey sprites: http://puu.sh/pL776/892f3fc5ae.png
- Fixes #354 

# Changes overview:

Akula eggs were using the locker.dmi. Removed this and gave them an icon_state.

Dogborg digestion wasn't properly digesting people. Now it properly deletes them after digestion.

Absorption now takes a flat 5% each tick instead of 4 nutrition per tick, meaning you can absorb people that ate shitloads of food. People will be properly absorbed when under 100 nutrition.
# Absorption explanation and example below
Absorption now works like this:
Removes 5% of the prey's nutrition each tick, and the predator gets that 5%

Example: So 1000 would progress as shown: 950, 902, 857, 814, 773, 735, 698, 663, 630, 598, 568, 540, 513, 487, 463, 440, 418, 397, 377, 358, 340, 323, 307, 291, 277, 263, 250, 237, 225, 214, 203, 192, 183, 174, 165, 157, 149, 141, 134, 127, 120, 114, 109, 103, 98(Absorbed) 
When nutrition > 100, the prey becomes absorbed
(NOTE: Above numbers are rounded.)

So, it'd take 45 ticks  (~90 seconds, give or take.) for someone with 1000 nutrition to be absorbed.

### CODE REVIEW

**Comment by Cameron653** [comment]
DNM for now, going to involve multiple bugfixes.

**Comment by Cameron653** [comment]
Changes overview:

Akula eggs were using the locker.dmi. Removed this and gave them an icon_state.

Dogborg digestion wasn't properly digesting people. Now it properly deletes them after digestion.

Absorption now takes a flat 10% each tick instead of 4 nutrition per tick, meaning you can absorb people that ate shitloads of food.
# Absorption explanation and example below
Absorption now works like this:
Removes 10% of the prey's nutrition each tick, and the predator gets that 10%

Example: So 1000 would go to 900, 810, 729, 656, 590, 531, 478, 430, 387, 348, 313, 282, 254, 228, 205, 185, 166, 147, 133, 119, 107, 96, and have it so when they go under 100 nutrition they get absorbed. 

So, it'd take 22 ticks  (~66 seconds, give or take.) for someone with 1000 nutrition to be absorbed.

**Comment by SpadesNeil** [comment]
Looks good to me.

**Comment by Cameron653** [comment]
DNM, going to add more things to this.

**Pull request merged**
