### PR TITLE
Changes to Arrivals Locker room

### PR DESCRIPTION
**Pull request by Very-Soft**
Turned the locker room into 2 rooms, 1 with more lockers, 1 security checkpoint

arrivals 1

arrivals 2

arrivals 3

I mostly did this as a test, as I'm learning how to map and things, but also thought that, what with the dorms being so close by, what with all their toilets, that maybe the locker room should have more lockers. And then there's a small security checkpoint, so you can roleplay papers please with Visitors.

### CODE REVIEW

**Comment by SilencedMP5A5** [comment]
neat

**Comment by SingoDingo** [comment]
I like it, personally!

**Comment by Leshana** [comment]
I like how there is a bookshelf, and how there are donuts.

**Comment by LittleBigKid2000** [comment]
Needs a speaker playing the Papers, Please theme on loop.

**Pull request merged**
