### PR TITLE
Fix misleading alert.

### LINKED ISSUE #3828: The observe button's warning about respawning lies
#### Brief description of the issue
When you click the 'Observe' button in the lobby, it says you will have to wait one minute.
Until now, that's been correct. Now, the respawn timer after observing is apparently _5_ minutes.

#### What you expected to happen
To be able to return to the lobby after observing for one minute.

#### What actually happened
Had to wait five minutes to return to the lobby.

#### Steps to reproduce
- Observe
- Wait for a period of time between 0 and 299 seconds
- Click 'respawn'

#### Code Revision
- ad18753b9d6bfd50b51846b726f025f1e781a75c

### PR DESCRIPTION
**Pull request by lbnesquik**
This correct a dated overlook.
Fixes #3828
This does not correct #3887

### CODE REVIEW

**Comment by Mewchild** [comment]
The problem with this, as indicated in #3887, is that the tram still allows you the instant respawn

**Comment by Mewchild** [comment]
The problem with this, as indicated in #3887, is that the tram still allows you the instant respawn.
Also, you linked an issue with nothing to do with this. https://github.com/VOREStation/VOREStation/issues/3828

**Comment by lbnesquik** [comment]
Correction is once more appreciated. I got all mixed up typing those. Regarding the tram, i think that's another problem that, while related, doesn't affect this PR.

**Comment by Mewchild** [comment]
You can't say it's fixing an issue, when you're not in fact fixing it. You're saying it's fixing a misleading alert, while the tram will still be incorrect and have a different time from the others (At instant, as opposed to the 5 that's now in the warning/alert)

**Comment by SpadesNeil** [comment]
Needs // Vorestation Edit

**Comment by lbnesquik** [comment]
Did it with github built in editor. Not sure it's very helpful there.

**Pull request merged**
