### PR TITLE
Add a side door to the forensic room. Markings suck

### PR DESCRIPTION
**Pull request by lbnesquik**
- This does not cancel giving detective more access to the rest of security.

### CODE REVIEW

**Comment by lbnesquik** [comment]
This needs a mapmerge before being merged. Ask Rykka on the discord about this particular PR as i am simply not used to those tools.

**Comment by VictorZisthus** [comment]
Give me access to this PR and I'll run mapmerge!

**Comment by lbnesquik** [comment]
This PR has been fxixed, yey!

**Comment by Novacat** [comment]
Not fixed.

**Comment by lbnesquik** [comment]
What is the issue?

**Pull request closed without merging**
