### PR TITLE
Add protean shakes

### PR DESCRIPTION
**Pull request by Arokha**
Adds protean shakes to fitness vendors (as contraband), with minor mechanical effect.

Liquid protean is weak NIF repair juice (10% as effective), and weak tricord (30% as effective). Metabolizes at half the speed though, so you probably shouldn't try to replace either with it.

### CODE REVIEW

**Comment by Rykka-Stormheart** [comment]
description = "This seems to be a small portion of a Protean creature, still slightly wiggling."
taste_description = "wiggly peanutbutter"

.... urgh


nice

**Comment by Heroman3003** [comment]
Honestly, for the NIF repair aspect of it, speed of processing is entirely irrelevant downside, since as long as it processes eventually (and if you dont die it will), you get full use of its effect.

**Comment by Arokha** [comment]
True though still, 0.1x the effect.

**Comment by Little-119** [comment]
I feel responsible for coming up with this dumb pun

**Pull request merged**
