### PR TITLE
Makes Vox spawn with a fancy dancy double emergency Phoron tank

### PR DESCRIPTION
**Pull request by Yoshax**
Dying is bad.

### CODE REVIEW

**Comment by Arokha** [comment]
Did you test this? ;v

**Comment by Yoshax** [comment]
Yes. The tank exploded on-spawn. Optimal result.

**Comment by Arokha** [comment]
So is this fixed-fixed now? And has an icon? Did you just push -f it or something

**Comment by Yoshax** [comment]
Yeh, all fixed. Repathed some stuff cause of new() issues by overriding. Amended and force pushed to keep it 1 commit.

**Pull request merged**
