### PR TITLE
adds hand-holes to the skyrat/tg ported uniforms

### PR DESCRIPTION
**Pull request by peeesh**
somethin somethin, tgcode doesnt need to manually cut holes for some reason but we do

so i cut holes manually to the best of my ability

should be able to see your hands without needing to wear gloves or whatever now

if you really need clarification check icondiffbot i spent about twenty minutes cutting and pasting

### CODE REVIEW

**Comment by peeesh** [comment]
wait i gotta check the rolled down shit as well FUCK

**Comment by peeesh** [comment]
nevermind theres nothing there we're good

**Comment by KillianKirilenko** [comment]
I assume the hand hole thing is because they do something different with the limb depth for rendering purposes. I did take a quick look at figuring it out myself, but didn't get anywhere unfortunately.

**Comment by Youtubeboy139** [comment]
> I assume the hand hole thing is because they do something different with the limb depth for rendering purposes. I did take a quick look at figuring it out myself, but didn't get anywhere unfortunately.

They calculate hands on a separate layer so when your arm falls off there's not a gap in the uniform

Might be worth looking at porting that here

**Comment by KillianKirilenko** [comment]
> > I assume the hand hole thing is because they do something different with the limb depth for rendering purposes. I did take a quick look at figuring it out myself, but didn't get anywhere unfortunately.
> 
> They calculate hands on a separate layer so when your arm falls off there's not a gap in the uniform
> 
> Might be worth looking at porting that here

That's exactly why I looked into it, yes. But like I said, didn't get anywhere.

**Comment by Youtubeboy139** [comment]
> > > I assume the hand hole thing is because they do something different with the limb depth for rendering purposes. I did take a quick look at figuring it out myself, but didn't get anywhere unfortunately.
> > 
> > 
> > They calculate hands on a separate layer so when your arm falls off there's not a gap in the uniform
> > Might be worth looking at porting that here
> 
> That's exactly why I looked into it, yes. But like I said, didn't get anywhere.

Is there a reason why it didn't go anywhere? Cause I was going to look at it once I got home and I'd rather not waste my time if it's going to be an impossible task

**Comment by KillianKirilenko** [comment]
> > That's exactly why I looked into it, yes. But like I said, didn't get anywhere.
> 
> Is there a reason why it didn't go anywhere? Cause I was going to look at it once I got home and I'd rather not waste my time if it's going to be an impossible task

Does "I have no idea how to start untangling the code" count? I tried looking at a couple of things I figured *might* be relevant, but couldn't really make heads or tails of most of it and wasn't in the right mindset to keep digging either.

**Comment by Youtubeboy139** [comment]
> > > That's exactly why I looked into it, yes. But like I said, didn't get anywhere.
> > 
> > 
> > Is there a reason why it didn't go anywhere? Cause I was going to look at it once I got home and I'd rather not waste my time if it's going to be an impossible task
> 
> Does "I have no idea how to start untangling the code" count? I tried looking at a couple of things I figured _might_ be relevant, but couldn't really make heads or tails of most of it and wasn't in the right mindset to keep digging either.

I'll poke around, I have some general idea on how it works from passing knowledge

**Comment by peeesh** [comment]
> > I assume the hand hole thing is because they do something different with the limb depth for rendering purposes. I did take a quick look at figuring it out myself, but didn't get anywhere unfortunately.
> 
> They calculate hands on a separate layer so when your arm falls off there's not a gap in the uniform
> 
> Might be worth looking at porting that here

my gut feeling is that trying to port that basically means checking every single sprite or bring an entire host of new ones

even then not every sprite can just be yoinked from another codebase, some are unique.

beats me.

**Comment by peeesh** [comment]
wait this is merged

**Pull request merged**
