### PR TITLE
Adds a fish farm.

### PR DESCRIPTION
**Pull request by Ketrai**
Adds a fish farm.

I also went ahead and fixed the virgo4b water to be the fishable water, so now you can swim proper.

 Of course, swimming in the fish farm is discouraged. Fishing is encouraged, the breeder farms keep up with demand.

Ic justification? An alternative way of producing food to allow the station to be more self-sufficient in case of a disconnect with the colony.

How does it work? Sci-fi magic really. Underwater breeder farm for fish and algae, likely. This is more so just so we can actually fish without going into the wilderness. I will likely make phoron water and phoron-themed fish later for a seperate area. Yes, you can find lakes in the wilderness (not even guaranteed). But the complete lack of comms and agressive weather makes it very unrelaxing. And not everyone has access to void suits. Fishing is something fun to do whilst you chat with other crewmembers.

There's no access restriction. Like with the public garden everyone can go fish at their own leisure using the rods provided. You still need chef equipment to prepare the fish correctly.

The fish farm starts with two bass and a salmon. Just to add some flair even when no one's caught any fish yet.

### CODE REVIEW

**Comment by Ketrai** [comment]
Yup, need to use the mapmerge tool. Which I don't know how to use so give me a moment to figure that out or help me figure it out.

**Comment by SpadesNeil** [comment]
The awkward position and shape of this room really bothers me. Why not just use the atrium pond?

**Comment by Ketrai** [comment]
Mainly because everyone and their mother seems to be against the idea of being able to catch actual fish in the atrium pond. Also I dunno. The shape and position doesn't feel that weird if you're walking around in it. It mainly feels weird looking at it. Hardly more awkward than the shuttle bay in my opinion. In any case. I'm all for just having the pond be fishable . But then that implies you can kill the koi and eat them. Which I don't like.

**Comment by Heroman3003** [comment]
Try throwing a fishing rod into any decorative Koi Pond irl and count seconds before you're arrested. Because those ponds are not full-on ecosystems, and fish in them are usually are just equivalent of an open-air fishtank.

Also, inb4 doctors start fishing there just to cook simplest fish dishes and extract carpotoxin, just like happened with carpburgers in cargo crates.

**Comment by Heroman3003** [comment]
Also: Enormouslyt gigantic area with almost every external wall being a window on surface 3, and only a single vent and scrubber. Yep if meteoroid ever hits there, this is not getting cleaned out.

**Comment by Ketrai** [comment]
Meteor doesn't happen often. and there's a lot of places for it to hit. I could always add some large scrubbers, if that's your complaint. This is just the same as a "what if the atrium got hit by a meteor" case at this point.

By the way, the fish you can catch don't contain any carptoxin. they contain some kind of neurotoxin. Not useful for medical, and you have to be a chef to safely prepare them.

**Comment by Ketrai** [comment]
See here for more details on fishing https://github.com/PolarisSS13/Polaris/pull/6113

- Real fish meat. Still toxic, but not carpotoxic.

All fish caught by fishing have neurotoxic protein instead. It's neutralized either by the succ from the chemmaster, or by injecting anti-toxin. One unit is generally enough to neutralize it in any fish. It turns into normal protein.

**Comment by Ketrai** [comment]
uhh, wtf travis? I just added those tiles that you're erroring on :V

**Comment by TheFurryFeline** [comment]
If you haven't already, shift the chairs and tables over one space near the entrance?

**Comment by Ketrai** [comment]
I moved the fishing area to tether level 2, removed the dome, and added fishable water to virgo4b beach. 

Screenshots updated

**Comment by Ketrai** [comment]
https://cdn.discordapp.com/attachments/187013248309002240/584845242356858908/unknown.png

I will eventually sprite in a shoreline with waves and beach sand underground.

**Comment by Pear120** [comment]
This shit makes my lamprey moist.
More recreational stuff like this is always appreciated, and I love the cave feel, and the fishing catwalk.
I'd personally say slap some walls on either side of that southern maint door, and walls under each lightbulb, but that's just minor stuff.

**Comment by Novacat** [comment]
Can you make the shallows a bit wider?

**Comment by Ketrai** [comment]
I already made the shallows a bit wider for it to look better. Just haven't updated the screenshot for it yet. I also noticed I have a station intercom to fix. And well I should add one to the place as well.

**Comment by Heroman3003** [comment]
You should also prolly delete .before files. There is no need for them anymore.

**Comment by Ketrai** [comment]
There, spacious shallows now.

**Comment by SpadesNeil** [comment]
This new setup is much nicer looking.

**Pull request merged**
