### PR TITLE
Removes hotfood vendors from station spawning

### PR DESCRIPTION
**Pull request by Heroman3003**
Its a vendor with poisoned food originally meant for spawning in pois with 'expired food' meme. It also randomly had carpotoxin aparently?! Basically makes it not appear in station spawning pool, and removes cartridges for it from cargo.

### CODE REVIEW

**Comment by Cameron653** [comment]
_nooooo how am I supposed to get my carpotoxin and zombiepoweder now!!!_

**Review by Cameron653 — APPROVED** [review]

**Comment by BonniePandora** [comment]
Isn't there a version of the hot food vendor that isn't like
Ancient & lethal? 
Why not swap this not-great one out for that instead, given it only really spawns at... the V2 surface outpost and the fuel depot, currently.

**Comment by Heroman3003** [comment]
> Isn't there a version of the hot food vendor that isn't like Ancient & lethal? Why not swap this not-great one out for that instead, given it only really spawns at... the V2 surface outpost and the fuel depot, currently.



> Isn't there a version of the hot food vendor that isn't like Ancient & lethal? Why not swap this not-great one out for that instead, given it only really spawns at... the V2 surface outpost and the fuel depot, currently.

Those are event machines for use in specific places or events. Also its not 'same version' really, its jsut a machine full of fastfood for free.

**Comment by Cafaling** [comment]
Kinda funny vendor, but probably for the best that it goes.

**Pull request merged**
