### PR TITLE
adds snail taurs v2

### PR DESCRIPTION
**Pull request by Belsima**
Every time I read vore porn, I envy the person getting consumed by the tentacle like object. Getting molested and having their sensitive spots touched and tickled by smaller slimy tentacles.

So every now and then, early in the morning while the grass is starting to get dew, I go out and grab a lot of snails.

Like, a lot. I collect as much as I can for the months and put them in a bio I have in my garage that was built for snails.

Then, when I'm feeling a little adventurous, I grab as much snails as I can, put them in a sleeping bag, and snuggle up in there with them.

Sure, it kills some of them, but it's _so_ worth it. I put on some headphones with some consumption (ASMR) sounds effects and pretend I'm getting eaten alive.

The feel of snails crawling across my body, slime and mucus sliding and oozing off my naked body gets me riled up. Nothing like snails tickling your armpits and mounting your nipples while making your anus pucker as they wipe your ass for you.

### CODE REVIEW

**Comment by Renkindle** [comment]
You're actually doing it, the absolute madman

**Comment by kcin2001** [comment]
you act like he didnt have it before

**Comment by Belsima** [comment]
she
also i fixed it this time

**Comment by Screemonster** [comment]
No.

**Pull request closed without merging**
