### PR TITLE
Some Asteroid Fixes

### PR DESCRIPTION
**Pull request by Novacat**
- Replaces Nanomed Pluses with more oxygen lockers.
- Fixes Excursion Shuttle Disposals
- Adds a table to Excursion Shuttle Cockpit

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Aheeeeeem, didn't notice this while I was doing #10420. Think ya can slap the changes into here too?

**Comment by Novacat** [comment]
I am fairly certain that the two PRs will not conflict, so I do not think that will be necessary.

**Comment by TheFurryFeline** [comment]
They both touch the same file, however.

**Comment by Novacat** [comment]
Different parts.

**Comment by TheFurryFeline** [comment]
Someday, I'll figure out how you can tell that a conflict won't happen with these simultaneous PRs 🤔

**Pull request merged**
