### PR TITLE
New ore chunk sprites, ore box sprite

### PR DESCRIPTION
**Pull request by Arokha**
Makes the ore have more colors, more shading. Removes things like the coal ore which is just a solid black blob.

### CODE REVIEW

**Comment by Rykka-Stormheart** [comment]
I gotta say, I like all of these except the phoron one :c

**Comment by Arokha** [comment]
Why not that one? I think the crystal looks neat

**Comment by Rykka-Stormheart** [comment]
> Why not that one? I think the crystal looks neat

The brighter pink-ish color fits the current phoron sheets really well. Unless you're planning on updating those too, the dull-pink crystal doesn't look as... vibrant as the current phoron ore. The current ore does look a little out of place compared to the new sprites, but the new phoron crystal feels more 'dull'. Perhaps a brighter pink on the ore crystal bits itself might help?

**Comment by Arokha** [comment]
Well it does make a bit of sense that the ore is more dull than the refined counterpart. I mean you just dug it out of the ground.

**Comment by KasparoVy** [comment]
These sprites look dope!

**Pull request merged**
