### PR TITLE
TGUI Vore Panel

### PR DESCRIPTION
**Pull request by ShadowLarkens**
Makes the Inside! panel TGUI. Mew~

### CODE REVIEW

**Comment by KasparoVy** [comment]
Lmfao, that's awesome. Nicely done

**Comment by Heroman3003** [comment]
I feel like wording on the vore prefs could use being more consistant and/or reordered a little. Like Digestion, Absorption and Healbelly prefs all relate to different belly modes, but are worded differently and are not in a row. And generally language could be more clear, like "mobs allowed to eat" in prefs, or "digest brute/burn".

Also that's more of a minor personal thing, but I feel like the order of the controls stuff has been a little messed up for a while now, and that sound-related settings got split up by others. So fleshy belly and Internal loop are not next to eject/swallow noise settings, while they probably should've been.

**Comment by Wickedtemp** [comment]
Do we know for a fact, 100%, that updating to this won't delete any existing saved data for the current panel

**Comment by KasparoVy** [comment]
@Wickedtemp With the massive detail some people put into their characters & vorebellies I highly recommend backing up everything to formatted txt files and placing 0 trust in the system

**Comment by ShadowLarkens** [comment]
@Wickedtemp 100% yes, it touches absolutely nothing but the front end, it's not possible for this to erase your vore settings; though I'll say Kasparov gives good advice in general.

**Comment by KasparoVy** [comment]
OH SHIT TOOLTIPS

**Pull request merged**
