### PR TITLE
[Bug/graphics fix] Breath mask and cigarettes fix

### PR DESCRIPTION
**Pull request by radar651**
Fixes breath mask for Vulpkanin and fixes several species lacking cigarettes. Akula, Trajaran, Unathi and Vulpkanin now have missing assets in their sprite sheets [mask.dmi] to show cigarettes, cigars, pipes, and in the case of Vulpkanin, breath mask pulled down. This has kind of bugged me for a long time and was a simple fix. Mostly fixing names and moving things over to the sheets. Joints were also missing from the sheets so they have been added as well.

### CODE REVIEW

**Comment by radar651** [comment]
I'll just remove those updates then to those two

**Comment by Rykka-Stormheart** [comment]
> I'll just remove those updates then to those two

I can PR the changes up to Polaris, or you can, it's pretty easy and it'd save the icon issues <3

**Comment by radar651** [comment]
> 
> 
> > I'll just remove those updates then to those two
> 
> I can PR the changes up to Polaris, or you can, it's pretty easy and it'd save the icon issues <3

If you want to go ahead

**Comment by Rykka-Stormheart** [comment]
PR created

**Comment by Greenjoe12345** [comment]
Teshari are missing sprites for E-cigs, if that is something you would want to fix too

**Comment by radar651** [comment]
I wasn't even aware of e-cigs so it kind of wasn't a big deal worry.

**Comment by Greenjoe12345** [comment]
They're a thing on Polaris so I would imagine they would have been ported down here too, still, tesh don't have a sprite for them

**Comment by radar651** [comment]
Hmm. Maybe in a future fix but I am more consecrated on what Virgo uses.

**Comment by Greenjoe12345** [comment]
Does Virgo not have e-cigs then?

**Comment by radar651** [comment]
As far as I know, no. If we do we don't use them at all.

**Comment by KillianKirilenko** [comment]
Should mark this as linked to #6692.

**Comment by Greenjoe12345** [comment]
hm, looking at the loadout you don't have them there anyway

**Comment by KasparoVy** [comment]
Smoke up!

**Pull request closed without merging**
