### PR TITLE
Overhauls First Aid Kits

### PR DESCRIPTION
**Pull request by Novacat**
- Refactors First aid kits to be mostly autoinjector and pill based. No syringes, no health analyzers, just autoinjectors and pills.
Regular First Aid Kit: 4x Gauze, 2x Ointment, 1x Paracetamol pill bottle
Toxin First Aid Kit: 1x Dylovene Pill Bottle, 4x Dylovene Autoinjectors, 2x Hyronalin autoinjectors
Burn First Aid Kit: 1x Kelotane pill bottle, 4x Dermaline/Leporazine autoinjectors, 2x Ointment.
Oxy First Aid Kit: 4x Dexalin Plus autoinjectors, 1x Inaprovaline pill bottle, 1x Iron pill bottle, 1x Dexalin Pill Bottle
Adv First Aid Kit: Replaces Autoinjector with Assorted Pill bottle (3 Inaprov, 3 Dylovene, 2 Iron, 2 Tramadol, 3 Hyronalin, 1 Spaceacillin pills)
- Buffs default pill bottle contents. This narrows the effectiveness between autogenerated pills and pill bottles, and those brewed up by players.
- Splits Miner autoinjector into four seperate autoinjectors, one for each damage type. Reduces the price in the mining/exploration vendors.
- Tweaks Pill contents for a bit better consistency. Biggest change is that dexalin pills are 7.5u each.
- Changes Vermicetol chemical color to something more reddish.
- Overhauls Internals closet, reduced O2 kits from them, adds more emergency spacesuits.
- Removes Organ Kits, Combat First Aid Kits now have a pill bottle with assorted organ repair pills.
- Surgical kits now have a regular health analyzer, and can hold health analyzers.

### CODE REVIEW

**Comment by Wickedtemp** [comment]
...why remove the health analyzer? 

And why would you remove the emergency hypoxia kits from the *emergency O2 lockers*

Whats the reasoning?

**Comment by Wickedtemp** [comment]
Im going to need an actual pc to type out stuff about this. Burn kits shouldnt have *dermaline*, and they *need* ointment else you get infections. O2 kits don't need dexalin plus, standard dexalin is fine for first aid. O2 kits need inaprovaline. 

I'll write more later

**Comment by Novacat** [comment]
Dermaline and Dexalin Plus are only found in autoinjectors, and in extremely small quantities due to autoinjectors having only 5u of reagent. That should be fine.

As for the emergency lockers, ideally I would like the emergency lockers to have little first aid packets that Baystation has, as an endgoal. The main reason I removed the oxy kits from the O2 lockers is to make the Oxy kits a little more uncommon.

The health analyzers I removed mostly because I feel Health Analyzers generally should be a bit rarer outside of Medical itself.

**Comment by Wickedtemp** [comment]
On a proper computer with an actual keyboard, so I can actually type stuff out. 

As a general thing, the kits need health analyzers. If you have reason to get out one of the first-aid kits, you're going to need an analyzer to know how severe the situation is. I'm fairly sure that health analyzers existing in the kits isn't a huge deal when it comes to "outside of Medbay" because I've mained the department for nearly six years and I can't think of a single instance where the existence of a health analyzer caused issues. The only kits, as far as I'm aware, that are found in any meaningful number outside of Medbay are going to be the O2 kits (which should remain in the lockers) and the basic first aid kit, which according to the most recent edit is keeping its analyzer, so keeping the others really isn't going to matter anyway. The only kit that doesn't need an analyzer is the advanced-aid kit. 

Now going by each kit:

- Regular First Aid Kit: 1x Health Analyzer, 3x Gauze, 2x Ointment, 1x Paracetamol pill bottle
This is mostly fine. It's honestly a toss-up between an autoinjector and the paracetamol pills.

-Toxin First Aid Kit: 1x Dylovene Pill Bottle, 6x Dylovene Autoinjectors
Needs a health analyzer. I'd recommend cutting the dylo injectors to 3, and have the analyzer, and 2 hyronalin injectors.

-Burn First Aid Kit: 1x Kelotane pill bottle, 6x Dermaline autoinjectors.
Dermaline is a bit more than 'first-aid'. The injectors should have kelotane at the most. I'd recommend 2 kelotane injectors, health analyzer, and 3 stacks of ointment. The ointment is **an absolute must** in this kit. You cannot disinfect burns without it, and you can literally use it to heal burns. 

-Oxy First Aid Kit: 4x Dexalin Plus autoinjectors, 1x Inaprovaline pill bottle, 1x Iron pill bottle, 1x Dexalin Pill Bottle
Needs health analyzer. You can cut the dexalin-plus injectors to make room for it. A standard autoinjector would also be beneficial, since it lowers damage done by bloodloss (as well as the oxy from crit) and you have iron pills in there for bloodloss.  When it comes to first-aid, you can get somebody stable without the dex-plus, so I think its more of an ActualMedicalThing than an EmergencyKit thing. 

-Adv First Aid Kit: Replaces Autoinjector with Assorted Pill bottle (3 Inaprov, 3 Dylovene, 2 Iron, 2 Tramadol, 3 Hyronalin, 1 Spaceacillin pills)
Mostly fine. Really a tossup between the pills and the inaprov injector, specially because these are really only in Medbay and if a Dr wants to swap theirs for something else, they can already do that ezpz.

-Buffs default pill bottle contents. This narrows the effectiveness between autogenerated pills and pill bottles, and those brewed up by players.
Looks mostly fine. I'd recommend making sure that the dosage is listed somewhere on the pill, and/or pill bottle, whether in the name or examine text. 

- Overhauls Internals closet, removed O2 kits from them, adds more emergency spacesuits.
Put the kits back and its fine. If there's a big enough breach that people need to resort to the softsuits, then chances are they're going to need these to spawn as-normal. It's not like they really spawn anywhere else other than the O2 lockers and Medbay. The primary purpose in the lockers is for lung ruptures and lose.breath, which stacks and can continue to cause you to suffocate even if you have an air source. On a side note make dexalin-plus set lose.breath to zero or something so that doesn't happen anymore kthankx.






-

**Comment by Novacat** [comment]
The main reason I am hesitant to put health analyzers in everything, is that more often than not, you can figure out what is wrong with someone just by symptoms. Vomiting? Toxins. Gasping? Oxy. Brute and Burns are pretty easy, too. Considering these are first aid kits, basically the idea is for someone to grab something out of it and use it on the injured while waiting for medical to come help. The reason why I went autoinjector heavy is because autoinjectors can be used through space suits/void suits, which might be needed (especially in a breach)!

As for Burn kits, ill relent and toss one ointment into it, but the idea I am pushing is to make white kits a bit more the go-to kit for ointment, gauze, and the health analyzer.

I will return O2 kits to the emergency lockers, but they are still going to be a lot rarer on account of the buffed contents.

**Comment by Wickedtemp** [comment]
No, dude. Put more ointment in the burn-kit, 3 minimum. It's literally a basic staple of burn injuries. Gauze/Ointment work differently, and perform different tasks and fulfill different roles than bicaridine, kelotane and dermaline, and you know this. This is especially important for burns specifically, due to the higher infection risk, and the fact that burns tend to be more spread-out.

This plays into the "oh just ask them where it hurts", because for someone with burns,  the answer is "everywhere" or at least several areas. A single pack of ointment has 10 uses, it's just not sufficient.

And if you were going for "accessibility through suits", you wouldn't even need injectors for that. Syringes go through void and hardsuits. In addition if you did want to improve accessibility for people in suits, you would've just kept the O2 kits in the lockers. With the suits. To be used in instances where everybody would have a suit.

For the burn kit specifically, you pretty much made it into just another bottle of chems instead of actual first-aid. First-aid shouldn't be reagent-heavy for brute/burn, and for your burn kit, that's literally all that's there. I'd like to think you'd trust me on this, given my experience.

**Comment by Novacat** [comment]
There already is ointment in the white first aid kits, my point was that you can use them. The reason I opted for one ointment in the burn kit was so that if someone had it in their hand while treating someone, they can grab it and treat them. Otherwise there is no point in having a regular first aid kit, and might as well re purpose it into a trauma kit or something.

**Comment by Wickedtemp** [comment]
The white kits are primarily for brute trauma. This is why they have more gauze than ointment, and why they have both. Cuts can get infected, but bruises have a lower risk, so the kits inventory reflects that. 

The burn first-aid kits are for treating burns, specifically, which is why they lack gauze since gauze is only used to stop bleeding wounds, and have a few kelotane pills in addition to the ointment that is used to heal burn damage and salve to prevent infection. That's literally what these kits are for. It doesn't take away AT ALL from the brute first-aid kits, evidence of this is the fact that the burn first-aid kits have always had ointment in them and it hasn't at all harmed the brute first-aid kits usage in any way, shape or form.

The reason we don't repurpose the brute first-aid kit into something else is that there's a specific niche for it as it is, and it fulfills that niche relatively decently.

**Comment by Novacat** [comment]
The amount of ointment used tends to be highly variable. Someone who zapped their hand off (at least until zaps were refactored) would have a ton of burn in one bodypart, but just one bodypart which means one unit of ointment gets used and that is it, but you still need a significant amount of burn medicine to remove the damage. Removing the damage being important because burns can still get infected even after they have been salved. You have to get that burn healed as soon as possible.

The reason the white kit has more gauze than ointment is because gauze is used per wound, so you can very easily use multiple gauze per body part. While ointment will always treat the bodypart regardless of how many burns that bodypart has. All things equal, you will go through gauze much quicker than ointment.

**Comment by Wickedtemp** [comment]
...yes, so you can see why having enough burn medicine to treat 15+ people, while only having enough ointment to disinfect 10 limbs max, is unbalanced, right?

**Comment by Novacat** [comment]
You should also count the 2 ointment in the white first aid kit, so, thirty limbs, which is much better.

**Comment by Wickedtemp** [comment]
Are you going to make sure that every single burn kit has a brute kit adjacent to it in every single instance?

**Comment by Novacat** [comment]
So far, it is already the case that if there is a fire first aid kit, the other three non-adv first aid kits are close by! So nothing would have to change there at all. The only first aid kits that can be found on their own are regular first aid Kits and oxygen first aid kits, and the latter is entirely because of the internal locker spawn.

**Comment by Wickedtemp** [comment]
...i mean we have an entire job slot dedicated to literally only that

**Comment by Novacat** [comment]
Chemistry is not always available, and, the whole purpose of first aid kits is to provide a stopgap, for both medical and non-medical, until chemistry can finish making medicines. Chemistry is still undoubtedly superior, especially in delivery mechanisms, with hyposprays, syringe cases, and 60u bottles of medicine. But this provides a useful stopgap in those emergencies where chemistry is not available.

**Comment by Wickedtemp** [comment]
Yeh, and first aid kits already had that. If that was the goal, just increasing the number of pills wouldve been all that was needed.

**Comment by Screemonster** [comment]
On the arguments for putting health analysers in some of the kits, the reason white kits don't really need them is that there's nothing in the white kit that can treat the things that a health analyser would tell you. Like, analyser says someone's got 30 brute? Who cares, shiftclicking them tells you they're bleeding from the arm so you put bandages on their arm.

Now I'm wondering how viable it'd be for a FUTURE FEATURE to make a cut-down version of the analyser for toxins and oxyloss. It's _first aid_, stuff for regular crew to grab people and stop them dying before the actual medical personnel arrive on the scene, or else patching up boo-boos that aren't worth pulling medbay out of a scene.

So a quick toxins detector that just confirms "no toxins detected" "light toxins detected" "HEAVY TOXINS DETECTED, SEEK URGENT MEDICAL INTERVENTION" or something for the toxins kit, since all you really need is a y/n on whether it's worth using the contents of said kit on people.

**Comment by Natje0** [comment]
Everything I didn't like has been changed! I think it's all good now.

 I VERY much like the hyronalin in the tox kits.
 The removal of health scanners I thought silly at first, but my opinion was changed. There's many ways to gauge peoples health besides them (unless they're fully dressed and burned atleast) and I'd love to see a simplified version as Scree speaks of.
I meant to post this hours ago but I got distracted and forgot, woops

**Pull request merged**
