### PR TITLE
Adds 10 new UD POI's

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
POI's listed as follows:
Abandoned Outpost
~~Broken Engine~~  (Commented out pending radiation rework)
Mimicry
Old Drone Hive
Phoron Rat Den
Puzzle Corridor
~~Rad Threat~~  (Commented out pending radiation rework)
Rykka's Easter Egg
Spider Nest
Subterranean Lake
Tree Shrine
Wolf Den

Screenshots: https://imgur.com/a/gpzJ295

### CODE REVIEW

**Comment by Heroman3003** [comment]
Abandoned Outpost: I dunno about the mechwrecks present there, as they are combat mechs and provide loot completely unrelated to mining as a result

Broken Engine and Rad Threat: Mining already struggles quite a bit against radiation as a whole, I dunno about adding even more issues related to that to just blacklist them from ever entering an area

Rykka Easter Egg: The doggo will die of atmos before any miner will get to go down there

Wolf Den: pretty sure wolves and otie will attempt to fight. Although I'm betting on otie due to, again, wolves just dying of atmos before anything happens. Also uncontained artifact is uhhh.. Same issue as radiation, mining is pretty ill-equipped to deal with it, and depending on RNG it might end up just being big area denial

Generally applicable to all: I didn't see any new /virgo3b turfs defined, but definitely saw some new turfs used. That will probably result in any new tiles having A) active edges and B) phoron overlay all over them, unlike normal tiles in the Underdark

**Comment by Rykka-Stormheart** [comment]
> Abandoned Outpost: I dunno about the mechwrecks present there, as they are combat mechs and provide loot completely unrelated to mining as a result

You're not clearing the outpost as a solo miner. It's not a huge deal, you need a team to clear the damn thing anyways.

> Broken Engine and Rad Threat: Mining already struggles quite a bit against radiation as a whole, I dunno about adding even more issues related to that to just blacklist them from ever entering an area

Mining has geiger counters, and the voidsuits are rad-insulated.

> Rykka Easter Egg: The doggo will die of atmos before any miner will get to go down there

...how do I fix that? :c

> Wolf Den: pretty sure wolves and otie will attempt to fight. Although I'm betting on otie due to, again, wolves just dying of atmos before anything happens. Also uncontained artifact is uhhh.. Same issue as radiation, mining is pretty ill-equipped to deal with it, and depending on RNG it might end up just being big area denial

Regarding RNG, artifact, and such, not a huge deal to me, imo. That's part of the risk. I intend to leave it in and judge how it goes. Do remember if it's too much, we can tweak, reduce, or eliminate it later, yeah?

> Generally applicable to all: I didn't see any new /virgo3b turfs defined, but definitely saw some new turfs used. That will probably result in any new tiles having A) active edges and B) phoron overlay all over them, unlike normal tiles in the Underdark

All turfs are v3b tiles.

**Comment by Heroman3003** [comment]
> You're not clearing the outpost as a solo miner. It's not a huge deal, you need a team to clear the damn thing anyways.

Well, I am saying that on assumption that Underdark is still meant to be something doable as a singular person, as it was when it was begun and when first PoIs were introduced, with all threats being meant to be handlable by a single miner who just happened upon the PoI while digging ores.

> Mining has geiger counters, and the voidsuits are rad-insulated

Geiger counters don't help much beyond just allowing to know the bounds of the zone thats as good as un-enterable, and the shielding on suits is only partial and will not actually protect from radiation. Even suit from vendor doesn't have full protection from it. Radiation sources are a dead zone.

> ...how do I fix that? :c

Need to define mobs properly, with proper stats to accomodate virgo3b survival

> Regarding RNG, artifact, and such, not a huge deal to me, imo. That's part of the risk. I intend to leave it in and judge how it goes. Do remember if it's too much, we can tweak, reduce, or eliminate it later, yeah?

You do you. But artifact RNG can be absolute bitch, as practice showed

> All turfs are v3b tiles.

Both tree shrine and lake use non-v3b tiles

**Comment by Rykka-Stormheart** [comment]
> > You're not clearing the outpost as a solo miner. It's not a huge deal, you need a team to clear the damn thing anyways.
> 
> Well, I am saying that on assumption that Underdark is still meant to be something doable as a singular person, as it was meant to be when it first begun and when first PoIs were introduced, with all threats being meant to be handlable by a single miner who just happened upon the PoI while digging ores.

I think having the one large, extremely rare point won't hurt. You'll know to avoid it if you see it from experience.
 
> > Mining has geiger counters, and the voidsuits are rad-insulated
> 
> Geiger counters don't help much beyond just allowing to know the bounds of the zone thats as good as un-enterable, and the shielding on suits is only partial and will not actually protect from radiation. Even suit from vendor doesn't have full protection from it. Radiation sources are a dead zone.
> 
> > ...how do I fix that? :c
> 
> Need to define mobs properly, with proper stats to accomodate virgo3b survival

Where do I define the mob? Or is there a var I can change on the existing mob?
 
> > Regarding RNG, artifact, and such, not a huge deal to me, imo. That's part of the risk. I intend to leave it in and judge how it goes. Do remember if it's too much, we can tweak, reduce, or eliminate it later, yeah?
> 
> You do you. But artifact RNG can be absolute bitch, as practice showed

> > All turfs are v3b tiles.
> 
> Both tree shrine and lake use non-v3b tiles

That's fine - they're simply there to look pretty. So what if they have a slight purple effect on them?

**Comment by Heroman3003** [comment]
> I think having the one large, extremely rare point won't hurt. You'll know to avoid it if you see it from experience.

Another reminder that point cost does not actually affect rarity of PoIs as much as it may seem. It primarily determines how much 'worth' is the PoI's contents, but only really secondarily how often it appears.

> Where do I define the mob? Or is there a var I can change on the existing mob?

There is a file with all Underdark things separately defined where you can put /3b versions of mobs. As for var, its not a single one but half a dozen vars that determine atmos suspectibility. Look it up in existing mobs

> That's fine - they're simply there to look pretty. So what if they have a slight purple effect on them?

Active edges are bad and should be avoided at all costs. To note what an active edge is: When roundstart atmos on two adjacent atmos-passing tiles is different, resulting in before-round gas movements. That should not be happening. Purple gas effect may be fine, but the fact that those tiles will contain indoor air rather than 3b atmosphere isn't.

**Comment by Rykka-Stormheart** [comment]
> > I think having the one large, extremely rare point won't hurt. You'll know to avoid it if you see it from experience.
> 
> Another reminder that point cost does not actually affect rarity of PoIs as much as it may seem. It primarily determines how much 'worth' is the PoI's contents, but only really secondarily how often it appears.

Again, I'm leaving as-is and waiting to see how it goes/etc.

> > Where do I define the mob? Or is there a var I can change on the existing mob?
> 
> There is a file with all Underdark things separately defined where you can put /3b versions of mobs. As for var, its not a single one but half a dozen vars that determine atmos suspectibility. Look it up in existing mobs
> 
> > That's fine - they're simply there to look pretty. So what if they have a slight purple effect on them?
> 
> Active edges are bad and should be avoided at all costs. To note what an active edge is: When roundstart atmos on two adjacent atmos-passing tiles is different, resulting in before-round gas movements. That should not be happening. Purple gas effect may be fine, but the fact that those tiles will contain indoor air rather than 3b atmosphere isn't.

Tree Shrine corrected, subt lake is using water tiles - there's no such v3b tile for water.

**Comment by Rykka-Stormheart** [comment]
> Wolf Den: pretty sure wolves and otie will attempt to fight.

This is also fixed, phoron wolves are set to "underdark" faction, as is the otie I var-edited

**Comment by Heroman3003** [comment]
You can easily create new V3B tiles based off of existing ones without much hassle by using same method as demonstrated at the very bottom of Underdark things file.

**Comment by Novacat** [comment]
My first immediate concern is that, the Underdark is meant to be soloable by Miners. Underdark POIs are not supposed to kick your ass like Exploration ones, and a lot of the ones here have... quite a few mobs, which makes me concerned in regards to that.

**Comment by Rykka-Stormheart** [comment]
> My first immediate concern is that, the Underdark is meant to be soloable by Miners. Underdark POIs are not supposed to kick your ass like Exploration ones, and a lot of the ones here have... quite a few mobs, which makes me concerned in regards to that.

Plenty of UD spawns already have 3+ mobs - the "drone swarm" ones for instance are just a 'group' of very small "viscerator-alike" drones, for instance. The mob refactor should help massively, as mobs cannot attack anywhere near as fast anymore.

**Comment by Screemonster** [comment]
Yeah, underdark is a solo area which makes me wary of putting anything in there that's intended for a team.

Also radiation fucking sucks. Environmental hazards in general under our medical system tend to be a case of "either you gear up to be totally immune, or else you either die or have to stop what you're doing to seek treatment". There's no such thing as a safe threshold where you can limit your exposure to avoid damage, you're either immune or you're not. And miners being out of the station, as far from medbay as you can get, and usually solo, increases the suck factor.

Exploration PoIs? Sure. Mining? Nah.

**Comment by Rykka-Stormheart** [comment]
> Yeah, underdark is a solo area which makes me wary of putting anything in there that's intended for a team.
> 
> Also radiation fucking sucks. Environmental hazards in general under our medical system tend to be a case of "either you gear up to be totally immune, or else you either die or have to stop what you're doing to seek treatment". There's no such thing as a safe threshold where you can limit your exposure to avoid damage, you're either immune or you're not. And miners being out of the station, as far from medbay as you can get, and usually solo, increases the suck factor.
> 
> Exploration PoIs? Sure. Mining? Nah.

Concerns addressed

**Pull request merged**
