### PR TITLE
Adds Sergal, Akula & Naga EVA Rig Sprites

### PR DESCRIPTION
**Pull request by KasparoVy**
Copies Unathi EVA rig helmet sprites per standard.
This also fixes an issue with the Naga surgeon apron. I mis-clicked in Dream Maker at some point and made it animated with one blank frame, so the thing was seizure-inducing. Hilarious, but unintentionally fucked up. My bad.

virgo ss13 sergal and akula EVA hardsuit sprites 20200530
virgo ss13 naga EVA hardsuit 20200531

### CODE REVIEW

**Comment by KasparoVy** [comment]
Good borg.

**Comment by KillianKirilenko** [comment]
Nice work. The shading on the serg tails always threw me off and I could never quite get them to look right with my reworks.

**Comment by KasparoVy** [comment]
DNM - adding Naga EVA suit as well

@KillianKirilenko What I ended up doing here was ripping the tailsprite off another suit (I think it was the industrial hardsuit), cutting it into 2 sections (dark + brassy/light) and then adjusting hue/sat/lum to get the desired colours. I referenced other hardsuits for concept and voila!

The only 'custom' work I had to do was for a few certain pixels where it was obvious the light/dark colours blended, and for that I just did some shit and made it work

As for the Akula, it's the exact same tail as on the engineer voidsuit! It's copy-pasted across a lot of other sprites so I adjusted the suit as required, fit the tail on and done.

A lot of the spritework for the Akula tail is covered because the control module (backpack part with the glowy lights) covers the suit & the 'tail' is a part of the suit.

**Comment by KillianKirilenko** [comment]
Makes sense. I usually cut a sample tail off another suit, then paste it onto the new suit and paint over it, sampling the colors off the suit itself. The number of shades on some sergal suit tails tends to throw me off though, so the end result often never looks entirely satisfactory to me.

**Comment by KasparoVy** [comment]
I went ahead and banged it out anyway. This is good to go - even the bloody snakes get EVA rigs.

**Comment by Arokha** [comment]
Neato :0

**Pull request merged**
