### PR TITLE
DMCA FREE speech bubbles

### PR DESCRIPTION
**Pull request by crabcube**
the first one was my test but I'm a total fool, so it has been erased, but here is the bubbles i did finish in the meantime! (now not comically large). Apologies for the blood pressure spike earlier!

currently in the list is a rooster and a peacock but those are proving very hard to do in such a tiny space.

### CODE REVIEW

**Comment by crabcube** [comment]
image

**Comment by ShadowLarkens** [comment]
so, you didn't update this branch while you were working, which means you deleted the thinking states from my PR in this commit

**Comment by crabcube** [comment]
> so, you didn't update this branch while you were working, which means you deleted the thinking states from my PR in this commit

Guh- DID I? I pushed the stage commit button like i did before in the web editor. How do I Undo that?

**Comment by crabcube** [comment]
image
This is how it looks on my end- What did i break? ;w;

**Comment by Kashargul** [comment]
grafik

You used an outdated DMI. Pull the file directly from master. Add your new ones. THEY also will need thinking states. Then overwrite the current DMI with the latest one.

**Comment by crabcube** [comment]
> Image from icon diff bot
> 
> You used an outdated DMI. Pull the file directly from master. Add your new ones. THEY also will need thinking states. Then overwrite the current DMI with the latest one.

thanks! I will start on that now then.

**Comment by Heroman3003** [comment]
Tell me if this is still worked on, closing as stale for now

**Pull request closed without merging**
