### PR TITLE
Spider race & modifications!

### PR DESCRIPTION
**Pull request by Cameron653**
Sprites made by: ArgobargSoup
Lore made by: Gazer
- Adds Vasilissan race
- Adds Vasilissan race "legs" in the wings selection.
- Edits Gazer eyestalks
- Allows people to change custom_species name if they want to choose a stock race (Promethean, spider, etc)
- Allows stock spider race to create web bindings. (Pretty much a fancy suit that does nothing but look nice.)
- Allows people to select their blood color without having to be a custom race.
- Adds xenochimeras to suit cycler, along with spiders. (Not sure what issue the xenochimeras one was.)

Vasilissan INFO:
- 20% resistant to brute damage.
- 15% more vulnerable to fire damage.
- Takes no cold damage. Instead, slowly gets weakened and passes out in the extreme cold.
- Has extremely good dark vision.
- Has web-bindings proc, allowing them to make the web bindings suit.
Photo: http://i.imgur.com/dHEGbmg.png

### CODE REVIEW

**Comment by Cameron653** [comment]
DNM need to edit a few things.

**Comment by SpadesNeil** [comment]
Lore is needed on the wiki.

**Comment by LiquidFirefly** [comment]
Added!

**Comment by Cameron653** [comment]
Accidentally left them as NO_SCAN. Went ahead and fixed that.

**Comment by Cameron653** [comment]
This should be ready for merge. Did some more testing and couldn't find any errors.

**Pull request merged**
