### PR TITLE
Add New Dogborg model for Sec

### PR DESCRIPTION
**Pull request by Suhayll**
sec borg
Adds a new dogborg sprite skin for security.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
>(Static)

Eh?

**Comment by Suhayll** [comment]
What?

**Comment by Draycu** [comment]
Ah, I believe it would replace the current old static non-animated sprite for the K9 module, right?

**Comment by kcin2001** [comment]
No its a new sprite completely

**Comment by Draycu** [comment]
Okay, I see that now!  Saw reskin and thought that meant replace at first.  I would be happy to use it as a new K9 skin!

**Comment by Suhayll** [comment]
My bad on a poor title.

**Comment by kcin2001** [comment]
Dont know why ace posted what he did

**Comment by kcin2001** [comment]
Theres no better way to put it that i know of

**Comment by Suhayll** [comment]
Renamed title to something more clear.

**Comment by kcin2001** [comment]
It was done so we dont overwrite it again @jakksergal

**Pull request merged**
