### PR TITLE
better glowing eyes

### PR DESCRIPTION
**Pull request by Seris02**
so they stop showing through glasses n shit, thanks

### CODE REVIEW

**Comment by Very-Soft** [comment]
did you actually test this and see to it that it actually works? I went to test it and it doesn't appear to work.
image

**Comment by Seris02** [comment]
> did you actually test this and see to it that it actually works? I went to test it and it doesn't appear to work. image

I did, yeah, lemme see if I can see what's going on

**Comment by KillianKirilenko** [comment]
> so they stop showing through glasses n shit, thanks

What if we *want* them to show through glasses, eh? At the very least it'd be nice if they could still overlay transparent glasses. Sunglasses ok, probably not much sense in glowing behind those, but someone might want that too.

**Comment by Runa-Dacino** [comment]
> > so they stop showing through glasses n shit, thanks
> 
> What if we _want_ them to show through glasses, eh? At the very least it'd be nice if they could still overlay transparent glasses. Sunglasses ok, probably not much sense in glowing behind those, but someone might want that too.

I echo this.

It should be an option either for glowing eyes 
OR
Be sth that checks if the glasses are sunglasses or normal ones.

Not sure how you'd make sure AR glasses accomodate both.

**Comment by KillianKirilenko** [comment]
> I echo this.
> 
> It should be an option either for glowing eyes OR Be sth that checks if the glasses are sunglasses or normal ones.
> 
> Not sure how you'd make sure AR glasses accomodate both.

I think the simpliest way would be to make it a cycle switch like ghost-darkness. `Off->On->Overlay Glasses->Overlay All Eyewear->Off->...`

**Comment by Seris02** [comment]
not ready for merging by the way, haven't gotten around to testing what the issue is that very soft put above

**Pull request closed without merging**
