### PR TITLE
Atmos revamp, part 2

### PR DESCRIPTION
**Pull request by Gearshy**
(Also see #2133.)
After the requisite amount of reeeeing at the screen as things refused to work for no readily apparent reason, here's the slightly less messed-up file.

Changes:
- Moved all of atmosia's inputs to ground level.
- Extra purge vents added to scrubber line.
- External radiator added for cooling scrubbers/waste as needed.
- Filter system rearranged to stop phoron from getting into every single pipe.
- CO2 storage moved to ground level, connected to oxygen generators.
- One heater/cooler pair provided free of charge.
- High-power pumps pre-placed on all filter->gas storage outputs.
- Supply line set to pressurize at round start.
- Suit coolers and inflatables placed in atmos.
- One (1) atrium-facing air alarm placed on surface level 2, just east of the door into the atmos lobby.

Screenshots:
- dreammaker_2017-09-10_18-48-45

- dreammaker_2017-09-10_18-46-59

### CODE REVIEW

**Comment by Cyantime** [comment]
The radiator array would look better if it turned downwards instead of sticking straight out into the rock.

**Comment by chaoko99** [comment]
Could you make a habit of embedding your screenshots? Copying the image and pasting it into the description editor/comments will embed it and make it load with the page.

**Comment by Gearshy** [comment]
>The radiator array would look better if it bent outwards instead of sticking straight into the rock.

dreammaker_2017-09-11_23-19-33
Something more like this?

>Could you make a habit of embedding your screenshots? Copying the image and pasting it into the description editor/comments will embed it and make it load with the page.

Yeah, I can do that.

**Comment by Gearshy** [comment]
I blame @Cyantime. This is how the radiator looks now: 
dreammaker_2017-09-12_00-20-09

**Comment by Screemonster** [comment]
And yet with all the crossing, despite being a gordian nightmare to look at, it's actually more efficient as a radiator due to the stacked pipes 👍

**Comment by SpadesNeil** [comment]
Any last words with this?

**Comment by SpadesNeil** [comment]
eh I wanna do map edits so MMMMERRRRGGGGG

**Comment by Gearshy** [comment]
...well, now our nitrogen reserve is 3*40,000L*75atm, while our oxygen reserve is 3*10,000L*25atm. I'll, uh. Fix that in just a moment.

**Pull request merged**
