### PR TITLE
Makes SilencedMP5A5 spawn with their gun

### PR DESCRIPTION
**Pull request by Cameron653**

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Link to app?

**Comment by Cameron653** [comment]
No idea where the app is. They just PM'd me they stopped spawning with it. It's in the code, so I'm assuming it's already approved.

**Comment by SpadesNeil** [comment]
https://forum.vore-station.net/viewtopic.php?f=26&t=1084

**Comment by SpadesNeil** [comment]
https://forum.vore-station.net/viewtopic.php?f=28&t=922

**Comment by SpadesNeil** [comment]
image

**Comment by Cameron653** [comment]
Well, I have no idea, then. I'll ask them to comment on the PR for clarity.

**Comment by SilencedMP5A5** [comment]
https://forum.vore-station.net/viewtopic.php?f=27&t=1084
this

**Comment by SilencedMP5A5** [comment]
i've been spawning with the thing as i should since it was approved, up until recently because ???

**Pull request merged**
