### PR TITLE
Adds some spots to loiter in

### PR DESCRIPTION
**Pull request by Very-Soft**
Does #3790 : Adds some spots to hang out in as per @Verkister 's suggestions. I used different materials for some bits though. 

space3-2
Small change here, but it shows where a locker and a trash pile were moved to, to make room for the hangout spot. I also added a wall to a corner, so that space wouldn't leak in through the crack in the window.

space3
There's a couple of hangout spots here. Places for folk to hang out if they're waiting for medical, cargo, or the elevator!

space2
Here's a Public Meeting Room! An alternative to the library's game room. It could probably be used by IAAs to have discussions with larger groups of people, in case such should be needed. Or maybe It's where interns plan their investments? Either way, it's a fully functional room.
(I also added a couple decals near the engineering doors, to make them like every other door, as they seemed to be missing)

space 1
Here's a small spot. Now it's got a table and a comfy bench to hang out in. Perhaps it's a waiting area for the holodeck?
(I also moved that one light fixture over BECAUSE IT WAS ASYMMETRICAL REE)

surface 3
A little dining area that overlooks the atrium, similar to how it used to be, but less in the way!

I had some ideas for how to make the last idea not a fire hazard, but surface 3 already has a fair few places to loiter, and I was worried about it cluttering an already high traffic area. 

For your consideration!

### CODE REVIEW

**Comment by Ketrai** [comment]
👍

**Comment by Arokha** [comment]
This PR is very likely to conflict with the Polaris sync one, which also changes these maps.

**Comment by KasparoVy** [comment]
Really digging these tweaks.

**Comment by Arokha** [comment]
You don't appear to have fixed diagonal corner madness.

**Comment by Little-119** [comment]
Why didn't I notice that asymmetrical light months ago *scream

**Comment by Very-Soft** [comment]
I don't mind asymmetry when it's clearly not intended to be symmetrical. The light bothered me because it seemed obvious that it was meant to be, but it wasn't.

**Pull request merged**
