### PR TITLE
Gives prometheans the trash eater trait.

### PR DESCRIPTION
**Pull request by Cameron653**

### CODE REVIEW

**Comment by Screemonster** [comment]
macro promethean janitor cleans up the hallways (2562, colorised)
image

**Comment by Cyantime** [comment]
Verk mentioned that this also need to give them the `/mob/living/proc/eat_trash` verb.

**Comment by Arokha** [comment]
Depends on what they wanna do. If they wanna eat trash items, this would do it. If they want to eat 'a ton of things' like pAIs and stuff then they'd need the verb.

**Comment by Cameron653** [comment]
Doesn't trashcan var also give them the eat_trash verb?

**Comment by Cameron653** [comment]
OH, I see. The code was changed for it.

**Pull request merged**
