### PR TITLE
Yet more engineering fixes and adjustments.

### PR DESCRIPTION
**Pull request by Jakksergal**
- Adjusts the construction area's area to make doors powered from the outside.
- Attempts to fix CE's access to secure storage. If the fix doesn't work it wont break anything for the other engineers.
- Adds missing air alarms to maintenance.
- Adds a drink vendor and borg charger to the lobby.
- Minor aesthetic changes.
- Adds an electrical shaft with a ladder and an upwards wire.
- Removes the catwalks in the locker area and replaces it with normal turf until https://github.com/VOREStation/VOREStation/issues/1959 is fixed.

Let this one sit for a day just in case something else comes up.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
`access = list()` is "you need all of these to get through this door"
`access_one = list()` is "you need any _one_ of these to get through this door.

Mix and match as necessary.

**Comment by Jakksergal** [comment]
I know what they're for but some reason `req_access = list(11)` and `req_one_access = list(10)` on the same door makes the CE not able to enter it. It doesn't make any sense to me, this is just attempting to fix the issue.

**Comment by SpadesNeil** [comment]
That doesn't make any sense. Although I was mistaken earlier. req_access overrides req_one_access I think.

https://github.com/VOREStation/VOREStation/blob/master/code/game/jobs/job/engineering.dm
https://github.com/VOREStation/VOREStation/blob/master/code/game/jobs/access_datum.dm

**Comment by Jakksergal** [comment]
That doesn't seem to be the case. Players reported that removing secure tech storage's airlock control board and reconstructing the door with the same board allows them to access it with CE clearance. It turns out that the door starts with the vars I stated above but reconstructing it sets `req_one_access` to null. Although I'm frankly not certain what I should set that var in DM to to achieve the same result. 
Is it `null`, `list(null)`, `list()`, `{}` or what?

**Comment by SpadesNeil** [comment]
None of the above.

`req_one_access = newlist()`

**Pull request merged**
