### PR TITLE
New borg module: Command Hound

### PR DESCRIPTION
**Pull request by LunarFleet**
I was looking through old borg art a while back, and stumbled upon an old concept Vale drew up. A few days of cobbling and suffering later, and I have made this. https://cdn.discordapp.com/attachments/351885478863044610/391236984246632459/c-borg.png

My command hound concept uses the nature of the second law to assist heads of staff in their duties. This module is quite comparable to a command secretary and, to a degree, an IAA/head of personnel, in the sense that both IAA's and HoP's act as mediators. 

Command hounds can step in to resolve conflicts in departments that LACK a head of staff, or they can step in if a head of staff asks them to. This works well because the second law requires borgs to serve the crew based on their rank and role. If there is no head of staff, then the rank would be the same, ensuring the borg will be impartial, only judging based on role, as biasing towards either member of an argument would be violating this law. 

(For reference, the HoP wiki mentions this. This is the idea I'm going for with the command borg)
A Happy Department Is a Productive Department
Now that a certain department is staffed, it also falls under your and Internal Affairs' jurisdiction to make sure that each of the departments are running smoothly. Check up with all of the other department heads frequently to make sure that there aren't any inter-department problems or any major problems between crew members.

Command borgs do NOT have a department they belong to,  beyond the command department (Not sure command classifies as a department really). Meaning, if each department has a head of staff, command borgs are near identical to command secretaries; they have no influence over any department, they do not order any department around. They do whatever the heads of staff want them to do, whether it be paperwork, helping an intern, etc; they're an assistant to the heads of staff. Along with this, the second law requires you to serve people based on rank and ROLE, which would imply that interfering with their job, their ROLE, is against that law. 

Chain of command wise, a command hound would be at the bottom of the head of staff chain of command, but above normal crew; they have no influence over the heads of staff, but they do fill in for any head of staff that is missing. 

Module item wise, it is similar to the clerical borg, but with some extra bits. Originally, I was going to have it be, item wise, identical to a clerical borg, but then I realized that no one ever plays the clerical borg  because there is rarely paperwork to do, so I tried to make it a tiny bit more interesting.
The items include
- A pen
- Paper dispenser
- Clerical borg's paperwork gripper
- Hand Labeler
- Stamp
- Denied Stamp
- Bluespace Filing Belly (For storing lots of paperwork, or whatever else a head of staff may want you to carry. Is basically just a janihound belly but without the recycling part)
- When emagged, pounce module!
(Updated the items, will edit the files in the morning)

This all has working sprites, for every belly/movement state. I changed the X-ray borg vision icon to the thermal goggles, because, before that, it was just a triangular warning sign. I also had to change a few small lines in the fax machine, as you cannot insert IDs into a fax machine as a borg, so I just made it like the comms console, where it logs you in if you are an AI/borg interacting with it. 

Overall, this was my first time working on code stuffs in byond, and my second time spriting, so if I made any mistakes, just point them out and I will try my best to fix them.  https://cdn.discordapp.com/attachments/383791599911436288/716514980786077706/the_boy.PNG
(Also I will happily make more sprites/a wiki article about how to play this module if this ends up getting added)

### CODE REVIEW

**Comment by Heroman3003** [comment]
I don't like idea of borg that is dedicated to command. Hound version of clerical module would be one thing, but this is way overkill, especially with crazy tools when compared to other modules, like ID, X-ray or bluespace harpoon.

**Comment by KasparoVy** [comment]
Wow this borg has some crazy equipment.

**Comment by Heroman3003** [comment]
To add to my previous comment: I heavily disagree with any lawed synthetic being in any way 'above' the crew by default, doubly so if its tied to their module of all things (considering any borg can be any module).  ID modification is also among things that is exclusive to two unique highest ranking jobs and should probably stay that way. XRay goggles are a tool plain OP (inb4 scene stalking), and as far as I'm aware are unused anywhere for a reason. And harpoon is equitable to hand tele in the type of equipment it is (fun note: hand tele is illegal item for research modules).

If clerical borg was to work well, what they'd need is not toolkit and authority to act like a HoP, but ability to actually do things on their own. Particularly, an ability to send faxes on their own and actually manipulate paper-related objects properly. Secretary is a popular job because fluff, clerical is unpopular because it cant even compare to secretary, and making them comparable would be more than enough to make them viable without making them as crazy as this proposal.

**Comment by LunarFleet** [comment]
I have to disagree with the clerical borg comment. Paperwork is done very minimally in the first place, not enough to warrant an entire module for it. Command secretary is decently well used because of the roleplay position it allows. Clerical borg lacks this, as you are just a paperwork machine, you have no real connection to anything. That, and non-hound borgs are less popular in general. 

The idea of the command hound is for you to have the chance to be an impartial mediator, which your laws would be perfect for. For all intents and purposes, you aren't really above the crew, as a command hound should be, at most, working to unify the crew to work better together. As your laws state that you serve the crew based on role and rank, you shouldn't be interfering with their duties themselves, that comes back to the whole 'role' thing. 

But for the items, I am of the opinion that it is combinations of items that make things powerful. A bluespace harpoon, x-ray, and a self recharging laser, would be insane. There would be no way to counter that, it would be extremely overpowered. 

But a bluespace harpoon, plus the ability to see through walls, has much less of an effect, it leaves you in a more supportive role if anything. The rest of your tools are for paperwork after all. Sure, the goggles may let you see a problem, or threat, and the harpoon may let you get to it, but what are you going to do, stamp it to death? Also, keep in mind that the goggles do nothing for darkness. Common scene spots, like maintenance or dorms, are gonna be too dark to really snoop on, and most people use subtle for that sorta thing anyway, so it isn't like you're going to hear their actions through walls either. 

Regardless, the idea of a sort of mediator hound seems interesting, and would open a lot of RP opportunities, so I am happy to adjust the items in any way necessary.

**Comment by Heroman3003** [comment]
Clerical borg is not used for RP purposes in same manner no other 'normal' borg is not used for RP purposes. 90% of the time borgs fall into category of regular borgs being job and just job things, while hounds are used for RP, scene and others. Lack of clerical hound till now would be main reason it hasn't been used for some sort of command servitude module, IMO, though unusability of Clerical's toolset due to critical limitations of paperwork's clumsiness with grippers and inability to use fax would play the part.

> Chain of command wise, a command hound would be at the bottom of the head of staff chain of command, but above normal crew; they have no influence over the heads of staff, but they do fill in for any head of staff that is missing.
This is what was stated in the original post. And the entire premise of silicons is that they exist entirely outside chain of command OR if they had to be put somewhere on it, at the very bottom of it, below the normal crew, due to laws in place.

The idea that they are INTENDED to use XRay + Bluespace Harpoon is stupid. Bluespace Harpoon's interactions with any sort of vision augumentations are unintentional design-wise, and any still-existing ones are considered bugs. You are only meant to be able to teleport to tiles you'd see without mesons/gravitons/xray/whatever. 

Most people actually don't use subtle when they feel like they're private, in my experience. Like dorms or hidden spots. And very does scene itself happen in entirely unlit spot (even in dorms, lights aren't often turned off in my personal experience).

**Comment by lm40** [comment]
wtf is what that equipment. most heads of staff can't make access modifications. having what is basically a glorified command secretary able to makes no sense. bluespace harpoon and x-ray just seems like you're taking the piss tbh there is zero legitimate reason for it to have those whatsoever.

overall not a fan of putting borgs in command for the obvious reason that all silicons are tools, not users. even the ai is not supposed to act in any sort of command capacity. but this gear selection is so much of a joke I had to say something.

**Comment by LunarFleet** [comment]
The original idea, referred to in the image Vale made, was to include an ability to view cameras from anywhere. This seemed overcomplicated, and a bit too much overall, so I figured x-ray would be a close enough second, as it does not light up the areas you are viewing, and is localized. I did not imagine this to be such a point of conflict, as there isn't much you can really do with the vision, and the harpoon has (if I remember reading it correctly) a thirty second cooldown, with a very limited range. If that is going to be a problem, I would be happy to remove them. 

Though, on the topic of borgs being tools, a command hound would still be nothing but a tool, just a tool for heads of staff, in the same way a head of staff can delegate duties onto a command secretary. They have no department to belong to, and interfering with normal duties would go against that whole 'serve based on role' part of the second law, they'd only really step in when there is a conflict occuring. Which is something I have seen AIs do repeatedly on other servers; acting as a middle man between two disagreeing crew members, or two disagreeing departments. AIs have no ability to interfere and order around crew members, but they can still use their communication abilities to harmonize situations, a command hound would be the same way.

**Comment by Verkister** [comment]
I feel like this would be pretty rad as a special case event/shenanigans/whitelist borg kinda like the ert models and such. As a public access borg this would be way too powertrippy for most folks around.

**Comment by lm40** [comment]
okay but if they are supposed to be basically a command secretary, why do they have access modification ability, a bluespace harpoon, x-ray vision, etc. etc.

if they are supposed to do an rp job they shouldn't have mechanic-heavy tools especially ones that make no sense.

**Comment by Heroman3003** [comment]
Especially considering two of those tools are unique to specific one-person job (reminder: borg modules arent locked behind certain amounts), and third of those tools isn't even obtainable. it feels like just trying to throw absurdly strong and unique stuff in for sake of making it more appealing instead of fixing flaws that are still present in the base design of Clerical module.

**Comment by LunarFleet** [comment]
Because Borgs are law bound machines, and they have no chance at benefiting themselves with their position. As you said, borgs are tools, it would make sense for more trust to be given to a tool than to a person with their own, lawless self interests. 

Though, I have already said that I would be happy to adjust the items as necessary, I am not digging my feet into the ground for them. If there are any suggestions on how to, as Hero says, fix flaws that are present in the base clerical module, I would be happy to change the module and add/remove whatever is necessary in the morning. Though, Hero has mentioned a few times that the inability to fax has crippled the clerical module; I did include a fix for that, albeit a simple one, which simply authenticates the fax machine if a borg or AI interacts with it.

But regardless, I'd be happy to change the items, they aren't crucial to the idea of the module itself, which is that they are a mediator and command secretary with the lowest ranking command position. Items can be easily changed, the way a module is designed to be played, RP wise, is more important.

**Comment by lm40** [comment]
honestly command secretary isn't in the chain of command and this shouldn't be either. but from a code perspective I would be much more comfortable with the three things I mentioned axed.

**Comment by LunarFleet** [comment]
Perhaps I could take in more opinions and try to patch up the normal clerical module too, then make the command hound have the same items? As Hero is of the opinion that the clerical module is flawed to begin with, which I can agree with.

I do still believe a borg being a part of the chain of command would be fine due to the second law though, as AIs often already help unify and defuse situations.

**Comment by Heroman3003** [comment]
Nothing is stopping the borg from doing it same way AI does and AI still has 0 proper authority over anything except borgs slaved to it. Having a module with legal power dedicated to ordering people around is ridiculous in that regard.

**Comment by LunarFleet** [comment]
Borgs usually lack the proper ability to communicate in that way, unlike AIs. Along with this, some degree of authority is often needed, as many characters are stubborn or ignorant. The AI can try to defuse the situation, can bring it to the attention of the appropriate heads of staff too, but they can't outright resolve it, which is what I'm suggesting with this.

Being able to mediate these sorts of conflict would allow for more RP opportunities, and holding a degree of authority would also be useful when working on some forms of paperwork, such as faxing docking codes to the talon and such. As said before, borgs are tools, and cannot benefit from their own powers, whilst their laws should limit them from interfering with the jobs of others, these are the main reasons why I thought of this in the first place, it seemed fitting due to the impartial nature of a law bound machine. 

Though, Hero, what do you think should be done with the Clerical module to make it more functional? As you have mentioned before that it is already flawed.

**Comment by Heroman3003** [comment]
Speaking of Clerical module specifically, obvious issue 1 is inability to use the fax. Ability to better interact with paper-related objects (fax, copier, noticeboard, etc). Beyond that, extreme clunkinsess with actually doing any paperwork. Good potential solution could be tools that allow easier/alternative handling of paper. Inbuilt copier or ability to pre-type the text and then print it out in different colors or whatever. Also, I don't remember exactly, but interactions with such things as folders, paper stacks and clipboards may be a little busted, but not sure if still issue. Maybe some sort of borg tool version of clipboard? Oh, and of course, simple tape tool, for ability to make/use taped papers. For more fluff improvements, replacing the paper dispenser with a more multiple option one. Paper/photopaper/coffee/pen/some other simple office-style things.

**Comment by LunarFleet** [comment]
I tested the copier, fixed the fax machine, but haven't tried the others, so I'll work on that today. If there are any other suggestions on how to fix up the Chound and clerical borg, I'd be happy to hear them.

**Comment by LiquidFirefly** [comment]
Dude, what is this?   Like, for real.  No matter how many times you say 'A lawed borg can't powertrip' I deadass can't find it in my heart to ever believe you.  You've still got people behind these keyboards and those people will try to benefit from their own decisions no matter how impartial their character should be. There should be absolutely no circumstances where a literal (and sometimes figurative) tool should be making decisions for the crew.  The AI doesn't even do that and it has authority over all stationbound silicons.  What you're proposing is a silicon role that's effectively just not silicon by all intents and purposes.   By the way it's got head of staff gear, all of it for... reasons?  I'm gonna leave that statement alone.  This thing should not be able to change _alert levels_ It shouldn't be able to fax central command, it shouldn't be able to change ID access, and it definitely shouldn't be able to legally open the _red armory_ whenever it wants.  If you want a command secretary borg, go right on ahead I can't argue with you, whatever.  Make it able to write and copy paperwork and deliver missives and record speech or something, I don't know.  This thing is... not okay.

**Comment by Heroman3003** [comment]
IMO, one part here is fine and that is sending faxes to Central. Literally anyone can do it in crew and AI even has a button dedicated to an equivalent of that. Especially considering that nature of vast majority of faxes will either be "someone asked me to send this" or "we need X crewmember requested". Changing alert levels is also already within capability of any silicon that can view a command console IIRC, but I do not think that is too harmful either. Although changing ID access, or having absolutely any form of authority over anything regardless of its purpose is going way too far in overkill territory.

**Comment by LunarFleet** [comment]
I have already removed the ID modification stuff, and the other items that were disagreed upon, added more paperwork items in their place, like a folder and the dispenser Hero suggested, which prints paper, folders, and coffee, as suggested.

Though, going back, my understanding of it was that the borg's laws would be the part that makes them impartial. In that case, blatantly not following these laws would go against server rules, so the person behind the screen would be much less of an issue. At least, it'd be more of an OOC issue than an IC issue. 

Lastly, as Hero said, Borgs can already do most of the things mentioned, and AIs are trusted with a lot of power already. The command hound wouldn't be interfering with department stuff, as that would go against their laws. They would be more like an IAA, resolving disagreements. They don't have much real power over crew, they'd just be resolving disagreements and acting as a mediator. That is rather fitting for a tool I'd think, there is even a law set that reflects this, to a degree. I believe it is called Corporate, basically just a lawset that encourages an AI/borg to minimize expense.

**Comment by lbnesquik** [comment]
I am not a fan of any borgs having any authority over crew either.

**Comment by LunarFleet** [comment]
Personally, I don't really see the issue due to the laws. But, if this is going to be a persistent issue, then we can just remove that as well. Leave the command hound as a command secretary that tries to help resolve disputes between departments and people _without_ the authority, just acting as an advisor and secretary that no one _has_ to listen to. Does that sound acceptable enough? If so, I can apply the same changes to the normal clerical module and that should be just about it.

**Comment by MrSign** [comment]
As long as we keep the module as just a glorified command secretary that a Head of Staff can adopt for their paperwork business, I'm all for it. But, we should avoid making it simply making the module a 'Head of Staff' or a 'mobile AI', if that makes sense.

**Comment by LunarFleet** [comment]
At this point we're just making it a clerical hound, and updating the clerical hound to have more functioning items, like the ability to actually use the fax machine. That's all fine, but I still think both the clerical borg and hound should have access to most channels. An actual command secretary can be given a new headset, or new encryption keys, if the appropriate head of staff asks for their help in the department. 
Borgs are a bit trickier to add channels to in-game, and their tool like nature would make sense for them to be able to be trusted with these channels from the start. Normal clerical borgs already have access to the command and service channels, I'm just suggesting they have access to the others so they can work with a department better if a head of staff wants to delegate any duties onto the borg, same as the command secretary.

**Comment by Heroman3003** [comment]
This borg is meant to be equivalent of a secretary. It shouldn't get any more channels than that and it having service is a grace to be thankful for already (and to me that part doesn't make much sense beyond it being a subtype of general service borg tbh). No borg should be able to delegate, just like secretaries can pass over orders, but can't actually delegate or order anyone in someone else's name. if they need an extra channel, they can use normal borg way of getting extra channels.

**Comment by LiquidFirefly** [comment]
For reference, the only other roles that have radio all access are the CD and the fucking AI, if only because they're plugged into everything.  You shouldn't be meeting or exceeding AI with any of this stuff buddy.

**Comment by LunarFleet** [comment]
"No borg should be able to delegate, just like secretaries can pass over orders"
The idea of having more comms is so they can pass over orders more easily, but regardless, I am pretty sure command secretaries can be given most of the responsibilities of a head of staff, if that head of staff chooses, not just relay orders. 

Regardless, it was just a thought due to the extra steps needed to add a radio channel to a borg, relax, I'll keep it the same as the normal clerical module, and we can be done with this.

**Comment by Very-Soft** [comment]
The command secretary borg shouldn't get access to all the channels. It's a borg that serves command, it should have the command channel.

**Comment by LunarFleet** [comment]
Aye that was already covered, and responded to. I'm just going to make it a pure copy of the clerical module, rename it to clerical hound, and improve the gripper so it can grab taped papers, and that'll be that.

**Comment by KasparoVy** [comment]
:(

**Pull request closed without merging**
