### PR TITLE
Mining Changes

### LINKED ISSUE #4357: Mining shed's area is mislabeled
#### Brief description of the issue
Mining shed's lower half is called "Engineering Outpost Atmospherics", despite not being engineering, actual outpost or atmos.

#### What you expected to happen
It to be called approprietly to its place (AKA Mining)

#### What actually happened
Entirely false name

#### Steps to reproduce
- Have power alarm in Engineering Outpost Atmos
- Pull your hair out in attempt to figure out where is it
- Check map and realize its mining shed

#### Code Revision
- db0f530d6e376aa765141f2b426c582edf45a4f9

### PR DESCRIPTION
**Pull request by Mewchild**
Re-adds the old mining outpost, with some changes
- The outpost is connected to station power, via a heavy duty power cable
    - The outpost is on the same power subgrid as the rest of mining, to note
- The Pacman Generators and Phoron have been removed, to account for this

Makes some tweaks to mining lobby
- Adds a cargo tug to the mining warehouse, replacing the four secure lockers
- Removes the Binoculars from mining, as they're no longer useful as of #4398
- Fixes #4357

### CODE REVIEW

**Comment by Mewchild** [comment]
MapDiffBot is down. Screenshots:

image
image
image
image

**Comment by Mewchild** [comment]
> I wonder what ever happened to the mapdiffbot

Apparently the owner's website choked to death, and he didn't want to fix it (at this time)

**Comment by Mewchild** [comment]
image

**Comment by Arokha** [comment]
Thanks fuzzybutt.

What's on the table? Can't really see. And if every locker is supposed to have those bags, why don't the lockers start with them...? :v

**Comment by Mewchild** [comment]
image
Removed the ore bags, as they do start in the locker by default. Would have put two of them in each locker

**Comment by Arokha** [comment]
Checked, ya, we did remove xenoarch tools from mining. Please also remove from here.

**Comment by Mewchild** [comment]
image

**Comment by Arokha** [comment]
Thanks!

**Comment by Mewchild** [comment]
image

**Comment by SpadesNeil** [comment]
Yeah please stick a mech charger outside with the powernet including it.

**Pull request merged**
