### PR TITLE
Move some things NT wouldn't sell to hacked purchasable

### PR DESCRIPTION
**Pull request by Arokha**
Pending a better solution, like charging money instead of cargo points for them to represent buying them from some independent supplier.

Edit to explain: I'm not changing their legal status, I'm making it so you need to hack the console to order them, because presumably they're ordered from not-centcomm (which is where everything else comes from), pending a better system with like separate vendors that can come/go/etc.

### CODE REVIEW

**Comment by Heroman3003** [comment]
Why tho. All these are literally recreational supplies and have nothing illegal about them. If its question of "but why would NT sell them", then why would NT sell collectible hats or multiple types of ready-to-eat food or generally have hospitality/recreation anything to begin with. Contraband category should be for things that are illegal.

**Comment by SweetBlueSylveon** [comment]
Are collars, costumes, restraints, and figures really contraband? If so they shouldn't be. Throw posters n that mix if they are though, given they're in contraband.dmi. This is also the only way to get restraints as they don't spawn normally.

**Comment by Heroman3003** [comment]
Posters have been marked as contraband for a long time and honestly should be moved out of contraband category, IMO, considering this is like from oldest time when putting a poster up was considered vandalism IIRC. Because there is nothing contraband about the recreational or poster crates as a whole, only about Null and Stolen crates. Which are definitely leagues and leagues above in terms of danger and shouldn't be overly encouraged, especially since cargo people can be demoted for modifying console like that, and if actually practical, yet innocent stuff that someone may need is in the contraband category, it wouldn't be too fair.

**Comment by lbnesquik** [comment]
I don't see how restraints, action figures or restraints are contraband worthy. Especially collars meant for pets and not crew.

**Comment by H0lySquirr3l** [comment]
Honestly, none of these could even legally be considered controband accept for maybe the restraint crate. But even then a craft IAA agent could easily word bend their way around it. We probably should just wait until the new system is in place before we go changing this. What happens if the new system doesn't come for a good long while? do we really want these innocent things sitting on the contraband list for ages?

**Comment by Arokha** [comment]
It's not about that they're ILLEGAL, it's that there's no reason that NT would sell you these items. Don't misunderstand, I'm making it so you have to hack the console to obtain them, not changing their legal status.

**Comment by Heroman3003** [comment]
Hacking the console is also illegal. Making people do illegal things to get perfectly legal things is dumb. Gimping simple things without actually providing the 'eventual replacement' first is also dumb.

**Comment by Arokha** [comment]
Is hacking the console illegal?

**Comment by Heroman3003** [comment]
To add to that, why can't these changes wait until the promised 'new system' is actually in place? Its not like these crates are causing any problems or even ordered that often. And which crates get put under it and which aren't makes little sense either, especially with how pretty much entire recreation category would fall under your definition of 'why NT give it', not just these 4 things (like lasertag equipment or foam weapons).

Imo this PR just adds needless hassle for sake of needless hassle while equating collars and wolfgirl clothes to guns and explosives in terms of contraband.

**Comment by Arokha** [comment]
Let me be clear: Any sort of equation between collars and wolfgirl clothes to guns is in your head. Donuts and flashbags are not in any way similar, yet they come out of the same vending machine.

I already explained what I believe the 'contraband' stuff to represent. Just products from other vendors, not literally 'only illegal goods'. The var is called contraband, that's why I put it in the title.

If the title is confusing to you, I'll edit it.

**Comment by H0lySquirr3l** [comment]
It's honestly less the title. It's just what heroman said. This change is only a change for the sake of changing. Again I ask, how soon is this new system going to be in place? Why randomly add steps to get things that have long since been available and cause no radical issues. I will level with you and say that I can see your point, hacking the console honestly doesn't take that long. I also like and the idea of the console being "locked" to just the NT database of items. But I am just confused as to where the lines are... why not just go ahead and lock stuff like the laser tag and other recreational stuff as well? or was it discussed somewhere that they are too much of a high-value OOC item to lock away while this new trader system is being developed?

**Comment by Arokha** [comment]
Doesn't lasertag stuff already spawn on the station? I thought there were closets for lasertag stuff near the pool. And sure, if you prefer that, I can do that to them too if that's where the line is for you!

**Comment by H0lySquirr3l** [comment]
Honestly, yes. For me, I just want consistency. It would also at least help set the mindset for players to know that stuff is "locked" by NT at the round start for later once the actual system is put in. 

No, there is no laser tag locker spawn at the pool. The pool only has pool toys, personal lockers, and a closet to change underwear. The gym only has a closet for swimsuits.
image

**Comment by Heroman3003** [comment]
The two lockers in south-east ARE the lasertag lockers.

**Comment by H0lySquirr3l** [comment]
Huh.... Then could we also just make an action figures locker and hide it in like... the library maintenance tunnels? Same with the collars and other recreational items? It would sound like a good compromise to locking the recreation stuff down.

**Comment by Screemonster** [comment]
I don't see how "recreational restraints" would be something that you'd be able to purchase on expenses from the office supply catalogue.

Hacking the console to use company funds to obtain good for your personal use is cool and fun though.

Is hacking the console illegal? Maybe. Don't get caught dummy. Don't leave it hacked. Hack the QM console and leave the regular one clean. Build a secret ordering console in the warehouse maintenance tunnel. Maybe more boards for common computers should be obtainable without having to go through science or breaking into tech storage. Order a new ordering console board on the sly and set it up to do your embezzling.

Furthermore, why is it BAD on an ooc level for cargo to be running a contraband operation using company funds? I was under the impression that was half the point of playing the department.

**Comment by MrSign** [comment]
> Furthermore, why is it BAD on an ooc level for cargo to be running a contraband operation using company funds? I was under the impression that was half the point of playing the department.

The second half of that fun is doing a massive contraband ring bust as Security. Unless they're smart to not get caught.

**Comment by Heroman3003** [comment]
Imo, main issue I have is that this PR is in a way restricting purely fluff and scene items as something 'you shouldnt normally have' while not offering any alternatives other than vague "there will be a different system later", while practice shows that only half the time does that "different system" ever actually come to be. And with how stuff being restricted is harmless scene/fluff, I don't see why it should be restricted **now** and not when the said system actually is ready.

**Comment by Heroman3003** [comment]
And to add to add to that, it doesn't just mean 'allow purschases from non-NT sources' because you will only be able to order it from the hacked consoles. Which means that non-cargo will no longer be able to place orders for those items period. Basically meaning that they either straight up request cargo go hack console or not get those at all. Which, combined with the fact that if same logic applied to those 4 crates is applied to cargo ordering list as a whole, almost entirety of hospitality, recreation, costumes and misc categories can be dumped into 'contraband'.

**Comment by Rykka-Stormheart** [comment]
> And to add to add to that, it doesn't just mean 'allow purschases from non-NT sources' because you will only be able to order it from the hacked consoles. Which means that non-cargo will no longer be able to place orders for those items period. Basically meaning that they either straight up request cargo go hack console or not get those at all. Which, combined with the fact that if same logic applied to those 4 crates is applied to cargo ordering list as a whole, almost entirety of hospitality, recreation, costumes and misc categories can be dumped into 'contraband', basically means cargo is no longer a source of simple fun fluff stuff.

I support this, tbh. It's not the end of the world and the console usually ends up hacked anyways, and "non-cargo can't place orders for those items" - good.

**Comment by Heroman3003** [comment]
> and "non-cargo can't place orders for those items" - good.

Ah yes, because generic pure kink/fluff items should absolutely be exclusive to one department that they have absolutely 0 relation to for no good reason.

**Comment by H0lySquirr3l** [comment]
This might need to be something asked to the server at large with something like a survey.

**Comment by Rykka-Stormheart** [comment]
> > and "non-cargo can't place orders for those items" - good.
> 
> Ah yes, because generic pure kink/fluff items should absolutely be exclusive to one department that they have absolutely 0 relation to for no good reason.



> This might need to be something asked to the server at large with something like a survey.

Looking at it from a more overarching "realism" pov, yes, they shouldn't be order-able. Why would NT sell you kink restraints?

On a player-side pov, there should be another way to obtain them (which there is by hacking the console), or you can maint-dive, iirc.

**Comment by InterroLouis** [comment]
As much as there is the argument that 'NT doesn't sell these things', well. There also isn't. Do we really have it that all the stuff available via the cargo shuttle is JUST being bought from NT? With this logic we might as well put all the robolimbs blueprints to contraband too, since those are the MOST obvious thing to NOT be sold by NT. Just going via your 'realism', here. Or, we could keep the ideas that sometimes fun is more important than realism, or whatever. It's not that hacking the console isn't easy, it's just obvious and moreover obviously illegal. If you're going to make innocuous things require hacking the console, make the more dangerous illegal things like null crates and the like require you to EMAG the console, so just hacking it isn't quite so sinister.

**Comment by TheFurryFeline** [comment]
> Main issue I have is that this PR is in a way restricting purely fluff and scene items as something 'you shouldnt normally have' while not offering any alternatives other than vague "there will be a different system later", while practice shows that only half the time does that "different system" ever actually come to be. And with how stuff being restricted is harmless scene/fluff, I don't see why it should be restricted **now** and not when the said system actually is ready.

I have reservations about this PR for pretty much the same reasons posted here by Heroman. Collars **should not** be restricted to contraband.

**Comment by Cameron653** [comment]
I personally think this change isn't really much of an issue, and it personally seems fine to me since it's pointing out that that "Items that you can order normally are NT approved, or otherwise sent by NT" and the items that aren't listed are "Items that are either not NT approved or are being gotten by another (possibly non NT approved) vendor."

I don't really feel too strongly one way or another towards the items listed being listed as contraband, but I can definitely see why they're listed as such.

Everything that you need to hack the console can be obtained quickly/produced quickly (grab/make a multitool) and hacked in a few instants, or if someone is lucky, they can just emag it w/ no issue.

Also a good point for this being there is that it'd make it so security wouldn't be able to get as uppity about cargo hacking the console, since instead of contraband being extremely dangerous things, it could be "Things that NT doesn't supply/approve of" and would be a lesser thing.

**Comment by lbnesquik** [comment]
I like the idea of different suppliers but maybe we should flesh things out properly in that case.

**Comment by Arokha** [comment]
> obviously illegal

I just don't get where this comes from, and even though I've challenged several people to show me where in spacelaw it says it's illegal, nobody has. Can you, @InterroLouis?

**Comment by Arokha** [comment]
We talked in admin chat, it's not illegal, nothing we could find in spacelaw says it's illegal.

**Comment by AegisOA** [comment]
I said it in #supply, I'll say it here. You write this off as it being entirely too easy to just hack the console to get all this stuff that, in my opinion, shouldn't even be behind that wall to begin with... yet, not everyone has a reason to hack things, or the knowledge to do so. You might be forgetting that in a HRP environment, it's kind of silly to take something like hacking knowledge for granted. Before this change, sneakily giving someone some sceneing supplies was (and should be) as easy as pressing a few buttons. After this change, both I and they will be SOL because I don't hack things unless I have an emag; if the emag's then only used to unlock the "actually illegal" options as another suggestion offered, then that's, like, two layers of being SOL.

**Comment by AegisOA** [comment]
As an aside, I also support the idea of asking the server at large if this is something they would like to see; note, not just #supply, seeing as this will effect even people who visit Cargo for these affected items. As things are, given the comments, it's a divisive enough change to warrant it, and it'd be kinda **not great** if it was still passed right over our heads.

**Comment by serenekerosene** [comment]
personally i support this change, as it will incentivize low-profile crime and learning the console hack, provide ample ground for characters to bond, and make hacking the console slightly more ambiguous in intent and thus less meta-able as an act on its' own. additionally (correct me if i'm wrong but) it seems nearly all fluff items involved in this change can also be found in pre-spawned locations in maints or in the laundry room vendors with the exception of the wolfgirl cosplay crate and the riding crop in the restraints crate

**Comment by ExabyteDiscord** [comment]
> I just don't get where this comes from, and even though I've challenged several people to show me where in spacelaw it says it's illegal, nobody has. Can you, @InterroLouis?

Hacking in it of itself tends to refer to an unauthorized access to something, which typically would mean crime. The [Guide to Contraband](https://wiki.vore-station.net/Guide_to_Contraband#Generally_not_contraband) states that 'basic tools' are not contraband, though specifically leaves out multitools and insulated gloves in the provided images, which would indicate that they don't fit in. Further reinforcement is followed by the next section that Job gear isn't contraband, so those in the right hands wouldn't be seen as contraband, though cargo has no explicit use for a multitool or insulated gloves and isn't provided with their job.

Onto [Corporate Regulations](https://wiki.vore-station.net/Corporate_Regulations), Charge §102 of Petty Theft uses the posession of insulated gloves as an example.
> Items can include anything from toolboxes to metal to insulated gloves.
>
Secondly, Charge §212 of Major Contraband specifically references the words,
> the contraband is designed with the specific purpose of breaking into secure areas (such as an emag, or bluespace harpoon, but not multitools or insulated gloves, as those have a legitimate intended purpose).
>
This could possibly be seen as an indication to show that they're Minor contraband as opposed to Major, as it doesn't fit in with either of the requirements of Major contraband, but this is a less solid example.

Onto a more personal note about the PR, I think it might be best if this is left until it's more fleshed out, as a discussion in the [#supply](https://discord.com/channels/173831852602294272/315700369974099969/722459894598467665) channel of the discord notes that Cargo staff have no particular reason to know how to hack, and locking things off and encouraging them to learn something seen as illegal simply to perform their job better is likely not the best solution for the HRP environment that is Virgo.

**Comment by Screemonster** [comment]
lmao _what_ if that's your reading of the guide to contraband then I'm adding multitools and gloves to the list of things that are explicitly not contraband. If you arrest someone for having a fucking multitool I will secban you.

**Comment by ExabyteDiscord** [comment]
> If you arrest someone for having a fucking multitool I will secban you.
>
I'd personally suggest just updating the wiki instead of threatening a sec ban on someone who doesn't even play security. Aro asked for examples, I provided. The wiki's so bloody out of date that anybody who's new to the game and isn't active in discord discussions 24/7 could make this mistake.

**Comment by Screemonster** [comment]
It's more that it's such a ludicrous misreading of policy that it couldn't be possible to make that mistake without being malicious. For the record, no, things that spawn in public areas of the station and can be literally created in your own department are not contraband to possess, especially if they stay in that department (and you don't need to leave the department to hack the console by definition), and _especially_ especially if they have a million other uses around the station, which multitools do. They are 100% covered under "basic tools".

**Comment by Wickedtemp** [comment]
We used to have vendors for collars and other accessories. Why not just move the restraints and all that stuff there?

**Comment by Screemonster** [comment]
I'm up for there being multiple ways to obtain the same stuff if you know where to look.

**Comment by serenekerosene** [comment]
> 
> 
> We used to have vendors for collars and other accessories. Why not just move the restraints and all that stuff there?

ah was it removed? i could've sworn there was a machine for it in the laundry room zone on floor 1

**Comment by Wickedtemp** [comment]
...Also Scree thats dumb. Obviously people can nonmaliciously assume gloves/multitool is bad. Its happened before, and an outdated wiki is *probably* at least partially to blame.

**Comment by Wickedtemp** [comment]
Anyway.

Some characters aren't going to hack the cargo console due to 'alignment', or lack of knowhow, or a fear of being accused of doing a bad thing. Some *players*, aren't going to hack the cargo console for those same reasons. 

Same goes for placing orders. Some characters/players wouldn't want to ask Cargo to hack their console.

I get that some people are excited at the thought of petty crime, but there are *more* players/characters that *aren't*, and they just want to get fun scene stuff for fun scene purposes like they used to.

I feel like instead of moving it to hacked-only, you could create a new cargo category called "Imports", implying imported from Non-CC areas like from off-central Vendors. NT, as big as it is, is obviously going to have many smaller businesses chomping at the bit to get a market in those stations. How cargo points equate to money when it comes to purchasing is background fluff at best. 

Alternatively, there's the collar/accessory vendor. 

There are already options that are likely overall better than this one, so shouldn't we close this one and focus on those instead?

**Comment by Screemonster** [comment]
I'm sorry if I came across as harsh, so let me clarify. I'm a scottish man who just woke up so everything I type should be read to a background of bagpipes and violence. It's like when an australian drops the C-bomb, they don't actually mean to insult you, it translates to "buddy".
"if you do $RIDICULOUS_THING, then I will do $FURTHER_RIDICULOUS_THING" is not a threat to people that don't do $RIDICULOUS_THING. I assume you don't.
Multitools, as noted, spawn in medical and several other departments. They're useful for getting grubs. They 100% have legitimate uses for any crewmember to have. They're about as ubiquitous as flashlights. Their _illegitimate_ uses can be replicated with a pair of remote signallers if you know what you're doing. The only reason the basic tools page lacks a picture of them is that it literally didn't occur to us that someone could read something from their _absence_ and there's no room on the page to include every tool in the game.

Back on topic, I 100% agree with mlempest that there should be ways to obtain the things that aren't cargo. Hell, put a secret vendor in the kinky dungeon or something.

**Comment by AegisOA** [comment]
I could get behind the idea of there being alternate ways to get these items **alongside** the currently proposed changes, because, again, I don't want to be that person who can't supply the fun scene items simply because my ethics don't co-align with hacking my department's equipment the longer, dirtier way.

At the same time, though, I do kind of like the idea of there being that "Imports" tab, if the IC suspension of disbelief that NT sells these things to us is that much of an issue. Maybe have them marked up in price a little to further sell the idea that it's coming through NT from a 3rd party, and maybe have hacking lower them to the earlier prices. Still incentivizing hacking for the people who want to hack, while also "punishing" the people who don't to a lesser degree.

**Comment by Screemonster** [comment]
Hell, "hacking" the console could be rephrased as "enable imports from suppliers not on NT's approved vendor list". On the circuitboard, it's phrased as "Current receiver spectrum is set to: STANDARD" with the other state being "BROAD".

Supply control console boards are such ancientcode that they don't even have a desc set.

@Arokha - how about a one-line addition to https://github.com/VOREStation/VOREStation/blob/f7979eb0b71bd73cf28b0d599deacf02256a8f08/code/game/objects/items/weapons/circuitboards/computer/supply.dm to say "There is a toggle switch for the circuit's transceiver. Toggling the receiver to BROAD will enable purchases from suppliers that are not on NT's approved vendor list" or something to that effect in the examine tab?

Also it should be noted that if you need some restraints for a scene and cargo aren't around to get them then you can just mash F1 and most of the time we'll just spawn that stuff for you.

**Comment by Wickedtemp** [comment]
I mean Ive done that before and was told "you can get them ICly", so tbh I don't even rely on asking staff for scene stuff. 

Given, I don't care a whole lot about having to go to cargo for that stuff. We do that currently anyway and its never been a problem I've run into for scene related stuff. My only issue is the link to "hacking", and the negative, "contraband, sketchy" vibes it brings to the table, because some people are going to have to choose between breaking character for scene stuff, or not breaking character and looking like an ass for it because its preventing someone elses fun, when previously that wasn't ever an issue. 

Making it "not hacking" would fix this,
Making the fun stuff not require any sort of modification would fix this,
Having the fun stuff be available elsewhere would fix this,

Though we'll need something in Regulations/SOP for Security/Cargo, "While not enabled by default, ordering and receiving orders from non-approved sources is not strictly a breach of SOP or Regulations, these vendors have not been properly screened by HR and may contain obscene, inappropriate, or hazardous items, and injuries, whether physical or emotional, that result from the ordering from these vendors are totally not our fault. Especially if you never thought of a safeword. Its not that hard, geez."

**Comment by Arokha** [comment]
I should mention that collars and many outfits are also available via vendors.

**Comment by Screemonster** [comment]
image
This is loadout. Are there _any_ items in the collar crate that aren't obtainable here?

image
Likewise. Arrivals laundry.

Did we really go for 40 comments arguing about something that you can just walk up and grab out of a vending machine?

**Comment by Wickedtemp** [comment]
Collars are already covered, yes, but there were three other crates that were moved to Contraband category, and I believe thats what we're primarily discussing. We might as well just move cosplay stuff to whatever Clothing vendor we have, the Restraints crate contents to the vendor with the collars, and the action figures to...whatever vendor that has anything vaguely toy related if we have that. Or just put those back into noncontraband because I'm pretty sure some of those are directly related to NT, like... there are CMO and Scientist figurines modeled after the default NT uniform for those roles. I'm *fairly* sure the implication is that they're sold by NT, or given out, like toys at a fast food place.

**Comment by TheFurryFeline** [comment]
> I should mention that collars and many outfits are also available via vendors.

I'd forgotten about those vendors when I made my comment earlier. That said, I retract opposition stance but I still lean towards not liking it even if I'm now in the neutral

**Comment by Rykka-Stormheart** [comment]
Quite frankly I think this is a non-issue.

You can get collars and outfits from vendors, and kink restraints/etc can be gotten from maint or an ahelp if you're desperately in need of it and cargo refuses to multitool the console. (I'm not sure if it should be called hacking if it's just toggling a receiver from narrow to wide band).

As for the wolf girl cosplay crate, again, precisely how many people order that? If it's desperately needed, AHELP, or wait until we implement the new vendors and/or systems to get it. Or, ask cargo for it.

Again I'd like to mention that you wouldn't buy kink restraints using your company's credit card. :P

**Comment by Wickedtemp** [comment]
People shouldn't have to choose between hacking or dumpsterdiving for a scene item that is currently 100% available right now. 

If its such a nonissue then this pr as a whole is pointless. Jf its a nonissue then no change is needed.

**Comment by Arokha** [comment]
> If its a nonissue then no change is needed.

Actually, if it's a nonissue then the PR is moot, not "not needed", and you shouldn't be wasting time commenting on it!

Can someone explain why hacking the console is an issue? You don't even need to move. You can reach all the tools you need to hack from one spot, and there's no skill involved like hacking a door or anything.

Also, I'll mention we're part of the way through reviewing *all* supply crates, so this might just get updated with all the ones we've found that aren't NT-work-approved. There's 350 crates though, so it takes a minute, and we want to assign a supplier to all of them.

**Comment by Wickedtemp** [comment]
I already explained why people feel the hacking is an issue. We aren't talking about strictly mechanics here. I'll just copypaste.

""The reasons this is a point of contention is a combination of things, primarily the requirementto "hack".

There are characters who wouldn't do that, out of ethics reasons or knowhow. There are characters who wouldn't order from lists that required "hacking" for those reasons as well. This puts those characters, and players, by extension in awkward spots because now they feel as though they can't order these items from Cargo, or if they play Cargo, that they can't complete these orders without breaking character in some way, when previously these items were just simple stamp and approve requests.
""

And no, maintdiving isnt a solution here. 

This is making several cargo players feel uncomfortable. They don't want to have to hack shit. Not everybody IC is a hacker or has some criminal background. Some characters have ethics concerns. Some characters aren't going to know how to hack shit anyway. They shouldn't be intentionally excluded just because the developers don't want to allow these items to be accessed outside of hacking.

Its not going to be an issue for some people because they don't care, and will just look up how to do it on the wiki. There are others who don't want to do that, and that is completely valid. Ignoring that because "well iunno why it matters" is just unfair to those players, because *they do know* why it matters to themselves. 

If I make a PR to put the restraints items into the collar vendor, would that be rejected, or would it be an acceptable addition to help resolve the issues that some players have brought up?

**Comment by Heroman3003** [comment]
I'd argue about cat crate tbh, from the list as a whole, as the rodent problem with mice on station is a thing and cat is a natural counteraction to that (basically same reason as goat crate for plant-related issues since IIRC goat doesn't actually have other uses as of now).

And I still don't see why 'non-work-appropriate' things wouldn't be supplied to station that has a public bar, a pool, a holodeck with purely recreational modes of operation and a bunch of vendors with many 'non-work-appropriate' things. Station itself has multiple locations that have no reason to be in a 'workplace' and yet cargo can't order a crate of costumes without bypassing NT's limits on 'whats reasonable in a workplace'?

**Comment by Arokha** [comment]
We mused on making a restraints vendor and putting it in the dungeon on the station, and I don't think people would oppose that much. At that point you might as well remove the crate.

> public bar, a pool, a holodeck with purely recreational modes of operation and a bunch of vendors with many 'non-work-appropriate' things

Those are static improvements to enhance morale. They don't require upkeep or additional cost, or any effort on NT's part now that they're built. You're even forced to provide the power for them yourselves, how heinous! Representing a holodeck that is already built, and permanently fixed in place, that NT already makes you maintain yourselves, as as being equatable to the not-work-related supply things is silly. Offices have amenities in them. Offices do not offer to order you costumes at your request. Offices MIGHT provide costumes to everyone on Halloween or something. Have you worked in an office?

Also, if you'll allow me to rant for a second (you have to),

It's very frustrating to hear this (and many other things) represented as a "realism vs fun" thing. There's no such thing as a "realism vs fun" choice or PR in this, or any game development. No game developer, or contributor, or creator of any kind is going to make an addition to the game that they don't find personally enhances the game unless someone has them at gunpoint. It's never "realism vs fun", it's always "Group A fun vs Group B fun".

It's a bit annoying to see it reduced to such a basic misrepresentation of the challenges here, and I'm never quite sure if it's being willfully misrepresented as "one side hates fun, the other side doesn't", by always representing the choices as "X vs fun". It is either a very deep misunderstanding of what is actually happening, or just a really lazy strawman. It needs to stop. Please understand that at no point will anyone try to add something to the game that they think nobody, even themselves, will enjoy. That is not a thing. Except maybe if Goofball does it.

**Comment by Wickedtemp** [comment]
Tbh even though I skimmed the 40+ posts and might have missed something, I dont think anyone, or at least many people, said this was a "realism v fun" thing except for when you brought it up. I'm not arguing that, and I dont think Heroman did either. 

I already copied and pasted the IC knowledge/ethics thing so I know youve seen that already and know thats what my points of contention are, hopefully. There are multiple ways to fix this that Ive already mentioned but I havent heard anybody comment on them or show interest.

**Comment by ShadowLarkens** [comment]
> Can someone explain why hacking the console is an issue? 

One thing I've seen brought up a few times here and in Discord is that the requests console can't be (or usually isn't, perhaps?) hacked, which means people can't browse the off-brand wares and properly generate a supply request form, they have to rely on asking cargo to do i; which requires knowing it's a thing. 
Do you think "new people won't know this is a thing and therefore won't order it" is an issue worth considering?

**Comment by Arokha** [comment]
> Do you think "new people won't know this is a thing and therefore won't order it" is an issue worth considering?

I already addressed that. The end goal is to get this stuff into an entirely separate cargo system that uses cash instead of supply points, though if Tempest makes a vendor for some of it then it becomes less and less relevant, anyway.

**Comment by Heroman3003** [comment]
Well, I think this is good thing then that station and its workings are absolutely nothing like office job, and is actually a facility designed to accomodate both on- and off-duty crew, continuous habitation and generally being more than just a workplace. Comparing station to office job is a bad comparison.

As for realism vs fun argument. Its simple. Realism must bring something of value with it to the game, not just 'be there' to make it more realistic for sake of being more realistic. That is good game design. Just adding things with only intent behind it being 'realism' isn't a good game design. And I understand argument of 'fun-hating' really well, considering how many times have I been called fun-hater for not having same opinion on whats fun and what isn't. But I do consider that changing gameplay aspects of the game to be more realistic with only reason of doing it being 'make it more realistic' is bad choice for game design. It's not about 'removing fun'. It's about making controversial changes without a good reason beyond 'realism'. Realism in and of itself is irrelevant to having an enjoyable game. Game can be realistic and enjoyable if realism aspects are integrated into it in a way that enchances game experience, not detracts from it. And the way it is being done right now, I feel, simply detracts from the game without adding much of anything other than said 'realism for sake of realism'.

I like idea of multiple legal suppliers, potentially with non-NT suppliers having inconsitant pricing or other inconviniences. But just locking it behind the hacking of console completely fails to represent the changes you supposedly want. Rather than do this PR the way it is now, especially with how harmless the items in question are, it really would be better to first have at least said cash.

It's not that I don't want a multiple supplier system to be in the game. But SS13 development in general has a long-running history of 'temporary' solutions and adjustments 'pending a better one' becoming permanent, regardless of how well the problem was actually solved or whether there was even a 'problem' to begin with.

**Comment by Arokha** [comment]
> sometimes fun is more important than realism
@Wickedtemp 

The rant wasn't directed at you. I just happened to reply to your comment in the same reply, so I wouldn't need to make more than one.

**Pull request closed without merging**
