### PR TITLE
Makes all synthetic limbs freely attachable/detachable.

### PR DESCRIPTION
**Pull request by Heroman3003**
Title. Let the limbless memes commence.

### CODE REVIEW

**Comment by KasparoVy** [comment]
Holy fuck this is awesome man. SYNTH TF UP!

**Comment by Wickedtemp** [comment]
Is there an actual purpose to this mechanic or is it just for funsies? Does it allow synthetic limbs to just be put on ezpz following an amputation or does that still require an actual surgery step?

**Comment by Heroman3003** [comment]
Attachment of limb would still require all steps prepared before it can be slapped on, afaik. But yeah, generally its just mechanic for funsies and the "take off an arm to beat someone with" memes.

**Comment by Arokha** [comment]
Take care with protean limbs. Make sure those dissolve or something when removed. It doesn't make sense for them to be attachable to other people, and might result in **Unforseen Consequences**. They should probably just create a dust pile if they are ever detached. They might already do that! I'm just sayin', make sure they do.

**Comment by Heroman3003** [comment]
> Take care with protean limbs. Make sure those dissolve or something when removed. It doesn't make sense for them to be attachable to other people, and might result in **Unforseen Consequences**. They should probably just create a dust pile if they are ever detached. They might already do that! I'm just sayin', make sure they do.

To make proteans incapable of using detach limb thing properly would be a separate thing out of scope of this PR. They technically should be able to already do it freely when transformed into brand that already allows it. This just PR makes all brands and types capable of doing it.

**Comment by Arokha** [comment]
> > Take care with protean limbs. Make sure those dissolve or something when removed. It doesn't make sense for them to be attachable to other people, and might result in **Unforseen Consequences**. They should probably just create a dust pile if they are ever detached. They might already do that! I'm just sayin', make sure they do.
> 
> To make proteans incapable of using detach limb thing properly would be a separate thing out of scope of this PR. They technically should be able to already do it freely when transformed into brand that already allows it. This just PR makes all brands and types capable of doing it.

Proteans are nanostuff, they shouldn't be able to remove limbs and have them exist outside of themselves. Protean limbs are dusted when they come off, I just want you to make sure whatever you're doing also makes that happen, otherwise you're adding a way to circumvent a restriction that's in place. Fixing circumventions to game things, if you're adding them, is not outside the scope of your PR.

**Comment by Heroman3003** [comment]
> 
> 
> > > Take care with protean limbs. Make sure those dissolve or something when removed. It doesn't make sense for them to be attachable to other people, and might result in **Unforseen Consequences**. They should probably just create a dust pile if they are ever detached. They might already do that! I'm just sayin', make sure they do.
> > 
> > 
> > To make proteans incapable of using detach limb thing properly would be a separate thing out of scope of this PR. They technically should be able to already do it freely when transformed into brand that already allows it. This just PR makes all brands and types capable of doing it.
> 
> Proteans are nanostuff, they shouldn't be able to remove limbs and have them exist outside of themselves. Protean limbs are dusted when they come off, I just want you to make sure whatever you're doing also makes that happen, otherwise you're adding a way to circumvent a restriction that's in place. Fixing circumventions to game things, if you're adding them, is not outside the scope of your PR.

I'm not adding circumventions, they were added by a different PR entirely from upstream. All I'm doing is making them apply universally, rather than partially to some brands of prosthetics and completely to other.

**Review by Novacat — APPROVED** [review]

**Comment by Novacat** [comment]
Should be merged alongside https://github.com/VOREStation/VOREStation/pull/9847

**Comment by KasparoVy** [comment]
SWEET man! This is awesome. Thank you

**Pull request merged**
