### PR TITLE
Allows Tails to Hide Bodyparts, Shoes & Clip Uniforms/Suits

### PR DESCRIPTION
**Pull request by KasparoVy**
Adds a method for tails to hide bodyparts like legs to allow for a bit more spriter freedom. Sets Satyr legs & taur bodies to prevent regular legs from rendering when selected.

E.g.1 The Satyr legs & taur bodies prevent the regular leg organs from rendering, so you no longer have to sprite them such that they cover the pixels ordinary legs would've occupied.

E.g.2 The deer body has bulky front legs because if they weren't sprited to cover the regular body beneath you'd have weird pixels poking out. This prevents that from happening by preventing legs from rendering when you got a taur tail.

_I snipped the bottom of the Satyr legs off for testing purposes to make sure legs weren't rendering underneath. I made sure no sprite changes were committed._
virgo ss13 goat and taur legs hiding leg organs

Satyr legs & taur bodies now also hide shoes.

Additionally, satyr legs & taur bodies will now 'clip' the lower half of uniforms & suits to prevent weird pixels poking out where they shouldn't.

_Screenshot from the character creator showing how tails/taur bodies with clipping masks can cut off parts of uniforms and suits._
virgo ss13 goat and taur legs clipping uniforms and suits
virgo ss13 wasp taur clipping virgo ss13 alraune taur clipping

_**Pending changes based on review:**_
- [x] Hide shoes. _(To be committed)_
- [x] Deal with suits using clipping mask and icon difference from [this PR](https://github.com/ParadiseSS13/Paradise/pull/8489).
- [x] Shitloads of testing.

**EDIT:** _This also means porting stuff like Citadel taur bodies is now viable due to the way those are sprited._

### CODE REVIEW

**Comment by Heroman3003** [comment]
This really only really surfacely solves the issue, primarily because shoes and jumpsuits and fullbodysuits will keep rendering the same way they used to. And keep poking out from underneath same way legs would.

**Comment by KasparoVy** [comment]
How deep do we want to go? Do we want to have it straight up prevent the rendering of that other stuff too?

**Comment by Heroman3003** [comment]
That is the big dillema and a big problem with all the taurhalves and such. In the end to make it work, you need not just to hide legs, but make alternative sprites for everything that covers below waist. Hiding legs is pretty easy. Hiding shoes is as well. Hiding a 'part' of a full body suit (be it jumpsuit or one of various suit slot fullbodies)? Good luck. If it was as easy as just making legs invisible it would have been done a long time ago. But its same reason all species must fit humanoid bodyshape and if they dont then you're insane: the need to resprite almost entire gallery of suits and jumpsuits to fit it.

**Comment by KasparoVy** [comment]
I found out a way to clip part of a sprite out of another sprite to allow hair to obscure shining eyes for Paracode some time ago that I think might work, so I'll see what I can do there.

That'd allow for simply using a taur 'template' and cut those pixels out of jump/fullbody suit sprites so the lower parts of those suits wouldn't show weird pixels outside of slender taur legs.

**Comment by Heroman3003** [comment]
That could work, but last I heard direct editing in-game like that can have a good time with your performance. And by good time I mean eat at it like mole at dirt. But if you can make it work, it should be good, as long as _thoroughly_ tested with many, many possibilities of what can go and poke out in one way or another regardless.

**Comment by KasparoVy** [comment]
Yeah, hopefully the performance impact isn't too big. I don't know to what extent if any it affected Para but this is definitely scaling up that sort of icon manipulation.

[This](https://github.com/ParadiseSS13/Paradise/pull/8489) is the PR I used it in

**Comment by KasparoVy** [comment]
Ah, wicked! I figured it out. I'll post some commits after a bit more testing and sleep, but I'll be doing yet more testing for sure.

**Comment by KasparoVy** [comment]
The clipping works a treat but requires further testing past the basic functionality checks. Please take a look at the clipping mask in `icons\mob\vore\taurs_vr.dmi' with the icon state `taur_mask_def`

Clipping masks are done by essentially making a blank sprite and covering every pixel you DON'T want removed with fully opaque rgb(255,255,255)/#FFFFFF full white pixels. Creating masks this way ensures the least amount of icon manipulation

**Comment by Heroman3003** [comment]
Will need an update due to new taurhalf having been added: the wasp one.

**Comment by KasparoVy** [comment]
Rebased and replayed the addition of the clip mask after the wasp taur, added a couple clip masks specific to wasps and alraune due to how different they are around the pelvis from the default clip mask

**Pull request merged**
