### PR TITLE
more stuff that can fit on toolbelts of holding

### PR DESCRIPTION
**Pull request by PastelPrinceDan**
big belt = some big stuff

lets toolbelts of holding hold
- inducers
- plasma cutters bc engineering projects are !!fun!! + miners use toolbelts too 
- light replacers
- stacks of steel & glass (only those because they're the most commonly used by engi)

### CODE REVIEW

**Comment by Heroman3003** [comment]
I don't think any mining tool needs to fit on toolbelt, mining exclusive or not. Plasma cutter is already smaller than normal drill as part of its advantages.

Same to stacks.

**Comment by PastelPrinceDan** [comment]
some engi players asked about the stacks so that's why they're here. if an admin/maintainer wants them removed, i'll do so.

as for the plasma cutter, no one really ever asks for them except people doing projects (mostly because it kinda Sucks) which is mostly why i added them, but i suppose i could remove them too if asked

**Review by Very-Soft — CHANGES_REQUESTED** [review]
Conflicts

**Comment by PastelPrinceDan** [comment]
...i fucked something up somewhere, please hold

**Pull request closed without merging**
