### PR TITLE
Minor Security Voidsuit Helmet Updates

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Some minor updates to voidsuit helmets from downstream;

Vulp & Tesh riot voidsuit helmets more closely match the suits themselves
Vulp security voidsuit helmets have a standard blue visor to match regular security colors

Demo (including some extra 'altsec' stuff that isn't included in this PR, but could be if wanted);
security_sets_demo

### CODE REVIEW

**Comment by Novacat** [comment]
Vulpkanin stuff is good! Teshari stuff will likely need to be sent upstream.

**Comment by KillianKirilenko** [comment]
I can easily run the tesh helmets upstream, yeah.

As for Riot/CC suits: the situation is complicated. By default, the "crowd control" (aka riot on the demo sheet) suits have armor values that match the standard suit. The "riot" (aka alt-sec on the demo sheet, or "sec EVA" in supply) suits have armor values that are better suited to riots (much higher melee defense, slightly worse protection against bullets/lasers), but most species lack the sprites to use them.

It's a confusing mess.

**Comment by Novacat** [comment]
That is generally a consequence of most voidsuits not having any species sprites. Which is a big problem here, and one of the reasons why I regularly venture forth to retrieve sprites from elsewhere.

My guess at some point someone fixed the Tesh helmet sprites on Polaris and that change made it downstream since we are hard-sync'd to Polaris and have a mirrorbot kicking changes downstream.

**Comment by KillianKirilenko** [comment]
Perhaps. Either way, I've pushed the majority of the changes [up to Polaris](https://github.com/PolarisSS13/Polaris/pull/6957) now, with a bunch of extras for good measure (mostly UI sprites).

I'll trim the tesh changes out of this in a moment.

**Pull request merged**
