### PR TITLE
Updates the Stun Revolver sprite

### PR DESCRIPTION
**Pull request by ShadeAware**
Changes the stun revolver sprite to something a bit more in-line with other weapons.

**Previous Sprite:**
image

**New Sprite:**
image

### CODE REVIEW

**Comment by Arokha** [comment]
Looks neat

**Comment by Novacat** [comment]
The current stun revolver sprite is pretty new, id like to have both be a thing. Perhaps the old one become a 'retro' stun revolver?

**Comment by TheFurryFeline** [comment]
> The current stun revolver sprite is pretty new, id like to have both be a thing. Perhaps the old one become a 'retro' stun revolver?

For the record, I believe that was already discussed between the artists of these sprites in the dev-assets channel.

**Comment by Very-Soft** [comment]
I will say first, I like the sprite. It's a good sprite.

But. This doesn't look like a revolver at all. Like, revolvers are called revolvers because they have the part that revolves to ready the next shot.

**Comment by SplinterGP** [comment]
the sprite seems pretty good, the only thing i thiiink that looks a bit awkward is the grip

**Comment by SplinterGP** [comment]
> 
> 
> I will say first, I like the sprite. It's a good sprite.
> 
> But. This doesn't look like a revolver at all. Like, revolvers are called revolvers because they have the part that revolves to ready the next shot.
> 
> (Admittedly the one you are replacing also doesn't have that, I know)

that depends actually, some of the old revolvers(while this doenst has a implicit revolver chamber, wel because it doenst need one its a energy weapon) it does have something which revolvers actually had which is the break action 
image

**Comment by ShadeAware** [comment]
Closed in favor of #10819, now I need to figure out how to sprite weapons like Eris

**Pull request closed without merging**
