### PR TITLE
More Protean Tweaks

### PR DESCRIPTION
**Pull request by Novacat**
Going to try increasing simplemob nom times instead.

### CODE REVIEW

**Comment by Screemonster** [comment]
does this affect only proteans or everyone? Because I can see this making mouse-eating an absolute pain.

**Comment by Novacat** [comment]
Basically unless I made another var specifically for mice it would maybe effect mice as well?
I have no idea if it affects object holders though.

**Comment by Verkister** [comment]
This affects everyone and every mob

**Comment by Verkister** [comment]
and yes, it also affects scooped holders since those just relay the vore onto the held mob

**Comment by Verkister** [comment]
should just leave the vore time stuff untouched and make attacks cancel the vore timer because this is fucking over everyone literally only because some proteans went battle-blob in order to abuse vore for combat advantage, which is already against rules.

**Comment by Very-Soft** [comment]
Yeah let's not make vore things take three times as long across the board.

**Pull request closed without merging**
