### PR TITLE
Giving Thunder Dome Suits Armor Values

### PR DESCRIPTION
**Pull request by nate657**
Essentially gives the thunder dome suits armor values. Also excuse any oddities in my pull request or anything like that, had a bit of trouble.

### CODE REVIEW

**Comment by Cameron653** [comment]
:+1: everything looks good.

**Comment by SpadesNeil** [comment]
I'd rather send this upstream to Polaris when given the chance.

**Comment by Cameron653** [comment]
Going to close this and send it to polaris. Nate agreed to this.

**Comment by SpadesNeil** [comment]
Reference the original issue so I know to close it!

**Pull request closed without merging**
