### PR TITLE
Makes improved health scanners able to pinpoint rads

### PR DESCRIPTION
**Pull request by Cameron653**
Because why not.
Currently science can make an improved health analyzer, the other are adminspawn/maintspawn/PoI spawn, and them having the ability to pinpoint rads really isn't worth it.

This gives science a reason to spend some resources on better health analyzers and medical a (slightly increased) reason to want improved health analyzers.

### CODE REVIEW

**Comment by Novacat** [comment]
iirc, I usually ask for improved health analyzers because they can pinpoint broken bones/internal bleeding.

**Comment by Cameron653** [comment]
The improved analyzers are good, but the ability for them to detect rads were left out.

When I initially coded the radiation rework, I was under the presumption that the higher tier analyzers could be made, not just the tier 1 advanced analyzer that can't use the mechanic to point out radiation.

I doubt anyone will be going and trying to get an improved health analyzer just because it detects radiation, but it's just adding on another reason it'd be beneficial to have one.

**Comment by Novacat** [comment]
Hm. My current thought is rather than move the advanced analyzer's features to the improved analyzer, a better approach would be to just give R&D the ability to make the advanced analyzers. It is silly that the advanced analyzer is basically event character only and the phasic one just does not exist at all.

**Comment by Cameron653** [comment]
That'd be another way of going about it as well. Let me see about doing that real quick

**Comment by Cameron653** [comment]
Made the advanced analyzer able to be created in PR #14255

**Pull request closed without merging**
