### PR TITLE
Add "Treadwell" sprite for engineering robots.

### PR DESCRIPTION
**Pull request by Ardebitis**
Adds the "treadwell" appearance for engiborgs, as approved [here.](http://forum.vore-station.net/viewtopic.php?f=26&t=939) However, this will make the appearance available to all players, but that is fine with me.

### CODE REVIEW

**Comment by Belsima** [comment]
Could we get this back on Polaris? I like it.

**Comment by SpadesNeil** [comment]
Just send this to Polaris, I say.

**Comment by Belsima** [comment]
They already did.

**Comment by SpadesNeil** [comment]
Oh, then close this. :U

**Pull request closed without merging**
