### PR TITLE
Replace/Add lots of sounds from VerySoft

### PR DESCRIPTION
**Pull request by Arokha**
Lots of neat AI announcement voices.

### CODE REVIEW

**Comment by KasparoVy** [comment]
Really well done, they sound super legit. Just something right about AI vox having an accent of some sort.

**Comment by Rykka-Stormheart** [comment]
I love this!

**Comment by Arokha** [comment]
Could add a preference, but I don't really feel there's much change from now. 90% of these already have vox announcements that use the old voice.

**Comment by Arokha** [comment]
We'll do that if people are grumpy gooses.

**Pull request merged**
