### PR TITLE
Implements switching on/off duty midround via timeclock terminals

### PR DESCRIPTION
**Pull request by Heroman3003**
Well, that was what timeclocks were for in the first place, so here you have it.

Allows to switch off-duty if PTO of your current department is positive and allows to go on-duty as any non-head, non-IAA, non-secretary job you are not jobbanned from (including alt-titles), all using timeclock terminal.

15 minute cooldown between joining and first ability to switch, and further 15 minute cooldown after every switch.

Switches are announced over common channel, similar to arrival/departure.

A config option, by default it is OFF (same as PTO gathering in general).

### CODE REVIEW

**Comment by Novacat** [comment]
Itsabouttime

**Comment by Wickedtemp** [comment]
What happens to Head roles going off-duty? Do they go to Off-duty Medic/Engineer/Officer, or Worker?

**Comment by Heroman3003** [comment]
Four department heads go to appropriate department. HoP and CD go off-duty worker.

**Comment by Mewchild** [comment]
LEMME JUST PUT A FAT FUCKIN +1 ON THIS

**Comment by Wickedtemp** [comment]
Assuming that going 'off duty' to circumvent demotion would be seen as being identical to leaving the round?

**Comment by Heroman3003** [comment]
Jobs that don't earn PTO (visitors) and TERMINATED can't even access that part of menu.

**Comment by Wickedtemp** [comment]
I mean more like "I'm going offduty instead of handing my ID to the HoP so you can't officially demote me." 

Currently, having people cryo before the demotion is actually handled is kinda a common thing, happened a couple days ago, too.

**Comment by Heroman3003** [comment]
That'd be up for admins to decide then. But generally, I believe demotion is the punishment. And when that punishment is not applicable, other options can be used, as its not the only one.

**Comment by Screemonster** [comment]
a h e l p

**Pull request merged**
