### PR TITLE
Adds Awen Henry's fluff + public marking and hair

### PR DESCRIPTION
**Pull request by Natje0**
This PR adds:

Wolfgirl uniform, hat and sandals, based on the Wolfgirl mob, for the SCA-approved character Awen Henry
The uniform could be added to a cargo costume crate too, if someone is interested in doing that. I won't do it though.

Additionally, for public use, it adds two markings to make Anime eyes (Think Catgirl and Wolfgirl mob eyes. Yes. Like that._(Good luck making it with with your favorite hair, hahahah)_)
Also adds a new hairstyle, shoulder-length messy, which is an edited version of Wolfgirl hair. Likely to not work perfectly with most colors as it was designed to work for with white eyes bordering white hair, and coloring might be off for most colors.

Would love for the code and spritesheets to be reviewed to ensure I didn't screw up.

### CODE REVIEW

**Comment by Verkister** [comment]
Gonna be a pretty big conflict with my overhaul PR, might wanna make a white version of the hair sprite for the better blend mode and add it to the big change file once it's through heh.

**Comment by Natje0** [comment]
Oh, damn it.

**Comment by SpadesNeil** [comment]
Conflicts aaaaaaaaaa

**Comment by Natje0** [comment]
Ok, so it seems Verkister fixed the human_face_vr conflict with their other PR, but... What's conflicting with custom_clothes?

**Comment by Verkister** [comment]
A couple goggles sprite changes from another recent pr. Just 2 icons to paste from the current master.

**Comment by Natje0** [comment]
Updated the two of files, conflicts should be resolved with that.

**Comment by SpadesNeil** [comment]
nyet still conflict

**Comment by SpadesNeil** [comment]
Conflicting files
icons/mob/human_face_vr.dmi
icons/vore/custom_clothes_vr.dmi

**Comment by Verkister** [comment]
Ay ya gotta merge my thing first so they can sync it in and have git stop whining over the pr conflicts.

**Comment by SpadesNeil** [comment]
In future, reference the other PRs via their number so I know if you're doing a PR related to an existing PR or issue.

**Comment by Natje0** [comment]
Alright, the clothes conflict has been resolved, the PR is related with #2262 (Lilians hair fix)
Verkisters conversion #2264  and icon blending overhaul #2256.
As far as I can tell, I've made this PR conflict-free with all of them,

**Comment by Natje0** [comment]
Made a new PR that I HOPE work with #2285.

**Pull request closed without merging**
