### PR TITLE
Adds the ability for meteors to be deflected by baseball bats

### PR DESCRIPTION
**Pull request by deathride58**
image

☄️ 🏌️

### CODE REVIEW

**Comment by ArgobargSoup** [comment]
http://i.imgur.com/yKxIOI1.jpg
INSTANTLY reminded of this

**Comment by KasparoVy** [comment]
God bless

**Comment by Very-Soft** [comment]
swing the bat
baseball

**Comment by Cameron653** [comment]
What about immovable rods?

**Comment by EtheoBoxxman** [comment]
https://www.youtube.com/watch?v=9i4T6nRPC1Q

**Pull request merged**
