### PR TITLE
Redesigning Surface Medical

### PR DESCRIPTION
**Pull request by LiquidFirefly**
Changed the entire layout of surface three and two, of note ORs are now attached to triage, surface 2 now contains patient care and nice big bathrooms, Resleeving is right down the stairs above triage, public access hallway was removed in favor of exit buttons, etc.   It's a lot, I have screenshots down in #Medical but I can also slam 'em in here. 
Surf1
Surf2
Surf3

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Miiiiiight wanna run mapmerge on these files. 
image

**Comment by LiquidFirefly** [comment]
> Miiiiiight wanna run mapmerge on these files.
> image

A whatnow

**Comment by LiquidFirefly** [comment]
Alright, don't know why there's two of those but, y'know, whatever

**Comment by TheFurryFeline** [comment]
Seems like it worked, though. 👍 Filediff is far more reasonable.

**Comment by LiquidFirefly** [comment]
Well, yeah it worked without a problem, my github app is still fucked from trying to install the hook though.  It's dependent on something that isn't actually on the github app, maybe the repository or something?  But I can't commit with it anymore so I had to use the web client for this

**Pull request merged**
