### PR TITLE
Protean Whitelist People

### PR DESCRIPTION
**Pull request by Cameron653**
https://forum.vore-station.net/viewtopic.php?f=46&t=2164&sid=c91bed2c443cbbdb01aa061de4a029a1

### CODE REVIEW

**Comment by lm40** [comment]
While you're doing proteans can you do this one too https://forum.vore-station.net/viewtopic.php?f=46&t=2163

**Comment by Cameron653** [comment]
Gotcha.

**Comment by Cameron653** [comment]
Added

**Comment by lm40** [comment]
ty

**Comment by Cameron653** [comment]
No problem. If anyone is ever whitelisted, DM/ping me and let me know.

**Pull request merged**
