### PR TITLE
Adds in moth wings.

### PR DESCRIPTION
**Pull request by Cameron653**
This is a new sprite.

Proposed changes in this Pull Request:
- Add in moth wings

NOTES:
**SPRITE CREATED BY: Tk420634**
Sprites: http://puu.sh/pnlel/ecf5ccde7e.png

### CODE REVIEW

**Comment by SpadesNeil** [comment]
We have permission to use these?

**Comment by Cameron653** [comment]
They are on another  ss13 github which is licenced with AGPL v3, so we do indeed have permission to use them.

**Comment by SpadesNeil** [comment]
From Paradise?

**Comment by Cameron653** [comment]
From Citadel, not Paradise.

**Pull request merged**
