### PR TITLE
Late September Sync

### LINKED ISSUE #578: Can’t make SMES machines.
Can’t make SMES machines.

#### Brief description of the issue
While I was messing around in the construction area, I wanted to make a SMES machine. After making the frame and adding the circuit board into it, I add cables yet it still says “30 cable pieces needed” despite the fact I already inserted them. Also, it only takes 5 cable pieces, that’s why there are cables sticking out of the frame. 

#### What you expected to happen
To make a proper smes.

#### What actually happened
Can’t insert cables and finish the smes

#### Steps to reproducer
Make a machine frame with 5 metal pieces, screw it in place, add the smes circuit, and fail putting all 30 cable pieces in.

### PR DESCRIPTION
**Pull request by Cameron653**
See: Title
Fixes #578 
Fixes a bug reported on Dev channel that prevented users from selecting loincloth in the loadout select menu
Fixes a spriting issue reported on Dev channel that caused the saddlebag to be mirred (East and West sprites were in wrong areas)

Let Travis do it's thing before merging.

### CODE REVIEW

**Comment by Cameron653** [comment]
A bug was reported where users were prevented from selecting the loincloth in the loadout menu, even though it's perfectly fine in game.

Going to fix it and put it in this PR

**Comment by Cameron653** [comment]
Also fixed a sprite bug with saddle bags being in the incorrect position on the sprite

**Comment by SpadesNeil** [comment]
Why was back_vr removed?

**Comment by Cameron653** [comment]
I was using the github website instead of the github desktop client, so I had to delete and then put it back in.

**Comment by SpadesNeil** [comment]
Ok.

**Pull request merged**
