### PR TITLE
Prevents cryo-consoles from saving guns

### PR DESCRIPTION
**Pull request by SpadesNeil**
because they are guns

### CODE REVIEW

**Comment by Arokha** [comment]
Can I suggest an alternative? Instead, we just rewrite cryoconsoles to log items (and log them to the game log), but delete them regardless.

That way we can use Splunk and be like "Oh, Ace literally never puts his gear back before cryoing" etc

**Comment by Ketrai** [comment]
Better yet, instead of having the guns lost, can we get it so that certain items can only be accessed with certain IDS? as would make sense?

**Comment by Screemonster** [comment]
Having the preserve_item var be "what access is needed to retrieve this" rather than a binary "preserve or nah" would be pretty neato.

**Comment by Arokha** [comment]
Except 'TRUE' == 1 == ACCESS_ARMORY so everything is just 'armory' by default for all legacy items. Which might be okay?

**Comment by Screemonster** [comment]
Given that a lot of the retrievable items are just clothing, might be overkill. Also leaves the question of "what do we with things like clothing that we want to be preserved but don't want to access-restrict".

There... _might_ be a solution that doesn't involve going through and defining a value on every item but I can't think of it right now.

**Comment by SigholtStarsong** [comment]
Might I suggest referencing Paradise Station's github? I'm pretty sure that their cryo console is set up to check for accesses.

**Comment by SpadesNeil** [comment]
We used to have a cryo access requirement, and I have no idea why we never ported it back in.

**Comment by SpadesNeil** [comment]
@Arokha Do you want to write that? If so, close and replace this. Otherwise I'm going to merge this later.

**Comment by Arokha** [comment]
I'll write it.

**Pull request closed without merging**
