### PR TITLE
Release Update

### PR DESCRIPTION
**Pull request by SpadesNeil**
No new PRs will be considered until we can resolve the last 6 pages of stale PRs.

But the AI update is finally in, so that means we can actually get some shit done.

Obvious exception, I will allow PRs that affect other PR branches in order to eliminate conflicts or other problems.

### CODE REVIEW

**Comment by Novacat** [comment]
Looking through the mirrors, a lot of them (even the ones that passed travis) have a lot of conflicting files. Those can only be resolved by someone with write access to the branch, unless I am a massive idiot and overlooking something?

**Comment by SpadesNeil** [comment]
I think you are correct.

**Comment by Novacat** [comment]
Note: https://github.com/VOREStation/VOREStation/pull/4804 contains a critical fix for an issue discovered during testing.

**Comment by SpadesNeil** [comment]
Gonna merge this release update and see how the AI changes work on the server. Hopefully nothing explodes.

**Pull request merged**
