### PR TITLE
Add more explo name bloat

### PR DESCRIPTION
**Pull request by TheDavestDave**
Offsite Coordinator added because I think that is what Explo manger should be named.

Off site supported added for thoose non combat explos

Off site first aider for FM's that are more explo than medic

### CODE REVIEW

**Comment by Detective-Google** [comment]
...first aid**er**?? What. If you want to be "more Explo than medic" as an FM then maybe... Play explo?

**Comment by TheDavestDave** [comment]
https://www.hse.gov.uk/firstaid/first-aider.htm

idk man, pretty sure a first aider is a nice stepping stone form explo to FM

**Comment by Very-Soft** [comment]
I'm really not feeling these names. I think distancing the explorer role from the explorer role by adding an alt title for it is only going to make people salty when they inevitably find that they do in fact still have to do normal explo things if they join an exploration mission. 

Offsite coordinator sounds more like something you'd call the school teacher on a field trip

and first aider sounds gross, and I don't like it.

**Comment by Novacat** [comment]
I have the same opinion as soft, and, I kinda feel that we have maybe gone a little too far with alt titles anyway.

**Comment by lm40** [comment]
offsite coordinator i might be persuaded of, but 'first aider' i just don't like the sound/idea of, and 'offsite support'? really? when there's already 'offsite scout'?

that's why i thumbs-downed

**Comment by KillianKirilenko** [comment]
First Aider is linguistically awkward and highly redundant -- mostly because I would expect *every explorer* to know the most fundamental steps of first aid as part of basic job training. It's like calling yourself a Chef because you threw together some buttered toast for breakfast. Anyone* can do that.

*Okay, *almost* anyone...

As for the two Offsite titles, they sound more like CentComm-side jobs. Major computer system broke down and engineering can't figure it out? Time to contact Offsite Support!

**Comment by Heroman3003** [comment]
Support and First Aider just kinda sound dumb. Coordinator may work, but not in conjunction with Offsite. Maybe Expedition or Exploration Coordinator would look better?

**Comment by Novacat** [comment]
We had a small discussion in staffchat and decided that we do not really want these alt titles.

**Pull request closed without merging**
