### PR TITLE
Converts gas, ore, plants and reagent strings to defines

### LINKED ISSUE #16632: [GENERAL] Reagents and drugs use strings
Someone assign myself. This is more as a reminder and todo to replace all of those strings with defines after this is done not to conflict. https://github.com/VOREStation/VOREStation/pull/16627

### PR DESCRIPTION
**Pull request by Kashargul**
🆑 
code: converts gas, ore, plants and reagent strings to defines
/:cl:

closes #16632

### CODE REVIEW

**Comment by Heroman3003** [comment]
image

**Comment by Heroman3003** [comment]
Slight conflict with resleeving cure namechange, pls fix and will merge before anything esle

**Comment by Kashargul** [comment]
There's new reagents I need to add, too....

**Comment by Heroman3003** [comment]
Im not reading allat

**Pull request merged**
