### PR TITLE
un-nerfs fishing from previous change

### PR DESCRIPTION
**Pull request by Seris02**
PR #12142 changed the max volume of snacks, which affected fishing bait, to the point where even the deluxe bait only gives the minimum reduction, 0.75

this adjusts it to a completely different formula, based around what I think the general calculated bait values should be for the bait types.

Screenshot 2023-01-03 112213

### CODE REVIEW

**Comment by Heroman3003** [comment]
Just change internal volume for the bait specifically back to what it was pre-nerf. This feels needlessly convoluted, and bait was just not something I even thought accounted for something like volume; nor do I think it needs to have expanded volume snacks do. Main reason for expansion was to fit all the reagent from cooking, modular or normal, when it comes to 'bigger' recipes.

**Comment by Seris02** [comment]
> Just change internal volume for the bait specifically back to what it was pre-nerf. This feels needlessly convoluted, and bait was just not something I even thought accounted for something like volume; nor do I think it needs to have expanded volume snacks do. Main reason for expansion was to fit all the reagent from cooking, modular or normal, when it comes to 'bigger' recipes.

The thing is that you can use all snacks as bait, so if I want to just stock up on... I dunno
Super bite burgers for bait, which would be great on polaris code, about the same as deluxe worms, I wouldn't be able to here, and they'd have the minimum reduction still

**Comment by Heroman3003** [comment]
I just really dont like the whole "if we are 80 do one version, if not do the other" option. Its very snowflakey. Changing formula to be more universal rather than snowflakign it up to account for our changes is preferred when we are a 'soft' downstream to polaris anyway. Ideally, there'd just be one universal formula that applies to all snacks still. Maybe make it require less 'percentage' of foodiness to top it off, but cap it or something. Or make it based purely on numeric amount of food. Something that's not "check if we've been buffed or not and calculate differently depending on that".

**Comment by Seris02** [comment]
> I just really dont like the whole "if we are 80 do one version, if not do the other" option. Its very snowflakey. Changing formula to be more universal rather than snowflakign it up to account for our changes is preferred when we are a 'soft' downstream to polaris anyway. Ideally, there'd just be one universal formula that applies to all snacks still. Maybe make it require less 'percentage' of foodiness to top it off, but cap it or something. Or make it based purely on numeric amount of food. Something that's not "check if we've been buffed or not and calculate differently depending on that".

aight, will just go with the formula I was going to change it to beforehand then, will do tomorrow

**Comment by Seris02** [comment]
is done
mlem

**Pull request merged**
