### PR TITLE
Restricts myarps (author request)

### PR DESCRIPTION
**Pull request by Verkister**
Azura's request. It is their personal character and voice after all.

### CODE REVIEW

**Review by Novacat — CHANGES_REQUESTED** [review]
Something like this should probably be cleared through a fluff item request. Since it is a trivial item it will certainly be accepted.

Otherwise, I would rather the entire emote was restricted rather than just only the sound file.

**Comment by Very-Soft** [comment]
Yeh if they want it removed that's fine, but if it's a thing restricted to their ckey, there's an official process for that.

**Comment by Very-Soft** [comment]
I offered a replacement myarp sound if you wanna set the normal myarp sound to that~

**Comment by KasparoVy** [comment]
*merp :D

**Comment by Novacat** [comment]
It has been a few months and there has been no response.

**Pull request closed without merging**
