### PR TITLE
Adds Eguns back to Cargo

### LINKED ISSUE #3862: Energy Gun Crate not available to order via cargo
#### Brief description of the issue
Title. The [energy Gun crate](https://github.com/VOREStation/VOREStation/blob/44380c7c30caf1ab8dea66d5a8a989c9af3671e4/code/datums/supplypacks/munitions.dm#L119) doesn't show up in the cargo list

#### What you expected to happen
To be able to order additional standard weapons for security

#### What actually happened
ADVANCED EGUNS FOR ALL. Ahelp and ask the pack spawned in

#### Steps to reproduce
- Walk to Cargo, check list

#### Code Revision
- release - 
ad18753b9d6bfd50b51846b726f025f1e781a75c 
 
#### Anything else you may wish to add:
- https://i.imgur.com/vYyQk15.png

### PR DESCRIPTION
**Pull request by Mewchild**
Ups the price of 2 eguns from 40 to 50 points, keeping in line with other weapon packs. Changed Access from security to armory.

Fixes #3862

### CODE REVIEW

**Comment by Arokha** [comment]
Doesn't this close an issue you opened? Shouldn't you put the magic 'fixes' words in

**Comment by Mewchild** [comment]
Fixes https://github.com/VOREStation/VOREStation/issues/3862

**Comment by SpadesNeil** [comment]
In the top post dummy.  :U

**Comment by Mewchild** [comment]
I actually didn't know that was a keyword for git. I thought it was just a common courtesy thing- and I simply forgot to do it when I made this PR. My bad.

**Comment by Arokha** [comment]
Fixes, Resolves, Closes, Fixed, Resolved, Closed, Fixing, Resolving, Closing

If followed by an issue, will close that issue

**Pull request merged**
