### PR TITLE
[MIRROR] Pipe Clamps, Shutoff Valves, and Leaking Tubes, oh my.

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/6279
--------------------
Ports Pipe clamps, shutoff valves, and pipe leakage from Baystation.

Pipe clamps are found in atmos techs' lockers, or 2 in the CE's locker.

Automatic shutoff valves can be acquired from the pipe dispenser, and will automatically close themself if they detect a leak on the pipe network they are attached to.

Pipes without endcaps will slowly leak their contents into the area around them, unless they are stasis clamped.

### CODE REVIEW

**Comment by Novacat** [comment]
This is going to need some mapping changes, so I am going to hold off on merging this.

**Comment by pontifexminimus2** [comment]
Hey I mean when this get merged I guess i play Sam as Warden then.

**Comment by chaoko99** [comment]
This is going to need some serious "do not even attempt to merge this" changes. Nobody wants this. Everyone I have shown this to, does not want this. I do not want this, I am *quitting the server* if we get this. This change will straight up allow people to get phoron into distro by MISTAKE if the mining cycler is ever force open and the resultant fire causes their welding tank to explode, merging the surrounding atmo with the contents of the pipeline. Various members of Vore's staff that I have asked don't want this.

This is another case of the Polaris devs adding shit that only they want, and getting them merged because they are developers, and cannot be wrong.

Hey, that sounds familiar, you know why? That's exactly why it got merged on BAY! NOBODY WANTED THIS THERE EITHER

**Comment by Screemonster** [comment]
Honestly just override the set_leaking proc and have done with it.

**Comment by SpadesNeil** [comment]
>Honestly just override the set_leaking proc and have done with it.

What Scree said.

**Pull request merged**
