### PR TITLE
Adds 'Smite' verb and pray button

### PR DESCRIPTION
**Pull request by Arokha**
For easier adminbuse in response to things. c:

### CODE REVIEW

**Comment by SpadesNeil** [comment]
I asked for this a year ago and you all said no.

**NOW DO YOU SEE WHY WE _NEED_ THIS?**

**Comment by Arokha** [comment]
W-when did I say no ;w;

**Comment by SilverTalismen** [comment]
What will Smite do exactly?

**Comment by Arokha** [comment]
Just lets admins abuse players when appropriate. It gives them a list of options like breaking legs and stuff if they're being dumbasses in pray.

Also, merged upstream, so merging here.

**Pull request merged**
