### PR TITLE
Redoes bar/caffeteria/coffee shop

### PR DESCRIPTION
**Pull request by Arokha**
Remaps them to be near or combined with each other since people keep asking. Threw in working Cards Against ~~Humanity~~ The Galaxy decks on a gaming table in newbar. We should add vore things, though the first black card I drew was "________ is on the kitchen menu today."

Also adds new construction area just south of the dorms, on the arrivals hallway where the locker room used to be for building your ~~strip club~~ ~~pred bar~~ whatever.

Also fixed a bunch of other map problems. Toxins testing, dock airlocks, etc kinda need working piping. And hey, half of the dorm scrubbers didn't actually work.

Also fixed some random wires here and there.

image

image

### CODE REVIEW

**Comment by Arokha** [comment]
Leshana would prefer to make these changes ICly first, hence the DNM tag.

**Comment by SpadesNeil** [comment]
This is so much nicer than the current setup.

**Comment by Screemonster** [comment]
If this is gonna be a mini-version of the old boxstation locker room setup with a sitting area and showers, can we fling a univend in there? A lot of the new outfits aren't actually obtainable in-game outside of the loadout menu and it might be nice to be able to get more after roundstart.
You know. 'cause of reasons. The resleeving room could probably do with 'em too. For similar reasons. :p

**Comment by Arokha** [comment]
> If this is gonna be a mini-version of the old boxstation locker room setup with a sitting area and showers

Maybe you didn't notice but we have that now, just south of the dorms on the right. :p That area is now a construction site.

image

**Comment by Arokha** [comment]
And FYI here's the former coffee shop. Emergency EVA storage (since this is pretty far from main EVA, and close to medical), and a small construction area.

image

**Comment by Screemonster** [comment]
I meant in terms of "locker roomy area between arrivals and the rest of the station where people can get dressed".

But I'm working until Wednesday so won't have time to knock up a vendor until then.

**Pull request merged**
