### PR TITLE
Skyrat connected consoles

### PR DESCRIPTION
**Pull request by Arokha**
Modular and normal computers connect:
dreamseeker_zDbIYeVIsJ

Advanced (aka different sprite) version of (L-to-R) engines, helm, sensors consoles, the three you need for overmap flight:
ji22SIbzGk

### CODE REVIEW

**Comment by Very-Soft** [comment]
ME BIG LIKE

**Comment by KillianKirilenko** [comment]
Oh, fancy. Should make ship cockpits and some workspaces look a lot nicer.

The N/E/W adv sensors overlays appear to include the rest of the console though.

Might look even better if there were inner-corner angle pieces for joining consoles together... 🤔

**Comment by Arokha** [comment]
> Oh, fancy. Should make ship cockpits and some workspaces look a bit nicer.
> 
> The N/E/W adv sensors overlays appear to include the rest of the console though.
> 
> Might look even better if there were inner-corner angle pieces for joining consoles together, even if they're just dummies/placeholders.

Fixed, and that sounds neat, if you wanna do!

**Comment by KasparoVy** [comment]
Loving this round of graphical rework, place's looking better all the time

**Comment by KillianKirilenko** [comment]
> > Might look even better if there were inner-corner angle pieces for joining consoles together, even if they're just dummies/placeholders.
> 
> Fixed, and that sounds neat, if you wanna do!

Maybe sooooon. I'll experiment with a couple different designs as well, I have some Ideas. just need to set some time aside to mash pixels together and see what comes out.

**Comment by Novacat** [comment]
Thought: We should have this as a subtype instead of replacing the old one, since I can see a few places where the singleton consoles would work better.

**Comment by Arokha** [comment]
> Thought: We should have this as a subtype instead of replacing the old one, since I can see a few places where the singleton consoles would work better.

That sounds pretty difficult as a subtype, since it'd be, y'know like... you'd have to make a subtype of every computer subtype.

**Comment by Novacat** [comment]
A var would work!

**Comment by Arokha** [comment]
> A var would work!

You do it! It would be good practice to get back into it ;p

**Pull request merged**
