### PR TITLE
Port Eris Trashbag of Holding

### PR DESCRIPTION
**Pull request by Arokha**
image

### CODE REVIEW

**Comment by dwinters99** [comment]
I'm all for a trashbag of holding but god is that sprite ugly. Not only that, it doesn't match the other X of holding sprites.

**Comment by SplinterGP** [comment]
agree with dwinters a bit, i woulndt say its ugly but feels a bit scuffed all over

**Comment by Arokha** [comment]
> I'm all for a trashbag of holding but god is that sprite ugly. Not only that, it doesn't match the other X of holding sprites.

They are also being replaced.

**Comment by Very-Soft** [comment]
I like it

**Pull request merged**
