### PR TITLE
Gives xenochimeras hair.

### LINKED ISSUE #408: Xenochimera don't have any hairstyles
#### Brief description of the issue
As title. The only hairstyle/facial styles are bald and shaved, respectively.

#### What you expected to happen
To plop the tajara messy hairstyle on and keep on truckin'.

#### What actually happened
Chrome-dome.

#### Steps to reproduce
Just spawn as a xenochimera.

### PR DESCRIPTION
**Pull request by Cameron653**
Gives them hairstyles, and all the species specific hairstyles, since they're really odd creatures
Fixes #408

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Please reference issues when you fix them or resolve them.

**Comment by Cameron653** [comment]
Ah, sorry about that. I keep forgetting about that.
#408

**Comment by SpadesNeil** [comment]
No prob.

**Comment by Cameron653** [comment]
Looked it back over, everything seems done and ready for merge.

**Pull request merged**
