### PR TITLE
Resprites Crates (And stuff like the cargo tug)

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
:cl: Toriate
imgadd: All regular crates and large crates now have new sprites, made by yours truly.
/:cl:

dreamseeker_fJBkArqi8X

This PR will resprite all crates. The new sprites have more detailed bits (e.g. lids that actually have thickness) on them, and are in 3/4ths perspective. The blood pack crate has also received a new unique sprite.

Large crates are also included in this PR. For instance:
5kGKigMTlA
(Yes I'm aware those have been dummied out)
MGJjltpFqp
ed7vRDNdQe

The regular crates are completely original creations of mine, but the large crates are modified from Eris and TG (Critter crate) sprites.

ToricratesRemasteredPreview2

Depending on the reception this PR receives, I might go ahead and resprite a bunch of things into 3/4ths perspective in future PRs.

### CODE REVIEW

**Comment by Verkister** [comment]
Neat stuff. Would like to see the mob crates made more like the new critter crates though, especially with the significantly decreased largeness of the new largecrates making them even less ethically appealing than before. The miniature shipping containers look like an interesting idea totally calling for a nifty truckbed redesign on the cargo tugs as well heh

**Comment by Michiyamenotehifunana** [comment]
dreamseeker_nREEOLcXKa

Cargo tugs are now using Eris' sprites with new North and South facing sprites made by me. The truckbeds/trailers now have a slightly extended forklift-like structure that'd support the corners of the miniature shipping containers.

In lieu of actually making the mob largecrates more ethically appealing, I've made them use the lisacrate iconstate which has holes poked in it for air. I'd just move all the mobs into the critter crates, but from what little testing I've done, it seems that mobs can't actually spawn in them.

**Comment by SpadesNeil** [comment]
We should port this to Polaris later. Or I'm sure Polaris will come get it if they like it.

**Comment by KasparoVy** [comment]
These sprites are bomb, gj!

**Comment by Ketrai** [comment]
I like the sprites, but they don't really fit in with the rest of the station palette, much like how our ladders kinda curse with the rest of low-contrast no-shine land. Really, we'd need to get rid of our walls for something shinier for these to fit in, or at least resprite floors/closets to have a bit more chrome.

**Comment by Ketrai** [comment]
Also as bluehaus brought up, the perspective on the crates is 3/4th, meaning you can only see top and front. Most of the sprites on station are drawn in cabinet, meaning you can see front, side, and top. Without this level of depth these crates end up looking mightily flat, and out of place.

**Pull request merged**
