### PR TITLE
Remove reaction reagent powergaming

### PR DESCRIPTION
**Pull request by Arokha**
Don't just delete all the reagents in our mob simply because there was a reaction. That doesn't make any sense. Pls.

image

### CODE REVIEW

**Comment by Cyantime** [comment]
Time to fill someone with water and hook them up to a potassium IV for constant explosions.

**Comment by SpadesNeil** [comment]
Medical outrage in 3... 2... 1...

**Comment by Burrito-Justice** [comment]
I've neither used this nor seen it used (outside of accidentally tossing potassium in a beaker when I was making cryoxadone) so I'm not outraged.

_yet._

**Comment by Arokha** [comment]
I've seen it used a couple of times. :p

**Pull request merged**
