### PR TITLE
Blood Reagents Refactor

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Expands on #15361 by bumping the blood-regen handling up a level and comparing the reagent id to a species-level blood_reagent variable for regen purposes.

You can set your blood regen reagent under the VORE tab alongside blood colour, from a list of pre-approved types. Your chosen reagent will be shown on health analyzers and in your medical records.

Also makes slime jelly the default blood regen reagent for prometheans because why not?

### CODE REVIEW

**Comment by Heroman3003** [comment]
There's per-trait customization now, no? I think stuff like winged flight having toggle on default behaviour and such. Could that be used for blood type selection?

**Comment by KillianKirilenko** [comment]
Mmmmmaybe. It looks like I'd need to extend the functionality of that... well, function, since it only supports booleans and colours right now.

**Comment by KillianKirilenko** [comment]
I think I figured out a fix, I just need to offload the handling to the VORE tab instead, so it'll be with blood colour rather than blood type. Will test in a little bit.

**Comment by KillianKirilenko** [comment]
Now it works! Just needs review for the actual allowed reagents for blood recovery.

**Comment by SatinIsle** [comment]
I support this addition, it's really cool customisation, but I'd like this information to be presented on medical devices.
Mostly: Health analysers and body scanners. Possibly in medical records too.

**Comment by Heroman3003** [comment]
Noble-metal-based blood is a meme but an okay meme. Sure, lesgo.

**Comment by KillianKirilenko** [comment]
> Noble-metal-based blood is a meme but an okay meme. Sure, lesgo.

They were mostly just placeholders whilst I was testing the system. I was expecting a little more feedback on allowed reagents before merging!

**Pull request merged**
