### PR TITLE
Vore transform overhaul

### PR DESCRIPTION
**Pull request by ShadowLarkens**
Instead of the derpy, broken ass transform modes, you can just now open a damn appearance changer panel. For feature parity, the appearance changer (in all instances including mirrors... don't question how a spider taur can look in the mirror and become a fat wolftaur, it's *fine* >.>) is now able to style ears, tail, and wings.

### CODE REVIEW

**Comment by Huenererschrecker** [comment]
You did it. You crazy son of a b, you did it!

**Comment by pontifexminimus2** [comment]
:pog:

**Comment by KillianKirilenko** [comment]
And here I'd just noticed the appearance changers for ERT/Traders/etc. didn't support ears and tail. Nice work!

**Comment by Heroman3003** [comment]
Changing ears/tail/taur/wings via mirror seems very ehh... Other than that it's good. Although big aspect of markings is missing, I do think its still a net improvement.

**Comment by Cyantime** [comment]
Regular mirrors should probably only be able to recolor tails/etc, since they can already recolor hair, but huge transformations that are usually limited to resleeving stuff being available from every mirror on the station is sorta dumb.

**Comment by ShadowLarkens** [comment]
>.>
what existing appearance changer flag should I use, then? 
Tying it to Hair style was the easiest one to use.

**Comment by Cyantime** [comment]
APPEARANCE_RACE is the closest thing for general species changes, there isn't really anything good for levels between "take a human and make them a drider with bat wings" and "add cat ears"

**Comment by pontifexminimus2** [comment]
Is there any progress on this? Or is this in development hell. 

because this is a very good PR and is worth pursuing further.

**Pull request merged**
