### PR TITLE
Adds 2 New Ears, a Tail & a Few Markings

### PR DESCRIPTION
**Pull request by KasparoVy**
I'm straight up in love with the character creator, it absolutely rocks & I feel like I've sank more time screwing around with it than actually playing

I've been sitting on these sprites/this PR for bloody ages & really wanted to use at least some of them lmao.
There is actually sprites for vulp-style Ward-Takahashi roboparts but I left that out of this PR.
There was also a finished re-skinning system to allow for use of different ORGANIC bodypart sprites (whitelisted per-species, selectable in the same manner as synthetic limbs) but that was also left off.

### **Changes:**

- Adds short/terrier & thin/jackal Vulpkanin ears (dual-colourable)
- Adds a dual-colourable tail inspired by Ward-Takahashi cybernetics.
- Adds a few markings:
- --> Vulp Short Nose (shifted 1 pixel closer to the face in the east/west sprites -- usefor for people leveraging Sergal heads/etc. to create face shapes as seen below)
- --> Vulp Alt. Face (Vulpine facial hair but in marking form)
- --> Taj Alt. Nose (Tajaran nose marking but colour mult & the same colour in all dirs)
- --> Talons (Inspired by Ward-Takahashi Spirit markings)
- --> Claws (Inspired by Ward-Takahashi Spirit markings)

### **Sprite showcase:**
_Using the vulp short nose, claws & talons_
virgo ss13 vahrr nazha with claws and talons markings 20200502

_Using the new vulp thin ears, claws & talons_
virgo ss13 jackal vulp with new ears and markings 20200502

_Using new vulp short ears, vulp alt. face, cybernetic tail, claws & talons_
virgo ss13 ward takahashi vulp with new ears and markings 20200502

### CODE REVIEW

**Comment by KasparoVy** [comment]
Closing and re-opening to see what's up with my man Travis here

**Comment by KasparoVy** [comment]
Yeah Travis ain't feeling it, oh well.

**Comment by Arokha** [comment]
Those are neaaaaaaat

**Comment by KasparoVy** [comment]
Sorry for the late response-- slept most of the day

It looks like the diff (while detecting modifications) those icons are actually the same but since they're identified (corvidbelly, zbody, eggnerd/eboop, otternose & tentaclemouth) changes can be reverted

**Pull request merged**
