### PR TITLE
Mob tf smite

### PR DESCRIPTION
**Pull request by SatinIsle**
Added a new smite called Mob Transformation that allows staff to turn anyone into another mob using the same methods as mouse rays/polymorph/beastform, except with no limits.

Added a player effects panel "Fix" option to revert mob TF that will work on the aforementioned smite and any other methods that use the same type of mob TF.

### CODE REVIEW

**Comment by Kashargul** [comment]
No more bundles on repo.

**Comment by SatinIsle** [comment]
> No more bundles on repo.

Do I just delete them from this then?

**Comment by Kashargul** [comment]
> > No more bundles on repo.
> 
> Do I just delete them from this then?

Yes, compilation is handled server side now

**Comment by SatinIsle** [comment]
> Yes, compilation is handled server side now

Alrighty, think I did it properly!

**Pull request merged**
