### PR TITLE
part 2 borg customization - First downstream of new dullahan sprites.

### PR DESCRIPTION
**Pull request by Asher-42**
should be finished now, no code yet as the decals PR hasnt been merged, but heres the file.

* everything but the -sit has headbob animations as the -sit is rarely used.

current: 
image

### CODE REVIEW

**Comment by Asher-42** [comment]
swapped dullahan janitor and science sprites around

**Comment by Asher-42** [comment]
added command, forgot. ready now.

**Comment by Heroman3003** [comment]
Tell me when you've implemented those

**Comment by Asher-42** [comment]
> Tell me when you've implemented those

should be good now, but id scan the names in case i missed something.

also fixed an issue that a janitor k4t was labeled mining

**Pull request merged**
