### PR TITLE
Added "Circuit Programmer" to scientist alt-titles

### PR DESCRIPTION
**Pull request by Pear120**
Just a new title, no new loadouts.

### CODE REVIEW

**Comment by Cameron653** [comment]
Add the edit to z_all_jobs_vr.dm instead of editing a stock .dm file.

**Comment by SpadesNeil** [comment]
Why not just "programmer"? Less vague.

**Comment by Jakksergal** [comment]
Wouldn't "Circuit Designer" or "Hardware Designer" be a bit more accurate? They don't actually program anything.

**Comment by Pear120** [comment]
Github is confusing as fuck as-is. I'm closing this and starting another.

**Comment by Jakksergal** [comment]
All you had to do was add //VOREstation edit to the end of the line and push another commit, mang.

**Comment by Pear120** [comment]
Ain't nobody got time fo' dat.

**Pull request closed without merging**
