### PR TITLE
Toggle Overlay for the various kinds of goggles

### PR DESCRIPTION
**Pull request by Very-Soft**
image

image

image

image

### CODE REVIEW

**Comment by Sageofaether12** [comment]
very poggers and very doggers, thank you soft

**Comment by BonniePandora** [comment]
Thank god, now I can mine without a migraine-inducing overlay _having_ to be plastered across my screen.
Very noice

**Comment by Novacat** [comment]
We talked about this a bit in staffchat, and, mostly want to bring a couple of points from there.

- There should be some visual indicator that you are wearing vision-enhancing goggles. Especially since it is a really, really bad idea to weld while having them on.
- You can already toggle the goggles on/off without having to take them off.

My own personal thought is that having enhanced vision should have downsides, and I am not a fan of the idea of just being able to turn this on at the start of the shift and just forget you have them.

That said, the colors of some of the special visions (esp mesons) are a bit irritating and could probably be changed to something less eye-grating.

**Comment by Very-Soft** [comment]
Not desired per staff discussion

**Pull request closed without merging**
