### PR TITLE
Adds warning signs to the entrance of the underdark

### LINKED ISSUE #3575: Underdark doesn't have any warning for new players
#### Brief description of the issue
There's no access restrictions on the underdark.

#### What you expected to happen
For the doors to have access restriction, so not any random civilian can walk out there.

#### What actually happened
Two civilians almost died.

#### Steps to reproduce
Be a civilian
Go to the underdark
Find that the doors aren't access restricted.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
Would be neat if only xenoarch, cargo, security and medical would be able to access the area. So others have to ask for authorization first. Maybe also an update to the SoP about the underdark?

### PR DESCRIPTION
**Pull request by Very-Soft**
Fixes #3575 by adding some bones, and a couple of helpful warning signs

bonesnstuff

Adds a new Dangerous fauna sign 
h_life

Also a graffiti sign by @Verkister !
pis off

(Suggested by Seiga)

image

### CODE REVIEW

**Comment by Ketrai** [comment]
👍

**Comment by SpadesNeil** [comment]
We should probably sprite an actual sign if possible.

**Comment by Verkister** [comment]
pis

**Comment by KasparoVy** [comment]
Bahaha, bloody fantastic

**Pull request merged**
