### PR TITLE
Updates Listening Post gateway submap

### PR DESCRIPTION
**Pull request by Heroman3003**
Title. Refluffs it in the merc-removing flavor.

Also, properly removes snow outpost submap from the pool, which @Novacat seems to have tried to do, but not in the right place? If it is wanted to stay, just say so.

### CODE REVIEW

**Comment by Meghan-Rossi** [comment]
Those dates are all in the future compared to station time (currently 2321).

**Comment by Heroman3003** [comment]
I intentionally left the dates on old logs wrong. I also wrote in a small excuse as to why that is (and why they reference now-noncanon events)

**Comment by Sebbe9123** [comment]
> Those dates are all in the future compared to station time (currently 2321).

Gateway isn't neccessarily tied to station lore, you can have magic and shit inside the gateway maps if you want to, just not on the actual station.

**Comment by Heroman3003** [comment]
> Gateway isn't neccessarily tied to station lore, you can have magic and shit inside the gateway maps if you want to, just not on the actual station.

Gateway 100% is tied to station lore, or at least lore of same universe. No magic in the setting.

**Comment by KillianKirilenko** [comment]
Wrong files there, I think. You (accidentally?) altered the april fools tether submaps & defines not the main tether ones.

**Comment by Heroman3003** [comment]
Ah, whoops, lemme just--

**Pull request merged**
