### PR TITLE
Fixes the infina-scoped-rifle bug

### PR DESCRIPTION
**Pull request by BonniePandora**
List adjusted to match the others, so by all accounts this _should_ fix it, it's a dirty webedit PR so here's hoping at least.
Fixes #[12510](https://github.com/VOREStation/VOREStation/issues/12510) hopefully

### CODE REVIEW

**Comment by WinterDarkraven** [comment]
You ruined the fun!

Merge this please infinite guns is no way to tide... no effort...

**Comment by KillianKirilenko** [comment]
This seems like a kinda daft way of handling it anyway. Crafting menu feels like a solution looking for problems.

**Comment by BonniePandora** [comment]
> This seems like a kinda daft way of handling it anyway. Crafting menu feels like a solution looking for problems.

Probably is! I'm not the one who ported/added the stuff though so I'm just fixing up a bug, it'll be on them to do anything beyond that.

**Comment by KillianKirilenko** [comment]
> Probably is! I'm not the one who ported/added the stuff though so I'm just fixing up a bug, it'll be on them to do anything beyond that.

Yeah, not saying it's your fault or anything, just generally musing out loud.

**Pull request merged**
