### PR TITLE
Port all xenobio slime sprites from Eris

### PR DESCRIPTION
**Pull request by Arokha**
Icondiffbot!

### CODE REVIEW

**Comment by Very-Soft** [comment]
Some of the sprites in the icondiff bot look a bit funky with part of it is missing in one of the frames. Can you confirm whether that's so in the actual sprite animation?

https://camo.githubusercontent.com/521ef8fcb0649e49fca3e4f0b4170d17e7b26dd1c03a5fa54068e3dea5735345/68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f35383237363334322f323934383235313930312f322f61667465722e676966

I love these sprites overall, but if that's messed up in the actual sprite it should be fimx't

**Comment by Arokha** [comment]
> Some of the sprites in the icondiff bot look a bit funky with part of it is missing in one of the frames. Can you confirm whether that's so in the actual sprite animation?
> 
> https://camo.githubusercontent.com/521ef8fcb0649e49fca3e4f0b4170d17e7b26dd1c03a5fa54068e3dea5735345/68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f35383237363334322f323934383235313930312f322f61667465722e676966
> 
> I love these sprites overall, but if that's messed up in the actual sprite it should be fimx't

image

That's an IDB bug

**Comment by Heroman3003** [comment]
To note, this won't look nearly as good in the game. Our xenobio, iirc, only uses grey slime sprites and applies coloration, so with them being way darker, it's going to be big pain to get colors old right. Not to mention the 'shininess' overlay.

Also, expressions are gone, which were kind of a very important visual cue to slime mood/behaviour in our system, which is also bad.

Sprites look fine, but clearly not made for our xenobio system.

**Comment by Arokha** [comment]
> To note, this won't look nearly as good in the game. Our xenobio, iirc, only uses grey slime sprites and applies coloration, so with them being way darker, it's going to be big pain to get colors old right. Not to mention the 'shininess' overlay.
> 
> Also, expressions are gone, which were kind of a very important visual cue to slime mood/behaviour in our system, which is also bad.
> 
> Sprites look fine, but clearly not made for our xenobio system.

What're you talking about? It's the same xenobio system. The expressions are there too, if they aren't in IDB that's an IDB bug or they didn't change (probably that one).

Maybe the extra sprites are useless (or maybe we should switch to using those) but even the grey one has nicer transparency and shading than our current ones.

**Comment by Very-Soft** [comment]
image

**Comment by Very-Soft** [comment]
> To note, this won't look nearly as good in the game. Our xenobio, iirc, only uses grey slime sprites and applies coloration, so with them being way darker, it's going to be big pain to get colors old right. Not to mention the 'shininess' overlay.
> 
> Also, expressions are gone, which were kind of a very important visual cue to slime mood/behaviour in our system, which is also bad.
> 
> Sprites look fine, but clearly not made for our xenobio system.

So I'm not an expert on the matter or anything but I am pretty sure the slimes use their unique sprites, elsewise rainbow slimes and bluespace slimes wouldn't look as different as they do.

**Comment by Heroman3003** [comment]
> 
> 
> image

I literally couldn't see that because I don't use git lightmode. Thanks, that solves that mystery.



> 
> 
> > To note, this won't look nearly as good in the game. Our xenobio, iirc, only uses grey slime sprites and applies coloration, so with them being way darker, it's going to be big pain to get colors old right. Not to mention the 'shininess' overlay.
> > Also, expressions are gone, which were kind of a very important visual cue to slime mood/behaviour in our system, which is also bad.
> > Sprites look fine, but clearly not made for our xenobio system.
> 
> So I'm not an expert on the matter or anything but I am pretty sure the slimes use their unique sprites, elsewise rainbow slimes and bluespace slimes wouldn't look as different as they do.

Nope. Those two simply use 'overrides'. Most slimes use coloration with potential addition of shiny/lit overlay. The REAL icon file used for slimes on our codebase is slime2.dmi, not slimes.dmi.

**Comment by Arokha** [comment]
GRUNT. Heroman is correct, these sprites are unused. I'll come back and do it for rainbow and bluespace later.

**Pull request closed without merging**
