### PR TITLE
Add an audible alarm sound to SM Delamination

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
Does what it says. You cannot possibly miss SM delams now, even with a headset off. The sound isn't terribly loud, unless you're deepthroating an intercomm, because it uses the intercomms to play.

### CODE REVIEW

**Comment by Novacat** [comment]
Either needs vorestation edits, or to be kicked to Polaris.

**Comment by parasitoide** [comment]
I'm planning on porting this to Polaris, could I ask the source of this sound to ensure it's license-compliant?

**Comment by SpadesNeil** [comment]
@Rykka-Stormheart you're not on the Discord so I can't contact you but yeah sourcing is important. Otherwise I gotta revert this.

**Comment by Rykka-Stormheart** [comment]
> @Rykka-Stormheart you're not on the Discord so I can't contact you but yeah sourcing is important. Otherwise I gotta revert this.

Source is from Baystation's files: 
https://github.com/Baystation12/Baystation12/blob/dev/sound/ambience/matteralarm.ogg

**Comment by SpadesNeil** [comment]
Works for me.

**Pull request merged**
