### PR TITLE
Raise limit on bellies

### PR DESCRIPTION
**Pull request by Arokha**
For ~~Tempest~~ anyone who wanted to have more than 10 like a *crazy person*

### CODE REVIEW

**Comment by SpadesNeil** [comment]
how

why

**Comment by Arokha** [comment]
***CHAKATS***

**Comment by Wickedtemp** [comment]
Um.
I currently have all 10 slots used, plus an additional 1-2 slots saved on Google docs so I can copy/paste and switch them out ingame when I want to use them. 

And I have ideas for 5 more that I would use. 

I had honestly thought that there were other people who may be having this issue, but it might actually just be me. Apparently the vore panel limit can't be changed per Ckey, though.

**Comment by SpadesNeil** [comment]
y tho

**Comment by Wickedtemp** [comment]
Wh-what's wrong with having more bellies? :p 

I think Ace is worried that they're going to have to tour each one!

**Comment by SpadesNeil** [comment]
;-;

**Comment by Wickedtemp** [comment]
So West brought it to my attention that they have also reached the vore panel limit, I'm not the only one!

ITS NOT JUST ME! AHAHA!

**Comment by SpadesNeil** [comment]
god damn it fine

fkkin weirdos

**Pull request merged**
