### PR TITLE
Adds Alexis's ancient wand

### PR DESCRIPTION
**Pull request by stobarico**
The approved application: https://forum.vore-station.net/viewtopic.php?f=26&t=1108 (It also has the images, sound and code)

### CODE REVIEW

**Comment by Yoshax** [comment]
If you wanted, you could probably do a spawn sparks on the attack_self, see igniters for that. Seems like that's kinda what you were going for, and would make it have some visual feedback too. Also you didn't change the description :P

**Comment by stobarico** [comment]
Yeah, i planned on doing that, but it got waaay too difficult for me, literally spent 2 hours trying to do it, i will try fiddling with it again, also going to change the name and description, probably forgot to update it after i tested the item one last time

**Comment by stobarico** [comment]
I'm going to get back on it tomorrow, but if anyone can help me, here's the link: http://piratepad.net/W6PPKPAZaX
My current problem is that the sparks aren't actually comming out

**Comment by stobarico** [comment]
Please do not merge yet, as currently the sparks do not delete themselfs, i will fix that tomorrow

**Comment by stobarico** [comment]
This is ready to be merged

**Comment by Yoshax** [comment]
Huh. Did you test that?

**Comment by stobarico** [comment]
I did, works just fine, with the cooldown, the message and the sparks (Also made sure they disappeared, they do now)

**Pull request merged**
