### PR TITLE
Makes the thermal vision NIF software illegal.

### PR DESCRIPTION
**Pull request by Cyantime**

### CODE REVIEW

**Comment by Natje0** [comment]
It's already locked to Director Access(Or something like that). I think it's fine that way, tbh...

**Comment by SpadesNeil** [comment]
I don't think it should even exist tbh.

**Comment by Cyantime** [comment]
It's currently available to anyone with captain access, combat cyborgs that are only available during code red and bound by laws had theirs taken away, does the captain get a pair of (undetectable) thermals?

**Comment by SpadesNeil** [comment]
That is why it shouldn't exist.

**Comment by Cyantime** [comment]
Making them illegal is pretty similar to not existing, the machine needs to be both hacked and emagged for someone to get them. They also fit better with the other combat software, like the one that generates an egun.

**Comment by kcin2001** [comment]
illegal would work probably

**Comment by SpadesNeil** [comment]
I don't think that one should exist either!

But at least if it's illegal medical crew will generally be like "NO I WON'T INSTALL THAT! IN FACT I'M CALLING SECURITY!"

**Comment by Cyantime** [comment]
You don't install nifsofts, you just go to a vendor and then you have them. You only need to have the nif itself installed by medical.

**Comment by kcin2001** [comment]
Ace medical doesnt install the software only the hardware

**Comment by SpadesNeil** [comment]
Oh. <_>

**Comment by SpadesNeil** [comment]
tbh thermal and weapon nifs should be _removed_

**Comment by Ketrai** [comment]
Why? they're really hard to get. e.g you need to emag and hack the nifsoft machine. (altho emags are rather rare) then they're SO expensive you need to be a high paying job before you can even get them. and if anything people rarely use em, ever.

**Comment by Renkindle** [comment]
I've never seen the illegal weapon NIF software even used before because of those hurdles to get to it.

**Comment by SpadesNeil** [comment]
Expect me to abuse this.

**Pull request merged**
