### PR TITLE
Swap chemmaster, port beaker sprites

### PR DESCRIPTION
**Pull request by Arokha**
They have little label sprites as well for when you label them. And non-wooden lids I dunno why they were wood before.
Beakers from Eris, though /tg/'s are very similar, but a headmin liked these more than /tg/'s.

image

### CODE REVIEW

**Comment by Ketrai** [comment]
Can we please have a condimaster with labeled 60 u bottles again T-T

**Comment by SplinterGP** [comment]
does it have transparency ? would be good to have

**Comment by Very-Soft** [comment]
I do like these more than the old ones. They look real good and depthy!

**Comment by Heroman3003** [comment]
I feel like the liquid itself inside the jar shouldn't be as 'shiny' but that's kinda nitpicky.

**Pull request merged**
