### PR TITLE
Disables Gateway

### PR DESCRIPTION
**Pull request by Novacat**
I am tired of this WIP being left a WIP on live, so I am just going to outright disable it until we get a better variety of maps.

### CODE REVIEW

**Comment by Sebbe9123** [comment]
Bro what the fuck is this, where's the discussion?

**Comment by dwinters99** [comment]
Third explo content removal this month? I really do hope something is being planned behind the scenes.

**Comment by Sebbe9123** [comment]
Ascian, you need to make a new gateway contest thing, not take away content because YOU don't like it. If this stays merged, you ARE OBLIGATED to remove genetics too since that shit is literally broken and not even a WIP.

**Comment by Novacat** [comment]
The discussion was had, and this was the conclusion that was brought. Also, genetics is effectively disabled, considering all the roundstart machinery is gone for it.

**Comment by dwinters99** [comment]
Did the discussion involve ANY non-staff?

**Comment by Sebbe9123** [comment]
> The discussion was had, and this was the conclusion that was brought. Also, genetics is effectively disabled, considering all the roundstart machinery is gone for it.

Okay so how do I un-disable gateway mid round then like anyone can do with genetics? :)
And who did you have this discussion with, cuz I sure af wasn't invited.

**Comment by TheDavestDave** [comment]
the discussion was on discord across multiple channels, at least with non-staff. And it's gonna be quite hard to refer back to

my understanding is that staff are upset about rushing into the gateway soon as and no one taking it serouisly. It's only been held on so long hopeing that someone make better maps for it, but ascian should recapped instead of what I remeber

I think it's worth noting that if it is removed it's very unlikely it'll ever be readded

**Comment by Novacat** [comment]
As mentioned in the PR, the only reason it was removed was due to a lack of variety of maps. Once more maps are added in, the gateway will be re-enabled again. It is not like genetics or blueshield where they were removed for other reasons.

**Comment by dwinters99** [comment]
I agree with DavestDave. The likelyhood of this ever being devved for and being readded is EXTREMELY low.

**Comment by Sebbe9123** [comment]
> As mentioned in the PR, the only reason it was removed was due to a lack of variety of maps. Once more maps are added in, the gateway will be re-enabled again. It is not like genetics or blueshield where they were removed for other reasons.
> 
> The gateway structure will remain for admins to do adminbus things with.

But then... remove v2 and v4 then, they're the same maps and doesn't have variety either?

**Comment by TheDavestDave** [comment]
it has problems I don't think it's map varierty. The current map rotations suck. Only way they are dangerous is with admemes so no one treats them as such, we just get told off in discord for not. Most people who still do gate way rush them so there's not even a chance for admins to set things up

**Comment by Sebbe9123** [comment]
> it has problems I don't think it's map varierty. The current map rotations suck. Only way they are dangerous is with admemes so no one treats them as such, we just get told off in discord for not. Most people who still do gate way rush them so there's not even a chance for admins to set things up

Admins can make spooky announcements after setting shit up AFTER though, if they miss the window. They literally have build mode and a million other tools to do all this stuff.

**Comment by Verkister** [comment]
Nobody wants to set up events as afterthought just to be replayed through by the same rushers.

**Comment by nerdass** [comment]
rushers are why people hate explorers

**Comment by Sebbe9123** [comment]
> Nobody wants to set up events as afterthought just to be replayed through by the same rushers.

Nobody wants to set up events anyways though, unless the event has a chance of getting someone banned or has a chance of making massive player drama that drives everyone super toxic because of administrative actions.

**Comment by nerdass** [comment]
that's a lot of words for saying everyone else is the problem lol

**Comment by DemicusMaximus** [comment]
I will say that _I personally_ would prefer it to stay, but I understand why its being removed.

As for my second point, don't be a snide prick to Nova just because you don't like a change. Criticize all you want, its why this program exists, but don't be an ass about it.

**Pull request merged**
