### PR TITLE
Adding Shading to Mushroom Cap

### PR DESCRIPTION
**Pull request by LiquidFirefly**
Should've been there before, I'm just a moron and accidentally put the wrong version into the .dmi, and somehow didn't notice on the test build.

### CODE REVIEW

**Comment by Heroman3003** [comment]
Conflicts, sorry, resolve pls

**Comment by Heroman3003** [comment]
Uh, I see your commit but the conflict is still there

**Comment by LiquidFirefly** [comment]
You have to mark it resolved.   There are no coflicts I can see.   Look at the file.

**Comment by Heroman3003** [comment]
изображение
And manual solving is impossible because its a binary file.

**Comment by LiquidFirefly** [comment]
I'll just make a new pull when I get home.   Ugh.

**Comment by LiquidFirefly** [comment]
#14677

**Pull request closed without merging**
