### PR TITLE
Port Eris mining satchel sprites, satchel of holding

### PR DESCRIPTION
**Pull request by Arokha**
NdGATcNTJv

SoH is in the ORM vendor and science can also make it

### CODE REVIEW

**Comment by ShadeAware** [comment]
God, that inside is pretty

**Comment by SplinterGP** [comment]
i think the sprite is pretty good just needs some straps around like the old one did, feels a bit too plain the normal one

**Comment by KasparoVy** [comment]
Hell yeah! This is going to be so damn handy. I love the sprite for the SoH.

**Comment by Very-Soft** [comment]
ME LIKE

**Comment by Heroman3003** [comment]
I like the second one but colors on first one are kinda too washed out.

**Pull request merged**
