### PR TITLE
Asteroid Janitor Closet and Bathroom

### PR DESCRIPTION
**Pull request by klaasjared**
Adds the requested asteroid bathroom and janitor closet with some scatted vendors that were never added.

That's it.

That's the PR.

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
For the record, as stated in dev-general, this is DNM pending testing on OP's computer.

**Comment by klaasjared** [comment]
Tested it, it works now, also squeeked out some bugs I found while doing it

**Comment by Arokha** [comment]
Mlemflicts

**Comment by klaasjared** [comment]
oh holy fuck

**Comment by klaasjared** [comment]
right, nuking this and re-posting to fix

**Pull request closed without merging**
