### PR TITLE
Makes Meteors Less Powerful

### PR DESCRIPTION
**Pull request by Cameron653**
It caused a _huge_ breach and put phoron throughout the entirety of the station. This decreases it so there's not a guaranteed breach, and that the explosion isn't as utterly massive as it was before.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
oh lol, yea, good idea

**Comment by Cyantime** [comment]
Booooo.

**Comment by Cameron653** [comment]
@Cyantime You forced me to use the fix-atmospheric-grief button ;v

**Comment by Cyantime** [comment]
The meteor itself didn't breach the atrium, it was people later on opening doors and firelocks that flooded it. That's the real problem, any minor breach can instantly turn into a station-crippling one because of how absurdly open the surface levels are.

**Pull request merged**
