### PR TITLE
Add optional selectable fullscreen belly overlays with pred & prey prefs

### PR DESCRIPTION
**Pull request by ShadowLarkens**
This is a first-stage system. There's a fairly limited selection of options that can be improved by spriters, and some improvements to be made some point in the future, such as being able to color the overlay or introducing ckey-locked belly sprites.

Prey pref

Pred pref (per-belly)

Webm in action
https://i.tigercat2000.net/2020/08/CGbnpFY0e8.webm

Notice in the chat for hud disabling

### CODE REVIEW

**Comment by KasparoVy** [comment]
Wooooahh that's dope. I remember seeing some of Soft's work on synth bellies so I imagine once this does the rounds in the discord we'll see more overlays pretty soon!

**Comment by FlintlockDaFox** [comment]
I hope this gets added. it would be really neat.

**Comment by JoanRisu** [comment]
Has this been extensively tested to make sure things are properly working?

**Comment by Very-Soft** [comment]
Specifically, I want to make sure that when the prey turns this off, but the pred has it turned on, that the prey is not just blind/stuck in darkness.

**Comment by ShadowLarkens** [comment]
I already tested this pretty extensively, no matter what circumstances there are, the prey turning off blindness overlays will 100% of the time remove them from their vision

**Comment by ShadowLarkens** [comment]
Specifically, I ensure that prey's toggle always works by the following:
 - Toggling it off will immediately run clear_fullscreen to get rid of the fullscreen overlay on the belly key
 - Prey with the toggle off will not even have overlay_fullscreen called when they're eaten
 - Every process tick the belly will check the preferences of prey, and if they have the preference toggled off, it clears the fullscreen on the belly key
 - Toggling the preference off will make your hud show back up if it was previously disabled

**Pull request merged**
