### PR TITLE
Adds more clothing from Polaris and various sources

### PR DESCRIPTION
**Pull request by GhostActual**
Ports the clothes from the Mirror that was broken and organizes them as such. Also fixes some of the sprites to match the art style. And adds a bonus helmet for the Major Bill's Flightsuit. Also adds another bonus frontier void suit for the Vulp. Also adds new and modified firefighting gear I yoinked from an in-progress PR from Polaris and ports a new fire extinguisher from Skyrat to compliment the new fire gear.

The Mirror that this fixes:
https://github.com/VOREStation/VOREStation/pull/11539/files

### CODE REVIEW

**Comment by KasparoVy** [comment]
Nice. Cheers!

**Comment by GhostActual** [comment]
I realize that the Fire Equipment could have been put into a new PR but since the equipment is mostly clothing-related I decided to add it all to this.

**Comment by Very-Soft** [comment]
Seems fine from what I can tell, feel free to undraft

**Comment by GhostActual** [comment]
I'll solve conflicts tomorrow

**Pull request merged**
