### PR TITLE
Makes corner decals less anal about placement order.

### PR DESCRIPTION
**Pull request by chaoko99**
Does this even NEED a changelog?

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Fucking with layers is generally not a good idea actually now that I think of it.

**Comment by chaoko99** [comment]
Works fine locally. What you guys really need is a proper set of defines and whatnot for planes and layers (Why don't you actually?)

**Comment by chaoko99** [comment]
BLeh. Polaris actually could use a proper plane master port.
I'll do it later.

**Comment by SpadesNeil** [comment]
Kay.

**Pull request closed without merging**
