### PR TITLE
Gives Noodle his own pen next to Chaplain's Office! <3

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
With windows so you dorks can peek. <3

### CODE REVIEW

**Comment by Heroman3003** [comment]
Against, primarily due to the fact that it removes connection to maintenance on floor 1 below via ladder, which was pretty important connection point

**Comment by Very-Soft** [comment]
Yah I'm pretty well in agreement with heroman. I'd prefer we didn't lose the vertical access point there. I'm pretty sure there's spots around there to move the ladder to, if you wouldn't mind.

**Comment by Very-Soft** [comment]
> Actually, we already have a free access point back when I overhauled the surface Civvy subgrids a bit. Can probably remove the access restriction on the door where part of the old bar maint is. A bit north of the janitor closet.

Yeh but they could put the ladder at the end of the little hall there like, a few tiles over from where it used to be ezpz, and just have it come out on the side there.

**Comment by Very-Soft** [comment]
Also also also also. Important point I just noticed. This removes medical access to the crematorium. The back door that leads in there has medical access, for allowing medical to dispose of bodies, which was added to the chapel's stuff a while back. 

Somewhat important.

**Comment by Very-Soft** [comment]
Additionally. I just wanted to ask, why the chaplain? 

Why not like, pathfinder pet? Or warden on surface security? Or just kind of general atmos pet, since he was already in engineering.

Not that I particularly mind noodle going to the chaplain, just, it's a bit unconventional for the chaplain to get a pet.

**Comment by Rykka-Stormheart** [comment]
> Additionally. I just wanted to ask, why the chaplain?
> 
> Why not like, pathfinder pet? Or warden on surface security? Or just kind of general atmos pet, since he was already in engineering.
> 
> Not that I particularly mind noodle going to the chaplain, just, it's a bit unconventional for the chaplain to get a pet.

Scree asked/suggested the chaplain get a pet.

Regarding the ladder, I'll see what I can do.

**Comment by Very-Soft** [comment]
Well! If I could make a suggestion on the shape of things:

chapelpet

Something more like this shape would allow for both the snake and the intended function of that back room to both coexist in this space. I do think that having more vertical access points is important, and shouldn't be taken for granted. And medical really should be able to access the crematorium.

**Comment by Rykka-Stormheart** [comment]
> Well! If I could make a suggestion on the shape of things:
> 
> chapelpet
> 
> Something more like this shape would allow for both the snake and the intended function of that back room to both coexist in this space. I do think that having more vertical access points is important, and shouldn't be taken for granted. And medical really should be able to access the crematorium.

I can do that! <3

**Comment by Rykka-Stormheart** [comment]
Fixed

**Comment by Screemonster** [comment]
> Additionally. I just wanted to ask, why the chaplain?
> 
> Why not like, pathfinder pet? Or warden on surface security? Or just kind of general atmos pet, since he was already in engineering.
> 
> Not that I particularly mind noodle going to the chaplain, just, it's a bit unconventional for the chaplain to get a pet.

because giving the chaplain a little garden with a serpent in it appeals to my sense of humour

I wanted an apple to spawn in there too

**Comment by Very-Soft** [comment]
omg I only just now got the joke

**Comment by KasparoVy** [comment]
Sheer class

**Pull request merged**
