### PR TITLE
Changes wall damage from being (usually) 25 brute to 12 and doesnt add a stun to it

### PR DESCRIPTION
**Pull request by ReoDaProtovali**
25 damage for a wallthrow is pretty extremely high. That's higher than some low calibre bullets! It also turns bones into powder because your bones are made of glass. This makes the damage lower but it has a stun when you hit wall because oof ouchy. I dont think "speed" is ever passed in so the default value of 5 was always used. Consistency is also nice

### CODE REVIEW

**Comment by Heroman3003** [comment]
Damage reduction is fine, but I don't think stun is a good idea.

**Comment by ReoDaProtovali** [comment]
it's an extremely short stun for being THROWN into the wall, you get a stun for stumblewalking into walls, windows and pretty much everything else that isnt a maw. I think a stun is absolutely fine

**Comment by Heroman3003** [comment]
General staff consensus is that rather than full stun this should at most be a short slow or confusion.

**Comment by ReoDaProtovali** [comment]
should that be changed for stumbling too, then?

**Comment by Heroman3003** [comment]
No, specifically for the throws. Otherwise throws can result in complete easy stunlock from externals sources, while stumbling is purely self-inflicted. And if someone gets confused from being slammed into wall and then also smacks into it, then its comedy.

**Comment by ReoDaProtovali** [comment]
I could decrease the amount of time, but I think being launched into a wall, and just getting dizzy from it both doesnt make sense, and could result in running back into the wall immediately, which is a pretty similar issue, I think

Also plenty of things cause dizziness that isnt in control

**Comment by ReoDaProtovali** [comment]
stun is gone

**Pull request merged**
