### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by Yoshax**
Does part of #181 better than it does.

### CODE REVIEW

**Comment by Cameron653** [comment]
This would probably be better than what I wrote up. Going to remove the pay bugfix from my PR.

**Comment by Arokha** [comment]
Can you move the stuff in the non _vr.dm files to _vr.dm files? Like the labcoat changes.

Just do:
```js
/datum/gear/suit/roles/poncho/science
	 allowed_roles = list("Research Director","Scientist", "Roboticist", "Xenobiologist")
```

Don't need to copy more than the line you're wanting to override. And undo your changes to the existing .dm files so they merge if Polaris changes them.

**Comment by Yoshax** [comment]
https://github.com/VOREStation/VOREStation/pull/203/commits/0554eac2fc2e957ce93323a50e73567ed507a1fd is cherry-picked from Polaris, and was my PR, and is merged. I just added it because I was fixing something similar.

**Comment by Arokha** [comment]
Oh I see! Alright.

**Comment by Yoshax** [comment]
No idea why it hasn't linked it to the Polaris one like it should. Github is being really odd today.

**Pull request merged**
