### PR TITLE
Fancy Lifeboats

### PR DESCRIPTION
**Pull request by GhostActual**
Adds new fancy lifeboats to station one and surface three.

Surface Lifeboat (lifeboat1)
lifeboat1-n

Station Lifeboat (lifeboat2)
lifeboat2-n

### CODE REVIEW

**Comment by SigholtStarsong** [comment]
I feel like I should note the SOS on the Station Lifeboat is backwards. 

Also, for being Lifeboats, the colors aren't particularly contrasting or eye-catching, making it read less as a lifeboat and more as a medical transport shuttle.

**Comment by GhostActual** [comment]
> I feel like I should note the SOS on the Station Lifeboat is backwards.
> 
> Also, for being Lifeboats, the colors aren't particularly contrasting or eye-catching, making it read less as a lifeboat and more as a medical transport shuttle.

Looks like I forgot to mirror it when I moved it over from lifeboat1, will fix when I get off of work. As for the color, I am not actually the original artist for these, I merely adapted the existing lifeboats from Eris to fit the two life boats on station. I'll look into possible color options but I won't promise anything.

**Comment by Arokha** [comment]
I'll mark as draft for now until you mirror the thingy and if you want to look into color options, or decide not to, either way, you can undraft whenever.

**Comment by Andromeda-K22** [comment]
lifeboats in real life are orange and very brightly colored

**Comment by GhostActual** [comment]
I shall fix conflicts as soon as other PRs with map changes are finished

**Comment by GhostActual** [comment]
Oops

**Pull request closed without merging**
