### PR TITLE
Rework of expedition areas

### LINKED ISSUE #4894: Exploration department relocation - mapping project
#### Brief description of the issue
The main issue this seeks to solve is the fact that the chapel is presently almost completely isolated on Asteroid 2, where pretty much nobody ever goes as the only things there are the AI upload, EVA, and a maintenance entrance into medical. Likewise, the expedition is one of the departments most likely to have a use for additional EVA suits if they're bringing extra volunteers along, so it makes sense for them to be closer, along with the back entrance to medbay.

Figured I'd make an issue to brainstorm the finer details. A crappy mockup can be found below. To sum up - chapel moved to where the hangar is now. This leaves plenty of space around it to make the chapel a little bigger, add a proper funerary area next to the mass driver like on boxstation, or whatever other changes we feel like. Exploration department is moved to the vacated space, with a little room to expand northwards, staging area / meeting room in front of the shuttle, gear storage and pathfinder office to the right, and some extra space for the backup shuttle to be parked. AI core and upload shunted to the right, the core is no longer completely surrounded by maintenance and beset by the constant sounds of mice bumping doors.
 
Discuss, 'cause although some things were discussed in discord they've already scrolled waaaaaay past the screen.

#### Anything else you may wish to add:
image

image

image

### PR DESCRIPTION
**Pull request by Heroman3003**
Stationside expedition areas.

- Moved Chapel to asteroid 1, reworked layout slightly. The confession booth now actually has a proper intercom.

- Moved Gateway and Gateway prep to Asteroid 1.

- Replaced Gateway and Gateway prep with vacant area.

- Moved exploration crew and equipment ares to Asteroid 2.

- Moved excursion shuttle pad to Asteroid 3. Accessible from either public staircase on Asteroid 1 or from exploration access to said staircase on Asteroid 2.

- Exploration areas now have their own dedicated substation.

- Moved AI areas slightly to accomodate new changes.

- Reworked maintenance to fit new layout (amount of trash piles unchanged).

Screenshots:
http://prntscr.com/nfhu1d - Asteroid 1
http://prntscr.com/nfhean - Asteroid 2
http://prntscr.com/nfhue6 - Asteroid 3
http://prntscr.com/nfyjid - Surface 3
http://prntscr.com/nfhf6i - Surface 2

Resolves #4894

### CODE REVIEW

**Comment by Screemonster** [comment]
What happened to the backup shuttle that was moved to asteroid 1 in #4889?

**Comment by Heroman3003** [comment]
@Screemonster Its move to Asteroid 1 was cancelled due to whole 'dedicated area' backlash and it is still in docks, just docks themselves got adjusted to fit it.

**Comment by Very-Soft** [comment]
Just pointing out that this is another stealth nerf to people's ability to do crimes, being that the changes to the surface surrounds the surface armory in outside atmosphere.

**Comment by Screemonster** [comment]
holy crap I hadn't noticed that. There's even _cameras_ covering it what the shit

Enclose that section in, put a janitorial closet or something in the space next to the corridor, and just seal that space in the middle off with blank plating and some sort of junk in there. The surface armory isn't supposed to be inpenetreble, people _are_ supposed to be able to commit crimes.

God it's like nobody's heard of an intentional design flaw in a game...

**Comment by Heroman3003** [comment]
https://prnt.sc/nfyjid - alright. That access was already completely blocked off in another PR that was merged and Scree did not comment on, but if so desired, there. A practical use for station mimics.

**Comment by Very-Soft** [comment]
Much better, thank you~

**Comment by Heroman3003** [comment]
I still do not like reputation of that place, with it being treated as free sec loot stash, for the record. Because there is difference from 'being able to get in' and 'being able to get in whenever with 0 consequence because of people growing so disensitized to it being gotten into'. If we had a crocodiles, initial revision would have had a moat.
To me its like putting spare ID in the wall-stash near AI upload somewhere and then going 'well, its secure area still', while people can always easily open it up with noone ever realizing.

**Comment by Very-Soft** [comment]
I mean I already went over why I think it's fine in the other one. 

But to reiterate, I think you're worrying a lot about a super fringe issue. The surface armory is not broken into on most shifts. And most shifts that I've ever seen it broken into, the person either didn't abuse what they stole and so didn't get caught, which is fine imo. Or they did abuse what they got, and security jumps all over them.

Like, I've actually literally never seen a time where security people knew someone broke in there but were just like 'who cares'

but if antag types want a taser or something, the surface armory is basically the only place to get it that doesn't require breaking into high traffic high visibility locations.

And putting a mote around it just makes it so there's only one honestly viable way to go about doing such a heist. Needing to break through 2 walls and a mimic is more reasonable, more fun of an ask, in my opinion.

**Comment by Screemonster** [comment]
Remember that time someone accused sam of breaking into the armory and stealing headset keys LITERALLY EVERY SHIFT HONESTLY IT'S EVERY TIME THEY PLAY and we checked logs and found them on the security channel a total of like nine times in the entire year?

**Comment by Novacat** [comment]
Since the only concerns regarding this have been addressed, I am going to go ahead and merge this.

**Pull request merged**
