### PR TITLE
Some new voremob additions and tweaks

### PR DESCRIPTION
**Pull request by Verkister**
-Ports Chompstation phoron dragon (big, mountable)
-Adds direwolf (big, mountable)
-Adds chubby oties (regular, collar, security, all mountable)
-Fixes dragon mounting.
-Adjusts corrupthound, otie, and rat damages for post-AI-fix balance.
-Slightly buffs phoron dragon health to match the tankier new look.
kuva
kuva
kuva

### CODE REVIEW

**Comment by Arokha** [comment]
Pics!!!

**Comment by Verkister** [comment]
pics added

**Comment by TheFurryFeline** [comment]
Inb4 our lovely Verk makes mawshots with those puppers 😊

**Comment by KasparoVy** [comment]
Direwolf sprite is bloody awesome

**Pull request merged**
