### PR TITLE
Adds in more entertainemnt monitors so that libarianst or Reporters have much more exposure.

### PR DESCRIPTION
**Pull request by H0lySquirr3l**
Added Entertainment Monitors to:
Outside Surface Medical. https://cdn.discordapp.com/attachments/187013248309002240/709815868317761596/unknown.png

Inside Surface Sec lobby. https://cdn.discordapp.com/attachments/187013248309002240/709816318085300254/unknown.png

Work out room next to the space docks. https://cdn.discordapp.com/attachments/187013248309002240/709819927652991097/unknown.png

On the north side of Tram lobby. https://cdn.discordapp.com/attachments/404851206150815746/709823633467637881/unknown.png

Next to the tram door in the cafe. 
image

next to the entrance from dorms to dark bar. https://cdn.discordapp.com/attachments/404851206150815746/709825666908028998/unknown.png

In sec lobby. https://cdn.discordapp.com/attachments/404851206150815746/709829929524789248/unknown.png

next to the stairs in the med bay healing center. https://cdn.discordapp.com/attachments/404851206150815746/709830224178839574/unknown.png

Outside the janitor's office. 
image
 
In the small area outside space medbay and space security. https://cdn.discordapp.com/attachments/404851206150815746/709836802999189525/unknown.png

The Stairs going up to bar from dorms. 
image

### CODE REVIEW

**Comment by H0lySquirr3l** [comment]
Some of the Monitors were bugged. also missing the added monitor to Cargo.
image

**Comment by H0lySquirr3l** [comment]
Fixed bugged monitors

**Comment by Arokha** [comment]
image
:eyes: 

Whoever told you they ran this through mapmerge2 is a probably not right

**Comment by Arokha** [comment]
FYI you can use https://fastdmm2.ss13.io to edit maps, and save them. The saved ones are in tgm format (map-merge format) by default.

**Comment by H0lySquirr3l** [comment]
I just... I never had heard of this. The last Time I did map edits I just used dream and mapmerger.

**Comment by H0lySquirr3l** [comment]
I have no idea what that image you posted means.

**Comment by Rykka-Stormheart** [comment]
I ran it through dmm2tgm, same as I've always done. No idea wtf happened here.

**Comment by H0lySquirr3l** [comment]
my computer is cursed... what does that mean?

**Comment by Rykka-Stormheart** [comment]
Still have 4 files in the wrong place, all of the maps need to be in /maps/tether/

**Pull request closed without merging**
