### PR TITLE
[MIRROR] Only slimes may squish.

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/5369
--------------------
Plain and simple. 
Also it's still keeping my old commits here even though it shouldn't be, send help.

Aro: Commented this out.

### CODE REVIEW

**Comment by Verkister** [comment]
Gamebreaking.

**Comment by Very-Soft** [comment]
This seems very much like an anti-fun PR.

**Comment by Cameron653** [comment]
Are you saying that people _can't_ squish their fat?

I personally say we keep it in.

**Comment by Mewchild** [comment]
@Very-Soft Squish was supposed to be restricted to slimes, for a long, long time. It was just... broken

**Comment by Wickedtemp** [comment]
I mean... So? It's fun and harmless. I say keep it.

**Comment by Arokha** [comment]
Commented it out.

**Pull request merged**
