### PR TITLE
Ensure Dhaeleena spawns correctly

### PR DESCRIPTION
**Pull request by Arokha**
She has been spawning incorrectly. This PR will ensure she spawns correctly each time.

image

### CODE REVIEW

**Comment by SilverTalismen** [comment]
Finally, This bug has been annoying the hell out of me for so long.

**Comment by SpadesNeil** [comment]
pfft

**Comment by SpadesNeil** [comment]
inb4 someone thinks this is a serious PR and starts pissing about admin/developer favoritism

**Comment by Dhaeleena** [comment]
This is clear catte aboose

**Comment by Screemonster** [comment]
catte aboote

**Comment by Arokha** [comment]
Just realized I should make a generic system instead for future use (Scree in boobs, Dhae in boots, Joan in butts, etc.) So I'll close this for now pending implementation of that.

**Pull request closed without merging**
