### PR TITLE
Add myself to the Protean whitelist

### PR DESCRIPTION
**Pull request by hynet-mel**
[My application for the Protean species recently got accepted](https://forum.vore-station.net/viewtopic.php?f=46&t=1815) and wanted to add myself to the whitelist

### CODE REVIEW

**Comment by Meghan-Rossi** [comment]
Congratulations.  You need to write your username in lowercase in this file for this to work though, byond uses lowercased no-punctuation versions of usernames ("ckeys") for a lot of things internally and the whitelists are linked into that.

**Comment by hynet-mel** [comment]
> 
> 
> Congratulations. You need to write your username in lowercase in this file for this to work though, byond uses lowercased no-punctuation versions of usernames ("ckeys") for a lot of things internally and the whitelists are linked into that.

Ah, alright, fault on my side then, whoops! Gonna see if I can change it.

**Comment by hynet-mel** [comment]
> 
> 
> Congratulations. You need to write your username in lowercase in this file for this to work though, byond uses lowercased no-punctuation versions of usernames ("ckeys") for a lot of things internally and the whitelists are linked into that.

Shhhhhhhould be done now, can you check if this is alright now? Thanks for the notice! <3

**Comment by Meghan-Rossi** [comment]
Yeah, looks good to me now.

**Comment by hynet-mel** [comment]
> 
> 
> Yeah, looks good to me now.

Sweeeet! Thanks.

**Pull request merged**
