### PR TITLE
Adds moth wings sprites plus fluffy bits + Double lizard horns

### PR DESCRIPTION
**Pull request by viv-eret**
Took the sprites from Hippie. Edited them a bit.

They're classified as tails and should work.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
:+1:

**Comment by viv-eret** [comment]
I totally didn't add this by accident. Just throw it in.

**Comment by Cameron653** [comment]
Everything looks good, even though github is saying you added a shitload of things. I do see a fix in there where taj_ears is. :+1: from me. Just have to wait for travis.

**Comment by Cameron653** [comment]
Closed due to request of PR creator, mainly due to travis never firing up. #424 is the current PR.

**Pull request closed without merging**
