### PR TITLE
pAI Bear Take-2

### PR DESCRIPTION
**Pull request by Dinnel**
I had no idea how do undo what I did before, so I made a new pull request. This time it only changes the pai_vr.dmi file.
I learned that I shouldn't modify the other file because apparently it causes conflicts and ours uses the pai_vr file only anyway.

### CODE REVIEW

**Comment by Cameron653** [comment]
Looks good to me.

**Comment by Belsima** [comment]
Have you looked into having this for Polaris? I can think of a use for it.

**Comment by SpadesNeil** [comment]
I don't think Polaris would want this but they are welcome to grab it.

**Comment by Dinnel** [comment]
You are free to use the sprite for whatever, so go ahead if you want!

**Comment by Belsima** [comment]
Merci

**Pull request merged**
