### PR TITLE
New Belts and Accessories

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

Adds in new, custom sprited icons for a vast number of things that were in desperate need of a face lift. The belts (all of them) now have a significantly better sprite that keeps the soul of the original sprites in mind. The vests and webbing you can find in maints now have their own polished sprites (Teshari onmob sprites included). Thigh drop bags also got the same treatment along with all the holsters whose sprites were originally ported from Aurora.

## How This Contributes To The VOREStation Roleplay Experience

No more old sprites. This is the future. We get shiny new sprites.

## Proof of Testing

<details>
<summary>
Screenshots/Videos</summary>
 
New Belt Sprites
Screenshot 2023-06-16 235948

New Holster, Thigh Bag, and Webbing/Vests Sprites
Screenshot 2023-06-16 235743

</details>

## Changelog

:cl:
image: Adds in new custom Belt Sprites
image: Adds in new custom Webbing sprites
image: Adds in new custom Vest sprites
image: Adds in new custom Thigh Bag sprites
/:cl:

### CODE REVIEW

**Comment by AmayaWah** [comment]
Yo this is pretty sick, nice work.

**Comment by TankTheBirb** [comment]
Sprites are good, I vibe with em.

**Comment by SatinIsle** [comment]
Personally think they look great, assuming the on mob sprites for the belts aren't changed

**Comment by Youtubeboy139** [comment]
> Personally think they look great, assuming the on mob sprites for the belts aren't changed

They are changed

**Comment by SatinIsle** [comment]
> > Personally think they look great, assuming the on mob sprites for the belts aren't changed
> 
> They are changed

I have no problem with them being changed btw, just can't give an honest opinion unless you show them too

**Comment by Youtubeboy139** [comment]
> > > Personally think they look great, assuming the on mob sprites for the belts aren't changed
> > 
> > 
> > They are changed
> 
> I have no problem with them being changed btw, just can't give an honest opinion unless you show them too

They are basically pallet swapped, nothing major was changed about them

**Pull request merged**
