### PR TITLE
Allows prometheans to change their hair color seperately from body color, and also headpat

### PR DESCRIPTION
**Pull request by Cyantime**

### CODE REVIEW

**Comment by Cameron653** [comment]
You should give the hair changing ability to Polaris upstream.

**Comment by Cyantime** [comment]
Prometheans can't have hair color that isn't their body color on Polaris, and they're the only shapeshifter species.

**Comment by Cameron653** [comment]
I'm assuming that has to do with the monochromatic variable

**Comment by Cyantime** [comment]
Right, that's also what made slimes that change their body color also change their hair color to the same.

**Comment by Belsima** [comment]
```
November 23, 2017
[8:37 AM] Belsima: https://github.com/VOREStation/VOREStation/pull/2515

Just saw this downstream with a 'send to polaris' tag. You want, or no?

[1:22 PM] Mechoid: ..That would be incredibly nice
```

From Promethean loremaster. May want to return that Polaris tag.

**Comment by Cyantime** [comment]
Closing this for now, will re-open with changes depending on what gets merged into Polaris

**Comment by Cyantime** [comment]
Re-opening and updating to match the polaris changes

**Comment by Cyantime** [comment]
Travis fell over and died, can someone give it a kick.

**Comment by Cameron653** [comment]
Don't edit prometheans.dm. That'll automatically be changed when we sync with polaris.

The other two are fine, I'll just have to fix the conflict with the proc being in our codebase and theirs.

**Comment by Cyantime** [comment]
I had just changed it to match the Polaris file, in case this is merged and the server is updated before a Polaris sync. Should I unchange that?

**Comment by Cameron653** [comment]
Correct. It'll just cause conflicts otherwise.

**Comment by Cyantime** [comment]
Done

**Comment by Cameron653** [comment]
Alright, that's better.

There will still be conflicts, as species_shapeshift.dm is being edited, but we won't need to adjust prometheans_vr when the sync occurs.

**Comment by Cyantime** [comment]
There'll be conflicts, but it shouldn't matter which side is used to resolve them, because they'll both be identical. Unless I'm completely mistaken about how conflicts are resolved like this.

**Comment by Cameron653** [comment]
You're correct. They'll both be identical, but Github will still scream at me that the files are completely different even though they're not. It only takes me about a minute or two per file for something as basic as this, however. So it'll be fine.

**Pull request merged**
