### PR TITLE
Polaris Sync

### PR DESCRIPTION
**Pull request by Cameron653**
# POLARIS SYNC

Syncs with Polaris.
Solved all conflicts. 
Code compiled.

### CODE REVIEW

**Comment by Cameron653** [comment]
Oh god something came out of nowhere and it won't merge. 1 second.

**Comment by Cameron653** [comment]
Found it. /area/crew_quarters/visitor_dinning was changed to /area/crew_quarters/visitor_dining. Map updated accordingly.

**Comment by Cameron653** [comment]
ALRIGHT that should fix it. Took the map on the current master and put it in the PR and changed dinning to dining as needed.

**Comment by Cameron653** [comment]
Ah... Gotta find the micros some more. One second.

**Comment by Cameron653** [comment]
ALRIGHT that's all the issues fixed. Map issue fixed, micro issues fixed, and said macros will never be a problem again.

**Comment by Cameron653** [comment]
...

**Comment by SpadesNeil** [comment]
https://www.youtube.com/watch?v=WXv2hWgfSPU

```192.14s$ DreamMaker vorestation.dme

DM compiler version 511.1381

loading vorestation.dme

loading interface/skin.dmf

loading tether-01-surface.dmm

loading tether-02-transit.dmm

loading tether-03-station.dmm

loading tether-04-mining.dmm

loading tether-05-solars.dmm

loading tether-06-colony.dmm

maps/tether/tether-06-colony.dmm:241:error: undefined type: /obj/item/ammo_magazine/m556saw

maps/tether/tether-06-colony.dmm:241:error: undefined type: /obj/item/ammo_magazine/m556saw

maps/tether/tether-06-colony.dmm:241:error: undefined type: /obj/item/ammo_magazine/m556saw

maps/tether/tether-06-colony.dmm:241:error: undefined type: /obj/item/ammo_magazine/m556saw

maps/tether/tether-06-colony.dmm:241:error: undefined type: /obj/item/ammo_magazine/m556saw

maps/tether/tether-06-colony.dmm:241:error: undefined type: /obj/item/ammo_magazine/m556saw

maps/tether/tether-06-colony.dmm:241:error: undefined type: /obj/item/ammo_magazine/m556saw/ap

maps/tether/tether-06-colony.dmm:241:error: undefined type: /obj/item/ammo_magazine/m556saw/ap

maps/tether/tether-06-colony.dmm:241:error: undefined type: /obj/item/ammo_magazine/m556saw/ap

maps/tether/tether-06-colony.dmm:241:error: unknown type

maps/tether/tether-06-colony.dmm:241:error: unknown type

maps/tether/tether-06-colony.dmm:241:error: unknown type

maps/tether/tether-06-colony.dmm:241:error: unknown type

maps/tether/tether-06-colony.dmm:241:error: unknown type

maps/tether/tether-06-colony.dmm:241:error: unknown type

maps/tether/tether-06-colony.dmm:241:error: unknown type

maps/tether/tether-06-colony.dmm:241:error: unknown type

maps/tether/tether-06-colony.dmm:241:error: unknown type

maps/tether/tether-06-colony.dmm:1522:error: undefined type: /obj/item/ammo_magazine/m556saw/ap

maps/tether/tether-06-colony.dmm:1522:error: undefined type: /obj/item/ammo_magazine/m556saw/ap

maps/tether/tether-06-colony.dmm:1522:error: undefined type: /obj/item/ammo_magazine/m556saw

maps/tether/tether-06-colony.dmm:1522:error: undefined type: /obj/item/ammo_magazine/m556saw

maps/tether/tether-06-colony.dmm:1522:error: undefined type: /obj/item/ammo_magazine/m556saw

maps/tether/tether-06-colony.dmm:1522:error: unknown type

maps/tether/tether-06-colony.dmm:1522:error: unknown type

maps/tether/tether-06-colony.dmm:1522:error: unknown type

maps/tether/tether-06-colony.dmm:1522:error: unknown type

maps/tether/tether-06-colony.dmm:1522:error: unknown type

loading tether-07-misc.dmm

maps/tether/tether-07-misc.dmm:1:error: undefined type: /turf/space/transit/east/shuttlespace_ew5

maps/tether/tether-07-misc.dmm:1:error: unknown type

maps/tether/tether-07-misc.dmm:2:error: undefined type: /turf/space/transit/east/shuttlespace_ew6

maps/tether/tether-07-misc.dmm:2:error: unknown type

maps/tether/tether-07-misc.dmm:3:error: undefined type: /turf/space/transit/east/shuttlespace_ew7

maps/tether/tether-07-misc.dmm:3:error: unknown type

maps/tether/tether-07-misc.dmm:4:error: undefined type: /turf/space/transit/east/shuttlespace_ew8

maps/tether/tether-07-misc.dmm:4:error: unknown type

maps/tether/tether-07-misc.dmm:5:error: undefined type: /turf/space/transit/east/shuttlespace_ew9

maps/tether/tether-07-misc.dmm:5:error: unknown type

maps/tether/tether-07-misc.dmm:6:error: undefined type: /turf/space/transit/east/shuttlespace_ew10

maps/tether/tether-07-misc.dmm:6:error: unknown type

maps/tether/tether-07-misc.dmm:7:error: undefined type: /turf/space/transit/east/shuttlespace_ew11

maps/tether/tether-07-misc.dmm:7:error: unknown type

maps/tether/tether-07-misc.dmm:8:error: undefined type: /turf/space/transit/east/shuttlespace_ew12

maps/tether/tether-07-misc.dmm:8:error: unknown type

maps/tether/tether-07-misc.dmm:9:error: undefined type: /turf/space/transit/east/shuttlespace_ew13

maps/tether/tether-07-misc.dmm:9:error: unknown type

maps/tether/tether-07-misc.dmm:10:error: undefined type: /turf/space/transit/east/shuttlespace_ew14

maps/tether/tether-07-misc.dmm:10:error: unknown type

maps/tether/tether-07-misc.dmm:11:error: undefined type: /turf/space/transit/east/shuttlespace_ew15

maps/tether/tether-07-misc.dmm:11:error: unknown type

maps/tether/tether-07-misc.dmm:12:error: undefined type: /turf/space/transit/east/shuttlespace_ew1

maps/tether/tether-07-misc.dmm:12:error: unknown type

maps/tether/tether-07-misc.dmm:13:error: undefined type: /turf/space/transit/east/shuttlespace_ew2

maps/tether/tether-07-misc.dmm:13:error: unknown type

maps/tether/tether-07-misc.dmm:14:error: undefined type: /turf/space/transit/east/shuttlespace_ew3

maps/tether/tether-07-misc.dmm:14:error: unknown type

maps/tether/tether-07-misc.dmm:15:error: undefined type: /turf/space/transit/east/shuttlespace_ew4

maps/tether/tether-07-misc.dmm:15:error: unknown type

maps/tether/tether-07-misc.dmm:20:error: undefined type: /turf/space/transit/east/shuttlespace_ew10

maps/tether/tether-07-misc.dmm:20:error: unknown type

maps/tether/tether-07-misc.dmm:21:error: undefined type: /turf/space/transit/east/shuttlespace_ew11

maps/tether/tether-07-misc.dmm:21:error: unknown type

maps/tether/tether-07-misc.dmm:22:error: undefined type: /turf/space/transit/east/shuttlespace_ew12

maps/tether/tether-07-misc.dmm:22:error: unknown type

maps/tether/tether-07-misc.dmm:23:error: undefined type: /turf/space/transit/east/shuttlespace_ew13

maps/tether/tether-07-misc.dmm:23:error: unknown type

maps/tether/tether-07-misc.dmm:24:error: undefined type: /turf/space/transit/east/shuttlespace_ew14

maps/tether/tether-07-misc.dmm:24:error: unknown type

maps/tether/tether-07-misc.dmm:25:error: undefined type: /turf/space/transit/east/shuttlespace_ew15

maps/tether/tether-07-misc.dmm:25:error: unknown type

maps/tether/tether-07-misc.dmm:26:error: undefined type: /turf/space/transit/east/shuttlespace_ew1

maps/tether/tether-07-misc.dmm:26:error: unknown type

maps/tether/tether-07-misc.dmm:27:error: undefined type: /turf/space/transit/east/shuttlespace_ew2

maps/tether/tether-07-misc.dmm:27:error: unknown type

maps/tether/tether-07-misc.dmm:28:error: undefined type: /turf/space/transit/east/shuttlespace_ew3

maps/tether/tether-07-misc.dmm:28:error: unknown type

maps/tether/tether-07-misc.dmm:29:error: undefined type: /turf/space/transit/east/shuttlespace_ew4

maps/tether/tether-07-misc.dmm:29:error: unknown type

maps/tether/tether-07-misc.dmm:30:error: undefined type: /turf/space/transit/east/shuttlespace_ew5

maps/tether/tether-07-misc.dmm:30:error: unknown type

maps/tether/tether-07-misc.dmm:31:error: undefined type: /turf/space/transit/east/shuttlespace_ew6

maps/tether/tether-07-misc.dmm:31:error: unknown type

maps/tether/tether-07-misc.dmm:32:error: undefined type: /turf/space/transit/east/shuttlespace_ew7

maps/tether/tether-07-misc.dmm:32:error: unknown type

maps/tether/tether-07-misc.dmm:33:error: undefined type: /turf/space/transit/east/shuttlespace_ew8

maps/tether/tether-07-misc.dmm:33:error: unknown type

maps/tether/tether-07-misc.dmm:34:error: undefined type: /turf/space/transit/east/shuttlespace_ew9

maps/tether/tether-07-misc.dmm:34:error: unknown type

maps/tether/tether-07-misc.dmm:110:error: undefined type: /turf/space/transit/east/shuttlespace_ew11

maps/tether/tether-07-misc.dmm:110:error: unknown type

maps/tether/tether-07-misc.dmm:111:error: undefined type: /turf/space/transit/east/shuttlespace_ew12

maps/tether/tether-07-misc.dmm:111:error: unknown type

maps/tether/tether-07-misc.dmm:112:error: undefined type: /turf/space/transit/east/shuttlespace_ew13

maps/tether/tether-07-misc.dmm:112:error: unknown type

maps/tether/tether-07-misc.dmm:113:error: undefined type: /turf/space/transit/east/shuttlespace_ew14

maps/tether/tether-07-misc.dmm:113:error: unknown type

maps/tether/tether-07-misc.dmm:114:error: undefined type: /turf/space/transit/east/shuttlespace_ew15

maps/tether/tether-07-misc.dmm:114:error: unknown type

maps/tether/tether-07-misc.dmm:115:error: undefined type: /turf/space/transit/east/shuttlespace_ew1

maps/tether/tether-07-misc.dmm:115:error: unknown type

maps/tether/tether-07-misc.dmm:116:error: undefined type: /turf/space/transit/east/shuttlespace_ew2

vorestation.dmb - 100 errors, 0 warnings (8/7/17 12:13 am) (max count reached)```

**Comment by SpadesNeil** [comment]
All 5.56 weapons are now 5.45 so this needs to be fixed.

**Comment by Cameron653** [comment]
THERE WE GO. FIXED. FOR REAL.

**Comment by SpadesNeil** [comment]
I mean there's also probably spots in our code that also still use 5.56 ammo incorrectly.

Although I don't think those items can spawn so who cares.

**Comment by Cameron653** [comment]
I just went ahead and replaced all references of 556 to 545 with the byond replacer.

**Comment by Cameron653** [comment]
Any ETA on when we can go ahead and merge this and get it on the live server? I'm pretty sure this won't break absolutely everything and it fixes some major bugs like being unable to watch people lewd as a ghost.

**Pull request merged**
