### PR TITLE
TGUI Character Directory

### PR DESCRIPTION
**Pull request by ShadowLarkens**

### CODE REVIEW

**Comment by aryll-linton** [comment]
what did us peasants do to deserve Shadow Larkens

**Comment by TheFurryFeline** [comment]
This is one HELL of an upgrade to the Char Directory 💛

**Comment by Rykka-Stormheart** [comment]
Oh, uh, feature request - in addition to Pred/Prey/Switch tags, can you also add Top/Bottom/Switch tags?

It'd really help for those of us that ALSO do ERP, or if we're just in the mood for ERP > Vore at that specific moment in time.

Thank you~ ❤️

**Review by Rykka-Stormheart — COMMENTED** [review]
Oh, uh, feature request - in addition to Pred/Prey/Switch tags, can you also add Top/Bottom/Switch tags?

It'd really help for those of us that ALSO do ERP, or if we're just in the mood for ERP > Vore at that specific moment in time.

IE like instead of it being "Tag", it'd be:
Character Directory Vore Pref: Pred/Prey/Switch
Character Directory ERP Pref: Top/Bottom/Switch/NA/Null

Thank you~ ❤️

**Pull request closed without merging**
