### PR TITLE
Add Surgery and Resleeving Rooms to Robotics!

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
Adds two surgery rooms and a resleeving room to robotics to make things a little more private!

If people still want to be treated like nothing but machinery in the public view, though, it's not difficult to setup an optable in public still - but this allows people to privately scene or conduct longer, more detailed synth RP + resleeves without clogging up chat/blocking Robotics, and especially because Robotics used to be so visible from literally everywhere.

General overview screenshot here:

### CODE REVIEW

**Comment by Rykka-Stormheart** [comment]
...the active edges are pissing me off to the point I might go fix it.

**Comment by VictorZisthus** [comment]
Can you PR this into #9146 or are you running on that? [I notice the exterior mech button]

**Comment by Rykka-Stormheart** [comment]
> Can you PR this into #9146 or are you running on that? [I notice the exterior mech button]

I uh would need edit access to but I could try and figure out a merge or something, but I'd say let this one roll in then merge it and re-do your S3 changes?

**Comment by dwinters99** [comment]
In full honesty it already takes a few stellar generations to get science to respond to requests so I don't know that removing the easy-access op-table is a good idea. This also makes it significantly harder for impromptu robot repairs wihtout having to ghetto repair. Furthermore this is propagating the Tether's hugeness and wasted space. Robotics was already a huge area that was used very little (except for RPing in after someone wanted to use the protolathe) so adding THREE ENTIRE NEW ROOMS, two of which will almost certainly never be used, is probably ill-advised. Like, when is the last time more than once synth needed repaired? When is the last time a synth needed resleeved? The only situation that I can imagine needing both ORs if if someone is taking deliberately long or if someone is teaching synth surgery. This also allows situations like this to occur with much more ease:
Screenshot_5

(pictured: 4 centcomm officers yelling at a scientist """teaching""" a roboticist how to do surgery without anesthetics or sterilizine. not pictured: the scientists limbless body after being taken to medical.)

There is also now dead-space at the top left, again agitating the TETHER2BIG issue. At most I think one OR  would be needed for the... synth repair scenes (??? I've never seen that happen but it lines up with how slow science is- to each their own.) 

On the bright side, it's great that robotics now gets two jumper-cables. I don't think they had a resleeving vendor either before, so that's good. Although looking at this now I see that the implanter is now behind a second door which means if a non-scientist wants a circuit implant they have to scour maint or waste a scientists time. Well, I tried to find the good parts. Sorry. I definitely think this needs another design philosophy pass.

**Comment by Runa-Dacino** [comment]
> In full honesty it already takes a few stellar generations to get science to respond to requests so I don't know that removing the easy-access op-table is a good idea. This also makes it significantly harder for impromptu robot repairs without having to ghetto repair. Furthermore this is propagating the Tether's hugeness and wasted space. Robotics was already a huge area that was used very little (except for RPing in after someone wanted to use the protolathe) so adding THREE ENTIRE NEW ROOMS, two of which will almost certainly never be used, is probably ill-advised. Like, when is the last time more than once synth needed repaired? When is the last time a synth needed resleeved? The only situation that I can imagine needing both ORs if if someone is taking deliberately long or if someone is teaching synth surgery. This also allows situations like this to occur with much more ease:
> Screenshot_5
> 
> (pictured: 4 centcomm officers yelling at a scientist """teaching""" a roboticist how to do surgery without anesthetics or sterilizine. not pictured: the scientists limbless body after being taken to medical.)
> 
> There is also now dead-space at the top left, again agitating the TETHER2BIG issue. At most I think one OR would be needed for the... synth repair scenes (??? I've never seen that happen but it lines up with how slow science is- to each their own.) supplementing the existing op-table.
> 
> On the bright side, it's great that robotics now gets two jumper-cables. I don't think they had a resleeving vendor either before, so that's good. Although looking at this now I see that the implanter is now behind a second door which means if a non-scientist wants a circuit implant they have to scour maint or waste a scientists time. Well, I tried to find the good parts. Sorry. I definitely think this needs another design philosophy pass.
> 
> EDIT: Is it even possible to set up an op-table? I'm pretty sure that got removed after some frisky explo folk set one up on the shuttle.

The reason for two rooms is simple:

If there are 3 roboticists,

one of the roboticists is using one exam/repair room for a scene.

There is no need for them to be yelled at for using their job as a backdrop for scening, since the other roboticist can do their job without their coworker being in the way.

**Comment by dwinters99** [comment]
> The reason for two rooms is simple:
>
> If there are 3 roboticists,
>
> one of the roboticists is using one exam/repair room for a scene.

Then surely you would only need 1 OR and the existing public table. Making the tether more complicated while creating more dead space is exactly what people have been trying to stop for the past year.

**Comment by lm40** [comment]
yeah probably my biggest objection to that it is bloat to the map for largely edge-case reasons but it really only ends up coming down to one extra surgery room which isn't /that bad/.

**Comment by nerdass** [comment]
We don't want organic surgery happening in robotics, why did you make this?

**Comment by nerdass** [comment]
Oh wait i get it, they're just regular rooms that don't have anesthetic. I kinda like this idea but there needs to be something posted in there that says HEY DON'T DO STUFF TO ORGANICS YA' GIT.

**Comment by Runa-Dacino** [comment]
> Oh wait i get it, they're just regular rooms that don't have anesthetic. I kinda like this idea but there needs to be something posted in there that says HEY DON'T DO STUFF TO ORGANICS YA' GIT.

For what it's worth, current robotics already has an anesthetic tank available.

**Comment by Rykka-Stormheart** [comment]
Closing this PR as Soft will be rolling this into her Surface Security update. Branch will remain up until that PR is in and through, for safety and asset-keeping. o7

**Pull request closed without merging**
