### PR TITLE
Port 5 /tg/ pai sprites

### PR DESCRIPTION
**Pull request by Arokha**
Corgi, bat, butterfly, hawk, duffel

### CODE REVIEW

**Comment by Verkister** [comment]
https://github.com/VOREStation/VOREStation/pull/10797 dmi conflict

**Comment by Arokha** [comment]
> #10797 dmi conflict

dangit

**Comment by Heroman3003** [comment]
Duffel one looks a bit too dumb for me.

**Comment by Very-Soft** [comment]
More options goood

**Comment by Arokha** [comment]
> Duffel one looks a bit too dumb for me.

Same but eh!

**Pull request merged**
