### PR TITLE
Drink update

### PR DESCRIPTION
**Pull request by SweetBlueSylveon**
Adds 20 new drinks, 30 replaced sprites for old drinks, and adds 3 new sprites to drinks without one. Snow White recipe changed.
Requires"Allow reagents to have specific metaglass icon files" from Arokha.

### CODE REVIEW

**Comment by SweetBlueSylveon** [comment]
"inconsistent indentation"
vorestation.dmb - 53 errors, 0 warnings (5/30/20 10:07 pm)
These are the errors from Arokha's PR not being merged yet.

**Comment by Arokha** [comment]
Nop, that's the indentation being inconsistent.
image

**Comment by Arokha** [comment]
Also you don't need these rows **for any drinks that already existed in the other file**, you just need that glass_icon_file line.

image

**Comment by SweetBlueSylveon** [comment]
Now it's changed to:
**code\modules\food\drinkingglass\metaglass_vr.dm:119:error: glass_icon_file: undefined var
vorestation.dmb - 53 errors, 0 warnings (5/30/20 3:55 pm)
**

**Pull request merged**
