### PR TITLE
Add Resh's HOS Coat

### PR DESCRIPTION
**Pull request by TheFurryFeline**
So, I saw a thing on forums here, https://forum.vore-station.net/viewtopic.php?f=26&t=1519 and thought, 'hey, I can fix that.' So, here we are. :> Also adjusts Phi's last name - in the comment for the listing - as I've seen it in-game, back to Vietsi.
Edit: Couple pushes with two additional file edits for Phi's name change, mostly to make sure that he still gets his box of items.
Edit2: Typo fixes for comments/text file for Phi's last name.

### CODE REVIEW

**Comment by KasparoVy** [comment]
Vesty*

**Comment by TheFurryFeline** [comment]
Mlem? Was there another thing I missed?

**Comment by KasparoVy** [comment]
Nah just joking about the name. No worries

**Comment by TheFurryFeline** [comment]
Pfft, alrighty.

**Pull request merged**
