### PR TITLE
Fixes initial nif backups.

### PR DESCRIPTION
**Pull request by Verkister**
-Nif tested preserving even with initial one-time backups.
-Moved some junk around.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
@Arokha this is your department

**Comment by SpadesNeil** [comment]
Also, please keep fixes in separate pull requests as opposed to changes to intended features.

**Comment by SpadesNeil** [comment]
I am not merging this until the bug removal and feature addition are made separate.

**Comment by Verkister** [comment]
there

**Pull request merged**
