### PR TITLE
More space creature events

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Lifted a bunch of critter sprites from Aurora to add some Flavour to space critter events. Introducing: space rays, space sharks, and space gnats!

- Space rays are passive unless provoked, unlike jellies, and will just kinda chill out until the event ends. They're fairly durable, and can cause reasonable harm to anything that attacks them. They spawn in very limited numbers.
- Space sharks are slow but tough and powerful, and also highly aggressive. Like rays, they spawn in very limited numbers. Aggress with care, or just wait them out. They yield a lot of meat with plenty of carpotoxin though.
- Space gnats are numerous but extremely fragile and very weak, mostly dangerous thanks to their evasive AI/attack patterns. Think "organic viscerator" and that's about it. They spawn in greater numbers than other 'space threats'.

The new events cannot fire on RP, but all three can fire as varying tiers of event on SD and Tether (rays and gnats cover all three tiers, sharks are tier 2/3 only). Not currently added to any POIs or belt-mining spawns or anything like that.

Probably needs some tuning for stats and numbers in events. The space shark also needs a proper cataloguer description since I totally phoned that one in.

### CODE REVIEW

**Comment by Heroman3003** [comment]
Two suggestions just from reading the description:

1) With how many events this makes, perhaps unifiying them into singular "space migration" event with mob type picked randomly and making event repeatable might be a good thing to do right now

2) It is 100% intentional that none of the 'space migration' events happen on RP anymore and thats because RP is not in space and does not have space levels, so I politely disagree with idea of adding any of new space migrations to its pool purely on logical perspective.

**Comment by KillianKirilenko** [comment]
> Two suggestions just from reading the description:
> 
> 1. With how many events this makes, perhaps unifiying them into singular "space migration" event with mob type picked randomly and making event repeatable might be a good thing to do right now

Yeah, I was mulling over doing that if it was the existing infrastructure, but I'm not exactly great at the coding side of things sometimes so overhauling the migration event as a whole felt like an out-of-scope thing. I'd rather get the basics down and then someone who knows what they're doing can wrangle the actual event stuff, 'cause otherwise I might end up sitting on the basics for ages.

My loose idea for an approach was to have a spawn list with each critter having its own value/rarity, and then it just spawns them randomly until it reaches the assigned point score for the event, similar to Scree's overhaul of abandoned crate loot.

> 2. It is 100% intentional that none of the 'space migration' events happen on RP anymore and thats because RP is not in space and does not have space levels, so I politely disagree with idea of adding any of new space migrations to its pool purely on logical perspective.

I figured, but I also thought it probably wasn't too much of a problem seeing as the only ones enabled for RP are rays, and those are harmless unless you attack them first. I'm fine with taking them off the list again if it's really an issue though.

**Comment by Screemonster** [comment]
> Space rays are passive unless provoked, unlike jellies, and will just kinda chill out until the event ends. They're fairly durable, and can cause reasonable harm to anything that attacks them. They spawn in very limited numbers.

Yes! Ha ha ha... _YES!_

Retaliate mobs that the crew have absolutely no reason to attack or provoke but will absolutely curbstomp you if you do are my favourite kind of mobs. Nothing warms my cold admin heart more than seeing someone getting absolutely ground to a paste by gaslamp or a dustjumper or the like.

It is _so_ much funnier when it's entirely their fault.

**Comment by Heroman3003** [comment]
> ~I figured, but I also thought it probably wasn't too much of a problem seeing as the only ones enabled for RP are rays, and those are harmless unless you attack them first. I'm fine with taking them off the list again if it's really an issue though.~

It's not a big issue, really, I just get stuck on consistency sometimes

**Comment by KillianKirilenko** [comment]
> > Space rays are passive unless provoked, unlike jellies, and will just kinda chill out until the event ends. They're fairly durable, and can cause reasonable harm to anything that attacks them. They spawn in very limited numbers.
> 
> Yes! Ha ha ha... _YES!_
> 
> Retaliate mobs that the crew have absolutely no reason to attack or provoke but will absolutely curbstomp you if you do are my favourite kind of mobs. Nothing warms my cold admin heart more than seeing someone getting absolutely ground to a paste by gaslamp or a dustjumper or the like.
> 
> It is _so_ much funnier when it's entirely their fault.

I think the best part is the combination of "monstrous appearance + retaliation AI". If people think before they act, they'll get themselves into trouble they really didn't need to get into, because even a moment of observation would show that it's not acting aggressively and can be safely ignored, no matter how dangerous it might look.

Rays won't really *curbstomp* anyone, but they're about as tough as jellies with a stronger attack, so if you're really careless they might hurt you. I might give them a higher knockdown chance or a similar disable/stun (sopo venom, or whatever) and see if it's possible to make them forget/deaggro anyone they knock down until aggressed again, so they basically just kind of gently bully anyone who tries to fight them but won't really do any serious harm unless you're incredibly persistent in fighting something that really doesn't want to fight.

*Something something the crew are the real monsters.*

> > ~I figured, but I also thought it probably wasn't too much of a problem seeing as the only ones enabled for RP are rays, and those are harmless unless you attack them first. I'm fine with taking them off the list again if it's really an issue though.~
> 
> It's not a big issue, really, I just get stuck on consistency sometimes

It's reasonable, and if they're the only event of that type on RP then you automatically know it's rays and there's not much point obfuscating it with the callout, which is basically the entire point of the events sharing the same message otherwise.

**Comment by Skysteak** [comment]
> Rays won't really _curbstomp_ anyone, but they're about as tough as jellies with a stronger attack, so if you're really careless they might hurt you. I might give them a higher knockdown chance or a similar disable/stun (sopo venom, or whatever) and see if it's possible to make them forget/deaggro anyone they knock down until aggressed again, so they basically just kind of gently bully anyone who tries to fight them but won't really do any serious harm unless you're incredibly persistent in fighting something that really doesn't want to fight.

I'm happy to see a more thoughtful approach to a retaliate mob than the standard 'Just make it flatten them' approach spitefully/lazily taken. Venom may be a good continuation of the theme and be in-line with Jellyfish; the de-aggro ensuring someone a bit too head strong (or ignorantly grabbing) is given a chance to walk away -- the continuation of violence and any consequences afterwards on the one persistently (and ill equipped). It has the bonus of giving the individual involved another opportunity to witness the lack of hostility thereafter, which is good after the panic/chaos of combat.

**Comment by KillianKirilenko** [comment]
A little crude, but I figured out how to make the rays ignore anyone they knock down. I reduced their damage slightly, but they have a 2-in-3 chance to weaken attackers and will 'forget' about any attackers they weaken.

**Comment by Heroman3003** [comment]
I'm gonna say that the merging of 5 events should be a goal in the future, but out of scope of this PR. This looks good.

**Pull request merged**
