### PR TITLE
Tether Map

### PR DESCRIPTION
**Pull request by Arokha**
# T  E  T  H  E  R
PR for the Tether Map

Dun dun dunnnn.

Way too many changes to even list in the PR description, to be honest.

### CODE REVIEW

**Comment by Very-Soft** [comment]
Hype!!

**Comment by OrbisAnima** [comment]
Love this, after the long wait, finally comfy planetside goodness

**Comment by Arokha** [comment]
```
The soul of the Machine God surrounds thee.
The power of the Machine God invests thee.
The hate of the Machine God drives thee.
The Machine God endows thee with life.
Live!
```

**Comment by JoanRisu** [comment]
Hologram posters when

**Pull request merged**
