### PR TITLE
Trauma'n'Burn kits resprite, 10 stages. UPD mapfixes and remades: Medbay toilet, Cafeteria, Mirrors, Fixed Walls, CС uniform, Virology.

### PR DESCRIPTION
**Pull request by RenardQueenston**
**MAP**

1. - Fixed:

- Medbay restroom(all the same but moved cooler, tables chairs, dispocial, vendomats(food), added 1 table and 1 random MRE on it) now muh comfortable.
- Some station and surface walls(lonely non-reinforced wall behind medbay shuttle now reinforced, missing wall in command conference room was added, some walls near xenobio turned into non-reinforced, some walls in atmos was reinforced, some walls near mining operations was replaced with floor, and some other walls i forgot).
- ALL(i suppose) mirrors(added where it should be and fixed pixel_y or pixel_x).

2. Added:

- Some loot for maintenance. https://i.imgur.com/16Myhh2.png
- "Easter egg" in station rocks(centcom officer's undersuit, shoes and beret).
- Colored bedsheets(blue in room 8, red in room 6, yellow in room 4, oragne in room 2) + random drink in room 8 + random carp plushie on table in room 6 + random action figure in room 2, dorm_rooms.
- 2 extra tiles in EVA near exit to space.

3. - Reworked:

- Cafeteria(tables, dispocial units, 2 windows) for comfort.
- Virology moved 1 tile to right.
- Medbay toilet near restroom(rotated 90 degrees to right, warmest lighting) now more comfy and more compact.

-----
**SPRITES**

**Added more sprite-stages from 1 to 10.**
Works fine, I checked it.

I made "Redraw" old sprites but with an indicator.

---
I made this "sprite redraw" because current sprites just.. Not bad, but i can't understand it. When i look on new sprites i see and imagine THIS - https://i.imgur.com/NRWaq0z.png

And - no - i'm not crazy. Maybe a little bit. But not.

I see tendention to make builds looks like TORCH.
VORE for example: sprites trauma and burn kits(lul), explorers shuttle(good but can be better), new crates(+- good), medbay reconstruction(omg why??) and.. Maybe somth else.

But it's not good because of many sprites in torch-bay just fucked up because of isometry and/or crooked-handed spriters who want to make more realistic sprites (or more unrealistic? i'm not sure bout this) but they just literally CAN'T.

"Futuristic" sprite-style isn't bad at all but mostly implementation just sucks. And "TORCH-like" room-design just looks like shittin' hangar and sucks too.

### CODE REVIEW

**Comment by Novacat** [comment]
A lot of the inconsistent sprite direction of Virgo is because of the mixed origins of a lot of our sprites. Most of our sprites were inherited from Polaris, which is basically (3+ year) old Bay sprites. Then some of those sprites but not all were replaced with Eris sprites. Some sprites still were than recently replaced with custom sprites specifically for Virgo. Further confusing things, a lot of sprites were also ported here from other places, such as Baystation.

**Comment by chaoko99** [comment]
Not a fan of this change. I prefer this medical kit looking thing over what I have always imagined to be a freaking lunchbag. Furthermore, the indicators are far more distinct on the original sprites. No support.

and until we end up with two-tile hallways, the claim that we're becoming torch-like is complete crap. The use of some outdated bay sprites do not make us torch-like. We were simply migrating to a different sprite. Things can simply change for the reason of subjectively looking better. Kinda like when we took sprites from Eris. We were wrong, but there's no accounting for taste.

**Comment by Wickedtemp** [comment]
Yeah, I like our current sprite over the old one, even if the old one were to include the quantity counter.

**Comment by Iroquois-Pliskin** [comment]
No matter what the sprite looks like, these things are always gonna be weird. Current sprites are fine, no change needed.

Also I'm having trouble following what you're saying/trying to say half the time.

**Comment by Keekenox** [comment]
Can I actually see a before and after comparison for these sprites?

**Comment by chaoko99** [comment]
image

**Comment by Very-Soft** [comment]
Yeah I like the old one more personally. It has more depth to it. The new version is much more simple in general, which -can- be good sometimes. But in this case, I'm not much of a fan of the simpler look.

**Comment by Very-Soft** [comment]
I gotta say, it seems like your map edits ought to go into a different PR than your icon changes. If it's decided that one or the other isn't wanted, then closing it would decline both.

**Comment by Novacat** [comment]
Map stuff should defiantly go into a seperate PR

**Comment by RenardQueenston** [comment]
My fucking god, Github, why this so hard to separate PRs without producing branches :(
I need to make another freakin branch for map, MY GOSH. WHY.

**Comment by RenardQueenston** [comment]
I'm out.

**Pull request closed without merging**
