### PR TITLE
Xenobiology Lab Rework - No longer WIP!

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
Moves Xenobiology lab from it's abandoned little corner :3c

- Xenobiology now has an access corridor, on S3, with dual airlocks.
- SMES/Substation - WIP
- Office, breakroom, first-aid-station, tool storage, decon and xenobio operating room (this is not intended for operating, it's for xenobio autopsy)
- Slime Cells on S2, along with slime gear.
- Added a Requests Console to RnD - at request of HzDonut
- Two open-air pens, without airlock, and stairs to the exterior.
- Converted old Xenobiology into "construction/maintenance" for now - Separate PR later for making it a misc/telesci lab (not my domain)
- Added 'support' pillars onto S1 for appearance. Also made minor tweaks to wiring as part of the substation change/addition.

[Xenobiology Lab Redesign Album](https://imgur.com/a/5D0dMkC)

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Conflict now popping up with tether_areas2.dm since my refactor got merged in.

**Comment by Rykka-Stormheart** [comment]
> `## UNIT_TEST: --------------- Research Miscellaneous Lab(/area/rnd/miscellaneous_lab) lacks an APC.
> 
> ## UNIT_TEST: --------------- Research Miscellaneous Lab(/area/rnd/miscellaneous_lab) lacks an Air scrubber.
> ## UNIT_TEST: --------------- Research Miscellaneous Lab(/area/rnd/miscellaneous_lab) lacks an Air vent.
> ## UNIT_TEST: !! FAILURE !! [MAP: Area Test APC / Scrubbers / Vents Z level 1]: [1/64]Some areas lacked APCs, Air Scrubbers, or Air vents.`
> Going to want to deal with this thing. I'll take a look at the powergrid stuff but may well need editing access for this one.

Yeah, I had forgotten to add APC's to the "construction" area where old Xenobiology was. My apologies, I can add those in momentarily.

**Comment by TheFurryFeline** [comment]
> > `## UNIT_TEST: --------------- Research Miscellaneous Lab(/area/rnd/miscellaneous_lab) lacks an APC.
> > ## UNIT_TEST: --------------- Research Miscellaneous Lab(/area/rnd/miscellaneous_lab) lacks an Air scrubber.
> > ## UNIT_TEST: --------------- Research Miscellaneous Lab(/area/rnd/miscellaneous_lab) lacks an Air vent.
> > ## UNIT_TEST: !! FAILURE !! [MAP: Area Test APC / Scrubbers / Vents Z level 1]: [1/64]Some areas lacked APCs, Air Scrubbers, or Air vents.`
> > Going to want to deal with this thing. I'll take a look at the powergrid stuff but may well need editing access for this one.
> 
> Yeah, I had forgotten to add APC's to the "construction" area where old Xenobiology was. My apologies, I can add those in momentarily.

Actually, you can just add it for tether_things or whatever it is that has it ignore the fact it has no APC, scrubbers, vents. There's a thing for that.

**Comment by Rykka-Stormheart** [comment]
> > > `## UNIT_TEST: --------------- Research Miscellaneous Lab(/area/rnd/miscellaneous_lab) lacks an APC.
> > > ## UNIT_TEST: --------------- Research Miscellaneous Lab(/area/rnd/miscellaneous_lab) lacks an Air scrubber.
> > > ## UNIT_TEST: --------------- Research Miscellaneous Lab(/area/rnd/miscellaneous_lab) lacks an Air vent.
> > > ## UNIT_TEST: !! FAILURE !! [MAP: Area Test APC / Scrubbers / Vents Z level 1]: [1/64]Some areas lacked APCs, Air Scrubbers, or Air vents.`
> > > Going to want to deal with this thing. I'll take a look at the powergrid stuff but may well need editing access for this one.
> > 
> > 
> > Yeah, I had forgotten to add APC's to the "construction" area where old Xenobiology was. My apologies, I can add those in momentarily.
> 
> Actually, you can just add it for tether_things or whatever it is that has it ignore the fact it has no APC, scrubbers, vents. There's a thing for that.

Too late, already edited it lmao. Pushing now. <3

**Comment by Jakksergal** [comment]
My opinion of the map, opinion on if this is even necessary aside.
General:
1. Not all windows need to be super reinforced, only the cells and even then that's iffy. Outside-facing windows should use one pane on the exterior in addition to the full pane. 
2. There's absolutely no need for another SMES for engineering to configure. There are no cell shields, or-- anything that warrants another SMES. There's even a generator! Nothing in xenobio uses that much power.
3. There's an abundant lack of floor decals.
Z1:
1. Stairs need to have a backing outside.
2. Signs need to have a wall to sit on and there's no need for so many.
3. Please just fill the old xeno lab in with rock.. There's no need for more absolutely vacant areas especially ones inside a department the public can't access.
4. There's a wall out in the middle there which I believe lines up with the corner of the shooting range which I don't think looks great alongside the massive pillars you've made for xenobio.
Z2:
1. The cells closest to the stairs look extremely claustrophobic to work around.
2. Why are there light switches *inside* the cells? 
3. Those huge pumps need to be linked to a control console which I don't see.
4. There is no general scrubber in the two cells closest to the doors.
5. Railings should all face the same direction to take advantage of sprite merging. i.e. they either all need to face inward or all face outward.
Z3:
1. Why the absolutely massive airlock for a simple hallway? How often do you expect that hall to be breached? 
2. Double walls make me cry.
3. The air canister is not accessible to refill from the station side. 
4. You wrapped the catwalk all the way around the xenobio area but didn't connect it to the existing external catwalk, making it pointless.
5. The science subgrid connects to the xenobio subgrid on the left side of the primary(?) xenobio airlock.
6. Again, why is there an airlock for a hallway? The second one at least has the *possibility* of being used when someone manages to breach the outside-accessable 
7. Research doesn't need two break lounges..
8. The blackbox doesn't serve any functionality to my knowledge but I don't see a point for it being here.
9. The downward connection in the stairwell should have a pair of rails beside it. This is not spess OSHA compliant!
8. There's a single AI holopad and it doesn't reach anywhere but the various areas of the hallway and nowhere else except maybe a tile of storage and the medbay each.

**Comment by Rykka-Stormheart** [comment]
> My opinion of the map, opinion on if this is even necessary aside.
> **General:**
> 
> 1. Not all windows need to be super reinforced, only the cells and even then that's iffy. Outside-facing windows should use one pane on the exterior in addition to the full pane.
> 2. There's absolutely no need for another SMES for engineering to configure. There are no cell shields, or-- anything that warrants another SMES. There's even a generator! Nothing in xenobio uses that much power.
- Again, it's designed for redundancy. That was the original plan, if we ever house extremely dangerous xenos

> 3. There's an abundant lack of floor decals.
- Working on that, still. WIP.

> **Z1:**
> 
> 1. Stairs need to have a backing outside.
- A backing?
> 2. Signs need to have a wall to sit on and there's no need for so many.
- I'll add walls, and imo the signs look cool
> 3. Please just fill the old xeno lab in with rock.. There's no need for more absolutely vacant areas especially ones inside a department the public can't access.
- Someone else is planning on adding stuff there later, that's why it's a vacant area.

> 4. There's a wall out in the middle there which I believe lines up with the corner of the shooting range which I don't think looks great alongside the massive pillars you've made for xenobio.
- The random one-pillar-wall is not me, or something I touched.

> **Z2:**
> 
> 1. The cells closest to the stairs look extremely claustrophobic to work around.
- They are, a bit, but they're intended for phoron-purges or housing stuff like gaslamps.
> 2. Why are there light switches _inside_ the cells?
- They shouldn't be _inside_ the cells - that's a mapping mistake, I'll correct it
> 3. Those huge pumps need to be linked to a control console which I don't see.
- Control Console for the pumps is on S/Z3.
> 4. There is no general scrubber in the two cells closest to the doors.
- Again, intended, because of the huge pumps.
> 5. Railings should all face the same direction to take advantage of sprite merging. i.e. they either all need to face inward or all face outward.
> 
> **Z3:**
> 
> 1. Why the absolutely massive airlock for a simple hallway? How often do you expect that hall to be breached?
- Future-proofing, if we ever get more dangerous xenos, or if some unwitting intern injects an orange core with phoron (or any other deadly injections)
> 2. Double walls make me cry.
- ?
> 3. The air canister is not accessible to refill from the station side.
- Not a big deal, it's connected to the in-loop.
> 4. You wrapped the catwalk all the way around the xenobio area but didn't connect it to the existing external catwalk, making it pointless.
- It's connected to the grass/ground outside.
> 5. The science subgrid connects to the xenobio subgrid on the left side of the primary(?) xenobio airlock.
- yes, that's intended, to power the 'primary' airlock if Xenobio's power fails or something.
> 6. Again, why is there an airlock for a hallway? The second one at least has the _possibility_ of being used when someone manages to breach the outside-accessable
- Future-proofing, defending against breaches.

> 7. Research doesn't need two break lounges..
- It's so far away it's fine, imo.
> 8. The blackbox doesn't serve any functionality to my knowledge but I don't see a point for it being here.
- Decoration, my dude.
> 9. The downward connection in the stairwell should have a pair of rails beside it. This is not spess OSHA compliant!
- meh, spess OSHA can suck my clit.
> 10. There's a single AI holopad and it doesn't reach anywhere but the various areas of the hallway and nowhere else except maybe a tile of storage and the medbay each.
- Oversight, I'll fix that.

**Comment by Jakksergal** [comment]
> Again, it's designed for redundancy. That was the original plan, if we ever house extremely dangerous xenos
I still don't understand how yet another SMES can be added under the reasoning of "futureproofing." Mobs don't interact with power, there are no heavy machines, there aren't too many lights, it's just a needless SMES.

> A backing?
Yes, a backing. Put walls on the opposite end of the intended entrance of the staircase. This prevents people from taking one giant step up 15 feet from the wrong end of the staircase. 

> The random one-pillar-wall is not me, or something I touched.

It'd look a smidgen nicer from the surface if it were removed.
> Again, intended, because of the huge pumps.

Huge pumps don't magic away the air, at least not the general purpose ones. You need to have basic scrubbing lines in the cell.
> Future-proofing, if we ever get more dangerous xenos, or if some unwitting intern injects an orange core with phoron (or any other deadly injections)

Does it need to be another *airlock* though? It's going to be a pain in the ass to get through every. single. time. It'll be slow to cycle, slow to open, and slow to walk through when everything's normal.

>>Double walls make me cry.
>?

image
Double walls is a mapping sin. It's generally not accepted unless it's either a secure location like the armory or AI core. The airlock to xenobio isn't one of those types of places. :v
>Not a big deal, it's connected to the in-loop.

That's actually worse because now the airlock pumps are connected to a 30k liter volume which is limited to below 300 kPa. Put a pump between the universal adapter and the airlock loop.

>It's connected to the grass/ground outside.

image 
That's not what I'm talking about.
>yes, that's intended, to power the 'primary' airlock if Xenobio's power fails or something.

I don't know if you've just misunderstood what I'm saying or not. I'm talking about the connection of the orange wire to the green wire on the West side of the airlock under the window that is between the doors.
image
A new thing I noticed while getting that screenshot, you've overlapped wires going the same direction in the SMES room. You merged the xenobio grid to the current science grid *and* you've merged the xenobio grid with the main grid. Ergo you've just made both your xenobio SMES and the research SMES pointless. Wires pass power to other wires connected regardless of color.

**Comment by Rykka-Stormheart** [comment]
> > Again, it's designed for redundancy. That was the original plan, if we ever house extremely dangerous xenos
> 
> I still don't understand how yet another SMES can be added under the reasoning of "futureproofing." Mobs don't interact with power, there are no heavy machines, there aren't too many lights, it's just a needless SMES.

I'm leaving it for now.

> > A backing?
> 
> Yes, a backing. Put walls on the opposite end of the intended entrance of the staircase. This prevents people from taking one giant step up 15 feet from the wrong end of the staircase.

image Done.

> > The random one-pillar-wall is not me, or something I touched.
> 
> It'd look a smidgen nicer from the surface if it were removed.

Removed it.

> > Again, intended, because of the huge pumps.
> 
> Huge pumps don't magic away the air, at least not the general purpose ones. You need to have basic scrubbing lines in the cell.

image Done.

> > Future-proofing, if we ever get more dangerous xenos, or if some unwitting intern injects an orange core with phoron (or any other deadly injections)
> 
> Does it need to be another _airlock_ though? It's going to be a pain in the ass to get through every. single. time. It'll be slow to cycle, slow to open, and slow to walk through when everything's normal.

These airlocks cycle instantly. There's no wait time - because it doesn't need to equalize pressure or atmosphere content. The only time in which it would have to do is when it's needed - in the case of a breach, or phoron fire, etc. That's the only time the cycling takes time.

> > > Double walls make me cry.
> > > ?
> 
> image
> Double walls is a mapping sin. It's generally not accepted unless it's either a secure location like the armory or AI core. The airlock to xenobio isn't one of those types of places. :v

What else would you suggest be put there?

> > Not a big deal, it's connected to the in-loop.
> 
> That's actually worse because now the airlock pumps are connected to a 30k liter volume which is limited to below 300 kPa. Put a pump between the universal adapter and the airlock loop.

image
Done.

> > It's connected to the grass/ground outside.
> 
> image
> That's not what I'm talking about.

image Corrected.

> > yes, that's intended, to power the 'primary' airlock if Xenobio's power fails or something.
> 
> I don't know if you've just misunderstood what I'm saying or not. I'm talking about the connection of the orange wire to the green wire on the West side of the airlock under the window that is between the doors.
> image

 image Wiring corrected.

> A new thing I noticed while getting that screenshot, you've overlapped wires going the same direction in the SMES room. You merged the xenobio grid to the current science grid _and_ you've merged the xenobio grid with the main grid. Ergo you've just made both your xenobio SMES and the research SMES pointless. Wires pass power to other wires connected regardless of color.

Again, see above, wiring corrected.

**Comment by TheFurryFeline** [comment]
Rykka, you do know I had been working on some of this stuff....? Off and on for the last few days... I had already fixed some of the wiring as well on my side.

**Comment by Rykka-Stormheart** [comment]
> Rykka, you do know I had been working on some of this stuff....? Off and on for the last few days... I had already fixed some of the wiring as well on my side.

Shit, sorry.

**Comment by Jakksergal** [comment]
>>>>Double walls make me cry.

>>>?

>>Double walls is a mapping sin. It's generally not accepted unless it's either a secure location like the armory or AI core. The airlock to xenobio isn't one of those types of places. :v

>What else would you suggest be put there?

How about no double walls at all? Just shift everything below the topmost wall up one tile?

**Comment by Heroman3003** [comment]
Welp, I'll go over it from top to bottom in no particular order of importance though I will separate technical mistakes from personal gripes with design and balance. This post will only highlight technical issues I saw with the design, not general design/balance/ideas. I will post a separate one for those to make sure objective stuff only is in this one.

Technical:

- Airlock from research to hallway is giant and only has two scrubbers. If it were to ever function, it'd take ages.

- There is rock between walls of mini-atmos and airlock. On surface 3 there is no rock.

- Wire under rwall in substation is big owch. Thats why all substations have two doors. Also engineering has no way to access the substation.

- In the north of the hallway itself, there is a sign under a plant

- Theres way too many lights in general hallway. You could probably half the amount and still have same brightness, with possibility to lower even further.

- Newscasters are literally on the walls. Like all wall devices they are meant to be on the floors, and offset to  be on the wall.

- Disposals in the cells used chutes. What they should be using is outlets, as chutes can be entered. Or do you want slimes jumping out of disposals at you?

- Cameras overlayed over lights, intercom overlayed over the air alarm on lower floor, this all just looks bad. Could probably arrange it better and again, cut down on excess lights

**Comment by Heroman3003** [comment]
Now to more subjective aspects. All of that is criticizing general design choices and balance rather than execution. All of that are still my opinions, blah blah, but I feel like many of points I raise are rather important. To preface: I will not be treating it as an outpost, because it is not disconnected from station, and I will treat it as a singular, small branch of a bigger department that has a bunch of equal branches and deserves equal attention, not attention and space that an entire department could occupy.

- Wire under the quintiple reinforced glass is still not properly accessible, even if it has openspace under it.

- The whole ordeal doesn't need and never needed real airlocks to begin with. Airlocks for 'contingency' is stupid. Why dont we have airlock in front of main research entrance, since entire place could be flooded with phoron? Why don't we have airlock in passageway to public garden with its very exposed top floor suspectible to flooding? Full on airlocks should be leading outside. I did suggest to put a cycler into the entrance myself, but what I meant is a small cycler akin to one virology or other servers' xenobios have, not an actual airlock and a singular one.

- Why does that almost empty hallway need to be a screen and a half long?

- What is the point of it having its own personal mini-atmos tank that will not only not be connected to the xenobio itself roundstart unless somebody manually enables it, but will flood the distro loop with all the air FROM that tank roundstart instead?

- Personal generator with no fuel... Same question, just why? No other substation gets it why should xenobio get one.

- Atmospheric alarm console is an engineering console and I dont see why it should be in xenobiology

- Why triple the roundstart amount of phoron? 4 sheets are way more than enough to run it for a long while, 12 is overkill. Even chem gets 6.

- What in the world is BLACKBOX doing there? Its unique telecommunication device, there should only be one on the map and in secure area.

- Why do they get personal breakroom, personal bathroom and personal office again? Research is just a corridor away and xenobio is part of research, all of those facilities already exist in research.

- Whats with a roundstart mouse in the second research breakroom?

- A live xenomorph. It starts with live xenomorph.

- The sleeper and other stuff in same room are positioned really awkwardly, because ideally you'd want to be able to walk around it fully or just pin it to the wall in the first place rather than have one tile obstructing it.

- Xenobio had 3 monkey cube boxes + a single cube out of box. Single cube should totally exist still. Oh, and 12 boxes now? Why so damn many? Xenobio is self-sufficent with monkeys as it is.

- Xenobio isn't janitorial, nobody else gets light replacer, why do they? Galoshees are fine and understandable. Though TWO replacement boxes for an area that small really is redundancy galore.

- South facing sinks on lower floor look really awkward without being offset to look like they are mounted to the wall like all other south facing sinks are

- Random extract why again? Just seems like extremely RNG-based and unnecesary attempt at buffing.

- Why more regular slime pens? Important part of xenobio as a job is management of your pens and space. I don't see why increasing amount by 2 would be needed.

- Why more than one button for almost every pen? This will create more confusion than it will help, especially  with all the buttons for...

- Separators. I understand like two or three pens being connectable, but pretty much all of the mis ridiculous, IMO.

- Lightswitch in every pen is pretty redundant.

- All the windows are way overreinforced. All external windows normally only have one extra panel and thats leading outside. Pen windows, especially ones with 5/4 glass on them are literally irrepairable because that sort of thing is only possible via mapping. Thats why old pens only had 4 directional ones.

- Separation of the containment and general levels pretty much removes any threat slimes may possess. Its good that they no longer just leak out into general research hallway, but this pretty much turns any outbreak into utter cakewalk.

- On lower level, where xenobiologist would be spending most of their time, there are no chargers.

- There are no watertanks for refilling extinguishers or fueltanks for those welders anywhere in the new xenobio.

- Doublewalls on upper level behind staircase just look awkward with no real purpose to existing.

- Support column right outside research airlock doors looks goofy. You could probably delete half of them without ruining the 'view'.

- Old xenobio would be better off either disconnected from hallway (no doors) or just filled with rock with how big and absolutely empty area is. Even construction areas have either smaller size or some proper construction-feeling fluff to them.

**Comment by Rykka-Stormheart** [comment]
> Now to more subjective aspects. All of that is criticizing general design choices and balance rather than execution. All of that are still my opinions, blah blah, but I feel like many of points I raise are rather important. To preface: I will not be treating it as an outpost, because it is not disconnected from station, and I will treat it as a singular, small branch of a bigger department that has a bunch of equal branches and deserves equal attention, not attention and space that an entire department could occupy.
> 
> * Wire under the quintiple reinforced glass is still not properly accessible, even if it has openspace under it.
Shouldn't be an issue.

> * The whole ordeal doesn't need and never needed real airlocks to begin with. Airlocks for 'contingency' is stupid. Why dont we have airlock in front of main research entrance, since entire place could be flooded with phoron? Why don't we have airlock in passageway to public garden with its very exposed top floor suspectible to flooding? Full on airlocks should be leading outside. I did suggest to put a cycler into the entrance myself, but what I meant is a small cycler akin to one virology or other servers' xenobios have, not an actual airlock and a singular one.
Because this looks cool? Plenty of people like it.

> * Why does that almost empty hallway need to be a screen and a half long?

Appearances.
> * What is the point of it having its own personal mini-atmos tank that will not only not be connected to the xenobio itself roundstart unless somebody manually enables it, but will flood the distro loop with all the air FROM that tank roundstart instead?
To fuel the airlocks. Same setup every other airlock across the entire damn station has.

> * Personal generator with no fuel... Same question, just why? No other substation gets it why should xenobio get one.
Redundancy.

> * Atmospheric alarm console is an engineering console and I dont see why it should be in xenobiology
It's to monitor the below cells/pens. 

> * Why triple the roundstart amount of phoron? 4 sheets are way more than enough to run it for a long while, 12 is overkill. Even chem gets 6.
Again, multiple xenobiologists. That's what this entire damn wing is designed for.

> * What in the world is BLACKBOX doing there? Its unique telecommunication device, there should only be one on the map and in secure area.
If you'd bothered to pay attention, blackbox is decorative.

> * Why do they get personal breakroom, personal bathroom and personal office again? Research is just a corridor away and xenobio is part of research, all of those facilities already exist in research.

Because they're airlocked and a good distance from Research
> * Whats with a roundstart mouse in the second research breakroom?
Because mouse.

> * A live xenomorph. It starts with live xenomorph.

The xenomorph dies instantly. It has a bruteloss of 9 to the 25th power or some shit
> * The sleeper and other stuff in same room are positioned really awkwardly, because ideally you'd want to be able to walk around it fully or just pin it to the wall in the first place rather than have one tile obstructing it.

That's the medbay setup in surface medbay, which is what I was told to replicate
> * Xenobio had 3 monkey cube boxes + a single cube out of box. Single cube should totally exist still. Oh, and 12 boxes now? Why so damn many? Xenobio is self-sufficent with monkeys as it is.
Because the setup is designed for 3-4 xenobiologists. 3ish monkey crates each.

> * Xenobio isn't janitorial, nobody else gets light replacer, why do they? Galoshees are fine and understandable. Though TWO replacement boxes for an area that small really is redundancy galore.
Eh. Redundancy doesn't hurt.

> * South facing sinks on lower floor look really awkward without being offset to look like they are mounted to the wall like all other south facing sinks are
They're fine.

> * Random extract why again? Just seems like extremely RNG-based and unnecesary attempt at buffing.
/shrug. If everyone is going to bitch about it, I'll take it out.

> * Why more regular slime pens? Important part of xenobio as a job is management of your pens and space. I don't see why increasing amount by 2 would be needed.
Because it doesn't hurt? I never saw you doing Xenobio, Hero, the fucking place was cramped with more than one person doing slimes at once.

> * Why more than one button for almost every pen? This will create more confusion than it will help, especially  with all the buttons for...

The buttons are for dividers and the doors.
> * Separators. I understand like two or three pens being connectable, but pretty much all of the mis ridiculous, IMO.
Nah. They're good for slime movement.

> * Lightswitch in every pen is pretty redundant.

Again, I disagree.
> * All the windows are way overreinforced. All external windows normally only have one extra panel and thats leading outside. Pen windows, especially ones with 5/4 glass on them are literally irrepairable because that sort of thing is only possible via mapping. Thats why old pens only had 4 directional ones.
Pen windows are dupes from existing xenobio. If they're fully busted, then they're replaced with 4 reg directional ones.

> * Separation of the containment and general levels pretty much removes any threat slimes may possess. Its good that they no longer just leak out into general research hallway, but this pretty much turns any outbreak into utter cakewalk.
This setup was planned with the idea we'd someday have more dangerous xenos than just slimes.

> * On lower level, where xenobiologist would be spending most of their time, there are no chargers.

Go up to S3 to recharge. It's a small bit of walking.
> * There are no watertanks for refilling extinguishers or fueltanks for those welders anywhere in the new xenobio.
The watertanks was an oversight, the fueltanks? Nope. Not having those in xenobio, it's dumb and just causes more problems than it solves.

> * Doublewalls on upper level behind staircase just look awkward with no real purpose to existing.
/shrug. Maybe to you.

> * Support column right outside research airlock doors looks goofy. You could probably delete half of them without ruining the 'view'.
Again, it's fine imo.

> * Old xenobio would be better off either disconnected from hallway (no doors) or just filled with rock with how big and absolutely empty area is. Even construction areas have either smaller size or some proper construction-feeling fluff to them.

Again, not my jurisdiction.

**Comment by Heroman3003** [comment]
> To fuel the airlocks. Same setup every other airlock across the entire damn station has.

Except they use PROPER machinery and proper connection. The connection being BEFORE the air tank and not after, and using a REGULATOR rather tha npump. What you have right now will NOT fuel the airlocks and WILL spill out that entire tank into distro loop of whole station.

**Comment by Rykka-Stormheart** [comment]
> > To fuel the airlocks. Same setup every other airlock across the entire damn station has.
> 
> Except they use PROPER machinery and proper connection. The connection being BEFORE the air tank and not after, and using a REGULATOR rather tha npump. What you have right now will NOT fuel the airlocks and WILL spill out that entire tank into distro loop of whole station.

https://i.gyazo.com/ec60a99e6ea48f78ff15971192eacc7e.png

This is the current setup.

**Comment by cruxxansata** [comment]
Did you know that _anyone_ can use dreammaker?

**Comment by Mewchild** [comment]
Really? You mean the fact that this is an open source codebase, on a free platform, means anybody can try to make changes? Had no idea. Thank you for broadening our horizons.

On a more serious note, I've worked with Rykka a bit on this, trying to get things taken care of in regards to finalizing the last few bugs. I believe this should be good to go

**Comment by Rykka-Stormheart** [comment]
Reconfigures both airlocks to be "internal" airlocks - also fixes the now-unneeded airtank, gives Engineering proper access to the Xenobiology SMES, reworks the doors so that the wires for both Master and subgrid are accessible, rather than one being under a R-wall, fixes small issue with sinks in S2 slime pens.

Removes the xenos from the OR, removes the full-on surgery kit and replaces it with the Morgue's autopsy kit. Fixes multiple unsimulated tiles accidentally left behind.

Now, both airlocks still have some issues with not _locking_. But, at least you can get in and out of them, unlike before.

**Comment by Rykka-Stormheart** [comment]
> Not really a fan of the giant construction area in old xenobio, especially since, unlike most construction areas, it cannot be accessed by the public. Should either be repurposed or just turned into rock.

The construction area was intended for others who requested it, Cain and other scientists. They have plans to use it as the basis of a telesci lab that they have to build during the shift.

**Pull request merged**
