### PR TITLE
Allows sipping proteans/prometheans

### PR DESCRIPTION
**Pull request by Arokha**
Grab a straw and sip!
dreamseeker_L6yDK144Iz

### CODE REVIEW

**Comment by LordSaladin** [comment]
this should apply the victim's vore taste

**Comment by Arokha** [comment]
> this should apply the victim's vore taste

OOO good idea

**Comment by Arokha** [comment]
> this should apply the victim's vore taste

Done

**Comment by dwinters99** [comment]
Hopefully sipping a protean puts 5u of protean shake in the recipient.

**Comment by Arokha** [comment]
> Hopefully sipping a protean puts 5u of protean shake in the recipient.

3 but yes

**Pull request merged**
