### PR TITLE
Makes file pathing for mobs not piss me off

### PR DESCRIPTION
**Pull request by SpadesNeil**
This habit of using memes or pop culture references in code triggers me on a personal level and serves to do nothing but frustrate coders and admins who are trying to find something in the code but unfortunately aren't psychic and can't figure out what fucking path something exists under.

You see this shit?

rous, badboi, wah

**STOP DOING THIS FUCKING SHIT.**

Do I call the frog mobs simple_mob/hostile/pepe? NO I FUCKING DON'T.

[flails angrily in an overreacting manner]

I'm rejecting all future PRs that do this absurd thing with meme names.

### CODE REVIEW

**Comment by Screemonster** [comment]
I think wah is the native name for them from wherever red pandas originate.

**Comment by Ketrai** [comment]
I totes agree with spades here. Like, it infuriates me if I can't find something using the file finder, or the byond file finded in dreammaker, coz someone renamed it to something obscure. And scree, I don't care, red panda is way way more general, I don't think peopel are gonna type in WAh when they're trying to find the simplemob they reference.

**Comment by SpadesNeil** [comment]
>I think wah is the native name for them from wherever red pandas originate.

Put "wah" into google and tell me what you see.

**Comment by Arokha** [comment]
> The Sherpa people of Nepal and Sikkim call it ye niglva ponva and wah donka. The word wậː is Sunuwari meaning bear; in Tamang language, a small, red bear is called tāwām.

From wikipedia, though wah is mostly a furry word

**Comment by SpadesNeil** [comment]
Like I said. Put "wah" into google and tell me what you see.

**Comment by SpadesNeil** [comment]
image
WAH removed

**Pull request merged**
