### PR TITLE
Polaris Sync 2018-03-30

### PR DESCRIPTION
**Pull request by Leshana**
### Features
PolarisSS13/Polaris#5048 - More projectiles now ignite things 
PolarisSS13/Polaris#4931 - Adds a cursed sword (and other haunted things)
PolarisSS13/Polaris#5079 - Adds permanent markers 

### Changes
PolarisSS13/Polaris#5060 - AFK Kicker should affect ghosts and people in the lobby
PolarisSS13/Polaris#5076 - MDs and EMTs spawn with the white medkit
PolarisSS13/Polaris#5098 - Changes to objects random

### Lore Changes
PolarisSS13/Polaris#5068 - terminus is now not just serial-numbers-filed-off Spacer
PolarisSS13/Polaris#5111 - Lore-Compliant Oculum News Channel
PolarisSS13/Polaris#5112 - prettified lorecodex, added a month's worth of news

### Bug Fixes
PolarisSS13/Polaris#5110 - Items in suit storage should no longer vanish.
PolarisSS13/Polaris#5128 - Fixes pAI crew manifest is nonfunctional (PolarisSS13/Polaris#4951)

### Refactor
PolarisSS13/Polaris#5105 - Nanoui now supports use of multiple template
PolarisSS13/Polaris#5072 - **Arranges lots of things into planes**
PolarisSS13/Polaris#5115 - Fix for MOB_CAN_SEE_PLANE
PolarisSS13/Polaris#5126 - Fixes fullbright mode hiding lighting overlays.
PolarisSS13/Polaris#5127 - Table Layering and Runtime Fixes

### CODE REVIEW

**Comment by Natje0** [comment]
I'd rather not have the kit Medical players spawn with get replaced with the weaker one. It just seems entirely unnecesary.

**Comment by Screemonster** [comment]
Eh, no other job spawns with any particularly good job gear, just the absolute basics. Engineers don't even get goggles even though they get a welder, and it's the shit welder which isn't as good as the ones in their lockers. Officers don't start with gear. The detective gets a zippo and a hat. Pretty much any job is going to be underequipped if they charge straight in to work with their spawn gear only, even if they do have an advanced medkit.

**Comment by Cameron653** [comment]
I don't see much of an issue with MDs spawning with a white instead of red medkit. We're not an action server, so a small nerf in starting equipment isn't a huge deal.

**Comment by Wickedtemp** [comment]
I also disagree with the medkit change. It adds nothing except making medical's meta cargo-request-list longer. 

The reason it was changed on polaris was primarily _because_ it's a bit more actiony. They also don't usually have cargo too often, so this was an attempt to make advanced kits a bit more rare.

As for Virgo, well... It's meaningless, we usually have some manner of cargo staff or somebody around to approve cargo orders, so while we'd be able to circumvent this relatively easily, cargo regularly gets 1000+ points, etc. I still can't see a reason to implement this, since, well... It's a meaningless annoyance that we previously wouldn't have.

**Comment by Arokha** [comment]
Headstaff decided the medkit change and ghost observing kick is fine with the additional caveat that it not kick admins who are just on to reply to ahelps.

**Comment by Natje0** [comment]
So medical get yet another inconvenience and it doesn't even get a discussion.
Cameron is right, we're not an action server, it won't have a **huge** impact. But it's yet another inconvenience, on the job that well, has a LOT of inconveniences already. More so than a nerf, it's just another pain in the ass in a job that already has a lot of pains in the ass.

It makes sense in Polaris, BECAUSE they're an action server. Here, it's just another anti-fun bother.

**Comment by Arokha** [comment]
Anything that alters how you play the game and requires an additional step or action can be called an inconvenience, but games themselves are a series of inconvenience strung together to create gameplay. With no problem or conflict, there's no gameplay.

To some players that play here, I know the existence of health and injury at all is an inconvenience, and would just as soon have it removed from the game. Some players play certain species or use certain traits with the sole purpose of removing mechanics they don't want to deal with so they can ERP instead. There are many that would rather the server just be a chatroom with sprites, but that is not the server we are going to host.

We are going to host a server where the gameplay exists. You are calling it 'not an action server', which is true, but it's not "a chatroom" either. The gameplay will exist, and be maintained according to the mission statement we've laid out.

Tweaks to the gameplay will be made, and they simply cannot all be "make X or Y easier or more powerful". Such a thing would only move us further from the game we intend to run. Only allowing change in one direction is not something we're going to allow ourselves to be limited by. Everything that's not an increase in power can be called "an inconvenience", because sure, any time we think something is unnecessarily powerful, lowering how powerful it is is adding "an inconvenience". That doesn't mean it's a bad thing.

Also keep in mind, SS13 and VS are continually evolving. The game isn't finished, nor will it ever be. There will be changes. Some of them will alter or weaken functionality. I'm sure other changes are coming down the pipe that alters how medical works, and one of the things I'd like to do is buff ATK/ABKs a bit, which would mean everyone spawning with them would be even more powerful. 

So, none of these changes should be considered in isolation. They should be considered in the continually evolving ecosystem of players, admins, and gameplay we're working on. None of them are intended to be "I want to annoy these players" and the occasional assertions that, in fact, that's somehow the true goal of these changes is asinine and needs to stop. There's zero reason we'd try to annoy a player, or a group of players on purpose.

**Comment by Natje0** [comment]
Leave the extremes out of this please. It's really frustrating to try to give feedback only to be slapped with things like "Oh but everything is an inconvenience, what, you want a chatroom?"

And how many inconveniences are we going to give Medical players? When will we GIVE instead of TAKE? It is incredibly demotivating when you look at how Medical as a department is being changed. Things are being taken, nerfed, removed.
The only things I can think of, that is solely a positive that we've added to make Medbay more fun to play, is the bio-printer that's been desired and yearned for for god-knows how long, and the synthesizer that will show god-knows-when.

The game is constantly evolving yes. But the way Polaris is taking medbay is not a way I want to see here.
Why?
Because I want it to be **fun** to play in medical.

I will not support such a change until 
# **AFTER**
the advanced trauma kits are changed to actually be _significantly_ better than gauze.

We've done a fair bit of pre-emptive nerfs in preparation of features that are **PLANNED**.
Just look at mining. There's so many plans there, and they lost the RIGsuit for a while there in _preparations_ for a feature that was _planned_.
They've yet to get any of those features.

I don't want to see that pre-emptive nerf crap happen any more. Give the nerfs when we get the features they're meant to balance.

**Comment by OrbisAnima** [comment]
Technically is ok, Guys, this is coming from Polaris, if its an issue just propose a change and then add it ON TOP of our stuff, there is no reason to put on hold a sync for stuff that can be later adapted to the game.

**Pull request merged**
