### PR TITLE
Fulpstation Labcoats

### PR DESCRIPTION
**Pull request by GhostActual**
Ports over all Labcoats from Fulpstation and changes those that weren't at Fulpstation to match the art style of those ported. As an added bonus to the new Roboticist Labcoat, there is also a new Techpriest Robe that is contraband inside the Robodrobe.

I could make an image of all the Labcoats I ported to showcase them all but I am tired.

### CODE REVIEW

**Comment by Very-Soft** [comment]
These look great!

**Comment by GhostActual** [comment]
Had to convert to draft, forgot to change the `on_mob` sprite for the `cmoalt` labcoat

**Comment by KasparoVy** [comment]
Damn, the rework of the classic labcoats the folks at Fulp did is bloody awesome, thanks for the port!

Not sure if it's a problem in the DMI too butt the icondiffbot says there's a rogue pixel in the south-facing sprite of the techpriest onmob.
image

**Comment by GhostActual** [comment]
> Damn, the rework of the classic labcoats the folks at Fulp did is bloody awesome, thanks for the port!
> 
> Not sure if it's a problem in the DMI too butt the icondiffbot says there's a rogue pixel in some of the techpriest onmob south-facing sprite's frames.
> image

I will check that too

**Comment by GhostActual** [comment]
> Damn, the rework of the classic labcoats the folks at Fulp did is bloody awesome, thanks for the port!
> 
> Not sure if it's a problem in the DMI too butt the icondiffbot says there's a rogue pixel in some of the techpriest onmob south-facing sprite's frames.
> image

Error with the DMI check, no pixel found

**Comment by Arokha** [comment]
Alas, a labcoat PR opened before yours conflicted. Sorry! When these things happen I try to do first-opened merges first so, in this case yours was opened later and so you get to resolve the merge conflict.

It was the RD's labcoat, so just copy those icon states to yours for those two files and you're good.

**Comment by GhostActual** [comment]
> Alas, a labcoat PR opened before yours conflicted. Sorry! When these things happen I try to do first-opened merges first so, in this case yours was opened later and so you get to resolve the merge conflict.
> 
> It was the RD's labcoat, so just copy those icon states to yours for those two files and you're good.

>:[

**Pull request merged**
