### PR TITLE
Enables Novel Posting

### PR DESCRIPTION
**Pull request by R3dtail**
Doubles Max_message_len from 2048 to 4096

Because I hate having to break up posts and this would at least mitigate it somewhat , additionally making it easier for folks to get their posts out without worrying AS MUCH about the 2048 character limit should? be decent.

### CODE REVIEW

**Comment by Very-Soft** [comment]
I'm fine with this personally, unless there's some kind of technical reason this is a bad idea or whatever. It doesn't happen often, but it's annoying when you hit the text cap, so I'm fine with it being raised.

**Comment by Wickedtemp** [comment]
Totally support this. Text caps are annoying.

**Comment by dwinters99** [comment]
image
Thank you.

**Comment by TheFurryFeline** [comment]
Also supporting this as a novel poster >w>

**Comment by Tenryumi** [comment]
Yes please. I WANT this.

**Comment by Arokha** [comment]
> image
> Thank you.

Hey be glad I added that message instead of it just vanishing into the ether which is what it did before |3

**Pull request merged**
