### PR TITLE
Lighter than air

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

Replaces various outdated Atmos sprites and outright deletes the ones that are no longer used at all in the codebase (i.e. the Heater and Vent sprites that were sitting in atmos.dmi). These sprites come straight from the TG codebase with some key changes to the stationary siphon (basically remade it from scratch while taking inspiration from the portable siphon). I also created new medpump sprites so that all the portables match (the vent on top of the medpump is a heat exhaust vent, I swear).

EDIT: Added a hard-port of the canisters from Eris cause they're just /TG canisters that have static colors (I was too lazy to color them myself)

EDIT 2: Tried to also address stationary Pipe Tanks but my idea just wasn't hitting.

atmos_showcase

## How This Contributes To The VOREStation Roleplay Experience

Honestly just replaces the current sprites that are in the codebase with much better looking sprites.

## Changelog

:cl:
del: Removed Heater sprites from atmos.dmi
del: Removed Vent sprites from atmos.dmi
image: Changed the portable siphon sprite
image: Changed the portable scrubber sprite
image: Changed the stationary siphon sprite
image: Changed the stationary scrubber sprite
image: Changed the medpump sprite
image: Changed the N20 medpump sprite
image: Ported Eris canister sprites
image: Added Phoron Eris style canister
image: Added Purple Eris style canister
/:cl:

### CODE REVIEW

**Comment by Enzo-Leon** [comment]
Nice c:

**Comment by Heroman3003** [comment]
Can't personally say I like any of the new sprites.

**Comment by Runa-Dacino** [comment]
image


These look like it'd be very difficult to see at-glance if they're full, half-full, near-empty or empty.

**Comment by Youtubeboy139** [comment]
> image
> 
> These look like it'd be very difficult to see at-glance if they're full, half-full, near-empty or empty.

Sprite-0001

**Pull request closed without merging**
