### PR TITLE
Discord integration

### PR DESCRIPTION
**Pull request by Leshana**
Please remind me which thing I forgot to do.

### CODE REVIEW

**Comment by JoanRisu** [comment]
The faxes go straight to Central Bridge, yes? Making sure.

**Comment by SpadesNeil** [comment]
We should probably have a specific fax channel.

**Comment by JoanRisu** [comment]
We already have too many channels. We should try not to over populate ourselves unless absolutely necessary.

**Comment by Leshana** [comment]
The destination of the faxes is not part of this code, or any code.  That is a configuration within discord.   
It uses discord webhooks, which can be assigned from channel in the discord server configuration.

**Comment by SpadesNeil** [comment]
Well I know _that_, I just mean we don't want fax messages spamfucking our admin channel. :U 

Also we should probably bump this upstream to Polaris too at some point. It's useful.

**Comment by SpadesNeil** [comment]
So once this is uploaded what needs doing in the config?

**Pull request merged**
