### PR TITLE
Adds a new neutral metabolism trait.

### PR DESCRIPTION
**Pull request by Verkister**
After consulting people who the hardly noticeable totally optional high-metabolism trait has made suffer, I've decided to add a new one instead for a noticeable arpee fluff one-uppance!
-It's double powerr!
-Gives pred characters an excuse to do their pred things.
-Aimed majorly for arpees as pred/macro/taur characters.
-Not recommended for efficient law-abiding workers or eco-aware NIF users.
-Saves exercise for Sportaflop!

### CODE REVIEW

**Comment by SpadesNeil** [comment]
OOooo this is nifty

So it makes them hungry faster?

**Comment by Verkister** [comment]
Basically yeah.
Also affects reagent processing speeds, which may be really good or really bad depending on the stuff. Which might also add a llittle pinch of chaotic seasoning to the flavor, but hopefully not too badly heh.

**Comment by SpadesNeil** [comment]
Closed?

**Comment by SpadesNeil** [comment]
This could have some unintended side effects so let's test this once it's in-game.

**Pull request merged**
