### PR TITLE
Removes redundant vulp ear markings

### LINKED ISSUE #8501: Hair overlapping anthro ears
#### Brief description of the bug
"Hawk" haircut overlaps the "wolf, colorable" ear when looking from the side.

#### What you expected to happen
The hair sprite layer should be behind the ear sprite layer.

#### What actually happened
The "Hawk" haircut is overlapping the "wolf, colorable" ear when looking from the side. I'm seeing the hair first and the ear in the background.

#### Steps to reproduce
- In the Character Setup screen, select haircut "Hawk";
- In the Character Setup screen, select "wolf, colorable" ears;
- Look at the side previews on the right.

#### Anything else you may wish to add:
Bald (ear sprite entirely visible):
image

Hawk (ear sprite partially hidden behind hair sprite):
image

### PR DESCRIPTION
**Pull request by Verkister**
-Removes 2 markings, "ears and face (vulp)" and "all head highlights (vulp)". Both are redundant since we have a proper ear system to slap those ears onto their correct layer rather than be a facepaint, and without the ear parts those markings were both just duplicates of the vulp face marking.

Fixes #8501

### CODE REVIEW

**Comment by KasparoVy** [comment]
:( I readily use these markings on a number of characters in conjunction with certain ears. All head highlights is the vulpkanin 'points' head marking from para. It lets you build custom 'ears' when used appropriately

eg. (uses all head highlights)
all head highlights are involved

and (uses all head highlights and the face + ears markings)
all head highlights are involved 2

The all head highlights also covers certain pixels that other markings do not (without being overly obstructive)
all head highlights are involved 3

I've spent a lot of time discovering various marking combinations to make shit pixel perfect, and I'd really rather these not be removed

**Comment by KasparoVy** [comment]
I readily use these markings on a number of characters in conjunction with certain ears. All head highlights is the vulpkanin 'points' head marking from para. You can use these markings in conjuction with other ear designs in the VORE tab to craft custom sprites & otherwise colour pixels where some markings aren't the most suitable

I've spent a lot of time discovering various marking combinations to make shit pixel perfect, and I'd really rather these not be removed. I've seen others use this strategy in character design as well

Instead of removing these, folks should use the proper ears from the ears section under the virgo tab - literally just takes a moment to figure out

@Verkister Please don't.

eg. (uses all head highlights & otie ears)
all head highlights are involved

and (uses all head highlights and the face + ears markings)
all head highlights are involved 2

The all head highlights also covers certain pixels that other markings do not (without being overly obstructive) -- corner of the inner ears connecting to brow
all head highlights are involved 3

I could provide a number of character designs here but the point is that these markings do have a use

**Comment by Verkister** [comment]
Point taken.

**Comment by KasparoVy** [comment]
Thank you kind sir

**Pull request closed without merging**
