### PR TITLE
Removes some redundant code.

### PR DESCRIPTION
**Pull request by SpadesNeil**
ToDo: Fix missing sound effects for guns.

Why the fuck does this check map diff renders?

### CODE REVIEW

**Comment by Cyantime** [comment]
If the firing sound is defined on the gun, it overrides the projectile's effect. This was intentional with the phaser.

**Comment by Novacat** [comment]
This does not happen, or is broken. The projectiles sound is overriding the gun sounds.

**Comment by Arokha** [comment]
All PRs check for map and icon diffs. That was the first one to run, though, and failed because:

image

**Comment by SpadesNeil** [comment]
:laughing: :gun:

**Comment by Anewbe** [comment]
~~Oh look, it's this jackass Anewbe jumping in again for no real reason!~~

The projectile sound is [supposed](https://github.com/VOREStation/VOREStation/blob/master/code/modules/projectiles/gun.dm#L680) to override the gun's sound, for things where multiple projectile types with different sounds can be fired (ie. Shotguns, Eguns).

**Comment by SpadesNeil** [comment]
@Anewbe In the context of shotgun ammunition, I see now why you would want to do this.

That said, I think the override should be the other way around. Different ammo may produce different sounds, but unique sounds may be desired for the sake of fluff--especially with energy weapons--while still using the same projectile as other, similar weapons.

But that's just my opinion on the matter.

**Pull request closed without merging**
