### PR TITLE
Custom_items.txt wasn't properly updated! [Fluff LeMat]

### PR DESCRIPTION
**Pull request by HzDonut**
Whoopsie daisy, error got caught and it's been fixed now.

### CODE REVIEW

**Comment by Arokha** [comment]
Diff is weird, doesn't work right in testing.

**Comment by HzDonut** [comment]
It was just a recompile issue and has been solved. Code checks out despite odd PR. Files identical to ones in last PR as well.

**Comment by HzDonut** [comment]
Raw from the first merge as proof: https://imgur.com/a/ecQS0

**Comment by HzDonut** [comment]
https://i.imgur.com/yU2q85Z.gifv and showing that everything works as intended, it's just a weird github issue.

**Comment by Leshana** [comment]
Something is wacko wrong with the commits, and the fork was deleted.

**Pull request closed without merging**
