### PR TITLE
icon fixes

### PR DESCRIPTION
**Pull request by cadyn**
upport of https://github.com/CHOMPStation2/CHOMPStation2/pull/7943

🆑
fix: fix icons
/:cl:

### CODE REVIEW

**Comment by cadyn** [comment]
oh just realized you guys don't actually have the 515 stuff yet. This should work fine once those changes are in.

**Comment by Kashargul** [comment]
I've made the last adjustments on this for the ntos downstream, if you want, you can up port them here, cadyn.

**Comment by Heroman3003** [comment]
we have 515 changes now but conflicts and needs update

**Comment by cadyn** [comment]
should be good now I believe, still a backlog of other PRs that should probably be upported, but god knows I'm tired after all the overhauling I did downstream

**Pull request merged**
