### PR TITLE
Bathroom Privacy

### LINKED ISSUE #10160: Bathroom stalls don't have locks
i have kinda known this for a while i guess, but why do things like reading rooms have locks and yet bathroom stalls don't?? privacy is important :disbelief:

### PR DESCRIPTION
**Pull request by TheFurryFeline**
Closes #10160. Lots of door name changes because dumb instances messed things up to the point I had to give different names for different bathroom locks, weh.

- maptweak: Adds locks to dorm bathrooms, Research bathroom, Surface Sec bathroom, Surface Med bathrooms, Surface Recovery bathrooms, Recreational bathrooms, bar restrooms, bathrooms near space burial, engy bathrooms, Asteroid Med Recovery bathroom, Asteroid Med bathroom, Asteroid Sec bathroom.
- maptweak: Removes Sec spawnpoint from bathroom because why?
- maptweak: Changes wall in IAA's Fax room to a window so they can see it's there.

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Pfft, and now the mapdiffbot broke on this one.

**Comment by TheFurryFeline** [comment]
Wait, when the hell did the pullbot commits pop in? That wasn't there when I compared this before PR'ing!

**Comment by Heroman3003** [comment]
> 
> 
> Closes #10160. Lots of door name changes because dumb instances messed things up to the point I had to give different names for different bathroom locks, weh.
> 🆑
> 
>     * maptweak: Adds locks to dorm bathrooms, surface brig bathroom, Research bathroom, Surface Sec bathroom, Surface Med bathrooms, Surface Recovery bathrooms, Recreational bathrooms, bar restrooms, bathrooms near space burial, engy bathrooms, asteroid brig bathroom, Asteroid Med Recovery bathroom, Asteroid Med bathroom, Asteroid Sec bathroom.
> 
>     * maptweak: Removes Sec spawnpoint from bathroom because why?
> 
>     * maptweak: Changes wall in IAA's Fax room to a window so they can see it's there.
> 
> 
> /🆑

IMO, the bathrooms in the brig itself should not be lockable because prison and its functionality.

**Comment by TheFurryFeline** [comment]
> > Closes #10160. Lots of door name changes because dumb instances messed things up to the point I had to give different names for different bathroom locks, weh.
> > 🆑
> > ```
> > * maptweak: Adds locks to dorm bathrooms, surface brig bathroom, Research bathroom, Surface Sec bathroom, Surface Med bathrooms, Surface Recovery bathrooms, Recreational bathrooms, bar restrooms, bathrooms near space burial, engy bathrooms, asteroid brig bathroom, Asteroid Med Recovery bathroom, Asteroid Med bathroom, Asteroid Sec bathroom.
> > 
> > * maptweak: Removes Sec spawnpoint from bathroom because why?
> > 
> > * maptweak: Changes wall in IAA's Fax room to a window so they can see it's there.
> > ```
> > 
> > 
> > /🆑
> 
> IMO, the bathrooms in the brig itself should not be lockable because prison and its functionality.

I was unsure about that myself and can remove those upon request from buttlynx or a 'min.

**Review by Novacat — CHANGES_REQUESTED** [review]
Brig bathrooms should not be lockable, I agree with that.

**Comment by JoanRisu** [comment]
Just remove the lock in the brig and this should be good to pass

**Comment by TheFurryFeline** [comment]
> Brig bathrooms should not be lockable, I agree with that.

Will commit update after arriving at home after class.

**Comment by TheFurryFeline** [comment]
Done, had to renumerise all id tags after removing surface brig bathroom lock, lol.

**Review by Novacat — APPROVED** [review]

**Pull request merged**
