### PR TITLE
Add wood wall sprites

### PR DESCRIPTION
**Pull request by CashMoneyMoney**
image

Adds in new wall sprites for walls made out of wood.

### CODE REVIEW

**Comment by CashMoneyMoney** [comment]
For any people wondering if it might merge with existing walls:

image

**Comment by SpadesNeil** [comment]
Not really a fan of the riveted look. The lack of texture makes it look more like brown plastic.

**Comment by CashMoneyMoney** [comment]
image

**Comment by Cameron653** [comment]
The sprites look good, but this touches a normal .dm file.
You'd probably be better off sending this to Polaris.

**Comment by Cameron653** [comment]
Upon second look, apparently Arokha modified these .dmi files already. So we're going to have conflicts if these files ever get changed on Polaris anyways, so it's not an issue to add these in. Not sure what to do with this PR, though.

**Comment by Cameron653** [comment]
Looked at the code again and saw why. It'd be a fucking nightmare to modify the code instead of having the .dmi conflict.

See: https://github.com/VOREStation/VOREStation/blob/d63303f136b124d2c91dbd98b3a600a3be95cc5b/code/game/turfs/simulated/wall_icon.dm

In this case, modifying a regular .dmi file is fine. This should be ready for merge.

**Comment by Belsima** [comment]
I might steal this for Polaris in my next wave of PRs, just as a note, since I heard that might explode things.

**Comment by SpadesNeil** [comment]
Marking this in case we need to look up the conflict later.

**Pull request merged**
