### PR TITLE
Adds new alt titles

### PR DESCRIPTION
**Pull request by Aroliacue**
Properly adds in some alternate titles for security, engineering and medical. Also closing my previous Search and Rescue PR as it is shitcode and also now irrelevant.

### CODE REVIEW

**Comment by lm40** [comment]
IF ANYTHING, plumber should be atmos tech although overall I think it a bad alt-title

**Comment by Aroliacue** [comment]
The lowly plumber is naught but a hydroponics basin builder, milord

**Comment by Heroman3003** [comment]
Plumber is too memey and completely unrelated to anything engineering actually does imo.
Architect seems rather unfitting to me too tbh.

Constable I think is good conceptually, but for some reason im just getting iffy vibes from it.

**Comment by Aroliacue** [comment]
>

**Pull request closed without merging**
