### PR TITLE
Fixed a minor issue that's kinda been overlooked for a while

### PR DESCRIPTION
**Pull request by Zandario**
Was merging _vr files manually down-stream on CitadelRP when I noticed two `/datum/category_item/catalogue/technology/drone/hivebot/laser`'s in `code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage_vr.dm`
Soooo... I fixed it, the end?

### CODE REVIEW

**Comment by Zandario** [comment]
Oh seems an icon thing got in?? One second.

**Comment by Zandario** [comment]
Haha
`## UNIT_TEST: !! FAILURE !! [MAP: Active edges (all maps)]: Maps contained 1 active edges at round-start.`
Can't wait till we fix this :)

**Comment by KasparoVy** [comment]
Thank you kindly

**Comment by TheFurryFeline** [comment]
Just close/reopen the PR to fix the active edge issue there. It's a semi-common issue caused by some of Polaris's POIs not mixing well with Virgo 3b's natural phoron atmos tiles when exposed to each other.

**Comment by Zandario** [comment]
Ah I see

**Pull request merged**
