### PR TITLE
Adds in a new prosthetic limb set.

### PR DESCRIPTION
**Pull request by Cameron653**
This is a new feature

Proposed changes in this Pull Request:

- Adds in "Talon LLC" prosthetic limbs.

Additional information:
Sprited by Viveret
Sprite example: http://puu.sh/pj7TT/5815f2174b.png

### CODE REVIEW

**Comment by SpadesNeil** [comment]
The sprites look offset.

**Comment by killer653** [comment]
They all look offset on the title screen. They're perfectly functioning in game.

**Comment by Cameron653** [comment]
They all look offset on the title screen. They're perfectly functioning in game like all the other sprites. I just took the title screen photo as it was the most convenient one.

**Comment by viv-eret** [comment]
My god what have i done

**Comment by Cameron653** [comment]
Non offset icons: http://puu.sh/pisiz/111c20bbcb.png

**Comment by Arokha** [comment]
Think you accidentally included talon_main.dmi twice, once in the right place, and once in the root. Copy-paste error maybe?

**Comment by SpadesNeil** [comment]
>Non offset icons: http://puu.sh/pisiz/111c20bbcb.png

Those are definitely offset. Look at the legs at the hips.

**Comment by viv-eret** [comment]
I got no idea what i need to do.
I just sprited it.

**Comment by Cameron653** [comment]
Oh, I see the issue. Fixing.

**Comment by Cameron653** [comment]
DNM until I actually fix the sprites.

**Comment by Cameron653** [comment]
Fiiiixed

**Pull request merged**
