### PR TITLE
Update alienwhitelist.txt

### PR DESCRIPTION
**Pull request by Rixunie**

### CODE REVIEW

**Comment by SpadesNeil** [comment]
It's Gutterband, not just gutter. :P Fixed it.

**Comment by Cyantime** [comment]
The language is "gutter", if you search for "gutterband" the only file that comes up is the whitelist file.

**Comment by SpadesNeil** [comment]
In that case there's two screwed up.

**Comment by SpadesNeil** [comment]
Fixed it.

**Pull request merged**
