### PR TITLE
Add Mining Music Tracks

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
Add Mining Music, courtesy of Chompers.

These use Forced_Ambience, meaning they WILL play. If that's annoying, I can tone it back to "regular" ambience.

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Posting just to say that the soundtracks are pulled from an old Lego game called Rock Raiders back in the last year of the 20th century: https://en.wikipedia.org/wiki/Lego_Rock_Raiders_(video_game)

**Comment by KasparoVy** [comment]
Sounds like the PC version, too. Mint

**Comment by lbnesquik** [comment]
While i dig the idea, having an option to turn them off is always nice, especially for mining so people can watch youtube or something without the game music poking in.

**Comment by TheFurryFeline** [comment]
That's a good idea for another PR, client-side toggleable music

On Nov 9, 2019 01:32, "Kates" <notifications@github.com> wrote:

While i dig the idea, having an option to turn them off is always nice,
especially for mining so people can watch youtube or something without the
game music poking in.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/VOREStation/VOREStation/pull/6140?email_source=notifications&email_token=AJGMTY3WWAFP5M4QFUGBFGDQSZKORA5CNFSM4JGSO5WKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDT7DJA#issuecomment-552071588>,
or unsubscribe

**Comment by KasparoVy** [comment]
Can confirm, am bumping tunes 24/7 when mining (probably was listening to music already but still), but do have ambience/etc. left on.

**Comment by SpadesNeil** [comment]
Unfortunately, adding these songs would probably not be kosher as far as copyright stuff goes. We already have some dodgy stuff in the game's soundtrack that we just hope nobody notices. Best not add more.

**Comment by TheFurryFeline** [comment]
Shame, it's good stuff for old music.

On Nov 23, 2019 23:38, "Spades" <notifications@github.com> wrote:

Unfortunately, adding these songs would probably not be kosher as far as
copyright stuff goes. We already have some dodgy stuff in the game's
soundtrack that we just hope nobody notices. Best not add more.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/VOREStation/VOREStation/pull/6140?email_source=notifications&email_token=AJGMTYZF24C7ZKRFTHISPCDQVIALXA5CNFSM4JGSO5WKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFADT4Y#issuecomment-557857267>,
or unsubscribe

**Pull request closed without merging**
