### PR TITLE
Nutrition + Diet Changes

### PR DESCRIPTION
**Pull request by Yoshax**
- Adjusts food to be 1/3 of its current effectiveness, meaning you can actually go eat something from the chef when you're hungry and not end up with 800 nutrition
- Makes Liopzine more effective so people can lose nutrition more easily
- Makes the diet pill in the fitness vendor actually effective

### CODE REVIEW

**Comment by SpadesNeil** [comment]
I like the changes, but I wanna see what others think too.

**Comment by Arokha** [comment]
I think it makes sense. You really couldn't eat much at all before being superfull.

**Comment by Screemonster** [comment]
> eat 1 steak
> never have to eat for the rest of a 6 hour shift

Now Scree has an excuse to steal the entire fridge.

**Comment by Wickedtemp** [comment]
I personally liked the 'weight-gain' flavor text you'd get from reaching max nutrition and all. Buuuut, can confirm, you drink 1 protein shake and you now have a 'massive rounded belly filled with glorping slush, they must have eaten twice their weight!' message, or somewhere around there.

**Comment by Yoshax** [comment]
You can still get it. You just need to eat an actual reasonable amount.

**Comment by AaronSherwood117** [comment]
Definitely like this change.  Not sure what exact effect 1/3 will have, but later balances can be made. At least people can actually justify grabbing a meal instead of eating one thing shoved onto the counter.

**Comment by Screemonster** [comment]
It was kinda silly that a burger provided more nutrition than, like


an entire guy

**Comment by AaronSherwood117** [comment]
Are we talking an entire guy in the gibber, or swallowed whole? Hard to tell sometimes.

**Comment by Arokha** [comment]
Seems like positive feedback from everyone. MERG.

**Pull request merged**
