### PR TITLE
Fixes bugs with suit sensors and tether levels

### PR DESCRIPTION
**Pull request by Heroman3003**
title, the weird spam is no more

### CODE REVIEW

**Comment by Burrito-Justice** [comment]
For the record, this is the spam in question:

**Comment by Heroman3003** [comment]
It will now just send a single message and close the window. If you try to open it again manually, another single message is sent.

**Comment by Wickedtemp** [comment]
What areas close the sensors monitor, because it'd be annoying as fuck to be looking for someone and moving around and keeping an eye on their status and have the window close.

**Comment by Heroman3003** [comment]
Shuttle transit areas and Central.

**Pull request merged**
