### PR TITLE
Adjust winged flight cost and description.

### PR DESCRIPTION
**Pull request by lbnesquik**
I fucked up trying to improve the number of commits by squashing but, made a mess instead. So here. New PR. Same content.

Previous link:
https://github.com/VOREStation/VOREStation/pull/4321

### CODE REVIEW

**Comment by Arokha** [comment]
This is slightly less meh to me than moving it to neutral but still slightly meh. Can leave it here for a bit to get opines.

**Comment by Screemonster** [comment]
Slightly less meh. Making the trait actually useful so it's worth the cost is preferable, but also effort.

**Comment by lbnesquik** [comment]
I am thinking of improving the perk overall but rn i'd like to have this pass through

**Comment by SpadesNeil** [comment]
I'm okay with this.

**Pull request merged**
