### PR TITLE
Add a lot of clothes/armor/suits/spacesuits/rigs

### PR DESCRIPTION
**Pull request by Arokha**
Sprites courtesy of whoever the sprite wizard at Eris is. They're real good.

annotateddreamseeker_ievZxnRyUI

**New default paramedic uniform:**
Paramedic uniform (/obj/item/clothing/under/rank/medical/paramedic)
dreamseeker_LqMQJbvvFB

**Available in loadout, lockers, and vendors on station:**
Cargo jacket (/obj/item/clothing/suit/storage/cargo) - 8 in image
Summer dress (/obj/item/clothing/under/summerdress) - 12 in image
Summer dress, red (/obj/item/clothing/under/summerdress/red) - 13 in image
Summer dress, blue (/obj/item/clothing/under/summerdress/blue) - 14 in image
Detective trenchcoat (/obj/item/clothing/suit/storage/det_trench/alt/black) - 15 in image
Detective trenchcoat (/obj/item/clothing/suit/storage/det_trench/alt2/black) - 16 in image
QM coat (/obj/item/clothing/suit/storage/qm) - 17 in image
Modern labcoat (/obj/item/clothing/suit/storage/toggle/labcoat/modern) - 18 in image
Modern CMO labcoat (/obj/item/clothing/suit/storage/toggle/labcoat/modern/cmo) - 19 in image
Cyberpunk jacket (/obj/item/clothing/suit/cyberpunk) - 20 in image

**Available in a cargo crate:**
Modern biosuit (/obj/item/clothing/suit/bio_suit/modern) - 3 in image
Modern biohood (/obj/item/clothing/head/bio_hood/modern) - 3 in image

**All admin-spawn/event stuff for now:**
Makeshift voidsuit (/obj/item/clothing/suit/space/void/makeshift) - 1 in image
Makeshift voidhelmet (/obj/item/clothing/head/helmet/space/void/makeshift) - 1 in image
Crusader armor (/obj/item/clothing/suit/armor/crusader) - 2 in image
Crusader helmet (/obj/item/clothing/head/helmet/crusader) - 2 in image
HEV suit (/obj/item/clothing/suit/space/void/hev) - 4 in image
HEV suit, violet (/obj/item/clothing/suit/space/void/hev/violet) - 4 in image
HEV helmet (/obj/item/clothing/head/helmet/space/void/hev) - 5 in image
HEV helmet, violet (/obj/item/clothing/head/helmet/space/void/hev/violet) - 5 in image
Custodian armor (/obj/item/clothing/suit/space/void/custodian) - 6 in image
Custodian helmet (/obj/item/clothing/head/helmet/space/void/custodian) - 6 in image
Aether voidsuit (/obj/item/clothing/suit/space/void/aether) - 7 in image
Aether voidhelmet (/obj/item/clothing/head/helmet/space/void/aether) - 7 in image
Excelsior uniform (/obj/item/clothing/under/excelsior) - 9 in image
Excelsior uniform (/obj/item/clothing/under/excelsior/mixed) - 10 in image
Excelsior uniform (/obj/item/clothing/under/excelsior/orange) - 11 in image
Leather coat (/obj/item/clothing/suit/storage/bladerunner) - 21 in image

**Some new hardsuits:**
F.P.E. hardsuit (/obj/item/weapon/rig/focalpoint) - 22 in image
Hephaestus hardsuit (/obj/item/weapon/rig/hephaestus) - 23 in image

### Somewhat unrelated bugfixes
- Voidsuit dispensers trying to shove tanks into your hand after attaching them to the voidsuit
- Helmet light sprites not being added to helmets when on
- Admin list VV removing an item from list misses alert
- Add rig menu button to top left so it's easier to get to
- Fixes https://github.com/VOREStation/VOREStation/issues/11028
- Added an /autoequip subtype of dummy that equips anything from it's turf when it loads

### CODE REVIEW

**Comment by Kraseo** [comment]
can you please stop stealing sprites from servers with wildly different artstyles that don't match up with ours at all

**Comment by TheToaster98** [comment]
Like my last comment, I don't believe we should have these sprites here.
Because yes, it looks amazing, they are very good sprites... for Eris.
They don't fit, the style doesn't fit, the itemform perspective doesn't fit.
Compare the current default gear that you spawn with, with the paramedic uniform(and with compare, I mean post a picture.), there is dissonance, it mixes bad, it doesn't F I T.
If you are going to go with anyway, which I expect you to, since you did so with the last sprite ports even when people complained about it, at least add a way to get the current uniform in the loadout.

**Comment by Arokha** [comment]
`can you please stop stealing sprites from servers with wildly different artstyles that don't match up with ours at all`

You can only say this until I steal enough sprites that it matches up with our artstyle 🙃 

`with the paramedic uniform`, `at least add a way to get the current uniform in the loadout`

There is no current paramedic uniform, you just start with scrubs. Scrubs are already in the loadout.

`even when people complained`

Yes, we do things even when people complain, especially if the number of people complaining is a tiny minority.

**Comment by Hatterhat** [comment]
> 
> 
> `can you please stop stealing sprites from servers with wildly different artstyles that don't match up with ours at all`
> 
> You can only say this until I steal enough sprites that it matches up with our artstyle 🙃

have you considered that an artstyle consisting of stolen sprites isn't an artstyle

**Comment by Flump1** [comment]
As has been mentioned before, these sprites clash incredibly hard with the established art style of the server. This is already **jarringly** apparent with previous merged sprites such as the beakers and the chem fridge, and stealing more sprites only intensifies the issue instead of addressing it.

On another note:

> we do things even when people complain, especially if the number of people complaining is a tiny minority.

Only a tiny minority of the playerbase interacts with the github in the first place, ergo **any** complaints would be made by a tiny minority, so this comment is not valid.

**Comment by Arokha** [comment]
> have you considered that an artstyle consisting of stolen sprites isn't an artstyle in and of itself

No because that sentence doesn't make sense. First you claim that we have a different art style than Eris and it's 'wildly different', which is a totally fine subjective opinion about art, but now you're claiming that somehow taking Eris's artstyle and moving it here makes it 'stolen' and thus 'not an art style'.

Keeping in mind my reply was a comment about "yeah, once we have mostly Eris sprites then it won't be a big deal and the other, older sprites will be the ones that are 'bad'", it's a pretty big disservice to Eris's spriters/sprites to say that even in that case, that they are 'stolen' and therefore 'not an art style any longer'. Like, I don't think you should really say that Eris's sprites are 'only good on Eris' even if a server has mostly Eris sprites. In that case I'd have to ask what you'd consider an 'art style' at all. Is something an 'art style' only if it's being presented by the creator?

> adding more of these clashing sprites only intensifies the issue instead of addressing it.

Until most of the sprites are made to match, sure, it might clash, but:

> Only a tiny minority of the playerbase interacts with the github in the first place, ergo any complaints would be made by a tiny minority, so this comment is not valid.

This is not 'invalid', it's a statement of fact, regardless of how you want to read it. Whether you read "a tiny minority of people who play on vorestation" or "a tiny minority of people who comment on github" or "a tiny minority of people who comment on github who are a tiny minority of people who play on the station", it doesn't matter. It's true in every case. If you're somehow also packing in an inference to "and also I think most players are represented on github" into what I said, then you are incorrect in that inference. I think you might be (incorrectly) assuming that most people don't use GitHub because they have some technical impediment and really want to express their opinions but just can't. This is not the case. Most people just don't care, and want to do RP and play space station game. They could not care less about the art styles or clashing sprites. So if you want to draw an inference from what I said, you can take away "I think only a minority cares at all about 'art style consistency', and even if 100% of that group complains, it's still a minority". I don't think 100% of that group is complaining, either way.

**Comment by Arokha** [comment]
dreamseeker_yt8mPfAVCV

Someone requested I also port the Excel suit so I did

**Pull request merged**
