### PR TITLE
Removes Security

### PR DESCRIPTION
**Pull request by SpadesNeil**
Because apparently we can't have nice things anymore and because so many people abuse the position of security to play backseat admin, cause drama, and generally be obnoxious shitters, I've decided that the most logical course of action is to remove security. A number of players have already requested this for months and frankly I'm sick of listening to shitcurity causing problems every other day.

Security job slots have been disabled for now, and the security part of the station has been blocked off, weapons removed, and the power cut as an IC placeholder until we decide what to do with the empty space.

### CODE REVIEW

**Comment by Cameron653** [comment]
Yeah... This is going to cause a _lot_ of controversy. Security is a pretty essential part of the station, and I don't think too many people are going to take kindly to this. I know you and a few others have been talking about removal of security due to people abusing it, but I really don't think this is the correct way to go about it. There has been suggestions on better ways to take care of this, and this feels like a knee-jerk reaction to what just recently happened. Please think about this before you embarrass yourself.

**Comment by OrbisAnima** [comment]
I think you should merge it and do a pilot test of this, to see how people receive it.

**Comment by JoanRisu** [comment]
Woah hey, finally we're doing this. 

I dunno, I'm usually a security advocate but lately the whole department has been a problem in the complaints department. I know people are a liiiiittle antsy about "punishing the many for the acts of the few" with code but I think we should give this a chance.

**Comment by OrbisAnima** [comment]
I already made an app to be a private detective.

**Comment by Poojawa** [comment]
Security should probably be whitelisted on a general stint, though. Most staff heads, really.

**Comment by Midaychi** [comment]
Replace security with mall cops who only have pepperspray, scooters, and plastic twisty ties.

**Comment by WankerSonofJerkin** [comment]
And so the age of biker gangs dawns upon Virgo Station...

**Comment by Poojawa** [comment]
zsmch

**Comment by Somekindofpony** [comment]
Ace, I have security characters. This isn't a cool thing to do without any warning, and to be real, I'm pretty upset. Yes, I've suggested it a few times as a joke, but I didn't think you'd actually do it. We /need/ security, the game's too full of people who need babysitting for it to not have it. What if griefers come and we're not on right away?

**Comment by SpadesNeil** [comment]
We're almost never away, and like I said, they're using it for backseat admining even when we are around. A few shitters that will get banned is not justification to keep an entirely bad department that encourages bad behavior.

So far votes are in my favor.

**Comment by Cameron653** [comment]
Ace, seriously. This is absolutely asinine. Name one server that doesn't have security. 

_**What's that? You have no actual examples? Well, maybe no other server is doing it because**_

# _**security is a goddamn vital part of the station and you won't listen to anyone telling you why this is a bad idea.**_

Not only are you going and pretty much making it so all **security characters people have made are unplayable** if this gets merged, but you're making it so that crimes end up becoming an admin issue, unless we're going to start to allow vigilante justice[.](http://i.imgur.com/1ZChiyg.png?1) Having no security on board is also just straight up immersion breaking. What research station would have no security force to make sure operations are running smoothly?

By even suggesting this, you're making us all look like a bunch of idiots. I have half a mind to close this here and now, but I feel like you'd just reopen it if I did so. By removing security, you're opening up the gates to vigilante justice which will cause even more problems than normal security does. Security may have problems, but completely removing them isn't the solution. So Ace, 
# _please go and think about this before you do anything rash._

**Comment by WankerSonofJerkin** [comment]
Getting preliminary work done on the sprites and code for the player-gangs system. It's definitely a unique alternative to security, and I like where it's going. @SpadesNeil , I'll send you the rough outline, let me know what you think.

**Comment by SpadesNeil** [comment]
Never did I think this would be such a controversial issue, but honestly, why can't we just give it a try as some suggested? Gonna have people quit? Give it up; we don't want such narrow minded players here. Give it a chance I say, and we'll play a few shifts with this. You have to at least give it a chance. Up in the admin chat on Discord, we already discussed this weeks ago, and I don't want to have this stupid argument again.

**Comment by Wickedtemp** [comment]
Haha, April Fools. I know you aren't stupid enough to actually think this is a good course of action.

**Comment by SpadesNeil** [comment]
April Fools? This is getting merged. Right now in fact.

**Comment by Somekindofpony** [comment]
Tempest, have you ever talked to Ace on voice chat?

**Comment by Cameron653** [comment]
Never have I seen such a stupid thing as thinking that _the removal of an entire fucking department wouldn't be controversial._ Gonna kill the server population is what you're going to do with this stupid PR. Let go of this argument, because it's only causing more problems and causing the entire server to be split up. You know where this server is going to go if this gets merged? Down in the trash, that's where

**Comment by Wickedtemp** [comment]
No, but I know they aren't a drooling moron, and the whole "remove sec for a day or two for April Fools" thing has been talked about time and time again, it's...kinda obvious what's happening here.

**Comment by Fevix** [comment]
Honestly, if it's this big of an issue, make Security require whitelisting. 

Also, if this is a serious thing and not an April Fools joke, I'm going to make it a point to break into what's left of Security every shift and take anything I can get my hands on because _without security who's going to stop me?_

**Comment by OrbisAnima** [comment]
you can get banned thou

**Comment by Benemuel** [comment]
Yes but that means literally any time someone does anything illegal, they will either get hit by a lynch mob, or banned.

**Pull request merged**
