### PR TITLE
Adds taur specific voidsuits to areas

### PR DESCRIPTION
**Pull request by Cameron653**
- Adds taur specific voidsuits (Voidsuit helmet included) to areas

All hardsuits spawn with a helmet.
- One Security Taur specific voidsuit to Armory. 
- One Atmos Taur specific voidsuit to Engineering EVA 
- One Engineering Taur specific voidsuit to Engineering EVA
- One Atmos Taur specific voidsuit to EVA
- Two Security Taur specific voidsuit to EVA
- Two Medical Taur specific voidsuits to EVA
- Two mining Taur specific hardsuits to Mining asteroid.

(Syndicate boxes represent where the taur hardsuits are placed)
http://puu.sh/rBhgG/e2086f9e84.png Engineering
http://puu.sh/rBhiy/aff94452a7.png EVA
http://puu.sh/rBhjE/bb90524361.png Armory
http://puu.sh/rDBNN/b2dcac5ae7.jpg Mining

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Note that at least the mining voidsuit does not work for cowtaurs.

**Comment by Cameron653** [comment]
Ah, yeah. The taursuits only work for horses, wolves, and nagas. Let me change the descriptions of them real quick

**Comment by Cameron653** [comment]
Done. Changed the descriptions to say that it only works for horse/wolf/naga halves, and changed it to say that when you try to put it on.

**Comment by Cameron653** [comment]
Travis just threw this up:

!! FAILURE !! [MAP: Active edges (all maps)]: Maps contained 3 active edges at round-start.

I didn't touch any tiles. All I did was place down items as shown above. The

**Comment by SpadesNeil** [comment]
Might be a problem with my gateway map.

**Comment by Cameron653** [comment]
Seems like it. The "Fixes descriptions" commit failed when it loaded zoo.dmm as the gateway map, but the "Adds in taur hardsuits" commit passed when it loaded listening post, and the previous commit passed when it loaded beach.dmm

**Pull request merged**
