### PR TITLE
[MIRROR] Vox pressure immunity is now a toggle.

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/8710
--------------------
- Adds getters to species pressure bounds.
- Adds a toggle and a slowdown to vox pressure resistance.

### CODE REVIEW

**Comment by TankTheBirb** [comment]
Vox do not get voidsuits in this code, this would exclude them from all EVA activities and jobs. It’s a polaris specific balance change. I wouldn’t merge it.

**Comment by Heroman3003** [comment]
I believe its ability for vox to disable their innate immunity to pressure damage that is shared between servers... for some reason?

**Comment by Heroman3003** [comment]
Regardless, this has no relevance to us. Closing

**Comment by Heroman3003** [comment]
I've realized that. However either way, we did not port those broader reworks, and our lore is different enough that most lore changes are not necessarily desired.

**Pull request closed without merging**
