### PR TITLE
Boostage Mk 3

### PR DESCRIPTION
**Pull request by TheFurryFeline**
MOAR BELLEHS

### CODE REVIEW

**Comment by KasparoVy** [comment]
Holy shite 40 bellies

**Comment by TheFurryFeline** [comment]
> Holy shite 40 bellies

I made it 30 about a year ago from 20. Now I'm doing this shit again. lmfao.

**Comment by TheFurryFeline** [comment]
https://github.com/VOREStation/VOREStation/pull/4642 Bruh, I'm two months late. 😹

**Comment by KasparoVy** [comment]
Might as well schedule a yearly increase

**Comment by SpadesNeil** [comment]
WHY???

**Comment by Novacat** [comment]
You are insane.

**Pull request merged**
