### PR TITLE
TGUI Civilian (except no double travis)

### PR DESCRIPTION
**Pull request by ShadowLarkens**
UI's Converted:
 - Aurora Cooking
 - Chaplain Book Selection
 - ColorMate
 - Cryo Storage
 - Holodeck
 - Jukebox
 - Looking Glass
 - Microwave
 - Newscasters
 - Timeclock
 - Vending Machine Improvements

Aurora Cooking
Chaplain Book Selection
ColorMate
Cryo Storage
Holodeck
Jukebox
Looking Glass
Microwave
Newscasters
Timeclock
Vending Machine Improvements

### CODE REVIEW

**Comment by ShadowLarkens** [comment]
travis I will stab you 🔪

**Comment by ShadowLarkens** [comment]
> don't touch newspapers at all
> travis starts throwing an error

🤔

**Comment by Heroman3003** [comment]
Newspapers use same interface as newscasters. Literally. They even update live.

**Comment by ShadowLarkens** [comment]
"Same" UI is certainly not the case, newspapers are nothing more than a way to linearly scroll through feed channels, though I wouldn't be surprised if they do infact update live

**Pull request merged**
