### PR TITLE
[MIRROR] Removes Shellguard Noble cyborg sprites.

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/5514
--------------------
This PR removes my Shellguard Noble cyborg sprites.
I respectfully ask that my shellguard sprite work is removed from the polaris codebase. If any other of my non-Shellguard sprites have been ported, that's not an issue. 

I'm not sure why they were also renammed to cupcake. That's a little odd.

### CODE REVIEW

**Comment by Screemonster** [comment]
The only borgs I can recall actually seeing on the station recently are the dogs, spiders, not-tau-honest floatydrone, and that terrifying multi-armed mediborg.

'cause of blahblahblah opensource GPL viral licencing etc sure we don't _have_ to but I can't think of a reason _not_ to for the sake of being nice

**Comment by SpadesNeil** [comment]
noble sprites

For reference also, these sprites would be removed.

Regardless of whether or not we plan to _keep_ them removed, we _must_ at least remove them once, then re-add them with proper attribution.

**Comment by Arokha** [comment]
They were added without the artist's permission. Even if the codebase is open source, you can't just steal copyrighted materials and include them in some open source project and say it's fine now. They should likely be removed.

**Comment by SpadesNeil** [comment]
:+1:

So I think the issue is settled for the moment, then. Properly attribute and we can still use it.

Personally I really like the sprites and would like to continue using them, so I'll do a quick PR to change the names and add some attribution in the PR while we're at it. Just for the hell of it.

**Comment by SpadesNeil** [comment]
Meh fuck it, I'm half asleep and can't figure out how to fenangle these sprites into our _vr files properly at the moment.

I'll just merge this for the time being so I don't forget about it. I can always add in the custom sprites at a later time.

**Pull request merged**
