### PR TITLE
It's the char setup update. (Wouldn't let me reopen the original PR after some explosive shenanigans)

### PR DESCRIPTION
**Pull request by Verkister**
Fucking hell github go suck a piss.

MAJOR HIGHLIGHTS:
-> A WHOLE BUNCH OF NEW MARKINGS AND CHARACTER ASSETS.
-> DUAL COLORABLE TAILS AND TAURS.
-> INDIVIDUALLY COLORABLE EARS.
-> FIXED CHARACTER SETUP PREVIEWS.
-> A WHOLE BUNCH OF MINOR VISUAL TWEAKS.

tl;dr chronological changelog details below.

-Added a bunch of marking assets from my older citadel ones.(otie, cow, corvid)
-Ported over the colorable otie wagtail.
-Added ears for otie and cow, colorable and plain versions.
-Ported over my old citadel drake taur. (disabled for now)
-Added a fixed _vr version of ponytail 6.
-Fixed the pixel offset issue with antlers.
-Added one pixel to every wolf taursuit to match them with the earlier body tweak that smoothed out the 90 degree tail snap angle.
-Added a few bootleg raccoon marking bits.
-Ported otie taur by request sure why not. (disabled for now)
-Tweaked a new properly centered curltail middle icon.
-Lined up and un-overlapped the setup previews. Also taurs can now fit into the frame and not be cropped in half.
-Unlocked the hidden and forgotten feature for secondary tail/taur colors.
-Currently the only enabled things are the colorable wolf tail and a new dual color wolftaur. The framework for more is ready for use though!
-Liberated ear coloring from the oppression of hair color.
-Disabled drake and otie taurs since they lack all gear compatibility :v
-Made dual-color wagtails possible.
-Added extra color features to curltail(wag), vulptail(wag), stripeytail, tigertail(wag), ringtail, naga, lizardtaur, felinetaur.
-As with the wolftaur earlier, naga, lizard, and felinetaurs have dual-color versions as subtypes to prevent compatibility issues with custom taurs.
-Merged ShadowLarkens' Big snake tail into the sprite file to avoid destructive PR conflicts.
-Added ArgobargSoup's zorren sprite stuffs ready to be coded in.
-Fixed a typo that probably caused the vulp shorttail wagstate be broken.
-Redirected zorren species towards the new icon file.
-Added colourable elf ears.
-Added framework for custom heads using custom eyes without messing the base code.
-Slightly tweaked sergal markings.
-Added new eyes for sergals with little more snout space inbetween.
-Added teshari feathers as markings after failing to fix them for custom species.

### CODE REVIEW

**Comment by Verkister** [comment]
Yeah seems I'm unable to mark the file resolved without exploding everything

**Comment by Cameron653** [comment]
If you use the github desktop client, you can have it show conflicts, merge the tails_vr.dmi file to your fork and sync it and it'll get rid of the conflict.

**Comment by Verkister** [comment]
problem is my file is just way too fucky to be merged into the base one here and I need to somehow mark it "newer" than the base one

**Comment by Verkister** [comment]
lmao finally

**Comment by Verkister** [comment]
Rewriting the lost file, hopefully I remember what it had in it... :v

**Comment by Cameron653** [comment]
This looks good to merge. I see no glaring issues with it.

**Comment by SpadesNeil** [comment]
Not overwriting the DMI files, are we? Because that is where the conflict was.

**Comment by Cameron653** [comment]
As far as I can see, the tail dmi has ketrai's icon included in it.

**Comment by SpadesNeil** [comment]
don't fucking break it :U

**Pull request merged**
