### PR TITLE
Finished hair file conversion (Awen, Citheronia, xeno heads) Ready to merge before more shenanigans happen.

### PR DESCRIPTION
**Pull request by Verkister**
-Merge before the conflict PRs and tell em to safely sync it over theirs, already contains both fluff hairstyles added and converted to multiply format.
-Also adjusts the brightness further a little after doing a proper check agaist white background.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
>Merge after the conflict PRs, already contains both fluff hairstyles added and converted to multiply format.

You realize that can't happen right?

**Comment by Verkister** [comment]
Eh up to you and manual permissions magics. I've seen more or less catastrophic dmi overwriting almost too many times before with no problems apart from the aftermath often falling on my shoulers.

**Comment by SpadesNeil** [comment]
I can't force overwrite conflicts. I mean, I can, but it fucks with things I'd like not fucked with.

**Comment by Verkister** [comment]
Wait this one isn't even marked conflicting. Just go ahead and do the merge and the others can safely sync it without worry of their stuff getting erased heh.

**Pull request merged**
