### PR TITLE
Re-added Shellguard Noble sprites (by Travelling Merchant)

### PR DESCRIPTION
**Pull request by Heroman3003**
Using the weird bypass system I made for adding spiderborg and Handy sprites. Now named approprietly as well.

Sprites were first uploaded to Paradise Station.

https://github.com/VOREStation/VOREStation/pull/4225 - Our mirror
https://github.com/PolarisSS13/Polaris/pull/5514 - Polaris' PR

### CODE REVIEW

**Comment by AaronSherwood117** [comment]
Didn't the creator of the sprites specifically ask for them to be removed

**Comment by Mewchild** [comment]
That is correct. They were removed on basis of polite request by the creator

**Comment by ArgobargSoup** [comment]
@AaronSherwood117 If you check the mirror PR that removed them from our codebase, the creator of the sprites did give permission for us to use them again, if they were properly credited for their creation and if they had the odd naming thing fixed.  (For some reason, they'd originally been listed as "CUPCAKE" on the relevant module lists...)

**Comment by Heroman3003** [comment]
Yes, sprites were asked for removal from Polaris specifically. As long as artist is credited and sprites are named approprietly, we can keep using them

**Comment by SpadesNeil** [comment]
We're allowed to use them, both legally and morally.

- One, Paradise uses them, and that's what open source code is.
- Two, the artist themselves **said** we can keep using it. They were just miffed at Polaris for not properly attributing it, which _is_ required by the license. Also we changed the weird rename that Polaris did, by the artist's request.

Sure I could have just changed it in the existing code but this is a more thorough way of attribution. We're not just re-adding it to be dicks. We're re-adding it because I like the sprites.

**Comment by SpadesNeil** [comment]
That said I'm still going to laugh at people if they try to white-knight on behalf of the artist who literally said "oh you can keep using them, just credit me properly would you?" which is what this PR is for.

**Pull request merged**
