### PR TITLE
TGUI-V4 w/ Camera Console

### PR DESCRIPTION
**Pull request by ShadowLarkens**
Mix of 
https://github.com/ParadiseSS13/Paradise/pull/13310 and
https://github.com/ParadiseSS13/Paradise/pull/13750

Upstream: https://github.com/PolarisSS13/Polaris/pull/7317 (camera console not in that version)

TGUI is a UI system developed by /tg/station to replace NanoUI. It has considerably better documentation, and a full development server that enables live debugging, log output, and live reloading to an external console window. It's generally easier to develop with once you get used to the Inferno.JS syntax that it uses. 

From Paradise:
## What Does This PR Do

This PR implements TGUI-V3. **This is mostly a direct port, but has been tweaked to allow it to co-exist alongside nanoUI with no connection between the two. This means that nanoUI behaves completely independently from TGUI, and thus can be removed fairly easily when needed.** This PR just adds in the framework for TGUI, as well as ~~two interfaces (Disposal units + Crew monitors)~~ (3, See bottom - Shadow) to keep bloat down. If this is merged, I will make more PRs down the road to get all the UIs converted to TGUI.

TGUI-V3 also includes a development server which allows you to create UIs ingame IN REAL TIME. No more recompiling or even reloading the server. Save the file in your IDE and watch your changes instantly appear in the UI ingame.

## Why It's Good For The Game

TGUI is FAST, has more control options, is easier to develop for (explain above), is actually documented unlike nano, and has more features. It also allows new TG ports for objects they have which use this UI.

# Screenshots

UIs Converted so far:
 - Crew Monitor & NTOS Version
 - Security Cameras & NTOS Version
 - Disposal Bins
 - More to come in future PRs

### CODE REVIEW

**Comment by ShadowLarkens** [comment]
Upgraded to [tgui 4.0](https://github.com/tgstation/tgstation/pull/52280)
Fancy window now have a preference option, and they're on by default. 
Fancy window:

**Comment by Novacat** [comment]
A couple of questions.

Is it planned to port the Camera console upstream?

Does this work all right with Modular Computers? Modular computers are heavily tied in to NanoUI functions (including camera console)

**Comment by ShadowLarkens** [comment]
@Novacat Yes and yes.
I already have the camera console ready to go upstream, but Ater asked me to leave the PR alone until they're done reviewing it.

Polaris doesn't have the modular computer changes, but this PR does- it's fully compatible with modular computers, and both the suit sensor monitoring program and the camera program have been converted to TGUI.
It's a little bit of a janky implementation, because I had to make sure that nano modules could coexist with tgui modules and the main interface is still written in nano, but I couldn't find any problems with it in testing.

**Comment by Novacat** [comment]
Well, this is too large and touches too many places I am unfamiliar with for me to effectively review this. Time to test this!

**Pull request merged**
