### PR TITLE
New Rack and Wardrobe

### PR DESCRIPTION
**Pull request by GhostActual**
In the spirit of sprite updates, I'll be yoinking the `underware_wardrobe` sprite from Baystation and the `rack` sprite from Fulpstation. Minor change, but it helps with quality of life.

New Sprites:

### CODE REVIEW

**Comment by Heroman3003** [comment]
These racks just look bad IMO

**Comment by Arokha** [comment]
I've never been able to understand the racks. Can someone explain them to me? Like, I don't understand what they're supposed to be. To me, they look like one of these:

image

Like I should be using it on a desk to store papers. S'why I usually map in shelves instead.

**Comment by Arokha** [comment]
code/game/objects/structures/under_wardrobe.dm:4:error: 'icons/obj/undies_wardrobe.dmi': cannot find file

**Comment by GhostActual** [comment]
> I've never been able to understand the racks. Can someone explain them to me? Like, I don't understand what they're supposed to be. To me, they look like one of these:
> 
> Like I should be using it on a desk to store papers. S'why I usually map in shelves instead.

I do the same thing, but this is for existing map objects. It is infinitely easier to sprite in a replacement than it is to go through and find each instance of a `rack` and replace it with a `shelf`

**Comment by Arokha** [comment]
> These racks just look bad IMO

I think all racks look bad. Replace 'em with shelves! I'd probably approve a PR for that.

**Pull request merged**
