### PR TITLE
Micro & mech tweaks.

### PR DESCRIPTION
**Pull request by lbnesquik**
- Add plastic to the robotics locker
- Restrict micros to micromechs. (Anyone below 50%)

VOREStation/VOREStation/issues/4332

### CODE REVIEW

**Comment by Screemonster** [comment]
Ehhhhhh, when I added the micromechs it was more for "micros can use these, they're cheaper and less obtrusive/costly than regular mechs" than "micros can only ever use these mechs".

Suits such as the ody still don't have micro equivalents.

**Comment by lbnesquik** [comment]
Would it be fine if there was a fuller range of comparable exosuits?

**Comment by Wickedtemp** [comment]
Mechs in general need a rework. I know, its horribly out of scope for this, but... I never use or order Ody mechs anymore. When Medical rarely DOES get one, it collects dust and will really never be used. Nearly everything it provides can be topped by an EMT in a voidsuit or rig.

**Comment by KasparoVy** [comment]
cuz strong spesmen can drag tons of heft with no slowdown

**Comment by lbnesquik** [comment]
There is a mech rework coming actually. Just got to wait for the sync.

**Pull request closed without merging**
