### PR TITLE
Port some /tg/ barsigns

### PR DESCRIPTION
**Pull request by Arokha**
Catgirl maid cafe time.

See icondiffbot.

### CODE REVIEW

**Comment by Very-Soft** [comment]
Moar signs good, I think the cleaner style for some of the replacements tends to look better-ish

I think the syndi-cat one might be messed up on its rotation though
image

**Comment by Arokha** [comment]
> Moar signs good, I think the cleaner style for some of the replacements tends to look better-ish
> 
> I think the syndi-cat one might be messed up on its rotation though
> image

Fixn't

**Comment by Heroman3003** [comment]
I dun really like the adminbuse one... seems like a bit TOO meta of a joke for the server.

Also am I blind or where did the giant stripper fairy go

**Comment by Arokha** [comment]
> I dun really like the adminbuse one... seems like a bit TOO meta of a joke for the server.
> 
> Also am I blind or where did the giant stripper fairy go

You are blind!

**Pull request merged**
