### PR TITLE
Add prefs for Be Morph, Be Maintpred, Be Lost Drone

### PR DESCRIPTION
**Pull request by Arokha**
Allows the 'never for this round' button to work, and for them to be disabled entirely if you don't want to be asked again.

### CODE REVIEW

**Comment by Heroman3003** [comment]
I personally would use singular preference for onstation spawns (morph and maint pred) since two as a whole are very similar in nature of event, but it's good to see those added. Though also mentioning those on wiki would be important, since other than pAI and positronic, none of the other 'antag-looking' preferences are used.

**Comment by Arokha** [comment]
Eh, I think when more variety is added to maint pred or maybe more nuance to morph it'll be different enough to make it worth it. I don't see much harm in having them separate until then. Also update the wiki, then, nerd!

**Comment by TheFurryFeline** [comment]
Corgi Runes and Crystal Sword also give prompts and ignore the "Never again for this round" option being selected.

**Comment by Arokha** [comment]
u fix

**Pull request merged**
