### PR TITLE
makes glasses mass producable

### PR DESCRIPTION
**Pull request by Ketrai**
Makes it so glasses can be mass produces in the autolathe, including metamorphic glasses.
Also added a few more glasses to spawn in the bartender's room, because 10 is quite limiting considering you'd pour cocktails in these glasses 90% of the time.

### CODE REVIEW

**Comment by Ketrai** [comment]
The command "(! grep 'step_[xy]' maps/**/*.dmm)" exited with 1.

Wut does that even meaaaan travis.

**Comment by Novacat** [comment]
...Are glasses even stackable? Is this confirmed to work?

**Comment by Ketrai** [comment]
The code was edited a while ago by polaris to allow unstackable items to be printed with the stack variable used here, i checked a pr that made lightbulbs mass printable for reference.

**Comment by Ketrai** [comment]
tested, works just fine

**Pull request merged**
