### PR TITLE
Fix various syntactic problems

### PR DESCRIPTION
**Pull request by SpaceManiac**
Code cleanup necessary for MapDiffBot to work. #3706

All the deleted `..()` currently do nothing.

Precedent:
https://github.com/ParadiseSS13/Paradise/pull/8742
https://github.com/yogstation13/yogstation/pull/3137
https://github.com/tgstation/tgstation/pull/32284

### CODE REVIEW

**Comment by Arokha** [comment]
Those vars without the space, I'm surprised DM compiles those.

**Comment by SpaceManiac** [comment]
There might still be other issues with the map rendering due to it being slightly tg-specific in certain ways but this is enough to make it mostly work.

**Comment by Arokha** [comment]
We appreciate the PR, either way!

**Comment by Arokha** [comment]
https://github.com/VOREStation/VOREStation/pull/3706/checks

Seems like the same problem still, over there, but maybe a step closer!

**Comment by SpaceManiac** [comment]
You may need to rebase that PR so that these changes are included.

**Comment by Arokha** [comment]
You were right! Though it's a little anomalous. Might not take planes into account? Appears to believe everything is on the same plane but different layers.

**Comment by Leshana** [comment]
Wow, these syntax problems were in there huh? Wacko

**Pull request merged**
