### PR TITLE
Improve inflatables realism

### PR DESCRIPTION
**Pull request by Arokha**
Closing an inflatable on a mob now gibs the mob

### CODE REVIEW

**Comment by Very-Soft** [comment]
10/10 finally some CONSEQUENCES

**Comment by Arokha** [comment]
Full-Life Consequences

**Comment by Natje0** [comment]
I've been waiting for this

**Comment by YuskoTheCoyote** [comment]
Finally some REAL updates!

**Comment by TheFurryFeline** [comment]
>:C No.

**Pull request closed without merging**
