### PR TITLE
Shadekin, Attack Icons, SA Refactor

### PR DESCRIPTION
**Pull request by Arokha**
I tried to be descriptive in the commits:
* Adds Shadekin and their ilk
* Adds attack icons for attacking things (like Bay)
* Allow mobs to glow in any intensity/color/etc for things like antiphoton glows
* Adds a HUD for player-controlled simple_animals, and the possibility to have unique huds for unique simple_animals (like Shadekin)
* Alters the away mission spawners to spawn from a weighted list
* Adds an "overlay" flick system. "overlay" is in quotes.
* Makes it so ghosts can snoop on containers (drag onto ghost)
* Allows simple_animals to have armor (values to be implemented in the near future)
* Don't require hostile=1 on silly things like Runtime and blue-eyes Shadekin
* Cleanup/bugfixes (only making things work that were broken, no feature/balance changes)

image

### CODE REVIEW

**Comment by Cyantime** [comment]
Those attack images are a toggleable preference, *right?* Because they look awful.

**Comment by Very-Soft** [comment]
While I've got no issue with it becoming a toggle, toggling it off would sort of put those who did at a slight disadvantage.

The main appeal of the item animation is to show at a glance who is attacking, and with what. 

This way you can tell the difference in the animation if someone is being bonked with a foam sword, or stabbed with a combat knife, WITHOUT trying to quickly make sense of the (possibly quickly scrolling) red text.

This is something you would be able to realistically discern at a glance, and that's what the animation does.

**Comment by Cyantime** [comment]
You can tell who is attacking who by the small mob movement, and the inhand sprites (which everything should have) are a good enough indicator of with what. I'd rather just have the option to disable it.

**Comment by KonBear** [comment]
[Adds a HUD for player-controlled simple_animals, and the possibility to have unique huds for unique simple_animals (like Shadekin)]

Does this mean we can end up controlling simple animals without admin shenanigans? I.E. through a sleever like we can with monkies ~~or ghost stuff like with drones and mice~~

**Comment by Screemonster** [comment]
Just because the option exists doesn't mean it's going to be used routinely.
This statement is mainly directed at the people who mash ahelp wanting to be spawned in as a xeno or a deathclaw or some other mob every single shift.

You know who you are.

**Comment by Arokha** [comment]
Made that a preference so @Cyantime stops whining like a LITTLE GIRL :[

**Pull request merged**
