### PR TITLE
Fixes #14173, other modular computer file manager improvements

### LINKED ISSUE #14173: [GENERAL] Data Crystals for Modular Computers are write only
#### Brief description of the bug
Upon uploading a file to a data crystal, it is impossible to delete it.

#### What you expected to happen
Press delete on the file in the crystal, delete the file in the crystal.

#### What actually happened
File remains on crystal, if the file is also on the computer, it will delete the one there, if there is no other file, it will do nothing.

#### Steps to reproduce
- Get Modular computer (Tablet, laptop, console)
- Get Data Crystal of any kind. (Basic, advanced, super)
- Put Crystal in computer.
- Move any file from the computer to the crystal, using the File Manager and the Upload button.
- Try to delete the file in the crystal.
- File in the computer gets deleted instead.
- Try again.
- Nothing happens.

#### Code Revision
- [40027ed9185ae642f433ef7eb1497936a55b14a2](http://127.0.0.1:59295/tmp19540/%3Ca%20href=%22https://github.com/VOREStation/VOREStation/commit/40027ed9185ae642f433ef7eb1497936a55b14a2%22%3Ehttps://github.com/VOREStation/VOREStation/commit/40027ed9185ae642f433ef7eb1497936a55b14a2%3C/a%3E)

### PR DESCRIPTION
**Pull request by Cyantime**
The ntos file manager will now properly modify files on a portable drive.
The ntos file manager will no longer allow you to create files with identical names.
Why were files normally accessed only by their filename when every file is already given a unique identifier, for what purpose was this done.

### CODE REVIEW

**Comment by Cyantime** [comment]
I'm not a tgui knower and have no idea what "code style issue" the linter is complaining about. It mentions Prettier but using the --pretty flag mentioned in the readme gives `[webpack-cli] Error: Unknown option '--pretty'`. Running the same with --lint comes up with nothing.

**Comment by ItsSelis** [comment]
> 

Hey! To run the prettify you can either do one of these things:
1) Use VSCode with the recommended extensions (aka prettify) to automatically prettify the file upon saving
2) Run tgui-prettybuild.bat

Note: **Do not do "tgui:build" inside of the console itself** because that will create a development build of the bundle, decreasing the performance and any optimization of network bandwith while also exposing development tools like kitchen sink.

**Comment by Cyantime** [comment]
@ItsSelis  For the future, do you mean that the commands provided in the readme [here](https://github.com/VOREStation/VOREStation/blob/master/tgui/README.md#usage) that say (recommended build option) are not actually recommended and will break things?

**Comment by ItsSelis** [comment]
> @ItsSelis For the future, do you mean that the commands provided in the readme [here](https://github.com/VOREStation/VOREStation/blob/master/tgui/README.md#usage) that say (recommended build option) are not actually recommended and will break things?

The recommended commands in the readme are correct. The tgui:build I was referring to was while using yarn, the full command in your console would have been `yarn tgui:build` but I forgot the yarn in the last comment which was a little mistake on my part while I was a little sleepy (If you check the tgui-build.bat or the tgui file in the bin folder, you might probably find tgui:build being ran with some arguments like --prod or --production or something).

But yeah, running the .bat file or the file just called tgui under linux is totally fine and recommended, building it in production mode.

**Pull request merged**
