### PR TITLE
Reworks Station 1 Atrium into Cafe, with Scree's blessing

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
image

Does not touch Cafe on Station 1. You're welcome to still use it, but this adds a more-relevant cafe/gathering spot to Asteroid 1 - Space levels sorely needed a gathering point.

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Might want to put windows at the north section so people can't climb-oh, wait, the whole thing doesn't look to have a shutter system in it?

**Comment by ArgobargSoup** [comment]
I would say light panels under all the marble tables, to keep things symmetrical.

...also something about "would be cool if barista job had its own slots", but that's out of scope for this PR  \:P

**Comment by ArgobargSoup** [comment]
Oh!  Another suggestion, for fluff reasons... a stool behind the counter, so a barista has somethin' ta sit on during quiet periods.

**Comment by Heroman3003** [comment]
Having some closing shutters similar to actual cafe would be nice, as well as having some windows to block people getting in even with shutters closed by just hopping the tables in the north

**Comment by Rykka-Stormheart** [comment]
> Having some closing shutters similar to actual cafe would be nice, as well as having some windows to block people getting in even with shutters closed by just hopping the tables in the north

Honestly, I don't think it needs shutters. It's fine as-is. That, and there's no wall to put the button on for said shutters.

**Comment by Rykka-Stormheart** [comment]
> I would say light panels under all the marble tables, to keep things symmetrical.
> 
> ...also something about "would be cool if barista job had its own slots", but that's out of scope for this PR :P

Done

**Comment by ArgobargSoup** [comment]
> > Having some closing shutters similar to actual cafe would be nice, as well as having some windows to block people getting in even with shutters closed by just hopping the tables in the north
> 
> Honestly, I don't think it needs shutters. It's fine as-is. That, and there's no wall to put the button on for said shutters.

Can put buttons on the central table!  And again, shutters are needed to stop people from just hopping the tables and accessing the machines.  Like how they stop people from just hopping the bar/kitchen/existing cafe counter.

Not that fun to come into the kitchen/bar/cafe as a chef/bartender/barista only to find that everyone's just self-serving and rendering your job moot.

...that being said, adding shutters would require that the central table, or the stuff on the upper part of the central table, be moved down... people can interact with stuff on the same tile as a shutter.

**Comment by Screemonster** [comment]
Get rid of the southernmost row of wooden flooring, replace with grass/tiles as appropriate. Likewise, tile over those little single-tile-wide strips of grass that are left over on the northern edge.

**Comment by Rykka-Stormheart** [comment]
> Get rid of the southernmost row of wooden flooring, replace with grass/tiles as appropriate. Likewise, tile over those little single-tile-wide strips of grass that are left over on the northern edge.

image

Done! <3

**Comment by ArgobargSoup** [comment]
Looks good to me!

The only last thing I'd do would be also out of scope for this PR, and that's making a donut and glass dispenser ta replace the booze-o-mat.  \:P

**Comment by TheFurryFeline** [comment]
Whoops, looks like #5750 may have well triggered conflicts here. Adding/changing the changed bits, in my experience, tends to help resolve conflicts.

**Comment by TheFurryFeline** [comment]
https://github.com/VOREStation/VOREStation/pull/5750/files#diff-0d2442686b8bafff55564e993a511ae8R11114 area has the changes for what you can adjust to the CE room as needed. Filediff looks to be easy enough to work with. :>

**Comment by TheFurryFeline** [comment]
https://github.com/VOREStation/VOREStation/pull/5839 may well be another thing you need to add to this if/when it gets merged before this one after the first round of conflict fixes. Unless you want me to help with that, as well. :>

**Pull request closed without merging**
