### PR TITLE
Nevrean beak fix

### PR DESCRIPTION
**Pull request by blazerules**
Replacement for nevrean beak from what I was told.

### CODE REVIEW

**Comment by kcin2001** [comment]
A pic of the actual beaks would be nice

**Comment by Screemonster** [comment]
The reason the original sprites weren't done like that in the first place is we didn't have markings at the time to let 'em be two-tone.

**Comment by saysage** [comment]
> A pic of the actual beaks would be nice

image
image
image

> The reason the original sprites weren't done like that in the first place is we didn't have markings at the time to let 'em be two-tone.

Well, thing is. It's not about being two-tone, nevrean beak is that orange thing on picture, everything else is wellll just face.

**Comment by saysage** [comment]
image

I'd say it might be good to make markings for belly and face, as it is on this ref, but I totally suck at this.

**Comment by kcin2001** [comment]
showing on a nevrean would be nice too

**Comment by kcin2001** [comment]
at least on the head

**Comment by saysage** [comment]
Oh crap, this led me to understanding that I did beaks a little too short now. PFFH. Alright, I have to fix it now, give me a moment.

**Comment by saysage** [comment]
image
That's approximate look of male beak...
image
Aaand of female.

**Comment by Arokha** [comment]
I mean, it's good that you added the marking, but it's not going to show up as selectable for anyone unless you actually add the marking datums to go with it.

**Comment by kcin2001** [comment]
Without looking at the dmi i assumed it replaced the existing ones

**Comment by blazerules** [comment]
Oh god, I don't fully know how it works and it turns out it merged the electrostaff into this...

**Comment by blazerules** [comment]
Was told Scree will implement it with a different method and to close this. All good I guess.

**Pull request closed without merging**
