### PR TITLE
Port emitter sprites

### PR DESCRIPTION
**Pull request by Arokha**
From /vg/, though I'm not entirely sure of their ORIGINAL original origins!

It has little wheelies that deploy when you un-anchor it c:

https://user-images.githubusercontent.com/15028025/121567620-cb95f780-c9ec-11eb-9740-196ac6629a6b.mp4

### CODE REVIEW

**Comment by Novacat** [comment]
Rather than poofing in thin air, I wonder if maybe they should be replaced with a broken machine object.

**Comment by dwinters99** [comment]
Extremely personal preference but I must say I strongly dislike this icon.

**Comment by Arokha** [comment]
> Rather than poofing in thin air, I wonder if maybe they should be replaced with a broken machine object.

What would you do with it? Also WYSI

**Comment by Novacat** [comment]
yes I was dead tired when I wrote that and did not realize I was posting in the wrong PR

**Comment by Very-Soft** [comment]
I love how this sprite looks, we might want to adjust the beam sprite for it eventually though

**Pull request merged**
