### PR TITLE
Security non-lethal balance changes

### PR DESCRIPTION
**Pull request by Yoshax**
I feel like the various non-lethal ranged weapons should feel more unique and varied. As such, I present these changes:

- Taser has a lower firing delay, 50% more shots, and 12.5% less induced agony. Still downs in 3 shots.
- Stun Revolver has 25% less shots, and 30~% more induced agony. Still down in 2 shots.
- .45s have been added to the Security Vendor, coming default loaded with flash rounds. These affect everyone on the tile hit, as well as all tiles 1 away. Good vs multiple people, or breaking up a fight. Do a small amount of burn. Downs in 3 shots.

Furthermore to keep things the same and bring things into line, these changes have been made:
- Handheld flashes work the same as the projectile ones, and will down in 3 uses.
- Shotgun Flash Rounds now affect 2 tiles away instead of 1, due to the pistols getting the 1 range.

### CODE REVIEW

**Comment by OrbisAnima** [comment]
Love the adding of the .45 with flash rounds, nice change, also, I love the idea of shotgun flash rounds

**Comment by SpadesNeil** [comment]
Ooo, shotgun flash rounds sound fun.

**Comment by SpadesNeil** [comment]
aaahhhh conflict

**Comment by Arokha** [comment]
I'm assuming by @SpadesNeil 's lack of complaint that he's fine with these changes

**Pull request merged**
