### PR TITLE
Closet vore and Tents

### PR DESCRIPTION
**Pull request by SatinIsle**
Added a new verb to the ability tab when interacting with closets called "Vore Occupants". This allows you to eat another person when both of you are inside of the same closet.

Added tents as a subtype of closets.

### CODE REVIEW

**Comment by Heroman3003** [comment]
Re: hidden vore

I recommend a typecheck on usr. Currently it seems like it might be causing runtimes if a ghost were to attempt doing it.

**Comment by SatinIsle** [comment]
> Re: hidden vore
> 
> I recommend a typecheck on usr. Currently it seems like it might be causing runtimes if a ghost were to attempt doing it.

Done!

**Comment by Heroman3003** [comment]
It has also been tested yes?

**Comment by SatinIsle** [comment]
> It has also been tested yes?

Yep

**Pull request merged**
