### PR TITLE
Replaces emag interaction with pizza voucher

### PR DESCRIPTION
**Pull request by Heroman3003**
Title. Droppod is ridiculous, yes, but also distructive in levels it really shouldn't be, and there is absolutely 0 indication to how dangerous it actually is until after you used it too.

Now with special delivery it just sends a pizza similarly to normal delivery, but that pizza will actually crush whoever it lands on. No damage to surroundings/lost equipment.

### CODE REVIEW

**Comment by Very-Soft** [comment]
I'd prefer that we make it give you an indication of how dangerous it is, with a confirmation dialogue rather than just removing the interaction.

**Comment by Novacat** [comment]
I am going to agree with Soft, I would rather have a warning dialogue instead of outright removing the feature.

**Comment by Heroman3003** [comment]
Replaced the interaction to not be that destructive to surroundings (that is, not damage anything except the mobs on tile it lands on), or the equipment/body of person (gibs instead of deleting)

**Comment by Very-Soft** [comment]
that sounds like a much better compromise

**Comment by SpadesNeil** [comment]
I kinda liked the drop pod but meh I guess there's a valid point.

**Comment by SpadesNeil** [comment]
Wait, can you even get pizza vouchers outside of admin spawning bullshit? I think you can get them from trash loot.

**Comment by Heroman3003** [comment]
You can order them in cargo, get them from trash piles and occasionally roundstart randomized trash can be a voucher too.

**Pull request merged**
