### PR TITLE
A new model set for Cyborgs/Drones! (Adminbus only small horses)

### PR DESCRIPTION
**Pull request by SableTowerofBabel**
Third time writing this. Git really doesn't like me.

Anyways, adds a new spriteset/model line for basically all cyborg modules (except dogborgs, i guess i could map them for that? but i'd have to make belly sprites and others and just ehhhhhhhhhhhhhhhhhhhhhhh) that may be familiar for some.

In the interests of a certain sort of witchcraft i'm making them public use instead of trying to restrain them. Because everyone should be able to provide service with a smile as a silicon.

The few issues there are are already noted in the discord, and if i'm not responsive on here just ping me there.
I'm sure i'll work on them. Hopefully. Some things are just too 'itsafeature' to fix.

### CODE REVIEW

**Comment by Very-Soft** [comment]
https://youtu.be/Q1aRBkRyjRQ?t=13

**Comment by Very-Soft** [comment]
In seriousness though, I don't mind these being present so they can be adminbussed, but I do not want normal players to be playing as MLP ponies, so they should not be selectable normally.

**Comment by SableTowerofBabel** [comment]
> In seriousness though, I don't mind these being present so they can be adminbussed, but I do not want normal players to be playing as MLP ponies, so they should not be selectable normally.

Pft. Fair enough though i'd need some help getting BYOND code to behave and have them available for busing but not normal play because i am incompetent when it comes to code.
There was a prototype sprite that was more horseish but i couldn't get it to look right and dropped the attempt, along with the more xenotype one inspired by an event in FTL. maybe i'll make those work in the future.

i do still kinda want to play as one myself, if only for specific character ideas.
SCA time? SCA time probably.
please ping me on discord i need to figure out how to do that.

**Comment by SableTowerofBabel** [comment]
For some reason i can't convert this to a draft while i bash my head against BYOND so just gonna close it for the moment. Ping/DM me on Discord (Sable#8051) if you've got tips or outright code snippets or just help in general


thank for aware

**Comment by SableTowerofBabel** [comment]
oh cool git is just being a dick as per usual
whatever
i have shit to do

**Comment by SableTowerofBabel** [comment]
Should be bus-only now. Please someone with actual competence with varediting midround make sure the eyeglow can actually be used.

**Comment by AmayaWah** [comment]
I am incredibly biased since I dislike ponies in almost any form, so

I have to say, I agree with the sentiment of it being solely available through admin powers. Idk. Maybe you can personally use it with a SCA. But I really don't wanna see these in game.
fuckingdyinginside

**Comment by SableTowerofBabel** [comment]
> I am incredibly biased since I dislike ponies in almost any form, so
> 
> I have to say, I agree with the sentiment of it being solely available through admin powers. Idk. Maybe you can personally use it with a SCA. But I really don't wanna see these in game.

That is the current state of the PR. I am a bit curious personally as to the dislike of the equines but that can be discussed somewhere other than here.
...if i ever figure out who is who so i can actually ask.

**Comment by Sebbe9123** [comment]
Is this okay with copyrights and stuff? Its undeniably just MLP.

**Comment by SableTowerofBabel** [comment]
> Is this okay with copyrights and stuff? Its undeniably just MLP.

Hasbro hasn't really cared about small projects and horse show, even back in the heyday only really big projects looking to sell themselves got the C&D (see 'Them's Fighting Herds' and its history for the single example where they did go after such and why they did so).
They've got bigger fish to fry than a series of 32x32 sprites on a voreaphile server for an ancient atmospheric simulator's roleplay-based deranged cousin of a game to use in admeme events.

Now, were it any other company i'd probably be sharing your concern and thus closing this PR.


Honestly i'll probably end up closing it for other reasons instead after today. Noticed a really big gripe i have with the sprites as they stand anyways upon closer examination, and will probably just make fresh ones now that i've got better tools to possibly make the other inspiration of an idea come to life.

**Comment by SweetBlueSylveon** [comment]
I do not want this in our code. This is not something I think should be available to just anyone, and I don't see this as acceptable as admin spawn only because then anyone can request it. If you want a character that is mlp based, you will need an SCA to begin with. If you make an SCA for an MLP character, and a fluff app for the sprites to be whitelisted for you alone to use, then I will see this as appropriate.

**Comment by SableTowerofBabel** [comment]
> I do not want this in our code. This is not something I think should be available to just anyone, and I don't see this as acceptable as admin spawn only because then anyone can request it. If you want a character that is mlp based, you will need an SCA to begin with. If you make an SCA for an MLP character, and a fluff app for the sprites to be whitelisted for you alone to use, then I will see this as appropriate.
> I would say the same thing if you wanted to make a borg that looked like a digimon, or a pokemon, or any other cartoon character. Because this dips into needing an application, and a limit to people being able to be them.

Aye, fair enough.

**Comment by Little-119** [comment]
> Hasbro hasn't really cared about small projects and horse show, even back in the heyday only really big projects looking to sell themselves got the C&D

don't you mean... hayday?

**Pull request closed without merging**
