### PR TITLE
Holodeck space turf fix

### LINKED ISSUE #6844: Holodecks Space Borkage
#### Brief description of the bug
Space Simulation produces icon-less tiles.

#### What you expected to happen
Space simulation of old

#### What actually happened
Invisible space tiles.

#### Steps to reproduce
- (Step 1) Go to holodorm
- (Step 2) Select Space Sim
- (Step 3) Blink in bewilderment at nothing there.

#### Code Revision
- 304653579408b5c57ded8a6d49452c502fe395d8 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
image

### PR DESCRIPTION
**Pull request by Arokha**
Fixes #6844

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Aww, I was hoping for the old version because that kind of Overmap could be distracting in a session. Like was discussed with Leshana about, and probably forgot to add into the issue I posted, the plain background of black with so many stars was nice.

**Comment by TheFurryFeline** [comment]
Oh, wait, my issue wasn't worded clearly enough but that's what I want, yeah. Restored version of the old space view in the holodeck with Space Simulation.

**Comment by Leshana** [comment]
@TheFurryFeline This PR actually helps move towards making that possible by restoring the old icons. That will make it fairly easy to choose between them in the future.

**Comment by TheFurryFeline** [comment]
Ooooh, sounds good, then!

**Pull request merged**
