### PR TITLE
Modify fluff gun to 10mm

### PR DESCRIPTION
**Pull request by Arokha**
Instead of mateba megarounds.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
y tho

With just two shots, the only hope of doing any damage that could help you at all is with Mateba

**Comment by Arokha** [comment]
The .357 literally oneshots people, though, is the thing. With those two shots, you could kill two people. Depending on your luck, instantly and untreatably, since it's enough damage to decapitate people.

**Comment by Arokha** [comment]
Have a GIF: http://imgur.com/kguicCu

**Comment by SpadesNeil** [comment]
I thought the Derringer had an accuracy debuff.

Apparently the _fucking jackass_ who added this didn't remember to add that. He--

wait

shit, _I_ added this gun

**Pull request merged**
