### PR TITLE
Text for handheld plushies when poked

### PR DESCRIPTION
**Pull request by Affurit**
Plushies now make sounds when poked. Squeak!

### CODE REVIEW

**Comment by Screemonster** [comment]
Are plushies a polaris thing? If so, need //vorestation edit on each changed line. For this though, rather than commenting every single line with the added var, it'd be easier to make a toys_vr.dm file and add all the extra definitions in there.

**Comment by Affurit** [comment]
God, really...?

**Comment by SpadesNeil** [comment]
Or we can just send this to Polaris!

**Comment by SpadesNeil** [comment]
Is now a duplicate of https://github.com/VOREStation/VOREStation/pull/4301

**Pull request closed without merging**
