### PR TITLE
Adds a new Kitsune language: "Kisun"

### PR DESCRIPTION
**Pull request by Cameron653**
Adds a new Kitsune language called "Kisun" created by Uwawa.
Is partially understood by Tradeband and CANILUNZT.
Unable to be understood by the AI or borgs like some languages.

### CODE REVIEW

**Comment by Uwawa96** [comment]
Thanks a bunch for taking time out of your evening to help me set this up!

**Comment by Heroman3003** [comment]
This is even memeier than Birdsong

**Comment by Cameron653** [comment]
> This is even memeier than Birdsong

I was asked to assist help them make the language & set the PR up for them due to them not having Github Desktop isntalled. This is @Uwawa96 's PR.

**Comment by Cameron653** [comment]
Also because the maps are all broken for some reason:
This compiles and works. Closing and reopening to tell travis to wake the hell up.

**Comment by pontifexminimus2** [comment]
No thanks, that's a total fucking meme.

Also, why would it not be understood by borgs and AI?

**Comment by Very-Soft** [comment]
We had a staff meeting today and this came up, we decided that we do not want this.

**Comment by Uwawa96** [comment]
Eight, thanks for your guy's time regardless of that.

As for why it would not be understood by A.I, simple and boiled down to two key points.
A) The idea was that it was one of those languages which are already only spoken by a rather small group of people, and nobody ever really bothered to upload a translation of such a far-out there and convoluted language into an A.I
B) They would still have a 50% translation rate of it via Cani and Tradeband.

Thou considering that staff decided against it is not like those 2 points really matter.

Once again, thanks to the staff to take a glance at this regardless.

**Pull request closed without merging**
