### PR TITLE
UwU speakv2 With feedback this time

### PR DESCRIPTION
**Pull request by Sebbe9123**
So!
While I was on break there was *some* dislike for the awoospeak, there wasn't a lot of feedback and I can't find anything on discord under the search terms "uwu trait", "uwu autohiss" or "cursed autohiss" so I'm just going by the feedback in the removal PR about it affecting other languages, specifically the Tajaran and Unathi ones. That's been (hopefully) patched.
Since it wasn't abused, at least not reportedly so, hopefully it wont this time either if it is accepted.

Other than that I'm going by what Scree wrote and wasn't responded to, that the removal was a kneejerk removal.

So here's V2.0, feel free to give feedback, hopefully constructive.

### CODE REVIEW

**Comment by TheDavestDave** [comment]
I never seen it used once when it was possible too, lots of people just reeeeeed over discord and the fun police removed it like edible pizzas from cargo

**Comment by Rykka-Stormheart** [comment]
Mega excited for this to come back

**Comment by chaoko99** [comment]
Nobody called it UwU speak. They called it OwO speak. And heavy oppose on this one because I like to pretend this server is at least somewhat serious.

**Comment by chaoko99** [comment]
Clarification of my opposition: Thre's another name for this type of thing. "Baby talk". I don't want anything of the sort on this server. Just because it wasn't abused in the 2 weeks we had it doesn't mean it won't be down the line. It wasn't even in the changelog IIRC.

**Comment by Sebbe9123** [comment]
> Clarification of my opposition: Thre's another name for this type of thing. "Baby talk". I don't want anything of the sort on this server. Just because it wasn't abused in the 2 weeks we had it doesn't mean it won't be down the line. It wasn't even in the changelog IIRC.

We were not doing Changelogs at the time, all our changelogs were Polaris's own.

**Comment by TheDavestDave** [comment]
https://www.youtube.com/watch?v=ld3A3QCpXd4

if we removed the l replaceing w we have the most common speach disorder in English instead of the second most common one

**Comment by Wickedtemp** [comment]
I kinda understand the opposition because its basically "babyspeak" on an 18+ fetish server.

**Comment by SpadesNeil** [comment]
We're not adding this back, I'm sorry.

I only merged it in the first place as as a cruel joke to the people I knew would **hate** it because of how overly worked up they got over dumb shit like `uwu`. Most of those people are gone now. I don't want them back because they are the "no fun allowed" types and trolling them was a decidedly great move because they all quit and went to shit on some other server.

But now that they're gone I don't actually want this back. It's excessively silly.

**Pull request closed without merging**
