### PR TITLE
It's time for hair color revolution!

### PR DESCRIPTION
**Pull request by Verkister**
-I SOMEHOW FIGURED OUT A COMBO BLEND THAT COMBINES THE BEST OF BOTH, ADD AND MULTIPLY AND LOOKING GOOD AT ALL COLORS IN LESS THAN AN HOUR AAAAAAAA!
-IMPOSSIBILITIES MY ARSE I AM GOD HSGHFJSD
-May need some adjustments in case some bases don't behave as well as they should but that's a task for future me after people have found and pointed out the hypothetical fucky hairstyles I'm too stoked to not rush this through right now lmao.
-Inb4 every other base comes porting faster than they jumped at the preview background pr.
kuva
kuva
Yeah it works just like that in-game too and looks great on every hairstyle and color I briefly managed to test.

Also Scree's handy lion demonstration of this stuff: https://imgur.com/a/cjGPC

### CODE REVIEW

**Comment by Cameron653** [comment]
You should port this to Polaris to save us from 1000 years of conflicts.

**Comment by Verkister** [comment]
Alright tossing a version there soon. Gonna need this one here too though for the vr styles and "early access" :v
Kinda wanna make sure it looks good in action too. Anyway gonna be doing the species bases too when I get the chance heh.

**Comment by SpadesNeil** [comment]
Is this good to merge?

**Comment by Verkister** [comment]
Yeah should be fine.

**Pull request merged**
