### PR TITLE
Map Tweaks

### PR DESCRIPTION
**Pull request by VictorZisthus**
Surface 1

Reinforced Xenobio support pillars; They hold part of the station up, they should absolutely ACT tough.

Reinforced the eatern walls of Atmospherics to deter break-ins via the holodeck dorms.

(77,110) Door given restricted access code 48 (Mining)

(76,108) Door given restricted access codes 24 and 48 (Atmos OR Mining)

Surface 2

(97,61) Inner Janitorial door given restricted access code 26 (Janitor)

Added a third bottle of space cleaner to the Jani closet, one for each jani cart now!

(107,120) Added an actual showerhead to the shower room.

Supplied Surface med with some extra supplies to account for the small space compared to Asteroid; Can now accomidate twice the staff it could before, gear-wise, anyway... Added Toolbox, Multitool, GPS, and Radios for EMT's in Storage.

(107,104) Added a new light in maint to help light the way from surface medical to the panic shelter.

Surface 3

(44,98) Added a new hall light

Fixed the flooring under the Reading room doors to match the rest of it

Station 2

Added more starting equipment to the surgery rooms to accomidate two surgeons each and generally look more organized [and actually give OP2 some Nanopaste]

(43,78) Added another Micro Manipulator to the pile in Tech Storage as QOL

Added R-wall to Secure Tech storage.

### CODE REVIEW

**Comment by Heroman3003** [comment]
Why access restriction on mini-atmos-thing near mining? All other places like that are public, this one probably shouldn't be any different.

Also, I'm pretty sure for surgery, the primary intent is to have 1 accomodate two-surgeons and another accomodate synthetic repair. Having 4 nanopastes roundstart sounds crazy.

**Comment by VictorZisthus** [comment]
> 
> 
> Why access restriction on mini-atmos-thing near mining? All other places like that are public, this one probably shouldn't be any different.
> 
> Also, I'm pretty sure for surgery, the primary intent is to have 1 accomodate two-surgeons and another accomodate synthetic repair. Having 4 nanopastes roundstart sounds crazy.

Huh, good point. I'll remove the access restrictiosn there, I forgot that the others were not restricted.

Fair enough, I'll remove the excess nanopastes from the PR as well.

**Comment by TheFurryFeline** [comment]
Was about to comment on the access restriction being added to somewhere near old mining, which I purposefully left as public access to be followed up with conversion to an as yet to be started project of transferring asteroid medical fully to the surface with three levels. Just a note :>

**Comment by VictorZisthus** [comment]
> 
> 
> Was about to comment on the access restriction being added to somewhere near old mining, which I purposefully left as public access to be followed up with conversion to an as yet to be started project of transferring asteroid medical fully to the surface with three levels. Just a note :>

AYYYYY Let me in on this you mlem. I was gonna help redo surface too!

**Comment by TheFurryFeline** [comment]
Ye, sure, go ahead. I was working from https://github.com/VOREStation/VOREStation/issues/6122 before suddenly losing all motivation to do anything with SS13.

**Pull request merged**
