### PR TITLE
Adds a logical consequence to milk overindulgence

### PR DESCRIPTION
**Pull request by drexample**
Alright, alright, I get it, everyone likes realism, but no one likes redundant code - so here's a better dairy beverage related feature.

You know how milk is supposed to make your bones stronger? Like really strong?
What if you drink too much of it? What if the bones become, y'know.
Too strong. That wouldn't be good. Your skeleton will become stronger than you.

### CODE REVIEW

**Comment by Very-Soft** [comment]
Please do not open meme prs

**Comment by drexample** [comment]
this wasn't a meme pr goddamn

**Comment by BigBababooey** [comment]
I feel as if we live in very different realities. Also we already have this joke but at a more reasonable because milk heals brute slowly iirc.

**Comment by Huenererschrecker** [comment]
Not anymore, that was removed some time ago if I remember right.

**Pull request closed without merging**
