### PR TITLE
Adds cursed speak autohiss

### PR DESCRIPTION
**Pull request by Sebbe9123**
FInally you can live out your dreams, hewwo speak is here.

### CODE REVIEW

**Comment by Kegsey** [comment]
I love it, 10/10.

It just works - Todd Howard.

**Comment by CRTXBacon** [comment]
I hate it but I'll scream if this isn't merged

**Comment by KasparoVy** [comment]
cursed_pr

**Comment by SpadesNeil** [comment]
https://www.youtube.com/watch?v=7mBqm8uO4Cg

**Pull request merged**
