### PR TITLE
Move Syringe Gun

### LINKED ISSUE #10274: Surface medical syringe gun missing
**Brief description of the bug**

No syringe gun in surface medical

**What actually happened**

No syringe gun placed in medical

**Steps to reproduce**

Just go look in medical, no syringe gun.

### PR DESCRIPTION
**Pull request by TheFurryFeline**
Title. And yes, I know there's a mapping freeze, but I think this is so minor as to be fine.

🆑 
maptweak - Move the Syringe Gun from the grenade crate onto the table, remove extra box.
/🆑 

Resolves #10274

### CODE REVIEW

**Comment by Heroman3003** [comment]
Considering upper levels are on map freeze and are getting purged completely with next PR for them, maybe just adding new one into surface medical without removing it from upper one would be better?

**Comment by TheFurryFeline** [comment]
As stated in the issue, the Surface Medical and Asteroid Medical both have a syringe gun. But the former was tucked away inside a grenade crate along with an extra box of cartridges. I've only just moved the thing out of the box. As for asteroid's syringe gun, I've left that alone, hence lack of an edit to the dmm for asteroid 2

**Comment by Novacat** [comment]
This will conflict with the mapping freeze unfortunately.

**Comment by TheFurryFeline** [comment]
Alas. Such a minor tweak, though.

**Comment by Arokha** [comment]
If it conflicts, you'll have to redo it after freeze anyway, so no point in leaving it open. Gonna close for now, 'without prejudice' as it were.

**Comment by TheFurryFeline** [comment]
Alrighty, then.

**Comment by TheFurryFeline** [comment]
Can I get this re-opened?

**Pull request closed without merging**
