### PR TITLE
Release

### PR DESCRIPTION
**Pull request by SpadesNeil**
now leave me alooooneeeee :U

### CODE REVIEW

**Comment by Cameron653** [comment]
#2299 please

**Comment by Cameron653** [comment]
https://github.com/PolarisSS13/Polaris/pull/4081
This got merged. I'm rushing a sync to get it in before we go master -> release.
We'll be able to upgrade to 512 with this which should fix the crashing.

**Comment by SpadesNeil** [comment]
Waiting on you, then.

**Comment by Cameron653** [comment]
I rushed the sync
_Jesus Christ_ how did they change so many files in such a short time since last release.

**Pull request merged**
