### PR TITLE
Converts the lighting process controller to a StonedMC subsystem

### PR DESCRIPTION
**Pull request by Leshana**
* No changes to lighting logic at all, it still processes sources, corners, and overlays in that order.
* Also optimized the initial creation of lighting overlays, and made it include CHECK_TICKs
* Removed the statistics gathering, at least for now.

### CODE REVIEW

**Comment by OrbisAnima** [comment]
Now, this will be fun, I look foward to give it a large nar sie test to see how it behaves

**Comment by SpadesNeil** [comment]
I know nothing about how the lighting system works.

@Arokha maybe should review this? Though it's made by Leshana so it's probably fine.

**Comment by AeroWing** [comment]
Did you need someone to shed some light on this stuff for you @SpadesNeil ?

**Comment by SpadesNeil** [comment]
>Did you need someone to shed some light on this stuff for you @SpadesNeil ?

cd5

**Pull request merged**
