### PR TITLE
Minor Post-Update Securiy Overhaul fixes.

### PR DESCRIPTION
**Pull request by Jakksergal**
Adds various missing objects and other general fixes.

### CODE REVIEW

**Comment by Jakksergal** [comment]
Most of these were pointed out by Phi.

**Comment by Mewchild** [comment]
A couple more things to fix:

- [ ] No washing machine in the brig
- [ ] All the beds are steel, and not padded as they were previously. I can see this for solitary, but not the regular cells
- [ ] No linens for the beds.
- [ ] Detective doesn't have access to interrogations
- [ ] Update the NanoUI maps

**Comment by Mewchild** [comment]
This door is public access. A mouse opened it
image

**Comment by KasparoVy** [comment]
It's clearly a hostile agent.

**Comment by Mewchild** [comment]
No button in the lobby desk to open the main/common doors. Was removed.

**Comment by Jakksergal** [comment]
The door to EVA is meant to be all access so those with access to the airlock but not security don't have be escorted five tiles. It is red because it is still a security area, but not a *secure* area. Just like the lobby of security.

**Comment by Jakksergal** [comment]
This is ready to be merged to prevent conflicts down the road.

**Pull request merged**
