### PR TITLE
adds in new slimes and fixes kendrick

### PR DESCRIPTION
**Pull request by kcin2001**

### CODE REVIEW

**Comment by kcin2001** [comment]
oh god i need some help with this

**Comment by Poojawa** [comment]
Make sure your base branch is 100% synced with live.

tools -> mapmerge -> 1prepare_map.bat

Do edits *test edits in game after compiling*

2clean_map.bat -> commit that changed map. Should fix any conflicts.

**Comment by SpadesNeil** [comment]
also CONFLICTS REEEE

**Comment by kcin2001** [comment]
Ill try again later today

**Comment by kcin2001** [comment]
im closing this, someone else more experienced do this please

**Pull request closed without merging**
