### PR TITLE
Adds pizza guy uniform

### PR DESCRIPTION
**Pull request by Heroman3003**
Finally, the most important occupation and the most dangerous one is represented.

Each pizza crate comes with one, and one is in cargo warehouse roundstart.

Sprites and idea made by Andy aka Kligor aka Delicious-Snack-To-Eat-And-Forever-Keep-Tummed-Because-He's-Cute

### CODE REVIEW

**Comment by Novacat** [comment]
Due to the map edit this will have to wait until the big squish happens.

**Comment by Heroman3003** [comment]
Since that z-level is just getting removed in the big squish, I dont think this will actually cause any conflicts?

**Comment by Iroquois-Pliskin** [comment]
Cursed but funny

**Review by Novacat — APPROVED** [review]

**Comment by Heroman3003** [comment]
No more map changes (since those would get overriden anyway)!

@Novacat

**Pull request merged**
