### PR TITLE
Adds handholding

### PR DESCRIPTION
**Pull request by kevinz000**
_With a monstrosity of a chained inline switch._

### CODE REVIEW

**Comment by Arokha** [comment]
'nested ternary operations'

**Comment by Screemonster** [comment]
needs the "vorestation edit" comment if you're not gonna be kicking this up to polaris

**Comment by Cyantime** [comment]
I'm amazed that Polaris doesn't have pronoun procs for his/her/their set up, considering the work they did with gender identities and such.

**Comment by The-clown-known-as-Pepe** [comment]
speedmerge nyaow

**Comment by Arokha** [comment]
***[handholding intensifies]***

**Comment by Leshana** [comment]
@Cyantime In byond you can just use  `\he`  or `\his`  most of the time.  I guess the issue being that it will output  "it" and "its"  instead of "they" or "theirs"  for non-male/female.

**Pull request merged**
