### PR TITLE
Adds toggleable character pref for sharp/fuzzy scaling. (Tested.)

### PR DESCRIPTION
**Pull request by Verkister**
**Tested working.**
-Yeah you should now be able to choose how your character looks without forcing a global mode over everyone.
-Especially benefitical for any character scaled to those atrociously fucked up deformation ranges.
-Kinda based on #1947 Go there for preview examples.
-Because some characters just look better soft and symmetrical instead of something that got run over with one of those landfill variety steamrollers.

### CODE REVIEW

**Comment by Cameron653** [comment]
Everything here looks good codewise, as it just removes gets rid of the pixelscale if someone toggles it on. No idea why your laptop does that.

**Comment by Yoshax** [comment]
Someone should probably pull this and test it locally.

**Comment by Verkister** [comment]
Anyone up for testing? Kinda unable myself as I have no idea how to even compile the code with the PIXEL_SCALE line enabled and the way my main setup somehow forces fuzzy scaling anyway.

**Comment by Verkister** [comment]
Tested faulty. Stay tuned for fix updates.
Seems the compile and forcefuzzy issues were caused by outdated client.

**Comment by Verkister** [comment]
Tested working.

**Pull request merged**
