### PR TITLE
Late August Polaris Sync

### PR DESCRIPTION
**Pull request by Cameron653**
It compiles.
No idea what was in it. Was only a few conflicts that were so minor I fixed them in like 2 seconds.
automatic/carbine was replaced with automatic/bullpup. Commenting it out in trash.dm caused compile errors (for some odd reason.) so I just put its replacement in.

- Teshari stuff added to Polaris, so the teshari stuff on our side was removed to prevent duplicates.

### CODE REVIEW

**Comment by Cameron653** [comment]
I lied. It doesn't' compile. one second.

**Comment by Cameron653** [comment]
Compiles now.

**Comment by SpadesNeil** [comment]
Travis disagrees.

**Comment by Funce** [comment]
I'm all over it

**Comment by Cameron653** [comment]
Now it should work. I though that was added to the same but guess not.

**Comment by Funce** [comment]
Woo teamwork?

**Pull request merged**
