### PR TITLE
Adds a costly trait that turns you into a walking dumpster.

### PR DESCRIPTION
**Pull request by Verkister**
-It costs 2 trait points and lets you eat items.
-I've been trying to make the verb (nonfunctional without the trait) to not show up for those without the trait fruitlessly for way too many hours so fuck it.
-Fuug goodnight it's already 5 am lmao

### CODE REVIEW

**Comment by Dhaeleena** [comment]
I really really really dont like the ability to eat any item, At any time, anywhere, of any size...and add the ability to digest them without drawback if the other PR is merged.

**Comment by Cameron653** [comment]
Personally, I'd like to see this in with a whitelist of sorts of items that you _can_ eat (See: Trash items, ID's, paper) items that have little to no importance while items such as guns will, quite literally, wreck you for eating them, as it is extremely powerful to just hold _any and every_ item you want in there and hide them away/gurgle the evidence of contra away with a button click.

That's just my opinion, though. Making this as requires discussion as it's, from what I can see, immediately controversial in the dev chat.

**Comment by Benemuel** [comment]
This.... Would have the problem yes of a high potential for abuse, or would need significant nerfing to have it not abuse able, most likely upsetting the side that wants to eat objects, and its existence upsetting people like Dhael. Maybe if a large amount of people wanted it but, as far as I can tell it upsets quite a few people, but only appeals to like three. If it was more I would personally support this but, since it is as far as I can tell not that many people I don't support this.

**Comment by icowom** [comment]
This works out on janipup's, becuase its a specific job. And their specific fluff.

I dont like the idea that any PC can take this trait and basically either, delete all the things and be a massive jerk.

Or be a supply truck on legs with just a buncha clicks.

**Comment by LeighKnapenberger** [comment]
Maybe a blacklist of items that it would be too overpowered to eat, or more feasibly, a whitelist of junk that the station's fine without?

**Comment by Benemuel** [comment]
...Would you really want this feature just to eat a bunch of wrappers and the like?

**Comment by LeighKnapenberger** [comment]
Sure, why the hell not.

**Comment by SpadesNeil** [comment]
no

**Comment by LeighKnapenberger** [comment]
Er... do you mind elaborating? Is this something that has no way of being implemented regardless of how much it's restricted?

**Comment by SpadesNeil** [comment]
This is something that has no way of being implemented regardless of how much it's restricted, yes.

**Pull request closed without merging**
