### PR TITLE
Add Bridge Bunny alt-title

### PR DESCRIPTION
**Pull request by Arokha**
Per Joan and staff meeting

### CODE REVIEW

**Comment by Heroman3003** [comment]
So, memey alt-titles are fine when its staff that wants them then?

**Comment by Novacat** [comment]
I do think Bridge Bunny as an official title is... kind of odd? "Bridge Officer" sounds like a much better official title while still being very bridge bunny-esque.

**Comment by Arokha** [comment]
> So, memey alt-titles are fine when its staff that wants them then?

> I do think Bridge Bunny as an official title is... kind of odd? "Bridge Officer" sounds like a much better official title while still being very bridge bunny-esque.

You will need to take that up with @JoanRisu

**Comment by JoanRisu** [comment]
We can add Bridge Officer too, though I would have to brief the staff on how to handle the implied authority of the name. It should probably also go under a separate PR. Bridge Bunny follows the particular trope of "Feminine Operations Officers who practically live on the bridge and ensures smooth operation of the ship/station."

Since we're on the topic of meme titles and this was part of a previous alt-title PR: #10034 uses the whitelisting system, implying the use of a fluff title that is _unique_ to the person that applied for the whitelist and not openly available to others as an official title. Whitelist also implies "staff wants/okay with them." I commented in the PR that I was generally fine with a whitelist given that whitelists by the very process of application weeds out whatever we don't want, including whatever titles are marked as inappropriate. 

Unfortunately, the uniqueness of holding a special, recognized title that you had to sign up and be approved for was not an appealing prospect to have to navigate, so it was turned down in favor of, "Let the HoP do unique titles and we'll just add titles that is more general and can be openly used." 

I have additional thoughts on titles but I want to keep this comment on-topic.

**Comment by Very-Soft** [comment]
I think bridge bunny is a little silly, but it's fine imo.

**Comment by lm40** [comment]
i don't really like it but apparently it's already been decided so yolo

**Comment by User-U-U** [comment]
I really am not a big fan of memey stuff personally, there has been a lot of it ingame and this seems like it will only add to it.

**Comment by Novacat** [comment]
Based on github comments I have a feeling that there might have been some miscommunication. That should probably be cleared up before this gets merged.

**Comment by Wickedtemp** [comment]
So can we add Chief Mlemical Officer

**Comment by JoanRisu** [comment]
Not unless it's an openly available title. Otherwise, personalized titles go through HOP.

**Comment by Wickedtemp** [comment]
> Not unless it's an openly available title. Otherwise, personalized titles go through HOP.

Yes, that's what I'm referring to. As an openly available title.

**Comment by JoanRisu** [comment]
Rejected by vote on 06/28/2021

**Pull request closed without merging**
