### PR TITLE
August 2019 Release Update

### PR DESCRIPTION
**Pull request by SpadesNeil**
Because I probably won't finish porting over files to my new computer until then.

We'll do the server update whenever the hell I am able.

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Looks like Travis needs to get restarted for that latest.

**Comment by SpadesNeil** [comment]
Waiting on https://github.com/VOREStation/VOREStation/pull/5534 to be corrected.

**Comment by SpadesNeil** [comment]
Go to hell map diff renders.

**Comment by SpadesNeil** [comment]
@JoanRisu is the only one with box access right now so -tags-

**Pull request merged**
