### PR TITLE
Ammo Boxes

### PR DESCRIPTION
**Pull request by GhostActual**
Added in new Ammo Boxes that replace the old ammo box system.
There are other, minor sprite changes and some code changes/organization in a vain attempt to combat the spaghetti.
Not much to this one, but it was a pain due to the map changes.

### CODE REVIEW

**Comment by Very-Soft** [comment]
did you actually test and make sure all this works as you expect it to?

**Comment by GhostActual** [comment]
Yes, this is originally from the Armory Revamp #11636, it uses the same code as the Ammo Boxes that were merged with Donk Co. Toys #12253

I'll run it through a test to be 100% sure, but as it stands it should work as intended

**Comment by Very-Soft** [comment]
Lemme know when you've tested it. With big PRs like this it's difficult for me to see by skimming through if something's not as it should be, so, would like to ensure that it's been well tested and all that.

**Comment by GhostActual** [comment]
It works

**Pull request merged**
