### PR TITLE
Death to Yosh's unholy pet.

### PR DESCRIPTION
**Pull request by SpadesNeil**
Deletes the mimic from the maintinence tunnels near medbay that was accidentally (I hope) added https://github.com/PolarisSS13/Polaris/pull/2227

### CODE REVIEW

**Comment by SilverTalismen** [comment]
I would say keep it in so it can ambush people, but then people will get salty when it manages to kill them xD

**Comment by SpadesNeil** [comment]
I should at least replace it with a vore version lol

**Comment by SilverTalismen** [comment]
You should! that would be fun

**Comment by Cameron653** [comment]
:+1:

**Comment by CSchlippy** [comment]
:+1::+1::+1::+1::+1::+1::+1::+1:

Vore it up!

**Pull request merged**
