### PR TITLE
Zoo.dmm added, Vault updated, various bugfixes

### PR DESCRIPTION
**Pull request by SpadesNeil**

### CODE REVIEW

**Comment by SpadesNeil** [comment]
> The command "(! grep 'step_[xy]' maps/**/*.dmm)" exited with 1.
> 0.01s$ (! find nano/templates/ -type f -exec md5sum {} + | sort | uniq -D -w 32 | grep nano)

Travis, can you fucking not?

**Comment by SpadesNeil** [comment]
Travis, what the fuck are you talking about? That variable DOESN'T EXIST!

**Comment by SpadesNeil** [comment]
.....

**Comment by Cameron653** [comment]
In maps/RandomZLevels/backup/zoo.dmm line 492, remove "{step_y = 6}"

**Comment by SpadesNeil** [comment]
This is what is on line 492.

`"jx" = (/obj/structure/window/reinforced{dir = 1},/obj/structure/window/reinforced{dir = 8},/obj/structure/window/reinforced{dir = 4},/obj/structure/grille,/obj/machinery/door/blast/shutters{density = 0; dir = 4; icon_state = "shutter0"; id = "syndieshutters_workshop"; name = "Blast Shutters"; opacity = 0},/turf/simulated/shuttle/plating,/area/awaymission/zoo/syndieship)`

**Comment by SpadesNeil** [comment]
Step_X doesn't appear anywhere in the code at all.

**Comment by Cameron653** [comment]
It's on line 492 in "RandomZLevels/backup/zoo.dmm" not "RandomZLevels/zoo.dmm"
Backup/zoo.dmm is the problem. Line 492 is 
``
"jx" = (/obj/structure/table/marble,/obj/machinery/microwave{step_y = 6},/turf/simulated/floor/tiled/white,/area/space)
``

When it should be
``
"jx" = (/obj/structure/table/marble,/obj/machinery/microwave,/turf/simulated/floor/tiled/white,/area/space)
``

**Comment by SpadesNeil** [comment]
Oh, what the hell. How did that get in there?

**Pull request merged**
