### PR TITLE
Fixes #9061 (partially) POI Stacking

### LINKED ISSUE #9061: POI stacking
#### Brief description of the bug
POIs don't respect each other's no-no square

#### What you expected to happen
For POIs to _not_ overlap

#### What actually happened
POIs overlap

#### Steps to reproduce
- Exist
- POIs overlap

#### Anything else you may wish to add:
It seems to be most frequently the killer rabbit POI and the ore cliff POI. Pictures below.
poi1
poi2
poi3
poi4
poi5

### PR DESCRIPTION
**Pull request by aryll-linton**
Adds submap areas to killer_rabbit and orecliff POIs so they don't overlap other POIs on init
Unfortunately cannot generalize this so if other POIs are found stacking please inform me thanks

### CODE REVIEW

**Review by Novacat — DISMISSED** [review]
Cliff1 is a Polaris POI, you will likely have to override it with Cliff1_vr.dmm, most of the Plains POIs have overrides like this.

**Comment by aryll-linton** [comment]
I also see deadly_rabbit_vr.dmm doesn't have an #include- is that intentional, or do I have to make a mountains_vr.dm or other?
In the mean time, this will probably suffice.

**Comment by KillianKirilenko** [comment]
Quad travis at it again I see.

Although if the cliffs are a Polaris POI, shouldn't the fix be upstreamed?

As for where the .dmm is included, I recommend using notepad++ or something with a 'find in files' feature. You can probably find where it's included that way, if it's not included in the .dme.

**Comment by aryll-linton** [comment]
I miiiight have to send the cliffs upstream, but it feels like this is a problem that they would've fixed by now if it wasn't intentional. As for the #include, it's that mountains.dm has a whole list of of things that say something along the lines "make sure to #include all the POIs here or your milk will spoil" and deadly_rabbit_vr.dm doesn't have one

**Comment by dwinters99** [comment]
I haven't done any work on this is too long, closing so I can come back to it later.

**Pull request closed without merging**
