### PR TITLE
Labeller, paper bins from Eris

### PR DESCRIPTION
**Pull request by Arokha**
See icon diff bot.

### CODE REVIEW

**Comment by Very-Soft** [comment]
The labler looks neat

I don't really like the new paper bin though. It looks mega flat without it's angley bit. Prefer the old one to the new one personally.

**Comment by Arokha** [comment]
> The labler looks neat
> 
> I don't really like the new paper bin though. It looks mega flat without it's angley bit. Prefer the old one to the new one personally.

I am indifferent in the 3/4ths to iso war, except to say that I think most servers doing real good sprites are doing the 3/4ths thing, so that's what most of them end up being, but personally the paper bin sprite has ALWAYS bothered me, because instead of comparing it to the perspective of nearby machines it's compared to the desk it's on and it feels EH.

**Comment by Verkister** [comment]
kuva
suggestion to make them more recognizable

**Comment by Arokha** [comment]
> kuva
> suggestion to make them more recognizable

You are totally correct. That does look better. I went ahead and implemented that.

**Comment by Heroman3003** [comment]
The new bins still look way too flat, imo. Better, but waaay too flat.

**Comment by Very-Soft** [comment]
I think is better with the change to the sprite

**Pull request merged**
