### PR TITLE
Algae generator changes

### PR DESCRIPTION
**Pull request by Cyantime**
Algae generators start turned off, and can be enabled/disabled from their interface.
Algae generators use power from the equipment channel, instead of environment.
Algae generators can be upgraded with better stock_parts from RnD, to improve their oxygen production rate, maximum material storage, and reduce power consumption.
One more sheet of algae is added to the crate next to the generators, for a total of four.
More algae sheets can be made from the biogenerator in Hydroponics or Xenobotany, and can be ordered from cargo.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Separate changes and fixes please.

Fixes are one PR.
Changes to features otherwise working as intended in another PR.

**Comment by Cyantime** [comment]
PR split up, the fixes are over at #2534

**Comment by SpadesNeil** [comment]
@Cameron6531 ya fekkin nerd get in here idk wat do and I am too sleepy to comprehend code and this is 2 weeks old

**Comment by Cameron653** [comment]
Uhhh. As far as I can see, this makes it so algae is able to made via the biogen and some other stuff which is listed in the description.

The PR looks good enough. I don't seee any crazy issues w/ it, and it seems simple enough.

**Pull request merged**
