### PR TITLE
Awens Fluff stuff attempt 2

### PR DESCRIPTION
**Pull request by Natje0**
This time there should be no conflict or trouble... I HOPE.

Used fresh codes to add the things, and upon the Gazer Lilianfluff fix, changed the code to have what was done there.
Basically meant to do everything #2257 does, and has #2262 's code fixes and stuff.

### CODE REVIEW

**Comment by Cameron653** [comment]
You still need to add the sprites to custom_clothes_vr.dmi, as they are missing from there.

**Comment by Natje0** [comment]
Dammit

**Comment by Natje0** [comment]
_Now_ it ought to have everything.

**Comment by Natje0** [comment]
Okay... I've now downloaded the code and tested it, and now everything works. Finally. Guess this is what happens when you put too much into one PR when you've got next to no experience o3o
Oh well, valuable experience.

**Comment by Cameron653** [comment]
Any objections before I merge? If not, going to merge this some time tomorrow.

**Pull request merged**
