### PR TITLE
Multiple xenochimera tweaks

### PR DESCRIPTION
**Pull request by Screemonster**
Some tweaks to the xenochimera sprite so they're not just tajarans.

Boosted the halloss xenochimera take from being in the cold, it only takes seconds of exposure to a really cold environment to knock them flat-out now.

Makes feralness more likely, and have less advance warning.

Tweaks to the narration for feralmessages and regeneration.

### CODE REVIEW

**Comment by Screemonster** [comment]
image
Oh, here's the sprite for reference. Both without jumpsuit and with the natty captain's uniform.

**Comment by SpadesNeil** [comment]
>Multiple xenochimera tweaks **#666**

**Comment by Screemonster** [comment]
https://www.youtube.com/watch?v=GGBHfXPqbgI :v

**Comment by Screemonster** [comment]
Scree uses the same set of pronouns as anyone else. It's verb conjugations that are always forced into third-person singular. :v

**Pull request merged**
