### PR TITLE
[MIRROR] Adds overmap sensors to the Southern Cross

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/7436
--------------------
And then, all at once, there was a great clamoring at ater's door to finish working on this stuff because everyone has ideas that ater needs to code, why doesn't he have more time to code, why has he started blocking everyone and responding only to people on teamspeak, ater don't goooooooo!

But really, this is very pretty.
Layout:

Tests:
[Turning it on (video)](https://puu.sh/Gfgta/37c8ea2301.mp4)
[Overmap events enabled (video)](https://puu.sh/GfgT8/ff143f4ef2.mp4)

And as I note in the changelog, I/we may in the future move this stuff to other locations, in separate departments or at least a dedicated room. I was eyeing the construction area across from the gym, but then realized this required such a small footprint and couldn't really justify using the whole space.

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Travis failing hard on this. Where even are all these errors coming from and MC crashing?

**Comment by TheFurryFeline** [comment]
And now there are conflicts for this thing. Oof.

**Comment by Arokha** [comment]
Bounce for modern CI to run.

**Comment by TheFurryFeline** [comment]
Doesn't seem like the bounce is working, oof. Hard reset or something? Like manual prs of all related files that have been made since the original

**Pull request closed without merging**
