### PR TITLE
adds cool and good new soft drink recipe

### PR DESCRIPTION
**Pull request by Screemonster**
Allows service staff to mix up a surprisingly refreshing new treat for their patrons by combining the zesty fizz of space cola with the cool refreshing taste of mint!

### CODE REVIEW

**Comment by KillianKirilenko** [comment]
Now we just need rolls of mentos in candy vendors. 👏

**Comment by Screemonster** [comment]
I'd have had to sprite those but yes

**Comment by Screemonster** [comment]
yes that makes more sense

I also put a comment in there since the rando reactions could do with being separated from the macro/micro chems

**Comment by Screemonster** [comment]
I have no idea how submitting a new commit didn't clear the requested changes thing git is a mystery

**Pull request merged**
