### PR TITLE
Fixes issue preventing cyborgs from being clicked

### LINKED ISSUE #1842: Cyborgs can't be clicked on
#### Brief description of the issue
Cybor gs can't be clicked on

#### What you expected to happen
Click on them with an ID to unlock, or click with a crowbar to open them up

#### What actually happened
Nothing. No message or anything

#### Steps to reproduce
- Click a cyborg

#### Code Revision
- 14d5421d1abb0625ca36ebefc0ddc6625f3e589c 
 
#### Anything else you may wish to add:
https://github.com/VOREStation/VOREStation/blob/06ba6f32aa46da0113ff1d68ead2307f34bed10b/code/modules/mob/living/silicon/robot/dogborg/dog_sleeper_vr.dm#L517-L525
The code I suspect is causing this bug. 

It prevents the below block of code from working properly, preventing cyborgs from being able to be clicked.
https://github.com/VOREStation/VOREStation/blob/bb53323e2e80da3c3f7b9aef198fd85cf31f5691/code/modules/mob/living/silicon/robot/robot.dm#L436-L625

### PR DESCRIPTION
**Pull request by killer653**
- Resolves #1842

Only way I could see fixing this while keeping in the dogborg trash compactor feeding code in.

### CODE REVIEW

**Comment by Cameron653** [comment]
>vorestation.dmb - 0 errors, 0 warnings (7/8/17 8:29 pm)
>All checks have failed

Travis I will delete you

**Comment by Cameron653** [comment]
"The command "(num=`grep -E '\\(red|blue|green|black|b|i[^mc])' **/*.dm | wc -l`; echo "$num escapes (expecting ${MACRO_COUNT} or less)"; [ $num -le ${MACRO_COUNT} ])" exited with 1.

0.01s$ source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup"

This is what is failing the PR. I have 0 idea what the hell it means or what it does, but there is no issues with this PR.

**Comment by Cameron653** [comment]
Found the issue, apparently the old code uses /red and whatnot which fails travis. Fixing.

**Comment by SpadesNeil** [comment]
see Travis knows what he is doing

I still hate him but he knows

**Comment by Cameron653** [comment]
I'm launching a crusade against /red /blue and /green after this.

**Pull request merged**
