### PR TITLE
New bottle and junk food sprites

### PR DESCRIPTION
**Pull request by stobarico**
Replaces sprites with new ones by Partheo (Some of them were made by myself since VOREStation has some unique bottles and food) ((Forgot to mention the flamethrower)) ((( And the new ingredients )))
c0f4350d57434471c4e6007c9e92ac31
0a2a50e7e6daad9e6e7d52e8f535f6ed
8ce2bbf45fb8403c185294182f43a41d
c4a8cfbc15f01a15378533173b878dae
b718e97989d3985023321b064a6ffbf4
58be9838b6f09b44cfde6d60229e6ce3

### CODE REVIEW

**Comment by Vorrarkul** [comment]
So I understand that my reasoning is entirely selfish, but I am against the new candy bar sprite because one of my characters has a fluff item coat that's meant to resemble the candy bar wrappers, and this new sprite has a completely different color scheme.

**Comment by Little-119** [comment]
Solution: Add multiple candy bar brands

**Comment by stobarico** [comment]
10e0fbd852f1fb98e404a7e937c8259b
63493fbf5b3805055495c48f1b6ce619
d18d3074a5b260f8d185424459010e5d
1f4c9b0702197d8825a01fd5ccc661f0
8068650fe35ef4c7ecdb697b46df44ff

Also, we decided that my red re-sprite was worse than the current brown and green sprite

**Comment by Arokha** [comment]
Some of these are cool and all, but you can't edit stock Polaris upstream .dmi files. See contributing.md for details.

**Comment by stobarico** [comment]
Alright, i will close this then

**Comment by KasparoVy** [comment]
Might've been able to put them in a file like `food_vr.dmi`, made a VOREStation edit at the lines where the food objects have their icon defines and gotten away w/i

**Pull request closed without merging**
