### PR TITLE
Remove Pabw

### PR DESCRIPTION
**Pull request by lbnesquik**

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
I do believe that was intentionally put there like that.

**Comment by Novacat** [comment]
So uhh... what is the reason for this PR?

**Comment by lbnesquik** [comment]
I don't like it, that's it

> 
> 
> So uhh... what is the reason for this PR?

I don't like it, that's it

**Comment by Heroman3003** [comment]
Bad PR.

**Comment by lm40** [comment]
i dont like it either  but evidently people do so i expect this is unlikely to change

**Comment by TheFurryFeline** [comment]
Opposed to this. It may look weird but it's a cute way to spell it and that's kinda what 'kins are all about. Their cuteness.

**Comment by lbnesquik** [comment]
Purely subjective whether you like it or not. The pr is just here

**Comment by ShadowLarkens** [comment]
I like pawb :c

**Comment by TheFurryFeline** [comment]
Why-Why_Would_You_Remove_Pawb
Shitty attempt but this would be those who like pawb. :3

**Comment by Iroquois-Pliskin** [comment]
Ah yes, a 2 line change that corrects what is basically a stupid typo requires staff discussion.

Shadekins are not cute, they are cringe, Dutch.

**Comment by Curt5** [comment]
I firmly agree that shadekin are not cute.
Additionally, this does not prevent players playing shadekin from writing 'pawb,' if they really really really want to. It just removes some unique code to standardize interaction messages whenever shadekin do stuff with their hands. A shadekin can still insist they have pawbs rather than hands- there just won't be coded echos that reflect that terminology. As there shouldn't be.

**Comment by Heroman3003** [comment]
> standartize

Except theres nothing standartized about mob interaction messages in the first place, and intent of them IS to have them be unique and mob-specific.

Honestly, this reminds me of "mlem is dumb" discourse in discord way too much.

**Comment by Screemonster** [comment]
pawb is not a typo

**Comment by DemicusMaximus** [comment]
If you're going to be pedantic about the use of the word 'pawb' in the code, then write an actual description next time so I don't have to scroll down into the comments just to understand what the hell it is you're requesting be changed/removed.

**Comment by Very-Soft** [comment]
Pawb is only on simplemob 'kin anyway, which we hardlyy use anymore. I don't really understand why people getting upsetti about it now. It's a dumb cute word leave it alone. :v

**Comment by Novacat** [comment]
After a brief discussion, it was decided that this will be left as is. Even if, at the end of the day, it is entirely irrelevant, there is the concern that merging this may encourage similar PRs that would have a more substantial impact.

**Pull request closed without merging**
