### PR TITLE
Fat Taurs Galore

### PR DESCRIPTION
**Pull request by TheFurryFeline**
Ports the sprites from https://github.com/CHOMPstation/CHOMPstation/pull/734 Fatties, rejoice! You, too, Kenzie. :P
- Fat Wolf taur sprite

- Fat Feline taur sprite

- - Sprite animation for feline taur

### CODE REVIEW

**Comment by Poojawa** [comment]
Bonus to this if you make it a toggle for taurs to acquire a fat sprite on devouring something that triggers the bulge on inspection. 

Make some turbofat for these chonks. :3

**Comment by TheFurryFeline** [comment]
This is just a port. I'm not that advanced with code yet. :v

On Nov 23, 2019 22:58, "Poojawa" <notifications@github.com> wrote:

Bonus to this if you make it a toggle for taurs to acquire a fat sprite on
devouring something that triggers the bulge on inspection.

Make some turbofat for these chonks. :3

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/VOREStation/VOREStation/pull/6221?email_source=notifications&email_token=AJGMTY2CYYYW7PUVQB54R23QVH3XPA5CNFSM4JQSW4HKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFADF4Q#issuecomment-557855474>,
or unsubscribe

**Comment by Poojawa** [comment]
No worries. I'll figure something out for this then.

**Comment by TheFurryFeline** [comment]
:+1:

On Nov 23, 2019 23:02, "Poojawa" <notifications@github.com> wrote:

No worries. I'll figure something out for this then.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/VOREStation/VOREStation/pull/6221?email_source=notifications&email_token=AJGMTYZS2LGMR3K7JQZD2ITQVH4ERA5CNFSM4JQSW4HKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFADG7Q#issuecomment-557855614>,
or unsubscribe

**Comment by SpadesNeil** [comment]
There apparently is a misconception that I disallowed belly sprites from being a thing a long time ago.

This is false. I would love having belly sprites. The only problem is getting them to behave properly with suits, as they would be little more than an overlay and most suits would be incompatible unless people wanted to sprite _every suit_ to work with them, which is insanity, and we're not doing that.

All we _really_ have to do is prevent people from wearing certain suits when their belly is too large. Notably, outer suits like armored vests or rigs or other stuff.

**Comment by Poojawa** [comment]
I've done said insanity before, so, yah

but I figure it'd just be easier to have the belly addon just not show up at all if suited, something something squeezed and compressed to fit in.

**Comment by ArgobargSoup** [comment]
...I second Pooj's idea of having bellies just hidden if heavy suits are put on.  Would probably be easier to do.

~~Also because heavy tums getting squeezed and compressed down are hot~~

**Pull request merged**
