### PR TITLE
Adds a ton of potential fluff alt-titles

### PR DESCRIPTION
**Pull request by Heroman3003**
Most of these will probably require staff and general discussion on whether they should make it, but hey, I thought to throw in as many things as I could think of. Just to add more variety into all the various job titles.

List of new alt titles (by the job, does not include existing ones, will be updated as feedback, discussion and decisions are made):

Visitor - Guest, Traveler, ~~Drifter~~
Intern - Research Intern
Bartender - Barkeeper, Mixologist, Barmaid
Chef - Sous-chef, Kitchen Worker
Botanist - Hydroponicist (removed by Polaris in past, returning), Cultivator, Farmer, Florist
Janitor - Garbage Collector
Librarian - Reporter, Archivist, Academic, Philosopher
Chaplain - Missionary, Preacher, Guru
Entertainer - Actor, Singer, Dancer, Magician, Comedian, Tragedian
Mime - Poseur
Clown - Fool
Quartermaster - Logistics Manager
Cargo Technician - Supply Courier, Cargo Loader, Disposals Sorter, Cargo Handler
Shaft Miner - Deep Space Miner, Prospector (removed by Polaris in past, returning)
Chief Engineer - Head Engineer, ~~Engineering Foreman~~, Foreman, Maintenance Manager
Station Engineer - Construction Engineer
Atmospheric Technician - Atmospherics Maintainer, Disposals Technician
Chief Medical Officer - Chief Physician, ~~Medbay Manager~~, Medical Director, Healthcare Manager
Medical Doctor - Physician, ~~Therapist~~, Medical Practitioner, Orderly
Chemist - Pharmacologist
Psychiatrist - Psychotherapist, Psychoanalyst
Paramedic - ~~First Responder~~, Medical Responder
Research Director - Research Manager, Head Scientist, Head of Development
Scientist - Lab Assistant, Xenopaleontologist, Gas Physicist, Circuit Programmer
Roboticist - Assembly Technician
Xenobiologist - Xenozoologist, Xenoanthropologist
Xenobotanist - Xenoflorist
Head of Security - Security Manager
Warden - Brig Sentry, Armory Superintendent
Detective - Investigator, Security Inspector
Security Officer - Patrol Officer, Security Guard, Security Deputy
Pathfinder - Expedition Lead, Exploration Manager
Pilot - Navigator, Co-Pilot
Explorer - ~~Offsite Investigator~~, Surveyor, Offsite Scout
Field Medic - ~~Expedition Doctor~~, Expedition Medic
Command Secretary - Command Liaison (removed by Polaris in past, returning), Bridge Secretary (removed by Polaris in past, returning), Command Assistant, Command Intern
Head of Personnel - Staff Manager, Facility Steward
Site Manager - ~~Executive Officer~~, Chief Supervisor, Facility Director
Internal Affairs Agent - Internal Affairs Liaison, ~~Internal Affairs Informant~~, Internal Affairs Investigator, Internal Affairs Delegate
Talon Pilot - Talon Helmsman
Talon Doctor - Talon Medic
Talon Engineer - Talon Technician
Talon Guard - Talon Security
Talon Captain - Talon Commander

Changes that aren't adding new alt titles:

Renamed Deputy Director alt-tile of HoP to Deputy Manager (because of recent CD rename)
Moved off-duty explorers to offduty_vr from exploration_vr
Removed unmarked vorestation edit in science.dm
Removed the (now) redundant alt-title definitions for base titles

Adjusted descriptions of Performer and Musician alt-titles for Entertainer
Removed Interpretative Dancer alt-title for Mime (replaced with Poseur, Dancer moved to be Entertainer alt-title)

Removed Lab Assistant alt-title from intern, is a scientist alt-title now. Research Intern is new science-edition Intern alt-title.
Fixed outdated Technical Assistant being referenced in description blurb for Apprentice Engineer

### CODE REVIEW

**Comment by lm40** [comment]
fluff  good

i don't really like 'drifter' because it sounds like a space hobo which is probably the intent but also not someone it would make any sense to allow on station

i would rather see something like 'medical director' than 'medbay manager' which just sounds kinda weird to me

the site manager alt titles also sound a little strange

otherwise 👍

**Comment by Heroman3003** [comment]
> i don't really like 'drifter' because it sounds like a space hobo which is probably the intent but also not someone it would make any sense to allow on station

Drifter is _kinda_ hobo-ish but I meant it in slightly different sense of word. Basically traveler that just... Never stops traveling, not necesarily someone broke and poor.

> i would rather see something like 'medical director' than 'medbay manager' which just sounds kinda weird to me

Medical Director is a good title idea and I can add that. Just that I mostly wanted each head/head-esque position to have an alt-title with "manager" in it for some reason and that was the best I could come up with I guess.

> the site manager alt titles also sound a little strange

Mostly followed the logic of "hmm yes those words seem to be made out of authority"

**Comment by cadyn** [comment]
First of all: Yes, yes, yes. Beautiful. Always felt like there should be more alt titles.

Second of all: Feedback.

Xenoanthropologist is probably better under scientist in my opinion, since xenobiology rarely deals with sentient species if at all. Xenoanthropology would likely be closer to xenoarcheology if anything.

Therapist - Probably just get rid of this, this is the psychiatrist or psychologist's job.

First responder - I don't like the vagueness of this, since irl first responders include firemen and police officers as well as paramedics, this could be extended to ss13 where first responders could include security and engineering.

Offsite investigator - This sounds really misleading. Maybe something more along the lines of Offsite researcher, since the idea is to collect data on foreign technologies and species?

**Comment by Rykka-Stormheart** [comment]
> First of all: Yes, yes, yes. Beautiful. Always felt like there should be more alt titles.
> 
> Second of all: Feedback.
> 
> Xenoanthropologist is probably better under scientist in my opinion, since xenobiology rarely deals with sentient species if at all. Xenoanthropology would likely be closer to xenoarcheology if anything.
> 
> Therapist - Probably just get rid of this, this is the psychiatrist or psychologist's job.
> 
> First responder - I don't like the vagueness of this, since irl first responders include firemen and police officers as well as paramedics, this could be extended to ss13 where first responders could include security and engineering.
> 
> Offsite investigator - This sounds really misleading. Maybe something more along the lines of Offsite researcher, since the idea is to collect data on foreign technologies and species?

Xenoanthropologist 100% fits under Xenobiologist. Just because they currently only deal with slimes does not mean that ICly they're not trained to, y'know, do xenobiology things.

Offsite Researcher sounds better than investigator, yeah :p

**Comment by Heroman3003** [comment]
> Xenoanthropologist is probably better under scientist in my opinion, since xenobiology rarely deals with sentient species if at all. Xenoanthropology would likely be closer to xenoarcheology if anything.

Main reason for it being under Xenobiologist was to have a more 'fluff' alt-title that wasn't so clearly directed to work with slimes and could be used as excuse to start more fun IC interactions with others.

> Therapist - Probably just get rid of this, this is the psychiatrist or psychologist's job.

Correct me if I'm wrong, but isn't just 'therapist' a general doctor practioneer? The type of doctor that either directs you to more specialized doctors or goes "its just cold"?

> First responder - I don't like the vagueness of this, since irl first responders include firemen and police officers as well as paramedics, this could be extended to ss13 where first responders could include security and engineering.

I suppose that's fair, but in context of SS13 I do think first association would be medical regardless.

> Offsite investigator - This sounds really misleading. Maybe something more along the lines of Offsite researcher, since the idea is to collect data on foreign technologies and species?

> Offsite Researcher sounds better than investigator, yeah :p

I was considering offsite researcher, but investigator felt more neutral, especially since Research and Exploration have officially been split off. I will look into more options for explorer.

**Comment by KillianKirilenko** [comment]
Other suggestions/feedback;
Pilot - Add Navigator?
Warden - I'd change Armory Superintendent to just Armorer
Chef - Add [Sous-chef](https://en.wikipedia.org/wiki/Sous-chef), perhaps?

> Correct me if I'm wrong, but isn't just 'therapist' a general doctor practioneer? The type of doctor that either directs you to more specialized doctors or goes "its just cold"?

Therapist is typically shorthand for "psychotherapist" in most of the western world. What you describe would simply be called a GP or General Practitioner.

**Comment by Heroman3003** [comment]
> Warden - I'd change Armory Superintendent to just Armorer

Armorer is associated to me as "someone who makes armor" rather than someone in charge of the armory

> Therapist is typically shorthand for "psychotherapist" in most of the western world. What you describe would simply be called a GP or General Practitioner.

Good to know. Where I am the 'general doctor' is just called Therapist. And the psychotherapist is called, well, psychotherapist. But that does give me an idea for a replacement.

**Comment by lm40** [comment]
maybe 'health services manager' or something then although that also sounds kinda weird

**Comment by KillianKirilenko** [comment]
> Armorer is associated to me as "someone who makes armor" rather than someone in charge of the armory

Which is technically correct, but out of date; now it usually refers to someone - typically a military specialist* - who manufactures and maintains weapons, especially firearms. Which is what the armory's full of, after all.

*Admittedly this may be a very good reason to *not* use Armorer as a title, given they're corpsec. I've seen my fair share of dumb edgy "ex-military" sec officers. 🤔

**Comment by KasparoVy** [comment]
Deep Space Miner is fucking top notch.

**Comment by Heroman3003** [comment]
Update 1, early feedback adjustments, additions as well as some of own ideas that got forgotten first time through:

Chef - Added Sous-chef
Botanist - Added Cultivator
Janitor - Added Garbage Collector
Librarian - Added Reporter and Archivist
IAA - Replaced IA Informant with IA Delegate
Entertainer - Added Actor, Singer, Dancer and Comedian. Adjusted description of musician and performer.
Pilo - Added Navigator
Explorer - Added Surveyor, Replaced Offsite Investigator with Offsite Scout
CMO - Added Medical Director, Replaced Medbay Manager with Healthcare Manager
Medical Doctor - Replaced Therapist with Medical Practitioner
Detective - Added Security Inspector
Security Officer - Added Security Deputy
Mime - Replaced Interpretive Dancer with Poseur

**Comment by Neopatra** [comment]
I like this! We should add barmaid for Bartender as well.

**Comment by Heroman3003** [comment]
> I like this! We should add barmaid for Bartender as well.

That's what barkeeper is kinda supposed to be. A more 'genderless' version of Barmaid/Barman.

**Comment by MrSign** [comment]
Love the alt-titles, gives a bit more variety and allows for specializations in certain fields associated with that job.

One issue I have is with the visitor's title of 'Drifter'. To have that on an ID. An OFFICIAL ID is just... weird. If a visitor came and just said; "Yeah, just put my title in as 'Drifter'." They'd just put in visitor.

Apart from that... I see no other issues. Good work!

**Comment by Haery70** [comment]
Honestly, I don't think that Traveler and Drifter would work well as Visitor alt-titles. They're giving me Greytider vibes. Warden doesn't really feel like it needs alt-titles, especially Brig Sentry since it feels like it works as a borg role or a maintenance drone variant. The rest, however, seems to be OK for me at least in this present time.

**Comment by Meghan-Rossi** [comment]
Barkeeper is good, but I think it would be good to have barmaid too, like how we have both janitor and maid.

**Comment by KasparoVy** [comment]
Cheers @Heroman3003 IK this is just fluff titles but it goes a long way lol, much appreciated

**Comment by Heroman3003** [comment]
Update 2, with some more feedback-based adjustments:

Visitor - Removed Drifter
Bartender - Added Barmaid
Cargo Technician - Added Cargo Handler
Field Medic - Renamed Expedition Doctor into Expedition Medic
Paramedic - Renamed First Responder into Medical Responder

**Comment by Very-Soft** [comment]
Executive Officer tends to be most commonly like, second in command under a captain or whatnot, so should probably be a HoP title, not a CD title, imo.

Librarian could have 'Scholar' maybe? It's similar to the theme of some of their other titles.

'Assembly Technician' is perhaps a little vague imo. I might assume that such a title would be an engineering role just by hearing it. I don't think it's a bad title, just something to consider, might make it sound more robot-ey somehow?

'Patrol Officer, Security Deputy' sound a little more 'police'-ey than I'd personally prefer maybe? It's probably fine but something to consider.

These are the woof ponderings. I like that there's lots more titles though! C:

**Comment by Heroman3003** [comment]
> Executive Officer tends to be most commonly like, second in command under a captain or whatnot, so should probably be a HoP title, not a CD title, imo.

I'll admit straight up, I am unfamiliar with how corporate ladders work. I thought that Executive Officer as SM alt-title would be akin to "Someone who was put in charge of station by people above (central/higher executives)", so would kinda highlight that they themselves are not truly in charge. I also considered Executive Director instead, but that feels way too high up corporate ladder. Again, just feelings these words give off and 0 corporate knowledge here.

> 'Assembly Technician' is perhaps a little vague imo. I might assume that such a title would be an engineering role just by hearing it. I don't think it's a bad title, just something to consider, might make it sound more robot-ey somehow?

I kinda tried to avoid excess wordiness among lines of "Emergency Medical Technician", and I do not quite see how the Assembly Technician could be redone without that wordiness. Also, when mechanics of game are considered at play, assembly would rarely be actually associated with engineering so I doubt it'd be too much of an issue.

> 'Patrol Officer, Security Deputy' sound a little more 'police'-ey than I'd personally prefer maybe? It's probably fine but something to consider.

That's intentional, partially. Its hard to add variety to just 'security' without leaning into military-esque or police-esque terms. I tried using ones that'd be most neutral though. ~~Also lowkey considered Sheriff for HoS alt-title at one moment but obviously it has every way to go wrong imaginable~~

> Librarian could have 'Scholar' maybe? It's similar to the theme of some of their other titles.

Hmm... Scholar leans a bit too much into "someone who actively learns" and carries sciency vibes. Could something like "Academic" work in its place instead, in your mind? Carries similar meaning while free of the sciency association. And on note of even more obscure librarian alt-titles, I was thinking of throwing in Philosopher as well...

**Comment by cadyn** [comment]
> Hmm... Scholar leans a bit too much into "someone who actively learns" and carries sciency vibes. Could something like "Academic" work in its place instead, in your mind? Carries similar meaning while free of the sciency association. And on note of even more obscure librarian alt-titles, I was thinking of throwing in Philosopher as well...

Scholar can be anyone who studies any field really, according to google's definition, it's more commonly used to refer to someone who studies the humanities, and personally I agree with that definition. Also, please add philosopher! I actually have a character who would make use of that title (even if I rarely play them).

**Comment by Heroman3003** [comment]
Feedback update 3:

Site Manager - Replaced Executive Officer with Facility Director
HoP - Added Facility Steward
Librarian - Added Academic and Philosopher
CE - Replaced Engineering Foreman with Foreman
RD - Added Head of Development

**Comment by cadyn** [comment]
Also just a fun little idea: Always liked the idea of using a navy-like command structure, so maybe as an alt title for Site manager, Captain, and for the HoP, Executive Officer. I'm not the most familiar with navy command structures, but I think the HoP and CD actually fall pretty close if not directly into these roles anyways.

**Comment by JoanRisu** [comment]
I will caution against adding more police-y name because we're in the process of changing Sec SoP to be less police-like in general and I wouldn't want you spending too much time on coming up with names that will end up being on a future chopping block due to policy changes.

**Comment by Heroman3003** [comment]
Well, I don't have any more ideas currently for sec anyway, and the ones that are currently on the list are about as far as I myself am willing to go anyway.

**Comment by Heroman3003** [comment]
Update 4, mostly extra suggestions:

Botanist - Added Florist
Entertainer - Added Tragedian
Clown - Added Fool

**Comment by Heroman3003** [comment]
Update 5, mostly on request of Nepox.

Intern - Renamed Lab Assistant into Research Intern
Scientist - Added Lab Assistant

**Comment by Heroman3003** [comment]
Update 6

Medical Doctor - Added Orderly

**Comment by cadyn** [comment]
Merge this already >:v

**Comment by Heroman3003** [comment]
> Merge this already >:v

Still awaiting Staff Discussion during next staff meeting afaik.

**Comment by chaoko99** [comment]
I feel like these are way, way too specific for the playerbase and counts that we have.

**Comment by Heroman3003** [comment]
O W O

**Comment by cadyn** [comment]
two months later

**Comment by KasparoVy** [comment]
Yey

**Pull request merged**
