### PR TITLE
Arachnoborg sprite set.

### PR DESCRIPTION
**Pull request by Heroman3003**
One for every non-hound module (including combat) with service and medical subtypes having to share.

https://image.prntscr.com/image/QGPiyuIHRMKB-0mnV-3SUw.png
https://image.prntscr.com/image/iZee6hoaS82Jl4ZjB79LXw.png

### CODE REVIEW

**Comment by SingoDingo** [comment]
_Arachnophobia rapidly setting in._

**Comment by Screemonster** [comment]
Arachnophobia _really_ sets in when the security arachnoborg "cuffs" you.

**Comment by Heroman3003** [comment]
Do not merge yet, Combat module's roll sprites still seem a bit broken, gonna look into that.

**Comment by Heroman3003** [comment]
Okay, combat module looks fine now.

**Comment by Arokha** [comment]
Travis misbehaving.

**Pull request merged**
