### PR TITLE
Redo excursion shuttle cockpit

### PR DESCRIPTION
**Pull request by Arokha**
So that the engines console can fit. Also why recliners? So silly.

image

### CODE REVIEW

**Comment by Novacat** [comment]
Make sure the cockpit is access locked to pilot.

**Comment by TheFurryFeline** [comment]
Also, nitpick but I'd rather the pipes not go under the walls :V I think you can safely re-path it to go under the doors without it cross anything else?

**Comment by Arokha** [comment]
> Also, nitpick but I'd rather the pipes not go under the walls :V I think you can safely re-path it to go under the doors without it cross anything else?

Which pipes are you referring to?
If you mean the fuel pipes: No, because then it would share a path with the grey pipe, with which it would connect. I also didn't add that, it was like that before and has been like that since this shuttle design was added. Scrubbers, supply, and *one normal colored pipe* can share a turf. You can't have both yellow and grey on the same turf or they will connect. Unfortunately we don't have /vg/s super pipe conduit things where you can have like 8 things on a turf.

If you mean the scrubbers/supply pipes in reference to them going under a window, that's under a window.

**Comment by TheFurryFeline** [comment]
> > Also, nitpick but I'd rather the pipes not go under the walls :V I think you can safely re-path it to go under the doors without it cross anything else?
> 
> Which pipes are you referring to?
> If you mean the fuel pipes: No, because then it would share a path with the grey pipe, with which it would connect. I also didn't add that, it was like that before and has been like that since this shuttle design was added. Scrubbers, supply, and _one normal colored pipe_ can share a turf. You can't have both yellow and grey on the same turf or they will connect. Unfortunately we don't have /vg/s super pipe conduit things where you can have like 8 things on a turf.
> 
> If you mean the scrubbers/supply pipes in reference to them going under a window, that's under a window.

Was the first one, yeah. Shame, though.

**Pull request merged**
