### PR TITLE
Adds in Xenomorph-Hybrid species.

### PR DESCRIPTION
**Pull request by killer653**
Notes:
A few .DMIs were dropped in discord to use from a codebase that uses AGPL and the person who dropped them was wondering if they could be used in game. They got the sprites to work for our codebase and went ahead and dropped them. Since I like xenomorphs, I went ahead and coded it in and gave it everything needed to work in game. They mostly have sprite/asthetical features, and very minor mechanical advantages/disadvantages.

Features/Code Notes:
- Can see 2x better in the dark than humans can (Although, it's still extremely hard to see, even with this) (Mechanical feature)
- Get hungry 2x faster than humans (Mechanical feature)
- Has neon green blood color, simulating their acidic blood (Doesn't do anything mechanically.)
- Has deformed icon sprites, so when they take genetic damage to a limb it will look different.
- Uses the Unathi spacesuit sprites, since there aren't any xenomorph spacesuit sprites made.
- Has a small blurb explaining what the hybrids are, and why they aren't super aggressive.
 
Photos:
Male: http://puu.sh/pUMGy/63a6ed300e.png
Female: http://puu.sh/pUNix/dd68f7b070.png
Colored (example): http://puu.sh/pUMHh/959ddaf462.png

### CODE REVIEW

**Comment by SpadesNeil** [comment]
I am not really okay with adding this, considering Xenomorphs are generally regarded as an antag-only race. If we add this race, and I don't want to, but if we do it must be whitelisted.

**Comment by Cameron653** [comment]
They're not actual xenomorphs, and more of a hybrid since there are already xenomorph hybrids running about the station. Their custom blurb basically talks about how their aggressive nature has mostly been removed due to gene modification and a few other things. The gene modding could be taken one of two ways, with xenomorph genes being added to a humanoid being suggested in the blurb.

**Comment by SpadesNeil** [comment]
I know they are hybrids. My statement still stands.

**Comment by Cameron653** [comment]
Eh, I just don't see them being abused/being used to act like an antag without reasoning, as the blurb states they shouldn't be aggressive. I could add the whitelist flag to them if you want, but it just doesn't seem entirely necessary.

**Comment by SpadesNeil** [comment]
I think it's necessary. We had xeno-demis before, and whitelisted them because they got abused. Vox are whitelisted because they are also an antag species. Same logic here.

**Comment by Cameron653** [comment]
Alright, I'll go ahead and add the whitelisted flag to them real quick.

**Comment by killer653** [comment]
Alright, they're whitelisted now.

**Comment by SpadesNeil** [comment]
:+1:

**Comment by Cameron653** [comment]
Is there anything else requsted for the race or anything like that? If not, this is ready for merge.

**Comment by SpadesNeil** [comment]
Hey, I just realized, we don't have anything on the lore page about this! Please fix!

https://wiki.vore-station.net/Backstory

**Comment by Cameron653** [comment]
Going to write up some quick lore for them.

**Comment by Cameron653** [comment]
Wrote up some quick lore, submitted it to the wiki.

**Pull request merged**
