### PR TITLE
Adds a slime trail taur half.

### PR DESCRIPTION
**Pull request by killer653**
Adds in a slime trail taur half.

Sprited by: Viveret

Photo: http://puu.sh/pxA2r/e937fa6bff.png

### CODE REVIEW

**Comment by SpadesNeil** [comment]
I mean this kinda just looks like a blob.

**Comment by Cameron653** [comment]
I agree with it looking like a blob, but they originally had it named "Slime trail" so I went ahead and named it that in the game.

**Comment by SpadesNeil** [comment]
I'm really not a fan of this. It doesn't seem to have any effort put into it, and I've never heard of a blob-taur. I only see this ever being used by the person who made it, and griefers who want to play a walking turd.

**Comment by Cameron653** [comment]
I put the PR with it up because someone gave me the sprites and requested I have it added in. I'll tell viveret to give his opinion on here as to why it should be added.

**Comment by viv-eret** [comment]
I could improve it this weekend, make it less blobby.

Probably gonna make it less thick and improve the colors, yadayadayada.

**Comment by SpadesNeil** [comment]
Something slug-looking might be nice.

**Comment by viv-eret** [comment]
Think a tree's roots

Thin for most of it but it's thin and spread out at the bottom

**Comment by viv-eret** [comment]
new sprites: http://imgur.com/a/zTdEU

sent the .dmi to cadence

**Comment by Cameron653** [comment]
New sprites: http://puu.sh/pwGIl/3583a4445c.png

**Comment by Cameron653** [comment]
New sprites: http://puu.sh/pwKaE/fd6b6b748b.png

**Comment by SpadesNeil** [comment]
Still looks like a blob to me but now a blob that looks like a cube. I don't understand what the goal here is.

**Comment by Cameron653** [comment]
I believe that Viveret is still fixing the sprite up and making it look nicer?  Not 100% sure, as I'm just updating the github as he sends me the .dmi's

**Comment by viv-eret** [comment]
I'm trying to do a slug-type thing?

**Comment by Cameron653** [comment]
New sprites: http://puu.sh/pxA2r/e937fa6bff.png

**Comment by viv-eret** [comment]
Ace?

**Comment by SpadesNeil** [comment]
I'm still not liking how this looks. It's too sharply angled. Doesn't feel slug-like at all. Just a badly sprited foot or boot or blob. I don't think slime taurs make a whole lot of sense anyway--even in the context of our station.

**Comment by viv-eret** [comment]
Close this for now, then.

**Pull request closed without merging**
