### PR TITLE
Armory Revamp 2022

### PR DESCRIPTION
**Pull request by GhostActual**
What it says on the tin. Revamps weapons - specifically ranged weapons. New sprites have been made for just about every gun that is inside `gun.dmi` as well as the addition of some new ones and new mechanics that might see their way into gameplay in the future. I would list some sprites I made for this PR but there are quite literally too many to post.

The PR isn't truly done, but I need to find a stopping point or I am going to lose my mind.

### CODE REVIEW

**Comment by GhostActual** [comment]
I rushed it and didn't check for minor details, need to go through it tomorrow

**Comment by SigholtStarsong** [comment]
Any chance we could see all the sprites for the stuff you're adding?

**Comment by GhostActual** [comment]
> 

I'm not kidding when I say this, there are at the bare minimum a hundred new/modified sprites in this so to show them all is difficult

**Comment by GhostActual** [comment]
This one might be dead, I dunno anymore

**Comment by GhostActual** [comment]
Maybe not so dead

**Comment by GhostActual** [comment]
Splitting the PR in the hopes of revival

**Pull request closed without merging**
