### PR TITLE
Makes putting down plating not place airless plating

### LINKED ISSUE #2460: putting platting on latice causes pressure damage
#### Brief description of the issue
putting plateing down in the aitruim make take pressue damage

#### What you expected to happen
to have air in the room when I put floor down.

#### What actually happened
that

#### Steps to reproduce
- (Step 1) put lattice down
- (Step 2)put plateing down
#### Code Revision
 a5844f786ef2a09948e6718a7d418b05d95f9324 
#### Anything else you may wish to add:
putting lattice down may make you be in the middle of floor two, with unsported lattice just floating there

### PR DESCRIPTION
**Pull request by Cameron653**
Fixes #2460
https://github.com/VOREStation/VOREStation/issues/2460

### CODE REVIEW

**Comment by SilencedMP5A5** [comment]
finally, now samba will never again baffle medical by coming in with a burst lung without having left the station.

**Comment by SpadesNeil** [comment]
Uh, keep in mind, this will make oxygen appear when you try placing tiles. I don't think this is a good change.

I think this should be coded in a more elaborate manner wherein the air contents of the original tile are copied.

**Comment by Arokha** [comment]
Agree with what @SpadesNeil said, take a look at shuttle code in unsorted.dm, namely like lines 815 and down.

**Comment by Cameron653** [comment]
Hmm, will look into this and see about bringing it over to Polaris.

**Pull request closed without merging**
