### PR TITLE
Makes ghosts able to play as some mobs sometimes

### PR DESCRIPTION
**Pull request by Very-Soft**
Like, when chicks grow up, they can play as the chicken
they can also play as mobs that are released from cargo crates

### CODE REVIEW

**Comment by Arokha** [comment]
Chaos reigns

**Comment by Ketrai** [comment]
Yesss. Will these stay as open options to possess or do you have to be a ghost at the time?

**Comment by Heroman3003** [comment]
At this point, having a 'proper' ghost pod panel would be great, imo. If only to keep track of it all.

**Comment by Very-Soft** [comment]
> Yesss. Will these stay as open options to possess or do you have to be a ghost at the time?

They will stay open until someone claims it or the mob dies, and will be accessible from the ghost pod verb

**Comment by Very-Soft** [comment]
> At this point, having a 'proper' ghost pod panel would be great, imo. If only to keep track of it all.

That may be good! Though, I think the way it is will probably be pretty fine even if things get a bit crowded in there. 

I think it will still be rare for it to get crowded though, since these are some sort of specific and not super common interactions, all of which are player initiated and can never happen spontaniously.

A clearer way to look at things though might be good at some point though.

**Comment by Ketrai** [comment]
> At this point, having a 'proper' ghost pod panel would be great, imo. If only to keep track of it all.

I unno how that could happen. You could just like, hit the uh, the uh thingie. The bird crate button. Of course! That would add juuuust a couple mobs to the list. Nodnod.

**Pull request merged**
