### PR TITLE
Updates expeditionary paths due to Polaris change

### PR DESCRIPTION
**Pull request by Cyantime**

### CODE REVIEW

**Comment by Burrito-Justice** [comment]
Bless your soul

**Comment by Arokha** [comment]
Wait, how does changing all these paths fix the icons

**Comment by Cyantime** [comment]
`/obj/item/clothing/under/utility/expeditionary/whatever` only exists in solgov_vr.dm, which was used to override some Polaris names and descriptions. The actual clothes were changed to `utility/sifguard/whatever`, so the expeditionary versions just went back to using the basic `/utility` sprites without the colored markings.

**Comment by Arokha** [comment]
OH. They're overrides. Gotcha.

**Pull request merged**
