### PR TITLE
Replace/add laptop sprites

### PR DESCRIPTION
**Pull request by Arokha**
image

1. Normal laptop
2. Rugged laptop
3. Elite laptop
4. Hybrid laptop

Ported from CEV-Eris

### CODE REVIEW

**Comment by Heroman3003** [comment]
Ew.

**Comment by Arokha** [comment]
The old ones for comparison:
image

**Comment by Heroman3003** [comment]
I like idea of more difference between various types, but really don't like any of the new sprites, to clarify.

**Comment by Rykka-Stormheart** [comment]
I love these. They look fucking STELLAR.

Way fucking cooler than the shitty, old laptops. 11/10.

**Comment by Ketrai** [comment]
These look better. Just wondering if there's side views too?

**Comment by Arokha** [comment]
> Just wondering if there's side views too?

Nawp, not even the old ones have side sprites sadly. Would be neat to have.

**Comment by KasparoVy** [comment]
Straight up I'm a massive fan of the new sprite implementations, Eris design is the bomb.

**Comment by Novacat** [comment]
I am actually leaning towards switching elite and hybrid. Mostly because number 3 looks very different while 1, 2, and 4 generally seem to share the same shape and such.

**Comment by Arokha** [comment]
> I am actually leaning towards switching elite and hybrid

Oh, meanwhile I kinda already made some other hybrid things based on the yellow/blue color pallets used in #4 >.>;;

**Comment by Novacat** [comment]
Just the tablets, to my knowlege, if its a huge deal can probably swap the #3 and #4 on those as well for consistency's sake. I just think that the different shape + wierd writing on the top lends more to an 'alien' look.

**Comment by Arokha** [comment]
I mostly meant the entire blue alien ship thing I made, plus all the sprites for the walls, consoles, tables, floors, shields, etc.

**Pull request merged**
