### PR TITLE
Fixes omni filters

### PR DESCRIPTION
**Pull request by Cameron653**
Until we do another sync.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
// VORESTATION EDIT

**Comment by Cameron653** [comment]
It's already fixed exactly the same way as Polaris. This'll make it so it (hopefully) doesn't cause a conflict.

**Comment by SpadesNeil** [comment]
Pretty sure it won't work that way but whatevs. :U

**Comment by Cameron653** [comment]
Well I hope it works! Else I'll have to go and fix a conflict and that's annoying >->

**Pull request merged**
