### PR TITLE
Boost Belly Limit

### PR DESCRIPTION
**Pull request by TheFurryFeline**
There will now be a maximum of 30 bellies for those crazy enough to spend the time and those too lazy to use text documents for that. >W>

### CODE REVIEW

**Comment by Wickedtemp** [comment]
Would support. Currently at like 18.

**Comment by TheFurryFeline** [comment]
Aye, Tempest. My currently most-used char's been maxed out for a while. Would love to add more bellies. >W>

**Comment by SpadesNeil** [comment]
okay but why tho

**Comment by TheFurryFeline** [comment]
Like I said in the comment, it'll allow those who want to spend all the time in making a slew of bellies. This is a low effect PR that'll just allow people to add more bellies.

**Pull request merged**
