### PR TITLE
TGUI Engineering: Squashed Edition (Commits Below)

### PR DESCRIPTION
**Pull request by ShadowLarkens**
See this album for screenshots of every UI https://imgur.com/a/NVGgKXI

This overhauls all of engineering to use TGUI. I mean *all* of engineering. Every single UI I could think of, and every single UI suggested by the engineering channel.

Full list below.
# Atmospherics
 - Algae Generator
 - Atmospherics Control
 - area_atmos/tag (Heavy Scrubber Control)
 - Gas Cooling System
 - Gas Heating System
 - general_air_control (Distro & Waste)
 - general_air_control/fuel_injection (Riot Control Console)
 - general_air_control/large_tank_control (Atmos Intake Control)
 - general_air_control/supermatter_core (Engine Cooling Control)
 - Gas Pump
 - Handheld Tanks
 - Omni Filter
 - Omni Mixer
 - Passive Pump
 - Portable Scrubber
 - Portable Pump
 - Portable Tanks
 - Tank Storage Unit
 - Trinary Filter
 - Trinary Mixer
 - Shutoff Valve Monitoring
 - Disposal Pipe Dispenser
 - Pipe Dispenser
 - Rapid Pipe Dispenser

# Alarms
 - Atmos Alerts
 - Air Alarms
 - Fire Alarms (removed UI)
 - Station Alerts

# Etc
 - Airlock Controller
 - Doors
 - Drone Fabricator
 - Elevator
 - Employment Records (related enough, right?)
 - Gravity Generator
 - ID Cards
 - Intellicards
 - Message Monitoring
 - Radios
 - RIGSuits
 - Space Heater
 - Signallers
 - Suit Cycler
 - Suit Storage Unit
 - Vending Machines
 - Wires!

# Power
 - APCs
 - PACMAN
 - Particle Accelerator Control Panel
 - Power Monitor
 - RCON
 - Shield Generator
 - SMES
 - Solar Controls
 - Shield Capacitor
 - Supermatter Monitoring
 - Silicon/Observer SM Monitoring
 - TEG

# Telecomms
 - Exonet
 - Server Monitor
 - Telecomms Monitor
 - Telecomms Multitool Menu
 - Quantum Relay

### CODE REVIEW

**Comment by ShadowLarkens** [comment]
note for when I'm not burnt to shit
HoldeltaToday at 21:08
is there any way to be turbo lazy and put sliders for input/output for the RCON?

**Comment by SplinterGP** [comment]
oh, neato, down on YW we have an autolathe that uses nanoUI and has queue and all, i dind't port it up yet because i dind't revise the code entirely but it seems to work completely fine, it also uses research designs system so you're able to add more recipes to it lets say stuff from away missions etc in a disk, if you want i can get you the nanoUI thing for it if you wanna convert it, or if you wanna teach me how to too.

**Comment by SplinterGP** [comment]
only trouble i remember having with it was the uh, unit test that says you cant have more than one design with same built path, so if you wanna make a design for a T-ray scanner on the autolathe and that one already exists for protolathe or any other machine, it gives a unit test error, except that nothing else. it has a field for searching stuff, categories, queue and a feature i added on science request that you can set it to eat materials on a tile adjacent to it.(Doens't work for stacks because they somehow just...bug alot, think aronai had issues with stacks on the auto stacking feature too.). if you wanna convert it to TGui or giving me tips on it, just give me a heads up!

**Comment by ShadowLarkens** [comment]
@SplinterGP Oh, thanks for the heads up! I'll probably look into that for help converting it here to TGUI, but I don't plan to do the Autolathe until TGUI Research. Not sure when that'll happen, I haven't decided what department to do next yet.

**Comment by SplinterGP** [comment]
oh alright!, i'll look on joining vorestation discord, since i'm not on it yet, but sure, i can do it if get me a little help, and port it up afterwards. 
image
that's pretty much how it looks like, and the code i did for it it's a mix of what we had and paradise autolathe. will get on discord and give you a ping, going to sleep soon so i'll try to see to do it tomorrow.

**Comment by KasparoVy** [comment]
> 
> 
> @SplinterGP Oh, thanks for the heads up! I'll probably look into that for help converting it here to TGUI, but I don't plan to do the Autolathe until TGUI Research. Not sure when that'll happen, I haven't decided what department to do next yet.

Great Cargonia! Ahaha. Buying/Order console, mining consoles (shuttle), that's about it basically.

**Comment by SplinterGP** [comment]
Btw discord link on wiki not working for me.

**Comment by ShadowLarkens** [comment]
Travis is freaking out, let's see if a new PR convinces it to stop

**Comment by ShadowLarkens** [comment]
#8629

**Pull request closed without merging**
