### PR TITLE
Skyrat singularity sprites

### PR DESCRIPTION
**Pull request by Arokha**
Each is old above new. Also moves S1 sprite out of singularity.dmi into effects, because every other stage of the singularity is in there. Awkward for there to be one stage not with it's friends.

# S1
old_s1
new_s1

# S3
old_s3
new_s3

# S5
old_s5
new_s5

# S9
old_s9
new_s9

### CODE REVIEW

**Comment by GhostActual** [comment]
I'll be honest, as pretty as the ones from Skyrat look, I prefer the classic hole in reality. It just has this ominous look to it that puts the fear of God in you while the other one is a singularity you'd view at a tourist attraction.

**Comment by Heroman3003** [comment]
Don't we also have clown-looking s11 singulo stage?

**Comment by Arokha** [comment]
> Don't we also have clown-looking s11 singulo stage?

Not that I saw. I mean I'm not replacing the S11 or theoretical clown S11 stages. They still exist, I just don't have one from skyrat to replace them with. I didn't delete them or anything.

If somehow the supermatter gets eaten it'll just use ye olde s11 stage. If there's a clown s11 stage I'm not aware of, it'd still be fine too.

**Comment by Very-Soft** [comment]
The new ones do look very nice, nice enough that they look like they were done by professionals. Are these from a different game originally or anything? 

Also, based on the icondiffbot, it looks like some of them don't loop. Not sure if that's just an icondiff bot thing or not, but something to double check on.

**Comment by Arokha** [comment]
> The new ones do look very nice, nice enough that they look like they were done by professionals. Are these from a different game originally or anything?
> 
> Also, based on the icondiffbot, it looks like some of them don't loop. Not sure if that's just an icondiff bot thing or not, but something to double check on.

In my browser they loop... looks fine to me even in IDB

**Comment by Ketrai** [comment]
Weird how it gets blue and sparkly at somw point when the other stages are relatively scary. But I'm down. Looks like this was done with effects rather than classic pixelart. Which tends to be something modern pixel art games use a lot for animation, lighting, etc.

**Comment by Ketrai** [comment]
Any chance of noting down the original author?

**Comment by Ketrai** [comment]
Looks like the original author is iamgoofball. Tho he's not the artist apparently. These were added into skyrat even before their repository went public, with no explanation given. He tried to add them to /TG/ as well https://github.com/tgstation/tgstation/pull/58439 .

**Comment by Ketrai** [comment]
https://cdn.discordapp.com/attachments/694611413582348288/744046619313569842/unknown.png Or this one which I believe is from NSV13

**Comment by Arokha** [comment]
I'm actually a bit surprised this one is the most mixed reactions so far lol, I think they look PURDY. But I'll close it for now. It'd be easy to do again if people change their minds.

**Pull request closed without merging**
