### PR TITLE
January Polaris Sync and various fixes

### PR DESCRIPTION
**Pull request by Cameron653**
- Polaris sync.
- Adds Wickedtemp's fixed healthhud sprite, along with the custom taur they provided.
- Fixes the floorlength braid. Again.
- Adds Xioen to alien whitelist for xenomorph hybrid ~~Removed so this can be merged~~  Fixed

Everything appears to work correctly.

Also, as Aronai pointed out, the science circuit room and librarian TV drone needs to be mapped in.

### CODE REVIEW

**Comment by Arokha** [comment]
`Vital Damage on FBPs is now tracked on the crew monitor`
Oh neat.

**Comment by Arokha** [comment]
`Adds Circuit Room to Science`
This one probably needs to be copypasted on the map.

**Comment by Arokha** [comment]
```Ports Bay's Journalist TV Drone
			f393daf
	@Neerti 	Map change + entertainment monitor tweak

Adds TV drone to librarian's office.
Entertainment monitors now broadcast the entertainment frequency when powered.```

This would need a map thing too.

**Comment by Arokha** [comment]
`Farmbots can be constructed again`
Someone was asking about this...

**Comment by Cameron653** [comment]
Was requested by Wickedtemp to add their fluff items. The above commit does so.

**Comment by Cameron653** [comment]
Commit above this comment fixed the floorlength braid.

Commit below this comment adds Xioen to the alien whitelist for xenomorph hybrids ( #842 )

**Pull request merged**
