### PR TITLE
Adds thermal regulators.

### PR DESCRIPTION
**Pull request by Cyantime**
Adds thermal regulators, which are basically space heaters but bigger. They need to be wrenched onto an cable node and take power directly from the powernet.
The temperature that they aim towards can be changed with a multitool.
One is added to atmos storage, and one to engineering storage. They can be ordered from cargo as well.
They can also be built from circuits, requiring 4 engineering and 3 power tech levels, 20 lengths of cable and 3 advanced capacitors.

### CODE REVIEW

**Comment by OrbisAnima** [comment]
Sauna metagroup approves of this.

**Comment by Cyantime** [comment]
Be sure to set it to ten million degrees and melt everyone in the sauna.

**Comment by SpadesNeil** [comment]
neat

**Comment by Yoshax** [comment]
Make them constructable.

**Comment by Cyantime** [comment]
Construction method added.

**Comment by SpadesNeil** [comment]
now add to wiki c:

https://wiki.vore-station.net/Guide_to_Construction

**Comment by Cyantime** [comment]
The frame already says what components are needed when the circuit is installed, it uses the standard machine building system.

**Comment by SpadesNeil** [comment]
CONFLICT REEEEEEE

we just updated the map heavily

**Comment by Cyantime** [comment]
Conflicts removed.

**Comment by Cameron653** [comment]
This good to merge? We need to map in slimes and there'll be conflicts if we don't merge this first.

**Pull request merged**
