### PR TITLE
[WIP] Cynosure Map Port

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Ports a more current version of Polaris' Cynosure map to our codebase. Why? Because I felt like it and wanted to see if it was doable. Mostly involved a lot of search and replace on item paths.

Marked as a draft because the dme currently has the map dm checked for testing. Also because it's actually still in testing. I would say it is 80-90% functional. Most of what's left is polish and fixes.

Overview:
Cynosure is a large three-level map based on the surface of Sif, a cold but breathable planet. The main facility consists of a ground level, a sublevel, and an upper level. A river curves around its western edge, running down from the high wilderness to the north. The facility uses a water-cooled supermatter core with solar backups. Departments are split mostly across z2 and z3, with mining and some 'hot' elements of the science department down on z1.

Notable changes:
- Resleeving and autoresleeving labs have been added, on z1 and z2 respectively. Auto-resleeving can be accessed with no medical assistance required via the maintenance tunnel between med and sec. Patients can leave via maint or via the main medbay area at their discretion.
- A gateway has been added to the basement level, with the east civilian elevator extended down to match.
- The wilderness checkpoint spawn and survivalist job are currently disabled.
- The random rooms in the sublevel are no longer randomized. A couple of slots have been left open/unused for personalization, the others are focused on socialization/recreation opportunities.
- Some glass panes on upper level overlooks have been removed. Watch your step!

To-do/known issues:
- [ ] Lighting gets funky in a handful of places, especially for the cargo shuttle after it departs.
- [ ] Minerals do not generate. This is my highest-priority fix target.
- [ ] There are no POIs in the north wilderness due to codebase divergence. Low priority, for now.
- [x] There are no offmap areas to explore; no debris field, no offmap sites, nothing. Just the telecomms satellite.
- [x] A handful of shuttles get confused and upset at roundstart. Related to the above, I think.
- [x] The Talon doesn't spawn either.
- [ ] Add belt mining or an approximate analogue (deep mining?).
- [ ] A buttload of active edges and scrubber/vent/APC-less zones need fixing.

### CODE REVIEW

**Comment by Heroman3003** [comment]
> Minerals do not be generate. This is my highest-priority fix target.

That might be simply due to your local config having mapgen off by default.

**Comment by KillianKirilenko** [comment]
> > Minerals do not be generate. This is my highest-priority fix target.
> 
> That might be simply due to your local config having mapgen off by default.

Nah, I tested it with tether just after and minerals generated fine. Polaris overhauled a bunch of mapgen stuff so there's other stuff I need to dig into I think.

**Comment by Cameron653** [comment]
I'd personally would like Cynosure being in rotation. It's a neat map.

Not my call, but has my support, anyway.

**Comment by KillianKirilenko** [comment]
> I'd personally would like Cynosure being in rotation. It's a neat map.
> 
> Not my call, but has my support, anyway.

It feels oddly cozy in a way that I can't quite pin down. Like it's not too big, but it doesn't feel too small, either?

I've got offmap stuff partially working at least. Mineral spawns are still being weird. Still got a lot of kinks that need ironed out before it's ready to rock.

**Comment by Heroman3003** [comment]
I personally am rather unsure about putting the Cynosure into the map rotation. I can't say its too radical or strong distaste for it, but I admittedly am very 'eh' about 4th rotation map being that.

**Comment by KillianKirilenko** [comment]
Closing for now. Might revisit later, but it'd be an extensive rework and a new project given I'd need to cut the map down to 140x140.

**Pull request closed without merging**
