### PR TITLE
attempts to port syringe icons

### PR DESCRIPTION
**Pull request by AmayaWah**
Ports the sprites of syringes from Baystation to Virgo!

### CODE REVIEW

**Comment by Heroman3003** [comment]
Isn't our current syringe icon code designed to like. Rotate to be verical when in the storages so that they don't overlap due to being smallest itemsize? Would that even work?

**Comment by Wickedtemp** [comment]
What are bays icons

**Comment by Heroman3003** [comment]
@Wickedtemp if you scroll down you can see Checks category at the bottom of PR. If you check Diffs check's details, you can see the icons comparison.

**Comment by Leshana** [comment]
It appears to me that this adds a new dmi file but not any code to use it, is that right?

**Comment by Wickedtemp** [comment]
I kinda prefer the ones we currently have over these. The current ones actually have syringe caps and just look nicer in my opinion.

**Comment by AmayaWah** [comment]
> It appears to me that this adds a new dmi file but not any code to use it, is that right?

Yes! I have no idea how to code and Aro said that I can just upload icons and it's ok.

**Comment by Wickedtemp** [comment]
Also how do these look in a syringe case?

**Pull request merged**
