### PR TITLE
Polaris Sync

### PR DESCRIPTION
**Pull request by LNSmith458**
Fixes a spelling mistake on the GUI for the Central Atmospherics Controller.

Yay first PR. Tell me if I made mistakes.

### CODE REVIEW

**Comment by Cyantime** [comment]
This is a Polaris typo, and should be fixed there.
https://github.com/PolarisSS13/Polaris/

**Comment by SpadesNeil** [comment]
Good catch. But yes, we should send this to Polaris.

**Comment by LNSmith458** [comment]
Will do. Thank you.

**Comment by Cameron653** [comment]
This isn't a polaris sync. This'll just cause conflicts if we commit this here. We'll get this with a real polaris sync if they have it upstream.

**Pull request closed without merging**
