### PR TITLE
[MIRROR] Nerfs Sonic Speed Wheelchair

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/5935
--------------------
Porting a few things from CHOMPstation, essentially to make it so that you're not going at Mach 3.

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
👏 Glad this one's all good.~

**Comment by Wickedtemp** [comment]
I kinda want to keep this.

**Comment by Iroquois-Pliskin** [comment]
fucc, I have to come up with new strats?

**Comment by Mewchild** [comment]
If you have a character that needs a wheelchair, or you have to use one for an extended period, this is painful. Any small amount of lag will have you jumping across the station.

https://github.com/VOREStation/VOREStation/issues/3556

**Pull request merged**
