### PR TITLE
Added Fire Fighting Foam Recipie

### PR DESCRIPTION
**Pull request by VictorZisthus**
For when you want to play around with the nifty water foam without draining all the actual tanks. Have fun with spray bottles and chem sprayers!

### CODE REVIEW

**Comment by KasparoVy** [comment]
Hell foooooam!

**Comment by VictorZisthus** [comment]
Another thing I'd really like to do is make it so that you can not only refill the tanks and stuff with this, but to make it so you can do so rapidly without the use of a chemmaster and bottle waste; Have the tank not accept the fluorine when dumping the contents in, allowing rapid refilling with just a click on a sink and the tank.

**Comment by VictorZisthus** [comment]
> 
> 
> Another thing I'd really like to do is make it so that you can not only refill the tanks and stuff with this, but to make it so you can do so rapidly without the use of a chemmaster and bottle waste; Have the tank not accept the fluorine when dumping the contents in, allowing rapid refilling with just a click on a sink and the tank.

On that note, we could even have a machine that just foams up the water instead...

**Comment by Zeldazackman** [comment]
Danke for adding this, as I was thinking about how lovely it'd be to have foam accessible for fighting fires and general walls of heat via the chem dispenser in a "certain situation" that arose due to xeno bio being well, xenobio

**Pull request merged**
