### PR TITLE
adds cool and fun new interactable environmental object

### PR DESCRIPTION
**Pull request by Screemonster**
barrelbig

y'all know exactly what this is and what it does

### CODE REVIEW

**Comment by KillianKirilenko** [comment]
Who do you suppose left all that radioactive waste down there? And why? ***Why?***

**Comment by Wickedtemp** [comment]
It's missing symbols! How will we know if its the acidic green sludge or the radioactive green sludge?

**Comment by Heroman3003** [comment]
Don't worry, it's all OSHA-approved, the Nanotrasen lets us do this

**Comment by Screemonster** [comment]
Don't y'all tempt me to copypasta the code from the manhole cover in there too

**Comment by Wickedtemp** [comment]
> Don't y'all tempt me to copypasta the code from the manhole cover in there too

DO IT DO IT DO IT

**Comment by foopwo** [comment]
> 
> 
> Who do you suppose left all that radioactive waste down there? And why? _**Why?**_

Why can't we find a way to safely dispose of radioactive waste and protect the environment?
Even if I personally stop this alien invasion. What kind of planet will we be leaving to our children? And our children's children, and...
### ...oh, the humanity!

**Comment by Darlantanis** [comment]
As a chemist this makes me scream.

**Pull request merged**
