### PR TITLE
[MIRROR] Makes math helpers defines for performance

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/5654
--------------------
What it says on the tin!

### CODE REVIEW

**Comment by SpadesNeil** [comment]
This is all gibberish to me and it's conflicted anyway.

**Comment by SpadesNeil** [comment]
weldingtool.dm had some screwy stuff but hopefully it's okay

**Comment by SpadesNeil** [comment]
No, I think I just deleted the welding tool's ability to start fires.

**Comment by Novacat** [comment]
Looks like welding tool was not merged properly. Can probably just hard reset it to Polaris, then port over the //VOREStation Edit changes, which is what I did when I worked on this PR.

**Comment by SpadesNeil** [comment]
If you can make another PR, the conflicts in this one are otherwise resolved.

**Pull request merged**
