### PR TITLE
better subtle, with targets including single tile and the normal 1 tile radius

### PR DESCRIPTION
**Pull request by Seris02**
and belly + preds
that was the most complicated logic in this whole thing, jesus

_**this should really, probably get a test merge or something I dunno, I can't test all the cases by myself on local**_

at the very least I know single tile subtle and 1 tile radius subtle both work all the time
and the all in belly + preds target also works, though I don't know for certain if it works for multiple preds, but it really, really should
objects inside bellies, like possessed items, also work for sure

ALSO, not certain if this needs vorestation comments?? because it's in a _vr file

### CODE REVIEW

**Comment by Seris02** [comment]
that wasn't my faaault that it failed

**Comment by Heroman3003** [comment]
tbh with psay and pme im not sure if this is entirely necessary to have but eh?

**Comment by Seris02** [comment]
> tbh with psay and pme im not sure if this is entirely necessary to have but eh?

yeah but what if I want to send it to people in belly who aren't absorbed and don't want to absorb said people

**Comment by Poojawa** [comment]
fun fact

if you log out from byond while still hosting a private server, you can then join your game again as a guest. This way you can test if your code works from multiple perspectives

**Comment by Seris02** [comment]
> fun fact
> 
> if you log out from byond while still hosting a private server, you can then join your game again as a guest. This way you can test if your code works from multiple perspectives

did that to test it but could only get up to one more client running

**Comment by Very-Soft** [comment]
Bringing up a dialogue to ask the range every time anyone sends a subtle is deffo no bueno, that will absolutely make normal subtle use more annoying, and should change if nothing else.

I don't super see the point in 1 tile either though. It sort of feels like, if you're wanting THAT level of privacy, you really ought to just move so you're not adjacent to other people.

**Comment by Novacat** [comment]
If there are only two options the better solution would be to just have a tablesubtle or something like that.

**Comment by Seris02** [comment]
> If there are only two options the better solution would be to just have a tablesubtle or something like that.

there are three, along with having specific targets as well

think I'll just close this and PR it downstream as a separate verb

**Pull request closed without merging**
