### PR TITLE
Adds in Spirit markings

### PR DESCRIPTION
**Pull request by kcin2001**
w/o markings
image

w/ markings
image

also available are headless versions of the lights and panels markings for people who like monitor heads

### CODE REVIEW

**Comment by kcin2001** [comment]
I have the all but the head but no just head, should i add a just the head?

**Comment by Arokha** [comment]
If you feel like doing the work, I personally think it'd be better with each set having:
- Whatever Name (Body)
- Whatever Name (Head)

Since that's how the tiger stripes are (maybe a couple others).

**Comment by kcin2001** [comment]
Its not like i have to make any new sprites just need to add a few more defines for markings

**Comment by kcin2001** [comment]
Ill do it when i get home

**Comment by kcin2001** [comment]
ugh

**Comment by kcin2001** [comment]
wtf happened

**Comment by kcin2001** [comment]
btw did a pr get merged that touches markings_vr.dmi?

**Comment by Arokha** [comment]
Maybe, not sure. There was the Teshari one that was open for a while, I think that one did probably.

**Comment by kcin2001** [comment]
Anyways I'll have to fix this later

**Pull request closed without merging**
