### PR TITLE
TGUI Medical: Second Pass

### PR DESCRIPTION
**Pull request by ShadowLarkens**
This is a second pass of Medical conversions to TGUI.
The following UIs have now been converted:
 - Body Designer (Bonus: Updates are now instant, and use a map element like the real preferences window.)
 - Cabinets
 - Disease Splicer
 - Isolation Centrifuge
 - Mirrors/Change Mob Appearance
 - Pathogenic Incubator
 - Pathogenic Isolator
 - SmartFridge

Additionally, a 30/60 preset has been added to the ChemMaster.
Also, upgraded Font Awesome to v5.14.0 because mmm virology icons

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
What about the bioprinter?

**Comment by Wickedtemp** [comment]
For the smart-fridge, what does the 'many' button do? Does it dispense 5?

**Comment by KasparoVy** [comment]
Oh dear god SalonPro/CMA ahaha. Too much time I spent fucking with that in NanoUI

**Comment by ShadowLarkens** [comment]
@TheFurryFeline the bioprinter doesn't have a UI, does it? It just has a bunch of selection boxes.
@Wickedtemp It displays a prompt asking you how many you want to dispense.

**Comment by Wickedtemp** [comment]
Neato

**Comment by TheFurryFeline** [comment]
Uhhhh, I don't remember, been ages since I touched that machine for limb printing.

**Pull request merged**
