### PR TITLE
New rollerbed sprites

### PR DESCRIPTION
**Pull request by Arokha**
Less eye-melting blue, now with More Clickability

image

### CODE REVIEW

**Comment by KasparoVy** [comment]
Looks awesome.

**Comment by Heroman3003** [comment]
Clickability is good, but I don't like the lack of white line on new sprite. Kinda made it actually look like a bed.

**Comment by Novacat** [comment]
Hospital beds actually do look like that. They tend to be very minimalistic and are not very comfortable.

**Comment by Heroman3003** [comment]
Eh, its less about it being comfortable and more about just having different color in 'where head goes' spot. Doesn't have to look like pillow like old one.

**Pull request merged**
