### PR TITLE
Traits clarity, changes, and additions.

### PR DESCRIPTION
**Pull request by Cameron653**
- Makes most traits clarify how weaker/stronger you are in terms of percents.
- Adds minor brute weakness & minor burn weakness/resistance. 1 point for 15% weakness.
- Increases brute/burn weakness to 25% for 2 points
- Makes brute/burn weakness/resistance for 50% for 3 points
- Adds "Very Low/High Endurance" which increases/decreases health by 50% for 3 points
- Increases haste+ & slowdown+ to 5 points. Haste/Slowdown to 3 points.
- Makes conductive go from 15% to 50% & 2 points. Conductive+ from 30% to 100% & 3 points
- Non-Conductive gives 25% resistance for 2 points. Non-Conductive plus 50% resistance for 3 points.

Please submit feedback for changes.

### CODE REVIEW

**Comment by DickFreedomJohnson** [comment]
+1 support I like these changes

**Comment by SilverTalismen** [comment]
Looks good to me, I never really use custom species much so its fine to me

**Comment by Cameron653** [comment]
Points fixed.

Conductive is a trait that's historically been taken because it has little to no effect in the game whatsoever until it comes to tasers. It was almost exclusively used as a trait to get haste w/ little downside. A 30% increase in taser or shock damage is nothing, but now it _actually_ has a stronger effect and people will think twice before using it as part of a "get haste with no noticeable downsides." 

Naming also fixed

**Comment by SpadesNeil** [comment]
Do we need any more feedback on this?

**Comment by Cameron653** [comment]
This should be good to merge. I got all the feedback I can imagine I'll get.

**Pull request merged**
