### PR TITLE
[READY] Removes Dogborgs

### PR DESCRIPTION
**Pull request by Heroman3003**
This has been a loooong time coming.

Topic of “dogborg” vs “normal borg” has been controversial for quite some time on different levels, and many arguments were levied, but ultimately, there was no answer to the issues that arose from disparity in perception between the two. This means the only feasible solution is to remove the dogborgs forever.

Yeah, nah, I’m kidding. Kinda. Sorta.
As of this PR’s merging, dogborg modules will be gone. Dogborgs themselves, however, will remain as just sprite options for existing borgs. Don’t worry! Most equipment unique to dogborgs, even bellies, has been transferred over. Same applies to other dogborg-unique features such as eye lights, resting sprites, dead sprites, belly sprites. All have been preserved without needing to make all those for all regular borgs thanks to new robust datumized borg sprite system.

Checklist of things to do:
- [x] Create modular datum type for robot sprites
- [x] Create subsystem for better storage and access to said datums
- [x] Change borg code to update icons based off of datums in question
- [x] Convert all existing station borg icons to use datums (11/11)
- [x] Develop sprite handling for 'special' borgs (syndie, event) (5/5)
- [x] Rework virgo lost drone pod to work back with single module again
- [x] Develop sprite handling for whitelisted module sprites
- [x] Develop sprite handling for Boozehound (it deserves its own spot on the list with its jank)
- [x] Devleop sprite handling for Default module and contingencies
- [x] Add system for sprite-specific borg module icon
- [x] Don't forget to add faildogs for issue spotting
- [x] Combine equipment lists of regular borgs and dogborgs into one singular list, that includes full functionale (10/10)
- [x] Give regular borgs unique dogborg functionale unrelated to equipment (i.e. riding)
- [x] Create system for 'fluff' appearance changes for borg equipment (puppy jaws, etc)
- [x] Lots of testing

So, a little presumptive Q&A about the whole thing.

Q: I can’t find dogborg module in the module list! How do I buppy!!!?!
A: Dogborgs have been merged into their respective ‘origin’ modules. Just pick the module and find the sprites for dogborgs (usually all collected at the bottom of the list, for sorting ease) For reference:
Security – K9
Crisis – Medihound
Surgeon – Traumahound
Engineering – Pupdozer
Research – Sci-borg
Miner – KMine
Janitor - Scrubpup
Service – Servicehound and Boozehound
Combat - ERT
Lost - Stray

Q: What about my cute sitting/belly/etc sprites?
A: All sprite-related features dogborgs had have been preserved, and modular system allows any new borg sprites added to have these features or not have them at will, not just dogborgs.

Q: What about belly module?
A: All borgs have belly module now.

Q: What about other unique dogborg equipment?
A: The fates of dogborg-unique things is as follows:
Boop module is now available to all borgs.
Tongue module is is now available to all borgs, but in slightly nerfed state – it no longer can clean and is mostly a fluff thing, except for its secret purpose, unlocked with—
Puppy jaws module has been effectively removed due to just being a generic low-damage weapon, BUT if your module sprite is a dog/drake/raptor borg, you’ll find your universal crowbar reskinned into that. Pry things with your jaws.
Other dogborg-unique things (paws of life, jumper paws, dogborg bag, sword tail, ert jaws) are still present as reskins of non-dogborg skins that only apply if your sprite is dogborg. Flexibility of such allows creation of heavily themed module sprites!

Q: What about dog puns in module name on manifest?
A: Yeah, those are gone. Sorry, but I do think it’s for the best to remove that unnecessary split between ‘borg for vore’ and ‘borg for job’.

Q: Boozehound could change color of its belly dynamically! Can I still do it?
A: Yes, although the proc for it is a bit more generic now, to account for other borg types in future potentially doing it - Customize Appearance.

Q: Whitelisted borg sprites, what about those?
A: All functional. Whitelisting itself is now done more akin to how loadout fluff item whitelisting is done, but otherwise all existing whitelists have been transferred over.

Q: I have flavor text set up for my dogborgs! Will it be lost?
A: Sadly, yes, not much I can do there. I recommend saving it separately before update is pushed through.

Q: So, everything is okay?
A: Yes! It might be a bit confusing at first, but long-term it’s both gonna enable more flexibility with adding borg sprites and remove last traces of dogborgs being the only borgs capable of vorny, at price of being worse at job.

Q: I chose a dogborg module and don't have a crowbar help!
A: That's what Puppy Jaws are now for. Theyre a reskin of crowbar.

Few extra notes:
- There are several unused sprites around that I am spotting that could be better used with new system, such as standard tallborgs. I am NOT doing that as I'm working on this. I don't know if I'll do it after this is done, but I'd welcome if someone is interested. 
- Some features of existing implemented sprites that just werent functional, however, such as some borgs having borg-specific 'open' sprites that didnt work or zoombas having 'dead' sprites that didnt work, are going to be implemented properly.
- The system is intended to be very modular to allow new sprite additions to be a lot more flexible with what elements they wish to have. Different sets of resting sprites, whether they get belly or not, equipment-based sprite changes, etc, etc, all independant of one another.
- Yes, this will mean all station borgs will have access to the belly module
- All the original robot icon files are untouched for now. Ideally theyll be cleaned out later, but for the moment I am leaving them be.

Current list of changes in process:
- Added a few new sprites - M-USE for station modules that didnt have it, as well as Service drakeborg.
- Medical tallborg sprites are now usable by both crisis and surgeon modules, not just crisis. The medihounds remain module locked as they have equivalents of different paintjobs.
- Water reserves and everything related to refilling and spending them are gone.
- Nerfed the tongue module by removing ability to clean.
- Puppy jaws have been removed from all modules, now the crowbar reskins into them if you're a dogborg, they werent practical either way.
- Boop module is available to all modules.
- Pounce is either available via emag or via normal module to all borgs
- Added one brand new belly module - generic Internal Cache for Standard and Clerical modules. They don't have any dogborg sprites, but they get a belly anyway.
- Lost Drone pod has been reworked. Instead of choosing between normal and dogborg, you now choose whether you get regular or vorny laws. Vorny laws guarantees the, well, vorny-oriented lawset attempt. As for sprite, you can choose either normal or dogborg as either option.
- As unrelated thing, completely deprecated the updateicon proc in favour of universally-used update_icon
- Might be forgetting other minor stuff, but feel free to point out or ask questions.

### CODE REVIEW

**Comment by User-U-U** [comment]
This was done on another codebase, I think citadel SR maybe not sure. Removed all the fluff was super lame. Also the crew manifest, character directory and examine will just show medical robot instead of the module names now. :/ I don't see the point

**Comment by TankTheBirb** [comment]
Given our focus on vore, having two different modules of each type was sort of a legacy thing we could move away from. It just needed someone insane enough to do it. As I understand it, the original reason we had it separate was because of Polaris. Which is no longer a concern for us.

So anyways I fully approve of this insane project as my earlier PRs for borg balancing could only address the tooling disparities, but not the mechanical disparities. Merging them all into the same modules will solve any balance between the modules entirely. It also, as you mentioned, opens up the option for non-dogborgs to get belly sprites without having to be a pupdozer/medihound etc.

**Comment by TankTheBirb** [comment]
> This was done on another codebase, I think citadel SR maybe not sure. Removed all the fluff was super lame. Also the crew manifest, character directory and examine will just show medical robot instead of the module names now. :/ I don't see the point

The point is that we don't need them to be separate modules with separate mechanics to them if we do this. For example, in the new system, someone could make a static sprite with a belly without having to also make rest and wreck states plus lights etc. Even if those are just copy pastes of the original sprite.

As fun as it is to have the themed names, calling the new MEKA or NIKO sprites various dog names is kinda stressing the point that there isn't a reason to have them separate unless we need to keep the mechanics separate. It was already weird with drakeborgs and raptorborgs. And we don't have a reason anymore to keep the modules separate.

**Comment by AviiCinders** [comment]
Finally we can recognize the superiority of raptorborgs!

Wait that isn't this PR?

**Comment by Very-Soft** [comment]
Tested the borgs some, feedback and bugs follow:
-Unsure if every borg module should have the lick module as it's kind of cursed for a roomba or a whatever the 'Tower' borg is supposed to be to run up and lick people, but that's just personal opinion.
-Unsure if the MEKA borg sprite is supposed to have a vore belly or not, it did not display one, while MEKA v2 did. Tested this specifically on the engineering module.
-Servicehound V2/ Darkmode don't have a vore belly sprite

Additionally we should make the admin log messages for borg eating and digesting just be admin log, or attack logs, not log_and_message_admins or whatever it is. There's not really a great reason to message us when borgs do vore.

**Comment by DigitalSquirrel95** [comment]
Hi hello.  Helping Soft with the various bug testing for this monster of a PR.  Posting any issues I find in this comment
-Boozehound currently returns a sprite error when you rest.  This happens both with, and without prey in your belly module.
-All borg types return "X has digested/eaten Y as a dogborg" in admin logs instead of "as a borg"
-All sprites for the "ScihoundDark" icon return as a sprite error.

**Pull request merged**
