### PR TITLE
Added Frog Taurs

### PR DESCRIPTION
**Pull request by MechaFrogg**
Added Frog taurs! I have no idea what I'm doing!

### CODE REVIEW

**Comment by MechaFrogg** [comment]
froggo

**Comment by SpadesNeil** [comment]
`H a s  s c i e n c e  g o n e  t o o  f a r ?`

**Comment by SpadesNeil** [comment]
[1:47 AM] Mewchild: Science has gone too far, but options are always good. Tell him that Eros station gives their seal of approval, but also tell him to pick up a bible

**Comment by Cameron653** [comment]
:+1:

**Comment by SpadesNeil** [comment]
fuckit

**Pull request merged**
