### PR TITLE
Minor Bugfixes/Tweaks - Expedition-focused.

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
Addresses V2 atmos tiles not allowing shots over them, and reduces charge/crank time for frontier phasers, as well as buffing them - you can reload while moving. QOL! <3

Specifically - Frontier Phasers/Carbines are 28 seconds to reload/recharge, Holdout Phasers are... 18-20. And they can be recharged on the move.

Before you worry about powergaming, they're still station-locked, and frankly, this buff is MASSIVELY needed with the damn ion hivebots everywhere still.

### CODE REVIEW

**Comment by Rykka-Stormheart** [comment]
#5620 is resolved via this PR.

**Comment by Screemonster** [comment]
I have no idea what the hell happened in the diff there

still think it'd be better to have a generic check for objects to decide whether they're subject to gravity or not rather than having the turf check specifically for projectiles and floating mobs

**Comment by Rykka-Stormheart** [comment]
> I have no idea what the hell happened in the diff there
> 
> still think it'd be better to have a generic check for objects to decide whether they're subject to gravity or not rather than having the turf check specifically for projectiles and floating mobs

Of course, I totally agree on that. In the meantime, though, this is a good "bandaid" fix we can sneak into the September update. Hopefully. <3

**Comment by Rykka-Stormheart** [comment]
I'm removing the expedition weapons tweaks for a separate PR.

**Pull request merged**
