### PR TITLE
Move away from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by ShadowLarkens**
This PR moves our CI Testing from Travis to GitHub Actions, following the approach of [Paradise](https://github.com/ParadiseSS13/Paradise/pull/14958)
and [/tg/station](https://github.com/tgstation/tgstation/pull/54668).

While some of our maintainers have assured us that it'll be fine and there's ways to keep using Travis for free...
it's really not worth the hassle, nor the danger of staying with a shaky platform. 

Travis is undergoing a lot of changes right now, and they're really not for the best, as they're enforcing much
stricter usage limits on their free tier in response to overuse.

It's really not a great idea to trust them at this point in time, nor the forseeable future, especially 
when we have the lovely built in Workflows courtesy of GitHub.

### CODE REVIEW

**Comment by KasparoVy** [comment]
Peace Travis

**Comment by park66665** [comment]
Guess this is a trend now; Bee too has moved to GitHub Actions:
BeeStation/BeeStation-Hornet#2902

Kudos for the work of CI migration btw

**Comment by Novacat** [comment]
Because this is a big change, going to poke Leshana and Aronai to give this a look over.

**Review by Arokha — APPROVED** [review]
Looks good to me.

**Comment by Shadow-Quill** [comment]
lgtm?

**Comment by TheFurryFeline** [comment]
Rest in pieces, Travis, our lord, for we have revolted against thee

**Pull request merged**
