### PR TITLE
Readd "All" Button to vore panel

### PR DESCRIPTION
**Pull request by ShadowLarkens**

### CODE REVIEW

**Comment by Heroman3003** [comment]
Does it appear even when there's no contents there, only when there's one thing or when there's two or more?

**Comment by ShadowLarkens** [comment]
It always appears

**Comment by Heroman3003** [comment]
Does it break anything if you try using it with 1 or 0 contents?

**Comment by ShadowLarkens** [comment]
Doesn't break anything, doesn't make a sound as release_all_contents cancels if there's nothing inside and transfer contents only runs for things in the belly and therefore won't be called if there's nothing there

**Pull request merged**
