### PR TITLE
Make gas turbine constructable and operational

### PR DESCRIPTION
**Pull request by Leshana**
* Make gas turbine constructable, as well as modernizing its code. Borrowed some from /tg
* Converted the gas turbine control computer to nano ui.

### CODE REVIEW

**Comment by Cyantime** [comment]
More engines for the engine pile!

**Comment by Jakksergal** [comment]
Would it be possible to do this with the pipe-based variant as well?

**Comment by Screemonster** [comment]
The codebases that have this don't have meltable walls and airlocks - what sort of temperatures are needed for it to be useful?

**Comment by Leshana** [comment]
@Jakksergal Probably.  But I was able to leverage mostly existing code and /tg's working turbines to do this quickly.   Plus the sprites aren't terrible.   The pipe based sprites are super bleh.
@Screemonster That sounds like a great thing for SCIENCE to find out, through RESEARCH!

**Pull request merged**
