### PR TITLE
Adds bolts to dorms.

### LINKED ISSUE #303: Dorms need either a lock or an occupied sign.
#### Brief description of the issue
I've been ghosting over the dorms for literally five minutes and seen three scenes get walked in on 'cause the other party (who was looking for an unoccupied one) had no way of telling which ones were taken.

#### What you expected to happen
Door locks like the old station, or at least an occupied sign like Surgery.

#### What actually happened
Testing every door like the stalls in a busy restroom until you find one that's unoccupied.

#### Steps to reproduce
Go to dorms.
Stroll in awkwardly upon a couple wherein one is waist-deep inside the other (facing doesn't matter)
Make awkward excuse and back away. Repeat in next dorm.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

### PR DESCRIPTION
**Pull request by Arokha**
We can fancy them up later with reserving by ID and whatnot.

Fixes #303

### CODE REVIEW

**Comment by SpadesNeil** [comment]
sdfzkg,hag,knjk use the map tooooools. :U

**Comment by Arokha** [comment]
I wasn’t aware we were using those? :v

**Comment by SpadesNeil** [comment]
Use theeeeeemmmm.

**Comment by Arokha** [comment]
Alriiiight. Well I'll have to redo all these changes if you want me to redo this with the map tools @_@ Can I just start doing it after this one?

**Comment by SpadesNeil** [comment]
Or you could save your changes on a new map first. :P

- Copy into virgo-1-Copy.dmm
- Get clean version of virgo-1.dmm
- Run map prep tool.
- Copy edits from virgo-1-Copy.dmm to virgo-1.dmm
- Delete the copy.
- Save changes.
- Run map cleanup.

**Comment by SpadesNeil** [comment]
Actually fuckit I'll do it. *nodnod* I have to handle this anyway: https://github.com/VOREStation/VOREStation/issues/331

**Pull request merged**
