### PR TITLE
Remove combat medkit from station spawns

### PR DESCRIPTION
**Pull request by Arokha**
It's pretty damn powerful for something you can just randomly find in several spots on the station.

### CODE REVIEW

**Comment by Natje0** [comment]
However, just like the black and red toolboxes, they don't always appear. They're rare to come across, and typically only one person will get it in a round. I really don't see any reason to take this away, and personally, I'd rather see it left in.

**Comment by Cyantime** [comment]
The red and black toolboxes that spawn randomly already had their power tools removed.

**Comment by Arokha** [comment]
It's more rare than the others, but there are still SEVEN spawners on the station.

**Comment by Cyantime** [comment]
Go back to gauze and ointments, put adv brute/burn kits in RnD

**Comment by Natje0** [comment]
Okay, I didn't know there was seven of them. How about just leaving the in-medical spawns, so it can be the occasional boon for Medical players, just like that one hypospray that sometimes spawn here or there?
And now that you mention it, yeah, Polaris redid the black&red toolboxes and ours got hit by the same. I'd want those turned back to normal again tbh, but that's not the topic atm.

I just don't want to see something useful and fun to find for medical players to just be removed like this for such a reason. It's *pills*, it's still much worse than if you get chemistry done, or put in work to liquify it all.

**Comment by Arokha** [comment]
- /obj/item/weapon/storage/pill_bottle/bicaridine - Bottle of 7 Bicard pills
  - Total healing potential: 420 brute damage (if ingested. Double if injected.)
- /obj/item/weapon/storage/pill_bottle/dermaline - Bottle of 7 Derma pills
  - Total healing potential: 840 burn damage (if ingested. Double if injected.)
- /obj/item/weapon/storage/pill_bottle/dexalin_plus - Bottle of 7 Dex+ pills
  - Total healing potential: 23 minutes of oxyloss immunity
- /obj/item/weapon/storage/pill_bottle/dylovene - Bottle of 7 Dylo pills
  - Total healing potential: 280 tox damage (if ingested. Double if injected.)
- /obj/item/weapon/storage/pill_bottle/tramadol - Bottle of 7 Tram pills
  - Not super hard to make, not a huge deal, but pretty robust.
- /obj/item/weapon/storage/pill_bottle/spaceacillin - Bottle of 7 Spaceacillin pills
  - Doesn't spawn anywhere else. Syringes are lower dosages. The only kit to contain this.
- [...]/hypospray/autoinjector/biginjector/clotting - Myelamine injector
  - Not super common, can't even make this in chem by default
- /obj/item/stack/medical/splint - Splint stack
  - Okay, pretty boring
- /obj/item/device/healthanalyzer/advanced - Advanced (L3) health analyzer
  - Impossible to obtain any other way

So on the whole, that one medkit will heal:
420 brute, 840 burn, 280 tox, 23 minutes of oxyloss
and contains
A health analyzer that's unobtainable in the game and meant for PoIs and stuff, and an autoinjector that can prevent the need for surgery (only once, admittedly)

**Pull request merged**
