### PR TITLE
Bumps borgs up by one.

### PR DESCRIPTION
**Pull request by Cameron653**
Increases borgs, so one more borg can latejoin.

https://i.imgur.com/X7MIKPZ.png

### CODE REVIEW

**Comment by icowom** [comment]
Mhmm, this would be perfect for setting up a squad of doggo borgs! Also some spread where every dept has at least one borg to call into service

**Comment by SpadesNeil** [comment]
I'm not sure we need so many borgs tbh.

**Comment by Cameron653** [comment]
People are requesting it and ahelps for borg slots to be opened isn't too uncommon, along with the fact borgs have such a different playstyle than humanoids that people seem to enjoy.

**Comment by SpadesNeil** [comment]
fuckit, but no more

**Pull request merged**
