### PR TITLE
Fixes cloning fucking up ear colors and wings.

### PR DESCRIPTION
**Pull request by Verkister**
-Yeh this fixes those.
kuva

### CODE REVIEW

**Comment by Dinnel** [comment]
If that's right, then this fixes this issue I had before. https://github.com/VOREStation/VOREStation/issues/2449

**Comment by Verkister** [comment]
Yeah it does.

**Comment by Cameron653** [comment]
Does this also fix the one machine that lets you make a sleeve?

**Comment by Verkister** [comment]
Probably. Seemed the dna code had it snipping out the uis past 27, and if the issues on that machine are dna related and the symptoms including the same borkage from ear color blue level, secondary ear color, wings, and wing color, then I'm pretty sure it could be the very same issue with this.

**Comment by Cameron653** [comment]
Alright. Happy to see someone found out the cause of this issue.

**Pull request merged**
