### PR TITLE
Food for Thought

### PR DESCRIPTION
**Pull request by klaasjared**
Tired of the lack of vending machines that offer delicious food options? Sick of Getmore and their tiresome slogans? Well here is the PR for you!

This PR adds several Baystation vending machines and their food items to Polaris as well as a brand new machine to aid in bloat removal. Below is a lenghty list of all current food vendors and the snacks taht each will carry.

Getmore Chocolate Corp

-Tau Ceti Bar
-Hundred-Thousand Thaler Bar
-Aerostat Bar
-Lars' Saltlakris
-Andromeda Bar
-Mocha Crunch
-Cronk Bar
-Shantak Bar
-Grandma Ellen's Hard Candy
-AlliCo Gummies
-BBQ Chips
-Chips
-4no Raisins
-Gum
-Admints
-Skrellsnax 
SnL Co. Snacks

-Tuna Snax
-BBQ Chips
-Chips
-Pistachios
-Smeki
-Salo
-Vobla (dried fish)
-4no Raisins
-Snack Cake
-Cheesie Honkers
-Syndi-Cakes
-Carps Ahoy! miniature cookies
-Bread Tube
-Beef Jerky
-Beef Jerky (True)
-Skrellsnax 
SweatMAX

-ChewMAX fruit bar
-SwoleMAX protein bar
Sol-Snacks

-Tidal Gobs (Triton)
-Saturn-0s -SPRITE DONE
-Jove Gello
-Plutonian Rods
-Frouka (Mars)
-Venusian Hot Cakes -SPRITE DONE
-Oort Cloud Rocks
-BBQ Chips
-Chips
-Skrellsnax 
-Gum
-Admints
-Sun Snax (Spicy chips)
-Appleberry Bits (Canned Cereal)
Nippon-tan!

-Rice Cake
-Pokeys
-Red Alert Nuts
-Choco Banang
-Hanami Dango
-Goma Dango
-Kaju Mamma! Bar
-TaroMilk Bar
-Calamari Crisps
-Skrellsnax 
-Ramen
-Namagashi
-Dorayaki
-Wasabi Peas
-Daifuku
Snix

-Suhariki (croutons)
-Canned Caviar
-Canned Caviar (True)
-Pistachios
-Smeki
-Salo
-Vobla (dried fish)
-Calamari Crisps
-Gum
-Admints
-Skrellsnax 
-MAPS
-Hakarl
-Pretzels
I would post all the lovely sprites that were added but then this would be ten times as long so instead here a sample showcase of some of the things that were added.

vstec_showcase

z_showcase_1

z_showcase_2

https://user-images.githubusercontent.com/609886/115921196-29747d00-a449-11eb-9634-08627fc1ae03.mp4

https://user-images.githubusercontent.com/609886/115921215-309b8b00-a449-11eb-83bc-f7d08477fd78.mp4

This PR is essentially done but does require a check from developers and moderators to make sure that nothing was missed during the coding process.

### CODE REVIEW

**Comment by Heroman3003** [comment]
There's really no need for all the countless comments specifying date of addition.

Also, none of these vendors appear to actually exist? Like, they are added, but are both unobtainable and not mapped in.

**Comment by klaasjared** [comment]
> There's really no need for all the countless comments specifying date of addition.
> 
> Also, none of these vendors appear to actually exist? Like, they are added, but are both unobtainable and not mapped in.

I've yet to code them into the maps yet - since the current map is being updated and changed I didn't want to do any map changes just yet. The vendors are ports from Baystation with added snacks - only one new food vendor is added. This is still a work-in-progress type deal, however the port works and can be pushed for mappers to add what they please from the selection of vendors that are added. Might possibly take a note out of tg/station and make it where vendors are randomized each shift but that is a ways down the line.

Also, the date of addition helps me find stuff easier, it's for organizational purposes.

**Comment by Greenjoe12345** [comment]
this was meant to be up on polaris but it was just.. dropped there and done here with all the modular stuff.. :(

**Comment by klaasjared** [comment]
> this was meant to be up on polaris but it was just.. dropped there and done here with all the modular stuff.. :(

I have my reasons why

**Review by Novacat — CHANGES_REQUESTED** [review]
Since this was already done upstream, I would recommend just earlyporting that down here and re-opening the Polaris PR.

**Pull request closed without merging**
