### PR TITLE
Nerfs cargo pizza

### PR DESCRIPTION
**Pull request by Ketrai**
Currently cargo pizza is identical to what the chef can cook. And it has become a huge staple for cargo to order. It's painful for a chef to come later in a shift, only to see everyone eating pizza, or for cargo to order pizza whilst they're on the job. 

This makes pizza from cargo an inferior version to that which the chef can cook. The amount of nutrients is worse, the taste is worse, and it takes more work compared to before, it's barely nutritious, and even dangerous to eat to some before you heat it up. It's still better than what you can get from a vending machine, but not as good as what the chef can make.

Summary of changes:
- supply crates come with frozen pizzas
- frozen pizzas have frost oil, harms prometheans
- heat frozen pizza to get pizza
- pizza looks worse, tastes worse, less nutritious
- new sprites for both frozen pizza, and thawed pizza. Visually different from chef pizza.
- made it cheaper to order pizza, as it is a direct nerf to the value of them.

### CODE REVIEW

**Comment by Screemonster** [comment]
A real pizza from the chef should definitely be better than ordering a freezer full of prepackaged crap. Microwaves are abundant enough in basically any department for this to not be an issue, and this puts cargo pizzzas nicely in the gap between "vending machine shit" and "actual food".

The burger and chinese food crates honestly aren't as bad as pizzas for replacing the chef given that each pizza is half a dozen slices. Shame we won't get scenes like this any more though:

image

Once again, people ordering in food when a chef exists ruin these precious moments when there isn't a chef and someone asks scree to solve this problem :V

**Comment by SpadesNeil** [comment]
This would be a good thing to port to Polaris at some point, but for us, we're certainly using this.

**Comment by ArgobargSoup** [comment]
Interesting, but I have one problem with this.

Namely, from personal experience, cooking something in the microwave doesn't *remove* reagents.  So this frozen pizza?  It's gonna keep that frost oil when heated in the microwave.

**Comment by Ketrai** [comment]
> Interesting, but I have one problem with this.
> 
> Namely, from personal experience, cooking something in the microwave doesn't _remove_ reagents. So this frozen pizza? It's gonna keep that frost oil when heated in the microwave.

I specifically coded it so unfrozen pizzas remove the reagents. Similar to how cooking xenomeat removed the acid.

**Comment by ArgobargSoup** [comment]
...Huh.  I managed to miss those lines.  And I've never cooked xenomeat on this server, due to xenos never bein' around, so I wouldn't know that part  :P

**Comment by Wickedtemp** [comment]
So... No pizza parties, unless there's a chef willing to grow and collect all of the required supplies?

**Comment by Sebbe9123** [comment]
> So... No pizza parties, unless there's a chef willing to grow and collect all of the required supplies?

No pizza parties unless that or there isn't a chef. Alternatively the Chef can order frozen pizzas and heat them up if they are lazy.

**Comment by Ketrai** [comment]
> So... No pizza parties, unless there's a chef willing to grow and collect all of the required supplies?

Reminding ya'll that there's 4 microwaves in the dorms. One in some break rooms. One in the mining outpost. One in the public garden. And you can easily get an engineer to make you one to put in the library if you so deem it necessary. The only thing that has changed really is that the pizzas are of worse quality, and ya gota heat em. Nothing is stopping you from doing an event with a delivery guy bringing real, warm pizzas. Makes more sense than having them shipped in a freezer in a cargo ship.

**Comment by Very-Soft** [comment]
Okay so let me just throw this out there... why?
The main reason people order pizzas is for when there is no chef, or the chef hasn't put out any food. Or for scenes. You're taking like, one of the only things people actually order from cargo, and just making it annoying to deal with. 

It seems like you're trying to punish people for having fun, when this has been a relatively non-issue tbh. Like, if you wanted to gimp pizzas you could probably just make the crate deliver 1 pizza instead of 5, instead of making a whole new kind of pizza that is 'dangerous if you don't cook it'.

**Comment by SpadesNeil** [comment]
>The main reason people order pizzas is for when there is no chef, or the chef hasn't put out any food. Or for scenes. You're taking like, one of the only things people actually order from cargo, and just making it annoying to deal with.

Because it makes the chef obsolete is why.

>It seems like you're trying to punish people for having fun, when this has been a relatively non-issue tbh. Like, if you wanted to gimp pizzas you could probably just make the crate deliver 1 pizza instead of 5, instead of making a whole new kind of pizza that is 'dangerous if you don't cook it'.

This has **not** been a non-issue. This has been an issue as long as Vorestation has been around. Chef players are made obsolete by there being a more convenient way to just stuff everyone with more nutriment than they could ever possibly need even on a _vore_ server _with the nutriment caps removed_.

And a little bit of frost oil isn't seriously that dangerous, c'mon.

**Comment by TheDavestDave** [comment]
there's no microwave in the public garden. The only public ones are in space or dorms, that we don't want people useing other than to lewd. 

and food code is funny. If you remove carpotoxin from a carp fillet. Cook it into fish and chips. It magicly has carp-o-toxin again

**Comment by Ketrai** [comment]
> there's no microwave in the public garden. The only public ones are in space or dorms, that we don't want people useing other than to lewd.
> 
> and food code is funny. If you remove carpotoxin from a carp fillet. Cook it into fish and chips. It magicly has carp-o-toxin again

I believe it to be intended. /obj/item/weapon/reagent_containers/food/snacks/fishfingers/New()
	..()
	reagents.add_reagent("protein", 4)
	reagents.add_reagent("carpotoxin", 3)
	bitesize = 3

It's supposed to be a way to get more captoxin out of the meat, and give chefs something to do.
If microwave availability is an issue, map some more in...

**Comment by Wickedtemp** [comment]
Why would you have a pizza party with frozen pizza. Like... This isn't even about the PR, but now I'm genuinely concerned that Ace has never had an actual pizza party.

**Comment by SpadesNeil** [comment]
>Why would you have a pizza party with frozen pizza.

thatisntwhatisaid

**Comment by Wickedtemp** [comment]
I mean you did, but... okay https://gyazo.com/a6244b0172951b589aad707598f2f12f

Like...wasn't saying you were eating it still frozen. That's just plain disgusting and against nature.

**Comment by SpadesNeil** [comment]
Well the pizza isn't frozen anymore if it's shoved in an oven, is it now? :T

**Comment by SpadesNeil** [comment]
Either way, the argument that you somehow can't have a pizza party with this new pizza is straight up the weakest argument for this yet.

**Comment by Wickedtemp** [comment]
Okay but promise me you'll have an actual pizza party at some point.

**Comment by TheDavestDave** [comment]
I say we force Ace to have a pizza party with us RL

**Pull request merged**
