### PR TITLE
Sync

### PR DESCRIPTION
**Pull request by Arokha**
Polaris Sync

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Discard the map changes for now and we'll fix the map problems in another pull. Make an issue about what needs changing on the map and assign me to handle it.

**Comment by Arokha** [comment]
I mean I can't merge this, because objects on our current map have items that were removed.

**Comment by SpadesNeil** [comment]
No I mean I understand that. I'll replace the map first, then we'll try pulling this in again without your map changes.

**Comment by SpadesNeil** [comment]
Include my gun update! :D

Anywhere the gun update conflicts, Polaris's version is preferable.

**Comment by SpadesNeil** [comment]
Psssst. We need dis done.

**Comment by Cameron653** [comment]
Going to close this and re-open it since travis is refusing to work.

**Pull request closed without merging**
