### PR TITLE
Exploration Update #3

### PR DESCRIPTION
**Pull request by Arokha**
It's that time again!
* Adds a third exploration mission: Virgo 2. Enjoy your vacation on a runaway greenhouse effect planet hellscape, including derelict aerostat for free.
* All shuttle destinations are now always loaded. Now you too can argue with your coworkers about what you should be doing and what the most important priorities are!
* Alien abduction is now a chance, rather than a shift's destination. If you get abducted, you can go back to the ship whenever, it's on the destination list from bluespace after that. You won't get stripped/teleported again (you don't know that ICly until you experience that, though).
* You can't start exploring for 45 minutes after the server loads. WAIT FOR YOUR COWORKERS. Don't be in such a rush at the start of each shift, gawed.
* Some mobs now don't process life() when nobody is on their z-level, to reduce lag.
* Increases Enjoyment Of Alien UFO For Our Synthetic Crew Members This Is Not Lying
* Adds two new mobs: jellies (like-likes from LoZ basically) and shadekin (WIP-ish for now, not mapped in).
* All mobs on away missions respawn, for the most part. You can deplete them, however, and make an area safe for other non-combat teams to come in and do stuff (or for the crew to enjoy the beach).

Includes a thing for mappers:
* The tether_away_spawner can spawn and track mobs, spawning them in easy ways, and handling some common things for you. Read _tether_submaps.dm for the definition or look in beach.dm for comments and how it's used.

### CODE REVIEW

**Comment by Very-Soft** [comment]
> You can't start exploring for 45 minutes after the server loads. WAIT FOR YOUR COWORKERS. Don't be in such a rush at the start of each shift, gawed.

yessssss

**Comment by KonBear** [comment]
Awesome~!

**Comment by Natje0** [comment]
I believe the Ion turrets should be reconsidered. Anyone with synthetic organs are going to be basically instamurdered by them, and it'll instantly cripple any Synths who get hit, or even just almost hit. And with 250hp too at that? It just sounds like a very bad idea after talking about it in Development.

**Comment by Arokha** [comment]
Swapped them for ion pistol turrets. But to be honest if you take an explorer team where every organic has a mechanical heart, or everyone is synthetic... then that's sorta just what you get.

**Pull request merged**
