### PR TITLE
i hate the engraving antichrist

### PR DESCRIPTION
**Pull request by Hatterhat**
to engrave things with sharp objects now you need to altclick the floor or wall, instead of "called every time you attack the floor on harm intent with a sharp object"

edit: also it engraves on help intent. still maintains altclick potential tho if you want

### CODE REVIEW

**Comment by FartMaster69420** [comment]
OH MY GOD YES

**Comment by Enzo-Leon** [comment]
JFC thank you.

**Comment by PastelPrinceDan** [comment]
the hero we needed

**Comment by Very-Soft** [comment]
As was discussed in dev chat, I'm on board with making this not be the default action for clicking floors with a sharp object since it's often disruptive, however, I am not convinced that putting it under alt click is the best option, because it is very unlikely that anyone unfamiliar with that will actually discover the function naturally.

I PERSONALLY would prefer if it only happened on help intent, or if there was a preference toggle (which defaulted to ON) to toggle whether your clicks did graffiti or not, that way it can still be stumbled upon, but prevented if you know what to do.

**Pull request merged**
