### PR TITLE
[MIRROR] Adds optional area-based definition for outdoors-ness

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/8155
--------------------
This is mostly for the new map, but it might be helpful to have now and outside of the map PR.

This essentially converts the `outdoors` var on turfs from a binary value to a ternary, with init values being able to be 'yes', 'no', and a new option, 'area', which makes it outdoors or indoors based on what the area wants it to be, with a newly added value that can hold a 'yes' or 'no'.

The advantage is that this helps avoid ten thousand `/outdoors` subtypes for turfs (tho that ship has kinda sailed, but we can now get rid of those types and replace with the base one instead). It also helps avoid bugs with single turfs that are indoors when they're intended to be outdoors (or the other way around). It also helps cut down on map overrided turfs to set `outdoors` to 0 or 1.

It should be noted the turfs themselves have the final say on whether or not they're outdoors. If the value is 'yes' or 'no', the area's value is irrelevant. Also, the 'yes' value is 1, and the 'no' value is 0, which mirrors the binary system and thus this should be backwards compatible with current maps.

By default, turfs defer to the area. Also by default, areas default to being indoors. This is done since the majority of areas are indoors. Most outdoor areas are under a general outdoor area anyways, so it's easy to apply it.

### CODE REVIEW

**Comment by Arokha** [comment]
Neerti said there's a mistake in this PR, waiting on a fix

**Comment by Novacat** [comment]
Is https://github.com/VOREStation/VOREStation/pull/11228 the fix?

**Comment by Arokha** [comment]
> Is #11228 the fix?

Yes, I'm going to cherrypick it into this PR and close that one

**Comment by Arokha** [comment]
Tested, rain and light stay outdoors, seems ok.

**Pull request merged**
