### PR TITLE
Jesse Soemmer - LeMat Fluff Item and Permit.

### PR DESCRIPTION
**Pull request by HzDonut**
Approved, worked fine when I tested it just a few hours ago (shoots .38, spins, can't load shotgun shells, no secondary barrel related verbs available). Just need a holster added to my holdout (waist). Tried to look through the fluff code to find an example of it to work off of, couldn't find it. Just pushing what's done and working through now instead of keeping it held back.

### CODE REVIEW

**Comment by HzDonut** [comment]
https://forum.vore-station.net/viewtopic.php?f=27&t=1243

**Comment by SilencedMP5A5** [comment]
...didn't HzDonut leave or something?

**Comment by Arokha** [comment]
User appears to have left

**Comment by KasparoVy** [comment]
:door: 🏃

**Pull request closed without merging**
