### PR TITLE
[MIRROR] Fixes personal ownership of cats

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/5713
--------------------
So, personal fluff cats are supposed to have a friend_name var where only that named character can be befriended, but, that var is not checked anywhere in the become_friends verb. This should fix that, I hope.

### CODE REVIEW

**Comment by Novacat** [comment]
VOREStation\code\modules\mob\living\simple_animal\animals\cat_vr.dm requires that var/ is removed from the friend_name var. That will get this to compile.

**Comment by SpadesNeil** [comment]
Need to fix some conflicts that were caused by the AI merge.

**Comment by Sebbe9123** [comment]
Should be a simple fix

**Comment by Sebbe9123** [comment]
Looked through the code and this branch is missing all of the Simple_mob stuff and it's goal it to add to a redundant and unused old system we _just_ stopped using now so I think we can ignore this one.

**Pull request closed without merging**
