### PR TITLE
Adding 2 new sergal hairstyles

### PR DESCRIPTION
**Pull request by saysage**
A bit of experiment for me, made 2 new sergal hairstyles as they really lack those.

### CODE REVIEW

**Comment by Verkister** [comment]
It is important to make sure your sprite files are up to date before making the edits. There has been two updates to these files after october 13. and you probably don't wish to override those with a file outdated by months.

**Comment by saysage** [comment]
Oh, crap. Seems that I really am bad with git if I did not understand how to get my fork updated. Can you explain it?

**Comment by Verkister** [comment]
I've only done it on desktop tortoisegit but i think it probably works sorta similarly in general. My way just needs to find "pull" or something from folder rightclick menus and to do it from the url of the main repository instead of your fork https://i.gyazo.com/3d9bc4557301a55505d2eb3a7f5d6368.png

**Comment by SpadesNeil** [comment]
Conflict aaaaaaaaaaa

**Comment by SpadesNeil** [comment]
This cannot be merged until the conflict is resolved. Also can we get pictures of the new sprites?

**Comment by Arokha** [comment]
Re-open this if you resolve the conflict. Closing due to inactivity.

**Pull request closed without merging**
