### PR TITLE
More chubby oties

### PR DESCRIPTION
**Pull request by Verkister**
- Adds chubby variants for phoron, red, and sec red oties.
- Also adds vested versions for direwolf and dog.

### CODE REVIEW

**Comment by Iroquois-Pliskin** [comment]
A: Okay but why add these? Is it meant for a meme? Why make those variants for every type?
B: Why the changes to the descriptions for existing Otie types? You didn't even include that in the pr description

**Comment by pontifexminimus2** [comment]
Neither of these questions really matter.

They're oties that are fat. It makes sense to make a subtype called "chubby". The variants exists for various fat dogs.

Changing the description minorly of barely seen simple mobs sounds also like a non-issue.

Are you picking a fight over something you're not invested in either way?
Is this how you should spend your time. Really.

**Comment by nerdass** [comment]
MORE SAUSAGES

**Comment by Iroquois-Pliskin** [comment]
> Are you picking a fight over something you're not invested in either way?
> Is this how you should spend your time. Really.



I'm actually mildly peeved that this is just a changelog that doesn't even include all the changes in the pr.

**Comment by Novacat** [comment]
A description change is something fairly minor, and, more than likely was forgotten about rather than intentionally left out.

**Pull request merged**
