### PR TITLE
August Release

### PR DESCRIPTION
**Pull request by Cameron653**
Merge this after the Polaris Sync.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Hold off on this as I am trying to add in some map fixes last minute.

**Comment by Ketrai** [comment]
Hey spades, whilst lookin into map fixes. there is a door on base level 3, near the science desk that's a science door for no reason. it leads into a maintance section which has a normal maintenance door on the other side. need science to even open this door so, it's pretty silly.

**Comment by SpadesNeil** [comment]
Screenshot please.

**Comment by Ketrai** [comment]
Give me a second, I'll have it here in a minute

**Comment by Ketrai** [comment]
http://imgur.com/a/G2vAf

**Comment by Jakksergal** [comment]
Please dear god don't make me try to solve conflicts again.

**Comment by Cameron653** [comment]
@Jakksergal Your map is already merged, dork.

**Pull request merged**
