### PR TITLE
Removes gnomes from trash piles

### PR DESCRIPTION
**Pull request by Novacat**
image

This is why we cannot have nice things.

### CODE REVIEW

**Comment by Iroquois-Pliskin** [comment]
Damn, that took no time at all. Can't say I blame you guys though.

**Comment by KasparoVy** [comment]
Lmao, I missed all the memes. WTF even happened hahaha

**Comment by Ketrai** [comment]
Well you chose to make them more obnoxious than they were. This is like the xenobotanist planting alcohol fruit everywhere except these make a sound effect now :v. GJ.

**Comment by Ketrai** [comment]
1. remove the sound effect because gods why was that added in the first place. 2. lower endurance or something to avoid wirecutter abuse. 3. change the product from 2 to 1. Would make it hell of a lot less spammable.

**Comment by Ketrai** [comment]
Oh my GOD, I just read through the pr adding the sounds and it literally plays just for digesting magic dust. So you could just grind down a ludicrous amount of gnomes, force feed someone a dust pill, and have them HOOH for days to come.

**Comment by SpadesNeil** [comment]
This is still hysterical.

**Comment by Novacat** [comment]
Ketrai, you are free to put up a PR to improve the balance of gnomes, but for now going to keep these things adminbus only.

**Comment by Haery70** [comment]
Hooh!

**Comment by Ketrai** [comment]
> Ketrai, you are free to put up a PR to improve the balance of gnomes, but for now going to keep these things adminbus only.

https://github.com/Yawn-Wider/YWPolarisVore/pull/458

I did, downstream. You're free to port it but I'm not gonna bother with "fixing" gnomes any other way, considering it's been dragged through the mud from its original purpose, and turned into a meme.

**Comment by SpadesNeil** [comment]
You didn't want to make a meme but you did want to make a reference that could be interpreted in a variety of different ways. You brought this on yourself. What did you _expect_ to happen?

Also, I don't appreciate digs at my staff. Ergo, I kindly request for you to fuck off. Yawnstation seems to appreciate your efforts more than we do. I'm sure you'll find better company there.

image
image

**Pull request merged**
