### PR TITLE
Remaps entirety of Medbay

### PR DESCRIPTION
**Pull request by Heroman3003**
Featuring a brand new layout, with mostly similar shape of primary rooms, but much more sanity in the positioning they have relative to each other. Also, additional exits via EMT bay and lower level hallway.

Of minor new features for the new medbay:

Blood-Onator, vendor for bloodpacks instead of them being stashed in freezers all over medbay (the freezers in surgeries still have prepared packs of O- though)

Tweeter, a little bird for a small flowery enclosure near psych office, for patients to relax looking at

Reverse sleepers/scanners are now a thing, and a thing that acctually works

Screenshots (in Editor):
Asteroid 3

Asteroid 2

Screenshots (in Game, dont mind missing lightswitches, already added):

Lower Entrance, Psych, Morgue, Surgery, Resleeving

Exam Room, Recovery Ward, Lower Scanner

Lower Storage, Patient Rooms

Chemistry, Lobby, EMT Bay

Treatment Center

CMO Office, Patient Rooms

Upper Storage, Break Room

Virology

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Maybe add a door opening button for the exit/waiting room on A2, leading outwards from the recovery room. Like with main doors in the ETC.

**Comment by Screemonster** [comment]
You know what I don't like about every medbay since northern star?

Every single one, the room with the scanners and sleepers is _also_ a thoroughfare. There's no way to get from reception into the deeper parts of the department without having to walk _through_ the active treatment area.

**Comment by Heroman3003** [comment]
Well, its for a practical reason though. 90% of the time, person coming in will be scanned/administered treatment right there and then before either being let go or moved deeper in. And regardless of that, the  secondary entrance/exit/waiting room should hopefully alleviate that a bit, with traffic being more of one-directional

**Comment by Novacat** [comment]
The nanopaste issue should probably be brought up in a seperate PR, since medical already starts with nanopaste. Merging this so that other mapping projects on station 2-3 can happen.

**Pull request merged**
