### PR TITLE
Colorable Collar/Choker Accessory

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Just a little accessory I felt was missing; a *colorable* collar/choker accessory, using the same system as the colorable cloak. Doesn't have a hanging tag like regular collars and can't be nametagged.

Explicitly left vague, so people can fluff it up however they see fit in character descriptions. Simple pet collar? Ok. Black lace choker? Sure! Whatever floats your boat.

Could maybe add a proc that lets people specify the material/name from fixed lists when using it in-hand or during character setup?

### CODE REVIEW

**Comment by KillianKirilenko** [comment]
No fuckin' clue how to set up customization in the loadout menu, but I figured out how to add one-shot customization where it prompts you to pick from a list of descriptors (e.g. plain, ornate), a list of materials (e.g. lace, leather, silver), and a short list of types (choker, collar, necklace).

Once customized you can't change it again, but you can use it as a stand-in for pretty much anything.

**Comment by KasparoVy** [comment]
@KillianKirilenko Aurora has name/description customization for a lot of their loadout items, it might be best to reference their code

**Comment by KillianKirilenko** [comment]
Thanks, I'll take a peek at some point.

**Comment by KasparoVy** [comment]
NP! They just recently refactored how 'gear tweaks' (eg. colouration + naming/description) works but it should still be relatively similar

**Comment by KillianKirilenko** [comment]
I think I see how they've done it, but it's a little more fiddly than I feel like wrestling with right now, especially as I wouldn't want to make it specific to just this item.

Not gonna work on it for now, but maybe in the future.

**Comment by KillianKirilenko** [comment]
travis froze/broke and needs to be rerun at some point

**Pull request merged**
