### PR TITLE
Update Pref Options

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Swaps the positional options to role options. Adds -pref subtypes as well to match the primary options.

### CODE REVIEW

**Comment by KillianKirilenko** [comment]
There's already a sanitize function, so worst-case it should just reset people to Unset/No ERP.

**Comment by TankTheBirb** [comment]
Having more specificity in existing categories isn't a bad idea. Although I personally would prefer using dominant/submissive, doesn't this change the option from preferred sexual positions to power dynamic positions?

**Comment by KillianKirilenko** [comment]
> Having more specificity in existing categories isn't a bad idea. Although I personally would prefer using dominant/submissive, doesn't this change the option from preferred partner positions to power dynamic positions?

Yes? That's what the first sentence of the PR says?

I could've added a new column but last I heard staff doesn't want it having too much info "up front".

**Comment by Heroman3003** [comment]
Note to self: include this change in announcement when talking about Loadout Overhaul too

**Review by Heroman3003 — APPROVED** [review]

**Pull request merged**
