### PR TITLE
Voxy port from Paradise (not 100% perfection, but)

### PR DESCRIPTION
**Pull request by Yatiyaya**
Ports over the sprites used on paradise for vox (Of course, tinkering on both sides will be needed to be made to finalize everything squarely away,
But, it does open vox up to a lot more uniforms/suits/helmets/etc currently)

### CODE REVIEW

**Review by Novacat — COMMENTED** [review]
Seems fine but I cannot review this in depth without IconDiff and from what I heard we are still waiting on approval for IconDiff2.

**Comment by Yatiyaya** [comment]
I did what I could to ensure whatever 'was' available was added, without taking away what we currently had in place, so it was only additions (with deletions of duplicates)

**Comment by Heroman3003** [comment]
Please provide screenshots of whatever it is that was added. Icondiff2 is still in waiting, so we have no way of properly reviewing what icons and such are being added.

**Comment by Yatiyaya** [comment]
UNiforms:
https://gyazo.com/f5724b3bb85d4749f63312f4fc2aa712
https://gyazo.com/58f96628c06f5fa8473a262e1482e584
https://gyazo.com/a36f8260993d3ad1687960f658a8f201
https://gyazo.com/507e880bb7e91a47dbba58bb4b8074bd

SUits:
https://gyazo.com/0cbd8aa23bfb35a5cd230a9fa36c72d7
https://gyazo.com/33cfeac39eac041aca75615f1b010465
https://gyazo.com/854517dbd6a5fa495d20b83e3e4f97bb
https://gyazo.com/524a29fb4724ef5b2148a618d4c2ebcf
https://gyazo.com/32ba6f965e356f48c8b46ada97208a3c

HEad:
https://gyazo.com/33f7a4d585227b0ece699f36696f9b2f
https://gyazo.com/b3f52b9898262826ee4fdcd75a610c8f
https://gyazo.com/a7ed23db1cfb6ee316e81ec43dcfee8d

HAnds:
https://gyazo.com/25f9d4a707dccc062ef2c596e5a64f7e

FEet:
https://gyazo.com/0d5ed6855ceda1fd5fc7593e61fda7b2

FAce:
https://gyazo.com/9b36b8448e47f6b576d5f6a7ff4458e6
https://gyazo.com/ddafda512d5171edf268032b71d2b5e7

EYes:
https://gyazo.com/60aa18ce625e85333d32bfc7dd0a45ec

**Comment by Yatiyaya** [comment]
The other two files (back and ears) require more work due to them having either limited or no decent analogues

**Comment by Heroman3003** [comment]
I see the point. I'll mark it approved since its just making vox compatible with more clothes. Just do note to post examples of what you do for the foreseeable future.

**Pull request merged**
