### PR TITLE
Synth colorable option

### PR DESCRIPTION
**Pull request by shazbot194**
Hello, so this is my first PR here. This PR gives you an option to use your body color to color synth parts. This can be enabled and disabled. It also adds in one set of synth parts and one set of heads, the Xion whiteout seriers. These include the default Xion parts and the Breacher helmet, all painted white and made ready to be painted other colors.

My little snowflake with the new Xion parts, showing the interface.
oacgcbsvshcvykupc3zvwa
bwbtbkwjsa2chzfelxhkfw

Another example of it being on and off
c-7icr_kt6ao54ombihwpw
-a6kzfw9rnkveej9fe6vng

If you have any concerns, I am more then happy to change the code or answer questions.

### CODE REVIEW

**Comment by shazbot194** [comment]
After some testing and trying, my method here will not work on Polaris, but I can get a similar system up there if requested.

**Comment by SpadesNeil** [comment]
`icons/mob/human_races/cyberlimbs/xion/xion_alt3.dmi` and `icons/mob/human_races/cyberlimbs/xion/xion_alt4.dmi`, are these default Polaris icons or are they Vorestation? If they are vorestation, they should have _vr and not _alt in the file path.

**Comment by shazbot194** [comment]
They are new vore station ones, but I will be closing this PR here shortly due to making a better version for Polaris. I am just testing to make sure the code works for both Vore and Polaris before I do.

**Comment by shazbot194** [comment]
Closing due to a better PR being made by me for Polaris:
https://github.com/PolarisSS13/Polaris/pull/4080

**Pull request closed without merging**
