### PR TITLE
Lore fixes I forgot (unconflicting)

### PR DESCRIPTION
**Pull request by SpadesNeil**

### CODE REVIEW

**Comment by Arokha** [comment]
image
image
image

**Comment by SpadesNeil** [comment]
image
:thinking:

**Comment by Arokha** [comment]
We should not make a habit of squash merging things, in fact I have it turned off most of the time.

**Comment by SpadesNeil** [comment]
No I just didn't know how to do this. Also I don't know why it's turned on for me. I'm pretty sure it breaks things.

**Comment by SpadesNeil** [comment]
Ignore the continued commits while I figure this out.

**Comment by Arokha** [comment]
Superceded by #3469

**Pull request closed without merging**
