### PR TITLE
fix gun handle_suicide

### PR DESCRIPTION
**Pull request by FelixRuin**
well... idk 
now suicide with gun have sound
and you cant suicide with gun who dont do damage (like sizegun or ML3M)

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Oh good, we won't need those warning labels anymore.

Probably should send this to Polaris.

**Comment by Screemonster** [comment]
As hilarious as it was for people to shrink (or grow) their heads until death, this is probably a good fix.

**Comment by FelixRuin** [comment]
well, like this? https://github.com/PolarisSS13/Polaris/pull/6462 really dont know

**Comment by Novacat** [comment]
Yeah that works fine. Since this got sent to polaris, merging.

**Pull request merged**
