### PR TITLE
ERT & Mercenary Ship Remodels

### PR DESCRIPTION
**Pull request by KillianKirilenko**
@Novacat asked me to look into this, so I'm remodelling the ERT ship into a fully-fledged overmap-flight ship with its own deployment shuttle. ERT teams will soon be deployed from the NRV Von Braun via the NRB Robineau.

I was instructed to *"go nuts"*, so that's exactly what I've done. Below is a slightly outdated version of outfitting/prep and the 'bridge':
image

Current version can be viewed on the Checks page under mapbot assuming it doesn't bug out. Comments/thoughts/feedback on the kind of equipment needed for the ERT is very welcome. The weapons and armor selection is already very wide and covers pretty much every base imaginable (with some old redundancies stripped out too), but the medical outfitting room might need some work.

Seating layout on the Robineau is up for discussion and may change before release.

todo
- [x] Full overmap flight capabilities + testing thereof
- [x] Shuttle docking tests
- [x] Commander's Quarters
- [x] Engineering
- [x] Atmospherics & Power setup
- [x] Areas
- [x] Airlocks
- [x] External Defenses (anti-meteor/anti-boarding turrets)

### CODE REVIEW

**Review by Novacat — CHANGES_REQUESTED** [review]
A couple of things.

- ERT should not have any mechs available to them, they are more of a national guard/militia. Their equipment should be the same as the one found on the current ERT ship.

- On the other hand, there should be a section of the ship, heavily armored and reinforced, that contains the deathsquad armory that is locked behind blast doors. A good example of this can be found in the old centcomm in the admin_use folder. Deathsquad having mechs is fine.

**Comment by KillianKirilenko** [comment]
The hull won't get much more heavily armored and reinforced than durasteel plate and plastitanium glass windows (besides making it thicker, I guess, which I'll be doing once the overall outline is finalized).

Armory has been split into Standard (SMGs, eguns, holdout eguns, nonlethal grenades, tasers, shotguns, netguns, stun batons, ion guns, low-yield EMP nades) and Delta (all the fun stuff: LMGs, ARs with extended mags, burst/scatter/xray lasers, etc. etc.). Likewise the mech portion of the mech/RIG bay has been isolated.

This'll help keep overall size/redundancy down. Hopefully.

**Comment by KillianKirilenko** [comment]
image

Ready for flight/nav tests.

**Comment by KillianKirilenko** [comment]
Engines are giving me some grief and not actually starting up properly when ordered to, so overmap flight is currently a no-go, but otherwise everything is functioning perfectly.

Even the landing craft:
image

**Comment by KillianKirilenko** [comment]
All flight tests have cleared; all that needs doing is for staff to sign off on the various equipment/outfitting supplies.

Note that once this is merged and put out to release, it will **immediately** replace the existing ERT shuttle in its entirety, with the following two caveats:
1. Players hoping to join the ERT *at any point* should familiarize themselves with the basics of overmap flight, as well as things like enabling the ship's engines.
2. Players hoping to join an ERT deployment should wait a few minutes before jumping in. The z-level takes a few moments to fully initialize, and mashing JOIN RESPONSE TEAM *may* cause you to spawn somewhere unexpected without proper equipment.

**Review by Novacat — CHANGES_REQUESTED** [review]
The materials should probably be downgraded to just regular reinforced steel/reinforced glass, similar to the NDV Daedalus (cruiser.dmm)

The forcefield in the middle makes me nervous. If meteors get through that it could be very bad. I would replace it with permanently shut blast doors, and perhaps a linear shield a few meters in front of it to catch any wayward meteors.

**Comment by KillianKirilenko** [comment]
It is a bit of a 'roidcatcher, I'll admit. I've switched the hangar doors to sealed by default and deleted the button. Standard shield generators won't cut it as their max range is 8 tiles, but I've added a couple extra point defense lasers. As long as the shields are up (and the precharged generator is on the bridge so it's impossible to miss) and the ERT don't insist on flying through six asteroid fields at the speed of plaid, they should be fine.

Hull has been switched to rsteel with rwindows. I wasn't sold on the durasteel in the first place just based on the color of it.

**Comment by KillianKirilenko** [comment]
Now includes the 'Manta' Mercenary Cruiser, for all your syndicate needs. I haven't determined exactly how the zlevel is picked/added for gamemode stuff so I'm not sure how it would work in practice, but as far as debug tab manual loading for events goes it works great.

Of course, small problem is that there's no stealth system for the boarding craft like the regular syndishuttle, since it seems like Aro or whoever originally coded overmap flight didn't incorporate that functionality into non-web/non-multi shuttles.

**Pull request merged**
