### PR TITLE
Adds in taur specific void/rigsuits

### PR DESCRIPTION
**Pull request by Cameron653**
# Sprites created by SilencedMP5A5
## Special thanks to Nightwing for helping me get this working when I ran into a brick wall.

Adds in:
- New rigsuit sprites for horse taurs, naga taurs, and wolf taurs
- New voidsuit sprites for horse taurs, naga taurs, and wolf taurs
- New voidsuits for taurs only 
(The voidsuits are listed as /taur. They need to be mapped into eva for them to be accessible without admin abuse)

If someone else without a taur/a different taur goes to wear rigsuit/voidsuit someone previously wore it'll change to fit their taur/non-taur body. Pretty neat!

PHOTOS:
Wolf (engineering) https://puu.sh/qQxKt/eebf275f54.png
Naga+Horse (engineering) https://puu.sh/qQBkC/b283c925d5.png
(Security) https://puu.sh/qQBav/9335d4218a.png
(Syndicate) https://puu.sh/qQByk/4f3573531e.png
(Mining) https://puu.sh/qQBIv/5b00b913a3.png
(Atmos) https://puu.sh/qQBQG/b079af5188.png
(Medical) https://puu.sh/qQBpG/3908479dbc.png
(Security Rigsuit) https://puu.sh/qQCvn/ce1cd988b6.png
(Mining Rigsuit) https://puu.sh/qQCTT/cd55e70528.png
(CE Rigsuit)  (Error taur is from debugging, pic below of sprite.) https://puu.sh/qQDlt/4c8951b962.png
Horse facing east (CE Rigsuit) https://puu.sh/qQEjS/569c849147.png
All three taurs (Xenoarch Rigsuit) https://puu.sh/qQDJk/877c6f7d95.png
All three taurs (Medical Hardsuit) https://puu.sh/qQE91/8331747684.png

Minor bug: When the rigsuit is first sealed, it'll revert back to the original sprite (Due to how rigsuit code works.) This can be simply fixed by toggling and untoggling the chestpiece part. Two clicks and it'll work for the rest of its use.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
https://puu.sh/qQDlt/4c8951b962.png This one appears bork in your screenshot.

**Comment by Cameron653** [comment]
Yeah, I mentioned that in note next to the link. It was when I was debugging a few things. The correct sprite image is below it.

**Comment by SpadesNeil** [comment]
Ah, ok. I missed it.

**Comment by SpadesNeil** [comment]
Polaris has been adding different skins for voidsuits. This should be updated at some point to accommodate these changes or else it might look funny.

**Pull request merged**
