### PR TITLE
Holocollar Addition to Autolathe 

### PR DESCRIPTION
**Pull request by TheFurryFeline**
Ports from ChompStation an addition to the Autolathe: Holocollars at no apparent cost in materials.

### CODE REVIEW

**Comment by Screemonster** [comment]
wait, so they just spawn with literally zero cost? Even if it's a _small_ material cost the autolathe shouldn't be able to generate anything out of literally nothing.

**Comment by KasparoVy** [comment]
And for my next trick...

**Comment by Heroman3003** [comment]
I agree with @Screemonster on that one, since currently only one item in autolathe uniquely costs nothing and thats autoinjector, a one-use item.

**Comment by TheFurryFeline** [comment]
Yeah, @Screemonster. Gonna close this and do a proper thing. I overlooked something when porting this.

**Pull request closed without merging**
