### PR TITLE
Quick Underground hotsprings fix

### PR DESCRIPTION
**Pull request by Rick4242**
Adds a layer of impassable rock around the outside of the eggnoggtown hotsprings to prevent it from being broken into and being exposed to colder air. 
(Also the hotsprings 'area' is completely filled in now)

### CODE REVIEW

**Comment by Heroman3003** [comment]
I'm not entirely sure thats anything that needs fixing.

**Comment by Rick4242** [comment]
Ack- meant for that fix to be made in a different PR, whoops.

**Comment by Heroman3003** [comment]
There's conflicts and this 'fix' isnt really fixing any real issues. Closing for now.

**Comment by Rick4242** [comment]
Unsure if I may come back to this later or something, kind of left it alone and forgot about it for some time.

**Pull request closed without merging**
