### PR TITLE
Talon guality of life map changes

### PR DESCRIPTION
**Pull request by Sinbest**
Minor changes to the Talon for quality of life reasons.

image
Added tables to the bridge so you have somewhere to put printouts

image
Organized the armory and voidsuit storage

That's all.

### CODE REVIEW

**Comment by Very-Soft** [comment]
Let's not stealth buff the talon's armory, please. 

Before
7 weapon cells
2 energy net gun
1 energy gun

After
13 weapon cells (+6) +1 in the guard's cabin
1 energy net gun (-1)
2 energy guns (+1)
5 leg holsters (+5)

Also counting the burst laser and the 2 holdouts, that puts the Talon at a total of 5 lethal weapons, 3 of which can be used on the main station, which makes me think that you think the talon is supposed to be the exploration team.

It's not. The talon is rarely fully crewed, and even when it is, not everyone actually needs a lethal weapon to rummage in caves and/or do trading RP, and if you want the whole team to have lethal weapons, there's ways to do that in the round. And the entire team certainly doesn't need extra pistol storage, or double the ammo.

Any balance changes should be clearly stated up front. As is, it looks like you're trying to sneak stuff in, and I am not feeling that kind of breach of trust, and I would really rather not have to super scrutinize everything you do.

**Review by Very-Soft — CHANGES_REQUESTED** [review]
Let's not stealth buff the talon's armory, please.

Before
7 weapon cells
2 energy net gun
1 energy gun

After
13 weapon cells (+6) ((+1 in the guard's cabin for a total of 14))
1 energy net gun (-1)
2 energy guns (+1)
5 leg holsters (+5)

Also counting the burst laser and the 2 holdouts, that puts the Talon at a total of 5 lethal weapons, 3 of which can be used on the main station, which makes me think that you think the talon is supposed to be the exploration team.

It's not. The talon is rarely fully crewed, and even when it is, not everyone actually needs a lethal weapon to rummage in caves and/or do trading RP, and if you want the whole team to have lethal weapons, there's ways to do that in the round. And the entire team certainly doesn't need extra pistol storage, or double the ammo.

Any balance changes should be clearly stated up front. As is, it looks like you're trying to sneak stuff in, and I am not feeling that kind of breach of trust, and I would really rather not have to super scrutinize everything you do.

**Comment by KillianKirilenko** [comment]
fwiw, I made the storage and armoury intentionally quite messy, to give it a more 'lived in'/less 'professional' feeling.

Tables are good though, I knew there was something I was overlooking. I'd move the vents up a bit so they're under the tables though, rather than under the chairs.

**Comment by Sinbest** [comment]
> Any balance changes should be clearly stated up front. As is, it looks like you're trying to sneak stuff in, and I am not feeling that kind of breach of trust, and I would really rather not have to super scrutinize everything you do.

Ah, I didn't realize I was buffing it so much, sorry I'm new to devving in general.

**Comment by Sinbest** [comment]
I've removed the extra ammo and energy gun, armory shouldn't be buffed anymore.

**Pull request closed without merging**
