### PR TITLE
Fixes inconsistant material refunds and removes material cost from door repair

### PR DESCRIPTION
**Pull request by ReoDaProtovali**
Started out with me fixing improper material refunds on deconstructs, ended with me making doors not cost materials. Oops! 
 
 This PR pretty much just fixes a few common issues with deconstruction not refunding the amount of resources used to build them, and obviously (probably) doesnt get all of them, but should help in a lot of common situations that involve repairs, usually after meteor strikes or engineering projects. 
 It also removes the sheet repair requirement from doors, because it just results in doors either being never repaired, or repaired via deconstructing the door and then rebuilding it, both scenarios which avoid the mechanic entirely.

### CODE REVIEW

**Comment by ReoDaProtovali** [comment]
why's it failing the integration test?-

**Comment by ItsSelis** [comment]
<details>

<summary>Excerpt from the Integration Tests Details</summary>

```
Initializing objects
[2023-11-10T17:18:21] Runtime in _sheets.dm,53: Cannot read null.sheet_singular_name
  proc name: update strings (/obj/item/stack/material/proc/update_strings)
  src: the solid phoron (/obj/item/stack/material/phoron)
  src.loc: null
  call stack:
  the solid phoron (/obj/item/stack/material/phoron): update strings()
  the solid phoron (/obj/item/stack/material/phoron): use(1)
  the solid phoron (/obj/item/stack/material/phoron): merge(the phoron crystal (/obj/item/stack/material/phoron))
  the solid phoron (/obj/item/stack/material/phoron): Initialize(1, null)
  the solid phoron (/obj/item/stack/material/phoron): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the solid phoron (/obj/item/stack/material/phoron), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(62[293](https://github.com/VOREStation/VOREStation/actions/runs/6818404283/job/18570486938?pr=15511#step:6:294)5)
  Master (/datum/controller/master): Initialize(10, 0, 1)
[2023-11-10T17:18:21] Runtime in _sheets.dm,53: Cannot read null.sheet_singular_name
  proc name: update strings (/obj/item/stack/material/proc/update_strings)
  src: the solid phoron (/obj/item/stack/material/phoron)
  src.loc: null
  call stack:
  the solid phoron (/obj/item/stack/material/phoron): update strings()
  the solid phoron (/obj/item/stack/material/phoron): use(1)
  the solid phoron (/obj/item/stack/material/phoron): merge(the phoron crystal (/obj/item/stack/material/phoron))
  the solid phoron (/obj/item/stack/material/phoron): Initialize(1, null)
  the solid phoron (/obj/item/stack/material/phoron): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the solid phoron (/obj/item/stack/material/phoron), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(622935)
  Master (/datum/controller/master): Initialize(10, 0, 1)
[2023-11-10T17:18:21] Runtime in _sheets.dm,53: Cannot read null.sheet_singular_name
  proc name: update strings (/obj/item/stack/material/proc/update_strings)
  src: the solid phoron (/obj/item/stack/material/phoron)
  src.loc: null
  call stack:
  the solid phoron (/obj/item/stack/material/phoron): update strings()
  the solid phoron (/obj/item/stack/material/phoron): use(1)
  the solid phoron (/obj/item/stack/material/phoron): merge(the phoron crystal (/obj/item/stack/material/phoron))
  the solid phoron (/obj/item/stack/material/phoron): Initialize(1, null)
  the solid phoron (/obj/item/stack/material/phoron): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the solid phoron (/obj/item/stack/material/phoron), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(622935)
  Master (/datum/controller/master): Initialize(10, 0, 1)
[2023-11-10T17:18:21] Runtime in _sheets.dm,53: Cannot read null.sheet_singular_name
  proc name: update strings (/obj/item/stack/material/proc/update_strings)
  src: the solid phoron (/obj/item/stack/material/phoron)
  src.loc: null
  call stack:
  the solid phoron (/obj/item/stack/material/phoron): update strings()
  the solid phoron (/obj/item/stack/material/phoron): use(1)
  the solid phoron (/obj/item/stack/material/phoron): merge(the phoron crystal (/obj/item/stack/material/phoron))
  the solid phoron (/obj/item/stack/material/phoron): Initialize(1, null)
  the solid phoron (/obj/item/stack/material/phoron): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the solid phoron (/obj/item/stack/material/phoron), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(622935)
  Master (/datum/controller/master): Initialize(10, 0, 1)
## TESTING: Located sector "NRV Stellar Delight" at 2,2, containing Z 3, 2, and 1
## TESTING: Located sector "NTV Starstuff" at 38,48, containing Z nothing
## TESTING: Located sector "Virgo 3B" at 54,76, containing Z 4 and 6
## TESTING: Located sector "NTV Virgo Flyer" at 9,23, containing Z nothing
[2023-11-10T17:18:25] Runtime in _sheets.dm,53: Cannot read null.sheet_singular_name
  proc name: update strings (/obj/item/stack/material/proc/update_strings)
  src: the borosilicate glass (/obj/item/stack/material/glass/phoronglass)
  src.loc: null
  call stack:
  the borosilicate glass (/obj/item/stack/material/glass/phoronglass): update strings()
  the borosilicate glass (/obj/item/stack/material/glass/phoronglass): use(1)
  the borosilicate glass (/obj/item/stack/material/glass/phoronglass): merge(the borosilicate glass sheet (/obj/item/stack/material/glass/phoronglass))
  the borosilicate glass (/obj/item/stack/material/glass/phoronglass): Initialize(1, null)
  the borosilicate glass (/obj/item/stack/material/glass/phoronglass): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the borosilicate glass (/obj/item/stack/material/glass/phoronglass), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(622935)
  Master (/datum/controller/master): Initialize(10, 0, 1)
## TESTING: Located sector "Virgo 4" at 31,95, containing Z 7 and 8
## TESTING: Located sector "Virgo 2" at 4,91, containing Z 9 and 10
[2023-11-10T17:18:27] Runtime in _sheets.dm,53: Cannot read null.sheet_singular_name
  proc name: update strings (/obj/item/stack/material/proc/update_strings)
  src: the algae sheet (/obj/item/stack/material/algae)
  src.loc: null
  call stack:
  the algae sheet (/obj/item/stack/material/algae): update strings()
  the algae sheet (/obj/item/stack/material/algae): use(1)
  the algae sheet (/obj/item/stack/material/algae): merge(the algae sheet (/obj/item/stack/material/algae))
  the algae sheet (/obj/item/stack/material/algae): Initialize(1, null)
  the algae sheet (/obj/item/stack/material/algae): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the algae sheet (/obj/item/stack/material/algae), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(622935)
  Master (/datum/controller/master): Initialize(10, 0, 1)
[2023-11-10T17:18:27] Runtime in _sheets.dm,53: Cannot read null.sheet_singular_name
  proc name: update strings (/obj/item/stack/material/proc/update_strings)
  src: the algae sheet (/obj/item/stack/material/algae)
  src.loc: null
  call stack:
  the algae sheet (/obj/item/stack/material/algae): update strings()
  the algae sheet (/obj/item/stack/material/algae): use(1)
  the algae sheet (/obj/item/stack/material/algae): merge(the algae sheet (/obj/item/stack/material/algae))
  the algae sheet (/obj/item/stack/material/algae): Initialize(1, null)
  the algae sheet (/obj/item/stack/material/algae): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the algae sheet (/obj/item/stack/material/algae), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(622935)
  Master (/datum/controller/master): Initialize(10, 0, 1)
[2023-11-10T17:18:27] Runtime in _sheets.dm,53: Cannot read null.sheet_singular_name
  proc name: update strings (/obj/item/stack/material/proc/update_strings)
  src: the algae sheet (/obj/item/stack/material/algae)
  src.loc: null
  call stack:
  the algae sheet (/obj/item/stack/material/algae): update strings()
  the algae sheet (/obj/item/stack/material/algae): use(1)
  the algae sheet (/obj/item/stack/material/algae): merge(the algae sheet (/obj/item/stack/material/algae))
  the algae sheet (/obj/item/stack/material/algae): Initialize(1, null)
  the algae sheet (/obj/item/stack/material/algae): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the algae sheet (/obj/item/stack/material/algae), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(622935)
  Master (/datum/controller/master): Initialize(10, 0, 1)
[2023-11-10T17:18:27] Runtime in _sheets.dm,53: Cannot read null.sheet_singular_name
  proc name: update strings (/obj/item/stack/material/proc/update_strings)
  src: the algae sheet (/obj/item/stack/material/algae)
  src.loc: null
  call stack:
  the algae sheet (/obj/item/stack/material/algae): update strings()
  the algae sheet (/obj/item/stack/material/algae): use(1)
  the algae sheet (/obj/item/stack/material/algae): merge(the algae sheet (/obj/item/stack/material/algae))
  the algae sheet (/obj/item/stack/material/algae): Initialize(1, null)
  the algae sheet (/obj/item/stack/material/algae): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the algae sheet (/obj/item/stack/material/algae), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(622935)
  Master (/datum/controller/master): Initialize(10, 0, 1)
[2023-11-10T17:18:27] Runtime in _sheets.dm,53: Cannot read null.sheet_singular_name
  proc name: update strings (/obj/item/stack/material/proc/update_strings)
  src: the algae sheet (/obj/item/stack/material/algae)
  src.loc: null
  call stack:
  the algae sheet (/obj/item/stack/material/algae): update strings()
  the algae sheet (/obj/item/stack/material/algae): use(1)
  the algae sheet (/obj/item/stack/material/algae): merge(the algae sheet (/obj/item/stack/material/algae))
  the algae sheet (/obj/item/stack/material/algae): Initialize(1, null)
  the algae sheet (/obj/item/stack/material/algae): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the algae sheet (/obj/item/stack/material/algae), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(622935)
  Master (/datum/controller/master): Initialize(10, 0, 1)
  (This error will now be silenced for 10 minutes)
```

</details>

**Comment by ReoDaProtovali** [comment]
I dont think that error's my doing... I didnt even touch sheets.dm!

**Comment by ItsSelis** [comment]
You could try updating the branch from master to get the latest changes. Maybe there was a bug that could go away by doing so.

It is very strange indeed though.

**Comment by ReoDaProtovali** [comment]
it's still failing! what's going wrong though...

**Comment by Heroman3003** [comment]
This getting fixed?

**Comment by ReoDaProtovali** [comment]
some day... I forgot what was wrong again- something to do with inits getting a null

**Comment by Heroman3003** [comment]
Something still wrong.

**Comment by Heroman3003** [comment]
VOREstation Edit comments are not necessary btw

**Pull request merged**
