### PR TITLE
Replaces noodle with poly

### PR DESCRIPTION
**Pull request by Sebbe9123**
So, it's been long in the making, we all know how cute Noodle is etc blah blah blah. But it's about damn time we show some love to Poly, thee one, the only, BEST (engineering) PET!

### CODE REVIEW

**Comment by Very-Soft** [comment]
I'm very, very okay with this. I was pretty annoyed when people added a snake to engineering as its pet, when engineering already has a pet. :Y

**Comment by Heroman3003** [comment]
I dont really like it simply on account of Poly being extremely annoying with constant item movement and radio spam

**Comment by Very-Soft** [comment]
Pets have their own little coves now, so Poly wouldn't be able to move items around unless you let him out. And I'm pretty sure you can set him to not start with a headset.

**Comment by Sebbe9123** [comment]
> Pets have their own little coves now, so Poly wouldn't be able to move items around unless you let him out. And I'm pretty sure you can set him to not start with a headset.

You can also just yoink the headset

**Comment by Novacat** [comment]
Is it possible to give Poly a headset? If so, it might be better too start poly *without* the headset and let people give Poly a headset if they feel like having a parrot on comms.

**Comment by Very-Soft** [comment]
I'm pretty sure it's possible to give poly the headset, would need to test. But yeah, I think that would be ideal.

**Comment by Poojawa** [comment]
Him having a headset is literally the best part though

**Comment by Sebbe9123** [comment]
> Him having a headset is literally the best part though

I *can* give him an omni headset, and add lines of stuff you'd never want to hear in any department.

**Comment by Poojawa** [comment]
Nawh. he just needs an engineering headset. it's up to the CE to give 'em theirs

or the CD to give their radio key

**Comment by Sebbe9123** [comment]
> Nawh. he just needs an engineering headset. it's up to the CE to give 'em theirs
> 
> or the CD to give their radio key

Yep! all that's done.

I really don't wanna strip away Poly's radio as there's no real reason to do it, if ya want it gone just take it off, you're engineers damn you!

**Comment by Poojawa** [comment]
POLY

**Comment by Very-Soft** [comment]
I gotta agree with scree on that one. 

Thinking about it, if you start poly without a headset and give one to him, you're pretty invariably going to have people start screaming at you about it. 

Poly screeching about this or that now and then isn't actually really a bother imo and engineering is the main department I actually play. People are just big babies about some stuff.

**Comment by Very-Soft** [comment]
the last thing I want is a CD ordering a CE be arrested for abusing comms because they gave their bird a headset.

And you know that'll happen sooner or later if they can blame the CE for it.

**Comment by Novacat** [comment]
Feels like a 'Damned if you do, Damned if you do not' situation. If the birb starts with the headset, you are going to have people deadset into breaking into the CE's office every shift to remove it. If the birb starts without the headset, there is concerns that someone will try to have the CE arrested if someone gives Poly the headset.

**Comment by Very-Soft** [comment]
Imo it's kind of a 'deal with it' type of situation. Like, the bird's squaking doesn't actually do anything to inconvenience you. It doesn't do anything to hurt the effectiveness of engineering chat. It's really really easy to ignore if you don't like it, and there's IC solutions to dealing with it if it's really bothering you that much.

But like, I really don't think people will mind it quite as much as folk are making out right now. And like, if engineers make a habit of hacking into the CE's office and swiping poly's headset... so what?

I think it's a lot more likely that that'll happen at first, and then people will stop caring, because it's not actually a big deal if poly screams 'OH GOD ITS LOOSE' every once in a while.

**Comment by Heroman3003** [comment]
Idle and constant flooding of department channel is just a very annoying thing, especially in department where you really do want to stay on comms at all times, even during scenes in case of emergencies.

**Comment by Sebbe9123** [comment]
> Idle and constant flooding of department channel is just a very annoying thing, especially in department where you really do want to stay on comms at all times, even during scenes in case of emergencies.

Kinda moot example as your radio will always have stuff flooding in, poly saying something every 5 minutes or so will make no difference

**Comment by Poojawa** [comment]
he only ever talks on engineering radio with a engi headset

He'll yell randomly on other channels if he has access to them.

You have to have a station bounced or intercom for him to talk on common channels

**Comment by Rykka-Stormheart** [comment]
I approve, let Poly have a headset. I'm tired of the anti-fun people screaming about "BUT NOISE ON COMMS" as if General comms aren't just a constant spam of chatter.

**Comment by Screemonster** [comment]
and it's not like we don't have random air traffic control chatter on common all the time and everyone ignores it

**Pull request merged**
