### PR TITLE
Adds eastern dragon taur sprite

### PR DESCRIPTION
**Pull request by CubeJackal**
Two colour overlays. Fat + suit sprites coming probably never. Enjoy spaghetti. 

noodlegif

### CODE REVIEW

**Comment by KillianKirilenko** [comment]
Ah, fresh noodles. These are pretty good! Your own work?

**Comment by CubeJackal** [comment]
> Ah, fresh noodles. These are pretty good! Your own work?

Yes! I think they came out alright for my first sprite in five or so years.

**Comment by Heroman3003** [comment]
They look great!

**Comment by KillianKirilenko** [comment]
> > Ah, fresh noodles. These are pretty good! Your own work?
> 
> Yes! I think they came out alright for my first sprite in five or so years.

For that much time away? Absolutely.

**Comment by Skysteak** [comment]
Solid work!

**Pull request merged**
