### PR TITLE
B to Resist

### PR DESCRIPTION
**Pull request by Novacat**

### CODE REVIEW

**Comment by Greenjoe12345** [comment]
wouldn't this be better suited to go on polaris?

**Comment by Novacat** [comment]
https://github.com/PolarisSS13/Polaris/pull/8062

Already done.

**Comment by Greenjoe12345** [comment]
alrighty, cool

**Comment by Rykka-Stormheart** [comment]
B to blow

**Comment by TheFurryFeline** [comment]
> B to blow

Rykka, no! 🗞️

**Pull request merged**
