### PR TITLE
Adds taur specific voidsuits to areas

### PR DESCRIPTION
**Pull request by Cameron653**
- Adds taur specific voidsuits (Voidsuit helmet included) to areas

.
- One Security Taur specific voidsuit to Armory. 
- One Atmos Taur specific voidsuit to Engineering EVA 
- One Engineering Taur specific voidsuit to Engineering EVA
- One Atmos Taur specific voidsuit to EVA
- Two Security Taur specific voidsuit to EVA
- Two Medical Taur specific voidsuits to EVA

This is my first time adding something to the map. I think I got it right.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Looks like you did it right. Can we have screenshots, though?

**Comment by Cameron653** [comment]
Really nothing to screenshot, I just put the taur voidsuits ontop of where
the normal voidsuits spawn.

**Comment by Cameron653** [comment]
(Syndicate boxes represent where the taur hardsuits are placed)
http://puu.sh/rBhgG/e2086f9e84.png Engineering
http://puu.sh/rBhiy/aff94452a7.png EVA
http://puu.sh/rBhjE/bb90524361.png Armory

**Comment by SpadesNeil** [comment]
Labeled "Do not merge" just because of updates coming in https://github.com/VOREStation/VOREStation/pull/634

**Comment by Cameron653** [comment]
Alright. I'll fix it back up when #634 gets done

**Comment by Cameron653** [comment]
Going to close this and make another PR

**Pull request closed without merging**
