### PR TITLE
Make some NIF items apply wear only when used, and not when purchased.

### PR DESCRIPTION
**Pull request by lbnesquik**
## About this pull request
As the title says, really. I do note that the strongest modules (illegal ones) still have wear from installation.

## Why is this good for the game
It makes more sense to have your wear and tear come from usage rather than just downloading a program. That's it.

### CODE REVIEW

**Review by TheFurryFeline — COMMENTED** [review]
I have certain concerns about what'll happen if someone were to be put into stasis for a long duration or if this will just be a 1 stasis action = wear. With the latter scenario in mind, it's possible that someone could drift in and out for a while, which could rack up the usage rate.

**Comment by lbnesquik** [comment]
> 
> 
> I have certain concerns about what'll happen if someone were to be put into stasis for a long duration or if this will just be a 1 stasis action = wear. That said, it's possible that someone could drift in and out for a while, which could rack up the usage rate.

If that's too much of a concern, it could always be put simply on the activation rather than both activation and stasis.

**Comment by TheFurryFeline** [comment]
> > I have certain concerns about what'll happen if someone were to be put into stasis for a long duration or if this will just be a 1 stasis action = wear. That said, it's possible that someone could drift in and out for a while, which could rack up the usage rate.
> 
> If that's too much of a concern, it could always be put simply on the activation rather than both activation and stasis.

Would depend on the situation, really. I hardly play anymore but I remember a few times where I went into stasis for several minutes on end, drifting in and out of consciousness and getting whacked by an Underdark mob each time until it roamed out of view and I was able to get away after waking up one more time, lol.

**Comment by Heroman3003** [comment]
Size Alteration is now a dead program with this

**Comment by lbnesquik** [comment]
> 
> 
> > > I have certain concerns about what'll happen if someone were to be put into stasis for a long duration or if this will just be a 1 stasis action = wear. That said, it's possible that someone could drift in and out for a while, which could rack up the usage rate.
> > 
> > 
> > If that's too much of a concern, it could always be put simply on the activation rather than both activation and stasis.
> 
> Would depend on the situation, really. I hardly play anymore but I remember a few times where I went into stasis for several minutes on end, drifting in and out of consciousness and getting whacked by an Underdark mob each time until it roamed out of view and I was able to get away after waking up one more time, lol.

The wear level is certainly not enough to kill your NIF.  There is over 30 uses of medimachines if your nif is full health. Even if it has only 50 of integrity, you still have 16 individual occasions to get put into stasis. This is plenty of reserve.

**Comment by TheFurryFeline** [comment]
> > > > I have certain concerns about what'll happen if someone were to be put into stasis for a long duration or if this will just be a 1 stasis action = wear. That said, it's possible that someone could drift in and out for a while, which could rack up the usage rate.
> > > 
> > > 
> > > If that's too much of a concern, it could always be put simply on the activation rather than both activation and stasis.
> > 
> > 
> > Would depend on the situation, really. I hardly play anymore but I remember a few times where I went into stasis for several minutes on end, drifting in and out of consciousness and getting whacked by an Underdark mob each time until it roamed out of view and I was able to get away after waking up one more time, lol.
> 
> The wear level is certainly not enough to kill your NIF. There is over 30 uses of medimachines if your nif is full health. Even if it has only 50 of integrity, you still have 16 individual occasions to get put into stasis. This is plenty of reserve.

A'ight, that sounds fine then.

**Comment by Detective-Google** [comment]
Not a fan of having your NIF take damage every time you charge off an APC as a synthetic. Means youre going to have to hunt down a charger more often which defeats the point of the program

**Comment by lbnesquik** [comment]
> 
> 
> Not a fan of having your NIF take damage every time you charge off an APC as a synthetic. Means youre going to have to hunt down a charger more often which defeats the point of the program

It is one point of damage out of 100. You got plentyyyy of charges before you actually will need to head to an APC.

**Comment by Novacat** [comment]
On one hand, this will result in less NIF wear for people who only occasionally use NIFSofts. On the other hand, this will result in a lot more NIF wear for people who heavily use the NIFsofts. Controversial. Can result in situations where someone accidentally deletes their NIF because they used it too much in the heat of the moment.

That said, I am personally not a fan of automatically activating NIFSoft programs having use wear because unlike the above situation, the user has no control over it activating or not.

**Comment by lbnesquik** [comment]
I will return to this later on.

**Pull request closed without merging**
