### PR TITLE
On mob examine

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Allows you to examine things that other people are wearing by clicking on the name of that item when you examine them!

Closes #14000

### CODE REVIEW

**Comment by Heroman3003** [comment]
It *looks* good, assuming its been tested, so should prolly cause no issue.

**Review by Heroman3003 — APPROVED** [review]

**Comment by KillianKirilenko** [comment]
> It _looks_ good, assuming its been tested, so should prolly cause no issue.

Don't worry, I give 'em all a cursory test to make sure everything works as-intended, except for some of the really, *really* basic ones. I can confirm that it works fine locally.

There is one *minor* issue I've found with this one, and it's that it lets you see if someone has a concealed holster by examining their undersuit. Concealed holsters don't appear on a cursory `examine`, but do on a closer inspection. I don't really foresee that actually being a problem though, not unless someone is _desperately_ trying to get a redshirt in trouble to the point of wasting everyone's time with petty, bad-faith complaints.

**Comment by foopwo** [comment]
> > It _looks_ good, assuming its been tested, so should prolly cause no issue.
> 
> Don't worry, I give 'em all a cursory test to make sure everything works as-intended, except for some of the really, _really_ basic ones. I can confirm that it works fine locally.
> 
> There is one _minor_ issue I've found with this one, and it's that it lets you see if someone has a concealed holster by examining their undersuit (if they don't have an oversuit that conceals it entirely, like a voidsuit). Concealed holsters don't appear on a cursory `examine`, but do on a closer inspection. I don't really foresee that actually being a problem though, not unless someone is _desperately_ trying to get a redshirt in trouble to the point of wasting everyone's time with petty, bad-faith complaints.

As well as certain disguised traitory items that reveal themselves on examine, such as a voice changer.

**Comment by KillianKirilenko** [comment]
> As well as certain disguised traitory items that reveal themselves on examine, such as a voice changer.

Hmmm. That is _slightly_ more problematic, but I'm not sure how to tackle that one codewise. I want to file it under "probably not a problem" like the holster thing, because the items will appear to look like normal objects anyway? And antag items shouldn't come up too much?

If Shitcurity Officer gets all fussy and calls someone out for wearing a voicechanger mask they have no reason to be able to ID, I don't think much really changes. They're still pushing the "traitor items identification" rules and all.

**Comment by Heroman3003** [comment]
I'm personally of the opinion that for here, neither of those is really a problem.

**Pull request merged**
