### PR TITLE
[MIRROR] Adds pineapple pizza box

### PR DESCRIPTION
**Pull request by VirgoBot**
Original PR: https://github.com/PolarisSS13/Polaris/pull/6682
--------------------
Cargo pizza pack can now feature pineapple pizzas too.

Also adds random pizzabox object for use in mapping or similar cases.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
DELET THIS

**Comment by Very-Soft** [comment]
NO, THE ULTIMATE PIZZA IS HERE, IT IS TIME FOR WAR

**Comment by SpadesNeil** [comment]
### AAAAAAAAAAAAAAAAAA

**Comment by KasparoVy** [comment]
The hell were they thinkin, look what they've done to us

**Pull request merged**
