### PR TITLE
Victor zisthus/maptweaks

### PR DESCRIPTION
**Pull request by VictorZisthus**
Overhauled most doors with new access codes as a result of the code fixes intended to keep departments as pure as possible.

Other changes marked below.

(77,111,1) Added Intercom
(77,110,1) Changed Door Sprite
(43,60,1) Added Atmos Access
(105,32,1) Tider's greetings...
(99,79,1) Made this place look a little less empty.
(100,38,2) Set starting pressure to match other tanks.
(96,83,3) Tide Bait.
(94,41,8) WHO PUT A CHAIR IN THE ENGINES? Removed.
(32,68,8) Added fluff text

Added R-walling to Mining processing and Mining shuttle at Level 8

### CODE REVIEW

**Comment by KasparoVy** [comment]
> (94,41,8) WHO PUT A CHAIR IN THE ENGINES? Removed.

Lmfao, I'm just going to assume that was the one on the belter shuttle. Hilarious

**Comment by VictorZisthus** [comment]
ANGER.

**Comment by VictorZisthus** [comment]
I give up.

**Comment by VictorZisthus** [comment]
FINALLY. Geez.

**Comment by VictorZisthus** [comment]
In a mergeable state, but no changes to A3.

**Comment by VictorZisthus** [comment]
As I thought, needs to merge before I can change A3

**Comment by Heroman3003** [comment]
It's a bit weird that access changes weren't actually mentioned in the OP or title of the PR tbh.

**Pull request merged**
