### PR TITLE
Adds autohiss traits.

### PR DESCRIPTION
**Pull request by Cameron653**
Adds traits that allow you to hiss like a unathi or a tajaran.

- Adds Unathi Autohiss Trait
- Adds Tajaran Autohiss Trait

Might want to increase the amount of traits select able by 1 sometime in the future.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Tajaran and Unathi won't have this by default, right?

**Comment by Cameron653** [comment]
As far as I know, no. This is a trait that people can pick if they want to roll their S,X, or R's

**Comment by Yoshax** [comment]
Does this force you to do the thing, or allow you to use the toggle?

**Comment by Cameron653** [comment]
It allows you to use the toggle.

**Pull request merged**
