### PR TITLE
Polaris Sync

### PR DESCRIPTION
**Pull request by Arokha**
New map system? Well fine.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
I hope this doesn't bugger up gateway maps.

**Comment by Arokha** [comment]
Shouldn't! And if it does, we'll just fix it.

**Comment by SpadesNeil** [comment]
Before the next server update, can you either do https://github.com/VOREStation/VOREStation/issues/1063 or fix https://github.com/VOREStation/VOREStation/pull/758 ?

**Comment by Arokha** [comment]
I didn't realize there were issues. A friend told me they had problems doing transfers so I'm already mostly done rewriting that part of the vore panel and updating how it works.

**Comment by SpadesNeil** [comment]
Appreciated!

**Pull request merged**
