### PR TITLE
Fixes tram ignoring respawn timers

### LINKED ISSUE #3887: Post-cryopod respawn time inconsistant
#### Brief description of the issue
Using tram bump-cryo to despawn allows you to respawn immediately. Any other cryopod that you ghost out of requires you to wait all 5 minutes.

#### What you expected to happen
All cryopods being usable to not have respawn time

#### What actually happened
Only tram bumb-cryo does that

#### Steps to reproduce
- Bump-cryo tram and try respawning
- Ghost out of any other cryopod and try respawning

#### Code Revision
- ad18753b9d6bfd50b51846b726f025f1e781a75c

### PR DESCRIPTION
**Pull request by Heroman3003**
Cue in angry lynchmob

Fixes #3887

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Who said this wasn't intended?

**Comment by Heroman3003** [comment]
Because when using it the way you use other ghostpods (drag-and-click), it still has proper respawn time. The ability to leave round by bumping it is coded differently than normal cryopod object and did not apply timeofdeath properly, which allowed to skip respawn time.

**Comment by Very-Soft** [comment]
It's not intended, and sort of commonly abused by many people.

**Comment by TheFurryFeline** [comment]
With no repercussions by admins, however.

On Apr 8, 2019 04:31, "Casey" <notifications@github.com> wrote:

It's not intended, and sort of commonly abused by many people.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/VOREStation/VOREStation/pull/4955#issuecomment-480737025>,
or mute the thread

**Comment by Novacat** [comment]
Not intended. It gets fixed. Simples.

**Pull request merged**
