### PR TITLE
Some (smaller) .js files moved over to .tsx for interfaces

### PR DESCRIPTION
**Pull request by ItsSelis**
These will be broken down into seperate PRs, to at least not make a giant nightmare of conflict resolving for downstreams.

TypeScript does have advantages over regular Javascript (though in it's core it works the same: Javascript is valid inside of TypeScript).

TypeScript does give developers better debugging tools, especially since it can validate the Javascript (variable types and if variables even exist) and tell if there is an error ahead of time (aka: before it's sent to the browser and the interface gets an error).

### CODE REVIEW

**Comment by Very-Soft** [comment]
No idea what any of this actually does, and it touches lots of things

**Comment by ItsSelis** [comment]
> No idea what any of this actually does, and it touches lots of things

In general it just makes the javascript file to a typescript file. In general what is inside of them is the exact same content and behavior as before, it will not change how a UI looks like at all.

It does however introduce static typing of variables passed (mostly defined at the top) in order to throw an Error in Visual Studio Code if a variable is not handled or coded correctly (normally the browser, aka the tgui windows in-game, throws an error on runtime if the same error is made).

Though of course I can test the interfaces more intensely first to check them all for function.

**Comment by Cameron653** [comment]
This has been sitting for a long time. If Selis can confirm that testing has been performed and everything that is tested is working as expected, this should be good to merge with the next update.

**Comment by Cameron653** [comment]
Currently testing myself before I merge.

**Comment by Cameron653** [comment]
Agent card works https://i.imgur.com/fWnyelK.png

/infra works (but the device itself is FUBAR https://i.imgur.com/IN4Ok5k.png)
Casino prize works https://i.imgur.com/hgTVUSs.png

Colormate works https://i.imgur.com/QqEd88a.png

Ano utilizer works https://i.imgur.com/tLK1hxv.png

Given that everything I've tested so far works, I'm going to trust that the rest of it does.

**Pull request merged**
